const topic0_questions = [
  {
    "question": "What happens if you execute an INSERT statement using statement.executeQuery('INSERT INTO...')?",
    "shortAnswer": "The JDBC driver throws a java.sql.SQLException because executeQuery() requires the database to return a tabular ResultSet, which DML statements (INSERT/UPDATE/DELETE) do not produce.",
    "explanation": "Always use executeUpdate() for DML operations.",
    "hint": "Throws java.sql.SQLException because no ResultSet is returned.",
    "level": "Beginner",
    "codeExample": "stmt.executeQuery('INSERT...'); // Throws SQLException!"
  },
  {
    "question": "What does the boolean return value of statement.execute(sql) signify?",
    "shortAnswer": "It returns true if the first result generated by the SQL command is a ResultSet (which can be retrieved via stmt.getResultSet()), or false if it is an update count or there are no results (which can be retrieved via stmt.getUpdateCount()).",
    "explanation": "Enables handling dynamic SQL and stored procedures returning multiple results.",
    "hint": "Returns true if result is a ResultSet, false if update count.",
    "level": "Intermediate",
    "codeExample": "boolean isRS = stmt.execute(sql); if (isRS) ResultSet rs = stmt.getResultSet();"
  }
];

export default topic0_questions;
