const questions = [
  {
    question: "What does the `zip` command do?",
    shortAnswer: "Creates compressed ZIP archives containing one or more files or directories.",
    explanation: "`zip` packages files using DEFLATE compression (like gzip) but also stores directory structure and metadata.",
    hint: "Think of it as a cross-platform alternative to `tar` + `gzip`.",
    level: "basic",
    codeExample: "zip archive.zip file1.txt file2.txt"
  },
  {
    question: "How do you recursively zip a directory with its contents?",
    shortAnswer: "Use the `-r` option: `zip -r archive.zip directory/`",
    explanation: "Without `-r`, zip only stores the directory name itself, not the files inside.",
    hint: "Always include `-r` when archiving folders.",
    level: "basic",
    codeExample: "zip -r myfolder.zip myfolder/"
  },
  {
    question: "What is the difference between `zip` and `gzip`?",
    shortAnswer: "`zip` creates archives of multiple files/directories; `gzip` compresses single files only.",
    explanation: "`zip` includes a directory index; `gzip` is often used with `tar` for similar functionality.",
    hint: "`zip` is self-contained; `gzip` needs `tar` to archive directories.",
    level: "intermediate",
    codeExample: "zip -r archive.zip folder/   vs   tar -czf archive.tar.gz folder/"
  },
  {
    question: "How do you set the compression level in `zip`?",
    shortAnswer: "Use `-1` (fastest) to `-9` (best compression). Default is `-6`.",
    explanation: "Higher levels use more CPU but produce smaller archives.",
    hint: "`zip -9 archive.zip largefile` for maximum compression.",
    level: "basic",
    codeExample: "zip -1 fast.zip *.txt   # speed over size"
  },
  {
    question: "How can you add files to an existing ZIP archive?",
    shortAnswer: "Simply run `zip archive.zip newfile.txt`; it adds or replaces files.",
    explanation: "If the archive exists, `zip` updates it by default. Use `-u` to add only newer files.",
    hint: "`zip -u` updates only changed files.",
    level: "intermediate",
    codeExample: "zip archive.zip file.txt   # adds file.txt"
  },
  {
    question: "How do you exclude certain files from being zipped?",
    shortAnswer: "Use the `-x` option with a pattern: `zip -r archive.zip . -x \"*.log\"`",
    explanation: "Patterns are shell-style wildcards; use multiple `-x` patterns to exclude multiple types.",
    hint: "Quote patterns to prevent shell expansion.",
    level: "advanced",
    codeExample: "zip -r backup.zip mydir -x \"*.tmp\" \"*secret*\""
  },
  {
    question: "How can you create a password-protected ZIP archive?",
    shortAnswer: "Use the `-e` option: `zip -e secure.zip file.txt` (prompts for password).",
    explanation: "Encryption uses PKZIP weak crypto; for strong encryption, consider `7z` or `gpg`.",
    hint: "`-P password` provides password inline (insecure in scripts).",
    level: "intermediate",
    codeExample: "zip -e secret.zip data.csv   # prompts for password"
  },
  {
    question: "What does `unzip -l` do?",
    shortAnswer: "Lists contents of a ZIP archive without extracting.",
    explanation: "Useful to preview what's inside before decompressing.",
    hint: "`unzip -l archive.zip | less` for large archives.",
    level: "basic",
    codeExample: "unzip -l archive.zip"
  },
  {
    question: "How do you zip files and strip directory paths?",
    shortAnswer: "Use the `-j` (junk paths) option: `zip -j flat.zip folder/*.txt`",
    explanation: "All files are placed directly in the root of the archive, ignoring folder structure.",
    hint: "Be careful of filename collisions.",
    level: "intermediate",
    codeExample: "zip -j images.zip photos/*.jpg"
  },
  {
    question: "What is the difference between `zip -u` and `zip -f`?",
    shortAnswer: "`-u` updates only files that are newer; `-f` freshens (updates if file exists, does not add new files).",
    explanation: "`-f` is less common; `-u` is more useful for incremental backups.",
    hint: "`zip -u` adds new files; `-f` only updates existing.",
    level: "expert",
    codeExample: "zip -u backup.zip *.txt   # add any new or changed .txt"
  },
  {
    question: "How can you delete a file from a ZIP archive?",
    shortAnswer: "Use `zip -d archive.zip file_to_delete`",
    explanation: "The `-d` option removes specified files from the archive.",
    hint: "You can use wildcards: `zip -d archive.zip *.log`",
    level: "advanced",
    codeExample: "zip -d backup.zip outdated.txt"
  },
  {
    question: "Can `zip` compress files from stdin?",
    shortAnswer: "Yes, use `-@` to read list of files from stdin: `find . -name '*.txt' | zip archive.zip -@`",
    explanation: "This is useful when file list is generated by another command.",
    hint: "Especially useful with `find` to archive selected files.",
    level: "expert",
    codeExample: "find logs -name '*.log' -mtime +30 | zip old_logs.zip -@"
  },
  {
    question: "What is the maximum file size for a ZIP archive?",
    shortAnswer: "Traditional ZIP format has 4GB limit, but ZIP64 (used by modern zip) supports exabytes.",
    explanation: "Most current `zip` implementations auto-detect and use ZIP64 for large files.",
    hint: "Use `-fz` to force ZIP64 if needed.",
    level: "expert",
    codeExample: "zip large.zip hugefile.dat   # auto ZIP64 if >4GB"
  },
  {
    question: "How do you test the integrity of a ZIP archive?",
    shortAnswer: "Use `unzip -t archive.zip`",
    explanation: "Tests CRC checksums of all files without extracting.",
    hint: "Do this after transfers to ensure archive is not corrupted.",
    level: "intermediate",
    codeExample: "unzip -t backup.zip && echo 'OK'"
  },
  {
    question: "What is the difference between `zip` and `7z`?",
    shortAnswer: "`7z` (7-Zip) offers better compression (LZMA) and stronger encryption but is not as universally available.",
    explanation: "ZIP is more compatible; 7z is more efficient for archives.",
    hint: "Use `7z` for personal backups; use `zip` for sharing with others.",
    level: "advanced",
    codeExample: "7z a archive.7z folder/   # much smaller but needs 7z installed"
  },
  {
    question: "How can you zip a directory excluding a subdirectory?",
    shortAnswer: "`zip -r archive.zip . -x 'subdir/*'` from within the parent directory.",
    explanation: "The `-x` pattern excludes everything under subdir.",
    hint: "Use `-x` multiple times for multiple exclusions.",
    level: "advanced",
    codeExample: "zip -r project.zip project/ -x 'project/temp/*' 'project/*.log'"
  },
  {
    question: "Does `zip` preserve permissions and ownership?",
    shortAnswer: "Preserves Unix permissions (read/write/execute) but not ownership (UID/GID) or ACLs.",
    explanation: "When unzipped on Unix, files get the default umask of the user.",
    hint: "For full preservation, use `tar` or `pax`.",
    level: "advanced",
    codeExample: "ls -l extracted_file   # permissions from archive, owner is current user"
  },
  {
    question: "How do you create a split (multi-part) ZIP archive?",
    shortAnswer: "Use `-s` size: `zip -s 1m -r split.zip large_folder/`",
    explanation: "Creates `.z01`, `.z02`, ... files suitable for 1.44MB floppy or email limits.",
    hint: "To extract, concatenate or use `zip -F` fix.",
    level: "expert",
    codeExample: "zip -s 50m -r bigsplit.zip data/"
  },
  {
    question: "How can you see the compression ratio of files in a ZIP?",
    shortAnswer: "Use `unzip -l` or `zipinfo` to see packed and uncompressed sizes.",
    explanation: "`unzip -l` shows ratio; `zipinfo -v` gives detailed per-file info.",
    hint: "`zipinfo archive.zip | grep -E '^\-'` shows column headers.",
    level: "intermediate",
    codeExample: "unzip -l archive.zip | tail -1   # shows total ratio"
  },
  {
    question: "What is the purpose of the `-y` option in `zip`?",
    shortAnswer: "Stores symbolic links as links rather than following them.",
    explanation: "Without `-y`, zip follows symlinks and includes the target file (potentially duplicate).",
    hint: "Use `-y` to preserve symlinks for extraction on Unix.",
    level: "expert",
    codeExample: "zip -r -y link_archive.zip .   # stores symlinks as symlinks"
  },
  {
    question: "How do you zip only files that have changed since a certain date?",
    shortAnswer: "Use `find -newer` to generate list, then `zip -@`: `find . -newer reference -type f | zip update.zip -@`",
    explanation: "This creates an incremental backup of files newer than a timestamp file.",
    hint: "`touch reference` at last backup time.",
    level: "expert",
    codeExample: "find . -type f -newer last_backup.txt | zip incremental.zip -@"
  },
  {
    question: "What is the difference between `zip` and `jar`?",
    shortAnswer: "`jar` (Java Archive) is essentially a ZIP file with a `META-INF/MANIFEST.MF` entry.",
    explanation: "`jar` uses the same compression but adds metadata for Java classpath.",
    hint: "You can rename a `.jar` to `.zip` and view its contents.",
    level: "intermediate",
    codeExample: "jar cf my.jar *.class   # similar to zip"
  },
  {
    question: "How can you fix a corrupted ZIP archive?",
    shortAnswer: "Use `zip -F` or `zip -FF` to attempt recovery.",
    explanation: "`-F` tries to fix; `-FF` more aggressive (scan for local headers).",
    hint: "Often succeeds if only central directory is damaged.",
    level: "expert",
    codeExample: "zip -F corrupt.zip --out fixed.zip"
  },
  {
    question: "Why does `zip` create an archive with absolute paths?",
    shortAnswer: "If you specify absolute filenames, `zip` stores them as absolute (starts with '/').",
    explanation: "To avoid this, either `cd` to the directory first or use relative paths.",
    hint: "Use `-j` to junk paths or `cd` before zipping.",
    level: "intermediate",
    codeExample: "cd /home/user && zip -r backup.zip data/   # relative paths"
  },
  {
    question: "How do you create a ZIP archive that includes hidden files (dotfiles)?",
    shortAnswer: "Use shell glob that includes `.*`: `zip -r dot.zip .[^.]* *`",
    explanation: "Alternatively, `shopt -s dotglob` then `zip -r dot.zip *` in bash.",
    hint: "`zip` does not include dotfiles by default unless you specify them.",
    level: "advanced",
    codeExample: "zip -r hidden.zip .[^.]* *   # includes .config, .bashrc, etc."
  },
  {
    question: "What does the `-T` option do in `zip`?",
    shortAnswer: "Tests the integrity of the newly created archive before exiting.",
    explanation: "Equivalent to running `unzip -t` automatically.",
    hint: "Use to ensure archive was created correctly.",
    level: "advanced",
    codeExample: "zip -r -T backup.zip data/"
  },
  {
    question: "Can `zip` compress to other formats like .7z?",
    shortAnswer: "No, `zip` only produces `.zip` archives. For .7z, use `7z` command.",
    explanation: "`zip` is specific to PKZIP format.",
    hint: "Use `7z a archive.7z files` for other formats.",
    level: "basic",
    codeExample: "7z a archive.7z folder/   # not zip"
  },
  {
    question: "How do you zip a large number of files without hitting 'Argument list too long'?",
    shortAnswer: "Use `find` with `-print0` and `xargs -0` or `zip -@`.",
    explanation: "Example: `find . -name '*.log' -print0 | xargs -0 zip logs.zip`",
    hint: "`zip -@` is simplest: `find ... -print | zip archive.zip -@`.",
    level: "expert",
    codeExample: "find . -type f | zip archive.zip -@"
  },
  {
    question: "What is the difference between `zip -r` and `zip -r -D`?",
    shortAnswer: "`-D` excludes directories from the archive (only stores files).",
    explanation: "Empty directories are not stored. Useful for source tarballs.",
    hint: "Often combined with `-r` to still recurse into but not store empty dirs.",
    level: "advanced",
    codeExample: "zip -r -D project.zip src/"
  },
  {
    question: "How can you view the compression method used for files in a ZIP?",
    shortAnswer: "Use `zipinfo -v archive.zip` or `unzip -Z archive.zip`.",
    explanation: "It will show 'deflated' (compressed) or 'stored' (no compression).",
    hint: "`unzip -Z archive.zip | grep method`",
    level: "expert",
    codeExample: "unzip -Z archive.zip"
  },
  {
    question: "Why does `zip` sometimes store files with 0% compression?",
    shortAnswer: "If the file is already compressed (JPEG, PNG, ZIP) or very small, `zip` stores without compression.",
    explanation: "Compression would increase size due to overhead; `zip` intelligent enough to store.",
    hint: "Use `-0` to force store (no compression) for already compressed files.",
    level: "advanced",
    codeExample: "zip -0 photo.zip *.jpg   # just store, no compression"
  }
];

export default questions;