const questions = [
  {
    id: 1,
    question: "What are the core steps in the TLS 1.3 1-RTT Handshake Protocol?",
    shortAnswer: "1. ClientHello (with KeyShare proposal); 2. ServerHello (with Server KeyShare); 3. Ephemeral ECDHE Shared Secret computation & HKDF derivation; 4. EncryptedExtensions + Encrypted Certificate + CertificateVerify; 5. Finished messages; 6. Application Data.",
    explanation: "TLS 1.3 establishes an encrypted connection in a single round trip (1-RTT). The client anticipates the server's preferred curve (e.g., X25519) and sends its public key share in the very first packet. The server responds with its matching key share, immediately deriving handshake encryption keys before sending its certificate.",
    hint: "ClientHello with KeyShare ➔ ServerHello with KeyShare ➔ Derived Keys ➔ Encrypted Certificate ➔ Finished.",
    level: "Basic",
    codeExample: `// TLS 1.3 1-RTT Handshake Message Sequence:
// Client ──[ClientHello + KeyShare(X25519)]──> Server
// Client <──[ServerHello + KeyShare + {EncryptedExtensions + Certificate + CertificateVerify + Finished}]── Server
// Client ──[{Finished}]──> Server
// ➔ Encrypted Application Data Flows!`
  },
  {
    id: 2,
    question: "What is the 'KeyShare' extension in TLS 1.3 and how does it eliminate a full round trip of negotiation?",
    shortAnswer: "The client generates an ephemeral (EC)DHE private key and transmits its public key share directly inside the initial `ClientHello` message for its preferred curves (like X25519 or P-256), allowing the server to compute the shared secret immediately upon receiving packet 1.",
    explanation: "In TLS 1.2, the client first asked which key exchange algorithm the server supported, waiting for `ServerKeyExchange` before generating keys (2-RTT). In TLS 1.3, the client speculatively provides public keys for top curves in `ClientHello`, allowing instant 1-RTT secret agreement.",
    hint: "Sending your half of the secret key in the very first greeting message instead of asking first.",
    level: "Moderate",
    codeExample: `// KeyShare Extension in ClientHello:
// Extension: key_share (0x0033)
//   NamedGroup: x25519 (0x001d)
//   Key Exchange Length: 32 Bytes
//   Key Exchange Data: 5a 1f 88 bc 3d 44 ... (Client Public Key)`
  },
  {
    id: 3,
    question: "What is a 'HelloRetryRequest' in TLS 1.3 and when does a 2-RTT fallback occur?",
    shortAnswer: "If the client's `KeyShare` extension did not include a curve supported by the server, the server sends a `HelloRetryRequest` specifying its required group (e.g., P-384), causing the client to send a new `ClientHello` with the correct KeyShare in 2-RTT.",
    explanation: "Because the client guesses which curve the server prefers (typically X25519 or P-256), rare mismatches can happen if a server only accepts P-384. The `HelloRetryRequest` tells the client: 'I support TLS 1.3, but please resend your KeyShare using secp384r1.'",
    hint: "A server saying: 'I want to connect, but please use curve P-384 instead of X25519.'",
    level: "Moderate",
    codeExample: `// HelloRetryRequest Flow (2-RTT Fallback):
// Client ──[ClientHello (KeyShare: X25519)]──> Server
// Client <──[HelloRetryRequest (Selected Group: secp384r1)]── Server
// Client ──[ClientHello (KeyShare: secp384r1)]──> Server
// Client <──[ServerHello + KeyShare + EncryptedCert + Finished]── Server`
  },
  {
    id: 4,
    question: "At what exact moment does packet encryption begin during the TLS 1.3 handshake?",
    shortAnswer: "Immediately after the `ServerHello` message; as soon as both parties have exchanged `KeyShare` public parameters, they compute the ECDHE shared secret and derive Handshake Traffic Keys, encrypting all subsequent messages (`EncryptedExtensions`, `Certificate`, `CertificateVerify`, `Finished`).",
    explanation: "In TLS 1.2, the certificate and handshake negotiation were plaintext. In TLS 1.3, unencrypted traffic ceases after `ServerHello`. The server derives `server_handshake_traffic_secret` and encrypts its own certificate before transmitting it over the wire.",
    hint: "Encryption begins right after ServerHello; the certificate is completely encrypted.",
    level: "Basic",
    codeExample: `// Encryption Boundary:
// [UNENCRYPTED ON WIRE] ➔ ClientHello, ServerHello
// ─────────────────── [CRYPTOGRAPHIC BOUNDARY] ───────────────────
// [ENCRYPTED ON WIRE]   ➔ EncryptedExtensions, Certificate, CertificateVerify, Finished, AppData`
  },
  {
    id: 5,
    question: "What is the function of the 'CertificateVerify' message in the TLS 1.3 handshake?",
    shortAnswer: "It contains a digital signature generated by the server's private key over a cryptographic hash of all preceding handshake messages, proving that the server actually owns the private key corresponding to the public key in the X.509 certificate.",
    explanation: "Anyone can intercept and forward a public certificate. The `CertificateVerify` message provides mathematical proof of identity: the server signs the transcript hash with its private key (using RSA-PSS or ECDSA). The client uses the public key from the certificate to verify the signature.",
    hint: "A digital signature proving that the server really owns the private key for the certificate it showed.",
    level: "Moderate",
    codeExample: `// CertificateVerify Signature Formula:
// Context = "TLS 1.3, server CertificateVerify"
// Transcript_Hash = SHA256(ClientHello || ServerHello || EncryptedExtensions || Certificate)
// Signature = Sign_PrivateKey(Context || Transcript_Hash)`
  },
  {
    id: 6,
    question: "What is the 'HKDF Key Schedule' (RFC 5869) and what are its three sequential master stages in TLS 1.3?",
    shortAnswer: "1. Early Secret (derived from PSK or 0 for 0-RTT); 2. Handshake Secret (derived from ECDHE shared secret for encrypting handshake); 3. Master Secret (derived for generating bi-directional application traffic keys).",
    explanation: "HKDF replaces the older, ad-hoc TLS PRF. It operates in two phases: `HKDF-Extract` (concentrating entropy into a uniform Pseudorandom Key [PRK]) and `HKDF-Expand-Label` (generating cryptographically isolated keys for client write, server write, IVs, and resumption).",
    hint: "Early Secret ➔ Handshake Secret ➔ Master Secret.",
    level: "Expert",
    codeExample: `// HKDF Key Schedule Flow:
// 1. Early Secret     = HKDF-Extract(0, PSK)
// 2. Handshake Secret = HKDF-Extract(Derived_Early, ECDHE_Shared_Secret)
//    ├──> client_handshake_key & iv
//    └──> server_handshake_key & iv
// 3. Master Secret    = HKDF-Extract(Derived_Handshake, 0)
//    ├──> client_application_key & iv
//    └──> server_application_key & iv`
  },
  {
    id: 7,
    question: "Why does TLS 1.3 generate separate independent traffic keys for Client-to-Server and Server-to-Client communication?",
    shortAnswer: "To prevent reflection attacks, eliminate cryptographic keystream race conditions, and guarantee that compromising one directional key does not allow an attacker to forge traffic in the opposite direction.",
    explanation: "TLS 1.3 derives `client_application_traffic_secret_0` and `server_application_traffic_secret_0`. The client uses `client_application_key` to encrypt outbound HTTP requests, while the server uses `server_application_key` to encrypt HTTP responses. Each direction maintains its own independent 64-bit sequence counter.",
    hint: "Each direction has its own private key and counter so traffic never collides or gets mixed up.",
    level: "Moderate",
    codeExample: `// Independent Directional Keys:
// Client ──(Encrypted with client_app_key + Seq #0)──> Server
// Server ──(Encrypted with server_app_key + Seq #0)──> Client`
  },
  {
    id: 8,
    question: "How does the 'Finished' message verify that no Man-in-the-Middle tampering occurred during the handshake?",
    shortAnswer: "It computes an HMAC (`verify_data`) over the complete transcript hash of every handshake message exchanged; if an attacker altered even a single bit in `ClientHello` or cipher proposals, the computed HMACs will not match and the connection aborts.",
    explanation: "The `Finished` message is authenticated using a dedicated `finished_key` derived via HKDF. Both the client and server calculate `verify_data = HMAC(finished_key, Transcript_Hash)`. This guarantees that both peers have an identical, untampered view of the entire handshake negotiation.",
    hint: "A final cryptographic seal that verifies both computers heard the exact same conversation without any alterations.",
    level: "Basic",
    codeExample: `// Finished HMAC Calculation:
// verify_data = HMAC-SHA256(finished_key, SHA256(ClientHello || ServerHello ... || CertificateVerify))`
  },
  {
    id: 9,
    question: "What is the architectural difference between 'One-Way TLS' and 'Mutual TLS' (mTLS)?",
    shortAnswer: "One-Way TLS authenticates only the server to the client (client remains anonymous at the TLS layer); Mutual TLS (mTLS) requires both the server AND the client to present X.509 digital certificates and `CertificateVerify` signatures.",
    explanation: "In One-Way TLS, the client checks the server's certificate, but user identity is handled later via passwords/cookies. In mTLS, the server transmits a `CertificateRequest` message. The client must present a valid client certificate issued by an approved CA, providing hardware-level identity proof for APIs and microservices.",
    hint: "One-Way TLS: You check the server's ID; mTLS: You and the server check each other's ID.",
    level: "Basic",
    codeExample: `// Mutual TLS (mTLS) Handshake Addition:
// Server sends: CertificateRequest(Supported CAs, Signature Algorithms)
// Client responds: Certificate(Client X.509) + CertificateVerify(Client Signature)`
  },
  {
    id: 10,
    question: "Why is 'Mutual TLS' (mTLS) widely considered mandatory for Zero Trust microservices architectures?",
    shortAnswer: "mTLS provides cryptographically verified service-to-service identity, prevents unauthorized container spoofing inside Kubernetes clusters, and enforces encryption across all internal east-west network traffic.",
    explanation: "In modern cloud-native architectures, the internal network is assumed to be hostile. Standard perimeter firewalls cannot stop an attacker who breaches a single pod. mTLS ensures that every single microservice (e.g., Payment Service to Billing DB) independently authenticates every incoming API connection.",
    hint: "Assuming the internal network is compromised and requiring every microservice to show cryptographic ID for every API call.",
    level: "Moderate",
    codeExample: `// Kubernetes Istio mTLS Policy:
// apiVersion: security.istio.io/v1beta1
// kind: PeerAuthentication
// metadata:
//   name: default
// spec:
//   mtls:
//     mode: STRICT`
  },
  {
    id: 11,
    question: "How does the cipher suite naming convention differ between TLS 1.2 and TLS 1.3?",
    shortAnswer: "TLS 1.2 tied Key Exchange, Authentication, Encryption, and MAC into a single complex string (e.g., `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384`); TLS 1.3 specifies ONLY the symmetric AEAD algorithm and PRF hash (e.g., `TLS_AES_256_GCM_SHA384`).",
    explanation: "In TLS 1.3, key exchange (ECDHE with X25519) and authentication (RSA-PSS or ECDSA) are negotiated via modular extensions (`supported_groups` and `signature_algorithms`). This decoupled design eliminated thousands of cipher combinations, simplifying configuration and auditing.",
    hint: "TLS 1.2 listed 4 things in the name; TLS 1.3 lists only the encryption algorithm and the hash.",
    level: "Basic",
    codeExample: `// Cipher Suite Naming Comparison:
// TLS 1.2: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (Combines KeyEx + Auth + Cipher + Hash)
// TLS 1.3: TLS_AES_256_GCM_SHA384               (Symmetric AEAD Cipher + PRF Hash ONLY)`
  },
  {
    id: 12,
    question: "What is 'Application-Layer Protocol Negotiation' (ALPN) and how is it used during the TLS handshake?",
    shortAnswer: "An extension in `ClientHello` where the client lists supported application protocols (e.g., `h2` for HTTP/2, `http/1.1`, `h3` for HTTP/3); the server selects the protocol in `EncryptedExtensions`, avoiding extra application round trips.",
    explanation: "Without ALPN (RFC 7301), after completing the TLS handshake, the client would have to send an unauthenticated HTTP upgrade request to switch to HTTP/2. ALPN negotiates HTTP/2 directly during the TLS handshake, saving an entire round trip of latency.",
    hint: "Agreeing whether to speak HTTP/1.1 or high-speed HTTP/2 while the security handshake is taking place.",
    level: "Moderate",
    codeExample: `// ALPN Extension in ClientHello:
// Extension: application_layer_protocol_negotiation (0x0010)
//   Protocols:
//     - h2 (HTTP/2 over TLS)
//     - http/1.1`
  },
  {
    id: 13,
    question: "Why was 'RSA-PSS' mandated in TLS 1.3, completely replacing legacy 'RSA PKCS#1 v1.5' signatures?",
    shortAnswer: "RSA-PSS (Probabilistic Signature Scheme) includes randomized salting and formal mathematical security proofs, eliminating deterministic padding flaws that allowed Bleichenbacher signature forgery attacks.",
    explanation: "RSA PKCS#1 v1.5 is deterministic, meaning the same message and key always produce the exact same signature. Historical implementation bugs in PKCS#1 v1.5 parsers allowed attackers to forge signatures for arbitrary domains. RSA-PSS is provably secure in the Random Oracle Model.",
    hint: "RSA-PSS adds randomized salt so mathematical padding forgery is impossible.",
    level: "Expert",
    codeExample: `// TLS 1.3 Signature Algorithms Extension:
// signature_algorithms:
//   - rsa_pss_rsae_sha256 (0x0804)
//   - rsa_pss_rsae_sha384 (0x0805)
//   - ecdsa_secp256r1_sha256 (0x0403)
//   - ed25519 (0x0807)`
  },
  {
    id: 14,
    question: "What is the 'KeyUpdate' message in TLS 1.3 and how does it replace legacy 'Renegotiation'?",
    shortAnswer: "A simple 1-byte message sent by either peer during an active connection that derives new traffic keys from the current keys via HKDF without interrupting data transfer or performing a heavy asymmetric handshake.",
    explanation: "In TLS 1.2, changing keys required a full re-handshake (Renegotiation), which was vulnerable to injection attacks (CVE-2009-3555) and caused high CPU spikes. `KeyUpdate` in TLS 1.3 rolls keys forward seamlessly (`traffic_secret_N+1 = HKDF-Expand-Label(traffic_secret_N, 'traffic upd')`).",
    hint: "A fast, 1-byte instruction that rolls encryption keys forward without stopping the conversation.",
    level: "Moderate",
    codeExample: `// TLS 1.3 KeyUpdate Record:
// Content Type: Handshake (22)
// Handshake Type: KeyUpdate (24)
// Request Update: update_requested (1)`
  },
  {
    id: 15,
    question: "What causes the common TLS error 'SSL_ERROR_BAD_MAC_READ' and how is it diagnosed?",
    shortAnswer: "A corrupted packet, altered ciphertext payload, or miscalculated sequence counter causing the AEAD authentication tag verification to fail during decryption; usually caused by bad network hardware, MTU truncation, or Man-in-the-Middle tampering.",
    explanation: "AEAD ciphers (AES-GCM / Poly1305) compute a 128-bit authentication tag over the ciphertext and associated data (including the sequence number). If an intermediate router flips a single bit or truncates the frame, the receiver's computed tag does not match, triggering `BAD_MAC_READ`.",
    hint: "A corrupted packet whose tamper-proof seal failed when the receiver tried to unlock it.",
    level: "Moderate",
    codeExample: `// OpenSSL Handshake Error Output:
// 140283402450816:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:s3_pkt.c:535:`
  },
  {
    id: 16,
    question: "How does system clock skew cause catastrophic TLS handshake failures with 'CERT_DATE_INVALID'?",
    shortAnswer: "X.509 digital certificates have strict `NotBefore` and `NotAfter` validity timestamps; if a client device's clock is inaccurate (skewed into the past or future by even a few hours), the certificate is rejected as expired or not yet valid.",
    explanation: "TLS certificate verification strictly compares the client's current system time against the certificate's validity window. If an IoT device in Barrackpore boots without an NTP time synchronization and its clock defaults to 1970 or 2020, every TLS connection will fail immediately.",
    hint: "If your computer's date is wrong, it will think the website's security certificate is expired or from the future.",
    level: "Basic",
    codeExample: `// Clock Skew Verification:
// Certificate Validity: NotBefore: Jan 1 2026, NotAfter: Jan 1 2027
// Client System Time : Dec 15 2024 (Clock skewed!)
// Result ➔ Handshake Aborted: Certificate is NOT YET VALID!`
  },
  {
    id: 17,
    question: "What is 'Server Name Indication' (SNI) and why is it essential for virtual hosting on HTTPS servers?",
    shortAnswer: "An extension in `ClientHello` that specifies the target hostname the client wants to reach, allowing a reverse proxy hosting hundreds of websites on a single public IP to serve the correct SSL certificate.",
    explanation: "Because TLS handshakes occur before HTTP headers are sent, without SNI, the server would not know which website the user requested (`bank.gov.in` vs `tax.gov.in`) and could only serve one default certificate. SNI announces the domain name early in `ClientHello`.",
    hint: "Telling the apartment building doorman which resident you are visiting before he unlocks the door.",
    level: "Basic",
    codeExample: `// SNI Extension in ClientHello:
// Extension: server_name (0x0000)
//   Server Name list:
//     HostName: treasury.barrackpore.gov.in`
  },
  {
    id: 18,
    question: "How does 'Curve25519' (X25519) provide superior performance and side-channel resistance compared to NIST curves in TLS 1.3?",
    shortAnswer: "X25519 uses a Montgomery curve with simple arithmetic that executes in constant time on all CPUs, eliminating data-dependent timing branch leaks and computing key exchanges 2x faster than NIST P-256.",
    explanation: "Designed by Daniel J. Bernstein, Curve25519 avoids complex point-addition formulas and modular inversion algorithms that created side-channel cache-timing vulnerabilities in older Weierstrass curves. It is the default, most widely deployed key exchange curve in TLS 1.3.",
    hint: "Ultra-fast, constant-time mathematics that is mathematically immune to timing attacks.",
    level: "Expert",
    codeExample: `// X25519 Key Exchange Performance:
// X25519 (Curve25519) : ~15,000 key exchanges / second / CPU core (Constant Time)
// NIST P-256           : ~7,500 key exchanges / second / CPU core`
  },
  {
    id: 19,
    question: "How do you test a Mutual TLS (mTLS) server endpoint using the cURL CLI?",
    shortAnswer: "Run `curl -v --cert client.crt --key client.key --cacert ca.crt https://api.fintech.barrackpore.gov.in` to supply the client certificate, private key, and trusted CA bundle.",
    explanation: "This command transmits `client.crt` in response to the server's `CertificateRequest`, generates the `CertificateVerify` signature using `client.key`, and validates the server's certificate against `ca.crt`.",
    hint: "Using curl with --cert, --key, and --cacert flags to test two-way authenticated APIs.",
    level: "Basic",
    codeExample: `// cURL mTLS Command:
$ curl -v --cert client_cert.pem --key client_key.pem --cacert internal_ca.pem https://api.fintech.barrackpore.gov.in/v1/payout`
  },
  {
    id: 20,
    question: "What is 'Session Ticket Resumption' in TLS 1.3 and how does it differ from legacy TLS 1.2 Session IDs?",
    shortAnswer: "In TLS 1.3, the server sends a `NewSessionTicket` after the handshake containing an encrypted state blob (PSK); the client presents this ticket in the `pre_shared_key` extension of subsequent `ClientHello` messages to resume without asymmetric math.",
    explanation: "Legacy TLS 1.2 Session IDs required servers to store state tables in memory for millions of users, creating server memory bottlenecks. Session Tickets (RFC 5077) store the encrypted state on the client side, allowing stateless load balancers to resume sessions seamlessly.",
    hint: "The server gives the client a sealed cryptographic ticket to hold so the server doesn't have to remember millions of sessions.",
    level: "Moderate",
    codeExample: `// TLS 1.3 NewSessionTicket Message:
// Handshake Type: NewSessionTicket (4)
// Ticket Lifetime: 86400 seconds (24 Hours)
// Ticket: 4A 1F 88 BC ... (Encrypted Master Secret Blob)`
  },
  {
    id: 21,
    question: "Why did TLS 1.3 remove the 'ChangeCipherSpec' message and how is it used only for middlebox compatibility?",
    shortAnswer: "In pure TLS 1.3, key transitions occur implicitly based on message sequence; however, legacy firewalls and middleboxes drop connections if they do not see a `ChangeCipherSpec` record, so TLS 1.3 sends a dummy 1-byte CCS record for compatibility.",
    explanation: "Middleboxes deployed across corporate networks between 2000 and 2015 expected a strict TLS 1.2 state machine. To prevent these 'ossified' middleboxes from dropping connections, RFC 8446 Appendix D specifies sending a dummy `0x01` ChangeCipherSpec record that is ignored by modern TLS 1.3 parsers.",
    hint: "A dummy 1-byte message sent to trick old corporate firewalls into not breaking the connection.",
    level: "Expert",
    codeExample: `// TLS 1.3 Middlebox Compatibility Mode:
// Client sends dummy record: [Content Type: ChangeCipherSpec (20)] [Length: 1] [Payload: 0x01]`
  },
  {
    id: 22,
    question: "What is 'Ed25519' (RFC 8032) and why is it increasingly preferred over ECDSA for TLS 1.3 signatures?",
    shortAnswer: "Ed25519 is an Edwards-curve digital signature algorithm that generates signatures in constant time without requiring a per-message random nonce $k$, eliminating catastrophic private key leakage bugs like the Sony PS3 ECDSA flaw.",
    explanation: "In standard ECDSA, if the random number generator repeats or biases the random nonce $k$ even slightly across two signatures, an attacker can mathematically extract the private key instantly. Ed25519 derives $k$ deterministically from a hash of the private key and message, making nonce reuse impossible.",
    hint: "A modern digital signature algorithm that does not rely on random numbers, preventing key leakage bugs.",
    level: "Expert",
    codeExample: `// Ed25519 Deterministic Nonce Derivation:
// r = SHA-512(Private_Key_Hash || Message) ➔ 100% Deterministic! Zero risk of nonce collision.`
  },
  {
    id: 23,
    question: "How do you trace the complete step-by-step TLS 1.3 handshake packet flow using the OpenSSL CLI?",
    shortAnswer: "Run `openssl s_client -connect <host>:443 -tls1_3 -msg -tlsextdebug` to output every handshake record, extension payload, and key share in human-readable hex.",
    explanation: "The `-msg` flag prints the raw bytes and message types of every TLS record exchanged (`ClientHello`, `ServerHello`, `EncryptedExtensions`, `Certificate`, `Finished`). The `-tlsextdebug` flag displays detailed extension parsing.",
    hint: "Using openssl with -msg and -tlsextdebug to see every single handshake message in the terminal.",
    level: "Basic",
    codeExample: `// OpenSSL Handshake Trace Output:
$ openssl s_client -connect bank.barrackpore.gov.in:443 -tls1_3 -msg
// >>> TLS 1.3 Handshake [length 014a], ClientHello
// <<< TLS 1.3 Handshake [length 007a], ServerHello
// <<< TLS 1.3 Handshake [length 001a], EncryptedExtensions
// <<< TLS 1.3 Handshake [length 045a], Certificate
// <<< TLS 1.3 Handshake [length 010a], CertificateVerify
// <<< TLS 1.3 Handshake [length 0034], Finished`
  },
  {
    id: 24,
    question: "What is 'Encrypted Client Hello' (ECH) and how does it prevent network observers from seeing the SNI domain?",
    shortAnswer: "ECH encrypts the entire `ClientHello` (including the SNI extension) using a public key fetched from the target domain's DNS HTTPS/SVCB resource record, wrapping it inside an outer dummy ClientHello.",
    explanation: "Standard SNI exposes which website you visit in plaintext. With ECH, your browser asks DNS for the domain's ECH public key over DNS-over-HTTPS (DoH), encrypts the inner `ClientHello` (`bank-treasury.internal`), and places it inside an outer generic `ClientHello` (`cloudflare.com`). Intermediate ISPs see only the generic front domain.",
    hint: "Hiding the destination name on the outside of the package so your internet provider cannot see what website you visit.",
    level: "Expert",
    codeExample: `// Encrypted Client Hello (ECH) Structure:
// Outer ClientHello : SNI = "public-gateway.com" (Visible to ISP)
// Inner ClientHello : Encrypted payload containing REAL SNI = "treasury.barrackpore.gov.in"`
  },
  {
    id: 25,
    question: "What is 'OCSP Stapling' (Certificate Status Request) and how does it accelerate the TLS handshake?",
    shortAnswer: "The web server queries the CA's Online Certificate Status Protocol (OCSP) server periodically, caches the digitally signed revocation response, and 'staples' it directly inside the `Certificate` message during the handshake, saving the client a separate HTTP lookup.",
    explanation: "Without OCSP stapling, when a user visits a website, their browser must pause the handshake and open an HTTP connection to the Certificate Authority's OCSP server to verify if the certificate was revoked, adding 100ms+ of latency. Stapling delivers the CA-signed proof directly in the handshake.",
    hint: "The server pre-fetches its own signed proof of certificate validity and gives it directly to your browser.",
    level: "Moderate",
    codeExample: `// OCSP Stapling in NGINX:
// ssl_stapling on;
// ssl_stapling_verify on;
// ssl_trusted_certificate /etc/ssl/ca_chain.pem;`
  },
  {
    id: 26,
    question: "How does 'Post-Quantum Hybrid Key Exchange' (X25519Kyber768) fit into the TLS 1.3 `key_share` extension?",
    shortAnswer: "The client generates both a 32-byte classical X25519 key and a 1184-byte Kyber-768 lattice public key, combining them into a single 1216-byte key share entry; the server responds with matching hybrid shares, deriving a quantum-proof shared secret.",
    explanation: "NIST standardized Kyber (ML-KEM) for quantum-resistant key encapsulation. In hybrid mode (RFC draft-ietf-tls-hybrid-design), the final shared secret is $S = \\text{HKDF}(\\text{ECDH Secret} \\parallel \\text{Kyber Decapsulated Secret})$, ensuring security even if one of the two algorithms is broken in the future.",
    hint: "Combining classical elliptic curve keys and quantum lattice keys together inside the standard KeyShare extension.",
    level: "Expert",
    codeExample: `// Hybrid Post-Quantum Key Share (Group 0x6399):
// key_share_data = [ 32-byte X25519 Public Key ] + [ 1184-byte Kyber-768 Public Key ]`
  },
  {
    id: 27,
    question: "What is the role of 'Transcript Hash' in the TLS 1.3 handshake state machine?",
    shortAnswer: "A running cryptographic hash (SHA-256 or SHA-384) updated with every handshake message sent or received; it is fed into HKDF label expansions, `CertificateVerify` signatures, and `Finished` verify_data to guarantee state synchronization.",
    explanation: "The transcript hash binds every handshake parameter together. If an attacker modifies a single byte in `ClientHello`, the transcript hash changes, causing the server's `CertificateVerify` signature or `Finished` HMAC to fail verification at the client.",
    hint: "A running mathematical summary of everything said during the handshake.",
    level: "Moderate",
    codeExample: `// Transcript Hash Accumulator:
// H0 = SHA256(ClientHello)
// H1 = SHA256(ClientHello || ServerHello)
// H2 = SHA256(ClientHello || ServerHello || EncryptedExtensions || Certificate)`
  },
  {
    id: 28,
    question: "How do you capture and decrypt TLS 1.3 traffic in Wireshark for debugging using an 'SSLKEYLOGFILE'?",
    shortAnswer: "Set the environment variable `SSLKEYLOGFILE=/path/to/keys.log`, launch your browser or cURL, and configure Wireshark under `Preferences ➔ Protocols ➔ TLS ➔ (Pre)-Master-Secret log filename` to point to that log file.",
    explanation: "Because TLS 1.3 enforces Perfect Forward Secrecy, Wireshark cannot decrypt traffic using the server's private key. The `SSLKEYLOGFILE` logs the ephemeral traffic secrets (`CLIENT_HANDSHAKE_TRAFFIC_SECRET`, `CLIENT_TRAFFIC_SECRET_0`), allowing Wireshark to decrypt the packets for debugging.",
    hint: "Logging ephemeral session keys to a text file so Wireshark can decrypt the traffic for debugging.",
    level: "Moderate",
    codeExample: `// Exporting Key Log File for Wireshark Decryption:
$ export SSLKEYLOGFILE=~/tls_secrets.log
$ curl https://bank.barrackpore.gov.in
// Wireshark reads ~/tls_secrets.log and decrypts all TLS 1.3 packets in real time!`
  },
  {
    id: 29,
    question: "What is the difference between 'Ephemerality' in TLS 1.3 ECDHE vs 'Static Pre-Shared Keys' (PSK)?",
    shortAnswer: "ECDHE generates new public/private key pairs for every single connection, providing Perfect Forward Secrecy; Static PSK uses a shared secret configured beforehand, providing instant 0-RTT connection without asymmetric math but lacking forward secrecy unless combined with ECDHE.",
    explanation: "TLS 1.3 supports pure PSK (used in constrained IoT networks) and hybrid PSK-with-ECDHE (`psk_dhe_ke`). In enterprise networks, hybrid PSK-DHE is preferred because it combines fast resumption with robust Perfect Forward Secrecy.",
    hint: "ECDHE makes new keys every time (PFS); PSK uses a pre-shared secret (Fast).",
    level: "Moderate",
    codeExample: `// TLS 1.3 PSK Key Exchange Modes:
// psk_ke     : Pure PSK (Fast, No Asymmetric Math, No PFS)
// psk_dhe_ke : PSK + Ephemeral ECDHE (Fast Resumption + Perfect Forward Secrecy!)`
  },
  {
    id: 30,
    question: "What is the definitive production checklist for configuring and verifying TLS 1.3 handshakes?",
    shortAnswer: "1. Enforce TLS 1.3 with 1-RTT KeyShare proposals (X25519); 2. Enable modern AEAD suites (`TLS_AES_256_GCM_SHA384`); 3. Enforce RSA-PSS or ECDSA digital signatures; 4. Deploy OCSP Stapling; 5. Enforce mTLS for internal microservices; 6. Validate via `openssl s_client -trace`.",
    explanation: "This six-point checklist ensures optimal cryptographic strength, sub-second handshake latency, and full compliance under CERT-In, RBI, and PCI-DSS 4.0 regulations.",
    hint: "TLS 1.3 + X25519 KeyShare + AEAD Ciphers + RSA-PSS + OCSP Stapling + mTLS for APIs.",
    level: "Basic",
    codeExample: `// Master TLS 1.3 Handshake Checklist:
// [✔] Protocol      : TLS 1.3 (RFC 8446) Mandated
// [✔] Key Exchange  : X25519 (Curve25519) + P-256
// [✔] Bulk Cipher   : AES-256-GCM / ChaCha20-Poly1305
// [✔] Signatures    : RSA-PSS (3072B+) or ECDSA (P-256)
// [✔] Optimization  : OCSP Stapling + ALPN (h2)
// [✔] Zero Trust    : Strict Mutual TLS (mTLS) on Internal APIs`
  }
];

export default questions;
