// topic13_files/topic13_questions.js

const questions = [
  {
    question: "What is the primary mechanism of multi-column grouping in SQL (`GROUP BY col1, col2`)?",
    shortAnswer: "MySQL creates composite group keys `(col1_value, col2_value)`; records are grouped into the same bucket only if they share identical values for *both* specified columns.",
    explanation: "Multi-column grouping partitions rows into distinct multi-dimensional sub-categories, forming a Cartesian subset of distinct column combinations.",
    hint: "Think of a composite key where both column values must match identically.",
    level: "basic"
  },
  {
    question: "If a table has 4 distinct cities and 3 distinct course streams, what is the theoretical maximum number of groups generated by `GROUP BY city, course`?",
    shortAnswer: "12 groups (4 × 3 = 12 combinations in the Cartesian product).",
    explanation: "The maximum number of groups is the product of distinct cardinalities of the grouping columns, assuming every combination exists in data.",
    hint: "Multiply the distinct values of column 1 by column 2 (4 * 3).",
    level: "basic"
  },
  {
    question: "Does the order of columns in the `GROUP BY` clause change the aggregated metric values?",
    shortAnswer: "NO. Aggregation metrics (SUM, COUNT, AVG) remain identical regardless of whether you write `GROUP BY city, course` or `GROUP BY course, city`.",
    explanation: "Group partitioning is commutative in terms of mathematical aggregations; however, column order affects default index utilization and implicit sorting in older MySQL versions.",
    hint: "The mathematical buckets and aggregates remain the same, but index matching requires prefix alignment.",
    level: "basic"
  },
  {
    question: "How can you group customer orders by both year and month in MySQL?",
    shortAnswer: "`GROUP BY YEAR(order_date), MONTH(order_date)` or `GROUP BY YEAR(order_date), MONTHNAME(order_date)`.",
    explanation: "Grouping by multiple date extraction functions creates temporal monthly trends across different years.",
    hint: "Use YEAR(date_col) and MONTH(date_col) together in GROUP BY.",
    level: "basic"
  },
  {
    question: "Why should you use `GROUP BY YEAR(order_date), MONTH(order_date)` instead of only `GROUP BY MONTH(order_date)` for multi-year data?",
    shortAnswer: "Grouping only by `MONTH(order_date)` conflates data from January 2024, January 2025, and January 2026 into a single January bucket.",
    explanation: "To preserve temporal separation between different calendar years, the year component must be included in the grouping criteria.",
    hint: "Without YEAR, January from all years combines into one single group.",
    level: "basic"
  },
  {
    question: "What is MySQL Error 1055, and why does multi-column grouping often trigger it?",
    shortAnswer: "Error 1055 occurs when `ONLY_FULL_GROUP_BY` is enabled and a `SELECT` column is neither included in `GROUP BY` nor wrapped in an aggregate function.",
    explanation: "SQL standards require deterministic results; any column in SELECT must be functionally dependent or explicitly aggregated.",
    hint: "Every unaggregated SELECT column must be present in GROUP BY.",
    level: "moderate"
  },
  {
    question: "How do you group text data case-insensitively when the database collation is binary or case-sensitive?",
    shortAnswer: "`GROUP BY UPPER(TRIM(city_name))` or `GROUP BY LOWER(city_name)`.",
    explanation: "Applying UPPER() or LOWER() normalizes string casing so that 'Kolkata', 'kolkata', and 'KOLKATA' collapse into one group.",
    hint: "Wrap the string column in UPPER() or LOWER() in GROUP BY.",
    level: "moderate"
  },
  {
    question: "Can you group data into custom numerical brackets or histogram bins in SQL?",
    shortAnswer: "YES, using mathematical expressions like `GROUP BY FLOOR(fee_inr / 5000) * 5000` or `CASE` statements.",
    explanation: "Integer division/multiplication or FLOOR creates discrete numerical intervals (e.g., ₹0-4999, ₹5000-9999).",
    hint: "Use FLOOR(col / interval) * interval to create bracket buckets.",
    level: "moderate"
  },
  {
    question: "How can you group student exam scores into grade tiers (Distinction, First Class, Pass)?",
    shortAnswer: "`GROUP BY CASE WHEN marks >= 75 THEN 'Distinction' WHEN marks >= 60 THEN 'First Class' ELSE 'Pass' END`.",
    explanation: "Searched CASE expressions can be placed directly in the GROUP BY clause to categorize continuous metrics into categorical groups.",
    hint: "Place the entire CASE WHEN expression inside the GROUP BY clause.",
    level: "moderate"
  },
  {
    question: "Can you use column aliases in the `GROUP BY` clause in MySQL?",
    shortAnswer: "YES. MySQL supports grouping by aliases defined in the `SELECT` list (e.g. `SELECT YEAR(order_date) AS yr GROUP BY yr`).",
    explanation: "MySQL extends standard SQL to allow aliases in GROUP BY and HAVING, although standard SQL technically evaluates GROUP BY before SELECT.",
    hint: "MySQL specifically allows aliases in GROUP BY, though standard SQL does not.",
    level: "moderate"
  },
  {
    question: "What is the performance implication of grouping by expressions like `GROUP BY UPPER(city)` without an expression index?",
    shortAnswer: "MySQL cannot use a standard B-Tree index on `city`, forcing a Full Table Scan and temporary filesort (`Using temporary; Using filesort`).",
    explanation: "Functions applied on indexed columns invalidate standard B-tree lookups unless a functional/expression index is created.",
    hint: "Applying a function to a column prevents normal index seeking.",
    level: "moderate"
  },
  {
    question: "How do you create an expression index in MySQL 8.0+ to optimize `GROUP BY UPPER(city)`?",
    shortAnswer: "`CREATE INDEX idx_upper_city ON students((UPPER(city)));`",
    explanation: "MySQL 8.0+ supports functional (expression) indexes enclosed in double parentheses, allowing the engine to index the computed value directly.",
    hint: "Use CREATE INDEX ... ON table((expression)). Double parentheses are required.",
    level: "expert"
  },
  {
    question: "How does a composite index `(centre_city, course_stream)` optimize a multi-column `GROUP BY centre_city, course_stream` query?",
    shortAnswer: "It provides a pre-sorted B-Tree index structure, allowing MySQL to perform a Tight Index Scan without creating temporary tables or sorting in memory.",
    explanation: "When grouping columns match the leading columns of a composite index in order, MySQL reads group boundaries directly off the B-tree leaf nodes.",
    hint: "Index provides pre-ordered data, eliminating temporary tables and filesort.",
    level: "expert"
  },
  {
    question: "If a composite index exists on `(colA, colB, colC)`, will `GROUP BY colB, colC` use the index for grouping?",
    shortAnswer: "NO, because it violates the Leftmost Prefix Rule (colA is missing from the leading position).",
    explanation: "B-Trees require the leftmost prefix to navigate index keys without a full index scan.",
    hint: "The leftmost prefix rule requires colA to be part of the filter or grouping.",
    level: "expert"
  },
  {
    question: "How does MySQL treat `NULL` values when grouping by multiple columns?",
    shortAnswer: "All `(NULL, NULL)` or `(col1_val, NULL)` rows are treated as equal and placed into a single shared group bucket for that combination.",
    explanation: "In SQL grouping semantics, NULL equals NULL; distinct composite combinations containing NULL form their own discrete groups.",
    hint: "Rows with NULL in composite columns are grouped together into one bucket.",
    level: "moderate"
  },
  {
    question: "What is the difference between `GROUP BY col1, col2` and `GROUP BY col1` followed by subqueries?",
    shortAnswer: "`GROUP BY col1, col2` computes all sub-category combinations in a single relational scan, whereas nested subqueries require multiple passes.",
    explanation: "Direct multi-column grouping is vastly more efficient and scalable than iterative subqueries.",
    hint: "Multi-column grouping partitions both dimensions simultaneously in one pass.",
    level: "basic"
  },
  {
    question: "How can you concatenate all student names belonging to each `(centre_city, course_stream)` pair?",
    shortAnswer: "Use `GROUP_CONCAT(student_name ORDER BY student_name SEPARATOR ', ')` in the `SELECT` list with `GROUP BY centre_city, course_stream`.",
    explanation: "GROUP_CONCAT aggregates strings within each composite group slice.",
    hint: "Use GROUP_CONCAT(name) along with multi-column GROUP BY.",
    level: "moderate"
  },
  {
    question: "How do you filter out multi-column groups that have fewer than 5 students and less than ₹50,000 in collected fees?",
    shortAnswer: "`GROUP BY centre_city, course_stream HAVING COUNT(*) >= 5 AND SUM(fee_inr) >= 50000;`",
    explanation: "The HAVING clause operates on the composite groups after both multi-column partitioning and aggregation are complete.",
    hint: "Use HAVING with COUNT(*) and SUM(fee_inr) after GROUP BY.",
    level: "basic"
  },
  {
    question: "Can you group by a boolean expression in MySQL (e.g. `GROUP BY is_passed, is_placed`)?",
    shortAnswer: "YES. MySQL evaluates boolean expressions as 1 (True) or 0 (False), resulting in up to 4 composite binary groups.",
    explanation: "Booleans in MySQL are aliases for TINYINT(1) and form standard grouping keys (0,0), (0,1), (1,0), (1,1).",
    hint: "Booleans evaluate to 0 or 1 and group into composite binary combinations.",
    level: "moderate"
  },
  {
    question: "What query calculates the total revenue and student count for each teacher per academic quarter?",
    shortAnswer: "`SELECT teacher_name, YEAR(enroll_date) AS yr, QUARTER(enroll_date) AS qtr, COUNT(*) AS students, SUM(fee) AS revenue FROM enrollments GROUP BY teacher_name, YEAR(enroll_date), QUARTER(enroll_date);`",
    explanation: "Groups across three dimensions: teacher identity, calendar year, and calendar quarter.",
    hint: "GROUP BY teacher_name, YEAR(date), QUARTER(date).",
    level: "moderate"
  },
  {
    question: "What is the risk of using positional column numbers in `GROUP BY 1, 2` in production?",
    shortAnswer: "If someone changes the column order in `SELECT`, the query silently groups by completely different columns, corrupting business reports.",
    explanation: "Positional grouping is fragile and non-descriptive; explicit column names or aliases should always be used in production.",
    hint: "Modifying the SELECT column order will silently alter which columns are grouped.",
    level: "moderate"
  },
  {
    question: "How can you group records by day of the week and hour of the day to detect server peak load times?",
    shortAnswer: "`GROUP BY DAYNAME(log_timestamp), HOUR(log_timestamp)`",
    explanation: "Extracts day name and hour to build a 7×24 activity heatmap matrix.",
    hint: "Use DAYNAME(timestamp) and HOUR(timestamp) in GROUP BY.",
    level: "moderate"
  },
  {
    question: "What is the difference between `GROUP BY DATE(created_at)` and `GROUP BY YEAR(created_at), MONTH(created_at), DAY(created_at)`?",
    shortAnswer: "Both group by calendar day, but `DATE(created_at)` returns a single DATE value while three separate functions produce three numeric components.",
    explanation: "DATE() is cleaner and outputs 'YYYY-MM-DD', while three separate columns allow independent sorting and hierarchical display.",
    hint: "DATE() produces one date column; the multi-column format produces three separate integers.",
    level: "moderate"
  },
  {
    question: "Why should you filter active students with `WHERE status = 'ACTIVE'` instead of `HAVING status = 'ACTIVE'` when doing multi-column grouping?",
    shortAnswer: "`WHERE` filters out inactive rows before grouping begins, drastically reducing memory usage, whereas `HAVING` forces MySQL to group inactive rows unnecessarily.",
    explanation: "Row-level filtering before aggregation preserves CPU cycles and memory by feeding fewer rows into the group partitioning algorithm.",
    hint: "WHERE reduces the row count before grouping; HAVING groups everything first.",
    level: "basic"
  },
  {
    question: "How do you group sales data by product category and price range tier simultaneously?",
    shortAnswer: "`GROUP BY category_id, CASE WHEN price < 1000 THEN 'Budget' WHEN price < 5000 THEN 'Mid' ELSE 'Premium' END;`",
    explanation: "Combines a standard relational foreign key with an inline CASE expression for multi-dimensional segment analysis.",
    hint: "Group by category_id and a CASE expression on price.",
    level: "moderate"
  },
  {
    question: "What is the execution order of `FROM`, `WHERE`, `GROUP BY`, `HAVING`, `SELECT`, and `ORDER BY` when multi-column grouping is involved?",
    shortAnswer: "1. FROM -> 2. WHERE -> 3. GROUP BY (multi-col) -> 4. HAVING -> 5. SELECT -> 6. ORDER BY -> 7. LIMIT.",
    explanation: "Multi-column grouping happens at stage 3, followed by group filtering at stage 4 and projection at stage 5.",
    hint: "WHERE runs before GROUP BY; HAVING runs after GROUP BY; SELECT runs after HAVING.",
    level: "basic"
  },
  {
    question: "How does `ORDER BY` interact with multi-column `GROUP BY` in MySQL 8.0?",
    shortAnswer: "MySQL 8.0 does NOT implicitly sort grouped results; you must explicitly specify `ORDER BY col1, col2` if ordered output is required.",
    explanation: "Earlier MySQL versions had implicit sorting for GROUP BY, which was deprecated and removed in MySQL 8.0 to improve query performance.",
    hint: "MySQL 8.0 does not sort groups automatically; always specify ORDER BY explicitly.",
    level: "moderate"
  },
  {
    question: "Can you group by a subquery expression in MySQL?",
    shortAnswer: "YES, scalar subqueries that return a single value per row can be used in the `GROUP BY` clause or grouped via alias.",
    explanation: "Any deterministic expression yielding a scalar value can act as a grouping dimension in MySQL.",
    hint: "Scalar subqueries producing single values per row can be grouped.",
    level: "expert"
  },
  {
    question: "What index would you build to optimize `SELECT dept, role, COUNT(*), SUM(salary) FROM employees WHERE status = 'ACTIVE' GROUP BY dept, role;`?",
    shortAnswer: "A composite index on `(status, dept, role, salary)`.",
    explanation: "This creates a covering index: `status` satisfies the equality WHERE filter, `dept, role` satisfy the GROUP BY without sorting, and `salary` provides the aggregate value without touching data pages.",
    hint: "Put equality WHERE column first, followed by GROUP BY columns, then aggregated column.",
    level: "expert"
  },
  {
    question: "What is the primary difference between multi-column `GROUP BY col1, col2` and `GROUP BY col1, col2 WITH ROLLUP`?",
    shortAnswer: "`GROUP BY col1, col2` generates only the finest grain composite groups, while `WITH ROLLUP` adds hierarchical subtotal rows and a grand total row.",
    explanation: "WITH ROLLUP computes super-aggregate rows across hierarchical levels (e.g., each city-course, then city total, then grand total).",
    hint: "Standard GROUP BY creates only leaf groups; WITH ROLLUP appends subtotals and grand totals.",
    level: "expert"
  }
];

export default questions;
