const questions = [
  {
    question: "What is the main advantage of Criteria API over HQL?",
    shortAnswer: "Type‑safe, dynamic query construction without string concatenation.",
    explanation: "Criteria API is ideal when you need to conditionally add WHERE clauses, JOINs, or ORDER BY based on user input. It avoids SQL injection and is refactor‑friendly.",
    hint: "Try building a search form with 5 optional filters – Criteria API keeps the code clean.",
    level: "basic",
    codeExample: "cq.where(predicates.toArray(new Predicate[0]));"
  },
  {
    question: "How to write a JOIN FETCH using JPA Criteria?",
    shortAnswer: "Use `Root.fetch()` method with JoinType.",
    explanation: "`root.fetch(\"courses\", JoinType.LEFT);` loads the association eagerly. For a join that also allows filtering, use `Join<...> join = root.join(\"courses\");` and then fetch.",
    hint: "`.fetch()` does not return a Join object; use `.join()` if you need to add conditions on the joined table.",
    level: "intermediate",
    codeExample: "root.fetch(\"courses\", JoinType.LEFT);"
  },
  {
    question: "What is the difference between `root.get(\"field\")` and `root.get(\"association\").get(\"field\")`?",
    shortAnswer: "The latter requires joining the association first, or it will fail.",
    explanation: "If `address` is a ManyToOne property, `root.get(\"address\").get(\"city\")` is invalid unless you have already joined `address` (e.g., `Join<Student, Address> addressJoin = root.join(\"address\")`).",
    hint: "Always join before navigating to a related entity's property.",
    level: "intermediate",
    codeExample: "Join<Student, Address> addr = root.join(\"address\"); cq.where(cb.equal(addr.get(\"city\"), \"Barrackpore\"));"
  },
  {
    question: "How do you create a DTO projection with HQL?",
    shortAnswer: "Use `SELECT NEW com.school.StudentDTO(s.id, s.name) FROM Student s`.",
    explanation: "The DTO class must have a matching constructor. This avoids loading full entities, reduces memory, and improves performance for read‑only queries.",
    hint: "Make sure the DTO constructor argument order and types match the SELECT clause.",
    level: "basic",
    codeExample: "List<StudentDTO> dtos = session.createQuery(\"SELECT NEW StudentDTO(s.id, s.name) FROM Student s\", StudentDTO.class).list();"
  },
  {
    question: "Can you use subqueries in the SELECT clause of HQL?",
    shortAnswer: "Yes, HQL supports subqueries in SELECT, WHERE, and FROM clauses (limited in FROM).",
    explanation: "Example: `SELECT s.name, (SELECT COUNT(c) FROM s.courses c) FROM Student s`. The subquery must return a single scalar value. Avoid correlated subqueries for large datasets.",
    hint: "If performance suffers, rewrite as a JOIN with GROUP BY.",
    level: "advanced",
    codeExample: "SELECT s.id, (SELECT MAX(c.credits) FROM Course c WHERE c.student.id = s.id) FROM Student s"
  },
  {
    question: "How to paginate with Criteria API?",
    shortAnswer: "Use `setFirstResult(offset)` and `setMaxResults(limit)` on the TypedQuery.",
    explanation: "After building the CriteriaQuery and obtaining the query object, call `query.setFirstResult(start).setMaxResults(pageSize)` before executing. Works the same as HQL.",
    hint: "For huge offset, consider keyset pagination for better performance.",
    level: "intermediate",
    codeExample: "em.createQuery(cq).setFirstResult(20).setMaxResults(10).getResultList();"
  },
  {
    question: "What is the JPA static metamodel and how does it help?",
    shortAnswer: "Generated `*_` classes provide type‑safe access to entity attributes in Criteria API.",
    explanation: "Instead of strings like `\"name\"`, you use `Student_.name`. This avoids typos and makes refactoring safe. Generated by annotation processor (e.g., Hibernate JPA Metamodel Generator).",
    hint: "Add the metamodel generator dependency and compile – you'll see classes like `Student_` in target/generated-sources.",
    level: "advanced",
    codeExample: "cq.where(cb.equal(root.get(Student_.name), \"Tuhina\"));"
  },
  // ... continue to 30 questions (full file will be provided in final answer)
];
export default questions;