const questions = [
  {
    question: "What is star topology?",
    shortAnswer: "A network topology where all devices connect to a central hub or switch.",
    explanation: "Each device has a dedicated connection to the central device, forming a star pattern.",
    hint: "Think of a star with a central point and rays going outward.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the central device in star topology?",
    shortAnswer: "A hub or switch (modern networks use switches).",
    explanation: "The central device manages traffic between connected devices.",
    hint: "The center of the star.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the difference between a hub and a switch?",
    shortAnswer: "A hub broadcasts to all ports; a switch forwards only to the intended port.",
    explanation: "Switches are smarter, eliminate collisions, and provide better performance.",
    hint: "One is smart, the other is simple.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the advantage of star topology over bus?",
    shortAnswer: "A single device failure doesn't affect others; bus does.",
    explanation: "Star provides fault isolation and easier troubleshooting.",
    hint: "One broken branch doesn't affect the others.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the main disadvantage of star topology?",
    shortAnswer: "The central switch is a single point of failure.",
    explanation: "If the switch fails, the entire network goes down.",
    hint: "All eggs in one basket.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Why is star topology the most common today?",
    shortAnswer: "Reliability, scalability, and ease of management.",
    explanation: "Star topology works well with modern switches and supports high speeds.",
    hint: "The best combination of features.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What type of cable is typically used in star topology?",
    shortAnswer: "Unshielded Twisted Pair (UTP) cables like Cat5e or Cat6.",
    explanation: "These cables use RJ-45 connectors and support up to 100m lengths.",
    hint: "The cable you plug into your computer.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the maximum length of a Cat6 cable in star topology?",
    shortAnswer: "100 meters.",
    explanation: "Beyond 100m, signal attenuation requires a repeater or fiber.",
    hint: "The standard limit for Ethernet.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Can star topology be wireless?",
    shortAnswer: "Yes, wireless access points act as the central device.",
    explanation: "Wireless clients connect to the access point (AP) in a star-like fashion.",
    hint: "Wi-Fi networks are a form of star topology.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What happens when a device is disconnected from a star network?",
    shortAnswer: "Only that device loses connectivity; others remain unaffected.",
    explanation: "Each device has its own dedicated path to the switch.",
    hint: "Remove one leaf from the star, the rest stay.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a collision domain in a switched star topology?",
    shortAnswer: "Each switch port is its own collision domain.",
    explanation: "With a switch, full-duplex operation eliminates collisions.",
    hint: "A private lane for each device.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the benefit of using a managed switch in star topology?",
    shortAnswer: "Allows VLANs, traffic monitoring, and QoS.",
    explanation: "Managed switches provide advanced features for network management.",
    hint: "A smart, configurable switch.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do you add a new device to a star network?",
    shortAnswer: "Connect it to an available port on the switch.",
    explanation: "The switch automatically detects and configures the new device.",
    hint: "Plug and play.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of VLANs in star topology?",
    shortAnswer: "VLANs logically segment a physical star network for security and performance.",
    explanation: "VLANs allow different groups to be isolated on the same switch.",
    hint: "Virtual separation.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is link aggregation in star topology?",
    shortAnswer: "Combining multiple switch ports to increase bandwidth and redundancy.",
    explanation: "LACP allows grouping of physical links into a logical bundle.",
    hint: "More lanes for faster traffic.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do you secure a star topology network?",
    shortAnswer: "Use port security, VLANs, and switch access controls.",
    explanation: "Prevent unauthorized devices from connecting to switch ports.",
    hint: "Lock the doors (ports).",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between a star topology and a tree topology?",
    shortAnswer: "Star has one central switch; tree has multiple switches in a hierarchy.",
    explanation: "Tree topology combines multiple stars in a hierarchical structure.",
    hint: "A single star vs. a family tree of stars.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the impact of using a lower-quality switch in star topology?",
    shortAnswer: "Bottlenecks, dropped packets, and slower network performance.",
    explanation: "A slow or overloaded switch cannot handle traffic efficiently.",
    hint: "The heart of the network must be strong.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does a switch learn the MAC addresses of connected devices?",
    shortAnswer: "Through the process of MAC address learning.",
    explanation: "The switch reads the source MAC address of incoming frames and associates it with the port.",
    hint: "The switch builds a table of who is where.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the purpose of STP (Spanning Tree Protocol) in star topology?",
    shortAnswer: "STP prevents loops when redundant links exist between switches.",
    explanation: "Redundant links improve reliability but require STP to prevent broadcast storms.",
    hint: "Prevents loops.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a leaf-spine architecture in networking?",
    shortAnswer: "A modern data center topology that uses multiple switches in a two-layer mesh.",
    explanation: "It's an evolution of star topology for high-performance data centers.",
    hint: "Star topology on steroids.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does QoS work in a star topology?",
    shortAnswer: "QoS prioritizes traffic based on application, ensuring critical data gets bandwidth.",
    explanation: "Managed switches support QoS through traffic classification and scheduling.",
    hint: "VIP lane for important data.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of a DHCP server in star topology?",
    shortAnswer: "A DHCP server automatically assigns IP addresses to devices connecting to the network.",
    explanation: "This eliminates manual IP configuration.",
    hint: "Auto IP assignment.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do you troubleshoot a device not connecting in star topology?",
    shortAnswer: "Check cable, switch port, NIC, and IP configuration.",
    explanation: "Isolate the issue by testing each component in the path.",
    hint: "Follow the path from device to switch.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of a network tap in star topology?",
    shortAnswer: "A network tap provides a copy of traffic for monitoring and analysis.",
    explanation: "Used with SPAN ports or inline taps for network visibility.",
    hint: "A look at the traffic.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the bandwidth capacity of a modern star topology?",
    shortAnswer: "Up to 10 Gbps per port on enterprise switches, with 40Gbps and 100Gbps uplinks.",
    explanation: "Speeds depend on switch and cabling standards.",
    hint: "Very fast, getting faster.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of fiber optics in star topology?",
    shortAnswer: "Fiber is used for longer distances and higher speeds, often as uplinks between switches.",
    explanation: "Fiber connects floors or buildings in a star-like design.",
    hint: "Long-distance links.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do you plan for scalability in star topology?",
    shortAnswer: "Leave spare ports, plan for switch stacking, and design for VLAN expansion.",
    explanation: "Scalability requires capacity planning and modular design.",
    hint: "Think ahead.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the impact of broadcast storms in star topology?",
    shortAnswer: "Broadcast storms can overwhelm the switch and network.",
    explanation: "VLANs and storm control prevent broadcast storms.",
    hint: "Too much broadcast traffic.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the future of star topology with software-defined networking?",
    shortAnswer: "SDN makes star topology more programmable and dynamic.",
    explanation: "Centralized control allows intelligent traffic management.",
    hint: "Smart networks.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;