// topic3_questions.js
// 30 FAQs on "Unary and Binary Operators" – basic to expert.

const questions = [
  {
    question: "What is a unary operator?",
    shortAnswer: "A unary operator works with only one operand.",
    explanation: "Examples include `+`, `-`, `++`, `--`, `!`, and `~`. They perform operations on a single value.",
    hint: "Look for operators that appear next to one value.",
    level: "basic",
    codeExample: "int a = -5; // '-' is unary",
  },
  {
    question: "What is a binary operator?",
    shortAnswer: "A binary operator works with two operands.",
    explanation: "Most operators are binary: arithmetic, relational, logical, assignment, etc.",
    hint: "They appear between two operands.",
    level: "basic",
    codeExample: "int sum = a + b; // '+' is binary",
  },
  {
    question: "What is the difference between prefix and postfix increment?",
    shortAnswer: "Prefix (`++x`) increments first then returns the new value; postfix (`x++`) returns the old value then increments.",
    explanation: "This affects the result when used in expressions.",
    hint: "Prefix: change then use; Postfix: use then change.",
    level: "intermediate",
    codeExample: "int x=5; int a = ++x; // a=6, x=6\nint y=5; int b = y++; // b=5, y=6",
  },
  {
    question: "What does the `!` operator do?",
    shortAnswer: "It negates a boolean value (true becomes false, false becomes true).",
    explanation: "It is the logical NOT operator.",
    hint: "Use it to invert a condition.",
    level: "basic",
    codeExample: "boolean isOpen = false;\nboolean isClosed = !isOpen; // true",
  },
  {
    question: "What is the unary minus operator?",
    shortAnswer: "It negates a numeric value (makes it negative).",
    explanation: "For example, `-5` gives -5. It does not change the sign of a variable unless assigned.",
    hint: "It's the same as multiplying by -1.",
    level: "basic",
    codeExample: "int negative = -5;",
  },
  {
    question: "What is the bitwise complement operator `~`?",
    shortAnswer: "It flips all bits of an integer operand (one's complement).",
    explanation: "For example, `~0b1010` (10) gives `0b11110101...` (two's complement representation).",
    hint: "It's a unary operator used in low‑level bit manipulation.",
    level: "advanced",
    codeExample: "int result = ~5;",
  },
  {
    question: "What are binary arithmetic operators?",
    shortAnswer: "`+`, `-`, `*`, `/`, `%` that work on two numeric operands.",
    explanation: "They perform addition, subtraction, multiplication, division, and modulo.",
    hint: "These are the most common operators.",
    level: "basic",
    codeExample: "int result = 10 + 3;",
  },
  {
    question: "What are binary relational operators?",
    shortAnswer: "Operators that compare two values and return a boolean: `==`, `!=`, `>`, `<`, `>=`, `<=`.",
    explanation: "Used in conditions and assertions.",
    hint: "They ask a question about the relationship between two values.",
    level: "basic",
    codeExample: "if (age >= 18) { }",
  },
  {
    question: "What is the difference between `&` and `&&`?",
    shortAnswer: "`&` is bitwise AND (or non‑short‑circuit logical AND when operands are boolean), while `&&` is short‑circuit logical AND.",
    explanation: "`&` always evaluates both sides; `&&` may skip the second operand if the first is false.",
    hint: "Use `&&` for conditions to avoid side effects.",
    level: "intermediate",
    codeExample: "if (obj != null && obj.isValid()) // safe",
  },
  {
    question: "What is a compound assignment operator?",
    shortAnswer: "Operators like `+=`, `-=`, `*=`, `/=` that combine an arithmetic operation with assignment.",
    explanation: "They are binary operators with a side effect (assignment).",
    hint: "They make the code shorter.",
    level: "intermediate",
    codeExample: "int x = 5; x += 3; // x = 8",
  },
  {
    question: "Can unary operators be applied to all types?",
    shortAnswer: "No, `!` works only on boolean, `~` only on integer types, `++` and `--` only on numeric variables.",
    explanation: "Each unary operator has specific type requirements.",
    hint: "Check the Java language specification for type compatibility.",
    level: "intermediate",
    codeExample: "// !true works, !5 is invalid",
  },
  {
    question: "What is the precedence of unary vs binary operators?",
    shortAnswer: "Unary operators have higher precedence than binary operators (except for assignment).",
    explanation: "For example, `-x + y` is parsed as `(-x) + y`.",
    hint: "Unary operators bind tighter.",
    level: "intermediate",
    codeExample: "int result = -5 + 3; // (-5) + 3 = -2",
  },
  {
    question: "How does Java evaluate `a++ + ++a`?",
    shortAnswer: "It depends on the order of evaluation; Java evaluates left to right, but it's confusing and should be avoided.",
    explanation: "The expression is considered side‑effect heavy and not recommended for production code.",
    hint: "Avoid such expressions.",
    level: "advanced",
    codeExample: "// Not recommended",
  },
  {
    question: "What is the ternary operator?",
    shortAnswer: "It's the only ternary operator in Java: `condition ? expr1 : expr2`.",
    explanation: "It takes three operands and returns one of two values based on the condition.",
    hint: "It's a shorthand for if‑else.",
    level: "intermediate",
    codeExample: "int max = (a > b) ? a : b;",
  },
  {
    question: "Is the assignment operator `=` unary or binary?",
    shortAnswer: "Binary, because it requires two operands: the left‑hand side (variable) and right‑hand side (value).",
    explanation: "It's a binary operator with a side effect.",
    hint: "It's a binary operator.",
    level: "basic",
    codeExample: "int x = 5; // '=' is binary",
  },
  {
    question: "What is the `instanceof` operator's arity?",
    shortAnswer: "Binary – it takes an object and a type.",
    explanation: "It checks if the object is an instance of that class or interface.",
    hint: "It's a type‑checking operator.",
    level: "intermediate",
    codeExample: "if (obj instanceof String) { }",
  },
  {
    question: "Can unary operators be overloaded?",
    shortAnswer: "Java does not allow operator overloading, so unary operators cannot be customised.",
    explanation: "Only the `+` operator is overloaded for string concatenation.",
    hint: "Java keeps it simple.",
    level: "advanced",
    codeExample: "// Not applicable",
  },
  {
    question: "What is the effect of using `++` in a loop?",
    shortAnswer: "It increments the loop control variable, typically advancing the loop.",
    explanation: "Used in `for` loops: `for (int i = 0; i < n; i++)`.",
    hint: "It's the standard way to move to the next element.",
    level: "basic",
    codeExample: "for (int i = 0; i < 10; i++) { }",
  },
  {
    question: "What are the common mistakes with `++` and `--`?",
    shortAnswer: "Misplacing prefix/postfix can change the logic. Also, using them inside complex expressions reduces readability.",
    explanation: "Many bugs arise from misusing these operators.",
    hint: "Use them in isolation when possible.",
    level: "intermediate",
    codeExample: "int i = 0; while (i++ < 5) { } // tricky",
  },
  {
    question: "What is the `+` operator when used with strings?",
    shortAnswer: "It performs string concatenation, a binary operator that works on two strings (or a string and another type).",
    explanation: "Example: `\"Hello\" + \"World\"` gives `\"HelloWorld\"`.",
    hint: "It's overloaded.",
    level: "basic",
    codeExample: "String message = \"Count: \" + 5;",
  },
  {
    question: "What is the difference between `-` as unary and binary?",
    shortAnswer: "Unary `-` negates a single value; binary `-` subtracts two values.",
    explanation: "The context determines which version is used.",
    hint: "If it has one operand, it's unary; if two, binary.",
    level: "basic",
    codeExample: "int a = -5; // unary\nint b = 10 - 3; // binary",
  },
  {
    question: "Can you use `++` on a double?",
    shortAnswer: "Yes, `++` can be applied to floating‑point variables (it increments by 1.0).",
    explanation: "It works on any numeric type.",
    hint: "It's not limited to integers.",
    level: "intermediate",
    codeExample: "double d = 5.5; d++; // d becomes 6.5",
  },
  {
    question: "What is the precedence of unary vs assignment?",
    shortAnswer: "Unary operators have higher precedence than assignment.",
    explanation: "So `x = -y` is parsed as `x = (-y)`.",
    hint: "Assignment is the lowest precedence.",
    level: "intermediate",
    codeExample: "int y = 3; int x = -y; // '-' first, then '='",
  },
  {
    question: "What is the role of binary operators in conditionals?",
    shortAnswer: "Binary operators like `&&`, `||`, and relational operators produce boolean results used in `if`, `while`, etc.",
    explanation: "They combine or compare values to make decisions.",
    hint: "They are the core of decision making.",
    level: "basic",
    codeExample: "if (temperature > 30 && humidity < 80) { }",
  },
  {
    question: "What is the side effect of `++` and `--`?",
    shortAnswer: "They modify the variable they operate on, which is a side effect beyond returning a value.",
    explanation: "This can be useful but needs care.",
    hint: "Side effects can change state.",
    level: "intermediate",
    codeExample: "int i = 0; int j = i++; // i becomes 1",
  },
  {
    question: "Can you apply `!` to a non‑boolean?",
    shortAnswer: "No, `!` requires a boolean operand.",
    explanation: "It's the logical NOT operator, so it only works on booleans.",
    hint: "Use `~` for bitwise complement on integers.",
    level: "basic",
    codeExample: "// !5 is invalid",
  },
  {
    question: "What is the `~` operator used for?",
    shortAnswer: "It's the bitwise complement, flipping all bits of an integer.",
    explanation: "It yields the one's complement of the value.",
    hint: "Used in low‑level bit operations.",
    level: "advanced",
    codeExample: "int result = ~0b1010;",
  },
  {
    question: "What is the difference between `||` and `|`?",
    shortAnswer: "`||` is short‑circuit logical OR; `|` is bitwise OR (or non‑short‑circuit OR when applied to booleans).",
    explanation: "Prefer `||` for boolean conditions.",
    hint: "`||` may skip evaluation of the right operand.",
    level: "intermediate",
    codeExample: "if (a > 5 || b < 10) { } // short‑circuit",
  },
  {
    question: "How does the compiler differentiate unary and binary `+`?",
    shortAnswer: "Based on the number of operands. If `+` has one operand, it's unary plus; if two, it's binary addition.",
    explanation: "Unary plus is rarely used and does nothing for numbers.",
    hint: "It's the same symbol but overloaded by arity.",
    level: "intermediate",
    codeExample: "int a = +5; // unary plus",
  },
  {
    question: "What is the associativity of unary operators?",
    shortAnswer: "Unary operators are right‑associative, meaning `- -x` is parsed as `-(-x)`.",
    explanation: "This is rare but useful in some contexts.",
    hint: "They bind from right to left.",
    level: "advanced",
    codeExample: "int a = 5; int b = - -a; // b = 5",
  },
  {
    question: "What are the performance implications of unary vs binary?",
    shortAnswer: "Unary operators are generally very fast, but side effects like `++` can have overhead in multithreading.",
    explanation: "In single‑threaded code, the difference is negligible.",
    hint: "Focus on clarity over micro‑optimisation.",
    level: "advanced",
    codeExample: "Not applicable",
  },
];

export default questions;