// topic11_questions.js
// 30 FAQs on "Rules for Infix to Postfix Conversion" – basic to expert.

const questions = [
  {
    question: "What is the first rule of infix to postfix conversion?",
    shortAnswer: "Operands (variables, constants) are immediately appended to the output.",
    explanation: "This is the simplest rule – operands retain their order and are written directly to the postfix expression.",
    hint: "Think about what happens to numbers and variables.",
    level: "basic",
    codeExample: "Infix: A+B → A and B go to output directly.",
  },
  {
    question: "How are left parentheses handled in the conversion?",
    shortAnswer: "Left parentheses '(' are pushed onto the stack.",
    explanation: "They mark the start of a sub‑expression and are treated as a low‑precedence marker.",
    hint: "They are pushed, not output.",
    level: "basic",
    codeExample: "Infix: (A+B) → '(' is pushed.",
  },
  {
    question: "How are right parentheses handled?",
    shortAnswer: "When a ')' is encountered, pop operators from the stack and output them until a '(' is found; then discard the '('.",
    explanation: "This ensures the sub‑expression inside parentheses is fully converted.",
    hint: "Operators inside are popped and output.",
    level: "basic",
    codeExample: "Infix: (A+B) → A B +",
  },
  {
    question: "What happens when an operator is encountered?",
    shortAnswer: "Pop operators of higher or equal precedence from the stack (if left‑associative) and append them to output; then push the current operator.",
    explanation: "This maintains the correct precedence order in the postfix expression.",
    hint: "Higher precedence operators come out first.",
    level: "intermediate",
    codeExample: "Infix: A+B*C → A B C * +",
  },
  {
    question: "What happens after the entire infix expression is processed?",
    shortAnswer: "All remaining operators are popped from the stack and appended to the output.",
    explanation: "Any operators still waiting in the stack are added at the end.",
    hint: "Stack is cleared.",
    level: "basic",
    codeExample: "Infix: A+B → after processing, '+' is popped.",
  },
  {
    question: "Why do we pop operators with higher precedence before pushing a new operator?",
    shortAnswer: "To ensure that higher precedence operators are placed before lower precedence ones in the output, preserving the evaluation order.",
    explanation: "Postfix evaluation must follow the same order as infix.",
    hint: "Precedence drives the output order.",
    level: "intermediate",
    codeExample: "A+B*C → '*' has higher precedence, so it appears before '+' in output.",
  },
  {
    question: "What is the role of associativity in the conversion rules?",
    shortAnswer: "For operators of equal precedence, associativity determines whether we pop equal‑precedence operators before pushing the new one.",
    explanation: "Left‑associative operators (like +, -, *, /) require popping equal precedence; right‑associative (like ^) do not.",
    hint: "Left‑associative pops equal; right‑associative doesn't.",
    level: "advanced",
    codeExample: "A-B-C → left‑associative: A B - C -",
  },
  {
    question: "What is the significance of the stack in this conversion?",
    shortAnswer: "The stack temporarily holds operators and parentheses until they are ready to be output.",
    explanation: "It allows us to handle precedence and nesting.",
    hint: "It's a waiting area.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What happens if there is a mismatched parenthesis?",
    shortAnswer: "The algorithm throws an error because the expression is invalid.",
    explanation: "Unmatched '(' or ')' indicate a syntax error.",
    hint: "The algorithm should detect and report it.",
    level: "intermediate",
    codeExample: "Infix: (A+B → missing ')'",
  },
  {
    question: "What is the output for infix `A+B*C`?",
    shortAnswer: "A B C * +",
    explanation: "Multiplication has higher precedence, so B*C is done first, then added to A.",
    hint: "Precedence.",
    level: "basic",
    codeExample: "A B C * +",
  },
  {
    question: "What is the output for infix `(A+B)*C`?",
    shortAnswer: "A B + C *",
    explanation: "Parentheses force addition first, then multiplication.",
    hint: "Parentheses override.",
    level: "basic",
    codeExample: "A B + C *",
  },
  {
    question: "What is the output for infix `A+B*C-D`?",
    shortAnswer: "A B C * + D -",
    explanation: "Multiplication first, then addition, then subtraction (left‑associative).",
    hint: "Order: * then + then -.",
    level: "intermediate",
    codeExample: "A B C * + D -",
  },
  {
    question: "What is the output for infix `A*B+C*D`?",
    shortAnswer: "A B * C D * +",
    explanation: "Multiplications first, then addition.",
    hint: "Two multiplications, then addition.",
    level: "intermediate",
    codeExample: "A B * C D * +",
  },
  {
    question: "What is the output for infix `A+B+C`?",
    shortAnswer: "A B + C +",
    explanation: "Addition is left‑associative, so it's `(A+B)+C`.",
    hint: "Left‑associative.",
    level: "basic",
    codeExample: "A B + C +",
  },
  {
    question: "What is the output for infix `A-B-C`?",
    shortAnswer: "A B - C -",
    explanation: "Subtraction is left‑associative, so `(A-B)-C`.",
    hint: "Left‑associative.",
    level: "basic",
    codeExample: "A B - C -",
  },
  {
    question: "What is the output for infix `A-B+C`?",
    shortAnswer: "A B - C +",
    explanation: "Left‑associative: `(A-B)+C`.",
    hint: "Left to right.",
    level: "basic",
    codeExample: "A B - C +",
  },
  {
    question: "What is the output for infix `A^B^C` (exponentiation is right‑associative)?",
    shortAnswer: "A B C ^ ^",
    explanation: "Because `^` is right‑associative, it's parsed as `A^(B^C)`, so postfix is `A B C ^ ^`.",
    hint: "Right‑associative.",
    level: "advanced",
    codeExample: "A B C ^ ^",
  },
  {
    question: "What is the output for infix `A+B*C+D`?",
    shortAnswer: "A B C * + D +",
    explanation: "Multiplication first, then additions left‑to‑right.",
    hint: "Precedence and associativity.",
    level: "intermediate",
    codeExample: "A B C * + D +",
  },
  {
    question: "What is the output for infix `(A+B)*(C-D)`?",
    shortAnswer: "A B + C D - *",
    explanation: "Parentheses force each sub‑expression, then multiplication.",
    hint: "Inner first.",
    level: "intermediate",
    codeExample: "A B + C D - *",
  },
  {
    question: "What is the output for infix `((A+B)*C)-D`?",
    shortAnswer: "A B + C * D -",
    explanation: "Innermost parentheses first, then multiplication, then subtraction.",
    hint: "Follow parentheses.",
    level: "intermediate",
    codeExample: "A B + C * D -",
  },
  {
    question: "What is the output for infix `A*(B+C)-D/E`?",
    shortAnswer: "A B C + * D E / -",
    explanation: "Parentheses first, then multiplication, then division, then subtraction.",
    hint: "Precedence and parentheses.",
    level: "advanced",
    codeExample: "A B C + * D E / -",
  },
  {
    question: "What is the output for infix `A+B*C/D`?",
    shortAnswer: "A B C * D / +",
    explanation: "Multiplication and division have equal precedence, left‑associative: `(B*C)/D` then add A.",
    hint: "Left‑associative for * and /.",
    level: "intermediate",
    codeExample: "A B C * D / +",
  },
  {
    question: "What is the output for infix `A*B+C/D`?",
    shortAnswer: "A B * C D / +",
    explanation: "Multiplication and division first, then addition.",
    hint: "Two separate computations then add.",
    level: "intermediate",
    codeExample: "A B * C D / +",
  },
  {
    question: "What is the output for infix `A*(B+C/D)`?",
    shortAnswer: "A B C D / + *",
    explanation: "Inside parentheses: C/D, then +B, then multiply by A.",
    hint: "Parentheses first.",
    level: "advanced",
    codeExample: "A B C D / + *",
  },
  {
    question: "Why does the algorithm pop operators of equal precedence for left‑associative operators?",
    shortAnswer: "Because left‑associative operators evaluate left‑to‑right, so the earlier operator should be output before the later one.",
    explanation: "This preserves the correct order.",
    hint: "Left‑associative means left first.",
    level: "advanced",
    codeExample: "A-B-C → output A B - C -",
  },
  {
    question: "Why does the algorithm NOT pop equal precedence for right‑associative operators?",
    shortAnswer: "Because right‑associative operators evaluate right‑to‑left, so the later operator should be output first.",
    explanation: "Example: A^B^C should be A^(B^C), so postfix is A B C ^ ^.",
    hint: "Right‑associative means right first.",
    level: "advanced",
    codeExample: "A^B^C → A B C ^ ^",
  },
  {
    question: "How does the algorithm handle spaces in the input?",
    shortAnswer: "Typically, spaces are ignored; only meaningful tokens (operands, operators, parentheses) are processed.",
    explanation: "Most implementations filter out whitespace.",
    hint: "Spaces are not considered.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "Can the same algorithm be used for converting infix to prefix?",
    shortAnswer: "Not directly; the rules differ, but you can adapt by reversing the expression and swapping parentheses.",
    explanation: "Infix to prefix requires a different approach, often using the same stack logic with modifications.",
    hint: "It's a separate process.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What is the time complexity of this conversion algorithm?",
    shortAnswer: "O(n), where n is the length of the infix expression.",
    explanation: "Each token is processed once, and each operator is pushed and popped at most once.",
    hint: "Linear.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What is the space complexity?",
    shortAnswer: "O(n) in the worst case (e.g., many nested parentheses or operators).",
    explanation: "The stack can grow to the number of operators.",
    hint: "Linear.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
];

export default questions;