// File: src/components/topics/topic4_files/topic4_questions.js
const questions = [
  {
    question: "What is framing in the context of the Data Link Layer?",
    shortAnswer: "The process of marking where a frame begins and ends within a raw bit stream.",
    explanation: "Framing allows the receiver to extract individual frames from the continuous stream of bits sent by the physical layer.",
    hint: "It's like putting punctuation in a sentence: it shows where one thought ends and the next begins.",
    level: "basic",
    codeExample: "// In PPP, the flag sequence 0x7E marks both start and end of a frame."
  },
  {
    question: "What are the four main framing techniques?",
    shortAnswer: "Character count, byte stuffing (character stuffing), bit stuffing, and physical layer coding violations.",
    explanation: "Each technique handles the problem of distinguishing frame boundaries with different trade‑offs in overhead and robustness.",
    hint: "Remember: Count, Byte, Bit, Physical.",
    level: "basic",
  },
  {
    question: "What is the main disadvantage of using a character count field?",
    shortAnswer: "If the count field is corrupted, the receiver loses synchronization and cannot locate the next frame.",
    explanation: "Because the receiver relies entirely on the count value to know how many bytes to read. An error in the count leads to misaligned frames until a special delimiter (if any) is encountered.",
    hint: "One corrupted number can break the whole sequence.",
    level: "moderate",
  },
  {
    question: "How does byte stuffing work? Give an example with flag 0x7E and escape 0x7D.",
    shortAnswer: "The flag pattern 0x7E marks frame boundaries. If 0x7E appears in the data, it is replaced by 0x7D followed by 0x5E (0x7E XOR 0x20). The escape 0x7D itself is replaced by 0x7D 0x5D.",
    explanation: "At the receiver, the stuffing is reversed: 0x7D 0x5E becomes 0x7E, and 0x7D 0x5D becomes 0x7D. This allows the flag to appear only as a delimiter, never in data.",
    hint: "It's like putting a backslash before a quote in a string.",
    level: "moderate",
  },
  {
    question: "What is the flag pattern used in HDLC and PPP bit stuffing?",
    shortAnswer: "01111110 (0x7E) – six 1s with a 0 at each end.",
    explanation: "When the sender sees five consecutive 1s in the data, it automatically inserts a 0 bit (stuffed). The receiver removes any 0 that follows five 1s, restoring the original data.",
    hint: "Five ones trigger a stuff; the flag has six ones, so it never appears in data.",
    level: "basic",
  },
  {
    question: "Why does bit stuffing guarantee that the flag pattern never appears inside the data?",
    shortAnswer: "Because after five consecutive 1s, a 0 is inserted. The flag pattern has six consecutive 1s – that would require the stuffed 0 to be removed, but it's inserted by the transmitter and removed only at the receiver after the flag detection.",
    explanation: "In the data stream after stuffing, you can never have six 1s in a row except as the flag (which is sent as a literal pattern). The receiver upon seeing six 1s knows it's a flag, not data.",
    hint: "The stuffing rule actively prevents the flag pattern from forming inside the payload.",
    level: "expert",
  },
  {
    question: "What is the worst‑case overhead of bit stuffing?",
    shortAnswer: "Up to 100% (one stuffed bit for every five original bits), but this is extremely unlikely.",
    explanation: "The worst pattern is all 1s: 11111 becomes 111110, adding 1 bit every 5 bits = 20% overhead. If we also count that a 0 after a run of five 1s is later followed by another run, the maximum theoretical overhead is 1/5 = 20%.",
    hint: "All ones causes the most stuffing.",
    level: "expert",
  },
  {
    question: "How does Ethernet avoid the need for byte or bit stuffing?",
    shortAnswer: "Ethernet uses physical layer coding (4b/5b, 8b/10b) that reserves special symbols (like Start of Frame Delimiter) that cannot occur in data.",
    explanation: "The 4b/5b encoding maps each 4‑bit nibble to a 5‑bit code word; some 5‑bit patterns are invalid for data and used as control symbols. Thus, the data itself never contains the delimiter pattern.",
    hint: "The encoding itself guarantees no ambiguity.",
    level: "expert",
  },
  {
    question: "What is the common flag byte used in PPP for framing?",
    shortAnswer: "0x7E (binary 01111110).",
    explanation: "Same as HDLC. PPP uses byte stuffing with escape 0x7D to transparently transmit any byte value, including 0x7E.",
    hint: "Remember ~ (tilde) is not used; it's 0x7E.",
    level: "basic",
  },
  {
    question: "In byte stuffing, what happens if the data contains the escape byte itself (e.g., 0x7D)?",
    shortAnswer: "It is also escaped: 0x7D is replaced by two bytes 0x7D 0x5D.",
    explanation: "This ensures that the receiver can distinguish between an escape that is part of stuffing and an escape that is actual data. When the receiver sees 0x7D, it looks at the next byte: if it's 0x5E, it yields 0x7E; if it's 0x5D, it yields 0x7D; otherwise, it's an error.",
    hint: "Escape the escape, just like in C strings.",
    level: "moderate",
  },
  {
    question: "What is the advantage of physical layer coding violations over stuffing?",
    shortAnswer: "No overhead on user data and simpler hardware decoding because delimiters are separate symbols.",
    explanation: "Since the coding scheme already has unused code points, the delimiter can be a valid physical symbol that never appears in the data. The receiver simply recognises that symbol as the frame boundary.",
    hint: "No extra bits inserted, no escape sequences – just a special symbol.",
    level: "expert",
  },
  {
    question: "What is a 'start frame delimiter' (SFD) in Ethernet?",
    shortAnswer: "A specific byte pattern (10101011) that follows the preamble and marks the beginning of the frame header.",
    explanation: "The SFD is a physical layer coding violation because the last two bits (11) break the alternating pattern of the preamble. It tells the receiver 'the next byte is the first byte of the frame'.",
    hint: "It's the 'go' signal after the count‑in.",
    level: "moderate",
  },
  {
    question: "Why is character count often combined with another framing method?",
    shortAnswer: "To provide resynchronisation: if the count field is corrupted, the receiver can fall back to flag detection to find the next frame.",
    explanation: "For example, DDCMP uses a count field but also includes a special flag at the end of the frame. If the count is wrong, the receiver scans for the flag to re‑establish framing.",
    hint: "Don't put all eggs in one basket; have a backup delimiter.",
    level: "moderate",
  },
  {
    question: "What does 'transparent transmission' mean?",
    shortAnswer: "The ability to send any arbitrary combination of bits (or bytes) as data without confusing the frame boundaries.",
    explanation: "Both byte stuffing and bit stuffing provide transparent transmission – the data can contain the flag pattern and it will be escaped, so the receiver still correctly identifies the real frame boundaries.",
    hint: "The data is 'invisible' to the framing mechanism.",
    level: "basic",
  },
  {
    question: "How does CAN bus implement bit stuffing?",
    shortAnswer: "After five consecutive bits of the same value (whether 0 or 1), the transmitter inserts a complementary stuffed bit.",
    explanation: "This ensures enough transitions for clock synchronisation in the NRZ‑like signalling. The receiver removes stuffed bits automatically. The stuffed bits do not affect CRC calculation.",
    hint: "CAN stuffs both 0s and 1s when repeated five times.",
    level: "expert",
  },
  {
    question: "What is the difference between bit stuffing and byte stuffing in terms of overhead?",
    shortAnswer: "Bit stuffing adds at most 1 bit per 5 original bits (20% worst case). Byte stuffing can add up to 100% overhead if data consists entirely of flag bytes (since each flag byte becomes two bytes).",
    explanation: "In practice, overhead for both is low (a few percent). Bit stuffing is more efficient for binary data; byte stuffing is simpler for software handling.",
    hint: "Bit stuffing has a known worst‑case bound; byte stuffing can double the size.",
    level: "moderate",
  },
  {
    question: "Why does USB use bit stuffing?",
    shortAnswer: "USB uses NRZI encoding, which requires a transition at least every 6 bit times to maintain clock synchronisation. Bit stuffing ensures that after six consecutive 1s (NRZI no transition), a stuffed 0 (which causes a transition) is inserted.",
    explanation: "Without stuffing, long runs of 1s would cause the receiver's clock to drift. The stuffed 0 forces a transition, allowing clock recovery.",
    hint: "It's for clock recovery, not just framing (though it also helps distinguish SYNC pattern).",
    level: "expert",
  },
  {
    question: "What is the 'abort sequence' in HDLC bit stuffing?",
    shortAnswer: "Seven or more 1s (011111111) indicates an abort, invalidating the current frame.",
    explanation: "If a receiver sees seven 1s in a row, it discards the frame being received and resumes searching for the next flag. This handles transmission errors gracefully.",
    hint: "More than six 1s = abandon ship.",
    level: "expert",
  },
  {
    question: "How does a receiver recognise a byte‑stuffed frame after an error?",
    shortAnswer: "By scanning the incoming byte stream for the flag byte (0x7E). Even if previous bytes were misinterpreted, the flag acts as a resynchronisation point.",
    explanation: "The receiver continuously looks for the flag. When found, it starts a new frame. That's why byte stuffing is robust: a corrupted byte may cause loss of a single frame, but the next flag resets the state.",
    hint: "The flag is a beacon that re‑establishes sync.",
    level: "moderate",
  },
  {
    question: "What is the purpose of the 'idle' pattern in HDLC?",
    shortAnswer: "A continuous sequence of 1s (or 0x7E flags back‑to‑back) indicating that the line is idle or between frames.",
    explanation: "The receiver treats consecutive flags as idle. The transmitter may send flags to keep the line active. This also helps keep the receiver synchronised.",
    hint: "Silence on the line is filled with flags or ones.",
    level: "moderate",
  },
  {
    question: "Can character count ever be used alone?",
    shortAnswer: "Only on very reliable links (e.g., internal backplane buses) where bit error rate is extremely low. Otherwise, it's dangerous.",
    explanation: "Character count alone is used in some high‑speed interconnects (like PCIe uses packet length fields, but with CRC and other checks). However, they also have link‑layer retries, effectively recovering from count errors.",
    hint: "When the link is practically error‑free, counting works.",
    level: "expert",
  },
  {
    question: "How does bit stuffing affect frame length?",
    shortAnswer: "The frame length becomes variable, depending on the data pattern. The transmitter adds stuffed bits; the receiver removes them.",
    explanation: "This means the actual number of bits transmitted can exceed the original frame size by up to ~20%. The receiver must be able to handle this variable length.",
    hint: "The physical length is not the same as the logical data length.",
    level: "moderate",
  },
  {
    question: "What is the 'zero insertion' method in bit stuffing?",
    shortAnswer: "Another name for bit stuffing: a 0 is inserted after every sequence of five consecutive 1s in the data stream.",
    explanation: "It's called zero insertion because you add a '0' bit. The receiver performs zero deletion (removes any 0 that appears after five 1s).",
    hint: "Same technique, different name.",
    level: "basic",
  },
  {
    question: "Why is byte stuffing less efficient for binary data than for text?",
    shortAnswer: "Binary data contains uniform distribution of all byte values, making it more likely to encounter the flag byte (1/256 chance per byte), requiring escaping.",
    explanation: "For text, the flag byte (often 0x7E) is rarely used, so overhead is low. For binary data (e.g., program files), the flag may appear often, increasing overhead.",
    hint: "Choose a flag that is rare in your typical payload.",
    level: "moderate",
  },
  {
    question: "What is a 'violation symbol' in physical coding?",
    shortAnswer: "A code word that is not used for any data symbol, reserved for control purposes like frame boundaries.",
    explanation: "For example, in 8b/10b encoding, certain 10‑bit sequences are invalid for data and are used as K‑codes (e.g., K28.5 for comma).",
    hint: "It's a word that has no data meaning, only control meaning.",
    level: "expert",
  },
  {
    question: "How does the receiver know to remove a stuffed bit versus the flag?",
    shortAnswer: "The receiver continuously monitors the bit stream. When it sees five consecutive 1s, it inspects the next bit: if it's a 0, it removes that 0 (it was stuffed). If the next bit is 1 (making six 1s), then it's a flag (or abort if more).",
    explanation: "The decision is made based on the sixth bit. This requires a state machine that maintains the count of consecutive 1s.",
    hint: "Five 1s + 0 = stuffed; five 1s + 1 = possible flag.",
    level: "expert",
  },
  {
    question: "What is the difference between 'octet stuffing' and 'bit stuffing'?",
    shortAnswer: "Octet stuffing is another name for byte stuffing (operates on 8‑bit bytes). Bit stuffing works on individual bits.",
    explanation: "Some standards (e.g., PPP) use the term 'octet stuffing' to emphasise that it works on bytes, not bits.",
    hint: "Octet = 8 bits.",
    level: "basic",
  },
  {
    question: "Can we use multiple flags between frames?",
    shortAnswer: "Yes, sending multiple consecutive flags is allowed and often used to separate frames or to keep the line idle.",
    explanation: "The receiver treats any number of flags as frame boundaries. After a flag, it starts looking for the next non‑flag byte to begin a new frame.",
    hint: "More flags just mean more space between frames.",
    level: "moderate",
  },
  {
    question: "What is an 'idle sequence' in HDLC?",
    shortAnswer: "A continuous stream of '1's (marking) or a series of flags, depending on the configuration. It indicates that no frame is being transmitted.",
    explanation: "In some environments, sending flags is preferred because it keeps the clock recovery circuits locked. In others, just holding the line at '1' (idle) is used.",
    hint: "The line is never truly silent; it's either flags or ones.",
    level: "moderate",
  },
  {
    question: "How would you handle a corrupted flag byte in a stuffed stream?",
    shortAnswer: "If the flag pattern is corrupted (e.g., a bit error changes 0x7E to something else), the receiver may not recognise the boundary. However, the next flag (if any) will resynchronise.",
    explanation: "Typically, a CRC check will fail on the corrupted frame, and the frame will be discarded. The receiver continues scanning for the next valid flag.",
    hint: "Lost sync is temporary; the next flag restores order.",
    level: "expert",
  }
];

export default questions;