// topic10_files/topic10_questions.js
// Module 004_004: Backup, Point-in-Time Recovery & Data Migration
// Topic 10: Exporting Query Results to CSV / Text Files using SELECT ... INTO OUTFILE

const questions = [
  {
    question: "What is `SELECT ... INTO OUTFILE` in MySQL, and where is the resulting file written?",
    shortAnswer: "It directly exports query results into a formatted text/CSV file created on the MySQL server's local filesystem (within the directory restricted by `secure_file_priv`).",
    explanation: "Because the file is written directly by the server daemon on local disk, export speed is extremely fast, bypassing client-side network rendering.",
    hint: "Exports query results to a file on the server's local disk.",
    level: "basic",
    codeExample: `SELECT * FROM kolkata_retail.orders 
INTO OUTFILE '/var/lib/mysql-files/orders_export.csv'
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\\n';`
  },
  {
    question: "What happens if the destination file specified in `SELECT ... INTO OUTFILE` already exists on the server filesystem?",
    shortAnswer: "The query fails with `ERROR 1086 (HY000): File '...' already exists`.",
    explanation: "MySQL intentionally refuses to overwrite existing files to prevent accidental data destruction and protect against malicious file overwrites.",
    hint: "MySQL will never overwrite existing files and throws Error 1086.",
    level: "basic",
    codeExample: `-- If /var/lib/mysql-files/orders.csv exists:
-- ERROR 1086 (HY000): File '/var/lib/mysql-files/orders.csv' already exists`
  },
  {
    question: "What MySQL privilege is required to execute `SELECT ... INTO OUTFILE`?",
    shortAnswer: "The global `FILE` administrative privilege.",
    explanation: "Because writing files to the host filesystem has operating system implications, only accounts with the global `FILE` privilege can run `INTO OUTFILE`.",
    hint: "Requires the global FILE privilege.",
    level: "basic",
    codeExample: `GRANT FILE ON *.* TO 'export_user'@'localhost';`
  },
  {
    question: "How do you prepend column header titles to a CSV file generated by `SELECT ... INTO OUTFILE`?",
    shortAnswer: "Use `UNION ALL` where the first `SELECT` statement contains string literals of column names, followed by the data `SELECT` query (with non-string columns cast to `CHAR`).",
    explanation: "By default, `SELECT ... INTO OUTFILE` outputs only row data without column names. Prepending a header row via `UNION ALL` creates standard RFC 4180 CSV files.",
    hint: "Use UNION ALL with a SELECT containing column title string literals.",
    level: "intermediate",
    codeExample: `SELECT 'Order ID', 'Customer Name', 'Amount (₹)', 'Date'
UNION ALL
SELECT order_id, customer_name, CAST(amount AS CHAR), DATE_FORMAT(order_date, '%Y-%m-%d')
FROM kolkata_retail.orders
INTO OUTFILE '/var/lib/mysql-files/orders_with_header.csv'
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\\n';`
  },
  {
    question: "In Mamata & Susmita's Barrackpore retail store, an accountant needed an export of all ₹1,000+ orders in CSV format. Why did `SELECT ... INTO OUTFILE '/home/mamata/report.csv'` fail?",
    shortAnswer: "Because `secure_file_priv` restricted server file operations to `/var/lib/mysql-files/`, rejecting any export path outside that designated directory.",
    explanation: "Changing the output path to `/var/lib/mysql-files/report.csv` resolved the error immediately.",
    hint: "File exports must be written to the directory specified by secure_file_priv.",
    level: "moderate",
    codeExample: `-- Correct path:
SELECT * FROM barrackpore_store.orders 
WHERE amount >= 1000.00
INTO OUTFILE '/var/lib/mysql-files/barrackpore_q3_report.csv'
FIELDS TERMINATED BY ',';`
  },
  {
    question: "In Abhronila & Debangshu's Kolkata fintech bank, an external auditor requested a CSV of 20 million ledger transactions. How did Debangshu export this in 8 seconds?",
    shortAnswer: "He executed `SELECT ... INTO OUTFILE` with `FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '\"'` directly to a high-speed NVMe mount inside `/var/lib/mysql-files/`.",
    explanation: "Direct server-side engine export bypassed client-side rendering bottlenecks, streaming 20 million records into a clean 1.8GB CSV file in 8.2 seconds.",
    hint: "Direct server-side export to NVMe disk bypassed client network rendering.",
    level: "expert",
    codeExample: `SELECT transaction_id, account_num, amount, txn_time
FROM kolkata_bank.ledger
WHERE txn_date = '2026-08-25'
INTO OUTFILE '/var/lib/mysql-files/daily_audit_20260825.csv'
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\\n';`
  },
  {
    question: "How can a client application export query results to a local CSV file when the user does NOT have filesystem access to the MySQL server?",
    shortAnswer: "Run the `mysql` CLI client with `--batch` (`-B`) and `--raw` (`-r`) and translate tabs to commas: `mysql -u user -p -e \"SELECT ...\" -B | tr '\\t' ',' > /local/path/output.csv`.",
    explanation: "The `--batch` option prints query results as tab-separated values to stdout, which can be redirected or converted to CSV on the client machine.",
    hint: "Use mysql CLI with --batch and pipe through tr or sed on the client.",
    level: "intermediate",
    codeExample: `mysql -h db.kolkata.internal -u user -p -B -e "SELECT * FROM kolkata_retail.orders;" | \\
  sed 's/\\t/,/g' > /local_laptop/orders.csv`
  },
  {
    question: "How does `SELECT ... INTO OUTFILE` represent SQL `NULL` values in the output text file by default?",
    shortAnswer: "It represents `NULL` as the two-character literal sequence `\\N`.",
    explanation: "If you want `NULL` represented as an empty string `\"\"` or the word `'NULL'`, wrap the column in `IFNULL(col, '')` or `COALESCE()`.",
    hint: "Defaults to \\N for NULL values.",
    level: "basic",
    codeExample: `SELECT order_id, IFNULL(discount_code, '') AS discount_code
FROM kolkata_retail.orders
INTO OUTFILE '/var/lib/mysql-files/orders_null_handled.csv'
FIELDS TERMINATED BY ',';`
  },
  {
    question: "What file ownership and permissions are assigned to files created by `SELECT ... INTO OUTFILE` on Linux?",
    shortAnswer: "Owner: `mysql:mysql`, with permissions `0640` (read/write for `mysql` user, read-only for `mysql` group, zero access for other users).",
    explanation: "Because the `mysqld` daemon process creates the file, it inherits the system daemon's user and group permissions.",
    hint: "Owned by mysql:mysql with 0640 permissions.",
    level: "intermediate",
    codeExample: `# ls -l /var/lib/mysql-files/
# -rw-r----- 1 mysql mysql 1849201 Aug 25 14:30 orders_export.csv`
  },
  {
    question: "What is `mysqldump --tab` (or `-T`), and how does it relate to `SELECT ... INTO OUTFILE`?",
    shortAnswer: "`mysqldump --tab=/dir/` produces two files per table: a `.sql` file containing the `CREATE TABLE` DDL and a `.txt` file containing the raw table data dumped via `SELECT ... INTO OUTFILE`.",
    explanation: "Combines the portability of schema DDL with the high-speed loading performance of flat text files.",
    hint: "Generates .sql schema files and .txt data files via SELECT INTO OUTFILE.",
    level: "intermediate",
    codeExample: `mysqldump -u root -p --tab=/var/lib/mysql-files/ --single-transaction kolkata_retail`
  },
  {
    question: "How do you format a `DATETIME` column during `SELECT ... INTO OUTFILE` to match standard ISO 8601 formatting?",
    shortAnswer: "Use `DATE_FORMAT(date_col, '%Y-%m-%dT%H:%i:%sZ')` in the query's select list.",
    explanation: "Formats temporal values into standard UTC strings recognized by downstream analytics systems.",
    hint: "Use DATE_FORMAT() to generate ISO 8601 strings.",
    level: "basic",
    codeExample: `SELECT order_id, DATE_FORMAT(order_date, '%Y-%m-%dT%H:%i:%sZ') AS order_date
FROM kolkata_retail.orders
INTO OUTFILE '/var/lib/mysql-files/orders_iso8601.csv'
FIELDS TERMINATED BY ',';`
  },
  {
    question: "What is the difference between `FIELDS TERMINATED BY '\t'` and `FIELDS TERMINATED BY ','`?",
    shortAnswer: "`FIELDS TERMINATED BY '\t'` creates Tab-Separated Value (TSV) files; `FIELDS TERMINATED BY ','` creates Comma-Separated Value (CSV) files.",
    explanation: "TSV files are often preferred when text fields frequently contain embedded commas, reducing the need for quote escaping.",
    hint: "\\t creates TSV files; comma creates CSV files.",
    level: "basic",
    codeExample: `SELECT * FROM kolkata_retail.orders
INTO OUTFILE '/var/lib/mysql-files/orders.tsv'
FIELDS TERMINATED BY '\\t' LINES TERMINATED BY '\\n';`
  },
  {
    question: "Why does `SELECT ... INTO OUTFILE` execute faster than client-side `SELECT` exports over JDBC or ODBC?",
    shortAnswer: "Because `INTO OUTFILE` writes data directly from the server's memory buffer to local disk, eliminating network socket serialization, client memory allocation, and client-side formatting overhead.",
    explanation: "Writing directly to local server storage avoids saturating the network interface during multi-gigabyte exports.",
    hint: "Writes directly from server RAM to local disk without network transfer.",
    level: "intermediate",
    codeExample: `-- Direct server disk write = Maximum NVMe I/O throughput.`
  },
  {
    question: "How do you export only a filtered subset of rows matching specific business criteria?",
    shortAnswer: "Include standard `WHERE`, `ORDER BY`, and `LIMIT` clauses in the `SELECT` query prior to the `INTO OUTFILE` clause.",
    explanation: "The database engine filters and sorts rows before formatting and writing them to disk.",
    hint: "Use WHERE and ORDER BY clauses before INTO OUTFILE.",
    level: "basic",
    codeExample: `SELECT order_id, customer_name, amount 
FROM kolkata_retail.orders
WHERE status = 'DELIVERED' AND city = 'Barrackpore'
ORDER BY amount DESC
INTO OUTFILE '/var/lib/mysql-files/barrackpore_delivered.csv'
FIELDS TERMINATED BY ',';`
  },
  {
    question: "What is `SELECT ... INTO DUMPFILE` and how does it differ from `SELECT ... INTO OUTFILE`?",
    shortAnswer: "`INTO DUMPFILE` writes a single raw, unformatted binary row without column delimiters or newline terminations, making it ideal for exporting raw binary blobs (such as images, PDFs, or compiled objects).",
    explanation: "While `INTO OUTFILE` is designed for tabular text files with multiple rows, `INTO DUMPFILE` extracts raw single binary blobs with zero formatting.",
    hint: "INTO DUMPFILE extracts single raw binary blobs (e.g. images) without formatting.",
    level: "expert",
    codeExample: `SELECT profile_picture 
FROM kolkata_retail.customers 
WHERE customer_id = 101
INTO DUMPFILE '/var/lib/mysql-files/customer_101.jpg';`
  },
  {
    question: "How can you compress an exported CSV file immediately after generating it with `SELECT ... INTO OUTFILE`?",
    shortAnswer: "Use an operating system command or cron script to run `zstd -T4 /var/lib/mysql-files/orders.csv` or `gzip /var/lib/mysql-files/orders.csv`.",
    explanation: "`SELECT ... INTO OUTFILE` writes uncompressed text; running post-export compression reduces file size by 70-80% before network transfer.",
    hint: "Compress the output file using zstd or gzip post-export.",
    level: "basic",
    codeExample: `# OS shell script:
mysql -u root -p -e "SELECT ... INTO OUTFILE '/var/lib/mysql-files/orders.csv' ...;"
zstd -T4 /var/lib/mysql-files/orders.csv`
  },
  {
    question: "What security risk is introduced if `secure_file_priv` is set to an empty string `\"\"`?",
    shortAnswer: "It allows database users with the `FILE` privilege to read or write files across ANY directory on the server filesystem, creating severe vulnerability to SQL injection and OS file modification attacks.",
    explanation: "An attacker could write arbitrary unauthorized files into web server document directories or system paths.",
    hint: "Setting secure_file_priv to empty string permits writing to any directory on the host.",
    level: "expert",
    codeExample: `-- DANGEROUS CONFIGURATION:
-- secure_file_priv = ""`
  },
  {
    question: "How do you export aggregated summary data (e.g. monthly sales by category) to CSV using `SELECT ... INTO OUTFILE`?",
    shortAnswer: "Write a standard `GROUP BY` aggregation query with the `INTO OUTFILE` clause appended.",
    explanation: "MySQL computes the aggregate totals in memory and writes the final summary rows directly to CSV.",
    hint: "Use GROUP BY with aggregate functions before INTO OUTFILE.",
    level: "basic",
    codeExample: `SELECT category, COUNT(*) AS total_sales, SUM(amount) AS total_revenue
FROM kolkata_retail.orders
GROUP BY category
INTO OUTFILE '/var/lib/mysql-files/category_sales_summary.csv'
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';`
  },
  {
    question: "Why should exported CSV files containing sensitive PII or financial data be deleted or encrypted immediately after transfer?",
    shortAnswer: "Because files in `/var/lib/mysql-files/` reside in plaintext on disk; leaving sensitive financial ledgers or customer PII unencrypted violates compliance regulations (PCI-DSS, GDPR).",
    explanation: "Automated scripts should encrypt exports with GPG or upload them to secure object storage and delete the local plaintext copy.",
    hint: "Plaintext CSV files on disk create PII data leakage risks.",
    level: "intermediate",
    codeExample: `# Script: GPG encrypt and delete plaintext:
gpg --encrypt --recipient audit@bank.internal /var/lib/mysql-files/report.csv
rm /var/lib/mysql-files/report.csv`
  },
  {
    question: "What is the impact of character encoding during `SELECT ... INTO OUTFILE` when exporting Bengali or Hindi text?",
    shortAnswer: "Specify `CHARACTER SET utf8mb4` in the query (`INTO OUTFILE '...' CHARACTER SET utf8mb4`) to ensure all Unicode characters are exported accurately without truncation.",
    explanation: "Guarantees that Indian regional language characters and emoji symbols are preserved in the exported CSV.",
    hint: "Specify CHARACTER SET utf8mb4 in the INTO OUTFILE clause.",
    level: "basic",
    codeExample: `SELECT customer_name_bengali, address_bengali
FROM kolkata_retail.customers
INTO OUTFILE '/var/lib/mysql-files/bengali_customers.csv'
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',';`
  },
  {
    question: "How can you automate daily CSV exports of completed orders to an external FTP or S3 bucket?",
    shortAnswer: "Schedule a daily cron job that executes the `SELECT ... INTO OUTFILE` query via `mysql -e`, uploads the CSV via `aws s3 cp`, and deletes the local file.",
    explanation: "Cron automation provides consistent scheduled ETL data feeds for external business intelligence systems.",
    hint: "Combine mysql -e with aws s3 cp in a scheduled cron script.",
    level: "intermediate",
    codeExample: `# Daily cron script:
0 1 * * * mysql -u root -pSecurePass -e "SELECT ... INTO OUTFILE '/var/lib/mysql-files/daily.csv' ...;" && \\
  aws s3 cp /var/lib/mysql-files/daily.csv s3://kolkata-bi-reports/ && \\
  rm /var/lib/mysql-files/daily.csv`
  },
  {
    question: "What is the role of `ESCAPED BY '\\\\'` in `SELECT ... INTO OUTFILE`?",
    shortAnswer: "It specifies the escape character used to escape delimiter characters, quotes, and newlines that appear inside actual data values, preventing field corruption.",
    explanation: "If a customer name contains `\"Mamata \"The Leader\" Banerjee\"`, the internal quotes are escaped as `\\\"`.",
    hint: "Escapes embedded quotes and delimiters within data values.",
    level: "basic",
    codeExample: `FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\\\'`
  },
  {
    question: "Can `SELECT ... INTO OUTFILE` export data from joined tables across multiple databases?",
    shortAnswer: "Yes, standard multi-table joins across different schemas (e.g. `kolkata_retail.orders JOIN kolkata_finance.ledgers`) can be exported seamlessly into a single combined CSV file.",
    explanation: "MySQL evaluates the multi-database join query in the engine and writes the unified result set directly to disk.",
    hint: "Supports standard multi-table and cross-database joins.",
    level: "intermediate",
    codeExample: `SELECT o.order_id, o.customer_name, l.transaction_reference, l.amount
FROM kolkata_retail.orders o
JOIN kolkata_finance.ledgers l ON o.order_id = l.order_id
INTO OUTFILE '/var/lib/mysql-files/joined_orders_ledger.csv'
FIELDS TERMINATED BY ',';`
  },
  {
    question: "What happens if a database query exporting 100 million rows with `SELECT ... INTO OUTFILE` exhausts all disk space on the server's partition?",
    shortAnswer: "The query fails with `ERROR 3 (HY000): Error writing file (Errcode: 28 - No space left on device)`, and the partially written file remains on disk.",
    explanation: "Monitoring disk space in `/var/lib/mysql-files/` is critical before initiating massive multi-gigabyte exports.",
    hint: "Throws Error 28 (No space left on device) if disk space is exhausted.",
    level: "intermediate",
    codeExample: `-- Ensure disk partition has sufficient free space before running massive exports.`
  },
  {
    question: "How do you format numeric columns with explicit decimal places (e.g. currency formatting) during `SELECT ... INTO OUTFILE`?",
    shortAnswer: "Use `FORMAT(amount, 2)` or `CAST(amount AS DECIMAL(10,2))` in the query select list.",
    explanation: "Ensures that financial amounts are formatted with consistent two-decimal precision in the output CSV.",
    hint: "Use FORMAT(col, 2) or CAST(col AS DECIMAL(10,2)).",
    level: "basic",
    codeExample: `SELECT order_id, FORMAT(amount, 2) AS formatted_amount
FROM kolkata_retail.orders
INTO OUTFILE '/var/lib/mysql-files/orders_formatted.csv'
FIELDS TERMINATED BY ',';`
  },
  {
    question: "Why should `SELECT ... INTO OUTFILE` be executed on read replicas rather than active primary master servers for large analytical reports?",
    shortAnswer: "To prevent heavy disk read I/O and buffer pool churn from competing with active OLTP user write transactions on the primary master.",
    explanation: "Offloading heavy analytical exports to read replicas protects production query latency.",
    hint: "Offloading to read replicas protects primary OLTP transaction performance.",
    level: "basic",
    codeExample: `-- Run heavy reporting exports on read replicas.`
  },
  {
    question: "What is the difference between exporting via `SELECT ... INTO OUTFILE` versus exporting via Python pandas / SQLAlchemy?",
    shortAnswer: "`INTO OUTFILE` writes directly from MySQL memory to local server disk in seconds; Python pandas transfers all rows over the network, parses them in Python RAM, and writes them locally, which is up to 10x slower on large datasets.",
    explanation: "For multi-gigabyte datasets, server-side `INTO OUTFILE` avoids network transfer and Python interpreter memory bloat.",
    hint: "INTO OUTFILE avoids network latency and Python memory overhead.",
    level: "intermediate",
    codeExample: `-- Server-side INTO OUTFILE: 8 seconds (10x faster than Python client fetch)`
  },
  {
    question: "How do you verify the exit status and row count of a `SELECT ... INTO OUTFILE` query in automated shell scripts?",
    shortAnswer: "Check the client execution summary output (`Query OK, N rows affected`) and inspect the shell exit code (`$? == 0`).",
    explanation: "Confirms that the query completed successfully and verifies the total row count exported.",
    hint: "Inspect $? and parse 'Query OK, N rows affected'.",
    level: "basic",
    codeExample: `mysql -u root -p -e "SELECT ... INTO OUTFILE ...;"
if [ $? -eq 0 ]; then echo "Export Succeeded ✅"; fi`
  },
  {
    question: "Can `SELECT ... INTO OUTFILE` be used to export JSON columns into a file?",
    shortAnswer: "Yes, JSON columns can be exported as text strings or formatted using `JSON_UNQUOTE()` and `JSON_EXTRACT()`.",
    explanation: "Allows exporting structured JSON documents alongside relational columns in standard CSV format.",
    hint: "Supports exporting JSON columns directly or formatted with JSON functions.",
    level: "intermediate",
    codeExample: `SELECT order_id, JSON_UNQUOTE(metadata->'$.shipping_pincode') AS pincode
FROM kolkata_retail.orders
INTO OUTFILE '/var/lib/mysql-files/orders_pincode.csv'
FIELDS TERMINATED BY ',';`
  },
  {
    question: "What is the primary operational takeaway of Topic 10 in Module 004_004?",
    shortAnswer: "`SELECT ... INTO OUTFILE` provides high-speed server-side query result export directly to CSV/text files: master delimiter formatting, prepend column headers via `UNION ALL`, enforce `secure_file_priv` directory security, handle `NULL` formatting, and execute heavy exports on read replicas to protect primary OLTP performance.",
    explanation: "Understanding server-side export mechanics allows database architects to generate massive analytical extracts and BI feeds in seconds with minimal resource contention.",
    hint: "Summarize server-side speed, delimiter formatting, UNION ALL headers, and secure_file_priv.",
    level: "basic",
    codeExample: `-- Master Production Query Export Pipeline:
SELECT 'Order ID', 'Customer Name', 'Amount (₹)', 'Status', 'Date'
UNION ALL
SELECT 
  order_id, 
  customer_name, 
  CAST(amount AS CHAR), 
  status, 
  DATE_FORMAT(order_date, '%Y-%m-%d')
FROM kolkata_retail.orders
WHERE order_date >= '2026-01-01'
INTO OUTFILE '/var/lib/mysql-files/q1_orders_report.csv'
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\\n';`
  }
];

export default questions;
