const questions = [
  {
    question: "What is C language and why is it called the mother of modern programming languages?",
    shortAnswer: "C is a procedural systems programming language created by Dennis Ritchie in 1972 at Bell Labs.",
    explanation: "C provided direct memory access, concise syntax, and high execution speed. Most modern operating systems (Linux, Windows, macOS), JVMs, Python interpreters, and database engines (MySQL, PostgreSQL) are written in C.",
    hint: "Think about kernel development and OS foundations.",
    level: "basic",
    codeExample: "#include <stdio.h>\nint main() { printf(\"C Foundations\\n\"); return 0; }"
  },
  {
    question: "What are the four main stages of the GCC compilation pipeline?",
    shortAnswer: "1. Preprocessing, 2. Compilation, 3. Assembly, 4. Linking.",
    explanation: "Preprocessing expands #include directives and macros. Compilation converts C code into assembly (.s). Assembly converts assembly code into object code (.o). Linking combines object code with library object files to produce the final executable binary.",
    hint: "Remember the file extensions: .c -> .i -> .s -> .o -> executable.",
    level: "basic",
    codeExample: "// GCC flags:\n// gcc -E main.c -o main.i (Preprocess)\n// gcc -S main.i -o main.s (Compile)\n// gcc -c main.s -o main.o (Assemble)\n// gcc main.o -o main     (Link)"
  },
  {
    question: "Why does the main function in C return an integer value?",
    shortAnswer: "The return value is an exit status code passed back to the operating system.",
    explanation: "By convention, returning 0 signifies successful execution (EXIT_SUCCESS), while any non-zero integer indicates an error condition (EXIT_FAILURE).",
    hint: "Check $? in Linux terminal after running a binary.",
    level: "basic",
    codeExample: "int main(void) {\n    return 0; // 0 = Success\n}"
  },
  {
    question: "What is the difference between #include <stdio.h> and #include \"myheader.h\"?",
    shortAnswer: "<stdio.h> searches standard system directories; \"myheader.h\" searches the local directory first.",
    explanation: "Angle brackets indicate standard library headers provided by the compiler toolchain. Double quotes tell the preprocessor to check the current project workspace directory before falling back to system directories.",
    hint: "Use quotes for your own created header files.",
    level: "basic"
  },
  {
    question: "What does the stdio.h header file stand for and contain?",
    shortAnswer: "stdio.h stands for Standard Input Output Header.",
    explanation: "It contains function prototypes, type definitions (like FILE), and macros (like NULL, EOF) for performing input and output stream operations such as printf, scanf, fopen, and fclose.",
    hint: "Standard I/O stream handler.",
    level: "basic"
  },
  {
    question: "What is the role of the C Preprocessor (CPP)?",
    shortAnswer: "It processes source text before the actual compilation phase starts.",
    explanation: "The preprocessor strips comments, expands macros (#define), includes header file contents (#include), and evaluates conditional compilation directives (#ifdef, #ifndef).",
    hint: "No C syntax checking happens during preprocessing; it is pure text manipulation.",
    level: "intermediate"
  },
  {
    question: "What is an object file (.o or .obj) in C?",
    shortAnswer: "A machine-code file generated by the assembler containing relocatable object code.",
    explanation: "An object file contains machine language instructions for a single source file, but unresolved function calls (like printf) must be resolved by the linker before it can run.",
    hint: "Object files cannot be executed directly until linked.",
    level: "intermediate"
  },
  {
    question: "What is a Linker and what does a Linker Error mean?",
    shortAnswer: "A Linker combines object files and libraries; linker errors happen when referenced symbols cannot be resolved.",
    explanation: "If you call a function like calculateGrade() but forget to link its definition file or library, the compiler phase succeeds but the linker throws an 'undefined reference' error.",
    hint: "Undefined reference to 'main' or function name is a linker error.",
    level: "intermediate",
    codeExample: "// Linker Error Example:\n// undefined reference to `main`"
  },
  {
    question: "What is the difference between int main() and int main(void)?",
    shortAnswer: "In C, int main(void) explicitly specifies that main takes zero arguments.",
    explanation: "In C, int main() means main accepts an unspecified number of parameters, whereas int main(void) strictly enforces that no arguments can be passed.",
    hint: "In C++, both mean no parameters, but in C void is explicit.",
    level: "intermediate"
  },
  {
    question: "How does printf format specifier %d work?",
    shortAnswer: "%d formats signed 32-bit decimal integers for console output.",
    explanation: "printf scans the format string for %, matches specifiers with subsequent arguments by type and position, and prints the formatted output buffer.",
    hint: "%d for decimal integer, %f for float, %c for character.",
    level: "basic",
    codeExample: "int age = 20;\nprintf(\"Age: %d years\\n\", age);"
  },
  {
    question: "Why is the & (address-of) operator required in scanf for basic variables?",
    shortAnswer: "scanf needs the memory address of the variable to write user input directly into it.",
    explanation: "Since C passes arguments by value, passing a variable directly to scanf would give scanf a copy. Passing &variable gives scanf its exact RAM location to store the parsed value.",
    hint: "Pass memory address so scanf can mutate local memory.",
    level: "basic",
    codeExample: "int roll;\nscanf(\"%d\", &roll);"
  },
  {
    question: "What happens if you omit the return 0 statement in C99 standard main function?",
    shortAnswer: "In C99 and later, the compiler automatically inserts an implicit return 0 at the end of main.",
    explanation: "While C99 auto-appends return 0 to main, explicitly returning 0 is considered best practice for readability and older compiler compatibility.",
    hint: "Explicit return 0 is always preferred.",
    level: "basic"
  },
  {
    question: "What is undefined behavior (UB) in C?",
    shortAnswer: "Execution behavior not specified by the C standard, leading to unpredictable outcomes.",
    explanation: "Undefined behavior occurs when a program executes invalid operations like division by zero, out-of-bounds array access, or dereferencing NULL pointers. The compiler is allowed to do anything, including crashing or producing incorrect results.",
    hint: "Avoid UB at all costs for secure systems programming.",
    level: "advanced"
  },
  {
    question: "What is the purpose of compiler flags like -Wall and -Wextra in GCC?",
    shortAnswer: "They enable comprehensive compiler warnings for potential code defects.",
    explanation: "-Wall enables all standard warnings, and -Wextra turns on additional warnings (such as uninitialized variables or type mismatches) to catch bugs before execution.",
    hint: "Always compile with gcc -Wall -Wextra main.c",
    level: "intermediate"
  },
  {
    question: "What is the difference between single-line (//) and multi-line (/* */) comments?",
    shortAnswer: "// comments out the rest of the line (C99+); /* */ comments out blocks.",
    explanation: "Single-line comments were introduced in C99 (borrowed from C++). Block comments can span multiple lines but cannot be nested.",
    hint: "Do not nest /* /* nested */ */ as it breaks compilation.",
    level: "basic"
  },
  {
    question: "What is Portable ANSI C?",
    shortAnswer: "C code adhering strictly to standardized specifications ensuring compilation across different operating systems.",
    explanation: "Writing standard C without OS-specific API calls (like Windows conio.h or Linux unistd.h) ensures code compiles seamlessly on Windows, Linux, macOS, and embedded ARM microcontrollers.",
    hint: "Stick to standard C library headers (<stdio.h>, <stdlib.h>, <string.h>).",
    level: "intermediate"
  },
  {
    question: "What is a segmentation fault (SIGSEGV)?",
    shortAnswer: "A crash caused by attempting to access memory that the program does not have permission to access.",
    explanation: "A segmentation fault occurs when trying to dereference an uninitialized pointer, read/write past allocated array memory, or write to read-only code segments.",
    hint: "Invalid memory address access.",
    level: "intermediate"
  },
  {
    question: "What is the role of an Assembler in GCC pipeline?",
    shortAnswer: "Translates assembly code (.s) into machine code object files (.o).",
    explanation: "The assembler takes human-readable assembly instructions (e.g. MOV, ADD, PUSH) and translates them into binary CPU instructions specific to the target architecture (x86_64, ARM).",
    hint: "Assembly text to binary opcodes.",
    level: "intermediate"
  },
  {
    question: "What is static linking vs dynamic linking?",
    shortAnswer: "Static linking copies library code into binary; dynamic linking links shared libraries at runtime.",
    explanation: "Static binaries (.a / .lib) are self-contained but larger. Dynamic binaries (.so / .dll) rely on system shared libraries at runtime, keeping executable size smaller.",
    hint: "Static = self-contained; Dynamic = shared runtime libraries.",
    level: "advanced"
  },
  {
    question: "How does C handle whitespace and free-form code layout?",
    shortAnswer: "C is a free-form language; spaces, tabs, and newlines are ignored except inside strings and tokens.",
    explanation: "Statements are terminated by semicolons (;), not newlines. Code formatting and indentation improve human readability without affecting compilation output.",
    hint: "Semicolons define statements, not line breaks.",
    level: "basic"
  },
  {
    question: "What is the size of standard integer types in C?",
    shortAnswer: "Size depends on target CPU architecture and compiler data model (usually 4 bytes for int on 32/64-bit systems).",
    explanation: "The C standard specifies minimum byte guarantees: char is 1 byte, short is at least 2 bytes, int is at least 2 bytes (usually 4), and long is at least 4 bytes (8 on 64-bit Linux).",
    hint: "Use sizeof(int) or <stdint.h> fixed-width types for precision.",
    level: "intermediate"
  },
  {
    question: "What is an entry point function in C?",
    shortAnswer: "The main() function is the designated entry point where program execution begins.",
    explanation: "When an OS launches an executable, the C runtime startup code (crt0) initializes global state and passes control directly to main().",
    hint: "Every standalone executable C program must have exactly one main function.",
    level: "basic"
  },
  {
    question: "What is buffer flushing in stdout?",
    shortAnswer: "Writing buffered output characters to the display screen immediately.",
    explanation: "printf output is line-buffered. Adding '\\n' or calling fflush(stdout) forces the buffer to output text to terminal immediately.",
    hint: "Always add \\n or fflush(stdout) when debugging output.",
    level: "intermediate"
  },
  {
    question: "What are escape sequences in C?",
    shortAnswer: "Special character combinations preceded by backslash (\\) representing unprintable or control characters.",
    explanation: "Common escape sequences include \\n (newline), \\t (tab), \\\\ (backslash), \\\" (double quote), and \\a (alert bell).",
    hint: "\\n = newline, \\t = horizontal tab.",
    level: "basic"
  },
  {
    question: "Why should beginner C programmers avoid conio.h and getch()?",
    shortAnswer: "conio.h is a non-standard MS-DOS header that fails to compile on Linux/macOS and modern compilers.",
    explanation: "Using non-standard headers breaks cross-platform portability. Beginners should use standard getchar() or fgets() from <stdio.h> instead.",
    hint: "Stick to standard <stdio.h> for portable code.",
    level: "basic"
  }
];

export default questions;
