const questions = [
  {
    question: "What is a wireless network?",
    shortAnswer: "A network that uses radio waves (or infrared) to transmit data without cables.",
    explanation: "Wireless networks provide mobility and flexibility using technologies like Wi-Fi, Bluetooth, and cellular.",
    hint: "How does your phone connect to the internet when you're not plugged in?",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are the main types of wireless networks?",
    shortAnswer: "Wi-Fi (WLAN), Bluetooth (PAN), Zigbee (IoT), Cellular (4G/5G), WiMAX, and Satellite.",
    explanation: "Each type serves different ranges, speeds, and use cases.",
    hint: "Think about the different ways you connect your devices.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is Wi-Fi and what standards does it use?",
    shortAnswer: "Wi-Fi is a wireless LAN technology based on IEEE 802.11 standards (Wi-Fi 4, 5, 6).",
    explanation: "Wi-Fi operates in 2.4 GHz, 5 GHz, and 6 GHz bands, with speeds up to 9.6 Gbps (Wi-Fi 6).",
    hint: "The wireless you use at home or in a café.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the difference between Wi-Fi and cellular networks?",
    shortAnswer: "Wi-Fi is for local area (short range); cellular (4G/5G) is for wide area (km range).",
    explanation: "Wi-Fi is typically privately owned and free, while cellular is carrier-provided and subscription-based.",
    hint: "One is for your home, the other for your mobile phone.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is Bluetooth used for?",
    shortAnswer: "Bluetooth is a short-range wireless technology for connecting personal devices (PAN).",
    explanation: "Used for wireless earbuds, keyboards, file sharing, and IoT.",
    hint: "Wireless earbuds and smartwatches.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is Zigbee and where is it commonly used?",
    shortAnswer: "Zigbee is a low-power, mesh networking protocol for IoT devices like smart bulbs and sensors.",
    explanation: "It operates in the 2.4 GHz band and is used in home automation.",
    hint: "Smart home devices that don't use Wi-Fi.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the typical range of Wi-Fi?",
    shortAnswer: "Indoors up to 100 meters, outdoors up to 100+ meters depending on obstacles and equipment.",
    explanation: "Range is affected by walls, interference, and the Wi-Fi standard.",
    hint: "How far can you be from your router?",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are the advantages of wireless networks?",
    shortAnswer: "Mobility, scalability, cost-effectiveness, flexibility, and quick deployment.",
    explanation: "No cabling required, easy to add devices, and supports moving users.",
    hint: "Why do we prefer wireless over wired in many cases?",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are the disadvantages of wireless networks?",
    shortAnswer: "Interference, security risks, limited range, shared bandwidth, and environmental effects.",
    explanation: "Wireless signals can be blocked, intercepted, or degraded.",
    hint: "Why might your Wi-Fi be slow or drop?",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is interference and how does it affect wireless networks?",
    shortAnswer: "Interference is disruption from other signals (microwave, neighbouring Wi-Fi) causing performance issues.",
    explanation: "It leads to lower throughput, higher latency, and packet loss.",
    hint: "Your Wi-Fi slows down when you use the microwave.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the difference between 2.4 GHz and 5 GHz Wi-Fi?",
    shortAnswer: "2.4 GHz has longer range but lower speed; 5 GHz has shorter range but higher speed.",
    explanation: "2.4 GHz is more crowded (interference); 5 GHz is cleaner but less penetrative.",
    hint: "Choose based on distance and speed needs.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is MU-MIMO in Wi-Fi?",
    shortAnswer: "Multi-User Multiple Input Multiple Output allows an AP to communicate with multiple clients simultaneously.",
    explanation: "Improves efficiency and throughput in dense environments.",
    hint: "AP talking to several devices at once.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is OFDMA in Wi-Fi 6?",
    shortAnswer: "Orthogonal Frequency Division Multiple Access divides a channel into smaller sub-channels for multiple users.",
    explanation: "Reduces latency and improves efficiency in high-density scenarios.",
    hint: "Splitting the highway into many lanes.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between WPA2 and WPA3?",
    shortAnswer: "WPA3 is the latest Wi-Fi security standard, offering stronger encryption (SAE) and improved authentication.",
    explanation: "WPA3 protects against brute-force attacks and provides better forward secrecy.",
    hint: "Newer is more secure.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a wireless access point (AP)?",
    shortAnswer: "A device that connects wireless clients to a wired network, bridging Wi-Fi and Ethernet.",
    explanation: "APs broadcast SSID and manage client associations.",
    hint: "The device that broadcasts your Wi-Fi signal.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a wireless mesh network?",
    shortAnswer: "A network where each node relays data for other nodes, extending coverage and providing redundancy.",
    explanation: "Used in smart home Zigbee and some Wi-Fi systems (mesh routers).",
    hint: "Devices that talk to each other to cover a larger area.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of 5G in wireless networking?",
    shortAnswer: "5G provides ultra-low latency, high bandwidth, and massive device connectivity for mobile and IoT.",
    explanation: "5G uses mmWave and sub-6 GHz frequencies, enabling applications like autonomous vehicles.",
    hint: "The next generation of mobile networks.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do you secure a Wi-Fi network?",
    shortAnswer: "Use WPA3 encryption, strong password, disable WPS, and use a guest network.",
    explanation: "Avoid open networks and regularly update firmware.",
    hint: "Lock down your Wi-Fi.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a site survey in wireless networking?",
    shortAnswer: "A process of analysing coverage, interference, and client density to optimise AP placement.",
    explanation: "Using tools to measure signal strength and identify dead zones.",
    hint: "Mapping your wireless coverage.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the maximum speed of Wi-Fi 6?",
    shortAnswer: "Up to 9.6 Gbps (theoretical).",
    explanation: "Real-world speeds are lower due to interference and client limitations.",
    hint: "Very fast, but not quite the theoretical max.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is signal-to-noise ratio (SNR) and why is it important?",
    shortAnswer: "SNR measures the ratio of signal power to noise; higher SNR means better link quality.",
    explanation: "Low SNR leads to errors and slower speeds.",
    hint: "How much signal vs. background noise.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is beamforming in Wi-Fi?",
    shortAnswer: "Beamforming focuses the Wi-Fi signal towards the client, improving range and throughput.",
    explanation: "Uses antenna arrays to direct the signal.",
    hint: "A spotlight instead of a floodlight.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the impact of channel bonding in Wi-Fi?",
    shortAnswer: "Channel bonding combines adjacent channels to increase bandwidth but may cause interference.",
    explanation: "Wider channels (e.g., 80 MHz) give more speed but are more susceptible to interference.",
    hint: "Wider lane for faster traffic, but more chance of collision.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does Wi-Fi roaming work?",
    shortAnswer: "Client devices switch between APs seamlessly, using protocols like 802.11k/v/r.",
    explanation: "Roaming ensures uninterrupted connectivity as users move.",
    hint: "Moving from one AP to another without dropping connection.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the difference between 4G and 5G in terms of latency?",
    shortAnswer: "4G latency is ~30-50 ms; 5G latency is <10 ms, enabling real-time applications.",
    explanation: "Low latency is critical for autonomous driving and AR/VR.",
    hint: "5G is much faster in response time.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of the spectrum in wireless networks?",
    shortAnswer: "Spectrum is the range of radio frequencies; allocation is regulated by governments (e.g., FCC).",
    explanation: "Different bands (licensed vs. unlicensed) affect performance and availability.",
    hint: "Radio frequencies are like roads for data.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the hidden node problem in Wi-Fi?",
    shortAnswer: "Two clients can't hear each other but both can hear the AP, causing collisions.",
    explanation: "RTS/CTS (Request to Send/Clear to Send) mechanism mitigates this.",
    hint: "Two people talking to the same person but can't hear each other.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the difference between contention-based and scheduled access in wireless?",
    shortAnswer: "Contention-based (Wi-Fi) uses CSMA/CA; scheduled access (cellular) allocates time slots.",
    explanation: "Scheduled access reduces collisions and is more efficient.",
    hint: "Wi-Fi tries to avoid collisions; cellular assigns slots.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the significance of the 6 GHz band for Wi-Fi 6E?",
    shortAnswer: "6 GHz provides additional spectrum with less interference, enabling high-speed, low-latency connections.",
    explanation: "It doubles the available spectrum for Wi-Fi.",
    hint: "A new, uncrowded highway for Wi-Fi.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does wireless network capacity scale with more users?",
    shortAnswer: "Capacity decreases as more users share the same channel; techniques like OFDMA and MU-MIMO help.",
    explanation: "Managing density requires careful planning and advanced technologies.",
    hint: "More users mean less bandwidth per user.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;