const topic14_questions = [
  {
    question: "Which four Access Modifiers can be applied to constructors in Java?",
    shortAnswer: "1. public (universal access), 2. protected (package + subclasses), 3. package-private / default (same package only), 4. private (declaring class only).",
    explanation: "Constructor access modifiers govern who is permitted to instantiate the class from different package locations.",
    hint: "public, protected, package-private, private.",
    level: "Beginner",
    codeExample: "public A() {}\nprotected A(int x) {}\nA(String s) {}\nprivate A(double d) {}"
  },
  {
    question: "What is the access modifier of the default constructor generated by the compiler?",
    shortAnswer: "The default constructor has the EXACT same access modifier as the class declaration (public if class is public, package-private if class is package-private).",
    explanation: "A public class gets a public default constructor; a package-private class gets a package-private default constructor.",
    hint: "Inherits class visibility.",
    level: "Intermediate",
    codeExample: "public class Trainee {} // Constructor is public\nclass Trainee {} // Constructor is package-private"
  },
  {
    question: "Can a constructor be declared with 'protected' visibility?",
    shortAnswer: "Yes. Protected constructors allow instantiation from within the same package, and allow subclasses in other packages to invoke 'super()' on it.",
    explanation: "Protected constructors are common in framework base classes (e.g. Spring, Hibernate template classes).",
    hint: "Allows subclass super() calls and same package instantiation.",
    level: "Intermediate",
    codeExample: "protected BaseService() {}"
  }
];

export default topic14_questions;