export const topic4Questions = [
  {
    question: "Why are large C projects structured into multiple source (.c) and header (.h) files?",
    answer: "Multi-file architecture promotes modular decomposition, encapsulation, independent incremental compilation (recompiling only modified files), and team collaboration."
  },
  {
    question: "What is the difference between a declaration and a definition in C?",
    answer: "A declaration announces the name and type signature of a symbol without allocating memory (e.g. extern int x; or int add(int, int);). A definition creates the entity and allocates physical storage (e.g. int x = 5; or function body { ... })."
  },
  {
    question: "What does the 'extern' keyword do when applied to a global variable?",
    answer: "'extern int count;' declares that 'count' exists and is defined in another translation unit, allowing other .c files to access it without allocating duplicate memory."
  },
  {
    question: "What does the 'static' keyword do when applied to a global function or variable?",
    answer: "It grants the function or variable Internal Linkage, making it completely private and invisible to other translation units, preventing symbol name collisions."
  },
  {
    question: "What is the difference between External Linkage and Internal Linkage?",
    answer: "Symbols with External Linkage (regular functions and non-static globals) can be referenced across different .c files by the linker. Symbols with Internal Linkage (static functions and file-scope static variables) are restricted strictly to their own .c file."
  },
  {
    question: "What causes a 'multiple definition of symbol' linker error?",
    answer: "Defining the same non-static global variable or function in more than one .c file (or defining a variable in a header file included by multiple .c files)."
  },
  {
    question: "What causes an 'undefined reference to symbol' linker error?",
    answer: "Declaring a function or variable (e.g. in a header) and calling it in main.c, but failing to compile or link the .c file (or library) where the function is actually defined."
  },
  {
    question: "What should be placed in header (.h) files?",
    answer: "1. Struct, union, enum, and typedef declarations\n2. Function prototypes\n3. extern global variable declarations\n4. Macro definitions (#define)\n5. static inline function implementations"
  },
  {
    question: "What should NEVER be placed in header (.h) files?",
    answer: "Non-static global variable definitions (e.g. int x = 0;) and non-inline function implementations with bodies { ... }."
  },
  {
    question: "What is an Object File (.o / .obj)?",
    answer: "A relocatable machine code file generated by the compiler (gcc -c) from a single translation unit containing compiled instructions and an unresolved symbol table."
  },
  {
    question: "What is the role of the Linker (ld) in a multi-file C project?",
    answer: "The Linker combines multiple .o object files and static/dynamic libraries into a single final executable binary, resolving cross-module function and variable address references."
  },
  {
    question: "How do you compile a multi-file project with GCC in a single step?",
    answer: "gcc -Wall -Wextra main.c module1.c module2.c -o myapp"
  },
  {
    question: "How do you compile a multi-file project using separate compilation steps?",
    answer: "1. gcc -c module1.c -o module1.o\n2. gcc -c module2.c -o module2.o\n3. gcc -c main.c -o main.o\n4. gcc main.o module1.o module2.o -o myapp"
  },
  {
    question: "What is Incremental Compilation and why is it faster?",
    answer: "When modifying one .c file in a 1,000-file project, only that single .c file is recompiled into its .o file, followed by a quick relink, saving hours of rebuild time."
  },
  {
    question: "What is an Opaque Pointer (Incomplete Type) pattern in C?",
    answer: "Declaring 'typedef struct Engine Engine;' in engine.h without defining its members. Callers can only hold 'Engine *' pointers and must call API functions (like engine_start(e)), providing pure object-oriented encapsulation."
  },
  {
    question: "How does the Opaque Pointer pattern prevent client code from breaking on internal struct changes?",
    answer: "Because client code never sees the internal struct members, changes to private struct fields do not require recompiling client translation units or breaking binary compatibility."
  },
  {
    question: "What is a Static Library (.a / .lib)?",
    answer: "An archive of .o object files (created via 'ar rcs libmylib.a foo.o bar.o') that is linked directly into the application executable at build time."
  },
  {
    question: "What is a Shared / Dynamic Library (.so / .dll)?",
    answer: "A compiled binary library loaded into memory at program launch or runtime, shared across multiple running processes to save disk space and RAM."
  },
  {
    question: "What is the One Definition Rule (ODR) in C?",
    answer: "Every identifier with external linkage must have exactly one definition across the entire program."
  },
  {
    question: "What is Name Mangling and why does C NOT have it?",
    answer: "Name mangling encodes function parameter types into symbol names (used in C++ for overloading). C uses plain symbol names, which is why C does not support function overloading."
  },
  {
    question: "How do you call a C function from C++ code without linker errors?",
    answer: "Wrap the C header prototypes in: #ifdef __cplusplus\nextern \"C\" {\n#endif\n/* prototypes */\n#ifdef __cplusplus\n}\n#endif"
  },
  {
    question: "What is the nm utility in Linux/GCC?",
    answer: "'nm myapp.o' lists all symbols (functions and variables) defined in or needed by an object file, showing whether they are local (t), global (T), or undefined (U)."
  },
  {
    question: "How do you prevent global namespace pollution in large C codebases?",
    answer: "Prefix all public API functions with a module namespace (e.g. math_matrix_multiply) and mark all private internal helper functions as 'static'."
  },
  {
    question: "What is a 'Tentative Definition' in C?",
    answer: "Writing 'int x;' at file scope without an initializer is a tentative definition. If no other definition with an initializer appears in the translation unit, the compiler initializes it to 0."
  },
  {
    question: "How does multi-file architecture enable unit testing in C?",
    answer: "Modules can be compiled and linked independently against dedicated test harnesses (like Unity or Criterion) without running the main application entry point."
  }
];
