// topic5_questions.js
// 30 FAQs on "Operator Associativity" – basic to expert.

const questions = [
  {
    question: "What is operator associativity?",
    shortAnswer: "It determines the order of evaluation when operators of the same precedence appear in an expression.",
    explanation: "Associativity can be left‑to‑right or right‑to‑left. It's only relevant when there are multiple operators at the same precedence level.",
    hint: "It's about grouping when precedence is equal.",
    level: "basic",
    codeExample: "int x = 10 - 3 - 2; // left‑associative: (10-3)-2 = 5",
  },
  {
    question: "What is the difference between left‑associative and right‑associative?",
    shortAnswer: "Left‑associative evaluates from left to right; right‑associative from right to left.",
    explanation: "Most binary operators are left‑associative, while assignment and ternary are right‑associative.",
    hint: "Left‑associative groups on the left; right‑associative on the right.",
    level: "basic",
    codeExample: "a - b - c → (a - b) - c (left)\na = b = c → a = (b = c) (right)",
  },
  {
    question: "Which operators are left‑associative?",
    shortAnswer: "Most binary operators: arithmetic (`+`, `-`, `*`, `/`, `%`), relational (`<`, `>`, `==`), logical (`&&`, `||`), bitwise, and postfix operators.",
    explanation: "They group from the left.",
    hint: "These are the common ones you use every day.",
    level: "basic",
    codeExample: "int result = 10 / 5 * 2; // (10/5)*2 = 4",
  },
  {
    question: "Which operators are right‑associative?",
    shortAnswer: "Assignment operators (`=`, `+=`, etc.), the ternary operator (`? :`), and prefix unary operators (`++`, `--`, `!`, `~`, etc.).",
    explanation: "They group from the right.",
    hint: "Less common but important.",
    level: "intermediate",
    codeExample: "int a = b = c = 5; // c=5, b=c, a=b",
  },
  {
    question: "How does associativity affect `a - b - c`?",
    shortAnswer: "It evaluates as `(a - b) - c` because subtraction is left‑associative.",
    explanation: "If subtraction were right‑associative, it would be `a - (b - c)`.",
    hint: "Think of how you'd read it left to right.",
    level: "basic",
    codeExample: "int result = 10 - 3 - 2; // 5",
  },
  {
    question: "What is the associativity of `&&` and `||`?",
    shortAnswer: "Both are left‑associative.",
    explanation: "So `a && b && c` is `(a && b) && c`. This is rarely an issue because AND and OR are associative in logic.",
    hint: "They work left to right.",
    level: "intermediate",
    codeExample: "boolean b = true && false && true; // (true && false) && true = false",
  },
  {
    question: "What is the associativity of assignment?",
    shortAnswer: "Assignment is right‑associative.",
    explanation: "This allows chaining: `a = b = c` means `a = (b = c)`.",
    hint: "Right to left.",
    level: "basic",
    codeExample: "int a, b, c; a = b = c = 5;",
  },
  {
    question: "What is the associativity of the ternary operator?",
    shortAnswer: "The ternary operator `? :` is right‑associative.",
    explanation: "So `a ? b : c ? d : e` is parsed as `a ? b : (c ? d : e)`.",
    hint: "Nested ternaries are evaluated from right to left.",
    level: "intermediate",
    codeExample: "int result = a > b ? a : b > c ? b : c; // right‑associative",
  },
  {
    question: "Are unary operators left‑ or right‑associative?",
    shortAnswer: "Prefix unary operators are right‑associative; postfix unary operators are left‑associative.",
    explanation: "For example, `+ + x` is `+ (+ x)`, while `x++--` is invalid.",
    hint: "Postfix binds tighter and is left, prefix is right.",
    level: "advanced",
    codeExample: "int a = 5; int b = - - a; // -(-a) = 5",
  },
  {
    question: "How does associativity affect `a + b + c`?",
    shortAnswer: "It's `(a + b) + c` because addition is left‑associative.",
    explanation: "For addition, associativity doesn't change the result because addition is mathematically associative, but it matters for order of evaluation (e.g., side effects).",
    hint: "Mathematically same but could affect side effects.",
    level: "intermediate",
    codeExample: "// left‑associative: (a + b) + c",
  },
  {
    question: "Why does associativity matter even if the result is the same?",
    shortAnswer: "Because of side effects – if operands have side effects (e.g., method calls that modify state), the order matters.",
    explanation: "For pure values, associativity may not change the result, but for impure expressions, it does.",
    hint: "Think about function calls in operands.",
    level: "advanced",
    codeExample: "int result = methodA() + methodB() + methodC(); // order depends on associativity",
  },
  {
    question: "What is the associativity of `*` and `/`?",
    shortAnswer: "They are left‑associative.",
    explanation: "So `a / b * c` is `(a / b) * c`.",
    hint: "Left to right.",
    level: "basic",
    codeExample: "int result = 12 / 3 * 2; // (12/3)*2 = 8",
  },
  {
    question: "What is the associativity of `%`?",
    shortAnswer: "The modulo operator `%` is left‑associative.",
    explanation: "So `a % b % c` is `(a % b) % c`.",
    hint: "Same as other multiplicative operators.",
    level: "basic",
    codeExample: "int result = 17 % 5 % 3; // (17%5)%3 = 2%3 = 2",
  },
  {
    question: "How does associativity affect bitwise operators?",
    shortAnswer: "Bitwise operators (`&`, `^`, `|`) are left‑associative.",
    explanation: "So `a & b & c` is `(a & b) & c`.",
    hint: "They're like arithmetic.",
    level: "intermediate",
    codeExample: "int flags = 0b1010 & 0b1100 & 0b1111; // left‑associative",
  },
  {
    question: "Can you change associativity with parentheses?",
    shortAnswer: "Yes, parentheses override both precedence and associativity.",
    explanation: "You can force a different grouping by using parentheses.",
    hint: "Parentheses are the ultimate tool.",
    level: "basic",
    codeExample: "int result = 10 - (3 - 2); // changes associativity",
  },
  {
    question: "What is the associativity of `instanceof`?",
    shortAnswer: "`instanceof` is left‑associative, but it's rare to chain it.",
    explanation: "You'd use parentheses if you need to combine.",
    hint: "Left‑associative.",
    level: "intermediate",
    codeExample: "// Not commonly chained",
  },
  {
    question: "Is the string concatenation `+` left‑ or right‑associative?",
    shortAnswer: "It's left‑associative, same as numeric addition.",
    explanation: "So `\"Hello\" + 5 + 3` is `(\"Hello\" + 5) + 3` => `\"Hello53\"`.",
    hint: "Left to right.",
    level: "intermediate",
    codeExample: "String s = \"Hello\" + 5 + 3; // \"Hello53\"",
  },
  {
    question: "What is the associativity of the cast operator?",
    shortAnswer: "Cast is right‑associative, but usually applied to a single operand.",
    explanation: "It's a unary operator with high precedence.",
    hint: "Right‑associative.",
    level: "advanced",
    codeExample: "double d = (double) 5 / 2; // (double)5 / 2",
  },
  {
    question: "How does associativity affect `a = b += c`?",
    shortAnswer: "Assignment is right‑associative, so `a = b += c` is parsed as `a = (b += c)`.",
    explanation: "The right side is evaluated first.",
    hint: "Right to left.",
    level: "intermediate",
    codeExample: "int a, b=5, c=3; a = b += c; // b becomes 8, a becomes 8",
  },
  {
    question: "What is the associativity of prefix `++` and `--`?",
    shortAnswer: "Prefix increment and decrement are right‑associative.",
    explanation: "So `++ ++ a` is invalid because `++a` is not a variable, but `- - a` is parsed as `- (- a)`.",
    hint: "Right‑associative.",
    level: "advanced",
    codeExample: "int a = 5; int b = - - a; // b = 5",
  },
  {
    question: "What is the associativity of postfix `++` and `--`?",
    shortAnswer: "Postfix increment and decrement are left‑associative.",
    explanation: "They have the highest precedence and are left‑associative.",
    hint: "Left‑associative.",
    level: "basic",
    codeExample: "int i = 5; int j = i++ + i++; // left‑associative: (i++) + (i++)",
  },
  {
    question: "Is `&&` associative?",
    shortAnswer: "Yes, logical AND is associative in mathematics, but in Java it's left‑associative for evaluation order.",
    explanation: "Since `&&` short‑circuits, the evaluation order matters for side effects.",
    hint: "Left‑associative.",
    level: "intermediate",
    codeExample: "boolean b = methodA() && methodB() && methodC(); // left‑associative",
  },
  {
    question: "What is the effect of right‑associativity on chained ternaries?",
    shortAnswer: "It means nested ternaries are grouped from the right.",
    explanation: "Example: `a ? b : c ? d : e` → `a ? b : (c ? d : e)`.",
    hint: "Right‑associative.",
    level: "intermediate",
    codeExample: "int result = x > 0 ? 1 : y > 0 ? 2 : 3; // right‑associative",
  },
  {
    question: "Do all languages use the same associativity rules?",
    shortAnswer: "No, languages may have different precedence and associativity rules.",
    explanation: "Java's rules are well‑defined; other languages like C or Python may differ.",
    hint: "Check the language spec.",
    level: "advanced",
    codeExample: "// Not applicable",
  },
  {
    question: "How can you avoid associativity pitfalls?",
    shortAnswer: "Always use parentheses to make the intended order explicit.",
    explanation: "Even if you know the rules, parentheses improve readability and prevent bugs.",
    hint: "Parentheses are your friend.",
    level: "basic",
    codeExample: "int result = (a - b) - c; // explicit",
  },
  {
    question: "What is the associativity of `^` (XOR)?",
    shortAnswer: "`^` is left‑associative.",
    explanation: "So `a ^ b ^ c` is `(a ^ b) ^ c`.",
    hint: "Left‑associative like bitwise AND.",
    level: "intermediate",
    codeExample: "int result = 0b1010 ^ 0b1100 ^ 0b1111;",
  },
  {
    question: "What is the associativity of shift operators?",
    shortAnswer: "Shift operators (`<<`, `>>`, `>>>`) are left‑associative.",
    explanation: "So `a << b << c` is `(a << b) << c`.",
    hint: "Left‑associative.",
    level: "advanced",
    codeExample: "int result = 8 << 1 << 2; // (8<<1)<<2 = 16<<2 = 64",
  },
  {
    question: "How does associativity affect `a / b / c`?",
    shortAnswer: "It's `(a / b) / c` because division is left‑associative.",
    explanation: "This is different from `a / (b / c)`.",
    hint: "Left‑associative.",
    level: "basic",
    codeExample: "int result = 100 / 10 / 2; // (100/10)/2 = 5",
  },
  {
    question: "What is the associativity of `?:` in Java?",
    shortAnswer: "Right‑associative.",
    explanation: "This allows nesting without parentheses, but parentheses are recommended.",
    hint: "Right‑associative.",
    level: "intermediate",
    codeExample: "int max = a > b ? a : b > c ? b : c; // right‑associative",
  },
  {
    question: "Can you mix left and right associative operators without parentheses?",
    shortAnswer: "Yes, but it can be confusing and error‑prone.",
    explanation: "Java's grammar handles it, but for readability, use parentheses.",
    hint: "Avoid mixing without parentheses.",
    level: "advanced",
    codeExample: "int result = a = b + c; // assignment is right, addition is left, works fine",
  },
  {
    question: "Why is it important to know associativity?",
    shortAnswer: "To correctly predict how expressions are evaluated, especially with chains of operators at the same precedence.",
    explanation: "It helps prevent logic errors and improves code understanding.",
    hint: "It's a fundamental part of expression evaluation.",
    level: "basic",
    codeExample: "Not applicable",
  },
];

export default questions;