/**
 * Topic 11 Questions: Common .gitignore Templates (Node, Python, Java, IDEs)
 * Module: 001_002_git-three-tree-architecture-and-basic-workflow
 * Educator: Sukanta Hui (Coder & AccoTax, Barrackpore)
 */

const topic11_questions = [
  {
    id: 1,
    question: "Why should `node_modules/` NEVER be committed to a Git repository?",
    options: [
      "`node_modules` contains thousands of nested platform-dependent files exceeding hundreds of megabytes that can be cleanly reproduced via `package.json` and `npm install`",
      "Git does not allow folders starting with the letter 'n'",
      "Because npm automatically deletes Git repositories",
      "Because GitHub charges $10 per node module"
    ],
    correctAnswer: 0,
    explanation: "Dependencies are deterministic and platform-specific; committing `node_modules` causes massive repository bloat and merge conflicts across operating systems."
  },
  {
    id: 2,
    question: "In Python projects, what does the rule `__pycache__/` ignore?",
    options: [
      "Compiled Python bytecode directory generated automatically by the CPython runtime",
      "Python source code files",
      "User passwords",
      "Python unit tests"
    ],
    correctAnswer: 0,
    explanation: "`__pycache__/` holds compiled `.pyc` bytecode files generated during execution, which should never be tracked."
  },
  {
    id: 3,
    question: "Which pattern properly ignores Python virtual environments created by `venv` or `virtualenv`?",
    options: [
      ".venv/\nvenv/\nenv/",
      "python.env",
      "virtual/",
      "*.pyvenv"
    ],
    correctAnswer: 0,
    explanation: "Standard virtual environment folders are `.venv/`, `venv/`, and `env/`."
  },
  {
    id: 4,
    question: "In Java/Maven projects, what directory holds compiled `.class` binaries and package artifacts that should be ignored?",
    options: [
      "target/",
      "src/",
      "pom.xml",
      "java_bin/"
    ],
    correctAnswer: 0,
    explanation: "Maven outputs all compiled `.class` files, test reports, and `.jar` artifacts into the `target/` directory."
  },
  {
    id: 5,
    question: "In Gradle Java/Kotlin projects, which directory holds build outputs that should be ignored?",
    options: [
      "build/ and .gradle/",
      "gradlew",
      "gradle/wrapper/",
      "settings.gradle"
    ],
    correctAnswer: 0,
    explanation: "Gradle stores transient build outputs in `build/` and internal cache in `.gradle/`."
  },
  {
    id: 6,
    question: "In Gradle projects, should `gradle/wrapper/gradle-wrapper.jar` be ignored in `.gitignore`?",
    options: [
      "No! The Gradle wrapper jar is required so developers and CI systems can run `./gradlew` without pre-installing Gradle",
      "Yes, all `.jar` files must be ignored",
      "Only on Windows",
      "Only in Kotlin projects"
    ],
    correctAnswer: 0,
    explanation: "The Gradle wrapper JAR is an exception: it is needed to execute `./gradlew` and is preserved with `!gradle/wrapper/gradle-wrapper.jar`."
  },
  {
    id: 7,
    question: "Which folder generated by JetBrains IDEs (IntelliJ IDEA, WebStorm, PyCharm) should typically be ignored?",
    options: [
      ".idea/ and *.iml",
      ".vscode/",
      "jetbrains.txt",
      "ide_cache/"
    ],
    correctAnswer: 0,
    explanation: "`.idea/` and `*.iml` contain JetBrains project and workspace metadata."
  },
  {
    id: 8,
    question: "Which VS Code files are safe/recommended to commit for team consistency?",
    options: [
      "Shared project configs like `.vscode/settings.json`, `.vscode/extensions.json`, and `.vscode/launch.json`",
      "The entire `.vscode/` folder including personal user cache",
      "Zero VS Code files ever",
      "VS Code installer"
    ],
    correctAnswer: 0,
    explanation: "Team-shared launch configurations, recommended extensions, and formatting settings in `.vscode/` can be committed while ignoring personal cache."
  },
  {
    id: 9,
    question: "What macOS operating system metadata file is commonly ignored across all repositories?",
    options: [
      ".DS_Store",
      "desktop.ini",
      "Thumbs.db",
      "mac.sys"
    ],
    correctAnswer: 0,
    explanation: "`.DS_Store` (Desktop Services Store) is created automatically by macOS Finder and should always be ignored."
  },
  {
    id: 10,
    question: "What Windows operating system files should be ignored in `.gitignore`?",
    options: [
      "Thumbs.db and desktop.ini",
      "explorer.exe",
      "win.ini",
      "system32.dll"
    ],
    correctAnswer: 0,
    explanation: "`Thumbs.db` (thumbnail cache) and `desktop.ini` are Windows Explorer metadata files."
  },
  {
    id: 11,
    question: "In Next.js and Nuxt.js React/Vue applications, what build directories must be ignored?",
    options: [
      ".next/ and .nuxt/",
      "pages/",
      "components/",
      "public/"
    ],
    correctAnswer: 0,
    explanation: "`.next/` and `.nuxt/` are transient compilation and server-side cache directories."
  },
  {
    id: 12,
    question: "Should lockfiles (`package-lock.json`, `yarn.lock`, `pnpm-lock.yaml`, `poetry.lock`) be ignored in `.gitignore` for applications?",
    options: [
      "NO! Lockfiles MUST be committed to ensure exact, reproducible dependency trees across all developer machines and production CI/CD builds",
      "Yes, lockfiles cause merge conflicts so they should always be ignored",
      "Only ignore package-lock.json",
      "Only ignore yarn.lock"
    ],
    correctAnswer: 0,
    explanation: "Lockfiles guarantee deterministic dependency resolution. Ignoring them causes 'works on my machine' production bugs."
  },
  {
    id: 13,
    question: "What online open-source repository maintains canonical `.gitignore` templates for virtually all programming languages?",
    options: [
      "github/gitignore",
      "npm/ignore",
      "w3c/gitignore",
      "git/templates"
    ],
    correctAnswer: 0,
    explanation: "GitHub maintains the official, community-curated `github/gitignore` repository."
  },
  {
    id: 14,
    question: "What CLI utility or web service lets you generate merged `.gitignore` templates for multiple tech stacks (e.g. Node + VSCode + macOS)?",
    options: [
      "gitignore.io (or `npx gitignore`)",
      "git init --all-templates",
      "npm template",
      "docker-compose"
    ],
    correctAnswer: 0,
    explanation: "gitignore.io allows developers to enter keywords like `Node,VisualStudioCode,macOS` and generate a composite `.gitignore` file."
  },
  {
    id: 15,
    question: "In a monorepo containing both a Python backend and a React frontend, what is the best `.gitignore` strategy?",
    options: [
      "A root `.gitignore` covering shared OS/IDE rules, combined with tech-specific rules for `node_modules/`, `.venv/`, `dist/`, and `__pycache__/`",
      "Creating 50 separate git repositories",
      "Ignoring all files in the root",
      "Never using monorepos"
    ],
    correctAnswer: 0,
    explanation: "A unified root `.gitignore` (or modular subdirectory `.gitignore` files) cleanly manages multi-language monorepos."
  },
  {
    id: 16,
    question: "In Rust projects using Cargo, which directory contains build outputs that must be ignored?",
    options: [
      "target/",
      "src/",
      "Cargo.toml",
      "rust_bin/"
    ],
    correctAnswer: 0,
    explanation: "Cargo compiles all binary artifacts, dependencies, and debug builds into `target/`."
  },
  {
    id: 17,
    question: "In Go projects, what files/directories are typically ignored?",
    options: [
      "Compiled binaries (`*.exe`, `*.test`), `vendor/` (if using Go modules without vendoring), and coverage files",
      "go.mod and go.sum",
      "main.go",
      "All packages"
    ],
    correctAnswer: 0,
    explanation: "Go binaries and test output binaries should be ignored, while `go.mod` and `go.sum` are committed."
  },
  {
    id: 18,
    question: "In C and C++ projects, which files must be ignored?",
    options: [
      "Object files (`*.o`, `*.obj`), compiled executables (`*.exe`, `*.out`), and build directories (`build/`, `cmake-build-debug/`)",
      "Header files (`*.h`)",
      "Source files (`*.cpp`)",
      "CMakeLists.txt"
    ],
    correctAnswer: 0,
    explanation: "Compiled object files, libraries (`*.a`, `*.so`, `*.dll`), and build folders must be ignored."
  },
  {
    id: 19,
    question: "What does `*.log` ignore in a project?",
    options: [
      "All log files generated by servers, test runners, and debuggers across all directories",
      "Logarithmic math calculations",
      "Logos and images",
      "Login credentials"
    ],
    correctAnswer: 0,
    explanation: "`*.log` matches any file with the `.log` extension anywhere in the repository."
  },
  {
    id: 20,
    question: "What pattern ignores code coverage reports generated by test runners like Jest, Istanbul, or Pytest-cov?",
    options: [
      "coverage/ and .coverage",
      "test/",
      "spec/",
      "unit_tests/"
    ],
    correctAnswer: 0,
    explanation: "Coverage test outputs (HTML reports, lcov files) reside in `coverage/` or `.coverage`."
  },
  {
    id: 21,
    question: "If a developer accidentally pushes a 500MB `node_modules` folder to GitHub, what happens to clone speeds for the team?",
    options: [
      "Every developer and CI runner will be forced to download the 500MB blob history on every clone, crippling bandwidth and storage",
      "GitHub automatically deletes the node_modules folder",
      "Clone speed becomes 10x faster",
      "Nothing changes"
    ],
    correctAnswer: 0,
    explanation: "Once committed, large binary blobs permanently inflate the Git object database, slowing down every clone and checkout."
  },
  {
    id: 22,
    question: "In PHP / Composer projects, which directory contains vendor dependencies that must be ignored?",
    options: [
      "vendor/",
      "composer.json",
      "composer.lock",
      "app/"
    ],
    correctAnswer: 0,
    explanation: "Composer installs PHP packages into `vendor/`, which must be ignored."
  },
  {
    id: 23,
    question: "In Ruby on Rails projects, what files are typically ignored?",
    options: [
      "log/, tmp/, .bundle/, and config/master.key",
      "Gemfile and Gemfile.lock",
      "app/models/",
      "config/routes.rb"
    ],
    correctAnswer: 0,
    explanation: "Logs, temporary cache, local bundles, and encryption master keys (`config/master.key`) must be ignored."
  },
  {
    id: 24,
    question: "Why does Sukanta Hui insist that every student initialize `.gitignore` before writing their first line of code?",
    options: [
      "Because prevention is 100x easier than retroactive Git history cleaning (e.g. `git-filter-repo` or BFG)",
      "Because Git init fails without gitignore",
      "Because VS Code crashes without gitignore",
      "Because it is required by law"
    ],
    correctAnswer: 0,
    explanation: "Preventing accidental commits of secrets and bloat from day one avoids painful, destructive Git history rewriting later."
  },
  {
    id: 25,
    question: "Which of the following is the most comprehensive Node.js `.gitignore` snippet?",
    options: [
      "node_modules/\ndist/\nbuild/\n.env\n.env.local\n*.log\n.next/\ncoverage/",
      "ignore node",
      "*.js",
      "src/"
    ],
    correctAnswer: 0,
    explanation: "The first option accurately captures dependencies, build outputs, environment secrets, log files, framework caches, and test coverage."
  }
];

export default topic11_questions;
