const questions = [
  {
    question: "What is the primary difference between LAN and WAN?",
    shortAnswer: "LAN covers a small area (building/campus), WAN covers a large area (country/global).",
    explanation: "LANs are typically high-speed and privately owned; WANs are slower and often use public infrastructure.",
    hint: "Think about the size of the geography.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What does PAN stand for and what is its typical range?",
    shortAnswer: "Personal Area Network, up to 10 meters.",
    explanation: "PANs connect personal devices like phones, tablets, and wearables using Bluetooth or NFC.",
    hint: "Devices within your personal space.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a Metropolitan Area Network (MAN)?",
    shortAnswer: "A network that spans a city or metropolitan area.",
    explanation: "MANs typically use fiber optic cables or microwave links and are often owned by a city or large organisation.",
    hint: "Covers a city, like a municipal Wi-Fi network.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Give an example of a PAN.",
    shortAnswer: "Connecting a smartphone to a wireless earbud or smartwatch via Bluetooth.",
    explanation: "PANs are short-range and device-centric.",
    hint: "Devices you carry with you.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Give an example of a LAN.",
    shortAnswer: "A school or office network connecting computers and printers.",
    explanation: "LANs are typically wired (Ethernet) or wireless (Wi-Fi) and privately owned.",
    hint: "The network in your computer lab.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Give an example of a MAN.",
    shortAnswer: "A city-wide fiber network connecting government offices and schools.",
    explanation: "MANs are larger than LANs but smaller than WANs, often using fiber or wireless links.",
    hint: "Public Wi-Fi across a city.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Give an example of a WAN.",
    shortAnswer: "The Internet.",
    explanation: "The Internet is the largest WAN, connecting billions of devices globally.",
    hint: "What you use to visit websites.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Which network type typically has the highest speed?",
    shortAnswer: "LAN generally has the highest speed (up to 10 Gbps).",
    explanation: "Short distances and private ownership allow for high-speed Ethernet and Wi-Fi.",
    hint: "Think of the network type with the least distance.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Which network type covers the largest geographical area?",
    shortAnswer: "WAN covers the largest area (global).",
    explanation: "WANs span countries and continents.",
    hint: "The network that connects the world.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the typical latency of a LAN compared to a WAN?",
    shortAnswer: "LAN has very low latency; WAN has higher latency due to distance.",
    explanation: "Short distances mean less propagation delay, whereas long distances introduce more delay.",
    hint: "Signal travel time increases with distance.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Which network type uses technologies like Bluetooth and NFC?",
    shortAnswer: "PAN (Personal Area Network).",
    explanation: "PANs are designed for short-range, low-power communication between personal devices.",
    hint: "Wireless earbuds and smartwatches.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Which network type uses technologies like Ethernet and Wi-Fi?",
    shortAnswer: "LAN (Local Area Network).",
    explanation: "LANs commonly use Ethernet for wired connections and Wi-Fi for wireless.",
    hint: "Office and home networks.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the role of a router in connecting different network types?",
    shortAnswer: "Routers connect LANs to WANs, enabling internet access.",
    explanation: "Routers forward data between networks, using IP addresses for routing.",
    hint: "The device that connects your home network to the internet.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "Why are WANs generally slower than LANs?",
    shortAnswer: "Due to longer distances, more intermediate hops, and shared infrastructure.",
    explanation: "Data travels over public or leased lines, and congestion can occur.",
    hint: "Think of a long highway with many intersections.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the ownership model for a MAN?",
    shortAnswer: "Often owned by a city, municipality, or a consortium of organisations.",
    explanation: "MANs may be built to serve public or private needs within a metropolitan area.",
    hint: "It's like city infrastructure.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How can a LAN be connected to a WAN?",
    shortAnswer: "Through a router and a modem, using an ISP's service.",
    explanation: "The router connects the LAN to the ISP's network, which is part of the global WAN.",
    hint: "Your home router is the gateway.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between a MAN and a WAN in terms of ownership?",
    shortAnswer: "MAN is often owned by a city or organisation; WAN is typically a mix of ISPs and public infrastructure.",
    explanation: "MANs are more local and controlled; WANs involve multiple carriers.",
    hint: "Think of who you pay for connectivity.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the primary use of a PAN?",
    shortAnswer: "To connect personal devices for data exchange and synchronization.",
    explanation: "Examples include syncing a fitness tracker, sharing files between a phone and laptop.",
    hint: "Devices you own and carry.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What are the main challenges of a WAN compared to a LAN?",
    shortAnswer: "Higher latency, lower bandwidth, and increased security risks.",
    explanation: "WANs involve multiple networks and public exposure, requiring more careful management.",
    hint: "Think about the complexities of the internet.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a Virtual Private Network (VPN) and how does it relate to WAN?",
    shortAnswer: "A VPN extends a private network across a public WAN (like the internet) securely.",
    explanation: "VPNs encrypt data to provide secure communication over a WAN.",
    hint: "A secure tunnel through the internet.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do network types affect application design?",
    shortAnswer: "Applications must consider latency, bandwidth, and reliability of the network type.",
    explanation: "Real-time apps (gaming) need low latency (LAN/WAN with QoS); bulk transfers can tolerate higher latency.",
    hint: "A video call vs. a file download.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the concept of 'distance' in networking and how does it affect speed?",
    shortAnswer: "As distance increases, signal attenuation and propagation delay increase, reducing speed.",
    explanation: "This is why LANs are fast and WANs are slower.",
    hint: "The speed of light imposes physical limits.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of switches in a LAN?",
    shortAnswer: "Switches connect devices within a LAN, forwarding frames based on MAC addresses.",
    explanation: "They create a collision domain for each port, improving performance.",
    hint: "A smart hub that directs traffic.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of a modem in connecting a LAN to a WAN?",
    shortAnswer: "A modem modulates and demodulates signals to communicate over the WAN infrastructure (e.g., cable, DSL).",
    explanation: "It converts digital LAN signals to analog for transmission and vice versa.",
    hint: "Modulator-demodulator.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does a MAN differ from a WAN in terms of technology used?",
    shortAnswer: "MANs often use fiber optics and microwave; WANs use a mix of fiber, satellite, and leased lines.",
    explanation: "MANs are usually within a city and may use Metro Ethernet; WANs use long-haul technologies.",
    hint: "Think of metropolitan vs. intercontinental.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the significance of the OSI model layer 2 and layer 3 in these network types?",
    shortAnswer: "Layer 2 (Data Link) is dominant in LANs (MAC addresses); Layer 3 (Network) is crucial for WANs (IP routing).",
    explanation: "LANs use switching (Layer 2); WANs use routing (Layer 3).",
    hint: "LANs are switched; WANs are routed.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do wireless technologies fit into these categories?",
    shortAnswer: "Wireless can be used in PAN (Bluetooth), LAN (Wi-Fi), MAN (WiMAX, LTE), and WAN (satellite, cellular).",
    explanation: "Wireless is a transmission medium, not a network type; it can be applied at any scale.",
    hint: "Wi-Fi is LAN; 4G is WAN.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the concept of 'collision domain' and how does it differ between LAN and WAN?",
    shortAnswer: "Collision domains exist in LANs (especially with hubs); WANs are point-to-point and have no collisions.",
    explanation: "Switches eliminate collision domains; WAN links are full-duplex, avoiding collisions.",
    hint: "Collisions occur when multiple devices transmit simultaneously on shared media.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do routing protocols differ between LAN and WAN?",
    shortAnswer: "LANs often use simpler protocols (RIP, OSPF) inside an autonomous system; WANs may use BGP between autonomous systems.",
    explanation: "WANs require more complex routing to handle many networks.",
    hint: "Interior vs. exterior gateway protocols.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the future of network types with emerging technologies like 5G and satellite internet?",
    shortAnswer: "These technologies blur the lines – 5G can serve as a MAN or WAN; satellite internet provides global WAN coverage.",
    explanation: "Networks are becoming more flexible and ubiquitous.",
    hint: "Connectivity everywhere, regardless of scale.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;