const questions = [
  {
    question: "What are the main applications of computer networks in education?",
    shortAnswer: "Online learning platforms, virtual classrooms, digital libraries, and collaborative research.",
    explanation: "Networks enable students and teachers to access resources and interact remotely.",
    hint: "Think about how you attend online classes.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How do networks support healthcare?",
    shortAnswer: "Through telemedicine, electronic health records, and medical imaging sharing.",
    explanation: "Networks enable remote consultations, instant access to patient data, and collaboration among specialists.",
    hint: "A doctor in one city can examine a patient in another.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is e-commerce and how does networking enable it?",
    shortAnswer: "E-commerce is buying and selling online, enabled by networks that connect customers, merchants, and payment systems.",
    explanation: "Networks handle transactions, inventory, and customer interactions in real time.",
    hint: "Shopping on Amazon or Flipkart.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is telemedicine?",
    shortAnswer: "Medical consultations conducted remotely over a network.",
    explanation: "Patients and doctors connect via video, phone, or messaging, using networks to transmit health data.",
    hint: "A doctor's appointment via video call.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How do networks enable social media?",
    shortAnswer: "They connect users, servers, and databases, allowing sharing of content and real-time interaction.",
    explanation: "Social media platforms are essentially large networked systems with millions of users.",
    hint: "Posting a photo on Instagram uses the network.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the role of networks in online gaming?",
    shortAnswer: "They enable multiplayer interactions, real-time synchronization, and communication between players.",
    explanation: "Gaming networks require low latency for a smooth experience.",
    hint: "Playing a game with friends online.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How do networks support government services?",
    shortAnswer: "Through e-governance portals, tax filing, public safety systems, and citizen services.",
    explanation: "Networks allow citizens to access services online and governments to manage data efficiently.",
    hint: "Filing taxes online or checking government announcements.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a Content Delivery Network (CDN)?",
    shortAnswer: "A system of distributed servers that deliver content to users based on their location.",
    explanation: "CDNs reduce latency and bandwidth usage by caching content closer to users.",
    hint: "Watching a YouTube video that loads fast no matter where you are.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How do networks benefit transportation?",
    shortAnswer: "Through GPS navigation, traffic management, fleet tracking, and ride-sharing apps.",
    explanation: "Networks provide real-time location data and route optimization.",
    hint: "Using Google Maps to find the fastest route.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the Internet of Things (IoT) and how does it rely on networks?",
    shortAnswer: "IoT connects everyday devices to the internet, enabling remote monitoring and automation.",
    explanation: "Smart home devices, wearables, and industrial sensors all rely on networks.",
    hint: "A smart thermostat you can control from your phone.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do networks enable cloud computing?",
    shortAnswer: "They connect users to remote servers providing on-demand computing resources.",
    explanation: "Cloud services (IaaS, PaaS, SaaS) are delivered over networks.",
    hint: "Using Google Drive or AWS.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the application of networks in research?",
    shortAnswer: "Distributed computing, data sharing, and collaboration across institutions.",
    explanation: "Scientists use networks to share datasets, run simulations, and communicate globally.",
    hint: "Projects like SETI@home using distributed processing.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do networks support remote work?",
    shortAnswer: "Through VPNs, collaboration tools, and cloud-based applications.",
    explanation: "Remote work depends on secure network connections to corporate resources.",
    hint: "Using Zoom and accessing company files from home.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of networks in banking and finance?",
    shortAnswer: "They enable online banking, real-time transactions, ATM networks, and fraud detection.",
    explanation: "Banking systems are heavily networked for security and speed.",
    hint: "Checking your balance via mobile app.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do networks aid in disaster management?",
    shortAnswer: "They enable communication, coordination, and data collection during emergencies.",
    explanation: "Networks connect first responders, government agencies, and affected populations.",
    hint: "Early warning systems and emergency broadcasts.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What are the applications of networks in manufacturing?",
    shortAnswer: "Automated production lines, quality control, inventory management, and predictive maintenance.",
    explanation: "Networks connect sensors, robots, and management systems for efficient production.",
    hint: "Smart factories using IoT and automation.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do networks facilitate supply chain management?",
    shortAnswer: "By providing real-time visibility into inventory, shipments, and logistics.",
    explanation: "Supply chain networks connect suppliers, manufacturers, and retailers.",
    hint: "Tracking a package from warehouse to your door.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the application of networks in entertainment?",
    shortAnswer: "Streaming services, online gaming, music platforms, and social media.",
    explanation: "Networks deliver content to users on demand.",
    hint: "Binge-watching a series on Netflix.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do networks support smart cities?",
    shortAnswer: "By connecting sensors, infrastructure, and services for efficient urban management.",
    explanation: "Smart traffic lights, waste management, and public safety rely on networks.",
    hint: "Traffic lights that adjust to real-time traffic conditions.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the significance of networks in e-learning?",
    shortAnswer: "They enable access to educational resources, interactive content, and global classrooms.",
    explanation: "E-learning platforms use networks to deliver courses and track progress.",
    hint: "Taking a Coursera course from anywhere.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do networks enable real-time collaboration?",
    shortAnswer: "Through shared workspaces, version control, and communication tools.",
    explanation: "Team members can edit documents, chat, and share screens over the network.",
    hint: "Multiple people editing a Google Doc together.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of networks in AI and machine learning?",
    shortAnswer: "They provide the data pipeline and distributed computing power for training models.",
    explanation: "AI models require large datasets and GPU clusters connected via networks.",
    hint: "Training a language model like GPT across thousands of servers.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do networks support blockchain and cryptocurrency?",
    shortAnswer: "They enable peer-to-peer communication, transaction verification, and distributed ledgers.",
    explanation: "Blockchain networks are decentralized and rely on network nodes to maintain consensus.",
    hint: "Bitcoin transactions are broadcast and validated over the network.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the application of networks in the Internet of Medical Things (IoMT)?",
    shortAnswer: "Connected medical devices for remote patient monitoring and diagnostics.",
    explanation: "Wearables, smart implants, and hospital devices communicate over networks.",
    hint: "A pacemaker that sends data to a cardiologist.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do networks enable edge computing?",
    shortAnswer: "By distributing processing closer to data sources, reducing latency and bandwidth.",
    explanation: "Edge devices process data locally and communicate with the cloud via networks.",
    hint: "Smart cameras detecting events without sending full video to the cloud.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of networks in autonomous vehicles?",
    shortAnswer: "They enable V2V (vehicle-to-vehicle) and V2I (vehicle-to-infrastructure) communication.",
    explanation: "Autonomous cars rely on networks to share data about traffic, obstacles, and routes.",
    hint: "Cars 'talking' to each other to avoid collisions.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do networks support precision agriculture?",
    shortAnswer: "By connecting sensors, drones, and irrigation systems for optimised farming.",
    explanation: "Farmers use networked sensors to monitor soil moisture, crop health, and weather.",
    hint: "Drones scanning fields and sending data to a farmer's app.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the application of networks in smart homes?",
    shortAnswer: "Remote control of lighting, heating, security, and appliances via internet connectivity.",
    explanation: "Smart home devices are connected to a central hub and accessible from anywhere.",
    hint: "Turning on your AC from the office.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do networks facilitate digital identity and authentication?",
    shortAnswer: "By enabling secure, remote verification of identity for access to services.",
    explanation: "Networks carry authentication tokens and biometric data for verification.",
    hint: "Logging into a bank app using fingerprint on your phone.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the future of network applications?",
    shortAnswer: "AI-driven networks, immersive experiences (AR/VR), quantum networking, and pervasive IoT.",
    explanation: "Networks will become more intelligent, faster, and deeply integrated into daily life.",
    hint: "What will the next decade bring?",
    level: "expert",
    codeExample: null,
  },
];

export default questions;