const questions = [
  {
    question: "What is a PAN and what is its typical range?",
    shortAnswer: "A Personal Area Network (PAN) is a network for devices within a person's immediate vicinity, typically up to 10 meters.",
    explanation: "PANs connect personal devices like smartphones, wearables, and laptops using Bluetooth, NFC, or USB.",
    hint: "Think of the devices you can reach without moving.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are the most common technologies used in a PAN?",
    shortAnswer: "Bluetooth, Bluetooth Low Energy (BLE), NFC, Zigbee, and USB.",
    explanation: "These technologies provide short-range, low-power communication between personal devices.",
    hint: "Wireless earbuds, smartwatches, and contactless payments.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Give an example of a PAN application.",
    shortAnswer: "Connecting a smartphone to a Bluetooth headset or a smartwatch.",
    explanation: "PANs are used for audio streaming, data sync, and file sharing between personal devices.",
    hint: "Listening to music from your phone on wireless earbuds.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the typical speed of Bluetooth 5.x?",
    shortAnswer: "Up to 24 Mbps (Bluetooth 5.x).",
    explanation: "Bluetooth 5.x offers improved speed and range over previous versions.",
    hint: "Enough for audio streaming and small file transfers.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is NFC used for in a PAN?",
    shortAnswer: "NFC enables short-range communication, often used for contactless payments and device pairing.",
    explanation: "NFC works at a few centimeters and is used for tap-to-pay and quick connections.",
    hint: "Tapping your phone to a payment terminal.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is Zigbee and where is it commonly used?",
    shortAnswer: "Zigbee is a low-power wireless protocol for IoT, used in smart home devices and industrial sensors.",
    explanation: "Zigbee supports mesh networking and is ideal for battery-powered devices.",
    hint: "Smart bulbs, door sensors, and thermostats.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Is a wired PAN possible? Give an example.",
    shortAnswer: "Yes, using USB cables to connect peripherals like keyboards, mice, or external drives.",
    explanation: "Wired PANs are not wireless but still personal and short-range.",
    hint: "Connecting a flash drive to your laptop.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the advantage of low-power PAN technologies?",
    shortAnswer: "They extend battery life of portable devices.",
    explanation: "BLE and Zigbee are designed for low energy consumption, ideal for wearables.",
    hint: "Your smartwatch lasts for days on a single charge.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How secure is a PAN compared to a LAN?",
    shortAnswer: "PANs are generally less secure due to weaker authentication and encryption mechanisms.",
    explanation: "Bluetooth and NFC can be vulnerable to eavesdropping and unauthorized access.",
    hint: "Always turn off discoverability when not needed.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the difference between Bluetooth Classic and BLE?",
    shortAnswer: "Bluetooth Classic is for high-bandwidth streaming (audio), BLE is for low-power data transfer (sensors).",
    explanation: "BLE uses less energy and is designed for occasional data bursts.",
    hint: "BLE is for fitness trackers; Classic is for earbuds.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are some common security risks in PANs?",
    shortAnswer: "Bluejacking (unsolicited messages), Bluesnarfing (data theft), and eavesdropping.",
    explanation: "Weak pairing and discoverable devices are common attack vectors.",
    hint: "Keep your Bluetooth hidden from strangers.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does interference affect PANs?",
    shortAnswer: "Other wireless devices (Wi-Fi, microwave ovens) can disrupt Bluetooth and Zigbee signals.",
    explanation: "PANs operate in the 2.4 GHz ISM band, which is crowded.",
    hint: "Your Wi-Fi might interfere with your Bluetooth connection.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "Can a PAN be extended to cover a larger area?",
    shortAnswer: "Yes, using mesh networking (like Zigbee) or using Bluetooth 5's extended range (up to 100m).",
    explanation: "Mesh allows devices to relay signals, extending coverage.",
    hint: "Smart home networks often use mesh.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of profiles in Bluetooth?",
    shortAnswer: "Profiles define how Bluetooth devices communicate for specific applications (e.g., A2DP for audio, HID for keyboards).",
    explanation: "Profiles ensure interoperability between different devices.",
    hint: "Without the right profile, devices won't understand each other.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do you pair Bluetooth devices securely?",
    shortAnswer: "Use a PIN or confirm a numeric code during pairing to verify the connection.",
    explanation: "Secure pairing prevents man-in-the-middle attacks.",
    hint: "Always check the code on both devices.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the typical data rate of NFC?",
    shortAnswer: "About 424 Kbps.",
    explanation: "NFC is designed for very short-range, low-speed communication.",
    hint: "Fast enough for payment data and small files.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "Can a PAN be used for internet access?",
    shortAnswer: "Yes, through tethering (e.g., Bluetooth PAN profile) or using a phone as a hotspot.",
    explanation: "Devices can share a cellular data connection via PAN.",
    hint: "Sharing your phone's internet with your laptop.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the advantage of using Zigbee over Wi-Fi for smart home devices?",
    shortAnswer: "Zigbee uses much less power and supports mesh networking, making it ideal for battery-powered sensors.",
    explanation: "Wi-Fi is power-hungry and not suitable for many IoT devices.",
    hint: "Your smart bulb doesn't need Wi-Fi; Zigbee is enough.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does USB fit into the PAN category?",
    shortAnswer: "USB is a wired PAN technology that connects peripherals to a host device.",
    explanation: "USB cables provide power and data, but the range is limited to cable length.",
    hint: "Plugging a keyboard or flash drive.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What are the main limitations of PANs?",
    shortAnswer: "Limited range, low data rates, and security vulnerabilities.",
    explanation: "PANs are not suitable for large data transfers or long-distance communication.",
    hint: "Don't try to stream 4K video over Bluetooth.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is Bluetooth 5's range improvement over Bluetooth 4.2?",
    shortAnswer: "Bluetooth 5 can reach up to 240 meters (Class 1) compared to 10 meters for Bluetooth 4.2.",
    explanation: "Range is extended using higher transmit power and coding schemes.",
    hint: "Better for whole-home coverage.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does BLE achieve low energy consumption?",
    shortAnswer: "BLE uses short data bursts and sleeps between transmissions, consuming very little power.",
    explanation: "It's designed for occasional communication rather than continuous streaming.",
    hint: "A heart rate monitor sends data every few seconds, not constantly.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of the Bluetooth stack?",
    shortAnswer: "The Bluetooth stack is the software protocol suite that manages communication between devices.",
    explanation: "It includes layers like L2CAP, RFCOMM, and GATT for different functions.",
    hint: "It's like the OSI model for Bluetooth.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the difference between a Bluetooth piconet and a scatternet?",
    shortAnswer: "A piconet is a network of up to 8 Bluetooth devices; a scatternet is multiple piconets interconnected.",
    explanation: "Scatternets allow more devices to communicate over a larger area.",
    hint: "Piconet = one master with up to 7 slaves; scatternet = overlapping piconets.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does Zigbee's mesh networking work?",
    shortAnswer: "Each Zigbee device can act as a router, relaying data to extend the network.",
    explanation: "Mesh provides redundancy and extended range without a central hub.",
    hint: "Smart bulbs can pass messages through each other.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the concept of 'wireless coexistence' in PANs?",
    shortAnswer: "Coexistence is the ability of different wireless technologies (Bluetooth, Wi-Fi, Zigbee) to operate without significant interference.",
    explanation: "Techniques like frequency hopping and adaptive channel selection help.",
    hint: "All sharing the same 2.4 GHz band.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How can you improve the security of a PAN?",
    shortAnswer: "Use strong pairing (Secure Simple Pairing), disable discoverability, and keep firmware updated.",
    explanation: "Encryption and authentication are also important.",
    hint: "Don't leave your Bluetooth open.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are the future trends in PAN technologies?",
    shortAnswer: "Lower power, higher speeds, and integration with AI and edge computing.",
    explanation: "Technologies like Bluetooth 5.2 (LE Audio), UWB, and Zigbee 3.0 are evolving.",
    hint: "More immersive audio and precise location services.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does a PAN interact with other networks like LAN or WAN?",
    shortAnswer: "PAN devices can connect to a LAN via a smartphone or hub, which then connects to the internet (WAN).",
    explanation: "Your phone acts as a gateway between your PAN (earbuds, watch) and the broader internet.",
    hint: "The phone is the bridge.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "Why is the IEEE 802.15 standard important for PANs?",
    shortAnswer: "IEEE 802.15 defines the standards for Wireless Personal Area Networks (WPANs), including Bluetooth and Zigbee.",
    explanation: "It ensures interoperability and compliance.",
    hint: "It's the blueprint for PAN wireless technologies.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;