/**
 * Java Core Tutorial - Module 003_003: Wrapper Classes, Autoboxing & Number Parsing
 * Topic 5: Compiler Translation: Integer.valueOf() vs intValue() Decompiled Bytecode
 * Educator: Sukanta Hui | Academic Hub: Barrackpore, West Bengal
 */

package com.coderaccotax.javatutorial.wrappers;

public class CompilerBytecodeTranslationDemo {

    public static void main(String[] args) {
        System.out.println("==========================================================================");
        System.out.println(" TOPIC 5: COMPILER TRANSLATION (valueOf & intValue) - BARRACKPORE");
        System.out.println("==========================================================================\n");

        System.out.println(">>> 1. SOURCE CODE WRITTEN BY DEVELOPER:");
        System.out.println("  Integer obj = 100;    // Autoboxing");
        System.out.println("  int val = obj;        // Auto-unboxing");
        System.out.println("  obj++;                // Increment operator on Wrapper!");

        System.out.println("\n>>> 2. EXACT BYTECODE GENERATED BY JAVAC COMPILER:");
        System.out.println("  Integer obj = Integer.valueOf(100);");
        System.out.println("  int val = obj.intValue();");
        System.out.println("  obj = Integer.valueOf(obj.intValue() + 1); // Unbox -> Add -> Re-box!");

        System.out.println("\n>>> CRITICAL INSIGHT ON 'obj++' WITH WRAPPER OBJECTS:");
        System.out.println("  - It extracts primitive with intValue()");
        System.out.println("  - Increments the primitive value");
        System.out.println("  - Allocates or fetches a BRAND NEW Integer object with Integer.valueOf()!");

        System.out.println("\n==========================================================================");
    }
}