const questions = [
  {
    question: "What is a WAN and what is its typical geographic coverage?",
    shortAnswer: "A Wide Area Network (WAN) covers a large area, such as a country, continent, or the globe.",
    explanation: "WANs connect multiple LANs and MANs across long distances, using technologies like leased lines and satellite.",
    hint: "Think of the internet or a corporate network connecting offices worldwide.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What technologies are commonly used in WANs?",
    shortAnswer: "Leased lines, satellite links, undersea fiber cables, MPLS VPNs, and cellular networks (4G/5G).",
    explanation: "WANs use a mix of wired and wireless technologies to cover long distances.",
    hint: "How do continents stay connected?",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does a WAN differ from a LAN?",
    shortAnswer: "A WAN covers a large area (country/global), while a LAN covers a small area (building/campus).",
    explanation: "WANs are slower, have higher latency, and are typically owned by multiple providers.",
    hint: "Think about the difference between your home network and the internet.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a leased line?",
    shortAnswer: "A dedicated point-to-point circuit provided by a telecom company, offering guaranteed bandwidth.",
    explanation: "Leased lines are used for business WAN connections and provide consistent performance.",
    hint: "A private, always-on connection.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the role of the internet in WANs?",
    shortAnswer: "The internet is the largest WAN, a public network connecting billions of devices globally.",
    explanation: "It serves as the backbone for many enterprise WANs through VPNs.",
    hint: "The network of networks.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is satellite communication in WANs?",
    shortAnswer: "Satellite links provide WAN connectivity in remote areas where terrestrial infrastructure is unavailable.",
    explanation: "They offer global coverage but have higher latency due to the distance to satellites.",
    hint: "Used for ships, aircraft, and remote sites.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are undersea fiber cables?",
    shortAnswer: "Fiber optic cables laid across oceans to carry the bulk of intercontinental internet traffic.",
    explanation: "They are the backbone of global WAN connectivity.",
    hint: "The physical cables under the sea.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is MPLS and how is it used in WANs?",
    shortAnswer: "MPLS (Multiprotocol Label Switching) uses labels to forward packets, enabling traffic engineering and VPNs in WANs.",
    explanation: "MPLS provides predictable performance and is used by ISPs to build private WAN services.",
    hint: "Labels instead of IP lookups.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a WAN VPN?",
    shortAnswer: "A virtual private network that extends a private network across a public WAN (like the internet).",
    explanation: "VPNs use encryption to secure data over the public internet.",
    hint: "A secure tunnel over the internet.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are the main advantages of a WAN?",
    shortAnswer: "Global reach, scalability, centralised management, and redundancy.",
    explanation: "WANs enable organisations to operate globally and collaborate across distances.",
    hint: "Connect anywhere.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are the disadvantages of a WAN?",
    shortAnswer: "High cost, slower speeds, higher latency, security risks, and complexity.",
    explanation: "WANs are expensive to build and maintain.",
    hint: "Cost and complexity.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the typical speed of a WAN connection?",
    shortAnswer: "1-100 Mbps, but can go up to 10 Gbps for enterprise fiber links.",
    explanation: "Speeds are lower than LANs due to the long distances and shared infrastructure.",
    hint: "Slower than your home Wi-Fi? Not necessarily, but often.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is latency and why is it higher in WANs?",
    shortAnswer: "Latency is the time for data to travel; it's higher in WANs due to the physical distance (speed of light delay).",
    explanation: "Signal propagation delay over long distances adds significant latency.",
    hint: "A packet crossing the ocean takes time.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is BGP and why is it important for WANs?",
    shortAnswer: "BGP (Border Gateway Protocol) is the routing protocol that exchanges routing information between autonomous systems on the internet.",
    explanation: "BGP is the glue that holds the global internet together.",
    hint: "The protocol that makes the internet work.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between a private WAN and the public internet?",
    shortAnswer: "A private WAN is owned and managed by an organisation (e.g., MPLS); the public internet is open and shared.",
    explanation: "Private WANs offer better performance and security but at a higher cost.",
    hint: "One is exclusive, the other is public.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is SD-WAN and how is it changing WANs?",
    shortAnswer: "SD-WAN (Software-Defined WAN) decouples the control plane from the data plane, allowing intelligent path selection.",
    explanation: "SD-WAN uses multiple connections (e.g., MPLS, broadband, LTE) and dynamically chooses the best path.",
    hint: "A smarter, more flexible WAN.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do you ensure security over a WAN?",
    shortAnswer: "Use encryption (IPsec, SSL/TLS), firewalls, and secure routing protocols.",
    explanation: "Security is critical as WANs traverse public or shared infrastructure.",
    hint: "Lock down the data in transit.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a point-to-point WAN link?",
    shortAnswer: "A direct connection between two locations, like a leased T1 line or fiber.",
    explanation: "Point-to-point links provide dedicated bandwidth and are simple to configure.",
    hint: "A pipe between two sites.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a hub-and-spoke WAN topology?",
    shortAnswer: "A central hub connects to multiple branch sites (spokes) in a star-like fashion.",
    explanation: "Traffic from branch to branch goes through the hub; commonly used for cost efficiency.",
    hint: "All roads lead to Rome.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a full-mesh WAN topology?",
    shortAnswer: "Every site has a direct connection to every other site, providing high redundancy but high cost.",
    explanation: "Used for critical networks where reliability is paramount.",
    hint: "Every site directly connected.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of a WAN accelerator (WAN optimizer)?",
    shortAnswer: "A WAN accelerator uses compression, caching, and deduplication to improve performance over the WAN.",
    explanation: "Reduces bandwidth consumption and speeds up applications.",
    hint: "Makes the WAN feel faster.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between a T1 and an Ethernet WAN connection?",
    shortAnswer: "T1 is a legacy leased line (1.544 Mbps); Ethernet WAN offers higher speeds (10 Mbps - 10 Gbps) at lower cost.",
    explanation: "Ethernet WAN is more scalable and cost-effective for modern needs.",
    hint: "Old vs. new.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do you choose between MPLS and SD-WAN?",
    shortAnswer: "MPLS offers guaranteed performance and security; SD-WAN offers flexibility, cost savings, and cloud optimisation.",
    explanation: "The choice depends on applications, budget, and cloud strategy.",
    hint: "Reliability vs. agility.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the concept of 'circuit switching' vs. 'packet switching' in WANs?",
    shortAnswer: "Circuit switching reserves a dedicated path (like old telephone networks); packet switching shares the path (like the internet).",
    explanation: "Packet switching is more efficient and used in modern WANs.",
    hint: "Dedicated line vs. shared highway.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does QoS work in a WAN environment?",
    shortAnswer: "QoS classifies and prioritises traffic to ensure critical applications get the bandwidth they need.",
    explanation: "Techniques include traffic shaping, prioritisation, and congestion avoidance.",
    hint: "VIP lane for important data.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the impact of packet loss on a WAN?",
    shortAnswer: "Packet loss degrades application performance, especially for real-time services like VoIP and video.",
    explanation: "TCP retransmissions increase latency; UDP streams may suffer quality loss.",
    hint: "Lost packets mean retransmissions.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do you troubleshoot a slow WAN link?",
    shortAnswer: "Use tools like traceroute, iPerf, and monitoring to identify bottlenecks (bandwidth, latency, packet loss).",
    explanation: "Check link utilisation, errors, and application traffic patterns.",
    hint: "Isolate the problem segment.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of DNS in WANs?",
    shortAnswer: "DNS resolves domain names to IP addresses, essential for accessing services over the WAN.",
    explanation: "DNS is a distributed system that works across the global WAN.",
    hint: "The phonebook of the internet.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is a WAN edge device?",
    shortAnswer: "A device at the boundary of a LAN that connects to the WAN, such as a router or SD-WAN appliance.",
    explanation: "It handles routing, security, and WAN optimisation.",
    hint: "The gateway to the wide area.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are the future trends in WAN technology?",
    shortAnswer: "SD-WAN, 5G integration, AI-driven networking, and increased adoption of cloud-native WAN architectures.",
    explanation: "WANs are becoming more intelligent, flexible, and cost-effective.",
    hint: "The future is software-defined and mobile.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;