const topic12_questions = [
  {
    "question": "Does the Java Virtual Machine (JVM) natively support nested or inner classes in bytecode?",
    "shortAnswer": "NO. The JVM bytecode specification only recognizes top-level classes. The 'javac' compiler transforms and flattens every nested, inner, and anonymous class into a separate, distinct top-level '.class' file using the dollar sign '$' naming convention (e.g. 'Outer$Inner.class' and 'Outer$1.class').",
    "explanation": "Synthetic package-private constructors are generated by javac to bridge private access.",
    "hint": "JVM has no concept of inner classes; javac flattens them into Outer$Inner.class files.",
    "level": "Intermediate",
    "codeExample": "// javac generates: Outer.class, Outer$Inner.class, Outer$1.class"
  }
];

export default topic12_questions;