import React, { useState } from 'react';
import {
  Layers, ArrowRight, ArrowLeftRight, Activity, Cpu,
  Database, Zap, ShieldCheck, CheckCircle2, AlertTriangle,
  FileText, Terminal, BookOpen, Calculator, Sparkles, RefreshCw
} from 'lucide-react';
import Teacher from "../../../../../common/TeacherSukantaHui";
import FAQTemplate from "../../../../../common/FAQTemplate";
import PlainTextPrint from "../../../../../common/PlainTextPrint";
import PythonFileLoader from "../../../../../common/PythonFileLoader";
import questions from "./topic2_files/topic2_questions";
import noteText from "./topic2_files/topic2_note.txt?raw";
import pythonCode from "./topic2_files/bus_width_addressing.py?raw";

// Interactive System Bus Architecture Simulator
const SystemBusVisualizer = () => {
  const [selectedBus, setSelectedBus] = useState('address');
  const [busWidth, setBusWidth] = useState(32);
  const [activeCycle, setActiveCycle] = useState('read');

  const busInfo = {
    address: {
      title: "Address Bus (Unidirectional)",
      icon: ArrowRight,
      color: "border-sky-500/40 text-sky-400 bg-sky-500/10",
      direction: "CPU ──▶ Memory & I/O Peripherals (One-Way)",
      description: "Transfers physical memory addresses and I/O port numbers from the CPU to RAM, ROM, and peripheral controllers.",
      formula: "Max Addressable Memory = 2^N Bytes (where N is number of address lines)",
      calculation: `${busWidth} Address Lines = 2^${busWidth} bytes = ${
        busWidth === 16 ? '64 KB' :
        busWidth === 20 ? '1 MB (Intel 8086 limit)' :
        busWidth === 24 ? '16 MB (Intel 80286 limit)' :
        busWidth === 32 ? '4 Gigabytes (4 GB)' :
        busWidth === 36 ? '64 Gigabytes (64 GB)' :
        busWidth === 48 ? '256 Terabytes (256 TB)' : '16 Exabytes (16 EB)'
      }`,
      cbseTip: "Remember: The Address Bus is STRICTLY UNIDIRECTIONAL. Memory never drives addresses into the CPU."
    },
    data: {
      title: "Data Bus (Bidirectional)",
      icon: ArrowLeftRight,
      color: "border-emerald-500/40 text-emerald-400 bg-emerald-500/10",
      direction: "CPU ◀──▶ Memory & I/O Peripherals (Two-Way)",
      description: "Carries the actual machine code instructions, integer numbers, floating-point data, and character bitstreams between the CPU, RAM, and hardware peripherals.",
      formula: "Data Word Throughput = Bus Width (bits) / 8 Bytes per Cycle",
      calculation: "64-bit Data Bus transfers 8 Bytes simultaneously in a single clock tick.",
      cbseTip: "During a READ cycle, data travels RAM -> CPU. During a WRITE cycle, data travels CPU -> RAM."
    },
    control: {
      title: "Control Bus (Command & Timing Lines)",
      icon: Zap,
      color: "border-amber-500/40 text-amber-400 bg-amber-500/10",
      direction: "CPU ──▶ Peripheral Control / Interrupts ◀── CPU",
      description: "Carries discrete timing pulses, read/write strobes, interrupt requests, and bus arbitration signals generated by the Control Unit (CU).",
      formula: "Key Signals: MEMR (Memory Read), MEMW (Memory Write), IOR, IOW, INTR, RESET",
      calculation: "Ensures no two devices drive the data bus at the same instant (prevents bus contention).",
      cbseTip: "The Control Bus carries control lines that tell memory WHETHER to read or write the data."
    }
  };

  return (
    <div className="w-full bg-slate-950 rounded-2xl p-4 sm:p-6 border border-slate-800 shadow-2xl space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-4">
        <div className="flex items-center gap-2.5">
          <div className="w-9 h-9 rounded-xl bg-sky-500/20 text-sky-400 flex items-center justify-center font-bold">
            <Layers size={20} className="animate-pulse" />
          </div>
          <div>
            <h3 className="text-base font-bold text-white tracking-tight">
              Interactive System Bus Trio &amp; Memory Addressing Engine
            </h3>
            <p className="text-xs text-slate-400">
              Select a bus type and adjust address bit-widths to observe theoretical memory capacity scaling.
            </p>
          </div>
        </div>
      </div>

      {/* Bus Selectors */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        {[
          { key: 'address', label: '1. Address Bus', sub: 'Unidirectional', icon: ArrowRight },
          { key: 'data', label: '2. Data Bus', sub: 'Bidirectional', icon: ArrowLeftRight },
          { key: 'control', label: '3. Control Bus', sub: 'Timing & Commands', icon: Zap }
        ].map(item => (
          <button
            key={item.key}
            onClick={() => setSelectedBus(item.key)}
            className={`p-4 rounded-xl text-left border transition-all cursor-pointer ${
              selectedBus === item.key
                ? 'bg-sky-500/15 border-sky-500 text-sky-200 shadow-lg shadow-sky-500/10'
                : 'bg-slate-900/80 border-slate-800 text-slate-400 hover:text-white hover:bg-slate-800/60'
            }`}
          >
            <div className="flex items-center gap-2 font-bold text-xs sm:text-sm text-white">
              <item.icon size={16} className={selectedBus === item.key ? 'text-sky-400' : 'text-slate-400'} />
              <span>{item.label}</span>
            </div>
            <span className="text-[11px] text-slate-400 block mt-1">{item.sub}</span>
          </button>
        ))}
      </div>

      {/* Bus Details Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-slate-900/95 to-slate-950 border border-slate-800 rounded-2xl p-5 space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800/80 pb-3">
          <h4 className="text-sm sm:text-base font-bold text-white flex items-center gap-2">
            <span className="text-sky-400 font-mono">▸</span> {busInfo[selectedBus].title}
          </h4>
          <span className="px-3 py-1 bg-slate-800 text-sky-300 font-mono text-xs rounded-full border border-slate-700">
            {busInfo[selectedBus].direction}
          </span>
        </div>

        <p className="text-xs text-slate-300 leading-relaxed">{busInfo[selectedBus].description}</p>

        {selectedBus === 'address' && (
          <div className="space-y-3 pt-2">
            <div className="flex flex-wrap items-center justify-between text-xs">
              <span className="text-slate-400 font-semibold">Simulate Address Bus Width (N lines):</span>
              <span className="text-sky-400 font-mono font-bold">{busWidth} Bits</span>
            </div>
            <div className="flex flex-wrap gap-2">
              {[16, 20, 24, 32, 36, 48, 64].map(w => (
                <button
                  key={w}
                  onClick={() => setBusWidth(w)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-mono font-bold transition ${
                    busWidth === w
                      ? 'bg-sky-500 text-white shadow-md shadow-sky-500/30'
                      : 'bg-slate-800 text-slate-400 hover:text-white'
                  }`}
                >
                  {w}-bit
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Calculation Box */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2 text-xs">
          <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800">
            <span className="text-amber-400 font-bold block mb-1">Architecture Formula:</span>
            <span className="text-slate-300 font-mono">{busInfo[selectedBus].formula}</span>
          </div>
          <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800">
            <span className="text-emerald-400 font-bold block mb-1">Computed Capacity / Role:</span>
            <span className="text-white font-mono font-semibold">{busInfo[selectedBus].calculation}</span>
          </div>
        </div>

        <div className="bg-amber-950/20 border border-amber-500/30 rounded-xl p-3 text-xs text-amber-200 flex items-start gap-2">
          <Sparkles size={16} className="text-amber-400 shrink-0 mt-0.5" />
          <span>{busInfo[selectedBus].cbseTip}</span>
        </div>
      </div>
    </div>
  );
};

export default function Topic2() {
  return (
    <div className="dark bg-slate-900 text-slate-200 min-h-screen py-8 px-4 sm:px-6 lg:px-8 space-y-10 font-sans">
      <div className="max-w-6xl mx-auto space-y-10">

        {/* 1. Header Section */}
        <div className="bg-gradient-to-r from-slate-900 via-sky-950/30 to-slate-900 border border-sky-500/20 rounded-3xl p-6 sm:p-8 shadow-2xl relative overflow-hidden">
          <div className="absolute top-0 right-0 w-80 h-80 bg-sky-500/10 rounded-full blur-3xl pointer-events-none" />
          <div className="relative z-10 space-y-3">
            <div className="flex flex-wrap items-center gap-2">
              <span className="px-3 py-1 bg-sky-500/10 text-sky-400 border border-sky-500/30 text-xs font-semibold rounded-full uppercase tracking-wider">
                Module 001 · Topic 2
              </span>
              <span className="px-3 py-1 bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 text-xs font-semibold rounded-full">
                Unit I: Computer Systems and Organisation (10 Marks)
              </span>
            </div>
            <h1 className="text-2xl sm:text-3xl md:text-4xl font-extrabold text-white tracking-tight leading-tight">
              System Bus Architecture: Data Bus, Address Bus, and Control Bus
            </h1>
            <p className="text-sm sm:text-base text-slate-300 max-w-3xl leading-relaxed">
              Understand how electrical signals travel across the motherboard. Master the distinct roles, directionalities, and bandwidth formulas of the Address Bus, Data Bus, and Control Bus.
            </p>
          </div>
        </div>

        {/* 2. Deep Conceptual Explanation */}
        <div className="bg-slate-800/40 border border-slate-800 rounded-2xl p-6 sm:p-8 space-y-6">
          <div className="flex items-center gap-3 border-b border-slate-700/60 pb-4">
            <Layers className="text-sky-400" size={24} />
            <h2 className="text-xl font-bold text-white">1. Conceptual Overview: The Information Highways</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-slate-900/80 border border-slate-700/50 rounded-xl p-5 space-y-3">
              <div className="w-10 h-10 rounded-xl bg-sky-500/10 text-sky-400 flex items-center justify-center font-bold">
                <ArrowRight size={22} />
              </div>
              <h3 className="text-base font-bold text-white">Address Bus (Unidirectional)</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Determines which memory cell or peripheral port the CPU wants to target. Since the CPU is the sole master initiating requests, signals flow strictly from the CPU to memory/IO.
              </p>
            </div>

            <div className="bg-slate-900/80 border border-slate-700/50 rounded-xl p-5 space-y-3">
              <div className="w-10 h-10 rounded-xl bg-emerald-500/10 text-emerald-400 flex items-center justify-center font-bold">
                <ArrowLeftRight size={22} />
              </div>
              <h3 className="text-base font-bold text-white">Data Bus (Bidirectional)</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Transfers the payload of information (instructions, integer values, strings). Because CPU must both read from memory and write back results, data moves in both directions.
              </p>
            </div>

            <div className="bg-slate-900/80 border border-slate-700/50 rounded-xl p-5 space-y-3">
              <div className="w-10 h-10 rounded-xl bg-amber-500/10 text-amber-400 flex items-center justify-center font-bold">
                <Zap size={22} />
              </div>
              <h3 className="text-base font-bold text-white">Control Bus (Commands)</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Carries operational strobe commands (MEMR, MEMW, IOR, IOW) and interrupt signals that synchronize device clocks and prevent electrical line collisions.
              </p>
            </div>
          </div>
        </div>

        {/* 3. Interactive Visualizer */}
        <div className="space-y-4">
          <div className="flex items-center gap-2">
            <Activity className="text-sky-400" size={20} />
            <h2 className="text-lg font-bold text-white">2. Interactive System Bus Simulator</h2>
          </div>
          <SystemBusVisualizer />
        </div>

        {/* 4. Deep Technical Breakdown */}
        <div className="bg-slate-800/40 border border-slate-800 rounded-2xl p-6 sm:p-8 space-y-6">
          <div className="flex items-center gap-3 border-b border-slate-700/60 pb-4">
            <Calculator className="text-amber-400" size={24} />
            <h2 className="text-xl font-bold text-white">3. Technical Formulae &amp; Address Space Scaling Table</h2>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-xs sm:text-sm text-left border-collapse">
              <thead>
                <tr className="border-b border-slate-700 bg-slate-900/80 text-sky-300">
                  <th className="p-3 font-bold">Address Lines (N)</th>
                  <th className="p-3 font-bold">Binary Address Space (2^N)</th>
                  <th className="p-3 font-bold">Direct Addressable RAM</th>
                  <th className="p-3 font-bold">Historical / Modern Architecture Example</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800 text-slate-300">
                <tr className="hover:bg-slate-800/40">
                  <td className="p-3 font-mono font-bold text-sky-400">16 bits</td>
                  <td className="p-3 font-mono">2^16 = 65,536 Bytes</td>
                  <td className="p-3 font-bold text-white">64 Kilobytes (KB)</td>
                  <td className="p-3">Intel 8080 / 8085, Zilog Z80</td>
                </tr>
                <tr className="hover:bg-slate-800/40">
                  <td className="p-3 font-mono font-bold text-sky-400">20 bits</td>
                  <td className="p-3 font-mono">2^20 = 1,048,576 Bytes</td>
                  <td className="p-3 font-bold text-white">1 Megabyte (MB)</td>
                  <td className="p-3">Intel 8086 / IBM PC XT (1981)</td>
                </tr>
                <tr className="hover:bg-slate-800/40">
                  <td className="p-3 font-mono font-bold text-sky-400">32 bits</td>
                  <td className="p-3 font-mono">2^32 = 4,294,967,296 Bytes</td>
                  <td className="p-3 font-bold text-white">4 Gigabytes (GB)</td>
                  <td className="p-3">Intel Pentium, x86 32-bit Windows XP / 7</td>
                </tr>
                <tr className="hover:bg-slate-800/40">
                  <td className="p-3 font-mono font-bold text-sky-400">36 bits (PAE)</td>
                  <td className="p-3 font-mono">2^36 = 68,719,476,736 Bytes</td>
                  <td className="p-3 font-bold text-white">64 Gigabytes (GB)</td>
                  <td className="p-3">Intel Xeon Physical Address Extension</td>
                </tr>
                <tr className="hover:bg-slate-800/40">
                  <td className="p-3 font-mono font-bold text-emerald-400">48 bits (x64)</td>
                  <td className="p-3 font-mono">2^48 = 281,474,976,710,656 Bytes</td>
                  <td className="p-3 font-bold text-emerald-300">256 Terabytes (TB)</td>
                  <td className="p-3">Modern AMD Ryzen, Intel Core i9, Apple M3</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        {/* 5. Code Demonstration */}
        <div className="space-y-4">
          <div className="flex items-center gap-2">
            <Terminal className="text-emerald-400" size={20} />
            <h2 className="text-lg font-bold text-white">4. Python Code Demonstration: System Bus Calculations</h2>
          </div>
          <PythonFileLoader
            fileModule={pythonCode}
            title="bus_width_addressing.py"
            highlightLines={[14, 27, 30, 48, 55]}
          />
        </div>

        {/* 6. Real-World Case Studies */}
        <div className="bg-slate-800/40 border border-slate-800 rounded-2xl p-6 sm:p-8 space-y-6">
          <div className="flex items-center gap-3 border-b border-slate-700/60 pb-4">
            <BookOpen className="text-amber-400" size={24} />
            <h2 className="text-xl font-bold text-white">5. Real-World Case Studies &amp; Scenarios</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-2">
              <span className="text-xs font-bold text-sky-400 uppercase tracking-wider">Case 1: The 4GB 32-bit Barrier</span>
              <h4 className="text-sm font-bold text-white">Why Older Windows 32-bit PCs Ignored 8GB RAM</h4>
              <p className="text-xs text-slate-300 leading-relaxed">
                When students installed 8 GB of RAM into a 32-bit OS, the 32-bit address bus could only generate 2^32 distinct binary addresses (4 GB). Any RAM beyond 4 GB remained physically invisible to the CPU.
              </p>
            </div>

            <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-2">
              <span className="text-xs font-bold text-emerald-400 uppercase tracking-wider">Case 2: Dual-Channel DDR4 RAM</span>
              <h4 className="text-sm font-bold text-white">Doubling Data Bus Width to 128 Bits</h4>
              <p className="text-xs text-slate-300 leading-relaxed">
                Motherboards with dual-channel RAM operate two 64-bit data buses in parallel, creating a virtual 128-bit wide data path that delivers 16 bytes per memory cycle, accelerating gaming and 3D rendering.
              </p>
            </div>

            <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-2">
              <span className="text-xs font-bold text-purple-400 uppercase tracking-wider">Case 3: USB vs Parallel Printer Cables</span>
              <h4 className="text-sm font-bold text-white">Serial Bus vs Parallel Bus Transition</h4>
              <p className="text-xs text-slate-300 leading-relaxed">
                Legacy 25-pin parallel printer cables suffered from electromagnetic cross-talk at high frequencies. Modern standards like USB 3.2 and PCIe use ultra-fast serial differential signaling lanes instead.
              </p>
            </div>

            <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-2">
              <span className="text-xs font-bold text-rose-400 uppercase tracking-wider">Case 4: DMA Controller Operation</span>
              <h4 className="text-sm font-bold text-white">Direct Bus Takeover for Fast SSD Backups</h4>
              <p className="text-xs text-slate-300 leading-relaxed">
                When transferring a 10 GB file from an NVMe SSD to RAM, the DMA controller takes temporary mastery of the Address and Data buses via the Control Bus, freeing the CPU core to execute other software.
              </p>
            </div>
          </div>
        </div>

        {/* 7. Common Pitfalls & Best Practices */}
        <div className="bg-slate-800/40 border border-slate-800 rounded-2xl p-6 sm:p-8 space-y-6">
          <div className="flex items-center gap-3 border-b border-slate-700/60 pb-4">
            <AlertTriangle className="text-amber-400" size={24} />
            <h2 className="text-xl font-bold text-white">6. Common Exam Pitfalls &amp; Best Practices</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-rose-950/20 border border-rose-500/30 rounded-xl p-5 space-y-3">
              <div className="flex items-center gap-2 text-rose-400 font-bold text-sm">
                <AlertTriangle size={18} />
                <span>Common Student Mistakes</span>
              </div>
              <ul className="text-xs text-slate-300 space-y-2 list-disc pl-4 leading-relaxed">
                <li><strong>Writing that Address Bus is Bidirectional:</strong> This is a fatal exam mistake. Address Bus is strictly UNIDIRECTIONAL (CPU to Memory).</li>
                <li><strong>Confusing Address Bus and Data Bus capacities:</strong> Address lines determine <em>maximum memory capacity</em> (2ᴺ); Data lines determine <em>word size</em> transferred per cycle (M/8 bytes).</li>
                <li><strong>Ignoring Control Bus signals:</strong> Writing that the Control Bus only controls fans. (It transmits read/write strobes and clock pulses).</li>
              </ul>
            </div>

            <div className="bg-emerald-950/20 border border-emerald-500/30 rounded-xl p-5 space-y-3">
              <div className="flex items-center gap-2 text-emerald-400 font-bold text-sm">
                <CheckCircle2 size={18} />
                <span>Examiner Preferred Answers</span>
              </div>
              <ul className="text-xs text-slate-300 space-y-2 list-disc pl-4 leading-relaxed">
                <li><strong>Show clear power of 2 calculations:</strong> Show 2¹⁰ = 1 KB, 2²⁰ = 1 MB, 2³⁰ = 1 GB, 2³² = 4 GB.</li>
                <li><strong>Draw Arrows Clearly:</strong> On block diagrams, draw a one-way arrow for Address Bus and a two-way arrow for Data Bus.</li>
                <li><strong>List specific Control Signals:</strong> Mention MEMR, MEMW, IOR, IOW by their official acronyms.</li>
              </ul>
            </div>
          </div>
        </div>

        {/* 8. Hint Section */}
        <div className="bg-slate-900 border border-sky-500/30 rounded-2xl p-6 space-y-3">
          <div className="flex items-center gap-2 text-sky-400 font-bold text-sm">
            <Sparkles size={18} />
            <span>Mnemonic to Remember Bus Functions</span>
          </div>
          <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
            Remember <strong>"A-D-C"</strong> like a postal courier: <strong>Address Bus</strong> is the Destination Envelope Address (tells where to go), <strong>Data Bus</strong> is the Package Contents (what is being carried), and <strong>Control Bus</strong> is the Delivery Receipt &amp; Stamp (tells whether to Deliver or Pick Up).
          </p>
        </div>

        {/* 9. Frequently Asked Questions */}
        <div className="space-y-4">
          <FAQTemplate
            title="Topic 2 · System Bus Architecture &amp; Memory Addressing FAQs"
            questions={questions}
          />
        </div>

        {/* 10. Plain Text Printable Document */}
        <div className="space-y-4">
          <PlainTextPrint
            content={noteText}
            filename="topic2_system_bus_note.txt"
            title="CBSE Class XI CS 083 – Topic 2 Revision Handbook"
            hidePreview={false}
            showDownload={true}
          />
        </div>

        {/* 11. Teacher's Note */}
        <Teacher
          note="Whenever you see a question on 'How many memory locations can be addressed by N address lines?', immediately apply 2^N bytes. Practice powers of 2 up to 2^32 (2^10=1K, 2^20=1M, 2^30=1G, 2^32=4G). This is guaranteed to earn full marks! — Sukanta Hui"
        />

      </div>
    </div>
  );
}
