const questions = [
  {
    question: "What is the correct pip command to install NumPy?",
    shortAnswer: "pip install numpy",
    explanation: "The standard pip command installs NumPy from the Python Package Index (PyPI). For a specific version: pip install numpy==1.26.4. To upgrade: pip install --upgrade numpy.",
    hint: "pip is the Python package installer.",
    level: "basic",
    codeExample: "# Run in terminal (not in Python file):\n# pip install numpy",
  },
  {
    question: "What is the standard alias used when importing NumPy?",
    shortAnswer: "np — as in: import numpy as np",
    explanation: "The alias 'np' is universally adopted across the entire Python data science community. Every tutorial, textbook, Scikit-learn documentation, and ML framework assumes you use 'np'. Using any other alias will confuse readers and collaborators.",
    hint: "Two letters. Used by everyone.",
    level: "basic",
    codeExample: "import numpy as np\narr = np.array([1, 2, 3])",
  },
  {
    question: "How do you verify that NumPy is installed correctly?",
    shortAnswer: "import numpy as np; print(np.__version__)",
    explanation: "After installation, import NumPy and print its __version__ attribute. If this runs without error and prints a version string (e.g., '1.26.4'), NumPy is correctly installed.",
    hint: "Use the dunder __version__ attribute.",
    level: "basic",
    codeExample: "import numpy as np\nprint(np.__version__)  # e.g., 1.26.4\nprint(np.__file__)     # installation path",
  },
  {
    question: "Why should you NEVER use 'from numpy import *'?",
    shortAnswer: "It imports hundreds of names into your namespace, causing conflicts and making code hard to read.",
    explanation: "NumPy has hundreds of public names (sum, max, min, etc.) that clash with Python builtins. Wildcard import pollutes the global namespace and makes it impossible to tell which 'sum' is being called — Python's or NumPy's. It also defeats IDE auto-complete.",
    hint: "Think about name clashes with Python's built-in sum(), max(), min().",
    level: "basic",
    codeExample: "# BAD — don't do this:\nfrom numpy import *\nresult = sum([1, 2, 3])   # which sum? Python's or NumPy's?\n\n# GOOD:\nimport numpy as np\nresult = np.sum([1, 2, 3])",
  },
  {
    question: "Is NumPy pre-installed in Google Colab?",
    shortAnswer: "Yes — Google Colab has NumPy pre-installed. Just use import numpy as np.",
    explanation: "Google Colab is a cloud Jupyter notebook environment with NumPy, Pandas, Matplotlib, Scikit-learn, and TensorFlow pre-installed. No pip install is needed. Simply import numpy as np to start using it.",
    hint: "Colab = cloud notebook with ML libraries pre-installed.",
    level: "basic",
    codeExample: "# In Google Colab — just run this, no installation needed:\nimport numpy as np\nprint(np.__version__)",
  },
  {
    question: "What error do you get if NumPy is not installed, and how do you fix it?",
    shortAnswer: "ModuleNotFoundError: No module named 'numpy'. Fix: run pip install numpy in the terminal.",
    explanation: "Python raises ModuleNotFoundError when the requested package is not installed in the active Python environment. Run 'pip install numpy' in the terminal (not inside a .py file). In Jupyter notebooks, use '!pip install numpy' with the ! prefix.",
    hint: "ModuleNotFoundError = package not installed.",
    level: "basic",
    codeExample: "# Fix in terminal:\n# pip install numpy\n\n# Fix in Jupyter/Colab cell:\n# !pip install numpy",
  },
  {
    question: "What conda command installs NumPy in an Anaconda environment?",
    shortAnswer: "conda install numpy",
    explanation: "Conda is the package manager for Anaconda/Miniconda. It resolves dependencies differently from pip and is preferred in scientific computing environments. 'conda install numpy' installs the MKL-optimized version for faster linear algebra.",
    hint: "conda is the Anaconda package manager.",
    level: "basic",
    codeExample: "# In Anaconda Prompt or terminal:\n# conda install numpy\n# or for a specific version:\n# conda install numpy=1.26.4",
  },
  {
    question: "What does np.__file__ tell you?",
    shortAnswer: "The filesystem path to the NumPy package installation directory.",
    explanation: "np.__file__ returns the absolute path to the NumPy package on your system (e.g., C:\\Python311\\Lib\\site-packages\\numpy\\__init__.py on Windows). This is useful for diagnosing environment issues when you have multiple Python installations.",
    hint: "__file__ is a standard Python module attribute showing the module's location.",
    level: "intermediate",
    codeExample: "import numpy as np\nprint(np.__file__)\n# e.g., /usr/local/lib/python3.11/dist-packages/numpy/__init__.py",
  },
  {
    question: "What is the difference between pip and conda for installing NumPy?",
    shortAnswer: "pip installs from PyPI without dependency solving; conda installs from conda channels with full dependency resolution and MKL optimization.",
    explanation: "pip is Python's default package manager and installs from PyPI. conda is Anaconda's manager that handles non-Python dependencies (like C libraries) and can install MKL (Intel Math Kernel Library) optimized NumPy which is faster for linear algebra. In most ML environments, either works. Prefer conda if using Anaconda.",
    hint: "conda resolves non-Python binary dependencies; pip does not.",
    level: "intermediate",
    codeExample: "# pip: from PyPI\n# pip install numpy\n\n# conda: from conda-forge or defaults channel\n# conda install -c conda-forge numpy",
  },
  {
    question: "How do you install NumPy inside a Jupyter Notebook cell?",
    shortAnswer: "Use !pip install numpy (with ! prefix to run a shell command).",
    explanation: "In Jupyter Notebook or JupyterLab, lines starting with ! are executed as shell commands. So !pip install numpy runs pip in the terminal from within the notebook. This is useful when you cannot access the terminal directly.",
    hint: "! prefix in Jupyter runs terminal (shell) commands.",
    level: "intermediate",
    codeExample: "# In a Jupyter Notebook cell:\n!pip install numpy\n\n# Then in the next cell:\nimport numpy as np\nprint(np.__version__)",
  },
  {
    question: "What attribute would you check to see how many public names NumPy exports?",
    shortAnswer: "len([a for a in dir(np) if not a.startswith('_')])",
    explanation: "dir(np) returns all attributes including private ones (starting with _). Filtering out names starting with _ gives the public API. NumPy exports several hundred public names including array creation, math, linalg, fft, random, and testing utilities.",
    hint: "dir() lists all attributes of any Python object.",
    level: "intermediate",
    codeExample: "import numpy as np\npublic_api = [a for a in dir(np) if not a.startswith('_')]\nprint(len(public_api))   # ~400+\nprint(public_api[:10])   # first 10 names",
  },
  {
    question: "What is the np.lookfor() function and when would you use it?",
    shortAnswer: "np.lookfor('keyword') searches NumPy's documentation for functions related to a keyword.",
    explanation: "np.lookfor() is a documentation search tool. For example, np.lookfor('sort') lists all NumPy functions related to sorting with brief descriptions. It is useful when you know what you want to do but don't know the exact function name.",
    hint: "Think of it as NumPy's built-in help search engine.",
    level: "intermediate",
    codeExample: "import numpy as np\nnp.lookfor('sort')     # finds np.sort, np.argsort, etc.\nnp.lookfor('random')   # finds all random-related functions",
  },
  {
    question: "What is ImportError: numpy.core.multiarray failed to import, and how do you fix it?",
    shortAnswer: "A corrupted or incompatible NumPy installation. Fix: pip install --upgrade numpy",
    explanation: "This error usually occurs when NumPy's C extension modules are missing or incompatible with the Python version. The fix is to reinstall: pip install --upgrade numpy, or in severe cases, uninstall and reinstall: pip uninstall numpy && pip install numpy.",
    hint: "multiarray is NumPy's core C extension — it must load successfully.",
    level: "advanced",
    codeExample: "# Fix steps:\n# 1. pip install --upgrade numpy\n# 2. If still fails:\n#    pip uninstall numpy\n#    pip install numpy",
  },
  {
    question: "Why was np.bool deprecated and removed in NumPy 1.24?",
    shortAnswer: "np.bool was an alias for Python's built-in bool, which was unnecessary and caused confusion. np.bool_ is the proper NumPy scalar type.",
    explanation: "In NumPy < 1.20, np.bool was allowed as an alias for Python's bool. This was deprecated in 1.20 and removed in 1.24 because it shadowed the built-in bool, creating confusion. The correct NumPy boolean type is np.bool_ (with underscore), which is a proper NumPy scalar dtype.",
    hint: "Use np.bool_ (with underscore) — the _ distinguishes it from Python's built-in bool.",
    level: "advanced",
    codeExample: "# Old (NumPy < 1.20) — now raises AttributeError:\n# arr = np.array([True, False], dtype=np.bool)  # WRONG\n\n# Correct:\narr = np.array([True, False], dtype=np.bool_)  # RIGHT\nprint(arr.dtype)   # bool",
  },
  {
    question: "What is MKL-optimized NumPy and how does it differ from standard NumPy?",
    shortAnswer: "MKL (Intel Math Kernel Library) optimized NumPy uses Intel's BLAS/LAPACK for 2x–5x faster linear algebra on Intel CPUs.",
    explanation: "Standard NumPy uses OpenBLAS for linear algebra. Anaconda ships with NumPy linked against Intel MKL, which is highly optimized for Intel CPUs and provides significant speedups for operations like matrix multiplication, SVD, and eigenvalue decomposition. Google Colab uses OpenBLAS. For ML training loops, the difference is usually minor.",
    hint: "MKL = Intel Math Kernel Library. Anaconda bundles it.",
    level: "advanced",
    codeExample: "# Check which BLAS NumPy is linked to:\nimport numpy as np\nnp.show_config()   # shows BLAS/LAPACK linkage details",
  },
];

export default questions;
