// topic0_files/topic0_questions.js

const questions = [
  {
    question: "What is a Cartesian Product (R1 × R2) in relational database theory?",
    shortAnswer: "A relational operation that combines every tuple of relation R1 with every tuple of relation R2, producing a relation with M × N rows and d1 + d2 columns.",
    explanation: "Standard mathematical definition of the Cartesian product.",
    hint: "Combines every row of R1 with every row of R2 (M × N rows).",
    level: "basic"
  },
  {
    question: "What is the ANSI SQL-92 keyword used to explicitly request a Cartesian Product?",
    shortAnswer: "`CROSS JOIN`.",
    explanation: "ANSI SQL syntax for Cartesian product.",
    hint: "CROSS JOIN.",
    level: "basic"
  },
  {
    question: "What are the three logical processing stages of an SQL JOIN query?",
    shortAnswer: "Stage 1: Generate Cartesian Product (R1 × R2) ➔ Stage 2: Apply ON Predicate Filter ➔ Stage 3: Preserve Outer Rows (for Outer Joins).",
    explanation: "The 3-stage logical join pipeline.",
    hint: "1. Cartesian Product ➔ 2. ON Filter ➔ 3. Outer Preservation.",
    level: "basic"
  },
  {
    question: "If Table A has 100 rows and Table B has 50 rows, how many rows does their Cartesian Product produce?",
    shortAnswer: "5,000 rows (100 × 50 = 5,000).",
    explanation: "Cardinality calculation for Cartesian product.",
    hint: "100 × 50 = 5,000.",
    level: "basic"
  },
  {
    question: "If Table A has 4 columns and Table B has 3 columns, what is the degree (number of columns) of their Cartesian Product?",
    shortAnswer: "7 columns (4 + 3 = 7).",
    explanation: "Degree calculation for Cartesian product.",
    hint: "4 + 3 = 7.",
    level: "basic"
  },
  {
    question: "What happens if a developer writes `SELECT * FROM students, courses;` without a `WHERE` or `ON` clause in MySQL?",
    shortAnswer: "MySQL executes a full Cartesian Product (CROSS JOIN), generating an unfiltered combination of all rows in both tables.",
    explanation: "Comma syntax Cartesian product behavior.",
    hint: "Executes an unfiltered Cartesian product.",
    level: "basic"
  },
  {
    question: "What is an 'Accidental Cartesian Explosion' in production databases?",
    shortAnswer: "An unintentional join where missing or malformed join conditions cause millions of intermediate rows to be generated, overwhelming server memory and CPU.",
    explanation: "Definition of Cartesian explosion hazard.",
    hint: "Unintended row multiplication due to missing join conditions.",
    level: "basic"
  },
  {
    question: "How does an `INNER JOIN` filter the rows generated by the conceptual Cartesian Product?",
    shortAnswer: "It retains only those candidate rows where the `ON` condition evaluates to `TRUE`, discarding rows that evaluate to `FALSE` or `UNKNOWN` (NULL).",
    explanation: "INNER JOIN filtering mechanics.",
    hint: "Retains only rows where the ON condition is TRUE.",
    level: "basic"
  },
  {
    question: "What is the Nested-Loop Join (NLJ) algorithm in MySQL?",
    shortAnswer: "An execution algorithm where the query engine reads each row from the outer driving table and performs an indexed lookup on the inner joined table.",
    explanation: "Nested-Loop Join execution strategy.",
    hint: "Iterates outer rows and does index lookups on inner table.",
    level: "moderate"
  },
  {
    question: "What is the Block Nested-Loop (BNL) Join algorithm in MySQL?",
    shortAnswer: "An optimization for unindexed joins that reads a block of outer rows into an in-memory `join_buffer` to scan the inner table fewer times, reducing disk I/O.",
    explanation: "Block Nested-Loop join buffer mechanism.",
    hint: "Loads chunks of outer rows into memory to reduce table scans.",
    level: "moderate"
  },
  {
    question: "What major join optimization was introduced in MySQL 8.0 to replace Block Nested-Loop joins?",
    shortAnswer: "Hash Join (which builds an in-memory hash table on the smaller relation and probes it with the larger relation).",
    explanation: "Hash Join in MySQL 8.0+.",
    hint: "Hash Join.",
    level: "moderate"
  },
  {
    question: "Why should table aliases (e.g. `s.student_id = e.student_id`) always be used in multi-table queries?",
    shortAnswer: "To prevent 'Column is ambiguous' SQL errors and clearly identify the origin of shared column names.",
    explanation: "Table aliases and ambiguity prevention.",
    hint: "Prevents column ambiguity errors.",
    level: "basic"
  },
  {
    question: "In academy management, if `students` has 5 rows and `courses` has 4 rows, how many candidate rows are evaluated in Stage 1 of a join?",
    shortAnswer: "20 candidate rows (5 × 4 = 20).",
    explanation: "Intermediate candidate row evaluation count.",
    hint: "5 × 4 = 20.",
    level: "basic"
  },
  {
    question: "Can a `CROSS JOIN` include an `ON` or `WHERE` clause?",
    shortAnswer: "YES. In MySQL, `CROSS JOIN` with an `ON` or `WHERE` clause behaves identically to an `INNER JOIN`.",
    explanation: "MySQL syntax equivalence between CROSS JOIN with ON and INNER JOIN.",
    hint: "Yes, in MySQL it behaves like an INNER JOIN when a condition is provided.",
    level: "moderate"
  },
  {
    question: "When is an intentional `CROSS JOIN` legitimately useful in real-world software applications?",
    shortAnswer: "When generating comprehensive matrixes, such as combining all product sizes with all colors, or generating every day of the month for schedule reporting.",
    explanation: "Legitimate production use cases for CROSS JOIN.",
    hint: "Generating combination matrixes (sizes × colors, days × slots).",
    level: "basic"
  },
  {
    question: "What is the three-valued logic result when comparing a column to NULL in a join condition (e.g. `colA = colB` where colB is NULL)?",
    shortAnswer: "`UNKNOWN` (which is treated as `FALSE` by `INNER JOIN` and filters out the row).",
    explanation: "Three-valued logic in join predicates.",
    hint: "Evaluates to UNKNOWN and gets filtered out.",
    level: "basic"
  },
  {
    question: "What is the 'Driving Table' (Outer Table) in an SQL join execution plan?",
    shortAnswer: "The first table chosen by the query optimizer to initiate the join loop, typically the table with the most selective filter or fewer rows.",
    explanation: "Definition of the driving table.",
    hint: "The first table scanned in the join execution loop.",
    level: "moderate"
  },
  {
    question: "How can a developer inspect which join algorithm MySQL is using for a query?",
    shortAnswer: "By prefixing the query with `EXPLAIN` or `EXPLAIN FORMAT=TREE`.",
    explanation: "Query execution plan inspection using EXPLAIN.",
    hint: "Use EXPLAIN or EXPLAIN FORMAT=TREE.",
    level: "basic"
  },
  {
    question: "What is the time complexity of a naive Cartesian Product evaluation without indexes?",
    shortAnswer: "O(M × N), where M and N are the row counts of the two tables.",
    explanation: "Computational complexity of Cartesian product.",
    hint: "O(M × N).",
    level: "basic"
  },
  {
    question: "What is the time complexity of an indexed Nested-Loop Join where the inner table has a B-Tree primary key?",
    shortAnswer: "O(M × log N) or O(M) with B-Tree root caching, which is orders of magnitude faster than O(M × N).",
    explanation: "Indexed join performance scaling.",
    hint: "O(M × log N), dramatically faster than full table scans.",
    level: "moderate"
  },
  {
    question: "In relational algebra, what symbol represents the Cartesian Product?",
    shortAnswer: "The multiplication symbol (×).",
    explanation: "Relational algebra notation for Cartesian product.",
    hint: "Multiplication sign (×).",
    level: "basic"
  },
  {
    question: "In relational algebra, what symbol represents the Theta Join (conditioned join)?",
    shortAnswer: "The bowtie symbol with a condition subscript (⋈_θ).",
    explanation: "Relational algebra notation for Theta join.",
    hint: "Bowtie symbol (⋈_θ).",
    level: "basic"
  },
  {
    question: "How is Theta Join (⋈_θ) formally defined in relational algebra?",
    shortAnswer: "As a selection (filter) applied over a Cartesian Product: R1 ⋈_θ R2 = σ_θ(R1 × R2).",
    explanation: "Mathematical equivalence between join and filtered Cartesian product.",
    hint: "Selection over a Cartesian Product: σ_θ(R1 × R2).",
    level: "moderate"
  },
  {
    question: "What happens if both tables in a join contain a column named `id` and you write `SELECT id FROM tableA JOIN tableB ...`?",
    shortAnswer: "MySQL returns an 'ERROR 1052 (23000): Column 'id' in field list is ambiguous'.",
    explanation: "Ambiguous column error.",
    hint: "Error: Column is ambiguous.",
    level: "basic"
  },
  {
    question: "How do you resolve the ambiguous column error?",
    shortAnswer: "By qualifying the column with its table name or alias: `SELECT a.id, b.id FROM tableA a JOIN tableB b ...`.",
    explanation: "Qualifying columns with aliases.",
    hint: "Prefix the column with its table name or alias.",
    level: "basic"
  },
  {
    question: "Why should `SELECT *` be avoided in production multi-table joins?",
    shortAnswer: "Because it retrieves all columns from all joined tables, transferring unnecessary bytes over the network and breaking queries if duplicate column names exist.",
    explanation: "SELECT * hazards in joins.",
    hint: "Wastes bandwidth, increases I/O, and causes duplicate column name collisions.",
    level: "basic"
  },
  {
    question: "What system variable in MySQL controls the memory allocated for Block Nested-Loop joins?",
    shortAnswer: "`join_buffer_size`.",
    explanation: "MySQL join buffer configuration variable.",
    hint: "join_buffer_size.",
    level: "expert"
  },
  {
    question: "In restaurant POS systems, how can a Cartesian Product generate all combos of 5 burgers and 4 drinks?",
    shortAnswer: "`SELECT b.burger_name, d.drink_name FROM burgers b CROSS JOIN drinks d;` (produces 20 combos).",
    explanation: "Practical combo matrix generation.",
    hint: "CROSS JOIN between burgers and drinks produces 20 combinations.",
    level: "basic"
  },
  {
    question: "Does the order of tables in an `INNER JOIN` (`A JOIN B` vs `B JOIN A`) affect the final result set?",
    shortAnswer: "NO. Mathematically, INNER JOIN is commutative (A ⋈ B = B ⋈ A), and the MySQL optimizer will pick the most efficient driving table regardless of written order.",
    explanation: "Commutativity of INNER JOIN.",
    hint: "No, INNER JOIN is commutative and the optimizer picks the best order.",
    level: "basic"
  },
  {
    question: "What is the ultimate takeaway for database engineers regarding Cartesian Products and Join Mechanics?",
    shortAnswer: "Every SQL join is fundamentally a filtered Cartesian product (R1 ⋈_θ R2 = σ_θ(R1 × R2)); always provide clear, indexed join predicates to prevent Cartesian explosions and achieve sub-millisecond query performance.",
    explanation: "Final summary conclusion for Topic 0 in Module 5.",
    hint: "All joins are filtered Cartesian products; use indexed join predicates to prevent Cartesian explosions.",
    level: "basic"
  }
];

export default questions;
