const questions = [
  {
    question: "What is the primary advantage of resource sharing in a network?",
    shortAnswer: "It reduces costs by allowing multiple users to share hardware and software.",
    explanation: "Instead of each user having their own printer or software license, a network centralises these resources.",
    hint: "Think of a lab with one printer serving all students.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does networking improve communication?",
    shortAnswer: "By enabling email, instant messaging, video calls, and collaborative platforms.",
    explanation: "Networks carry data that allows people to interact in real time across distances.",
    hint: "How do you chat with friends online?",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is centralised data management and why is it beneficial?",
    shortAnswer: "Storing data on a central server for easy backup, security, and access control.",
    explanation: "It simplifies backup, reduces duplication, and ensures consistent security policies.",
    hint: "All student records stored in one secure place.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does networking support remote access?",
    shortAnswer: "By allowing users to connect to the network from outside via VPN or cloud services.",
    explanation: "Remote access enables telecommuting, mobile work, and access to files from anywhere.",
    hint: "Working from home while accessing office files.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is scalability in the context of networking advantages?",
    shortAnswer: "The ability to add new users and devices without major redesign.",
    explanation: "A scalable network grows with the organisation, avoiding costly overhauls.",
    hint: "Adding more computers without breaking the network.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does networking reduce costs?",
    shortAnswer: "By sharing expensive hardware (printers, servers) and centralising software licenses.",
    explanation: "Organisations can buy one high-end printer instead of many, and use site licenses for software.",
    hint: "One printer for the whole office.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the advantage of improved security in a networked environment?",
    shortAnswer: "Centralised security controls like firewalls and authentication are easier to enforce.",
    explanation: "Network administrators can monitor traffic, apply updates, and manage access from a single point.",
    hint: "One lock for the whole building instead of individual locks.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does networking enhance collaboration?",
    shortAnswer: "By providing shared workspaces, version control, and real-time editing tools.",
    explanation: "Teams can work on documents simultaneously, track changes, and communicate effectively.",
    hint: "Multiple people editing a Google Doc together.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is high availability in networking?",
    shortAnswer: "The network's ability to remain operational despite failures, through redundancy.",
    explanation: "Redundant links, power supplies, and servers ensure minimal downtime.",
    hint: "The network keeps working even if one component fails.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Why is centralised management a key advantage?",
    shortAnswer: "It simplifies administration, troubleshooting, and policy enforcement.",
    explanation: "Admins can monitor the entire network from one dashboard, saving time and reducing errors.",
    hint: "One control panel for everything.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does networking benefit educational institutions?",
    shortAnswer: "It enables resource sharing, online learning, communication, and remote access.",
    explanation: "Students can access materials, submit assignments, and collaborate from anywhere.",
    hint: "Online classes and shared lab resources.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of networking in business continuity?",
    shortAnswer: "It provides redundant paths and backups, ensuring operations continue during crises.",
    explanation: "Failover mechanisms and off-site backups protect against disasters.",
    hint: "A company that can still operate after a fire.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does networking improve customer service?",
    shortAnswer: "By enabling quick access to customer data and support tools for staff.",
    explanation: "Agents can retrieve customer history and resolve issues faster.",
    hint: "Call centre agents pulling up your account instantly.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the advantage of using a network for software deployment?",
    shortAnswer: "Centralised deployment ensures all users have the same, updated version.",
    explanation: "IT can push updates to all computers simultaneously, reducing compatibility issues.",
    hint: "One update applies to every machine.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does networking enable better decision-making?",
    shortAnswer: "By providing access to real-time data and analytics from across the organisation.",
    explanation: "Managers can view dashboards and reports generated from centralised data.",
    hint: "Sales data updated instantly for the CEO.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the advantage of network printing?",
    shortAnswer: "Allows multiple users to share a single printer, reducing costs and space.",
    explanation: "Print jobs are queued and managed centrally, saving paper and maintenance.",
    hint: "Everyone prints to the same machine.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does networking facilitate e-commerce?",
    shortAnswer: "It connects customers, web servers, payment gateways, and inventory systems.",
    explanation: "Online shopping relies on networks to process transactions and update stock.",
    hint: "Buying a book online – the network connects you to the seller.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the benefit of network monitoring tools?",
    shortAnswer: "They provide visibility into performance, security, and usage trends.",
    explanation: "Helps detect anomalies, plan capacity, and troubleshoot proactively.",
    hint: "A dashboard showing your network's health.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does networking support innovation?",
    shortAnswer: "By enabling collaboration, access to external resources, and rapid prototyping.",
    explanation: "Teams can share ideas, tap into cloud services, and test new solutions quickly.",
    hint: "Developers using shared repositories and cloud testing environments.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the advantage of a unified communication system?",
    shortAnswer: "It integrates voice, video, and messaging into one platform, improving productivity.",
    explanation: "Users can switch between communication modes seamlessly.",
    hint: "One app for calls, messages, and meetings.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does networking improve asset management?",
    shortAnswer: "By tracking hardware and software inventory across the organisation.",
    explanation: "Network scanning tools can detect all connected devices and their status.",
    hint: "Knowing exactly what you have and where it is.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of networking in supply chain management?",
    shortAnswer: "It connects suppliers, manufacturers, and distributors for real-time coordination.",
    explanation: "Inventory levels, orders, and shipments are tracked via network-linked systems.",
    hint: "A global retailer knowing stock levels instantly.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does networking enable edge computing?",
    shortAnswer: "By distributing processing closer to data sources, reducing latency and bandwidth use.",
    explanation: "Edge devices (IoT) process data locally and send only relevant info to the cloud.",
    hint: "Smart cameras detecting events without sending full video to the cloud.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are the advantages of software-defined networking (SDN)?",
    shortAnswer: "Centralised control, programmability, and easier network automation.",
    explanation: "SDN separates control and data planes, allowing dynamic routing and policy changes.",
    hint: "A network you can program like software.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does networking enhance knowledge management?",
    shortAnswer: "By centralising knowledge bases, wikis, and collaborative platforms.",
    explanation: "Employees can find and share expertise easily, improving organisational learning.",
    hint: "A company wiki accessible to all.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the advantage of network virtualization?",
    shortAnswer: "It allows multiple virtual networks to run on the same physical infrastructure.",
    explanation: "Improves resource utilisation, isolation, and flexibility.",
    hint: "Separate virtual networks for different departments on one set of hardware.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does networking facilitate AI and machine learning?",
    shortAnswer: "By providing the data pipeline and distributed computing required for training models.",
    explanation: "AI models need large datasets and GPU clusters connected via high-speed networks.",
    hint: "Training a language model across thousands of servers.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the benefit of a well-designed network for remote teams?",
    shortAnswer: "It ensures seamless collaboration, access to resources, and security.",
    explanation: "VPN, cloud services, and collaboration tools depend on reliable network infrastructure.",
    hint: "A globally distributed team working as if in the same office.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does networking contribute to sustainability?",
    shortAnswer: "By optimising resource usage (e.g., shared printers, virtualisation) and enabling remote work.",
    explanation: "Reduces physical infrastructure, travel, and energy consumption.",
    hint: "Less printing, fewer commutes – greener operations.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are the long-term strategic advantages of networking?",
    shortAnswer: "It provides a competitive edge through agility, innovation, and customer responsiveness.",
    explanation: "Organisations with robust networks adapt faster to market changes and customer needs.",
    hint: "The network is the nervous system of a modern enterprise.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;