const questions = [
  {
    question: "What is resource sharing in a computer network?",
    shortAnswer: "The ability to use hardware, software, and data from any connected device.",
    explanation: "Examples: sharing a printer, accessing a shared drive, or using a common database. It reduces costs and improves efficiency.",
    hint: "Think of a lab with one printer serving all computers.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What does scalability mean in networking?",
    shortAnswer: "The ability to add new devices and users without significant redesign.",
    explanation: "A scalable network can grow in size and traffic load gracefully.",
    hint: "Adding more computers to a network without breaking it.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Why is reliability important in a network?",
    shortAnswer: "To ensure data is delivered correctly and consistently, even under load.",
    explanation: "Reliability means the network works as expected without frequent failures or errors.",
    hint: "Think of a network that never drops your connection.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is network security?",
    shortAnswer: "Measures to protect the network from unauthorized access and threats.",
    explanation: "Includes firewalls, encryption, authentication, and access control.",
    hint: "Keeping your data safe from hackers.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Define bandwidth in simple terms.",
    shortAnswer: "The maximum data transfer rate of a network, usually in bits per second.",
    explanation: "Higher bandwidth means more data can be transmitted per second.",
    hint: "Think of it as a highway's speed limit.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is latency and why does it matter?",
    shortAnswer: "Latency is the time delay in data transmission; low latency is critical for real-time apps.",
    explanation: "High latency causes lag in video calls and gaming.",
    hint: "The time between you speaking and the other person hearing it.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is fault tolerance?",
    shortAnswer: "The ability of a network to continue operating when a component fails.",
    explanation: "Achieved through redundancy (backup links, power supplies, etc.).",
    hint: "A network that doesn't crash when one device breaks.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is interoperability in networking?",
    shortAnswer: "The ability of devices from different vendors to work together using common protocols.",
    explanation: "Standards like TCP/IP ensure interoperability.",
    hint: "A Dell computer can talk to an Apple one.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does centralised management benefit a network?",
    shortAnswer: "It allows administrators to monitor and configure the network from a single point.",
    explanation: "Simplifies troubleshooting, policy updates, and security enforcement.",
    hint: "One dashboard to rule them all.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the difference between bandwidth and throughput?",
    shortAnswer: "Bandwidth is the theoretical maximum; throughput is the actual measured data transfer.",
    explanation: "Throughput is affected by latency, congestion, and overhead.",
    hint: "Bandwidth is the speed limit; throughput is the actual speed you travel.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "Why is security often a trade-off with performance?",
    shortAnswer: "Security measures like encryption add overhead, slowing down data transfer.",
    explanation: "More security (e.g., deep packet inspection) consumes CPU and increases latency.",
    hint: "Locking a door makes it secure but takes time to open.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of redundancy in fault tolerance?",
    shortAnswer: "Redundancy provides backup components to take over if primary ones fail.",
    explanation: "Example: dual power supplies, multiple network paths, backup servers.",
    hint: "Having a spare tire in the car.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does network congestion affect performance?",
    shortAnswer: "Congestion causes packets to be delayed or dropped, reducing throughput and increasing latency.",
    explanation: "Traffic management (QoS, buffering) helps mitigate congestion.",
    hint: "Too many cars on a highway slow everyone down.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the significance of Quality of Service (QoS)?",
    shortAnswer: "QoS prioritises critical traffic over less important traffic.",
    explanation: "Ensures that real-time applications (VoIP, video) get the bandwidth they need.",
    hint: "Priority lane for emergency vehicles.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does network topology affect characteristics?",
    shortAnswer: "Different topologies (star, mesh, ring) affect reliability, scalability, and cost.",
    explanation: "Mesh is highly reliable but expensive; star is cheaper but has a single point of failure.",
    hint: "The layout of the network impacts its strengths.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the importance of documentation for network management?",
    shortAnswer: "Documentation provides a map for troubleshooting and planning.",
    explanation: "Network diagrams, IP lists, and configs help maintain consistency.",
    hint: "A good map makes navigation easy.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do protocols contribute to interoperability?",
    shortAnswer: "Common protocols (TCP/IP, HTTP) ensure different devices understand each other.",
    explanation: "Protocols define rules for communication, making interoperability possible.",
    hint: "Speaking the same language.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is meant by 'network performance'?",
    shortAnswer: "It encompasses bandwidth, throughput, latency, and error rates.",
    explanation: "Performance determines user experience and application viability.",
    hint: "How fast and reliable the network feels.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "Why is scalability often a concern for growing organisations?",
    shortAnswer: "As organisations expand, they need to add more users and devices without major upgrades.",
    explanation: "A non-scalable network would require a complete redesign, which is costly.",
    hint: "Planning for future growth.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the cost-effectiveness characteristic?",
    shortAnswer: "Balancing performance, security, and reliability with budget constraints.",
    explanation: "Choosing equipment and solutions that provide good value for money.",
    hint: "Getting the most bang for your buck.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does latency affect real-time applications?",
    shortAnswer: "High latency causes delays, making real-time interactions (video calls, gaming) unusable.",
    explanation: "Applications require low latency (under 150ms) for a smooth experience.",
    hint: "A delayed conversation is frustrating.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the relationship between reliability and fault tolerance?",
    shortAnswer: "Fault tolerance is a key factor in achieving high reliability.",
    explanation: "A reliable network must be fault-tolerant to maintain service during failures.",
    hint: "Fault tolerance is the how; reliability is the outcome.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How can you improve network security without sacrificing performance?",
    shortAnswer: "By using hardware-accelerated encryption, efficient algorithms, and offloading security tasks.",
    explanation: "Modern CPUs have AES-NI instructions for fast encryption; also use dedicated security appliances.",
    hint: "Hardware acceleration can balance security and speed.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the impact of network design on scalability?",
    shortAnswer: "A hierarchical design (core, distribution, access) allows easier scaling.",
    explanation: "Modular designs can be expanded by adding modules rather than redesigning.",
    hint: "Think of a building designed for adding extra floors.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does network monitoring help maintain performance?",
    shortAnswer: "Monitoring detects bottlenecks, failures, and unusual traffic, enabling proactive action.",
    explanation: "Tools like SNMP, NetFlow, and ping provide real-time insights.",
    hint: "A dashboard showing your network's vital signs.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the concept of 'trade-offs' in network characteristics?",
    shortAnswer: "Improving one characteristic often degrades another (e.g., security vs. speed).",
    explanation: "Designers must balance conflicting requirements.",
    hint: "You can't have everything perfectly; you must choose priorities.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do you measure throughput in practice?",
    shortAnswer: "By sending known amounts of data and measuring the time taken, using tools like iPerf.",
    explanation: "Throughput = data size / time. It's affected by network conditions.",
    hint: "Test the actual speed, not just the advertised one.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the importance of standardisation in interoperability?",
    shortAnswer: "Standards ensure that devices from different vendors can communicate seamlessly.",
    explanation: "Without standards, the internet would be a fragmented mess.",
    hint: "Everyone following the same rules.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How can redundancy be implemented without excessive cost?",
    shortAnswer: "By using virtualisation, load balancing, and affordable backup links.",
    explanation: "Prioritise critical components for redundancy.",
    hint: "Not everything needs 100% redundancy; focus on the critical parts.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are the consequences of ignoring scalability?",
    shortAnswer: "The network will become slow, unreliable, and costly to upgrade when the organisation grows.",
    explanation: "Ignoring scalability leads to frequent redesigns and downtime.",
    hint: "Like building a house without room for an extra room.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;