const questions = [
  {
    id: 1,
    question: "What does ASCII stand for?",
    options: [
      "American Standard Code for Information Interchange",
      "All Standard Characters for Internet Integration",
      "Advanced System Coding for Information Interchange",
      "Automated System Code for International Interfaces"
    ],
    correctAnswer: 0,
    explanation: "ASCII stands for 'American Standard Code for Information Interchange'. Standard ASCII uses a 7-bit encoding scheme to represent 128 distinct characters (codes 0 to 127).",
    hint: "American Standard Code for Information Interchange."
  },
  {
    id: 2,
    question: "How many unique characters can standard 7-bit ASCII encode?",
    options: ["64", "128", "256", "512"],
    correctAnswer: 1,
    explanation: "With 7 bits, 2⁷ = 128 unique character codes (0 to 127) can be encoded.",
    hint: "2 to the power 7."
  },
  {
    id: 3,
    question: "What is the ASCII value of uppercase letter 'A' and lowercase letter 'a' respectively?",
    options: ["65 and 97", "48 and 65", "97 and 65", "64 and 96"],
    correctAnswer: 0,
    explanation: "In ASCII encoding, uppercase 'A' is 65 (binary 01000001) and lowercase 'a' is 97 (binary 01100001). The difference between uppercase and lowercase is 32 (bit 5 flipped).",
    hint: "'A' starts at 65, 'a' starts at 97."
  },
  {
    id: 4,
    question: "What is the ASCII decimal code for character digit '0'?",
    options: ["0", "32", "48", "65"],
    correctAnswer: 2,
    explanation: "The numeric character '0' has ASCII code 48 (binary 00110000), '1' is 49, up to '9' which is 57.",
    hint: "Digits 0 to 9 map to ASCII 48 to 57."
  },
  {
    id: 5,
    question: "What does ISCII stand for in Indian computing standards?",
    options: [
      "Indian Standard Code for Information Interchange",
      "International Standard Coding for Indian Interfaces",
      "Integrated System Character Information Interchange",
      "Indian Supercomputer Code for Internet Interfaces"
    ],
    correctAnswer: 0,
    explanation: "ISCII stands for 'Indian Standard Code for Information Interchange'. Developed by the Bureau of Indian Standards (BIS) in 1991, it is an 8-bit encoding scheme (256 characters) that encodes Indian scripts (Devanagari, Bengali, Tamil, Telugu, etc.) alongside Latin ASCII.",
    hint: "Indian Standard Code for Information Interchange (8-bit)."
  },
  {
    id: 6,
    question: "Why was UNICODE developed to replace regional 7-bit and 8-bit encoding schemes?",
    options: [
      "To make files smaller on disk",
      "To provide a universal, unique numeric code point for every character in every human writing system, historical script, and emoji symbol",
      "To restrict computers to English characters only",
      "To encrypt data during transmission"
    ],
    correctAnswer: 1,
    explanation: "Unicode is an international character encoding standard that assigns a unique code point (`U+XXXX`) to every symbol across all global languages (English, Bengali, Hindi, Arabic, Chinese, emojis), solving internationalization and font corruption issues.",
    hint: "Universal character encoding covering all world languages."
  },
  {
    id: 7,
    question: "Which Unicode encoding scheme uses a variable length of 1 to 4 bytes per character and is 100% backward-compatible with 7-bit ASCII?",
    options: ["UTF-8", "UTF-16", "UTF-32", "ISCII"],
    correctAnswer: 0,
    explanation: "UTF-8 (8-bit Unicode Transformation Format) is variable-width (1 to 4 bytes). Standard ASCII characters (0–127) take exactly 1 byte, making UTF-8 the dominant encoding standard of the World Wide Web.",
    hint: "Variable-length 1-byte backwards compatible with ASCII."
  },
  {
    id: 8,
    question: "How is the 1's complement of a binary number obtained [Enrichment]?",
    options: [
      "By adding 1 to the binary number",
      "By inverting every bit: flipping 0s to 1s and 1s to 0s",
      "By shifting all bits to the left by 1 position",
      "By converting the number to hexadecimal"
    ],
    correctAnswer: 1,
    explanation: "The 1's complement of a binary bitstring is generated by bitwise NOT: replacing every '0' with '1' and every '1' with '0'.",
    hint: "Invert / flip all bits."
  },
  {
    id: 9,
    question: "What is the 1's complement of the 8-bit binary number 00101100 [Enrichment]?",
    options: ["11010011", "11010100", "00101101", "11101100"],
    correctAnswer: 0,
    explanation: "Inverting each bit of 00101100: 0->1, 0->1, 1->0, 0->1, 1->0, 1->0, 0->1, 0->1 = 11010011.",
    hint: "Flip every 0 to 1 and every 1 to 0."
  },
  {
    id: 10,
    question: "How is the 2's complement of a binary number calculated [Enrichment]?",
    options: [
      "Multiply the number by 2",
      "Calculate the 1's complement (invert all bits) and add 1 to the least significant bit (LSB)",
      "Subtract 1 from the binary number",
      "Shift bits to the right twice"
    ],
    correctAnswer: 1,
    explanation: "2's Complement = (1's Complement) + 1. It is the universal standard for representing signed negative integers in digital ALU hardware.",
    hint: "Invert all bits, then add 1."
  },
  {
    id: 11,
    question: "Find the 2's complement representation of -13 in an 8-bit register [Enrichment]:",
    options: ["11110011", "11110010", "11101101", "10001101"],
    correctAnswer: 0,
    explanation: "+13 in 8-bit binary = 00001101. 1's complement = 11110010. Add 1 = 11110011. Thus, -13 in 8-bit 2's complement is 11110011.",
    hint: "00001101 -> invert to 11110010 -> add 1 to get 11110011."
  },
  {
    id: 12,
    question: "What is the primary advantage of 2's complement over 1's complement and Sign-Magnitude in CPU arithmetic [Enrichment]?",
    options: [
      "It eliminates the ambiguity of two representations of zero (+0 and -0) and allows addition and subtraction to be performed with identical adder circuitry",
      "It makes numbers double in value",
      "It requires fewer bits of physical RAM",
      "It prevents memory fragmentation"
    ],
    correctAnswer: 0,
    explanation: "In 2's complement, there is only one unique representation for zero (`00000000`), and subtraction $A - B$ is executed directly by adding $A + (\text{2's complement of } B)$, simplifying CPU ALU circuit design.",
    hint: "Unique zero and unified addition/subtraction hardware."
  },
  {
    id: 13,
    question: "What is the range of signed integers representable in an 8-bit 2's complement format [Enrichment]?",
    options: [
      "-128 to +127",
      "-127 to +127",
      "0 to 255",
      "-256 to +255"
    ],
    correctAnswer: 0,
    explanation: "For an $n$-bit 2's complement system, the range of representable signed integers is $-2^{n-1} \text{ to } +2^{n-1} - 1$. For $n=8$: $-2^7 \text{ to } +2^7 - 1 = -128 \text{ to } +127$.",
    hint: "Formula: -2^(n-1) to +2^(n-1) - 1."
  },
  {
    id: 14,
    question: "In Python, which built-in function returns the Unicode code point (integer) of a given character?",
    options: ["ord()", "chr()", "ascii()", "code()"],
    correctAnswer: 0,
    explanation: "`ord('A')` returns `65`. Conversely, `chr(65)` converts an integer Unicode code point back to its corresponding string character `'A'`.",
    hint: "ord() for ordinal value, chr() for character."
  },
  {
    id: 15,
    question: "What is the output of the Python expression `chr(ord('B') + 3)`?",
    options: ["'E'", "'D'", "'C'", "68"],
    correctAnswer: 0,
    explanation: "`ord('B')` evaluates to 66. 66 + 3 = 69. `chr(69)` returns `'E'`.",
    hint: "'B' + 3 letters in the alphabet -> 'C', 'D', 'E'."
  },
  {
    id: 16,
    question: "What is the fixed length of UTF-32 encoding for every character?",
    options: ["1 byte (8 bits)", "2 bytes (16 bits)", "4 bytes (32 bits)", "Variable length"],
    correctAnswer: 2,
    explanation: "UTF-32 is a fixed-length encoding where every single character code point is stored in exactly 4 bytes (32 bits), enabling simple random array indexing at the cost of higher storage overhead.",
    hint: "32 bits = 4 bytes fixed length."
  },
  {
    id: 17,
    question: "In Sign-Magnitude representation, what does the Most Significant Bit (MSB) signify [Enrichment]?",
    options: [
      "The exponent of the number",
      "The sign of the number: 0 for positive (+), 1 for negative (-)",
      "The parity check bit",
      "The fractional multiplier"
    ],
    correctAnswer: 1,
    explanation: "In sign-magnitude, the leftmost bit (MSB) is the sign flag ($0 = +, 1 = -$), and the remaining $n-1$ bits store the absolute magnitude of the number.",
    hint: "MSB 0 = positive, MSB 1 = negative."
  },
  {
    id: 18,
    question: "What is the ASCII value of the space character (' ') in decimal?",
    options: ["0", "13", "32", "48"],
    correctAnswer: 2,
    explanation: "The space character `' '` has ASCII decimal code 32 (binary 00100000, hex 0x20).",
    hint: "ASCII 32 is the spacebar character."
  },
  {
    id: 19,
    question: "What is the 8-bit binary representation of +45 in 2's complement [Enrichment]?",
    options: ["00101101", "10101101", "11010011", "00101111"],
    correctAnswer: 0,
    explanation: "Positive integers in 2's complement are represented identically to standard unsigned binary with a leading '0' sign bit. 45 = 32 + 8 + 4 + 1 = 00101101.",
    hint: "Positive numbers in 2's complement have MSB = 0 and normal binary magnitude."
  },
  {
    id: 20,
    question: "What happens in an 8-bit signed register if you add 1 to +127 in 2's complement [Enrichment]?",
    options: [
      "+128 is produced correctly",
      "Arithmetic Overflow occurs and the result wraps around to -128 (10000000₂)",
      "The computer crashes with a hardware fuse blown",
      "The register stays at 127"
    ],
    correctAnswer: 1,
    explanation: "In an 8-bit signed system, +127 is `01111111`. Adding 1 yields `10000000`, which represents -128 in 2's complement. This condition is known as integer arithmetic overflow.",
    hint: "Overflow wraps positive maximum to negative minimum."
  },
  {
    id: 21,
    question: "Which Indian organization designed the ISCII standard in 1991?",
    options: [
      "Bureau of Indian Standards (BIS)",
      "ISRO",
      "CBSE",
      "Department of Telecom"
    ],
    correctAnswer: 0,
    explanation: "ISCII (IS 13194:1991) was formulated by the Bureau of Indian Standards (BIS) in collaboration with CDAC to standardize computer keyboard overlays and font glyphs for Indian scripts.",
    hint: "Bureau of Indian Standards."
  },
  {
    id: 22,
    question: "What is the Unicode code point notation for Devanagari letter 'Ka' (क) and Bengali letter 'Ka' (ক)?",
    options: [
      "U+0915 and U+0995",
      "ASCII 65 and ASCII 66",
      "0x00 and 0x01",
      "UTF-8 only"
    ],
    correctAnswer: 0,
    explanation: "In the Unicode Standard, Devanagari 'क' is code point `U+0915` and Bengali 'ক' is code point `U+0995`.",
    hint: "Unicode code points are prefixed with U+ and 4 hex digits."
  },
  {
    id: 23,
    question: "What is the 2's complement of 11110000 [Enrichment]?",
    options: ["00010000", "00001111", "00010001", "11111111"],
    correctAnswer: 0,
    explanation: "1's complement of 11110000 = 00001111. Add 1: 00001111 + 1 = 00010000.",
    hint: "Shortcut: Keep all trailing zeros and the first '1' from right, invert all remaining bits to the left."
  },
  {
    id: 24,
    question: "What is the default string character encoding used in Python 3 source files?",
    options: ["ASCII", "UTF-8", "Latin-1", "ISCII"],
    correctAnswer: 1,
    explanation: "Python 3 source code files default to UTF-8 encoding (PEP 3120), allowing direct use of multilingual strings, international characters, and emojis in variable values and print statements.",
    hint: "Python 3 natively uses UTF-8."
  },
  {
    id: 25,
    question: "Case Study: Abhronila is developing a bilingual Python application for a community center in Naihati. Her program prints Bengali text `'নমস্কার'` and English text `'Welcome'`. Why does UTF-8 handle both seamlessly?",
    options: [
      "Because UTF-8 allocates 1 byte for English ASCII characters and 3 bytes for Bengali Unicode code points without requiring separate font drivers",
      "Because Bengali text is translated into English before printing",
      "Because the terminal converts all text into 7-bit ASCII",
      "Because Python replaces non-English characters with question marks"
    ],
    correctAnswer: 0,
    explanation: "UTF-8 dynamically scales its byte allocation per character: standard ASCII English characters occupy 1 byte, while Indic Unicode characters (like Bengali `U+0980` to `U+09FF`) are encoded in 3-byte sequences, allowing unified multilingual storage.",
    hint: "UTF-8 is variable-width, efficiently encoding both ASCII (1 byte) and Indic characters (3 bytes)."
  }
];

export default questions;
