// topic1_files/topic1_questions.js

const questions = [
  {
    question: "What is the primary purpose of the `EXPLAIN` statement in MySQL?",
    shortAnswer: "To inspect the execution plan generated by the Cost-Based Optimizer without executing the query, revealing how tables are scanned, which indexes are used, join orders, and estimated costs.",
    explanation: "Core definition and purpose of EXPLAIN.",
    hint: "Displays the execution plan chosen by the optimizer without executing the query.",
    level: "basic"
  },
  {
    question: "What statement generates the standard 12-column tabular execution plan in MySQL?",
    shortAnswer: "`EXPLAIN SELECT ...;` (or `DESCRIBE SELECT ...;` / `EXPLAIN FORMAT=TRADITIONAL SELECT ...;`).",
    explanation: "Standard tabular EXPLAIN syntax.",
    hint: "EXPLAIN SELECT ...;",
    level: "basic"
  },
  {
    question: "What statement generates the JSON-formatted execution plan in MySQL?",
    shortAnswer: "`EXPLAIN FORMAT=JSON SELECT ...;`.",
    explanation: "JSON EXPLAIN syntax.",
    hint: "EXPLAIN FORMAT=JSON SELECT ...;",
    level: "basic"
  },
  {
    question: "What statement generates the hierarchical Iterator Tree execution plan in MySQL 8.0.16+?",
    shortAnswer: "`EXPLAIN FORMAT=TREE SELECT ...;`.",
    explanation: "TREE EXPLAIN syntax.",
    hint: "EXPLAIN FORMAT=TREE SELECT ...;",
    level: "basic"
  },
  {
    question: "How do student queries for Mamata and Susmita illustrate `EXPLAIN FORMAT=TREE`?",
    shortAnswer: "Running `EXPLAIN FORMAT=TREE SELECT * FROM students s JOIN enrollments e ON s.id = e.student_id;` visually prints the nested loop join hierarchy with indentation: `-> Nested loop inner join → Table scan on e → Single-row index lookup on s`.",
    explanation: "Hierarchical visual representation of join order in TREE format.",
    hint: "Displays indented tree showing nested loop join and index lookups.",
    level: "basic"
  },
  {
    question: "What key advantage does `EXPLAIN FORMAT=JSON` have over traditional tabular `EXPLAIN`?",
    shortAnswer: "It exposes explicit mathematical cost metrics calculated by the optimizer, including `query_cost`, `read_cost`, `eval_cost`, `prefix_cost`, and `used_columns`.",
    explanation: "Granular cost metrics in JSON format.",
    hint: "Exposes exact query_cost, read_cost, eval_cost, and prefix_cost metrics.",
    level: "expert"
  },
  {
    question: "What is the 'Volcano Iterator Model' introduced in MySQL 8.0?",
    shortAnswer: "An execution engine architecture where every query step is an iterator with an `Init()` and `Read()` interface, streaming rows up the execution tree one row at a time.",
    explanation: "Volcano iterator execution engine model.",
    hint: "Iterator-based row-by-row streaming architecture used by FORMAT=TREE.",
    level: "expert"
  },
  {
    question: "How do you inspect how MySQL rewrote and normalized your SQL query?",
    shortAnswer: "Execute `EXPLAIN SELECT ...;` followed immediately by `SHOW WARNINGS;` to view the normalized rewritten query in the message column.",
    explanation: "Inspecting optimizer query rewrites via SHOW WARNINGS.",
    hint: "Run EXPLAIN followed immediately by SHOW WARNINGS;.",
    level: "basic"
  },
  {
    question: "Can `EXPLAIN` be used on DML mutation statements (`INSERT`, `UPDATE`, `DELETE`)?",
    shortAnswer: "YES; in MySQL 5.6.3+ and MySQL 8.0, `EXPLAIN` can be executed directly on `INSERT`, `UPDATE`, `DELETE`, and `REPLACE` statements without modifying data.",
    explanation: "EXPLAIN on DML statements.",
    hint: "Yes, EXPLAIN works on UPDATE, DELETE, and INSERT statements.",
    level: "basic"
  },
  {
    question: "What happens if you execute `EXPLAIN FOR CONNECTION <thread_id>;`?",
    shortAnswer: "It displays the execution plan of a currently executing query running in another active connection thread without interrupting it.",
    explanation: "Live connection EXPLAIN inspection.",
    hint: "Inspects the execution plan of a live running query in another connection.",
    level: "expert"
  },
  {
    question: "What does the `query_cost` field in `EXPLAIN FORMAT=JSON` represent?",
    shortAnswer: "The total estimated cost (I/O + CPU) calculated by the Cost-Based Optimizer for the entire query execution.",
    explanation: "query_cost metric in JSON explain.",
    hint: "Total estimated I/O and CPU cost for the entire query.",
    level: "basic"
  },
  {
    question: "What does `read_cost` represent in `EXPLAIN FORMAT=JSON`?",
    shortAnswer: "The estimated cost of reading data and index pages from storage or the buffer pool.",
    explanation: "read_cost metric in JSON explain.",
    hint: "Cost of reading storage/buffer pool pages.",
    level: "expert"
  },
  {
    question: "What does `eval_cost` represent in `EXPLAIN FORMAT=JSON`?",
    shortAnswer: "The estimated CPU cost of evaluating expressions, predicates, and conditions on examined rows.",
    explanation: "eval_cost metric in JSON explain.",
    hint: "CPU cost of evaluating row conditions.",
    level: "expert"
  },
  {
    question: "What does `prefix_cost` represent in `EXPLAIN FORMAT=JSON` for multi-table joins?",
    shortAnswer: "The cumulative cost of processing the join prefix up to the current table in the join order sequence.",
    explanation: "prefix_cost metric in JSON explain.",
    hint: "Cumulative join processing cost up to that table.",
    level: "expert"
  },
  {
    question: "Does `EXPLAIN` actually execute the query and read physical table rows?",
    shortAnswer: "NO; standard `EXPLAIN` (in all formats: tabular, JSON, TREE) only computes the estimated plan and does NOT execute the query (unlike `EXPLAIN ANALYZE`).",
    explanation: "Non-executing nature of standard EXPLAIN.",
    hint: "No, standard EXPLAIN only computes the estimated plan without executing.",
    level: "basic"
  },
  {
    question: "In what direction should you read a hierarchical `EXPLAIN FORMAT=TREE` output?",
    shortAnswer: "From the **most deeply indented child nodes (bottom-up)** to the root node at the top, representing the bottom-up flow of rows through iterators.",
    explanation: "Reading direction for FORMAT=TREE.",
    hint: "Read from the deepest indented child nodes upwards to the root.",
    level: "expert"
  },
  {
    question: "What does `-> Single-row index lookup on s using PRIMARY` signify in `FORMAT=TREE`?",
    shortAnswer: "An `eq_ref` access type where exactly one row is retrieved per parent row by traversing the primary key B+Tree.",
    explanation: "Single-row index lookup iterator.",
    hint: "Optimal eq_ref primary key lookup returning at most 1 row.",
    level: "basic"
  },
  {
    question: "What does `-> Table scan on e` signify in `FORMAT=TREE`?",
    shortAnswer: "A full table scan (`type = ALL`) where the storage engine reads every record in table `e` sequentially.",
    explanation: "Table scan iterator representation.",
    hint: "Full table scan reading all rows sequentially.",
    level: "basic"
  },
  {
    question: "What does `-> Nested loop inner join` signify in `FORMAT=TREE`?",
    shortAnswer: "A join iterator where for every row produced by the outer child iterator, matching rows are fetched from the inner child iterator.",
    explanation: "Nested loop join iterator.",
    hint: "Standard nested loop join iterating inner rows for each outer row.",
    level: "basic"
  },
  {
    question: "What does `-> Filter: (...)` signify in `FORMAT=TREE`?",
    shortAnswer: "An iterator applying a `WHERE` condition filter to discard rows that do not satisfy the predicate.",
    explanation: "Filter iterator in TREE format.",
    hint: "Applies a WHERE clause condition to filter out non-matching rows.",
    level: "basic"
  },
  {
    question: "Can `EXPLAIN` identify if a temporary table and filesort are required?",
    shortAnswer: "YES; in tabular format it shows `Using temporary; Using filesort` in the `Extra` column; in TREE format it shows `-> Sort: ...` or `-> Materialize into temporary table`.",
    explanation: "Identifying sort and temporary table iterators.",
    hint: "Yes, shows Using filesort / Using temporary or Sort/Materialize iterators.",
    level: "basic"
  },
  {
    question: "How do you specify the output format in the `EXPLAIN` command in MySQL 8.0?",
    shortAnswer: "Using the `FORMAT` option: `EXPLAIN FORMAT = [TRADITIONAL | JSON | TREE] SELECT ...`.",
    explanation: "EXPLAIN FORMAT clause syntax.",
    hint: "EXPLAIN FORMAT = TRADITIONAL | JSON | TREE SELECT ...",
    level: "basic"
  },
  {
    question: "What is the difference between `EXPLAIN FORMAT=TREE` and `EXPLAIN ANALYZE`?",
    shortAnswer: "`EXPLAIN FORMAT=TREE` prints estimated costs without running the query; `EXPLAIN ANALYZE` actually executes the query and prints both estimated costs AND actual execution times and row counts!",
    explanation: "FORMAT=TREE vs EXPLAIN ANALYZE distinction.",
    hint: "FORMAT=TREE estimates without executing; EXPLAIN ANALYZE executes to capture actual times.",
    level: "expert"
  },
  {
    question: "Why is `EXPLAIN FORMAT=JSON` preferred for automated performance monitoring tools?",
    shortAnswer: "Because JSON output is structured, machine-parsable, and provides structured keys for cost and index utilization without fragile regex parsing of tabular output.",
    explanation: "Programmatic consumption of JSON explain.",
    hint: "Structured, machine-readable format with complete numerical cost metrics.",
    level: "expert"
  },
  {
    question: "What happens when you run `EXPLAIN` on a query containing a subquery in the `SELECT` list?",
    shortAnswer: "It displays separate execution blocks with distinct `id` values (e.g. `id = 1` for primary query, `id = 2` for `SUBQUERY` or `DEPENDENT SUBQUERY`).",
    explanation: "Subquery representation in EXPLAIN.",
    hint: "Shows distinct id numbers for primary query and subquery blocks.",
    level: "basic"
  },
  {
    question: "What does `attached_condition` in `EXPLAIN FORMAT=JSON` show?",
    shortAnswer: "The exact predicate condition pushed down and evaluated at that specific stage or table scan in the execution plan.",
    explanation: "attached_condition field in JSON explain.",
    hint: "The WHERE predicate evaluated at that specific table scan.",
    level: "expert"
  },
  {
    question: "Can an `EXPLAIN` output change over time for the exact same query on the same table?",
    shortAnswer: "YES; as rows are added, updated, or deleted, statistical metadata changes, and the Optimizer may switch from a Table Scan to an Index Scan or alter join orders.",
    explanation: "Dynamic nature of execution plans based on data volume.",
    hint: "Yes, data growth and statistical updates alter optimizer cost calculations.",
    level: "basic"
  },
  {
    question: "What does `EXPLAIN FORMAT=TREE` output when a query requires a Hash Join in MySQL 8.0?",
    shortAnswer: "`-> Inner hash join (s.department_id = d.department_id)` (used for joins on un-indexed equality predicates).",
    explanation: "Hash join representation in FORMAT=TREE.",
    hint: "Shows → Inner hash join for un-indexed equi-joins.",
    level: "expert"
  },
  {
    question: "How does `SHOW WARNINGS` reveal constant folding and subquery flattening?",
    shortAnswer: "The rewritten query displayed in `SHOW WARNINGS` shows expressions pre-evaluated (e.g. `10 * 100` becomes `1000`) and subqueries transformed into inner joins or semi-joins.",
    explanation: "SHOW WARNINGS transformation inspection.",
    hint: "Shows pre-evaluated constants and subqueries rewritten into joins.",
    level: "expert"
  },
  {
    question: "What is the senior architect's summary rule for generating Execution Plans?",
    shortAnswer: "Always use **`EXPLAIN FORMAT=TREE`** as your primary visual diagnostic tool in MySQL 8.0 to inspect iterator hierarchies and join orders; use **`EXPLAIN FORMAT=JSON`** to extract precise `query_cost` and `eval_cost` metrics for automated tooling; and inspect **`SHOW WARNINGS`** to verify optimizer query rewrites and transformations.",
    explanation: "Authoritative architectural best practices for EXPLAIN formats.",
    hint: "Use FORMAT=TREE for visual hierarchy + FORMAT=JSON for costs + SHOW WARNINGS for rewrites.",
    level: "expert"
  }
];

export default questions;
