const questions = [
  {
    question: "What is the biggest security risk in a network?",
    shortAnswer: "Unauthorised access and data breaches.",
    explanation: "Networks can be attacked by hackers, malware, and insiders, compromising sensitive data.",
    hint: "Think about how a single weak password can expose everything.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Why is the initial cost of networking a disadvantage?",
    shortAnswer: "Hardware, software, installation, and training require significant upfront investment.",
    explanation: "Small organisations may find the cost prohibitive, especially for high-end equipment.",
    hint: "Buying switches, routers, cables, and hiring experts is expensive.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a single point of failure in a network?",
    shortAnswer: "A component whose failure causes the entire network to stop working.",
    explanation: "For example, if a central switch or server fails without backup, the network goes down.",
    hint: "A critical part that, if broken, breaks everything.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does network complexity affect organisations?",
    shortAnswer: "It requires skilled staff, increases troubleshooting time, and raises the risk of misconfigurations.",
    explanation: "Complex networks are harder to manage and more prone to errors.",
    hint: "Too many devices and rules make it hard to keep track.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a performance bottleneck?",
    shortAnswer: "A point in the network where traffic slows down due to limited capacity.",
    explanation: "Bottlenecks can be caused by slow links, overloaded servers, or congested switches.",
    hint: "A narrow road that causes traffic jams.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Why is network downtime a major disadvantage?",
    shortAnswer: "It halts operations, causing productivity loss, revenue loss, and customer dissatisfaction.",
    explanation: "Even short outages can be very costly for businesses.",
    hint: "Imagine an e-commerce site being down for just 10 minutes.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the impact of wireless interference?",
    shortAnswer: "It degrades signal quality, causing slow speeds and disconnections.",
    explanation: "Interference from other devices, walls, and environmental factors affects Wi-Fi.",
    hint: "Your Wi-Fi slows down when too many devices are using it.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Why do networks require skilled staff?",
    shortAnswer: "Design, configuration, monitoring, and troubleshooting need specialised knowledge.",
    explanation: "Hiring and training network administrators adds to costs.",
    hint: "Not everyone can set up and maintain a complex network.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are the maintenance overheads in networking?",
    shortAnswer: "Regular updates, patches, hardware replacement, and backups.",
    explanation: "Ignoring maintenance leads to security vulnerabilities and failures.",
    hint: "Networks need constant care, like a car needs servicing.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How can network policy enforcement be a challenge?",
    shortAnswer: "Enforcing access controls, usage policies, and monitoring compliance is difficult.",
    explanation: "Users may violate policies, and managing permissions for many users is complex.",
    hint: "Making sure everyone follows the rules.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is vendor lock-in and why is it a disadvantage?",
    shortAnswer: "When an organisation becomes dependent on a single vendor, limiting flexibility and increasing costs.",
    explanation: "Switching to another vendor is expensive and difficult.",
    hint: "Being stuck with one brand for all your network gear.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does network security affect performance?",
    shortAnswer: "Security measures like encryption and deep packet inspection add overhead, slowing down traffic.",
    explanation: "There's a trade-off between security and speed.",
    hint: "More locks on a door make it slower to open.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the risk of using outdated network equipment?",
    shortAnswer: "It lacks security updates, may not support new protocols, and is prone to failure.",
    explanation: "Old equipment can become a security and performance liability.",
    hint: "Using an old, unsupported router is risky.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "Why is network documentation often neglected and what is the consequence?",
    shortAnswer: "Poor documentation makes troubleshooting and planning difficult, leading to longer outages.",
    explanation: "Without a clear network map, identifying problems takes much longer.",
    hint: "Trying to fix something without a diagram.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the impact of network congestion on user experience?",
    shortAnswer: "It causes slow page loads, buffering, and dropped connections.",
    explanation: "Congestion is like a traffic jam – everything slows down.",
    hint: "Streaming a video that keeps pausing.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How can a single compromised device affect the entire network?",
    shortAnswer: "It can spread malware, launch attacks, or allow unauthorised access to other devices.",
    explanation: "Networks are only as secure as their weakest link.",
    hint: "One infected computer can infect many others.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What are the costs associated with network training?",
    shortAnswer: "Training staff to manage the network, and ongoing education to keep up with new technologies.",
    explanation: "This is a recurring cost that organisations must budget for.",
    hint: "Certifications and courses for network professionals.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "Why is network redundancy not always implemented?",
    shortAnswer: "It adds significant cost and complexity.",
    explanation: "Not all organisations can afford duplicate hardware and links.",
    hint: "Having two of everything is expensive.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does network failure affect a business's reputation?",
    shortAnswer: "Frequent outages erode customer trust and can lead to loss of business.",
    explanation: "Customers expect reliability; downtime damages the brand.",
    hint: "A bank that's often offline loses customers.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the challenge of scaling a network securely?",
    shortAnswer: "Adding new users and devices increases the attack surface and management overhead.",
    explanation: "Security must grow along with the network, which is complex.",
    hint: "More doors to lock means more keys to manage.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How can a network become a vector for data leakage?",
    shortAnswer: "If security is weak, sensitive data can be intercepted or exfiltrated.",
    explanation: "Data in transit is vulnerable to eavesdropping.",
    hint: "Sending unencrypted passwords over the network.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the impact of network misconfiguration?",
    shortAnswer: "It can cause security holes, performance issues, or total outages.",
    explanation: "A single misconfigured ACL or routing entry can break connectivity.",
    hint: "Typing the wrong IP address in a router can block traffic.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does network complexity affect disaster recovery?",
    shortAnswer: "Complex networks are harder to restore after a failure, increasing recovery time.",
    explanation: "The more intricate the network, the more things that can go wrong during recovery.",
    hint: "Untangling a complex web takes time.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the risk of relying on a single internet service provider (ISP)?",
    shortAnswer: "If the ISP has an outage, the entire network loses external connectivity.",
    explanation: "Dual-homing (multiple ISPs) is a solution but adds cost.",
    hint: "Your internet is down because your ISP is down.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does network monitoring become a disadvantage if not done properly?",
    shortAnswer: "Excessive monitoring can be resource-intensive and generate false alarms, leading to alert fatigue.",
    explanation: "Too many alerts can cause staff to ignore critical ones.",
    hint: "The boy who cried wolf – too many alerts, no one pays attention.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the challenge of integrating legacy systems into a modern network?",
    shortAnswer: "Legacy devices may not support modern protocols or security standards.",
    explanation: "Compatibility issues require additional workarounds or upgrades.",
    hint: "Old machines speaking old languages.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How can network sprawl become a problem?",
    shortAnswer: "When networks grow organically without planning, they become unmanageable and insecure.",
    explanation: "Uncontrolled growth leads to duplicate equipment, obscure connections, and difficulty in troubleshooting.",
    hint: "A city that grew without urban planning – chaotic.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the disadvantage of using unmanaged network devices?",
    shortAnswer: "Lack of visibility and control makes troubleshooting and security difficult.",
    explanation: "Unmanaged switches and APs don't provide monitoring or configuration options.",
    hint: "A black box – you can't see what's happening inside.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does network downtime affect financial transactions?",
    shortAnswer: "It can halt payment processing, leading to lost sales and frustrated customers.",
    explanation: "E-commerce sites lose revenue for every minute of downtime.",
    hint: "A checkout page that won't load.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are the risks of using open Wi-Fi networks in a corporate environment?",
    shortAnswer: "They expose data to interception and are vulnerable to man-in-the-middle attacks.",
    explanation: "Open Wi-Fi has no encryption or authentication, making it highly insecure.",
    hint: "Anyone can listen in on the traffic.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;