const questions = [
  {
    question: "What is tree topology?",
    shortAnswer: "A hierarchical network topology combining bus and star, with a root node at the top.",
    explanation: "It has a root, intermediate nodes, and leaf nodes, forming a tree-like structure.",
    hint: "Think of an inverted tree with branches.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are the three levels in a tree topology?",
    shortAnswer: "Root (top), intermediate (branches), and leaf (end devices).",
    explanation: "The root connects to intermediate nodes, which connect to leaf devices.",
    hint: "Top, middle, bottom.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the role of the root node in tree topology?",
    shortAnswer: "The root is the central hub that connects all branches and manages traffic.",
    explanation: "It is the top-level device, often a core switch or router.",
    hint: "The top of the hierarchy.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does data travel between two leaf nodes on different branches?",
    shortAnswer: "Data goes up to the root and then down to the other branch.",
    explanation: "The root forwards traffic between branches.",
    hint: "Up to the top, then down.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the advantage of tree topology?",
    shortAnswer: "Scalable and easy to manage due to hierarchical structure.",
    explanation: "Adding new branches is easy without affecting existing nodes.",
    hint: "Grows like a tree.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the disadvantage of tree topology?",
    shortAnswer: "The root is a single point of failure.",
    explanation: "If the root fails, the entire network goes down.",
    hint: "All eggs in one basket.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the difference between tree and star topology?",
    shortAnswer: "Tree has multiple levels (hierarchy); star has only one level.",
    explanation: "Star is a flat topology; tree is hierarchical.",
    hint: "One is a single star; the other is a star of stars.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the difference between tree and bus topology?",
    shortAnswer: "Tree has hierarchy; bus is a single shared line.",
    explanation: "Tree uses multiple branches; bus is linear.",
    hint: "One is hierarchical; the other is linear.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What type of cable is typically used for the backbone in tree topology?",
    shortAnswer: "Fiber optic cable for high speed and long distances.",
    explanation: "The backbone needs high capacity to handle aggregate traffic.",
    hint: "Fast and long.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Can tree topology be combined with other topologies?",
    shortAnswer: "Yes, tree is itself a hybrid of bus and star.",
    explanation: "It can also be part of a larger hybrid network.",
    hint: "Hybrid nature.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a VLAN and how does it relate to tree topology?",
    shortAnswer: "VLANs logically segment a physical tree network for security and performance.",
    explanation: "Different branches can be on different VLANs.",
    hint: "Logical segmentation.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do you add a new branch to a tree topology?",
    shortAnswer: "Connect a new switch/router to an existing node at the appropriate level.",
    explanation: "The new branch becomes a subtree of the parent node.",
    hint: "Graft a new branch.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What happens if an intermediate node fails in tree topology?",
    shortAnswer: "Its entire subtree becomes isolated from the rest.",
    explanation: "The nodes below that node cannot communicate above it.",
    hint: "The branch is cut off.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How can you make the root fault-tolerant?",
    shortAnswer: "Use redundant root switches with failover (e.g., VRRP, HSRP).",
    explanation: "Two roots with automatic failover provide high availability.",
    hint: "A backup root.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the impact of adding many levels to a tree topology?",
    shortAnswer: "Latency increases because data travels through more hops.",
    explanation: "More levels mean more intermediate nodes.",
    hint: "More levels = more hops.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the typical use case for tree topology?",
    shortAnswer: "Large campus networks, enterprise buildings, and university networks.",
    explanation: "Any network that needs hierarchical structure and scalability.",
    hint: "Big organisations.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of a core switch in tree topology?",
    shortAnswer: "The core switch is typically the root, handling traffic between branches.",
    explanation: "It aggregates traffic and forwards between different parts of the network.",
    hint: "The central hub.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of a distribution switch in tree topology?",
    shortAnswer: "A distribution switch connects multiple access switches to the core.",
    explanation: "It acts as an intermediate node between access and core.",
    hint: "Middle management.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of an access switch in tree topology?",
    shortAnswer: "An access switch connects end devices (PCs, printers) to the network.",
    explanation: "It is a leaf node in the hierarchy.",
    hint: "The entry point.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the three-tier hierarchical model in networking?",
    shortAnswer: "Core, distribution, and access layers – a structured design for large networks.",
    explanation: "This is essentially tree topology applied to enterprise networking.",
    hint: "A well-known design pattern.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the disadvantage of using a single root in tree topology?",
    shortAnswer: "Single point of failure; if the root fails, the network goes down.",
    explanation: "Redundancy (dual root) is needed for high availability.",
    hint: "No backup.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does STP (Spanning Tree Protocol) interact with tree topology?",
    shortAnswer: "STP prevents loops when there are redundant links in a tree.",
    explanation: "Redundant links can create loops; STP blocks some links.",
    hint: "Prevents loops.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the impact of network congestion on the backbone in tree topology?",
    shortAnswer: "Congestion on the backbone affects all branches.",
    explanation: "The backbone is a shared resource; congestion slows everything.",
    hint: "The main road is jammed.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the concept of 'distance vector' vs 'link state' routing in a tree?",
    shortAnswer: "Distance vector uses hop count; link state uses a map of the network.",
    explanation: "Link state (OSPF) is more efficient in hierarchical networks.",
    hint: "RIP vs OSPF.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does a tree topology support quality of service (QoS)?",
    shortAnswer: "QoS can be implemented at each level to prioritize traffic.",
    explanation: "The core and distribution layers can enforce QoS policies.",
    hint: "Priority handling.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the difference between a tree and a spine-leaf architecture?",
    shortAnswer: "Spine-leaf is a type of partial mesh, not a tree; tree is hierarchical with a root.",
    explanation: "Spine-leaf provides more redundancy and lower latency.",
    hint: "Mesh vs. tree.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do you design a tree topology for a multi-building campus?",
    shortAnswer: "Place the root in the main data center, connect each building via fiber to the root.",
    explanation: "Each building has its own distribution and access layers.",
    hint: "Hierarchy by location.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of a firewall in tree topology?",
    shortAnswer: "A firewall is typically placed at the root to protect the entire network.",
    explanation: "It filters traffic entering and leaving the network.",
    hint: "Security at the root.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the impact of cable length on tree topology?",
    shortAnswer: "Cable length limits the distance between nodes, especially at lower levels.",
    explanation: "Fiber is used for longer distances between buildings.",
    hint: "Distance matters.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does network virtualization affect tree topology?",
    shortAnswer: "Virtualization allows multiple logical trees on the same physical infrastructure.",
    explanation: "VLANs and overlay networks provide flexibility.",
    hint: "Logical vs. physical.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the future of tree topology with SDN?",
    shortAnswer: "SDN makes tree topology more dynamic and programmable.",
    explanation: "Centralized control allows easier management and scaling.",
    hint: "Software-defined trees.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;