const questions = [
  {
    question: "What is a client-server network?",
    shortAnswer: "A network architecture where dedicated servers provide services to clients.",
    explanation: "Clients request services (like web pages, emails), and servers fulfill those requests.",
    hint: "Think of a restaurant – you're the client, the kitchen is the server.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are the two main roles in client-server?",
    shortAnswer: "Client (requesting services) and Server (providing services).",
    explanation: "Clients are typically end-user devices; servers are powerful machines dedicated to serving.",
    hint: "One asks, the other answers.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Give an example of a client-server application.",
    shortAnswer: "Web browsing – browser is the client, web server is the server.",
    explanation: "The browser requests HTML pages, and the server responds.",
    hint: "How do you visit a website?",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a web server?",
    shortAnswer: "A server that stores and delivers web pages to clients (browsers).",
    explanation: "Web servers use HTTP/HTTPS to communicate with browsers.",
    hint: "Apache or Nginx.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a database server?",
    shortAnswer: "A server that manages structured data and handles queries from clients.",
    explanation: "Clients (applications) send SQL queries to retrieve or update data.",
    hint: "MySQL, PostgreSQL.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the main advantage of client-server over P2P?",
    shortAnswer: "Centralized management and security.",
    explanation: "Servers provide controlled access, backups, and easier policy enforcement.",
    hint: "One place to manage everything.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a disadvantage of client-server?",
    shortAnswer: "Single point of failure – if the server goes down, all clients are affected.",
    explanation: "Redundancy (backup servers) is needed to mitigate this.",
    hint: "All eggs in one basket.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a thin client?",
    shortAnswer: "A client that depends heavily on the server, with minimal local processing.",
    explanation: "Thin clients are often used in virtual desktop infrastructures.",
    hint: "A lightweight terminal.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a thick (fat) client?",
    shortAnswer: "A client that performs significant local processing, not just displaying data.",
    explanation: "Thick clients run applications locally, only occasionally using the server.",
    hint: "A full-featured application.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does a client discover the server's address?",
    shortAnswer: "Often via DNS (Domain Name System) or static configuration.",
    explanation: "DNS resolves domain names to IP addresses.",
    hint: "How does your browser find the server?",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the role of a load balancer in client-server?",
    shortAnswer: "Load balancers distribute client requests across multiple servers to avoid overload.",
    explanation: "Improves performance and redundancy.",
    hint: "Traffic cop for servers.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is an application server?",
    shortAnswer: "A server that hosts business logic and applications for clients.",
    explanation: "Application servers execute code and interact with databases.",
    hint: "Tomcat, JBoss.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between a web server and an application server?",
    shortAnswer: "Web server serves static content; application server executes dynamic logic.",
    explanation: "Often combined (e.g., Node.js can do both), but they have distinct roles.",
    hint: "Static vs. dynamic.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does client-server handle authentication?",
    shortAnswer: "Using sessions, tokens (JWT), or LDAP/Active Directory.",
    explanation: "Clients authenticate once, and the server manages identity for subsequent requests.",
    hint: "Login to access resources.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the impact of network latency on client-server?",
    shortAnswer: "High latency increases response time, degrading user experience.",
    explanation: "Mitigated by caching, CDNs, and optimizing protocols.",
    hint: "Slow network = slow app.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a mail server and its protocols?",
    shortAnswer: "A mail server handles sending and receiving emails using SMTP, IMAP, or POP3.",
    explanation: "Clients use these protocols to access their email.",
    hint: "Gmail uses mail servers.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a file server?",
    shortAnswer: "A server that stores and shares files over the network (SMB, NFS).",
    explanation: "Clients can map network drives or access shared folders.",
    hint: "Shared network drive.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do you secure client-server communication?",
    shortAnswer: "Use HTTPS (SSL/TLS) for web, IPsec for VPNs, and SSH for remote access.",
    explanation: "Encryption protects data in transit.",
    hint: "Lock the data while it travels.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of a DNS server?",
    shortAnswer: "DNS servers translate domain names (e.g., google.com) to IP addresses.",
    explanation: "Clients query DNS to find the server's IP.",
    hint: "Phonebook of the internet.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is server clustering?",
    shortAnswer: "Grouping multiple servers to appear as one, for high availability and load balancing.",
    explanation: "If one server fails, others take over.",
    hint: "Multiple servers acting as one.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between stateful and stateless servers?",
    shortAnswer: "Stateful servers remember client state (sessions); stateless servers don't.",
    explanation: "Stateless is more scalable (RESTful APIs).",
    hint: "Remembering vs. forgetting.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does a server handle thousands of concurrent clients?",
    shortAnswer: "Through multithreading, event-driven architecture, and connection pooling.",
    explanation: "Servers use efficient I/O models (e.g., epoll, kqueue).",
    hint: "Handling many at once.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is a reverse proxy and its benefits?",
    shortAnswer: "A reverse proxy sits in front of servers, handling requests, caching, and load balancing.",
    explanation: "Improves security, performance, and scalability.",
    hint: "Front door to the server.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the CAP theorem and how does it relate to client-server?",
    shortAnswer: "CAP theorem states that distributed systems cannot simultaneously provide Consistency, Availability, and Partition tolerance.",
    explanation: "Client-server architectures must make trade-offs.",
    hint: "Choose two of three.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do you scale a client-server application?",
    shortAnswer: "Vertical scaling (bigger server) or horizontal scaling (more servers).",
    explanation: "Horizontal scaling is more common with microservices.",
    hint: "Upgrade vs. add more.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is a Service-Oriented Architecture (SOA)?",
    shortAnswer: "An architectural approach where applications are composed of loosely coupled services.",
    explanation: "Services are provided by servers and consumed by clients.",
    hint: "Microservices predecessor.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of middleware in client-server?",
    shortAnswer: "Middleware facilitates communication between clients and servers, often in distributed systems.",
    explanation: "Examples: message queues (RabbitMQ), RPC frameworks (gRPC).",
    hint: "Glue between client and server.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does caching improve client-server performance?",
    shortAnswer: "Caches store frequently accessed data closer to the client, reducing server load and latency.",
    explanation: "CDNs, Redis, browser caching.",
    hint: "Remembering recent requests.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are the security challenges of client-server?",
    shortAnswer: "Server attacks (DDoS, SQL injection), man-in-the-middle, and data breaches.",
    explanation: "Security requires defense-in-depth: firewalls, encryption, monitoring.",
    hint: "Hackers target servers.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the future of client-server with cloud computing?",
    shortAnswer: "Client-server is evolving to cloud-native, with microservices, serverless, and edge computing.",
    explanation: "The model persists but with more abstraction and distribution.",
    hint: "Servers are now in the cloud.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;