// topic3_files/topic3_questions_linux.js
const questions = [
    {
        question: "What is the root directory in Linux?",
        shortAnswer: "The top-level directory denoted by '/'.",
        explanation: "All files and directories in Linux are organized under the root directory (/). It is the starting point of the filesystem hierarchy.",
        hint: "Think of it as 'C:\\' on Windows but forward slash.",
        level: "basic",
        codeExample: "cd /\nls -l"
    },
    {
        question: "What is the purpose of the /bin directory?",
        shortAnswer: "Contains essential user command binaries (executables) needed in single-user mode.",
        explanation: "/bin holds common commands like ls, cp, mv, cat, echo that are available to all users. It is part of the root filesystem and must be present for basic system operation.",
        hint: "Stands for 'binaries'.",
        level: "basic",
        codeExample: "ls /bin\nwhich ls"
    },
    {
        question: "How is /sbin different from /bin?",
        shortAnswer: "/sbin contains system administration binaries (usually for root), while /bin is for general user commands.",
        explanation: "Commands in /sbin like fdisk, mkfs, iptables are intended for system maintenance and typically require superuser privileges.",
        hint: "'s' stands for 'system' or 'superuser'.",
        level: "basic",
        codeExample: "ls /sbin\nsudo fdisk -l"
    },
    {
        question: "What does the /etc directory store?",
        shortAnswer: "Host-specific system configuration files.",
        explanation: "/etc contains configuration files for system services, applications, and network settings. Examples: /etc/passwd, /etc/fstab, /etc/hostname.",
        hint: "Originally 'et cetera', now means configuration.",
        level: "basic",
        codeExample: "ls /etc\ncat /etc/hostname"
    },
    {
        question: "What is the purpose of the /var directory?",
        shortAnswer: "Stores variable data like logs, spool files, temporary email, and cache.",
        explanation: "/var contains files that change in size and content during normal system operation – logs (/var/log), mail spools (/var/spool/mail), print queues, etc.",
        hint: "'var' stands for variable.",
        level: "basic",
        codeExample: "ls /var\nls /var/log"
    },
    {
        question: "Where are user home directories typically located?",
        shortAnswer: "Under /home/username.",
        explanation: "Each regular user gets a personal directory under /home, e.g., /home/alice. The root user's home is /root (not under /home).",
        hint: "Use ~ as shortcut for your home.",
        level: "basic",
        codeExample: "cd ~\npwd\nls /home"
    },
    {
        question: "What is special about the /root directory?",
        shortAnswer: "The home directory of the root (superuser) user.",
        explanation: "/root is separate from /home for security reasons. It is not accessible to regular users without sudo.",
        hint: "Root's home is not under /home.",
        level: "basic",
        codeExample: "sudo ls /root"
    },
    {
        question: "What is the purpose of /tmp?",
        shortAnswer: "Temporary files storage, cleared on reboot.",
        explanation: "All users can write to /tmp. Files are usually deleted on system restart. For persistent temporary files, use /var/tmp.",
        hint: "Short-lived data.",
        level: "basic",
        codeExample: "ls /tmp\necho 'test' > /tmp/myfile.txt"
    },
    {
        question: "What does the /dev directory contain?",
        shortAnswer: "Device files representing hardware components.",
        explanation: "/dev includes special files for hard disks (/dev/sda), terminals, random number generator (/dev/random), null device (/dev/null), etc. These are used to interact with hardware.",
        hint: "Stands for 'devices'.",
        level: "intermediate",
        codeExample: "ls /dev\nls /dev/sd*"
    },
    {
        question: "What is the /proc directory?",
        shortAnswer: "A virtual filesystem providing process and kernel information as files.",
        explanation: "/proc contains runtime system information (memory, CPU, processes). Files like /proc/cpuinfo, /proc/meminfo are not real files but are generated by the kernel on the fly.",
        hint: "Think of it as a window into the kernel.",
        level: "intermediate",
        codeExample: "cat /proc/cpuinfo\ncat /proc/meminfo"
    },
    {
        question: "What is the purpose of /usr directory?",
        shortAnswer: "Secondary hierarchy for user data and application files.",
        explanation: "/usr contains most user utilities and applications, including binaries (/usr/bin), libraries (/usr/lib), documentation (/usr/share/doc), and source code (/usr/src).",
        hint: "Stands for 'Unix System Resources' or 'user'.",
        level: "basic",
        codeExample: "ls /usr\nls /usr/bin"
    },
    {
        question: "How is /usr/bin different from /bin?",
        shortAnswer: "/bin is for essential binaries needed in single-user mode; /usr/bin is for non-essential user commands.",
        explanation: "Historically, /bin was on the root partition, /usr/bin on a separate partition. Modern Linux often merges them, but the distinction remains conceptually.",
        hint: "/bin is minimal; /usr/bin is everything else.",
        level: "intermediate",
        codeExample: "ls /bin /usr/bin | head"
    },
    {
        question: "What is the role of /boot directory?",
        shortAnswer: "Contains files needed for booting the system: kernel, initrd/initramfs, bootloader config.",
        explanation: "/boot holds the Linux kernel (vmlinuz), initial RAM disk (initrd.img), and GRUB configuration. It is often a separate partition.",
        hint: "Bootloader reads from here.",
        level: "basic",
        codeExample: "ls /boot\nfile /boot/vmlinuz-*"
    },
    {
        question: "What does /lib directory store?",
        shortAnswer: "Shared libraries and kernel modules needed by /bin and /sbin.",
        explanation: "/lib contains essential libraries (like libc.so) and kernel modules (/lib/modules). 64-bit systems may also have /lib64.",
        hint: "Libraries for essential binaries.",
        level: "intermediate",
        codeExample: "ls /lib\nldd /bin/ls"
    },
    {
        question: "What is the purpose of /opt?",
        shortAnswer: "Optional add-on application software packages.",
        explanation: "/opt is used for installing third-party or self-contained software (e.g., /opt/google/chrome). Each package gets its own subdirectory.",
        hint: "Stands for 'optional'.",
        level: "basic",
        codeExample: "ls /opt\nsudo ls /opt"
    },
    {
        question: "What is the /mnt directory for?",
        shortAnswer: "Temporary mount point for filesystems.",
        explanation: "System administrators can manually mount temporary filesystems (USB drives, network shares) under /mnt. Modern systems often use /media for removable media.",
        hint: "Mount temporary stuff here.",
        level: "basic",
        codeExample: "sudo mount /dev/sdb1 /mnt\nls /mnt"
    },
    {
        question: "What is the difference between /mnt and /media?",
        shortAnswer: "/mnt is for manual temporary mounts; /media is for auto-mounted removable media.",
        explanation: "/media is used by desktop environments to automatically mount USB drives, CDs, etc. /mnt is for administrator-controlled temporary mounts.",
        hint: "/media is more automated.",
        level: "intermediate",
        codeExample: "ls /media /mnt"
    },
    {
        question: "What is the lost+found directory?",
        shortAnswer: "Stores recovered file fragments after a filesystem check (fsck).",
        explanation: "If the system crashes and fsck recovers orphaned files, they are placed in lost+found. Each filesystem partition (e.g., /, /home) has its own lost+found.",
        hint: "Recovery area for damaged files.",
        level: "expert",
        codeExample: "ls -l /lost+found\nsudo ls /home/lost+found"
    },
    {
        question: "What is the /srv directory?",
        shortAnswer: "Site-specific data served by the system (e.g., web server content, FTP data).",
        explanation: "/srv holds data for services like HTTP (/srv/www), FTP, or version control repositories. It's not used by all distributions.",
        hint: "Stands for 'service' data.",
        level: "intermediate",
        codeExample: "ls /srv\ncd /srv/www"
    },
    {
        question: "What does the /run directory contain?",
        shortAnswer: "Runtime variable data for system processes since last boot.",
        explanation: "/run stores volatile runtime data like process IDs (PID files), lock files, and socket files. It is mounted as tmpfs (in RAM) and cleared on reboot.",
        hint: "Temporary but more structured than /tmp.",
        level: "expert",
        codeExample: "ls /run\nls /run/user"
    },
    {
        question: "What is the /sys directory?",
        shortAnswer: "Virtual filesystem exposing kernel and device information (similar to /proc but more structured).",
        explanation: "/sys provides a view of kernel objects, devices, drivers, and power management features. Used by tools like udev.",
        hint: "System device tree.",
        level: "expert",
        codeExample: "ls /sys/class/net/\ncat /sys/class/net/eth0/address"
    },
    {
        question: "What is an absolute path?",
        shortAnswer: "A path starting from the root directory (/), e.g., /home/user/file.txt.",
        explanation: "Absolute paths always begin with '/' and specify the complete location regardless of current working directory.",
        hint: "Starts with slash.",
        level: "basic",
        codeExample: "ls /var/log/syslog\ncd /usr/local/bin"
    },
    {
        question: "What is a relative path?",
        shortAnswer: "A path relative to the current working directory (no leading '/').",
        explanation: "Uses . (current) and .. (parent). Example: docs/report.pdf or ../src.",
        hint: "No leading slash.",
        level: "basic",
        codeExample: "cd /home\ncd user/Documents  # relative from /home\nls ../Downloads"
    },
    {
        question: "How do you view hidden files in a directory?",
        shortAnswer: "Use 'ls -a' or 'ls -A'.",
        explanation: "Hidden files start with a dot (e.g., .bashrc). 'ls -a' shows '.' and '..' as well; 'ls -A' excludes them.",
        hint: "Dot files are hidden.",
        level: "basic",
        codeExample: "ls -a ~\nls -A /etc"
    },
    {
        question: "What is the purpose of the /etc/passwd file?",
        shortAnswer: "Stores user account information (username, UID, GID, home directory, shell).",
        explanation: "Each line represents a user. Passwords are now usually stored in /etc/shadow. Format: username:password:UID:GID:comment:home:shell.",
        hint: "User database, but no real passwords.",
        level: "intermediate",
        codeExample: "cat /etc/passwd\ngetent passwd"
    },
    {
        question: "What does /etc/fstab control?",
        shortAnswer: "Filesystem table – defines how and where partitions are mounted at boot.",
        explanation: "fstab entries specify device, mount point, filesystem type, mount options, dump and fsck order.",
        hint: "File system table.",
        level: "intermediate",
        codeExample: "cat /etc/fstab\nman fstab"
    },
    {
        question: "What is the /etc/hosts file used for?",
        shortAnswer: "Static mapping between hostnames and IP addresses.",
        explanation: "Overrides DNS for local resolution. Useful for blocking sites or local development.",
        hint: "Local DNS replacement.",
        level: "basic",
        codeExample: "cat /etc/hosts\necho '127.0.0.1 mydev' | sudo tee -a /etc/hosts"
    },
    {
        question: "Where is the system hostname stored?",
        shortAnswer: "/etc/hostname (on most distributions).",
        explanation: "This file contains a single line with the system's hostname. The hostname command reads it at boot.",
        hint: "Also 'hostnamectl' on systemd.",
        level: "basic",
        codeExample: "cat /etc/hostname\nhostname"
    },
    {
        question: "What is the /proc/cpuinfo file?",
        shortAnswer: "Virtual file showing CPU details (model, cores, flags).",
        explanation: "Read-only. Displays information about each processor core.",
        hint: "Check CPU specs.",
        level: "intermediate",
        codeExample: "cat /proc/cpuinfo\nlscpu"
    },
    {
        question: "How to get memory info from /proc?",
        shortAnswer: "cat /proc/meminfo",
        explanation: "Shows total, free, available RAM, swap, buffers, cache.",
        hint: "Also 'free -h'.",
        level: "intermediate",
        codeExample: "cat /proc/meminfo\nfree -m"
    },
    {
        question: "What is the /dev/null device?",
        shortAnswer: "A special device that discards all data written to it and returns EOF on read.",
        explanation: "Often used to suppress output: command > /dev/null 2>&1. Reading from it returns end-of-file immediately.",
        hint: "Black hole of data.",
        level: "basic",
        codeExample: "echo 'hello' > /dev/null\ncat /dev/null"
    },
    {
        question: "What does /dev/zero do?",
        shortAnswer: "Provides as many null bytes (\\0) as read.",
        explanation: "Reading from /dev/zero returns infinite null characters. Useful for creating blank files or wiping data.",
        hint: "Null byte generator.",
        level: "expert",
        codeExample: "dd if=/dev/zero of=blank.img bs=1M count=10"
    },
    {
        question: "What is the difference between /dev/random and /dev/urandom?",
        shortAnswer: "/dev/random blocks when entropy pool is empty; /dev/urandom does not.",
        explanation: "Both generate random numbers. /dev/random is more secure but can block. /dev/urandom is non-blocking and sufficient for most uses.",
        hint: "'u' stands for unlimited (non-blocking).",
        level: "expert",
        codeExample: "head -c 10 /dev/urandom | hexdump"
    },
    {
        question: "What is the purpose of /usr/local?",
        shortAnswer: "For locally compiled or manually installed software not managed by package manager.",
        explanation: "/usr/local/bin, /usr/local/lib, etc., are used for system-wide custom installations, keeping them separate from distribution packages.",
        hint: "Local admin software.",
        level: "intermediate",
        codeExample: "ls /usr/local\nwhich /usr/local/bin/mycustomapp"
    },
    {
        question: "What does /usr/share contain?",
        shortAnswer: "Architecture-independent shared data (icons, fonts, documentation, man pages).",
        explanation: "Files here are not specific to CPU architecture, like /usr/share/man, /usr/share/doc, /usr/share/games.",
        hint: "Shared read-only data.",
        level: "intermediate",
        codeExample: "ls /usr/share\nls /usr/share/man"
    },
    {
        question: "Where are system log files stored?",
        shortAnswer: "Typically in /var/log.",
        explanation: "Logs like syslog, auth.log, dmesg, kernel.log are under /var/log. Systemd-based systems use journald but also write to /var/log.",
        hint: "Check /var/log.",
        level: "basic",
        codeExample: "ls /var/log\ntail -f /var/log/syslog"
    },
    {
        question: "What is /var/tmp used for?",
        shortAnswer: "Temporary files that persist across reboots.",
        explanation: "Unlike /tmp, files in /var/tmp are not automatically cleared on reboot. Used for larger or longer-term temporary data.",
        hint: "Persistent temporary.",
        level: "intermediate",
        codeExample: "ls /var/tmp\nfind /var/tmp -type f -mtime +7"
    },
    {
        question: "What is the purpose of /var/spool?",
        shortAnswer: "Holds data queued for processing (print jobs, mail, cron).",
        explanation: "Subdirectories: /var/spool/cron, /var/spool/mail, /var/spool/lpd. Spooled tasks wait to be handled by daemons.",
        hint: "Queued tasks.",
        level: "expert",
        codeExample: "ls /var/spool\nmailq"
    },
    {
        question: "What is the difference between a hard link and a symbolic link?",
        shortAnswer: "Hard link is another directory entry pointing to same inode; symlink is a special file containing a path.",
        explanation: "Hard links cannot cross filesystems or link to directories. Symlinks can point anywhere and can be broken.",
        hint: "ln vs ln -s.",
        level: "intermediate",
        codeExample: "ln file.txt hardlink\nln -s file.txt symlink\nls -li"
    },
    {
        question: "How do you create a symbolic link to a directory?",
        shortAnswer: "Use ln -s target link_name.",
        explanation: "Symlinks can point to directories; use -s option. Example: ln -s /var/log mylog.",
        hint: "Symbolic link = shortcut.",
        level: "basic",
        codeExample: "ln -s /etc myetc\nls -l myetc"
    },
    {
        question: "What is the sticky bit on a directory?",
        shortAnswer: "Restricts deletion: only file owner, directory owner, or root can delete files inside.",
        explanation: "Common on /tmp. Symbolized by 't' in permissions (e.g., drwxrwxrwt).",
        hint: "Sticky prevents others from deleting your files.",
        level: "expert",
        codeExample: "ls -ld /tmp\nchmod +t shared_dir"
    },
    {
        question: "What is the setuid bit?",
        shortAnswer: "Allows a program to run with the permissions of its owner (usually root) instead of the user running it.",
        explanation: "Set on executables (e.g., /bin/passwd). Represented by 's' in owner execute field.",
        hint: "Elevates privileges temporarily.",
        level: "expert",
        codeExample: "ls -l /bin/su\nchmod u+s myprog"
    },
    {
        question: "What command shows disk usage of directories?",
        shortAnswer: "du (disk usage).",
        explanation: "du -sh * shows summary for each item. du -h /home shows total for home.",
        hint: "du vs df.",
        level: "basic",
        codeExample: "du -sh /var\ndu -h --max-depth=1"
    },
    {
        question: "What command shows available disk space on mounted filesystems?",
        shortAnswer: "df -h",
        explanation: "df reports used and available space on all mounted partitions. -h for human-readable sizes.",
        hint: "Disk free.",
        level: "basic",
        codeExample: "df -h\ndf -i  # inode usage"
    },
    {
        question: "What is the purpose of the /etc/skel directory?",
        shortAnswer: "Skeleton directory containing default files copied to a new user's home directory.",
        explanation: "When a user is created, files from /etc/skel (e.g., .bashrc, .profile) are copied to the new home.",
        hint: "Template for new homes.",
        level: "expert",
        codeExample: "ls -la /etc/skel\nuseradd -m newuser"
    },
    {
        question: "What is the difference between .bashrc and .bash_profile?",
        shortAnswer: ".bashrc runs for interactive non-login shells; .bash_profile runs for login shells.",
        explanation: ".bash_profile is read at login (e.g., SSH). .bashrc is read for each new terminal. Many setups source .bashrc from .bash_profile.",
        hint: "Login vs interactive.",
        level: "intermediate",
        codeExample: "cat ~/.bashrc\ncat ~/.bash_profile"
    },
    {
        question: "How do you find all files owned by a specific user?",
        shortAnswer: "find / -user username 2>/dev/null",
        explanation: "The find command with -user option. Redirect stderr to suppress permission errors.",
        hint: "Use find -user.",
        level: "intermediate",
        codeExample: "find /home -user alice\nfind / -user root -name '*.conf'"
    },
    {
        question: "What is the purpose of the /lost+found directory?",
        shortAnswer: "Recovered file fragments after fsck.",
        explanation: "If the system crashes and fsck recovers orphaned files, they are placed in lost+found. Each filesystem partition has its own lost+found.",
        hint: "Filesystem recovery area.",
        level: "expert",
        codeExample: "sudo ls /lost+found\nsudo ls /home/lost+found"
    },
    {
        question: "What does the '..' directory entry represent?",
        shortAnswer: "The parent directory of the current directory.",
        explanation: "Each directory contains special entries: '.' for itself, '..' for parent. At root, '..' points to root.",
        hint: "Go up one level.",
        level: "basic",
        codeExample: "cd ..\npwd\nls -la"
    },
    {
        question: "What is the difference between /etc/init.d/ and /etc/systemd/system/?",
        shortAnswer: "/etc/init.d/ holds SysV init scripts; /etc/systemd/system/ holds systemd unit files.",
        explanation: "Modern Linux uses systemd with unit files. SysV init is legacy. Some systems support both for compatibility.",
        hint: "Systemd vs SysV init.",
        level: "expert",
        codeExample: "ls /etc/init.d\nls /etc/systemd/system"
    }
];

export default questions;