// File: src/components/topics/topic8_files/topic8_questions.js
const questions = [
  {
    question: "What is Stop‑and‑Wait flow control?",
    shortAnswer: "Sender transmits one frame, then waits for an ACK before sending the next.",
    explanation: "Only one frame is in the network at a time, which simplifies error recovery but limits throughput.",
    hint: "It's like a one‑way conversation with a pause after each sentence.",
    level: "basic",
  },
  {
    question: "What is the difference between transmission time and propagation delay?",
    shortAnswer: "Transmission time is the time to push bits onto the medium; propagation delay is the time for a bit to travel from sender to receiver.",
    explanation: "Transmission time depends on frame size and data rate; propagation delay depends on distance and speed of signal.",
    hint: "Transmission = pushing; propagation = travelling.",
    level: "basic",
  },
  {
    question: "What is the formula for efficiency of Stop‑and‑Wait?",
    shortAnswer: "Efficiency = Tt / (Tt + 2*Tp), where Tt is transmission time and Tp is one‑way propagation delay.",
    explanation: "The factor 2*Tp accounts for the round‑trip time of the frame and the ACK.",
    hint: "Only useful time over total time.",
    level: "moderate",
  },
  {
    question: "If Tt = 2 ms and Tp = 18 ms, what is the efficiency?",
    shortAnswer: "Efficiency = 2/(2+36) = 2/38 ≈ 5.26%.",
    explanation: "This shows very low utilization because the sender spends most of the time waiting for the ACK.",
    hint: "Plug into the formula and multiply by 100.",
    level: "moderate",
  },
  {
    question: "Why does Stop‑and‑Wait become inefficient on long‑distance links?",
    shortAnswer: "Because propagation delay increases, so the sender spends more time waiting for ACKs.",
    explanation: "The round‑trip time grows, so the ratio of useful transmission time to total time drops.",
    hint: "Longer distance → larger Tp → lower efficiency.",
    level: "basic",
  },
  {
    question: "What is the maximum possible efficiency of Stop‑and‑Wait?",
    shortAnswer: "100% when propagation delay is zero (Tp = 0).",
    explanation: "In practice, Tp is always >0, so efficiency is always less than 100%.",
    hint: "Only if the medium is infinitely fast.",
    level: "moderate",
  },
  {
    question: "How does increasing the frame size affect efficiency?",
    shortAnswer: "Increasing frame size increases Tt, which raises efficiency (since Tt/(Tt+2Tp) increases).",
    explanation: "Larger frames mean more useful data sent per round‑trip, improving channel utilization.",
    hint: "More bits per trip → better use of time.",
    level: "moderate",
  },
  {
    question: "How does increasing the data rate affect efficiency (for fixed frame size)?",
    shortAnswer: "Data rate increase reduces Tt, which lowers efficiency because the sender finishes sending faster and waits longer.",
    explanation: "Higher speed makes the waiting time proportionally larger, so efficiency drops.",
    hint: "Faster sending means more idle waiting.",
    level: "expert",
  },
  {
    question: "What is the round‑trip time (RTT) in the context of Stop‑and‑Wait?",
    shortAnswer: "RTT is the time from sending a frame until receiving its ACK. For Stop‑and‑Wait, RTT ≈ Tt + 2*Tp (ignoring ACK transmission).",
    explanation: "The sender cannot send a new frame until RTT has elapsed.",
    hint: "Total time per frame.",
    level: "moderate",
  },
  {
    question: "What is the bandwidth‑delay product and how does it relate to Stop‑and‑Wait?",
    shortAnswer: "Bandwidth‑delay product = data rate × RTT. It is the amount of data that can be 'in flight'. Stop‑and‑Wait keeps only one frame in flight, so the link is underutilized when this product is larger than the frame size.",
    explanation: "To fully utilize the link, you need to have enough frames in flight to fill the pipe.",
    hint: "The amount of data in the pipe.",
    level: "expert",
  },
  {
    question: "Why is Stop‑and‑Wait still used in some scenarios?",
    shortAnswer: "Because it is extremely simple and works well when frames are large and propagation delay is small (e.g., local networks).",
    explanation: "It requires minimal buffer and is easy to implement in hardware.",
    hint: "Simplicity has its place.",
    level: "moderate",
  },
  {
    question: "What is the effect of ACK transmission time on efficiency?",
    shortAnswer: "It adds to the total time, reducing efficiency further.",
    explanation: "The formula can be extended: Efficiency = Tt / (Tt + 2*Tp + Tack), where Tack is the ACK transmission time.",
    hint: "ACKs also take time to send.",
    level: "expert",
  },
  {
    question: "If Tt = 10 ms and Tp = 20 ms, what is the efficiency?",
    shortAnswer: "Efficiency = 10/(10+40) = 10/50 = 0.2 = 20%.",
    explanation: "Only 20% of the time is used for sending data.",
    hint: "Put numbers in the formula.",
    level: "moderate",
  },
  {
    question: "What is the minimum efficiency you can get (as Tp → ∞)?",
    shortAnswer: "Tends to 0% because the denominator grows infinitely large.",
    explanation: "As the link gets longer, the waiting time dominates.",
    hint: "Efficiency approaches zero.",
    level: "moderate",
  },
  {
    question: "What is the relationship between efficiency and throughput?",
    shortAnswer: "Throughput = efficiency × data rate. Low efficiency means low effective throughput.",
    explanation: "Even though the link speed is high, the actual useful data rate is limited by the efficiency.",
    hint: "Effective speed = efficiency × nominal speed.",
    level: "expert",
  },
  {
    question: "How would you improve the efficiency of a Stop‑and‑Wait link without changing the hardware?",
    shortAnswer: "Increase the frame size (Tt) to reduce the relative overhead of waiting.",
    explanation: "By sending larger frames, the sender spends more time transmitting per round‑trip, improving utilization.",
    hint: "Pack more data in each frame.",
    level: "moderate",
  },
  {
    question: "Why is Stop‑and‑Wait not used in high‑speed long‑distance networks?",
    shortAnswer: "Because its efficiency would be extremely low, wasting the high bandwidth.",
    explanation: "For high speeds, the frame transmission time is very small, making the waiting time dominate.",
    hint: "High speed means small Tt, so efficiency drops.",
    level: "basic",
  },
  {
    question: "What is a 'sliding window' and how does it solve the efficiency problem?",
    shortAnswer: "Sliding window allows multiple frames to be sent before waiting for ACKs, keeping the link busy.",
    explanation: "By having several frames in flight, the sender can continuously transmit, filling the bandwidth‑delay product.",
    hint: "Pipelining instead of stop‑and‑wait.",
    level: "moderate",
  },
  {
    question: "What is the optimal window size for a given link?",
    shortAnswer: "Window size should be at least the bandwidth‑delay product (in frames) to achieve 100% efficiency.",
    explanation: "You need enough outstanding frames to keep the pipe full; the ideal window = (data rate × RTT) / frame size.",
    hint: "Match window to the amount of data in flight.",
    level: "expert",
  },
  {
    question: "How does error probability affect the efficiency of Stop‑and‑Wait?",
    shortAnswer: "Errors cause retransmissions, increasing the average time per frame and lowering efficiency.",
    explanation: "If a frame is lost, the timer expires and the sender retransmits, adding extra waiting time.",
    hint: "Errors make it even worse.",
    level: "moderate",
  },
  {
    question: "What is the 'utilization' of a link in networking?",
    shortAnswer: "Utilization is the fraction of time the link is actually transmitting useful data (equivalent to efficiency).",
    explanation: "It is the same as efficiency for Stop‑and‑Wait.",
    hint: "Same concept.",
    level: "basic",
  },
  {
    question: "If a link has a data rate of 1 Mbps, frame size 1000 bits, and propagation delay 20 ms, what is the efficiency?",
    shortAnswer: "Tt = 1000/1e6 = 1 ms. Efficiency = 1/(1+40) = 1/41 ≈ 2.44%.",
    explanation: "Even though the link is fast, the propagation delay makes it very inefficient.",
    hint: "Calculate Tt first.",
    level: "expert",
  },
  {
    question: "What does the term 'idle time' mean in Stop‑and‑Wait?",
    shortAnswer: "Idle time is the time when the sender is waiting for an ACK and not transmitting.",
    explanation: "It is equal to the total time minus transmission time.",
    hint: "The opposite of busy time.",
    level: "basic",
  },
  {
    question: "How does the speed of light affect Stop‑and‑Wait efficiency?",
    shortAnswer: "The speed of light determines the minimum propagation delay; longer distances increase Tp, reducing efficiency.",
    explanation: "Because Tp = distance / speed of signal, larger distances imply larger Tp.",
    hint: "Physical limit.",
    level: "moderate",
  },
  {
    question: "What is the difference between throughput and goodput?",
    shortAnswer: "Throughput is the raw data rate; goodput is the rate of useful application data (excluding retransmissions and overhead).",
    explanation: "In Stop‑and‑Wait, goodput is even lower than throughput due to waiting and possible retransmissions.",
    hint: "Goodput = useful data / time.",
    level: "expert",
  },
  {
    question: "Why is Stop‑and‑Wait sometimes called 'send‑and‑wait'?",
    shortAnswer: "Because the sender alternates between sending and waiting for an acknowledgement.",
    explanation: "It's a descriptive name.",
    level: "basic",
  },
  {
    question: "If you increase the transmission time by using a lower data rate, does efficiency improve?",
    shortAnswer: "Yes, because Tt increases, so the ratio Tt/(Tt+2Tp) increases.",
    explanation: "Lower speed means longer transmission time per frame, which can improve efficiency (though throughput drops).",
    hint: "Slower but more efficient use of the link? Yes, in terms of percentage.",
    level: "expert",
  },
  {
    question: "What is the typical range of propagation delay in terrestrial networks?",
    shortAnswer: "A few microseconds for local networks to tens of milliseconds for transcontinental links.",
    explanation: "For example, a coast‑to‑coast link in the US may have Tp ≈ 20‑30 ms.",
    hint: "Varies with distance.",
    level: "moderate",
  },
  {
    question: "What is the typical range of propagation delay in satellite networks?",
    shortAnswer: "About 250‑300 ms for geostationary satellites.",
    explanation: "This high delay makes Stop‑and‑Wait extremely inefficient.",
    hint: "Geostationary orbit ≈ 36,000 km.",
    level: "basic",
  },
  {
    question: "What is the formula for throughput in Stop‑and‑Wait?",
    shortAnswer: "Throughput = frame size / (Tt + 2*Tp) (ignoring overhead).",
    explanation: "This is the rate at which frames are successfully delivered.",
    hint: "Data per total time per frame.",
    level: "moderate",
  },
  {
    question: "If you have a satellite link with Tp = 250 ms, what frame size would you need to achieve 50% efficiency with a data rate of 1 Mbps?",
    shortAnswer: "We need Tt/(Tt+500) = 0.5 → Tt = 500 ms. Frame size = Tt × data rate = 0.5 × 1e6 = 500,000 bits ≈ 62.5 KB.",
    explanation: "Very large frames are needed to make Stop‑and‑Wait efficient on satellite links.",
    hint: "Solve for Tt.",
    level: "expert",
  }
];

export default questions;