const questions = [
  {
    question: "What is network topology?",
    shortAnswer: "The arrangement of nodes and links in a computer network.",
    explanation: "Topology defines how devices are physically or logically connected.",
    hint: "Think of it as the blueprint of a network.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the difference between physical and logical topology?",
    shortAnswer: "Physical topology is the actual cabling; logical topology is how data flows.",
    explanation: "Physical is what you can see; logical is how data moves.",
    hint: "The physical layout vs. the data flow path.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is bus topology?",
    shortAnswer: "All devices share a single communication line (backbone).",
    explanation: "Simple and cheap but a break in the cable can bring down the network.",
    hint: "One line, many devices.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is star topology?",
    shortAnswer: "All devices connect to a central hub or switch.",
    explanation: "Most common topology; easy to manage but depends on the central device.",
    hint: "Like a star with a central point.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is ring topology?",
    shortAnswer: "Devices form a ring where each connects to two others.",
    explanation: "Data travels in one or both directions; dual rings provide fault tolerance.",
    hint: "A circle of devices.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is mesh topology?",
    shortAnswer: "Every device connects to every other device.",
    explanation: "Highly redundant but expensive; used in critical networks.",
    hint: "Fully connected.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is tree topology?",
    shortAnswer: "A hierarchical structure with a root node and branches.",
    explanation: "Combines bus and star; scalable but depends on the root.",
    hint: "Like a family tree.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is hybrid topology?",
    shortAnswer: "A combination of two or more topologies.",
    explanation: "Flexible and scalable but complex to design and manage.",
    hint: "A mix of different structures.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Which topology is most common in LANs?",
    shortAnswer: "Star topology is the most common.",
    explanation: "Easy to install, manage, and troubleshoot.",
    hint: "The one with a central switch.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the advantage of star topology?",
    shortAnswer: "Easy to add devices and isolate faults.",
    explanation: "If one device fails, others are unaffected.",
    hint: "Easy to manage.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the disadvantage of bus topology?",
    shortAnswer: "A single break in the cable can bring down the entire network.",
    explanation: "The backbone is a single point of failure.",
    hint: "One break, everyone down.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the advantage of mesh topology?",
    shortAnswer: "High redundancy and fault tolerance.",
    explanation: "Multiple paths ensure reliability.",
    hint: "No single point of failure.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the disadvantage of mesh topology?",
    shortAnswer: "Expensive due to many connections and cabling.",
    explanation: "Requires many cables and ports.",
    hint: "Costly to implement.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Can logical topology differ from physical topology?",
    shortAnswer: "Yes, they can be different.",
    explanation: "For example, a physical star can have a logical ring (Token Ring).",
    hint: "What you see vs. what data does.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a token in ring topology?",
    shortAnswer: "A special frame that circulates the ring, granting the right to transmit.",
    explanation: "Token Ring uses a token to control access.",
    hint: "A permission slip to send data.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of a hub in star topology?",
    shortAnswer: "A hub or switch centralizes connections and forwards traffic.",
    explanation: "All devices communicate through the central device.",
    hint: "The center of the star.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the impact of a switch failure in star topology?",
    shortAnswer: "The entire network goes down.",
    explanation: "The switch is a single point of failure.",
    hint: "No switch, no network.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between full mesh and partial mesh?",
    shortAnswer: "Full mesh connects every device to every other; partial mesh connects selectively.",
    explanation: "Partial mesh is cheaper and still provides redundancy.",
    hint: "All vs. some.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does tree topology combine bus and star?",
    shortAnswer: "A central root (like a bus) connects to hubs (like stars), forming a hierarchy.",
    explanation: "This creates a scalable and structured layout.",
    hint: "A hierarchical star.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the advantage of hybrid topology?",
    shortAnswer: "Flexibility to meet specific requirements.",
    explanation: "Can combine the strengths of different topologies.",
    hint: "Best of multiple worlds.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the disadvantage of hybrid topology?",
    shortAnswer: "Complexity in design and management.",
    explanation: "Requires careful planning and expertise.",
    hint: "More parts to manage.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is network resilience in the context of topology?",
    shortAnswer: "The ability of a network to continue operating during failures.",
    explanation: "Mesh topology offers the highest resilience.",
    hint: "Bouncing back from failure.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the impact of cable length on topology choice?",
    shortAnswer: "Bus and tree topologies have cable length limits; star has shorter individual cables.",
    explanation: "Ethernet has a 100m maximum per segment.",
    hint: "Distance matters.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is a VLAN and how does it affect logical topology?",
    shortAnswer: "A VLAN logically segments a physical network, changing the logical topology.",
    explanation: "VLANs allow multiple logical networks on one physical infrastructure.",
    hint: "Logical segmentation.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do you choose a topology for a data center?",
    shortAnswer: "Typically use spine-leaf (a type of mesh) for high performance and redundancy.",
    explanation: "Data centers require low latency and high availability.",
    hint: "Critical infrastructure needs the best.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of redundancy in topology design?",
    shortAnswer: "Redundancy provides backup paths to prevent network failure.",
    explanation: "Mesh and dual-ring topologies build in redundancy.",
    hint: "Backup plans.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does network topology affect performance?",
    shortAnswer: "Topology determines data paths, potential bottlenecks, and latency.",
    explanation: "A star with a high-capacity switch performs well; a bus may bottleneck.",
    hint: "The layout affects traffic flow.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the 'single point of failure' concept?",
    shortAnswer: "A component whose failure causes the entire network to fail.",
    explanation: "Examples: central switch in star, root in tree, backbone in bus.",
    hint: "A weak link.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does the cost of cabling vary by topology?",
    shortAnswer: "Mesh requires the most cabling; bus and star require less.",
    explanation: "Cost scales with the number of connections.",
    hint: "More connections = more cables = more cost.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of network design in topology?",
    shortAnswer: "Design determines the topology choice, equipment selection, and deployment.",
    explanation: "Good design balances cost, performance, and reliability.",
    hint: "Planning before building.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are the future trends in network topology?",
    shortAnswer: "Software-defined networking (SDN) and network virtualization are making topologies more dynamic and programmable.",
    explanation: "Topologies are becoming less physical and more logical.",
    hint: "The network can reshape itself.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;