/**
 * Topic 4: Preserving Branch Topologies: Using git merge --no-ff
 * Module: 002_002_merging-strategies-and-conflict-resolution
 * Instructor: Sukanta Hui (Coder & AccoTax, Barrackpore)
 */

const questions = [
  {
    id: 1,
    question: "What does the `--no-ff` flag do during `git merge`?",
    answer: "It forces Git to generate an explicit merge commit object even when a fast-forward merge would have been mathematically possible."
  },
  {
    id: 2,
    question: "Why do enterprise software methodologies (like GitFlow) mandate `--no-ff` for feature merges?",
    answer: "To preserve visual branch topologies, document feature boundaries in git log, and enable atomic one-command rollbacks."
  },
  {
    id: 3,
    question: "What happens to the visual graph when a feature branch is merged with `--no-ff` and then deleted?",
    answer: "The visual bubble in `git log --graph` remains permanently visible, clearly showing that the commits were developed in a separate branch before merging."
  },
  {
    id: 4,
    question: "How does `--no-ff` simplify rolling back an entire failed feature consisting of 15 commits?",
    answer: "You only need to revert the single merge commit (`git revert -m 1 <merge-sha>`) rather than individually reverting all 15 commits."
  },
  {
    id: 5,
    question: "What is the global Git configuration setting to enforce `--no-ff` across all repository merges?",
    answer: "`git config --global merge.ff false`."
  },
  {
    id: 6,
    question: "What is the command to override global `merge.ff = false` for a single merge where you want fast-forward?",
    answer: "`git merge --ff <branch-name>` (or `git merge --ff-only <branch-name>`)."
  },
  {
    id: 7,
    question: "Does `git merge --no-ff` trigger merge conflicts if there was no divergence?",
    answer: "No. Because there are no conflicting changes, Git automatically creates the merge commit cleanly without any conflict prompts."
  },
  {
    id: 8,
    question: "What is the structure of the commit object created by `git merge --no-ff`?",
    answer: "It is a standard merge commit object containing two parent hashes: Parent 1 (current HEAD) and Parent 2 (incoming feature branch tip)."
  },
  {
    id: 9,
    question: "How can you view only the top-level `--no-ff` milestone merge commits in your log?",
    answer: "`git log --first-parent --oneline`."
  },
  {
    id: 10,
    question: "What is the default commit message generated by `git merge --no-ff feature-gst`?",
    answer: "`Merge branch 'feature-gst'` (or `Merge branch 'feature-gst' into main`)."
  },
  {
    id: 11,
    question: "How can you specify a custom commit message when using `--no-ff`?",
    answer: "`git merge --no-ff -m \"feat: implement GST calculation engine v1.2\" feature-gst`."
  },
  {
    id: 12,
    question: "How does GitHub's default green 'Merge pull request' button behave regarding `--no-ff`?",
    answer: "By default, GitHub performs a `--no-ff` merge, creating an explicit merge commit referencing the Pull Request number (e.g. `Merge pull request #42 from team/feature`)."
  },
  {
    id: 13,
    question: "What is the difference between `git merge --no-ff` and `git merge --squash`?",
    answer: "`--no-ff` preserves all individual feature commits in history connected via a 2-parent merge commit, while `--squash` collapses all changes into a single 1-parent regular commit."
  },
  {
    id: 14,
    question: "Why do Trunk-Based Development proponents sometimes dislike `--no-ff`?",
    answer: "Because it creates extra merge commits and a non-linear graph, whereas Trunk-Based teams prioritize completely flat linear timelines via rebase and fast-forward."
  },
  {
    id: 15,
    question: "Can you use `--no-ff` when merging a release tag?",
    answer: "Yes: `git merge --no-ff v1.0.0` creates a clear milestone merge commit recording the tag integration."
  },
  {
    id: 16,
    question: "What happens if you run `git merge --no-ff` on an incoming branch that has zero new commits?",
    answer: "Git prints `Already up to date.` and does not create a superfluous merge commit."
  },
  {
    id: 17,
    question: "What does `git show --stat <no-ff-merge-sha>` display?",
    answer: "It displays the total file modifications and lines changed across the entire merged feature."
  },
  {
    id: 18,
    question: "What is the effect of running `git bisect` on a history with `--no-ff` merge commits?",
    answer: "`git bisect` can test entire feature branches at once or drill down into individual feature commits automatically."
  },
  {
    id: 19,
    question: "How do you configure a specific branch in `.git/config` to always merge with `--no-ff`?",
    answer: "`git config branch.<branch-name>.mergeoptions \"--no-ff\"`."
  },
  {
    id: 20,
    question: "What is the impact of `--no-ff` on repository disk size?",
    answer: "Virtually zero (around a few hundred bytes per merge commit object)."
  },
  {
    id: 21,
    question: "How does `git log --merges` utilize `--no-ff` commits?",
    answer: "It filters the repository log to display ONLY merge commits, serving as an instant changelog of all merged features."
  },
  {
    id: 22,
    question: "How does `git log --no-merges` behave on a `--no-ff` repository?",
    answer: "It hides all merge commit nodes and displays only the raw individual code authoring commits."
  },
  {
    id: 23,
    question: "What happens to the staging area during a `git merge --no-ff` command?",
    answer: "Git stages all changes from the incoming branch and immediately commits the merge object (unless `--no-commit` was passed)."
  },
  {
    id: 24,
    question: "How did Sukanta Hui explain `--no-ff` to Abhronila Das at AccoTax Barrackpore?",
    answer: "He compared fast-forward to tearing down a wall between two rooms to make one big hallway, whereas `--no-ff` is putting an archway labeled 'GST Department' over the door to preserve identity."
  },
  {
    id: 25,
    question: "What is the best rule of thumb for deciding between Fast-Forward and `--no-ff`?",
    answer: "Use Fast-Forward for trivial 1-commit bug fixes and local rebases; use `--no-ff` for multi-commit feature branches and production release PRs."
  }
];

export default questions;
