// topic14_files/topic14_questions.js

const questions = [
  {
    question: "What is the Lossless Join (Non-Additive Join) property in relational decomposition?",
    shortAnswer: "A property guaranteeing that joining decomposed relations via Natural Join reconstructs the exact original relation without producing spurious (phantom) tuples.",
    explanation: "Standard formal definition of lossless join property.",
    hint: "Exact reconstruction of the original table with zero phantom rows.",
    level: "basic"
  },
  {
    question: "What is a 'Spurious Tuple' in relation decomposition?",
    shortAnswer: "A false, non-existent row generated accidentally when joining improperly decomposed tables (lossy decomposition).",
    explanation: "Definition of spurious tuple.",
    hint: "A false phantom row generated by a lossy join.",
    level: "basic"
  },
  {
    question: "State Heath's Lossless Join Theorem for a binary decomposition of R into R1 and R2.",
    shortAnswer: "The decomposition is lossless if and only if the common attribute set (R1 ∩ R2) is a Super Key of R1 or a Super Key of R2 (i.e. (R1 ∩ R2) → R1 or (R1 ∩ R2) → R2).",
    explanation: "Heath's Theorem for binary lossless joins.",
    hint: "The intersection (R1 ∩ R2) must be a super key of R1 or R2.",
    level: "basic"
  },
  {
    question: "What is the Dependency Preservation property in relational decomposition?",
    shortAnswer: "A property guaranteeing that all functional dependencies in the original set F can be verified within individual decomposed tables without requiring cross-table SQL joins.",
    explanation: "Definition of dependency preservation.",
    hint: "All original functional dependencies can be enforced locally in single tables.",
    level: "basic"
  },
  {
    question: "Which property is MANDATORY in all relational decompositions: Lossless Join or Dependency Preservation?",
    shortAnswer: "Lossless Join is strictly MANDATORY (losing it causes permanent data corruption). Dependency Preservation is highly desirable but occasionally sacrificed in BCNF.",
    explanation: "Mandatory vs desirable decomposition properties.",
    hint: "Lossless Join is mandatory; Dependency Preservation is desirable.",
    level: "basic"
  },
  {
    question: "If relation R(A, B, C) with FD A → B is decomposed into R1(A, B) and R2(B, C), is the decomposition lossless?",
    shortAnswer: "NO, it is LOSSY! The common attribute is B, and B+ = {B}, which is NOT a super key of R1 or R2.",
    explanation: "Example of lossy decomposition on non-key attribute.",
    hint: "Lossy because common attribute B is not a super key.",
    level: "basic"
  },
  {
    question: "If relation R(A, B, C) with FD A → B is decomposed into R1(A, B) and R2(A, C), is the decomposition lossless?",
    shortAnswer: "YES! The common attribute is A, and A+ = {A, B} = R1, so A is a super key of R1 (Lossless by Heath's Theorem).",
    explanation: "Example of valid lossless decomposition.",
    hint: "Yes, common attribute A is a super key of R1.",
    level: "basic"
  },
  {
    question: "Does 3NF synthesis guarantee BOTH Lossless Join and Dependency Preservation?",
    shortAnswer: "YES! Bernstein's 3NF synthesis algorithm mathematically guarantees both Lossless Join and Dependency Preservation.",
    explanation: "3NF dual guarantee.",
    hint: "Yes, 3NF synthesis always guarantees both.",
    level: "basic"
  },
  {
    question: "Does BCNF decomposition guarantee Dependency Preservation?",
    shortAnswer: "NO. While BCNF always guarantees Lossless Join, it may not be possible to preserve all functional dependencies in BCNF without cross-table constraints.",
    explanation: "BCNF dependency preservation limitation.",
    hint: "No, BCNF can sacrifice dependency preservation.",
    level: "basic"
  },
  {
    question: "In relation R(A, B, C) with FDs {AB → C, C → B}, if decomposed into R1(C, B) and R2(A, C), which FD is lost?",
    shortAnswer: "`AB → C` is lost because no single decomposed table contains all three attributes {A, B, C}.",
    explanation: "Lost dependency example in BCNF.",
    hint: "AB → C is lost.",
    level: "moderate"
  },
  {
    question: "How can a lost functional dependency be enforced in a production database?",
    shortAnswer: "Using SQL database triggers (`BEFORE INSERT/UPDATE`) or application-level transactional validation queries.",
    explanation: "Enforcing lost dependencies via triggers.",
    hint: "Using database triggers or application code.",
    level: "basic"
  },
  {
    question: "What algorithm is used to test whether a multi-table decomposition (k ≥ 3) is lossless?",
    shortAnswer: "The Chase Algorithm (using a tableau matrix of symbols).",
    explanation: "Overview of the Chase Algorithm.",
    hint: "The Chase Algorithm using tableau matrices.",
    level: "expert"
  },
  {
    question: "How does the Chase Algorithm determine that a decomposition is lossless?",
    shortAnswer: "If iterative application of functional dependencies transforms at least one row of the tableau matrix into all original unsubscripted symbols (a1, a2, ..., an).",
    explanation: "Termination condition of the Chase algorithm.",
    hint: "When one row becomes all original symbols (a1, a2, ..., an).",
    level: "expert"
  },
  {
    question: "Why does a lossy decomposition cause data corruption?",
    shortAnswer: "Because querying the database with a natural join produces incorrect phantom associations that never existed in the real world.",
    explanation: "Consequences of lossy joins.",
    hint: "Creates false phantom records upon querying with joins.",
    level: "basic"
  },
  {
    question: "What is Heath's condition expressed as an attribute closure check?",
    shortAnswer: "Compute (R1 ∩ R2)+; if R1 ⊆ (R1 ∩ R2)+ OR R2 ⊆ (R1 ∩ R2)+, the decomposition is lossless.",
    explanation: "Attribute closure formulation of Heath's Theorem.",
    hint: "Check if (R1 ∩ R2)+ contains all attributes of R1 or R2.",
    level: "moderate"
  },
  {
    question: "In an academy roster `(student_id, student_name, course_id, fee)`, if decomposed into `R1(student_id, student_name)` and `R2(student_id, course_id, fee)`, is it lossless?",
    shortAnswer: "YES, because the common attribute `student_id` determines `student_name` (making it a super key of R1).",
    explanation: "Practical academy roster lossless check.",
    hint: "Yes, student_id is a super key of R1.",
    level: "basic"
  },
  {
    question: "In the same roster, if decomposed into `R1(student_name, course_id)` and `R2(course_id, fee)`, is it lossless?",
    shortAnswer: "NO, it is LOSSY! The common attribute is `course_id`, which does not determine `student_name` (students taking the same course get falsely mixed up).",
    explanation: "Practical academy roster lossy check.",
    hint: "Lossy because course_id does not determine student_name.",
    level: "basic"
  },
  {
    question: "What mathematical property ensures that no information is lost when storing data across decomposed tables?",
    shortAnswer: "The Lossless Join property.",
    explanation: "Core role of lossless join in relational theory.",
    hint: "The Lossless Join property.",
    level: "basic"
  },
  {
    question: "Can a decomposition be dependency preserving but lossy?",
    shortAnswer: "YES! For example, R(A, B, C) with FDs {A → B, B → C} decomposed into R1(A, B) and R2(B, C) preserves all FDs but is lossy with respect to candidate key A.",
    explanation: "Dependency preserving yet lossy decomposition.",
    hint: "Yes, preserving FDs does not automatically guarantee lossless join.",
    level: "moderate"
  },
  {
    question: "Can a decomposition be lossless but NOT dependency preserving?",
    shortAnswer: "YES! BCNF decompositions often achieve lossless join while failing to preserve all functional dependencies.",
    explanation: "Lossless but non-preserving decomposition.",
    hint: "Yes, common in BCNF decompositions.",
    level: "basic"
  },
  {
    question: "What is the projection of a functional dependency set F onto a sub-schema Ri (denoted as π_Ri(F))?",
    shortAnswer: "The set of all functional dependencies X → Y in F+ such that all attributes in X and Y belong entirely to Ri (X ∪ Y ⊆ Ri).",
    explanation: "Definition of projected dependency set.",
    hint: "All FDs in F+ whose attributes are contained within Ri.",
    level: "moderate"
  },
  {
    question: "How do you verify if an original FD X → Y is preserved in decomposition D = {R1, R2}?",
    shortAnswer: "Compute the closure of X under the combined projected dependencies (F1 ∪ F2)+; if Y is in this closure, the dependency is preserved.",
    explanation: "Algorithm for testing dependency preservation.",
    hint: "Compute X+ under the union of projected dependencies.",
    level: "moderate"
  },
  {
    question: "Why is dependency preservation important for database write performance?",
    shortAnswer: "Because if dependencies are preserved, each table's constraints can be verified in isolation with simple primary/unique key indexes without multi-table joins on every INSERT.",
    explanation: "Performance impact of dependency preservation.",
    hint: "Allows fast index checks on INSERTs without executing cross-table joins.",
    level: "basic"
  },
  {
    question: "If relation R(A, B, C, D) with candidate key A is decomposed into R1(A, B), R2(A, C), and R3(A, D), is it lossless?",
    shortAnswer: "YES! The common attribute A is the candidate key of R and a super key of all decomposed tables.",
    explanation: "Lossless star decomposition.",
    hint: "Yes, A is a super key of all relations.",
    level: "basic"
  },
  {
    question: "What is the minimum number of tables a relation can be decomposed into?",
    shortAnswer: "Two tables (binary decomposition).",
    explanation: "Binary decomposition baseline.",
    hint: "Two tables.",
    level: "basic"
  },
  {
    question: "In hospital management, if `Visits(patient_id, doctor_id, date)` is decomposed into `(patient_id, date)` and `(doctor_id, date)`, is it lossless?",
    shortAnswer: "NO, it is LOSSY! The common attribute `date` is not a key, creating spurious tuples mixing up which doctor saw which patient on that date.",
    explanation: "Healthcare lossy join example.",
    hint: "Lossy because date is not a super key.",
    level: "basic"
  },
  {
    question: "What SQL join operator is mathematically equivalent to the relational algebra natural join (⋈)?",
    shortAnswer: "`NATURAL JOIN` or `INNER JOIN ... ON table1.common_col = table2.common_col`.",
    explanation: "SQL equivalent of natural join.",
    hint: "NATURAL JOIN or INNER JOIN on common columns.",
    level: "basic"
  },
  {
    question: "When evaluating a database schema design, what is the first validation step?",
    shortAnswer: "Verify that all decompositions satisfy the Lossless Join property (mandatory step).",
    explanation: "First priority in decomposition validation.",
    hint: "Verify Lossless Join property first.",
    level: "basic"
  },
  {
    question: "What is the second validation step when evaluating a schema decomposition?",
    shortAnswer: "Check if the decomposition is Dependency Preserving (to avoid costly cross-table triggers).",
    explanation: "Second priority in decomposition validation.",
    hint: "Check for Dependency Preservation.",
    level: "basic"
  },
  {
    question: "What is the ultimate takeaway for database engineers regarding Lossless Join & Dependency Preservation?",
    shortAnswer: "Lossless Join is strictly non-negotiable to avoid data corruption; Dependency Preservation ensures fast, local constraint enforcement. Strive for 3NF when both are required, and use BCNF when eliminating all redundancy takes precedence.",
    explanation: "Final summary conclusion for Topic 14.",
    hint: "Lossless join is non-negotiable; dependency preservation ensures local constraint speed.",
    level: "basic"
  }
];

export default questions;
