// topic8_questions.js
// 30 FAQs on "Infix Expression" – basic to expert.

const questions = [
  {
    question: "What is an infix expression?",
    shortAnswer: "An expression where operators are placed between operands.",
    explanation: "This is the standard notation used in mathematics and most programming languages.",
    hint: "Think of A + B.",
    level: "basic",
    codeExample: "int result = a + b;",
  },
  {
    question: "How does infix handle operator precedence?",
    shortAnswer: "Operators have defined precedence levels; higher precedence operators are evaluated first.",
    explanation: "For example, multiplication (*) has higher precedence than addition (+).",
    hint: "Like in math: PEMDAS.",
    level: "basic",
    codeExample: "int x = 5 + 3 * 2; // 11 (3*2 first)",
  },
  {
    question: "What is the role of parentheses in infix?",
    shortAnswer: "Parentheses override precedence and force evaluation of the enclosed expression first.",
    explanation: "They make the order of operations explicit.",
    hint: "They group sub‑expressions.",
    level: "basic",
    codeExample: "int x = (5 + 3) * 2; // 16",
  },
  {
    question: "Why is infix considered human‑friendly?",
    shortAnswer: "It matches natural reading order and how we learn arithmetic.",
    explanation: "We are taught from childhood to read and write expressions in infix.",
    hint: "It's what we use in everyday life.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What are the disadvantages of infix for computers?",
    shortAnswer: "It requires precedence and associativity rules, and parentheses, making parsing more complex.",
    explanation: "Computers prefer unambiguous notations like prefix and postfix.",
    hint: "Think about the extra work for the compiler.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What is the associativity of infix operators?",
    shortAnswer: "Most binary operators are left‑associative, except assignment and ternary.",
    explanation: "Left‑associative means evaluation from left to right for same precedence.",
    hint: "a - b - c is (a - b) - c.",
    level: "intermediate",
    codeExample: "int x = 10 - 3 - 2; // 5",
  },
  {
    question: "Can you write `a + b * c` without parentheses and still have addition first?",
    shortAnswer: "No, because multiplication has higher precedence. You must use `(a + b) * c`.",
    explanation: "Precedence is fixed; parentheses are needed to change it.",
    hint: "Use parentheses to force addition first.",
    level: "basic",
    codeExample: "(a + b) * c",
  },
  {
    question: "What is the precedence of relational operators compared to arithmetic?",
    shortAnswer: "Relational operators (`>`, `<`, `==`) have lower precedence than arithmetic (`+`, `-`, `*`, `/`).",
    explanation: "So `a + b > c` is `(a + b) > c`.",
    hint: "Arithmetic first, then comparison.",
    level: "intermediate",
    codeExample: "if (a + b > c) { }",
  },
  {
    question: "How does Java evaluate `5 + 3 * 2`?",
    shortAnswer: "It evaluates `3 * 2` first (6), then `5 + 6` (11).",
    explanation: "Because `*` has higher precedence than `+`.",
    hint: "Multiplication before addition.",
    level: "basic",
    codeExample: "int result = 5 + 3 * 2; // 11",
  },
  {
    question: "What is the difference between `&` and `&&` in infix?",
    shortAnswer: "`&` is bitwise AND (or non‑short‑circuit logical AND), while `&&` is short‑circuit logical AND.",
    explanation: "`&&` short‑circuits; `&` does not.",
    hint: "Use `&&` for conditional logic.",
    level: "intermediate",
    codeExample: "if (a != null && a.isValid()) { }",
  },
  {
    question: "How do you handle floating‑point division in infix?",
    shortAnswer: "Make sure at least one operand is floating‑point to avoid integer division.",
    explanation: "In Java, `5 / 2` gives `2`; `5 / 2.0` gives `2.5`.",
    hint: "Use a decimal literal or cast.",
    level: "basic",
    codeExample: "double d = 5 / 2.0;",
  },
  {
    question: "What is the role of the assignment operator `=` in infix?",
    shortAnswer: "It assigns the value of the right operand to the left operand variable.",
    explanation: "It's an infix operator with lower precedence than others.",
    hint: "It's not equality.",
    level: "basic",
    codeExample: "int x = 10;",
  },
  {
    question: "Why is `a = b = c` valid in Java?",
    shortAnswer: "Because assignment is right‑associative, so it is parsed as `a = (b = c)`.",
    explanation: "The rightmost assignment is evaluated first.",
    hint: "Right‑associative.",
    level: "intermediate",
    codeExample: "int a, b, c; a = b = c = 5;",
  },
  {
    question: "What is the precedence of `+` and `-`?",
    shortAnswer: "They have the same precedence (additive), evaluated left‑to‑right.",
    explanation: "So `a - b + c` is `(a - b) + c`.",
    hint: "Same level.",
    level: "basic",
    codeExample: "int x = 10 - 3 + 2; // 9",
  },
  {
    question: "How do you ensure addition is done before multiplication in infix?",
    shortAnswer: "Use parentheses: `(a + b) * c`.",
    explanation: "Parentheses group the addition and force it to be evaluated first.",
    hint: "Wrap the addition.",
    level: "basic",
    codeExample: "(a + b) * c",
  },
  {
    question: "What is the precedence of the ternary operator `? :`?",
    shortAnswer: "It has lower precedence than logical OR (`||`) but higher than assignment.",
    explanation: "It's rarely used without parentheses for clarity.",
    hint: "Use parentheses with ternary.",
    level: "intermediate",
    codeExample: "int max = (a > b) ? a : b;",
  },
  {
    question: "What happens if you mix `&&` and `||` without parentheses?",
    shortAnswer: "`&&` has higher precedence, so `a || b && c` is `a || (b && c)`.",
    explanation: "This can be confusing; use parentheses to make it explicit.",
    hint: "AND before OR.",
    level: "intermediate",
    codeExample: "boolean b = true || false && false; // true",
  },
  {
    question: "Can you use infix with strings?",
    shortAnswer: "Yes, the `+` operator concatenates strings when at least one operand is a string.",
    explanation: "Example: `\"Hello\" + \"World\"`.",
    hint: "It's overloaded.",
    level: "basic",
    codeExample: "String s = \"Hello\" + \" World\";",
  },
  {
    question: "What is the difference between `==` and `equals()` in infix?",
    shortAnswer: "`==` compares references for objects; `equals()` compares content.",
    explanation: "For strings, use `equals()` for content comparison.",
    hint: "`==` checks identity.",
    level: "intermediate",
    codeExample: "if (str1.equals(str2)) { }",
  },
  {
    question: "What is the precedence of `instanceof`?",
    shortAnswer: "It has higher precedence than `==` but lower than relationals.",
    explanation: "Example: `obj instanceof String == true` is parsed as `(obj instanceof String) == true`.",
    hint: "Use parentheses for clarity.",
    level: "advanced",
    codeExample: "if (obj instanceof String) { }",
  },
  {
    question: "How does operator precedence affect boolean expressions?",
    shortAnswer: "Relational operators are evaluated first, then logical operators (`&&` then `||`).",
    explanation: "So `age > 18 && hasLicense` is `(age > 18) && hasLicense`.",
    hint: "Comparisons before logical.",
    level: "intermediate",
    codeExample: "if (age >= 18 && hasLicense) { }",
  },
  {
    question: "What is the associativity of `+` for strings?",
    shortAnswer: "Left‑associative, so `\"Hello\" + 5 + 3` is `(\"Hello\" + 5) + 3`.",
    explanation: "It concatenates left to right.",
    hint: "Left‑associative.",
    level: "intermediate",
    codeExample: "String s = \"Hello\" + 5 + 3; // \"Hello53\"",
  },
  {
    question: "How do you avoid integer division in infix?",
    shortAnswer: "Use a floating‑point literal or cast one operand to double.",
    explanation: "Example: `double d = 5 / 2.0;` or `(double) 5 / 2`.",
    hint: "Promote to double.",
    level: "basic",
    codeExample: "double d = (double) 5 / 2;",
  },
  {
    question: "What is the precedence of shift operators?",
    shortAnswer: "Shift operators (`<<`, `>>`) have lower precedence than additive but higher than relational.",
    explanation: "Example: `8 << 2 + 1` is `8 << 3` because `+` has higher precedence.",
    hint: "Additive first.",
    level: "advanced",
    codeExample: "int result = 8 << 2 + 1; // 8 << 3 = 64",
  },
  {
    question: "Can you chain multiple assignments in infix?",
    shortAnswer: "Yes, due to right‑associativity: `a = b = c = 5;`.",
    explanation: "All variables get the value 5.",
    hint: "Right‑to‑left.",
    level: "basic",
    codeExample: "int a, b, c; a = b = c = 5;",
  },
  {
    question: "What is the precedence of bitwise operators?",
    shortAnswer: "`&` > `^` > `|`, and they are lower than relationals.",
    explanation: "So `a & b | c` is `(a & b) | c`.",
    hint: "Check the table.",
    level: "advanced",
    codeExample: "int flags = 0b1010 & 0b1100 | 0b0001;",
  },
  {
    question: "How do you make an infix expression more readable?",
    shortAnswer: "Use parentheses, spaces, and break long lines.",
    explanation: "Clarity is more important than brevity.",
    hint: "Write for humans.",
    level: "basic",
    codeExample: "(a + b) * (c - d) // clear",
  },
  {
    question: "What is the role of the `+` operator in Java infix?",
    shortAnswer: "It performs numeric addition or string concatenation depending on operand types.",
    explanation: "If both operands are numeric, it adds; if one is a string, it concatenates.",
    hint: "Overloaded.",
    level: "basic",
    codeExample: "int sum = 5 + 3; String s = \"Hello\" + \"World\";",
  },
  {
    question: "What is the precedence of `!` (logical NOT) in infix?",
    shortAnswer: "It has very high precedence, just after unary operators.",
    explanation: "It applies to the immediate boolean expression.",
    hint: "It's unary.",
    level: "basic",
    codeExample: "boolean b = !true; // false",
  },
  {
    question: "Can you use `+` to concatenate strings and numbers?",
    shortAnswer: "Yes, if at least one operand is a string, the number is converted and concatenated.",
    explanation: "Example: `\"Age: \" + 25` → `\"Age: 25\"`.",
    hint: "String conversion.",
    level: "basic",
    codeExample: "String msg = \"Total: \" + (5 + 3); // \"Total: 8\"",
  },
];

export default questions;