const questions = [
  {
    question: "What is a MAN and what is its typical geographic scope?",
    shortAnswer: "A Metropolitan Area Network (MAN) spans a city or metropolitan area, typically up to 50 km.",
    explanation: "MANs connect multiple LANs across a city and are larger than LANs but smaller than WANs.",
    hint: "Think of a network covering a city like Kolkata.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What technologies are commonly used in MANs?",
    shortAnswer: "Metro Ethernet, fiber optics, microwave links, DWDM, and MPLS.",
    explanation: "MANs often use fiber as the backbone, with microwave as a backup or where fiber is not feasible.",
    hint: "High-speed connectivity across a city.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does a MAN differ from a LAN?",
    shortAnswer: "A MAN covers a city (up to 50 km), while a LAN covers a building or campus (up to a few km).",
    explanation: "MANs use different technologies (fiber, microwave) and are often owned by municipalities or ISPs.",
    hint: "Size and ownership.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does a MAN differ from a WAN?",
    shortAnswer: "A MAN covers a city; a WAN covers a country or globally.",
    explanation: "WANs are larger and use more complex routing, often across multiple ISPs.",
    hint: "City vs. country/world.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Give an example of a MAN.",
    shortAnswer: "A city-wide fiber network connecting government buildings, schools, libraries, and hospitals.",
    explanation: "Many cities deploy MANs for smart city services and public administration.",
    hint: "Municipal network.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is Metro Ethernet?",
    shortAnswer: "Ethernet technology deployed over fiber optics to connect LANs across a metropolitan area.",
    explanation: "Metro Ethernet offers high bandwidth and is a cost-effective alternative to leased lines.",
    hint: "Ethernet over a city.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the role of an ISP in a MAN?",
    shortAnswer: "ISPs often use MANs as aggregation networks to connect customers and backhaul traffic to core networks.",
    explanation: "A MAN can serve as the middle-mile connecting neighborhoods to the internet backbone.",
    hint: "The link between local networks and the internet.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is DWDM and why is it important in MANs?",
    shortAnswer: "DWDM (Dense Wavelength Division Multiplexing) sends multiple data streams over one fiber using different light wavelengths.",
    explanation: "It dramatically increases capacity without laying new fiber.",
    hint: "More data on the same fiber.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a microwave link in a MAN?",
    shortAnswer: "A wireless point-to-point connection using microwave frequencies, used where fiber is not possible.",
    explanation: "Microwave links can bridge distances over obstacles like rivers or mountains.",
    hint: "Wireless city link.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are the main advantages of a MAN?",
    shortAnswer: "High speed, scalability, centralised management, and support for multiple services.",
    explanation: "MANs provide cost-effective city-wide connectivity.",
    hint: "Efficient city networking.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are the disadvantages of a MAN?",
    shortAnswer: "High installation cost, regulatory hurdles, maintenance challenges, and security risks.",
    explanation: "Deploying fiber in cities is expensive and requires permits.",
    hint: "Cost and logistics.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How do you ensure redundancy in a MAN?",
    shortAnswer: "Use a ring topology with dual paths, so if one fiber is cut, traffic reroutes the other way.",
    explanation: "Resilient MANs often have multiple fiber rings or diverse microwave links.",
    hint: "Two ways around the city.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the typical speed of a modern MAN?",
    shortAnswer: "1-10 Gbps, with 40Gbps and 100Gbps on advanced backbones.",
    explanation: "Speeds depend on fiber technology and equipment.",
    hint: "Gigabit speeds across the city.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the significance of a MAN for smart cities?",
    shortAnswer: "MANs provide the connectivity for IoT sensors, traffic management, surveillance, and public safety systems.",
    explanation: "A MAN is the backbone for smart city applications.",
    hint: "City-wide IoT and services.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is MPLS and how is it used in MANs?",
    shortAnswer: "MPLS (Multiprotocol Label Switching) uses labels to forward packets quickly, enabling traffic engineering and VPNs.",
    explanation: "MPLS is often used in MANs to provide quality of service and separate traffic for different customers.",
    hint: "Labels instead of IP lookups.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do you secure a MAN?",
    shortAnswer: "Encryption (MACsec, IPsec), access controls, physical security, and monitoring.",
    explanation: "Security must protect against both cyber and physical threats.",
    hint: "Protect fiber and data.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between a MAN and a campus network?",
    shortAnswer: "A campus network covers a university or business park (larger LAN), while a MAN covers a city.",
    explanation: "Campus networks are privately owned and often use LAN technologies; MANs are city-wide.",
    hint: "Scale: campus vs. city.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What are the cost implications of building a MAN?",
    shortAnswer: "High upfront costs for fiber laying, equipment, and permits; operational costs for maintenance and power.",
    explanation: "ROI comes from long-term service delivery.",
    hint: "Expensive to build, but pays off over time.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of a Network Operations Center (NOC) in a MAN?",
    shortAnswer: "A NOC monitors the MAN, detects faults, and coordinates repairs to minimise downtime.",
    explanation: "Continuous monitoring is essential for a critical city infrastructure.",
    hint: "The command center.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does a MAN support Internet of Things (IoT) applications?",
    shortAnswer: "MAN provides the backhaul for IoT gateways, aggregating data from sensors across the city.",
    explanation: "Smart streetlights, parking sensors, and environmental monitors all rely on MAN connectivity.",
    hint: "City-wide sensor network.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a dark fiber network and how does it relate to MANs?",
    shortAnswer: "Dark fiber is unused fiber optic cable that is leased to organisations to build their own networks.",
    explanation: "Cities often lease dark fiber to ISPs or enterprises to create MANs.",
    hint: "Fiber that is available but not lit.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the difference between a ring and a mesh topology in a MAN?",
    shortAnswer: "A ring provides two paths; a mesh provides many paths, offering higher redundancy but more complexity.",
    explanation: "MANs often use rings for simplicity; critical networks may use partial mesh.",
    hint: "One loop vs. many interconnections.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does wavelength division multiplexing (WDM) increase fiber capacity?",
    shortAnswer: "WDM sends multiple wavelengths (colors) of light through a single fiber, each carrying a separate data stream.",
    explanation: "DWDM can carry 80+ wavelengths, multiplying capacity.",
    hint: "Many lanes on a single highway.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of SONET/SDH in legacy MANs?",
    shortAnswer: "SONET (US) and SDH (world) are time-division multiplexing standards used for fiber optic MANs, now largely replaced by Ethernet.",
    explanation: "They provided predictable bandwidth but are less flexible than Ethernet.",
    hint: "Older technology still in use.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do you handle fault detection in a fiber MAN?",
    shortAnswer: "Optical Time Domain Reflectometers (OTDR) and monitoring systems detect breaks or degradation.",
    explanation: "OTDR sends pulses and analyses reflections to locate faults.",
    hint: "Fiber cable diagnostics.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the impact of latency in a MAN?",
    shortAnswer: "Latency is low (microseconds) due to short distances, but increases with distance and network load.",
    explanation: "MAN latency is suitable for real-time applications like VoIP.",
    hint: "City-wide, latency is still very low.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do you manage Quality of Service (QoS) in a MAN?",
    shortAnswer: "Using traffic classification, prioritisation, and scheduling mechanisms like DiffServ or MPLS TE.",
    explanation: "QoS ensures critical services (like emergency communications) get priority.",
    hint: "Classify and prioritize traffic.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are the typical service level agreements (SLAs) for a MAN?",
    shortAnswer: "SLAs cover uptime (99.99%), latency, jitter, and throughput guarantees.",
    explanation: "SLA metrics ensure the network meets business needs.",
    hint: "Contracts with performance guarantees.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does a MAN integrate with cloud services?",
    shortAnswer: "MAN provides high-speed connectivity to cloud data centers, enabling hybrid cloud architectures.",
    explanation: "Enterprises use MANs to connect on-premise LANs to cloud providers.",
    hint: "Fast path to the cloud.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are the environmental considerations for building a MAN?",
    shortAnswer: "Minimise disruption during construction, use existing infrastructure, and plan for power efficiency.",
    explanation: "Sustainable MANs use low-power equipment and minimize physical footprint.",
    hint: "Green networking.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;