// topic4_files/topic4_questions.js

const questions = [
  {
    question: "What is a FULL OUTER JOIN in relational database theory?",
    shortAnswer: "A relational join operation that returns all matching rows from both tables, plus all unmatched rows from the left table and all unmatched rows from the right table.",
    explanation: "Standard formal definition of FULL OUTER JOIN.",
    hint: "Combines the complete results of both LEFT JOIN and RIGHT JOIN.",
    level: "basic"
  },
  {
    question: "Does MySQL support native FULL OUTER JOIN syntax directly?",
    shortAnswer: "NO. MySQL does not have a native `FULL OUTER JOIN` keyword and returns a syntax error (Error 1064) if attempted.",
    explanation: "MySQL syntax limitation for FULL OUTER JOIN.",
    hint: "No, MySQL lacks native FULL JOIN syntax.",
    level: "basic"
  },
  {
    question: "In relational algebra, what symbol represents the Full Outer Join?",
    shortAnswer: "The bowtie with four horizontal prongs extending on both sides (⟗).",
    explanation: "Relational algebra notation for Full Outer Join.",
    hint: "Full outer bowtie symbol (⟗).",
    level: "basic"
  },
  {
    question: "How do you emulate a FULL OUTER JOIN in MySQL?",
    shortAnswer: "By combining a `LEFT JOIN` and a `RIGHT JOIN` using the `UNION` operator: `(SELECT ... LEFT JOIN ...) UNION (SELECT ... RIGHT JOIN ...)`. ",
    explanation: "Standard MySQL FULL OUTER JOIN emulation pattern.",
    hint: "LEFT JOIN UNION RIGHT JOIN.",
    level: "basic"
  },
  {
    question: "Why is `UNION` used instead of `UNION ALL` in the standard emulation pattern?",
    shortAnswer: "Because `UNION` automatically eliminates the duplicate matching rows generated by both the LEFT and RIGHT queries, whereas `UNION ALL` would output matching rows twice.",
    explanation: "Deduplication role of UNION.",
    hint: "UNION removes duplicate matched rows produced by both queries.",
    level: "basic"
  },
  {
    question: "What is the high-performance alternative to `LEFT JOIN UNION RIGHT JOIN` in MySQL?",
    shortAnswer: "`LEFT JOIN` combined with `UNION ALL` and a `RIGHT ANTI-JOIN` (`WHERE left_table.id IS NULL`), which avoids expensive in-memory deduplication sorts.",
    explanation: "Optimized FULL OUTER JOIN pattern using UNION ALL.",
    hint: "LEFT JOIN UNION ALL (RIGHT ANTI-JOIN).",
    level: "expert"
  },
  {
    question: "In academy management, if `students` has 4 rows and `courses` has 3 rows (2 match, 2 students unmatched, 1 course unmatched), how many rows does the emulated FULL OUTER JOIN return?",
    shortAnswer: "5 rows (2 full matches + 2 unmatched students + 1 unmatched course = 5 rows).",
    explanation: "Row calculation for FULL OUTER JOIN.",
    hint: "5 rows in total.",
    level: "basic"
  },
  {
    question: "What values appear in the right columns for unmatched left-table rows in a FULL OUTER JOIN?",
    shortAnswer: "`NULL`.",
    explanation: "NULL padding for unmatched right attributes.",
    hint: "NULL values.",
    level: "basic"
  },
  {
    question: "What values appear in the left columns for unmatched right-table rows in a FULL OUTER JOIN?",
    shortAnswer: "`NULL`.",
    explanation: "NULL padding for unmatched left attributes.",
    hint: "NULL values.",
    level: "basic"
  },
  {
    question: "When is a FULL OUTER JOIN legitimately required in enterprise software systems?",
    shortAnswer: "For data reconciliation, discrepancy auditing, comparing staging tables with production tables, and merging two legacy systems.",
    explanation: "Production use cases for FULL OUTER JOIN.",
    hint: "Data reconciliation, auditing, and comparing two systems.",
    level: "basic"
  },
  {
    question: "In accounting, how does a FULL OUTER JOIN help reconcile bank statements with internal ledgers?",
    shortAnswer: "It displays matched transactions, bank charges missing in internal ledgers (right only), and internal ledger entries not yet cleared by the bank (left only).",
    explanation: "Financial bank reconciliation pattern.",
    hint: "Identifies cleared transactions, missing bank entries, and uncleared checks.",
    level: "moderate"
  },
  {
    question: "What happens if both queries combined by `UNION` do not have the exact same number of columns in their `SELECT` list?",
    shortAnswer: "MySQL throws 'ERROR 1222 (21000): The used SELECT statements have a different number of columns'.",
    explanation: "UNION column count matching requirement.",
    hint: "Error 1222: SELECT statements must have the same number of columns.",
    level: "basic"
  },
  {
    question: "Must the column aliases in the second query of a `UNION` match the column aliases in the first query?",
    shortAnswer: "NO. MySQL uses the column names and aliases from the FIRST `SELECT` statement for the final result set headers.",
    explanation: "Column naming rules in UNION queries.",
    hint: "No, the column names of the first SELECT are used.",
    level: "basic"
  },
  {
    question: "How do you find ONLY the discrepancies (unmatched rows on both sides) from a FULL OUTER JOIN?",
    shortAnswer: "By filtering for rows where either `left_table.id IS NULL` OR `right_table.id IS NULL` (symmetric difference).",
    explanation: "Symmetric difference extraction.",
    hint: "WHERE left.id IS NULL OR right.id IS NULL.",
    level: "moderate"
  },
  {
    question: "What is the Relational Algebra term for the set of rows returned when filtering a FULL OUTER JOIN for `WHERE left.id IS NULL OR right.id IS NULL`?",
    shortAnswer: "Symmetric Difference (Disjunctive Union: $(A - B) \cup (B - A)$).",
    explanation: "Mathematical symmetric difference concept.",
    hint: "Symmetric Difference ((A - B) ∪ (B - A)).",
    level: "moderate"
  },
  {
    question: "How can you use `COALESCE()` on the join key column in a FULL OUTER JOIN to avoid showing `NULL` IDs?",
    shortAnswer: "`COALESCE(s.student_id, c.student_id) AS unified_id`.",
    explanation: "Unified ID column pattern in FULL OUTER JOIN.",
    hint: "COALESCE(left.id, right.id) AS unified_id.",
    level: "basic"
  },
  {
    question: "Why can a standard `UNION` emulation be slow on tables with millions of rows?",
    shortAnswer: "Because `UNION` performs an expensive temporary table disk write and in-memory sort to eliminate duplicate rows.",
    explanation: "Performance overhead of standard UNION deduplication.",
    hint: "Requires temporary tables and duplicate sorting.",
    level: "moderate"
  },
  {
    question: "In the optimized pattern `LEFT JOIN UNION ALL (RIGHT ANTI-JOIN)`, why is `UNION ALL` 100% safe against duplicate rows?",
    shortAnswer: "Because the second query explicitly filters `WHERE left.id IS NULL`, guaranteeing zero overlap with the first `LEFT JOIN` query.",
    explanation: "Mathematical disjoint guarantee in optimized emulation.",
    hint: "The second query only selects unmatched right rows, so no duplicates exist.",
    level: "expert"
  },
  {
    question: "Can an emulated FULL OUTER JOIN be wrapped inside a database VIEW in MySQL?",
    shortAnswer: "YES. You can create a view `CREATE VIEW full_student_courses AS SELECT ... LEFT JOIN ... UNION SELECT ... RIGHT JOIN ...`.",
    explanation: "Encapsulating FULL OUTER JOIN in SQL views.",
    hint: "Yes, you can create a view to reuse the emulated query.",
    level: "basic"
  },
  {
    question: "In payroll audit, how does a FULL OUTER JOIN identify ghost employees vs unregistered contractors?",
    shortAnswer: "By joining HR master records with biometric badge scans: badge scans without HR profile = unregistered; HR profile without badge scan = absent/ghost.",
    explanation: "Biometric payroll audit use case.",
    hint: "Identifies unregistered badge swipes and absent employee profiles.",
    level: "basic"
  },
  {
    question: "Does `ORDER BY` work on an emulated FULL OUTER JOIN?",
    shortAnswer: "YES. Place a single `ORDER BY` clause at the very end of the entire `UNION` statement.",
    explanation: "Sorting UNION queries.",
    hint: "Place ORDER BY at the very end of the UNION query.",
    level: "basic"
  },
  {
    question: "What happens if you put an `ORDER BY` inside the first `SELECT` statement before `UNION` without parenthesis?",
    shortAnswer: "MySQL ignores the inner `ORDER BY` or throws a syntax error unless enclosed in parentheses with a `LIMIT` clause.",
    explanation: "ORDER BY rules inside UNION branches.",
    hint: "Ignored by the optimizer unless paired with LIMIT in parentheses.",
    level: "expert"
  },
  {
    question: "How do you distinguish which side a row originated from in a FULL OUTER JOIN result?",
    shortAnswer: "By adding a literal classification column: `CASE WHEN s.id IS NULL THEN 'Right Only' WHEN c.id IS NULL THEN 'Left Only' ELSE 'Full Match' END AS match_type`.",
    explanation: "Row origin tagging with CASE in FULL JOIN.",
    hint: "Use CASE WHEN left.id IS NULL THEN 'Right Only' ... END.",
    level: "basic"
  },
  {
    question: "What RDBMS engines support native `FULL OUTER JOIN` without needing `UNION` emulation?",
    shortAnswer: "PostgreSQL, Microsoft SQL Server, Oracle Database, and SQLite (3.39+).",
    explanation: "Cross-engine support for native FULL OUTER JOIN.",
    hint: "PostgreSQL, SQL Server, Oracle, and modern SQLite.",
    level: "basic"
  },
  {
    question: "In hospital audit, how do you verify doctor schedules against room bookings?",
    shortAnswer: "FULL OUTER JOIN between doctor shifts and room reservations to find unscheduled doctors and unassigned rooms.",
    explanation: "Healthcare room booking audit.",
    hint: "FULL OUTER JOIN between shifts and room reservations.",
    level: "basic"
  },
  {
    question: "What index setup best optimizes the two queries in an emulated FULL OUTER JOIN?",
    shortAnswer: "Indexes on the join key in both tables (e.g. `students.course_id` and `courses.course_id`).",
    explanation: "Indexing strategy for emulated FULL JOIN.",
    hint: "Index the join keys on both tables.",
    level: "moderate"
  },
  {
    question: "What is the maximum number of rows an emulated FULL OUTER JOIN of Table A (M rows) and Table B (N rows) can produce?",
    shortAnswer: "$M \\times N$ rows (if all rows match, behaving like a Cartesian product) or $M + N$ rows (if zero rows match).",
    explanation: "Theoretical upper bound on outer join rows.",
    hint: "M × N rows (max match) or M + N rows (zero match).",
    level: "moderate"
  },
  {
    question: "Can an emulated FULL OUTER JOIN join 3 or more tables?",
    shortAnswer: "YES, by cascading multiple UNION emulations or joining a third table onto the derived FULL JOIN table.",
    explanation: "Multi-table FULL OUTER JOIN emulation.",
    hint: "Yes, by joining onto the derived full join result.",
    level: "expert"
  },
  {
    question: "Why should software engineers understand the MySQL emulation of FULL OUTER JOIN even if other engines support it natively?",
    shortAnswer: "Because it deepens understanding of relational set operations (Union, Intersection, Set Difference) and ensures database-portable SQL design.",
    explanation: "Pedagogical and engineering value of FULL JOIN emulation.",
    hint: "Deepens understanding of set operations and enables database portability.",
    level: "basic"
  },
  {
    question: "What is the ultimate takeaway for database engineers regarding FULL OUTER JOIN in MySQL?",
    shortAnswer: "While MySQL lacks native FULL OUTER JOIN syntax, emulating it via `LEFT JOIN UNION RIGHT JOIN` (or the optimized `LEFT JOIN UNION ALL (RIGHT ANTI-JOIN)`) provides complete relational parity for data reconciliation and discrepancy audits.",
    explanation: "Final summary conclusion for Topic 4 in Module 5.",
    hint: "Emulate using LEFT JOIN UNION RIGHT JOIN or optimized UNION ALL anti-join.",
    level: "basic"
  }
];

export default questions;
