const questions = [
  {
    question: "What is a LAN and what is its typical coverage?",
    shortAnswer: "A LAN connects devices within a limited area like a building or campus.",
    explanation: "LANs are high-speed, low-latency networks typically owned by a single organisation.",
    hint: "The network in your school computer lab.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are the primary technologies used in LANs?",
    shortAnswer: "Ethernet (wired) and Wi-Fi (wireless).",
    explanation: "Ethernet uses cables (twisted pair, fiber), while Wi-Fi uses radio waves.",
    hint: "Connecting via cable or wirelessly.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the typical speed of a modern LAN?",
    shortAnswer: "100 Mbps to 10 Gbps, with newer standards up to 100 Gbps.",
    explanation: "Speed depends on the Ethernet standard (e.g., Gigabit Ethernet).",
    hint: "Fast enough for streaming 4K video.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a switch and what does it do in a LAN?",
    shortAnswer: "A switch connects devices within a LAN and forwards data based on MAC addresses.",
    explanation: "Switches create separate collision domains for each port, improving performance.",
    hint: "Think of it as a smart hub that directs traffic.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the difference between a switch and a router?",
    shortAnswer: "A switch connects devices within a LAN; a router connects different networks (e.g., LAN to WAN).",
    explanation: "Switches operate at Layer 2 (MAC addresses), routers at Layer 3 (IP addresses).",
    hint: "Switch = internal traffic; Router = external traffic.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the purpose of a router in a LAN?",
    shortAnswer: "To connect the LAN to other networks, typically the internet.",
    explanation: "Routers act as gateways, forwarding data between the LAN and WAN.",
    hint: "The device that provides internet access.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Give an example of a LAN.",
    shortAnswer: "A school computer lab connecting PCs, printers, and a server.",
    explanation: "LANs are common in offices, schools, and homes.",
    hint: "The network in your classroom.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is an Ethernet cable?",
    shortAnswer: "A twisted-pair cable used for wired LAN connections.",
    explanation: "Common types: Cat5e, Cat6, Cat6a. Speeds vary based on category.",
    hint: "The cable you plug into your computer for internet.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is Wi-Fi and how does it relate to LAN?",
    shortAnswer: "Wi-Fi is a wireless technology that allows devices to connect to a LAN without cables.",
    explanation: "Based on IEEE 802.11 standards. Access points (APs) bridge wireless and wired networks.",
    hint: "Connecting without a cable.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the typical range of a Wi-Fi network?",
    shortAnswer: "Indoors: 30-50 meters; outdoors: up to 100+ meters depending on the AP.",
    explanation: "Range is affected by walls, interference, and the wireless standard.",
    hint: "How far you can be from the router.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are the main advantages of a LAN?",
    shortAnswer: "High speed, low latency, security, and resource sharing.",
    explanation: "LANs are efficient, private, and cost-effective for organisations.",
    hint: "Think about sharing printers and files.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are the disadvantages of a LAN?",
    shortAnswer: "Limited geographic coverage, wiring costs, and maintenance requirements.",
    explanation: "LANs require physical infrastructure and skilled personnel.",
    hint: "Running cables is expensive.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a collision domain and how do switches affect it?",
    shortAnswer: "A collision domain is where data packets can collide. Each port on a switch is its own collision domain.",
    explanation: "Switches eliminate collisions by using full-duplex communication.",
    hint: "Switches make networks more efficient.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a broadcast domain in a LAN?",
    shortAnswer: "A broadcast domain is the set of devices that receive broadcast packets.",
    explanation: "Switches forward broadcasts to all ports in the same VLAN; routers don't forward broadcasts.",
    hint: "A broadcast message goes to everyone on the LAN.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is VLAN and why is it used in LANs?",
    shortAnswer: "A VLAN (Virtual LAN) logically segments a physical network for security and performance.",
    explanation: "VLANs isolate traffic, reducing broadcast domains and improving security.",
    hint: "Separate virtual networks on the same physical switch.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is PoE (Power over Ethernet)?",
    shortAnswer: "PoE delivers power and data over a single Ethernet cable.",
    explanation: "Useful for devices like IP cameras, wireless APs, and VoIP phones.",
    hint: "No separate power cable needed.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the maximum length of a standard Ethernet cable?",
    shortAnswer: "100 meters for twisted-pair Ethernet (Cat5e/Cat6).",
    explanation: "Beyond 100m, signal attenuation requires repeaters or fiber.",
    hint: "Measure from the switch to the device.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between 2.4 GHz and 5 GHz Wi-Fi?",
    shortAnswer: "2.4 GHz has longer range but lower speed; 5 GHz has higher speed but shorter range.",
    explanation: "2.4 GHz is more crowded (interference); 5 GHz is cleaner but more easily blocked.",
    hint: "Choose based on distance and speed needs.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a network switch's backplane capacity?",
    shortAnswer: "The total throughput the switch can handle across all ports.",
    explanation: "It determines if the switch can handle full-duplex traffic on all ports simultaneously.",
    hint: "How much traffic can flow at once.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does DHCP work in a LAN?",
    shortAnswer: "DHCP automatically assigns IP addresses to devices on the LAN.",
    explanation: "A DHCP server leases IPs, reducing manual configuration.",
    hint: "Plug and play – no need to set IP manually.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is network segmentation and why is it important in LANs?",
    shortAnswer: "Segmentation divides a LAN into smaller parts to improve security and performance.",
    explanation: "Uses VLANs, subnets, or switches to isolate traffic.",
    hint: "Separating departments on the same network.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of STP (Spanning Tree Protocol) in a LAN?",
    shortAnswer: "STP prevents network loops by blocking redundant paths.",
    explanation: "Loops cause broadcast storms; STP ensures only one active path.",
    hint: "Prevents network meltdowns.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is link aggregation (LACP) and why is it used?",
    shortAnswer: "Link aggregation combines multiple physical links into one logical link for increased bandwidth and redundancy.",
    explanation: "LACP (Link Aggregation Control Protocol) negotiates the aggregation.",
    hint: "Combining cables for more speed.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the difference between a managed and unmanaged switch?",
    shortAnswer: "Managed switches offer configuration, VLANs, and monitoring; unmanaged switches are plug-and-play.",
    explanation: "Managed switches are used in enterprise LANs; unmanaged for basic connectivity.",
    hint: "One can be configured; the other cannot.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do you troubleshoot a slow LAN?",
    shortAnswer: "Check for bandwidth hogs, switch errors, cable issues, and Wi-Fi interference.",
    explanation: "Use monitoring tools, check interface statistics, and test cables.",
    hint: "Isolate the bottleneck.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of ARP (Address Resolution Protocol) in a LAN?",
    shortAnswer: "ARP maps IP addresses to MAC addresses within a LAN.",
    explanation: "Devices use ARP to find the hardware address of another device on the same LAN.",
    hint: "Finding who has a particular IP.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is a network loop and how does it affect a LAN?",
    shortAnswer: "A network loop occurs when there are multiple active paths between switches, causing broadcast storms.",
    explanation: "Loops can saturate the network, making it unusable.",
    hint: "A circular path causing chaos.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the purpose of QoS in a LAN?",
    shortAnswer: "QoS prioritises critical traffic (e.g., VoIP, video) over less important traffic.",
    explanation: "Ensures quality for real-time applications even during congestion.",
    hint: "Voice calls get priority over file downloads.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do you secure a Wi-Fi LAN?",
    shortAnswer: "Use WPA3 encryption, strong passwords, disable SSID broadcast, and use MAC filtering.",
    explanation: "Security is critical for wireless networks to prevent unauthorised access.",
    hint: "Lock down your wireless network.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the future of LANs with technologies like 5G and Wi-Fi 6?",
    shortAnswer: "LANs will become faster, more reliable, and support more devices with lower latency.",
    explanation: "Wi-Fi 6 offers improved efficiency; 5G may complement or replace some LAN functions.",
    hint: "Higher speeds, more devices, and better efficiency.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;