// topic6_files/topic6_questions.js

const questions = [
  {
    question: "What is a CROSS JOIN in SQL?",
    shortAnswer: "A relational join operation that produces the complete Cartesian Product of two tables, combining every row in the first table with every row in the second table without any filtering condition.",
    explanation: "Standard formal definition of CROSS JOIN.",
    hint: "Produces the full Cartesian product (M × N rows).",
    level: "basic"
  },
  {
    question: "What is the formula for the number of rows produced by a CROSS JOIN between Table A (M rows) and Table B (N rows)?",
    shortAnswer: "$M \\times N$ rows.",
    explanation: "Cardinality calculation for CROSS JOIN.",
    hint: "M × N rows.",
    level: "basic"
  },
  {
    question: "What is the formula for the number of columns (degree) in the result of a CROSS JOIN between Table A (degree d1) and Table B (degree d2)?",
    shortAnswer: "$d_1 + d_2$ columns.",
    explanation: "Degree calculation for CROSS JOIN.",
    hint: "d1 + d2 columns.",
    level: "basic"
  },
  {
    question: "Is an `ON` clause required when writing a standard CROSS JOIN in ANSI SQL?",
    shortAnswer: "NO. A pure `CROSS JOIN` takes no `ON` clause because it pairs all rows unconditionally.",
    explanation: "Absence of ON clause in pure CROSS JOIN.",
    hint: "No ON clause is required.",
    level: "basic"
  },
  {
    question: "What happens in MySQL if you write `SELECT * FROM tableA CROSS JOIN tableB ON tableA.id = tableB.id;`?",
    shortAnswer: "In MySQL, a `CROSS JOIN` with an `ON` clause is treated as syntactic sugar for an `INNER JOIN`.",
    explanation: "MySQL syntactic equivalence for CROSS JOIN with ON.",
    hint: "Behaves identically to an INNER JOIN in MySQL.",
    level: "moderate"
  },
  {
    question: "Give a common production use case for an intentional CROSS JOIN in e-commerce.",
    shortAnswer: "Generating all SKU variant combinations (e.g. combining all Sizes with all Colors for each Product).",
    explanation: "E-commerce SKU matrix generation.",
    hint: "Generating Size × Color SKU variants.",
    level: "basic"
  },
  {
    question: "How can a CROSS JOIN be used to create a Date Dimension table?",
    shortAnswer: "By cross joining tables of Years, Months (1–12), and Days (1–31) to generate a complete master calendar grid.",
    explanation: "Calendar dimension table generation.",
    hint: "Cross joining Years × Months × Days.",
    level: "moderate"
  },
  {
    question: "If a store has 10 shirts, 4 sizes, and 5 colors, how many SKU records are generated by cross joining all three tables?",
    shortAnswer: "200 SKU records ($10 \\times 4 \\times 5 = 200$).",
    explanation: "3-table Cartesian product calculation.",
    hint: "10 × 4 × 5 = 200.",
    level: "basic"
  },
  {
    question: "In academy attendance tracking, why might an admin run a CROSS JOIN between `students` and `training_dates`?",
    shortAnswer: "To generate a master attendance template with default 'Absent' or 'Pending' status for every student on every class date.",
    explanation: "Master attendance matrix template.",
    hint: "Generates a default roster for every student on every date.",
    level: "basic"
  },
  {
    question: "What is an 'Accidental Cartesian Explosion'?",
    shortAnswer: "A performance disaster caused by omitting a join condition in multi-table queries on large tables, resulting in billions of intermediate rows and crashing server memory.",
    explanation: "Definition of Cartesian explosion.",
    hint: "Unintended multiplication of massive tables due to missing join conditions.",
    level: "basic"
  },
  {
    question: "What is the equivalent syntax to `SELECT * FROM A CROSS JOIN B;` using traditional comma syntax?",
    shortAnswer: "`SELECT * FROM A, B;`",
    explanation: "Comma syntax equivalence for Cartesian product.",
    hint: "SELECT * FROM A, B;",
    level: "basic"
  },
  {
    question: "Why is explicit `CROSS JOIN` syntax preferred over comma syntax in production SQL?",
    shortAnswer: "Because `CROSS JOIN` explicitly declares the developer's intention to generate a Cartesian matrix, whereas comma syntax looks like a forgotten `WHERE` clause.",
    explanation: "Code clarity and intentionality in ANSI syntax.",
    hint: "Proves the Cartesian product was intentional, not an accidental bug.",
    level: "basic"
  },
  {
    question: "Can a `WHERE` clause be applied to a `CROSS JOIN` query?",
    shortAnswer: "YES. Adding a `WHERE` clause filters the Cartesian product, transforming it logically into a Theta Join.",
    explanation: "Filtering a CROSS JOIN with WHERE.",
    hint: "Yes, WHERE filters the generated Cartesian product.",
    level: "basic"
  },
  {
    question: "What is the computational time complexity of executing a naive CROSS JOIN between Table A (M rows) and Table B (N rows)?",
    shortAnswer: "$O(M \\times N)$.",
    explanation: "Time complexity of Cartesian product.",
    hint: "O(M × N).",
    level: "basic"
  },
  {
    question: "If Table A has 50,000 rows and Table B has 50,000 rows, how many rows does an accidental CROSS JOIN generate?",
    shortAnswer: "2,500,000,000 rows (2.5 billion rows), which will likely crash or stall the database.",
    explanation: "Real-world scale calculation of Cartesian explosion.",
    hint: "50,000 × 50,000 = 2.5 billion rows.",
    level: "basic"
  },
  {
    question: "In restaurant menu pricing, write a CROSS JOIN query to generate combo meals of pizzas and drinks.",
    shortAnswer: "`SELECT p.pizza_name, d.drink_name, (p.price + d.price - 50.00) AS combo_price FROM pizzas p CROSS JOIN drinks d;`",
    explanation: "Restaurant combo meal price matrix.",
    hint: "pizzas p CROSS JOIN drinks d.",
    level: "basic"
  },
  {
    question: "How do you generate a round-robin sports tournament matrix where every team plays every other team both home and away?",
    shortAnswer: "`SELECT home.team_name, away.team_name FROM teams home CROSS JOIN teams away WHERE home.team_id != away.team_id;`",
    explanation: "Home and away sports fixtures via CROSS JOIN.",
    hint: "teams home CROSS JOIN teams away WHERE home.id != away.id.",
    level: "moderate"
  },
  {
    question: "What happens if one of the tables in a CROSS JOIN contains 0 rows?",
    shortAnswer: "The entire query returns 0 rows ($M \\times 0 = 0$).",
    explanation: "Zero row multiplication in Cartesian product.",
    hint: "Returns 0 rows.",
    level: "basic"
  },
  {
    question: "Can a CROSS JOIN be combined with aggregate functions like `COUNT(*)`?",
    shortAnswer: "YES. `SELECT COUNT(*) FROM tableA CROSS JOIN tableB;` returns the total Cartesian product row count ($M \\times N$).",
    explanation: "Counting Cartesian product cardinality.",
    hint: "Yes, returns M × N.",
    level: "basic"
  },
  {
    question: "What is the difference between a `CROSS JOIN` and an `INNER JOIN` without an `ON` clause in MySQL?",
    shortAnswer: "In MySQL, they are completely identical; `JOIN`, `INNER JOIN`, and `CROSS JOIN` without an `ON` condition all produce a Cartesian Product.",
    explanation: "MySQL join keyword equivalence without conditions.",
    hint: "They are completely identical in MySQL.",
    level: "moderate"
  },
  {
    question: "In testing and QA automation, how are CROSS JOINs used to generate mock test data?",
    shortAnswer: "By cross joining lists of first names, last names, cities, and statuses to seed millions of realistic test user records.",
    explanation: "Test data synthesis via CROSS JOIN.",
    hint: "Generates synthetic user data by cross joining name and city arrays.",
    level: "basic"
  },
  {
    question: "How can you limit the output of a CROSS JOIN during exploratory queries to avoid crashing your SQL client?",
    shortAnswer: "By appending a `LIMIT` clause (e.g. `LIMIT 100`).",
    explanation: "Limiting result sets with LIMIT.",
    hint: "Use the LIMIT clause.",
    level: "basic"
  },
  {
    question: "In cinema ticketing, how do you generate all seating options (Rows A–K and Seats 1–20) for an auditorium?",
    shortAnswer: "`SELECT CONCAT(r.row_letter, s.seat_number) AS seat_code FROM auditorium_rows r CROSS JOIN seat_numbers s;`",
    explanation: "Cinema seat map generation.",
    hint: "Cross join rows with seat numbers.",
    level: "basic"
  },
  {
    question: "Does `CROSS JOIN` utilize database indexes?",
    shortAnswer: "NO. A pure CROSS JOIN must output all combinations, so full table scans are performed across both tables.",
    explanation: "Index usage in pure CROSS JOIN.",
    hint: "No, requires full table scans to output all combinations.",
    level: "moderate"
  },
  {
    question: "What optimizer strategy in MySQL executes Cartesian products?",
    shortAnswer: "Nested loops scanning every row of the inner table for each row of the outer driving table.",
    explanation: "Nested loop Cartesian scan.",
    hint: "Nested loop scan across both tables.",
    level: "moderate"
  },
  {
    question: "Can you cross join a table with itself (Self Cross Join)?",
    shortAnswer: "YES. For example: `SELECT * FROM colors c1 CROSS JOIN colors c2;` to generate all 2-color combinations.",
    explanation: "Self cross join syntax.",
    hint: "Yes, using two aliases on the same table.",
    level: "basic"
  },
  {
    question: "In warehouse logistics, how do you map all delivery trucks to all loading docks?",
    shortAnswer: "`SELECT t.truck_id, d.dock_number FROM trucks t CROSS JOIN loading_docks d;`",
    explanation: "Logistics truck-to-dock mapping.",
    hint: "trucks CROSS JOIN loading_docks.",
    level: "basic"
  },
  {
    question: "What is the result of `SELECT * FROM (SELECT 1 AS num) a CROSS JOIN (SELECT 2 AS num) b;`?",
    shortAnswer: "1 row containing columns with values 1 and 2.",
    explanation: "Single row cross join evaluation.",
    hint: "1 row with values (1, 2).",
    level: "basic"
  },
  {
    question: "Why should `SELECT *` be avoided when cross joining wide tables?",
    shortAnswer: "Because multiplying wide rows with many columns creates huge memory buffers and massive network payload transfers.",
    explanation: "SELECT * penalty in CROSS JOIN.",
    hint: "Generates massive network payloads and consumes server memory.",
    level: "basic"
  },
  {
    question: "What is the ultimate takeaway for database engineers regarding CROSS JOIN?",
    shortAnswer: "CROSS JOIN is the mathematical Cartesian Product ($M \\times N$) designed for generating combination matrixes (SKUs, dates, rosters); always use explicit `CROSS JOIN` syntax and verify row volumes to prevent accidental server crashes.",
    explanation: "Final summary conclusion for Topic 6 in Module 5.",
    hint: "Generates M × N combination matrices; use explicit ANSI syntax and monitor table sizes.",
    level: "basic"
  }
];

export default questions;
