// topic1_questions.js
// 30 FAQs on "What is an Operand?" – basic to expert.

const questions = [
  {
    question: "What is an operand?",
    shortAnswer: "An operand is a value, variable, or sub‑expression on which an operator acts.",
    explanation: "Operands are the data that operators use to produce a result. They can be literals, variables, or even other expressions.",
    hint: "Think of the numbers and variables in a math equation.",
    level: "basic",
    codeExample: "int x = 5 + 3; // 5 and 3 are operands",
  },
  {
    question: "What are the three common types of operands?",
    shortAnswer: "Literals, variables, and sub‑expressions.",
    explanation: "Literals are fixed values (e.g., 5, 3.14, true). Variables are named storage (e.g., count, total). Sub‑expressions are any expression used as part of a larger one (e.g., (a+b) in (a+b)*c).",
    hint: "Look at any expression and see what the operator is acting on.",
    level: "basic",
    codeExample: "int result = (2 + 3) * 4; // (2+3) is a sub‑expression operand",
  },
  {
    question: "Can a method call be an operand?",
    shortAnswer: "Yes, if the method returns a value, it can be used as an operand.",
    explanation: "For example, `Math.max(10, 20)` returns 20, so it can be an operand in `int result = Math.max(10, 20) + 5;`.",
    hint: "If it returns something, it can be used.",
    level: "intermediate",
    codeExample: "double avg = (sum + total) / 2.0; // sum and total are variables",
  },
  {
    question: "What is the difference between an operand and an operator?",
    shortAnswer: "An operand is the data; an operator is the operation performed on that data.",
    explanation: "In `a + b`, `a` and `b` are operands, `+` is the operator. Operands are the 'nouns', operators are the 'verbs'.",
    hint: "Operands receive the action, operators do the action.",
    level: "basic",
    codeExample: "// In 10 * 2, 10 and 2 are operands, * is the operator",
  },
  {
    question: "What happens if an operand is uninitialised?",
    shortAnswer: "In Java, using an uninitialised local variable causes a compile‑time error.",
    explanation: "Java requires that variables be assigned a value before they are read. This prevents bugs from using garbage values.",
    hint: "Always initialise your variables.",
    level: "intermediate",
    codeExample: "int x; // x not initialised\nint y = x + 5; // error: variable x might not have been initialised",
  },
  {
    question: "Can a boolean value be an operand?",
    shortAnswer: "Yes, boolean values (true/false) are valid operands, especially for logical operators.",
    explanation: "For example, in `isAdult && hasLicense`, both are boolean operands.",
    hint: "Any data type can be an operand.",
    level: "basic",
    codeExample: "boolean result = (age > 18) && (age < 65);",
  },
  {
    question: "What is an operand in the context of a unary operator?",
    shortAnswer: "A unary operator has exactly one operand (e.g., `-x`, `++i`).",
    explanation: "Unlike binary operators that need two operands, unary operators act on a single operand.",
    hint: "It's the single value being operated on.",
    level: "basic",
    codeExample: "int neg = -5; // 5 is the operand of -",
  },
  {
    question: "Can an expression itself be an operand?",
    shortAnswer: "Yes, sub‑expressions can be operands in larger expressions.",
    explanation: "For example, `(a + b) * c` has `(a + b)` as an operand of the multiplication.",
    hint: "Parentheses often enclose sub‑expressions that act as operands.",
    level: "intermediate",
    codeExample: "int total = (x + y) * z;",
  },
  {
    question: "What is the significance of operand types?",
    shortAnswer: "The types of operands determine the result type and whether implicit conversions occur.",
    explanation: "For example, `int + double` yields a `double` because the int is widened.",
    hint: "Watch out for integer division.",
    level: "intermediate",
    codeExample: "double d = 5 / 2; // 2.0 because both operands are ints",
  },
  {
    question: "What are the common pitfalls with operands?",
    shortAnswer: "Using uninitialised variables, mixing types unintentionally, and mis‑understanding precedence can cause bugs.",
    explanation: "Also, side‑effects from method calls used as operands can lead to unexpected behaviour.",
    hint: "Test each part of a complex expression separately.",
    level: "intermediate",
    codeExample: "// Pitfall: if (x = 5) // assignment, not comparison",
  },
  {
    question: "How do you declare a constant operand in Java?",
    shortAnswer: "Use the `final` keyword, e.g., `final double PI = 3.14159;`.",
    explanation: "Constants improve readability and prevent accidental modification.",
    hint: "Constants are often named in uppercase.",
    level: "basic",
    codeExample: "final int MAX_SCORE = 100;",
  },
  {
    question: "Can a string literal be an operand?",
    shortAnswer: "Yes, strings can be operands, especially with the `+` operator for concatenation.",
    explanation: "Example: `\"Hello, \" + name` – both are operands.",
    hint: "The `+` operator works differently for strings.",
    level: "basic",
    codeExample: "String greeting = \"Hi\" + \" \" + \"there\";",
  },
  {
    question: "What is a literal operand?",
    shortAnswer: "A literal operand is a fixed value written directly in code, like `10`, `3.14`, `'a'`, or `true`.",
    explanation: "They are the simplest form of operand because they don't require any computation.",
    hint: "Literals are self‑explanatory.",
    level: "basic",
    codeExample: "int age = 25; // 25 is a literal operand",
  },
  {
    question: "Can an array element be an operand?",
    shortAnswer: "Yes, an array element (e.g., `arr[0]`) is a valid operand.",
    explanation: "It evaluates to the value stored at that index.",
    hint: "Array accesses are expressions that yield a value.",
    level: "intermediate",
    codeExample: "int sum = arr[0] + arr[1];",
  },
  {
    question: "What is the role of operands in boolean expressions?",
    shortAnswer: "In boolean expressions, operands are conditions or booleans that evaluate to true/false.",
    explanation: "For example, in `x > 5 && y < 10`, `x > 5` and `y < 10` are boolean operands.",
    hint: "They are the questions we ask the program.",
    level: "basic",
    codeExample: "if (temperature > 30 && humidity < 80) { }",
  },
  {
    question: "Can a class field be an operand?",
    shortAnswer: "Yes, instance and static variables can be operands, e.g., `this.age`, `Math.PI`.",
    explanation: "They are accessed via the dot operator, but the field itself is an operand.",
    hint: "Fields can be used anywhere a variable is allowed.",
    level: "intermediate",
    codeExample: "double circumference = 2 * Math.PI * radius;",
  },
  {
    question: "What is the difference between a variable operand and a literal operand?",
    shortAnswer: "A variable operand refers to a value that may change; a literal operand has a fixed value.",
    explanation: "Variables are named storage locations; literals are constant values written directly.",
    hint: "Think of variables as containers, literals as the contents.",
    level: "basic",
    codeExample: "int x = 10; // x is a variable, 10 is a literal",
  },
  {
    question: "How does Java evaluate operands in an expression?",
    shortAnswer: "Java evaluates operands from left to right, with the exception of short‑circuiting for `&&` and `||`.",
    explanation: "In `a + b`, `a` is evaluated first, then `b`, then the addition.",
    hint: "Order of evaluation is important for side effects.",
    level: "intermediate",
    codeExample: "int result = a++ + b; // a is incremented after its value is used",
  },
  {
    question: "What is the 'operand stack' in a virtual machine?",
    shortAnswer: "The operand stack is a data structure used by bytecode interpreters to hold operands for operations.",
    explanation: "In JVM, each method has an operand stack; instructions pop operands and push results.",
    hint: "This is how expressions are evaluated at runtime.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "Can a method call have side effects that affect other operands?",
    shortAnswer: "Yes, if the method modifies shared state, the order of operand evaluation can impact the result.",
    explanation: "For example, if you call a method that increments a global counter, the final value depends on evaluation order.",
    hint: "Avoid side effects in expressions.",
    level: "advanced",
    codeExample: "int result = increment() + increment(); // order matters",
  },
  {
    question: "What are the best practices for naming operand variables?",
    shortAnswer: "Use descriptive, camelCase names that indicate the purpose (e.g., `totalPrice`, `isActive`).",
    explanation: "Good names make the code self‑documenting and easier to maintain.",
    hint: "Avoid single‑letter names except for loop counters.",
    level: "basic",
    codeExample: "int numberOfStudents; // good\nint ns; // not descriptive",
  },
  {
    question: "Can an operand be null?",
    shortAnswer: "Yes, reference type variables can be null, which is a valid value (though it may cause NullPointerException if dereferenced).",
    explanation: "Null is a literal operand representing a reference that points to nothing.",
    hint: "Always check for null before using an operand in a method call.",
    level: "intermediate",
    codeExample: "String name = null; // null is a literal operand",
  },
  {
    question: "What is a compile‑time constant operand?",
    shortAnswer: "An operand whose value is known at compile time, such as a literal or a final variable initialised with a constant expression.",
    explanation: "The compiler can replace these operands directly in the bytecode.",
    hint: "Constants are often used in `switch` cases.",
    level: "intermediate",
    codeExample: "final int MAX = 100 + 50; // MAX is a compile-time constant",
  },
  {
    question: "How do you ensure operands are of the correct type?",
    shortAnswer: "By declaring variables with appropriate types, using casting when needed, and checking method signatures.",
    explanation: "Type safety is a key feature of Java; the compiler enforces it.",
    hint: "Use `instanceof` to check types before casting.",
    level: "intermediate",
    codeExample: "if (obj instanceof String) { String s = (String) obj; }",
  },
  {
    question: "Can an operator have more than two operands?",
    shortAnswer: "No, operators in Java are either unary (one operand) or binary (two operands). The ternary operator `?:` has three operands.",
    explanation: "The conditional operator `? :` is the only ternary operator.",
    hint: "It's often called the ternary operator because it has three operands.",
    level: "basic",
    codeExample: "int max = (a > b) ? a : b; // a, b, and the result are operands",
  },
  {
    question: "What is the difference between an operand and an argument?",
    shortAnswer: "An operand is used with an operator; an argument is used with a method or constructor.",
    explanation: "Arguments are values passed to methods, while operands are values used by operators.",
    hint: "Both are inputs, but to different constructs.",
    level: "intermediate",
    codeExample: "int sum = a + b; // a and b are operands\nMath.max(a, b); // a and b are arguments",
  },
  {
    question: "Can a lambda expression be an operand?",
    shortAnswer: "Yes, a lambda expression can be an operand when assigned to a functional interface.",
    explanation: "For example, `Runnable r = () → System.out.println(\"Hi\");` – the lambda is the operand of the assignment.",
    hint: "Lambdas are treated as values.",
    level: "advanced",
    codeExample: "Comparator<String> comp = (s1, s2) → s1.compareTo(s2);",
  },
  {
    question: "What is the role of operands in polymorphism?",
    shortAnswer: "Operands of polymorphic types can refer to objects of subclasses, affecting method dispatch.",
    explanation: "When an operand is of a superclass type, the actual method called depends on the runtime object.",
    hint: "This is dynamic binding.",
    level: "advanced",
    codeExample: "Animal a = new Dog(); // a is an operand of type Animal",
  },
  {
    question: "How does Java handle operands of different numeric types?",
    shortAnswer: "Java performs binary numeric promotion: if one operand is double, the other becomes double; if float, then float; if long, then long; otherwise int.",
    explanation: "This ensures that both operands are of the same type before the operation.",
    hint: "Be aware of widening conversions.",
    level: "intermediate",
    codeExample: "double result = 5 / 2.0; // int 5 promoted to double",
  },
  {
    question: "What is the 'invokedynamic' operand?",
    shortAnswer: "Invokedynamic is a bytecode instruction used for dynamic method invocation, and its operands include a method handle and a call site.",
    explanation: "It's used in lambda expressions and dynamic languages on the JVM.",
    hint: "Advanced topic, but essential for understanding modern Java.",
    level: "expert",
    codeExample: "Not applicable",
  },
];

export default questions;