const questions = [
  {
    question: "What is mesh topology?",
    shortAnswer: "A network topology where devices are interconnected with multiple redundant links.",
    explanation: "In full mesh, every device connects to every other; in partial mesh, only critical devices are fully connected.",
    hint: "Think of a spider web of connections.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the difference between full mesh and partial mesh?",
    shortAnswer: "Full mesh connects every device to every other; partial mesh connects only selected devices.",
    explanation: "Full mesh is more redundant but expensive; partial mesh balances cost and reliability.",
    hint: "All vs. some connections.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How many connections are needed for a full mesh with n nodes?",
    shortAnswer: "n(n-1)/2 links.",
    explanation: "Each node connects to every other node; total links = n*(n-1)/2.",
    hint: "The formula for complete graph edges.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the advantage of mesh topology?",
    shortAnswer: "High redundancy and fault tolerance.",
    explanation: "Multiple paths ensure network continues even if several links fail.",
    hint: "No single point of failure.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the disadvantage of mesh topology?",
    shortAnswer: "High cost and complexity.",
    explanation: "Requires many cables, ports, and sophisticated routing.",
    hint: "Expensive and complicated.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a routing protocol and why is it needed in mesh?",
    shortAnswer: "A protocol that finds the best path through the mesh (e.g., OSPF, BGP).",
    explanation: "Mesh networks need dynamic routing to adapt to link failures.",
    hint: "The GPS for data.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is ECMP (Equal-Cost Multipath)?",
    shortAnswer: "A technique that distributes traffic across multiple equal-cost paths for load balancing.",
    explanation: "Improves performance and redundancy.",
    hint: "Using multiple roads for traffic.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is spine-leaf architecture?",
    shortAnswer: "A modern data center topology using a partial mesh with leaf (access) and spine (aggregation) switches.",
    explanation: "Every leaf connects to every spine, providing redundancy and high performance.",
    hint: "A two-layer mesh for data centers.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does a mesh network handle a link failure?",
    shortAnswer: "Routing protocols detect the failure and recalculate paths, rerouting traffic around it.",
    explanation: "Self-healing is a key feature of mesh networks.",
    hint: "Go around the break.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the impact of adding a node to a full mesh?",
    shortAnswer: "You must add connections to all existing nodes, increasing complexity and cost.",
    explanation: "The number of links grows quadratically.",
    hint: "Every new node needs a link to everyone.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "Why is partial mesh more common than full mesh?",
    shortAnswer: "Partial mesh provides a balance between redundancy and cost.",
    explanation: "Full mesh is too expensive and complex for most networks.",
    hint: "Good enough and cheaper.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of link-state routing protocols in mesh?",
    shortAnswer: "They maintain a map of the network and compute the best path using algorithms like Dijkstra.",
    explanation: "Examples: OSPF, IS-IS.",
    hint: "They know the whole map.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between mesh and star topology?",
    shortAnswer: "Mesh has multiple redundant paths; star has a central hub with single paths.",
    explanation: "Mesh is fault-tolerant; star is simple and cost-effective.",
    hint: "Many roads vs. one hub.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between mesh and ring topology?",
    shortAnswer: "Mesh has multiple paths; ring has only two paths (or one in single ring).",
    explanation: "Mesh is more redundant and complex.",
    hint: "Spider web vs. circular track.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a failure domain in mesh topology?",
    shortAnswer: "The scope of impact of a single link or node failure.",
    explanation: "In mesh, a single failure affects only that link; traffic reroutes.",
    hint: "The area affected by a failure.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the benefit of using fiber optics in mesh networks?",
    shortAnswer: "Fiber supports high speeds and long distances with low attenuation.",
    explanation: "Fiber is ideal for point-to-point links in mesh.",
    hint: "Fast, long-distance connections.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of BGP in mesh networks?",
    shortAnswer: "BGP (Border Gateway Protocol) exchanges routing information between autonomous systems, often in mesh topologies.",
    explanation: "BGP is used in the internet backbone, which is a global mesh.",
    hint: "The routing glue of the internet.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the concept of 'route diversity' in mesh?",
    shortAnswer: "Having multiple independent paths between the same source and destination.",
    explanation: "Route diversity improves reliability and load balancing.",
    hint: "Different roads to the same place.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is a 'cut-through' forwarding in mesh switches?",
    shortAnswer: "A switching technique that forwards packets as soon as the destination address is read, reducing latency.",
    explanation: "Used in high-performance data center switches.",
    hint: "Fast path through the switch.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the impact of latency in large mesh networks?",
    shortAnswer: "More hops can increase latency; careful design is needed.",
    explanation: "Routing protocols must balance path length and reliability.",
    hint: "More hops = more time.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does a mesh network achieve load balancing?",
    shortAnswer: "By using ECMP or policy-based routing to distribute traffic across multiple paths.",
    explanation: "This prevents congestion on any single link.",
    hint: "Splitting traffic across roads.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the difference between Layer 2 and Layer 3 mesh?",
    shortAnswer: "Layer 2 mesh uses MAC addresses (e.g., TRILL); Layer 3 uses IP addresses (routed).",
    explanation: "Layer 3 is more scalable and common in data centers.",
    hint: "Switched vs. routed.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is a 'spine' and 'leaf' switch in a data center?",
    shortAnswer: "Spine switches provide connectivity between leaf switches; leaf switches connect to servers.",
    explanation: "This creates a partial mesh for high performance.",
    hint: "The backbone and the access layer.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of automation in managing mesh networks?",
    shortAnswer: "Automation (e.g., SDN) helps configure, monitor, and troubleshoot complex mesh topologies.",
    explanation: "Mesh networks are too complex for manual management.",
    hint: "Software managing the web.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the concept of 'link aggregation' in mesh?",
    shortAnswer: "Combining multiple physical links into a logical link for higher bandwidth and redundancy.",
    explanation: "Example: LACP (Link Aggregation Control Protocol).",
    hint: "Merging lanes for more capacity.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does a mesh network handle broadcast traffic?",
    shortAnswer: "Broadcasts are flooded across the mesh, but protocols like IGMP snooping limit multicast.",
    explanation: "Flooding can cause inefficiencies; careful design needed.",
    hint: "Broadcasting to everyone.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the 'triangle inequality' in mesh routing?",
    shortAnswer: "The direct path between two nodes is not always the shortest in terms of cost (e.g., latency).",
    explanation: "Routing protocols consider multiple metrics.",
    hint: "A direct route may not be the fastest.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the significance of the 'degree' of a node in mesh?",
    shortAnswer: "The number of direct connections a node has. Higher degree = more redundancy.",
    explanation: "Critical nodes should have high degree.",
    hint: "How many friends it has.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the cost-benefit analysis for implementing mesh?",
    shortAnswer: "Assess downtime costs vs. mesh deployment cost; mesh is justified for critical operations.",
    explanation: "Financial institutions, healthcare, and cloud providers use mesh.",
    hint: "Is the cost worth the reliability?",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the future of mesh topology?",
    shortAnswer: "Mesh is evolving with SDN, AI-driven routing, and wireless mesh networks.",
    explanation: "Mesh concepts are being applied to IoT and wireless networks.",
    hint: "Mesh is here to stay, getting smarter.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;