// File: src/components/topics/topic6_files/topic6_questions.js
const questions = [
  {
    question: "What is a parity bit?",
    shortAnswer: "An extra bit added to a data block to make the total number of 1s either even or odd.",
    explanation: "The sender and receiver agree on the parity type (even or odd). The receiver checks the parity to detect single‑bit errors.",
    hint: "It's like a check digit for binary data.",
    level: "basic",
    codeExample: "// Python: parity = bin(data).count('1') % 2"
  },
  {
    question: "What is the difference between even parity and odd parity?",
    shortAnswer: "Even parity makes the total number of 1s even; odd parity makes it odd.",
    explanation: "Both work equally well; the choice is arbitrary but must be consistent across the communication link.",
    hint: "One makes the count even, the other odd.",
    level: "basic",
  },
  {
    question: "How many bit errors can a single parity bit detect?",
    shortAnswer: "It can detect any odd number of bit errors (1, 3, 5, ...). Even numbers of errors are undetected.",
    explanation: "Because flipping an even number of bits preserves the parity (even stays even, odd stays odd).",
    hint: "Parity detects odd error counts.",
    level: "moderate",
  },
  {
    question: "Can a single parity bit correct errors?",
    shortAnswer: "No. Parity only detects errors; it does not provide any information about which bit is wrong.",
    explanation: "To correct errors, you need additional redundant bits (like Hamming codes) that can pinpoint the error location.",
    hint: "Detection ≠ correction.",
    level: "basic",
  },
  {
    question: "Why is parity still used if it's so limited?",
    shortAnswer: "It's extremely simple, fast, and adds very little overhead (1 bit). It's useful in low‑error‑rate environments or as an initial check.",
    explanation: "Many hardware UARTs implement parity in hardware with virtually no performance penalty. It's also a good educational tool.",
    hint: "Sometimes simple is enough.",
    level: "moderate",
  },
  {
    question: "What does the phrase 'parity is a weak error detection method' mean?",
    shortAnswer: "It means that parity cannot detect even numbers of bit flips, and its detection capability is limited compared to more sophisticated methods like CRC.",
    explanation: "For example, two bit flips can cancel out the parity. In contrast, CRC detects many more error patterns.",
    hint: "Weak = many errors go undetected.",
    level: "moderate",
  },
  {
    question: "In RS‑232 serial communication, what does 'parity none' mean?",
    shortAnswer: "No parity bit is transmitted; the frame consists only of start bit, data bits, and stop bits.",
    explanation: "When parity is 'none', error detection is left to higher layers or not performed at all.",
    hint: "No extra bit for checking.",
    level: "basic",
  },
  {
    question: "How does two‑dimensional parity improve upon single parity?",
    shortAnswer: "It adds parity bits for rows and columns, allowing detection (and correction) of single‑bit errors and detection of many multi‑bit errors.",
    explanation: "Two‑dimensional parity is a simple block code that can pinpoint a single error by the intersection of a bad row and bad column.",
    hint: "More redundancy = stronger detection.",
    level: "moderate",
  },
  {
    question: "What is the 'parity check' in a receiver?",
    shortAnswer: "The receiver counts the number of 1s in the received bits (including the parity bit) and compares it with the expected parity type.",
    explanation: "If the count matches the agreed parity (even or odd), the frame is assumed error‑free; otherwise, an error is flagged.",
    hint: "It's a simple verification step.",
    level: "basic",
  },
  {
    question: "What happens if the parity bit itself is corrupted?",
    shortAnswer: "The parity check will fail, and the receiver will assume an error in the data (even though only the parity bit flipped).",
    explanation: "The parity bit is part of the transmitted word, so any error in it will cause a parity mismatch, triggering an error response (e.g., requesting retransmission).",
    hint: "A bad parity bit acts like a data error.",
    level: "moderate",
  },
  {
    question: "Why do some communication protocols use parity with 'mark' or 'space' parity?",
    shortAnswer: "Mark parity sets the parity bit always to 1; space parity sets it always to 0. These are non‑checking modes, used for compatibility or to indicate a specific state.",
    explanation: "They are not used for error detection; they provide a fixed bit value that may be used for other purposes (e.g., as a simple identifier).",
    hint: "Mark = 1, space = 0 – no checking.",
    level: "expert",
  },
  {
    question: "What is the parity of the binary number 1101 (with even parity)?",
    shortAnswer: "The parity bit is 1 because there are three 1s (odd), so we add 1 to make four (even).",
    explanation: "Count ones: 1+1+0+1 = 3 (odd). Even parity requires even count, so add 1.",
    hint: "Count ones, then decide.",
    level: "basic",
  },
  {
    question: "If a receiver expects odd parity and receives 10110, is the frame valid?",
    shortAnswer: "Count 1s: 1+0+1+1+0 = 3 (odd). Since odd parity is expected, the frame is valid (no single‑bit error detected).",
    explanation: "The receiver's parity check passes, so it assumes the data is correct (though there could be undetected errors).",
    hint: "Check parity type.",
    level: "moderate",
  },
  {
    question: "Can parity be used to detect a burst error of length 2?",
    shortAnswer: "Not always. A burst of two errors may flip two bits; if they are both 1→0 or 0→1, the parity may remain unchanged. However, if one flips 0→1 and the other 1→0, the parity could still be preserved.",
    explanation: "Parity is not designed for burst errors; it only guarantees detection of single‑bit errors and some odd‑count errors.",
    hint: "Bursts often have multiple errors; parity may miss them.",
    level: "expert",
  },
  {
    question: "How is parity implemented in hardware?",
    shortAnswer: "A parity generator/checker is typically a XOR tree: the XOR of all data bits yields the parity (for even parity).",
    explanation: "An XOR tree combines the bits using XOR gates; the output is 1 if an odd number of inputs are 1. This is very fast in hardware.",
    hint: "XOR is the hardware equivalent of 'odd count'.",
    level: "expert",
    codeExample: "// Verilog: parity = ^data; // XOR reduction"
  },
  {
    question: "What is 'parity bit' in the context of RAID?",
    shortAnswer: "In RAID 3, 4, and 5, a parity bit (or block) is stored on a dedicated disk or distributed across disks to enable recovery from a single disk failure.",
    explanation: "The parity is computed by XORing the data across disks. If one disk fails, the data can be reconstructed by XORing the remaining disks with the parity.",
    hint: "RAID uses parity for fault tolerance.",
    level: "moderate",
  },
  {
    question: "What is the difference between a parity bit and a checksum?",
    shortAnswer: "A parity bit is a single‑bit, simple even/odd check. A checksum is a multi‑bit sum (or other function) that provides stronger detection.",
    explanation: "Checksums (e.g., 16‑bit) can detect more error patterns, including some multiple‑bit errors that parity would miss.",
    hint: "Checksum is more complex and powerful.",
    level: "moderate",
  },
  {
    question: "What is the main disadvantage of using parity in high‑speed networks?",
    shortAnswer: "It provides insufficient error detection for modern networks; it cannot detect many common error patterns, so higher‑layer protocols would still need to catch errors.",
    explanation: "High‑speed links have higher bit error rates and burst errors; parity is too weak. CRC is typically used at the link layer.",
    hint: "Too weak for high reliability needs.",
    level: "expert",
  },
  {
    question: "How can you compute odd parity from even parity?",
    shortAnswer: "Odd parity is the complement of even parity. If you compute even parity (1 for odd number of ones), odd parity is the inverse.",
    explanation: "If the data has an odd number of ones, even parity would be 1; odd parity would be 0 to make the total odd (odd + 0 = odd).",
    hint: "Just flip the bit.",
    level: "basic",
  },
  {
    question: "What does 'parity error' mean on a serial port?",
    shortAnswer: "It means the received data did not match the expected parity, indicating a transmission error (likely due to noise or misconfiguration).",
    explanation: "The UART detects this and may set a status flag; the driver can report it as a framing or parity error.",
    hint: "Mismatch between received and expected parity.",
    level: "moderate",
  },
  {
    question: "Can parity be used for error detection in a packet that also uses CRC?",
    shortAnswer: "Yes, but it would be redundant. CRC already provides strong detection, so parity is unnecessary and adds overhead.",
    explanation: "Typically, you use either parity (for very simple links) or CRC (for robust links). Using both is wasteful.",
    hint: "No need for two checks.",
    level: "moderate",
  },
  {
    question: "What is a 'parity generator' in digital logic?",
    shortAnswer: "A circuit that takes n input bits and outputs a single parity bit (the XOR of all inputs).",
    explanation: "It can be built using cascaded XOR gates. For even parity, the output is the XOR; for odd parity, it's the inverted XOR.",
    hint: "XOR tree.",
    level: "expert",
  },
  {
    question: "What is a 'parity checker' in digital logic?",
    shortAnswer: "A circuit that receives n bits (data + parity) and outputs a single bit indicating whether parity is correct.",
    explanation: "It computes the XOR of all n bits. If the result is 0 (for even parity) or 1 (for odd parity), the parity is correct.",
    hint: "Same XOR tree, just interpreted differently.",
    level: "expert",
  },
  {
    question: "Why doesn't TCP use a parity bit?",
    shortAnswer: "TCP uses a 16‑bit checksum, which is far more robust than a single parity bit.",
    explanation: "The checksum covers the entire segment and can detect many more error patterns. Parity would be insufficient for internet‑scale reliability.",
    hint: "Checksum is the standard.",
    level: "basic",
  },
  {
    question: "In ASCII transmission with 7‑bit data and parity, what is the total number of bits per character?",
    shortAnswer: "Usually 8 bits: 7 data bits + 1 parity bit (plus start and stop bits for asynchronous serial).",
    explanation: "This is common in serial communications where each character is transmitted as a frame.",
    hint: "7+1=8.",
    level: "basic",
  },
  {
    question: "What is the significance of the parity bit in magnetic tape storage?",
    shortAnswer: "Older tape drives used parity to detect read errors; if a parity error occurred, the block could be reread.",
    explanation: "This provided basic reliability before more advanced ECC was adopted.",
    hint: "Historical reliability.",
    level: "moderate",
  },
  {
    question: "Can a parity bit detect an error if the data and parity are both corrupted in a way that parity remains correct?",
    shortAnswer: "Yes, that's exactly the limitation: if the total number of flipped bits is even, parity remains unchanged, and the error is undetected.",
    explanation: "For example, if data changes from 1011 to 1000 (two flips) and parity changes from 1 to 0 (one flip), total flips = 3 (odd) would be detected. But if data flips two bits and parity also flips, total flips = 3 or 4; if total flips is even, it's undetected.",
    hint: "Even number of flips → undetected.",
    level: "expert",
  },
  {
    question: "What is the formula to compute even parity for a byte?",
    shortAnswer: "Even parity = XOR of all 8 bits. It is 1 if the number of 1s is odd, 0 if even.",
    explanation: "In C: `parity = data ^ (data >> 4); parity ^= parity >> 2; parity ^= parity >> 1; parity &= 1;` but often a simple loop is used.",
    hint: "XOR all bits.",
    level: "moderate",
  },
  {
    question: "What is the difference between 'parity' and 'checksum' in terms of overhead?",
    shortAnswer: "Parity adds only 1 bit per block; checksum adds multiple bits (e.g., 16 bits) per block.",
    explanation: "Parity is very low overhead but weak; checksum is higher overhead but stronger.",
    hint: "1 bit vs 16 bits.",
    level: "basic",
  },
  {
    question: "Why is parity not used in modern Ethernet?",
    shortAnswer: "Ethernet uses a 32‑bit CRC (Frame Check Sequence) for robust error detection, which is far more reliable.",
    explanation: "Parity would be insufficient for the high‑speed, error‑prone environment of Ethernet. CRC can detect burst errors and many other patterns.",
    hint: "CRC is much stronger.",
    level: "moderate",
  }
];

export default questions;