// topic9_questions.js
// 30 FAQs on "Prefix Expression" – basic to expert.

const questions = [
  {
    question: "What is a prefix expression?",
    shortAnswer: "An expression where the operator appears before its operands.",
    explanation: "Also known as Polish notation. Example: `+ A B`.",
    hint: "Operator first.",
    level: "basic",
    codeExample: "+ 2 3",
  },
  {
    question: "What is another name for prefix notation?",
    shortAnswer: "Polish notation.",
    explanation: "Named after the Polish logician Jan Łukasiewicz.",
    hint: "Think of the nationality.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "Why is prefix notation useful?",
    shortAnswer: "It eliminates the need for parentheses and precedence rules.",
    explanation: "The order of operations is determined by the position of operators.",
    hint: "Unambiguous.",
    level: "basic",
    codeExample: "+ 2 3",
  },
  {
    question: "How do you evaluate a prefix expression?",
    shortAnswer: "Scan from right to left, using a stack.",
    explanation: "Push operands, and when an operator is encountered, pop operands and push the result.",
    hint: "Right-to-left with stack.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What is the prefix form of `A + B`?",
    shortAnswer: "+ A B",
    explanation: "Operator '+' comes before operands A and B.",
    hint: "Operator first.",
    level: "basic",
    codeExample: "+ A B",
  },
  {
    question: "What is the prefix form of `(A + B) * C`?",
    shortAnswer: "* + A B C",
    explanation: "The addition is inside the multiplication.",
    hint: "Inner operation first.",
    level: "intermediate",
    codeExample: "* + A B C",
  },
  {
    question: "What is the prefix form of `A * B + C`?",
    shortAnswer: "+ * A B C",
    explanation: "Multiplication before addition due to precedence.",
    hint: "Higher precedence first.",
    level: "intermediate",
    codeExample: "+ * A B C",
  },
  {
    question: "What is the prefix form of `A + B * C`?",
    shortAnswer: "+ A * B C",
    explanation: "Multiplication first, then addition.",
    hint: "Precedence.",
    level: "intermediate",
    codeExample: "+ A * B C",
  },
  {
    question: "Does prefix notation require parentheses?",
    shortAnswer: "No, parentheses are never needed.",
    explanation: "The operator position eliminates ambiguity.",
    hint: "Not needed.",
    level: "basic",
    codeExample: "+ 2 3",
  },
  {
    question: "Which programming languages use prefix notation?",
    shortAnswer: "Lisp family languages (Scheme, Clojure, Common Lisp).",
    explanation: "All expressions are prefix in Lisp.",
    hint: "Think of parentheses-heavy languages.",
    level: "intermediate",
    codeExample: "(+ 2 3)",
  },
  {
    question: "How do you convert infix to prefix?",
    shortAnswer: "Reverse the infix expression, swap parentheses, then apply infix-to-postfix and reverse.",
    explanation: "There's a standard algorithm using stacks.",
    hint: "It's a multi-step process.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "What is the difference between prefix and postfix?",
    shortAnswer: "Prefix has operator before operands; postfix has operator after operands.",
    explanation: "They are mirror images in terms of operator position.",
    hint: "Before vs after.",
    level: "basic",
    codeExample: "Prefix: + A B; Postfix: A B +",
  },
  {
    question: "What is the evaluation order for prefix?",
    shortAnswer: "Typically right-to-left.",
    explanation: "Operands are evaluated first, then operators.",
    hint: "Scan from right.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "Can you evaluate prefix with a single stack?",
    shortAnswer: "Yes, using a stack and scanning right-to-left.",
    explanation: "Push operands, apply operators when encountered.",
    hint: "One stack is enough.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What is the time complexity of evaluating prefix?",
    shortAnswer: "O(n) where n is the number of tokens.",
    explanation: "Each token is processed once.",
    hint: "Linear.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What are the advantages of prefix over infix?",
    shortAnswer: "No precedence, no parentheses, easier for machines.",
    explanation: "Evaluation is straightforward with a stack.",
    hint: "Machine-friendly.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What are the disadvantages of prefix for humans?",
    shortAnswer: "It's less intuitive and harder to read for complex expressions.",
    explanation: "Humans are trained to read infix.",
    hint: "Not human-friendly.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "How do you handle unary operators in prefix?",
    shortAnswer: "They are written before the operand, just like binary operators.",
    explanation: "Example: `- 5` or `! true`.",
    hint: "Same as binary.",
    level: "advanced",
    codeExample: "- 5",
  },
  {
    question: "What is the prefix representation of `-5`?",
    shortAnswer: "- 5",
    explanation: "Unary minus operator before operand.",
    hint: "Operator first.",
    level: "intermediate",
    codeExample: "- 5",
  },
  {
    question: "What is the prefix form of `a > b && c < d`?",
    shortAnswer: "&& > a b < c d",
    explanation: "Each relational is prefix, then the logical AND.",
    hint: "Convert each part.",
    level: "advanced",
    codeExample: "&& > a b < c d",
  },
  {
    question: "Is prefix notation used in compilers?",
    shortAnswer: "Yes, sometimes as an intermediate representation.",
    explanation: "It simplifies code generation and optimization.",
    hint: "Used internally.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "What is the prefix form of `A + B * C + D`?",
    shortAnswer: "+ + A * B C D",
    explanation: "Left-to-right: A + (B*C) + D.",
    hint: "Associativity.",
    level: "advanced",
    codeExample: "+ + A * B C D",
  },
  {
    question: "How does prefix handle associativity?",
    shortAnswer: "The order of operands in the prefix expression reflects the evaluation order.",
    explanation: "Left‑associative operators are placed accordingly.",
    hint: "Operator position decides.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "Can you convert prefix to infix easily?",
    shortAnswer: "Yes, using a stack and the reverse process.",
    explanation: "Scan from right to left, combine operands with operators.",
    hint: "Reverse of evaluation.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What is the prefix form of `(A+B)*(C-D)`?",
    shortAnswer: "* + A B - C D",
    explanation: "Each parenthesized sub-expression is converted to prefix.",
    hint: "Inner first.",
    level: "intermediate",
    codeExample: "* + A B - C D",
  },
  {
    question: "Is prefix notation commonly used in mathematical textbooks?",
    shortAnswer: "No, textbooks use infix.",
    explanation: "Prefix is mainly used in computer science contexts.",
    hint: "Mostly academic.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What is the role of whitespace in prefix?",
    shortAnswer: "Whitespace is used to separate tokens (operators and operands).",
    explanation: "Without whitespace, parsing becomes ambiguous.",
    hint: "Use spaces.",
    level: "basic",
    codeExample: "+ 2 3",
  },
  {
    question: "Can prefix expressions be nested?",
    shortAnswer: "Yes, operands can be sub-expressions.",
    explanation: "Example: `+ 2 (* 3 4)`.",
    hint: "Nesting allowed.",
    level: "intermediate",
    codeExample: "+ 2 * 3 4",
  },
  {
    question: "What is the prefix form of `2 + 3 * 4`?",
    shortAnswer: "+ 2 * 3 4",
    explanation: "Multiplication first.",
    hint: "Precedence.",
    level: "intermediate",
    codeExample: "+ 2 * 3 4",
  },
  {
    question: "What is the prefix form of `(2 + 3) * 4`?",
    shortAnswer: "* + 2 3 4",
    explanation: "Parentheses force addition first.",
    hint: "Parentheses override.",
    level: "intermediate",
    codeExample: "* + 2 3 4",
  },
];

export default questions;