const questions = [
  {
    question: "What is a peer-to-peer (P2P) network?",
    shortAnswer: "A decentralized network where each node acts as both client and server.",
    explanation: "Peers share resources directly without a central authority, making P2P scalable and resilient.",
    hint: "Think of a group of people sharing files directly, not through a central server.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does P2P differ from client-server?",
    shortAnswer: "P2P has no central server; client-server has a dedicated server.",
    explanation: "In client-server, clients request services from servers; in P2P, each peer provides and consumes.",
    hint: "One has a boss, the other is a flat hierarchy.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are some examples of P2P networks?",
    shortAnswer: "BitTorrent, Bitcoin, IPFS, and some messaging apps (Matrix).",
    explanation: "These systems use P2P for file sharing, cryptocurrency, and decentralized communication.",
    hint: "File sharing and digital currency.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a key advantage of P2P networks?",
    shortAnswer: "Scalability – more peers add more resources.",
    explanation: "Unlike client-server, where the server is a bottleneck, P2P distributes load across peers.",
    hint: "The network gets faster as more users join.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a disadvantage of P2P networks?",
    shortAnswer: "Security risks – peers may be malicious.",
    explanation: "Without central authority, verifying trust is challenging.",
    hint: "Anyone can join and potentially cause harm.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the role of a tracker in BitTorrent?",
    shortAnswer: "A tracker helps peers discover each other by keeping a list of active peers.",
    explanation: "Trackers are used in first-generation P2P; newer systems use DHT.",
    hint: "A directory of who's online.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is DHT (Distributed Hash Table)?",
    shortAnswer: "A decentralized key-value store used for peer discovery without central servers.",
    explanation: "DHT is used in modern P2P systems like BitTorrent and IPFS.",
    hint: "A distributed phonebook.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does P2P handle peer churn?",
    shortAnswer: "By using redundancy and replication; peers can come and go without affecting availability.",
    explanation: "Files are split into pieces and distributed; even if some peers leave, others have the pieces.",
    hint: "No single peer is essential.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a 'leecher' and 'seeder' in BitTorrent?",
    shortAnswer: "A leecher is downloading; a seeder has completed the download and is uploading.",
    explanation: "The swarm relies on seeders for content availability.",
    hint: "Seeders are generous; leechers are consumers.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a 'supernode' in P2P?",
    shortAnswer: "A peer with higher capacity that acts as a coordinator for other peers.",
    explanation: "Supernodes improve efficiency by handling more queries and routing.",
    hint: "A more powerful peer.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does Bitcoin use P2P?",
    shortAnswer: "Bitcoin nodes form a P2P network to validate transactions and maintain a shared ledger (blockchain).",
    explanation: "No central bank – consensus is reached through mining and node validation.",
    hint: "A decentralized ledger.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is IPFS and how is it P2P?",
    shortAnswer: "IPFS (InterPlanetary File System) is a P2P hypermedia protocol for decentralized file storage.",
    explanation: "Files are addressed by content hash, and peers store and serve pieces.",
    hint: "A distributed web.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is NAT traversal and why is it important in P2P?",
    shortAnswer: "NAT traversal allows peers behind routers to establish direct connections.",
    explanation: "Techniques like STUN, TURN, and UDP hole-punching overcome firewalls.",
    hint: "Getting through the firewall.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do P2P networks manage trust and reputation?",
    shortAnswer: "Through reputation systems, where peers rate each other's behavior.",
    explanation: "Reputation helps mitigate malicious peers in some systems (e.g., eDonkey).",
    hint: "Rating other users.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between first and second generation P2P?",
    shortAnswer: "First generation (Napster) used central index; second generation (BitTorrent) uses DHT/trackers.",
    explanation: "Second generation is more decentralized and resilient.",
    hint: "Centralized vs. fully decentralized.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a P2P overlay network?",
    shortAnswer: "A virtual network built on top of the internet, where peers are logical nodes.",
    explanation: "Overlay networks define routing and discovery mechanisms (e.g., Chord, Kademlia).",
    hint: "A network on top of the network.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of encryption in P2P?",
    shortAnswer: "Encryption secures data in transit and provides privacy for peers.",
    explanation: "Used to protect against eavesdropping and content theft.",
    hint: "Locking your data while it travels.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a 'sybil attack' in P2P?",
    shortAnswer: "An attack where a single adversary creates many fake identities to control the network.",
    explanation: "Sybil attacks undermine trust and reputation systems.",
    hint: "Fake identities taking over.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does P2P achieve fault tolerance?",
    shortAnswer: "By distributing data and responsibilities across many peers, so no single failure brings down the system.",
    explanation: "Replication and redundancy are key.",
    hint: "No single point of failure.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is a 'gossip protocol' in P2P?",
    shortAnswer: "A protocol where peers periodically exchange information to propagate updates.",
    explanation: "Used for membership and state synchronization.",
    hint: "Spreading rumors.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the difference between structured and unstructured P2P overlays?",
    shortAnswer: "Structured overlays (e.g., Chord) have organized topology; unstructured are random (e.g., Gnutella).",
    explanation: "Structured is efficient for lookups; unstructured is simpler.",
    hint: "Organized vs. random.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do P2P networks handle Byzantine faults?",
    shortAnswer: "Using consensus algorithms (e.g., Proof-of-Work) to reach agreement despite malicious nodes.",
    explanation: "Bitcoin's blockchain is a famous solution.",
    hint: "Agreement even with bad actors.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the 'tragedy of the commons' in P2P?",
    shortAnswer: "Peers may take more than they give, degrading the network.",
    explanation: "Incentive mechanisms (e.g., tit-for-tat in BitTorrent) mitigate this.",
    hint: "People don't contribute enough.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does P2P enable censorship resistance?",
    shortAnswer: "No central point to shut down; content is distributed across many peers.",
    explanation: "Censors cannot easily remove content from a decentralized network.",
    hint: "Hard to silence.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of 'choking' and 'unchoking' in BitTorrent?",
    shortAnswer: "Choking temporarily stops uploading to a peer; unchoking resumes, based on reciprocity.",
    explanation: "This optimizes bandwidth and encourages sharing.",
    hint: "Taking turns.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are the challenges of building a P2P application for mobile devices?",
    shortAnswer: "Limited battery, network volatility, and NAT restrictions.",
    explanation: "Mobile P2P requires efficient protocols and adaptive strategies.",
    hint: "Battery life and connectivity.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does a P2P network manage IP address changes?",
    shortAnswer: "Using stable identifiers (e.g., peer IDs) and periodic announcements.",
    explanation: "DHTs use consistent hashing to maintain stability.",
    hint: "Peers don't stay at the same IP.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the impact of network latency on P2P performance?",
    shortAnswer: "High latency increases lookup times and file transfer delays.",
    explanation: "Proximity-aware routing can mitigate this.",
    hint: "Slow connections slow everything down.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the future of P2P in Web3?",
    shortAnswer: "Decentralized storage, identity, and applications will rely on P2P networks.",
    explanation: "Web3 aims to shift power from corporations to users.",
    hint: "The next generation of the internet.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do P2P networks handle packet loss?",
    shortAnswer: "Using redundancy and retransmission at the application layer.",
    explanation: "P2P applications often use UDP and implement their own reliability.",
    hint: "Don't rely on TCP.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;