/**
 * Topic 0: The Concept of Merging: Integrating divergent histories
 * Module: 002_002_merging-strategies-and-conflict-resolution
 * Instructor: Sukanta Hui (Coder & AccoTax, Barrackpore)
 */

const questions = [
  {
    id: 1,
    question: "What is the primary purpose of merging in Git?",
    answer: "Merging integrates changes from one branch (the incoming branch) into another branch (the target branch currently checked out), unifying divergent lines of development."
  },
  {
    id: 2,
    question: "Which branch must you be currently checked out on when executing `git merge <feature>`?",
    answer: "You must be on the TARGET receiving branch (e.g. `main` or `develop`). Git always merges the incoming branch INTO your active HEAD branch."
  },
  {
    id: 3,
    question: "What are the three essential commit nodes Git analyzes during a merge?",
    answer: "1. The common ancestor commit (Merge Base)\n2. The current active branch tip commit (HEAD / 'ours')\n3. The incoming branch tip commit ('theirs')."
  },
  {
    id: 4,
    question: "What is a Fast-Forward (FF) merge?",
    answer: "A merge that occurs when the target branch has not added any new commits since the feature branch was created. Git simply advances the target branch pointer forward to match the feature tip without creating a new merge commit."
  },
  {
    id: 5,
    question: "What is a Three-Way (3-Way) merge in Git?",
    answer: "A merge that occurs when both branches have diverged with new independent commits since their common ancestor. Git computes changes from the merge base and creates a new merge commit with two parents."
  },
  {
    id: 6,
    question: "Does `git merge feature` modify the `feature` branch itself?",
    answer: "No. The `feature` branch pointer remains completely unchanged at its current commit. Only the target branch (e.g. `main`) is updated."
  },
  {
    id: 7,
    question: "What is a 'merge commit'?",
    answer: "A special commit object created during a non-fast-forward or 3-way merge that contains references to two (or more) parent commits."
  },
  {
    id: 8,
    question: "Why is it important to ensure your working directory is clean before merging?",
    answer: "Uncommitted local modifications can conflict with incoming changes, leading Git to abort the merge to prevent overwriting unstaged work."
  },
  {
    id: 9,
    question: "What command can check your working tree status before initiating a merge?",
    answer: "`git status`."
  },
  {
    id: 10,
    question: "What happens if both branches modified different files or different lines of the same file?",
    answer: "Git automatically combines the changes cleanly and completes the merge without requiring human intervention."
  },
  {
    id: 11,
    question: "What happens if both branches modified the exact same lines in the same file differently?",
    answer: "Git halts the automatic merge process and triggers a 'Merge Conflict', inserting conflict markers into the affected files for manual resolution."
  },
  {
    id: 12,
    question: "What command can cancel an in-progress merge and return your repository to its exact pre-merge state?",
    answer: "`git merge --abort`."
  },
  {
    id: 13,
    question: "Can you merge multiple branches simultaneously into the current branch (Octopus Merge)?",
    answer: "Yes: `git merge branch1 branch2 branch3` creates an Octopus merge commit with more than two parents, provided there are no conflicts."
  },
  {
    id: 14,
    question: "What flag prevents a fast-forward merge and forces Git to create an explicit merge commit?",
    answer: "`git merge --no-ff <branch-name>`."
  },
  {
    id: 15,
    question: "What flag requires that a merge MUST be fast-forward, aborting if a merge commit would be needed?",
    answer: "`git merge --ff-only <branch-name>`."
  },
  {
    id: 16,
    question: "How does `git merge --squash <branch>` differ from a standard merge?",
    answer: "`git merge --squash` combines all changes from the feature branch into a single staged modification in your working tree without preserving individual commit history."
  },
  {
    id: 17,
    question: "What is the default merge commit message generated by Git?",
    answer: "`Merge branch '<incoming-branch-name>'` (or `Merge branch 'feature' into main`)."
  },
  {
    id: 18,
    question: "How can you specify a custom commit message during a merge?",
    answer: "`git merge -m \"feat: integrate new billing engine v2.0\" feature`."
  },
  {
    id: 19,
    question: "How do you preview the diff of what will be merged before actually running `git merge`?",
    answer: "`git diff HEAD...<incoming-branch>` (three-dot diff from merge base)."
  },
  {
    id: 20,
    question: "What default merge strategy does modern Git (2.33+) use?",
    answer: "The `ort` (Ostensibly Recursive's Twin) merge strategy, which replaced the older `recursive` strategy with superior speed and conflict handling."
  },
  {
    id: 21,
    question: "Where does Git record the in-progress merge state before the merge commit is completed?",
    answer: "Inside `.git/MERGE_HEAD` (storing the incoming commit SHA) and `.git/MERGE_MSG`."
  },
  {
    id: 22,
    question: "What happens to `.git/MERGE_HEAD` once a merge commit is successfully finalized?",
    answer: "Git automatically removes `.git/MERGE_HEAD`, signaling that the repository has returned to a normal, clean state."
  },
  {
    id: 23,
    question: "Can you delete a feature branch immediately after merging it into `main`?",
    answer: "Yes: `git branch -d <feature-branch>` safely prunes the branch pointer because all its commits are now reachable from `main`."
  },
  {
    id: 24,
    question: "How did Sukanta Hui explain Git merging to students Sachin and Mahima at AccoTax Barrackpore?",
    answer: "He compared merging to two junior accountants drafting separate sections of a company tax audit (one on GST slabs, the other on TDS deductions) and then compiling them into the master ledger under the chief auditor's supervision."
  },
  {
    id: 25,
    question: "What command displays a graphical ASCII tree of merged and diverged histories?",
    answer: "`git log --graph --oneline --decorate --all`."
  }
];

export default questions;
