const practiceQuestions = [
    { q: "What is the worst-case time complexity of linear search?", a: "O(n)", explanation: "In the worst case, the target is at the end or not present, requiring a scan of all n elements." },
    { q: "What is the time complexity of binary search?", a: "O(log n)", explanation: "Each step halves the search space, so the number of steps is log₂(n). For 1 million elements, only about 20 comparisons." },
    { q: "What must be true about an array before using binary search?", a: "It must be sorted.", explanation: "Binary search relies on the property that all elements left of mid are smaller and all right are larger. Without sorting, the algorithm cannot decide which half to search." },
    { q: "Write the iterative binary search loop condition.", a: "while (low <= high)", explanation: "The loop continues as long as the search range is non-empty. When low > high, the target is not in the array." },
    { q: "How do you calculate mid to avoid integer overflow?", a: "mid = low + (high - low) / 2", explanation: "Using (low + high) / 2 can overflow for very large arrays. The alternative expression is mathematically equivalent and safe." },
    { q: "What does Arrays.binarySearch() return if element is not found?", a: "-(insertion point) - 1", explanation: "The insertion point is the index where the element would be inserted to maintain sorted order. The negative value indicates 'not found' and also provides the insertion position via -(result + 1)." },
    { q: "For an array of 1,048,576 elements, how many steps max for binary search?", a: "20 (2^20 = 1,048,576)", explanation: "Binary search takes at most floor(log₂(n)) + 1 steps. Since 2^20 = 1,048,576, the maximum steps is 20." },
    { q: "Which search algorithm works on unsorted data?", a: "Linear search", explanation: "Linear search does not require any ordering; it simply checks each element in sequence." },
    { q: "What is the best-case time complexity of linear search?", a: "O(1)", explanation: "If the target is the first element, only one comparison is needed." },
    { q: "What is the space complexity of iterative binary search?", a: "O(1)", explanation: "Only a few integer variables (low, high, mid) are used, regardless of array size." },
    { q: "What happens if you run binary search on an unsorted array?", a: "Incorrect result (may return -1 even if element exists).", explanation: "Binary search assumes sorted order; on unsorted data, the mid comparison is meaningless, leading to wrong decisions and potentially missing the target." },
    { q: "Write the code to find the first occurrence of a duplicate using binary search.", a: "When arr[mid] == target, store index and set high = mid - 1.", explanation: "After finding a match, continue searching in the left half to find an earlier occurrence. Store the index each time and finally return the leftmost." },
    { q: "What is the worst-case number of comparisons for binary search on n elements?", a: "⌊log₂(n)⌋ + 1", explanation: "In the worst case, the target is found at the last step or not found at all. Each comparison reduces the range by half, leading to this count." },
    { q: "Can binary search be used on a linked list? Why?", a: "Not efficiently, because random access is O(n).", explanation: "Binary search requires O(1) access to the middle element. Linked lists require traversal to reach the middle, making the algorithm O(n log n) – worse than linear search." },
    { q: "What method in Java performs binary search on an array?", a: "Arrays.binarySearch()", explanation: "Part of java.util.Arrays, it provides optimized binary search for primitive arrays and objects." },
    { q: "Write the recursive binary search base case.", a: "if (low > high) return -1;", explanation: "When the search range becomes empty (low > high), the target is not present. This terminates the recursion." },
    { q: "What is the advantage of linear search over binary search?", a: "Works on unsorted data, simpler, better for small arrays.", explanation: "Linear search has no preprocessing cost and is simpler to implement. For tiny arrays, its constant factors can beat binary search." },
    { q: "How many comparisons for linear search on 1,000,000 elements worst-case?", a: "1,000,000", explanation: "If the target is last or absent, linear search examines every element." },
    { q: "What is the insertion point in binary search when element not found?", a: "The index where the element would be inserted to maintain sorted order.", explanation: "Arrays.binarySearch() returns -(insertionPoint)-1. The insertion point is the first index where arr[index] > target (or arr.length if all elements are smaller)." },
    { q: "Write the condition to search in the right half of a binary search.", a: "if (arr[mid] < target) low = mid + 1;", explanation: "If the middle element is less than the target, all elements left of mid are even smaller, so the target must be in the right half." }
];

export default practiceQuestions;