const questions = [
  {
    question: "What is the technical distinction between Eavesdropping and Wiretapping in network security?",
    shortAnswer: "Eavesdropping is the general unauthorized listening or sniffing of communications (logical/software level), while Wiretapping specifically involves physical or electrical tapping into the communication medium (hardware/physical level).",
    explanation: "Eavesdropping encompasses software-based packet sniffing (e.g. running tcpdump in promiscuous mode or capturing unencrypted Wi-Fi frames). Wiretapping refers to physical-layer interception, such as attaching inductive clamps to copper cables, splicing optical fibers, or installing hardware inline splitters to mirror electronic or photonic signals.",
    hint: "Think software/logical interception (eavesdropping) vs physical/hardware tapping (wiretapping).",
    level: "basic",
    codeExample: `// Interception Taxonomy:
// Eavesdropping:  Software-level capture (Promiscuous NIC / Wireshark / BPF Filter)
// Wiretapping:    Physical-level tap (Optical Macrobending / Inductive Copper Clamp / Hardware SPAN)`
  },
  {
    question: "How does Promiscuous Mode on a Network Interface Card (NIC) facilitate local network eavesdropping?",
    shortAnswer: "It disables the hardware MAC address filter, forcing the NIC to pass all frames observed on the physical medium up to the OS kernel regardless of destination MAC.",
    explanation: "Under normal operation, a NIC discards all Ethernet frames whose destination MAC does not match its own hardware address (or broadcast/multicast). In promiscuous mode (enabled via `ip link set eth0 promisc on` or libpcap), this hardware filter is disabled, allowing sniffing software like Wireshark or tcpdump to inspect all traffic traversing that collision domain.",
    hint: "Telling the network card to read every letter delivered to the neighborhood, not just its own mailbox.",
    level: "moderate",
    codeExample: `# Enable promiscuous mode in Linux:
sudo ip link set dev eth0 promisc on
# Verify promisc flag:
ip link show eth0 | grep -i promisc`
  },
  {
    question: "How does Optical Fiber Macrobending allow an adversary to wiretap high-speed backbone links passively?",
    shortAnswer: "By physically curving the glass fiber beyond its critical angle, causing a small fraction (1-3%) of photons to leak through the cladding into an external photodiode without breaking the fiber.",
    explanation: "Total Internal Reflection (TIR) in optical fiber requires the angle of incidence to exceed the critical angle. Macrobending introduces a mechanical curvature that allows a minute portion of the light wave to escape through the cladding. A high-sensitivity clip-on optical tap detects these escaped photons, reconstructing the optical bitstream with less than 0.3 dB of attenuation.",
    hint: "Bending the glass tube so light leaks out the curve into a sensor without cutting the cable.",
    level: "expert",
    codeExample: `// Optical Power Calculation (Beer-Lambert & TIR):
// P_out = P_in * 10^(-alpha * L / 10)
// Insertion Loss = -10 * log10(P_received / P_transmitted)
// A 0.25 dB tap loss remains undetected within standard patch panel margin!`
  },
  {
    question: "What is an Optical Time-Domain Reflectometer (OTDR), and how does it detect physical optical wiretaps?",
    shortAnswer: "An OTDR injects high-intensity light pulses into the fiber and measures Rayleigh backscattering and Fresnel reflections to pinpoint exact locations of micro/macrobends, splices, and taps.",
    explanation: "When an optical tap is applied, the mechanical bend causes localized optical loss and backscatter reflection changes. An OTDR analyzes the time delay of returned photons: `Distance = (c * t) / (2 * n_core)`. By comparing current trace graphs against an initial fiber baseline, security engineers can detect sudden attenuation drops as small as 0.05 dB at exact distances (e.g. 14.2 km from Kolkata datacenter).",
    hint: "Radar for glass fiber: sends a pulse of light and times the reflections to locate taps.",
    level: "expert",
    codeExample: `// OTDR Distance Calculation Formula:
Distance = (Speed of Light in Vacuum * Time Delay) / (2 * Core Refractive Index)
d = (3.0e8 m/s * 1.42e-4 s) / (2 * 1.4682) = 14,507.5 meters`
  },
  {
    question: "What are Inductive Copper Wiretaps, and how do they capture signals without stripping insulation?",
    shortAnswer: "They use magnetic coils (Hall effect sensors or current transformers) clamped around copper twisted pairs to detect electromagnetic field variations generated by flowing current.",
    explanation: "Electric current flowing through copper wires creates a concentric magnetic field proportional to signal voltage changes ($B = \\mu I / (2\\pi r)$). An inductive pickup coil placed adjacent to an unshielded twisted-pair (UTP) cable senses these magnetic fluctuations via Faraday's Law of Induction, capturing electrical signals without stripping insulation or breaking continuity.",
    hint: "Reading the magnetic field surrounding the wire without touching the copper metal.",
    level: "expert",
    codeExample: `// Faraday's Law of Induction for Copper Taps:
// Induced EMF: e = -N * (dPhi / dt)
// Shielding Defense: Use STP/SSTP cables with grounded foil to eliminate external magnetic emanations.`
  },
  {
    question: "What is TEMPEST (Van Eck Phreaking), and how does it enable non-invasive eavesdropping on computer equipment?",
    shortAnswer: "It is the interception and reconstruction of unintended electromagnetic radiation emanated by computer monitors, cables, keyboards, and processors.",
    explanation: "Electronic devices emit high-frequency radio frequency (RF) signals during operation (e.g., video display cables or HDMI serializer clocks). A Van Eck phreaking receiver tuned to the resonant frequency can pick up these emanations through office walls and reconstruct live desktop video or keystrokes in real time. Defenses include TEMPEST-certified Faraday shielding and zoning standards.",
    hint: "Using a radio antenna to reconstruct the image on someone's computer screen through a wall.",
    level: "expert",
    codeExample: `// TEMPEST Emanation Defense:
// Zone 0: Equipment in shielded room (<1 meter emanation boundary)
// Physical Control: Ferrite chokes on HDMI cables + Copper mesh Faraday cages`
  },
  {
    question: "Why are legacy protocols like Telnet, FTP, HTTP, and SNMPv1/v2c inherently vulnerable to passive eavesdropping?",
    shortAnswer: "They transmit all authentication credentials, session tokens, and data payloads in unencrypted cleartext ASCII over the network.",
    explanation: "Protocols designed in the early ARPANET/Internet era assumed a trusted physical network. When a user authenticates via Telnet (`USER admin`, `PASS secret123`) or FTP, credentials fly across routers as raw ASCII bytes. Anyone capturing packets with tcpdump reads credentials instantly without needing decryption algorithms.",
    hint: "Transmitting postcards through the postal mail instead of sealed envelopes.",
    level: "basic",
    codeExample: `// Cleartext Packet Dump (Telnet Port 23):
0x0020:  5553 4552 2061 646d 696e 0d0a 5041 5353  USER admin..PASS
0x0030:  2053 756b 616e 7461 4032 3032 360d 0a    .Sukanta@2026..`
  },
  {
    question: "How does MACsec (IEEE 802.1AE) provide hardware-speed protection against physical and data link layer wiretaps?",
    shortAnswer: "MACsec encrypts and authenticates all Layer 2 Ethernet frames at wire speed using AES-GCM-128/256 directly between switch interfaces.",
    explanation: "Unlike TLS (Layer 7) or IPsec (Layer 3), MACsec operates at the Data Link Layer (Layer 2). It encrypts the entire Ethernet payload—including IP headers, ARP packets, and VLAN tags—with hardware AES-GCM encryption. An adversary attaching an optical tap or copper splitter between two switches sees only encrypted MACsec frames with an invalid Security Tag (SecTAG).",
    hint: "Switch-to-switch encryption at Layer 2 before packets reach the optical fiber.",
    level: "expert",
    codeExample: `// Cisco Switch MACsec Configuration:
switch(config)# mka policy MACSEC-STRICT
switch(config-mka-policy)# key-server priority 1
switch(config-mka-policy)# macsec-cipher-suite gcm-aes-256
switch(config-if)# macsec`
  },
  {
    question: "What is a SPAN (Switched Port Analyzer) / Mirror Port, and how can it be abused for unauthorized eavesdropping?",
    shortAnswer: "A SPAN port copies all packets from designated switch ports to a monitoring port; if an attacker compromises switch admin credentials, they can silently mirror all VLAN traffic.",
    explanation: "Network administrators use SPAN for legitimate network debugging or IDS sensor taps. However, if an adversary acquires switch CLI access, they can configure `monitor session 1 source vlan 10` and `monitor session 1 destination interface Gi1/0/24`. The attacker's laptop plugged into port 24 receives a complete clone of all banking or executive communications silently.",
    hint: "Configuring the switch to duplicate all office phone calls to the attacker's extension.",
    level: "moderate",
    codeExample: `// Unauthorized SPAN Configuration:
switch# configure terminal
switch(config)# monitor session 1 source interface GigabitEthernet1/0/1 - 10 both
switch(config)# monitor session 1 destination interface GigabitEthernet1/0/48`
  },
  {
    question: "How does Berkeley Packet Filter (BPF) syntax optimize packet eavesdropping and lawful interception?",
    shortAnswer: "BPF provides an in-kernel bytecode filter engine that discards unwanted packets before copying them into user space, drastically reducing memory overhead.",
    explanation: "Copying 10 Gbps of raw network frames to user space crashes packet capture tools. BPF compiles human-readable expressions (e.g. `tcp port 443 and host 192.168.1.50`) into kernel microcode. The OS kernel evaluates the filter inside the socket buffer, passing only matching frames to the sniffer, enabling targeted surveillance with minimal CPU usage.",
    hint: "Filtering the mail at the loading dock so only target letters are copied.",
    level: "expert",
    codeExample: `# High-Performance BPF Expression:
tcpdump -i eth0 -nn "tcp[tcpflags] & (tcp-syn|tcp-ack) == (tcp-syn|tcp-ack) and net 10.0.0.0/8"`
  },
  {
    question: "What is the difference between an In-Line Hardware TAP and a SPAN Port for packet capture?",
    shortAnswer: "A Hardware TAP is a dedicated physical device spliced directly into the cable that mirrors 100% of full-duplex traffic without dropping frames; a SPAN port is a software feature on a switch that can drop frames under high CPU load.",
    explanation: "Physical TAPs (Test Access Points) split optical or electrical signals at the hardware layer with zero latency, zero configuration, and complete passive isolation (the monitoring port cannot transmit back into the network). SPAN ports share the switch's internal backplane and will silently drop mirrored packets if the switch CPU or egress buffer is saturated.",
    hint: "Dedicated optical prism (TAP) versus a software mirror setting inside a router (SPAN).",
    level: "moderate",
    codeExample: `// TAP vs SPAN Comparison:
// TAP:  Zero packet loss, failsafe link continuity, physical unidirectional diode
// SPAN: Uses switch CPU, drops packets on buffer congestion, modifies frame timing`
  },
  {
    question: "How does 802.11 Monitor Mode differ from Promiscuous Mode in wireless eavesdropping?",
    shortAnswer: "Promiscuous mode captures frames on an associated Wi-Fi network after joining it; Monitor mode captures all 802.11 radio frames in the air without associating or authenticating to any Access Point.",
    explanation: "In monitor mode (RFMON), a wireless card acts as a passive radio receiver tuned to a specific channel (e.g., 2.4 GHz Channel 6). It captures beacon frames, probe requests, authentication handshakes (EAPOL 4-way handshakes), and data packets from all nearby SSIDs without ever registering its MAC address with the router.",
    hint: "Tuning an AM/FM radio antenna to listen to all broadcasts in the air without joining the station.",
    level: "moderate",
    codeExample: `# Put wireless interface into monitor mode:
sudo airmon-ng start wlan0
# Capture raw 802.11 frames:
sudo airodump-ng wlan0mon --channel 6 --bssid 00:14:22:01:23:45`
  },
  {
    question: "What is an EAPOL 4-Way Handshake, and why do passive Wi-Fi eavesdroppers capture it?",
    shortAnswer: "It is the exchange between a Wi-Fi client and AP to establish encryption keys; capturing it allows an attacker to crack WPA2 pre-shared keys (PSK) offline using dictionary attacks.",
    explanation: "During WPA2-PSK connection, the AP and client exchange four EAPOL frames containing the ANonce, SNonce, and Message Integrity Code (MIC). A passive eavesdropper logs these 4 frames and runs offline cracking tools (hashcat / aircrack-ng) against wordlists without sending a single packet to the AP, keeping the attack completely undetected.",
    hint: "Record the conversation when keys are agreed upon, then guess the master password offline at home.",
    level: "expert",
    codeExample: `# Offline WPA2 Handshake Cracking:
aircrack-ng -w /usr/share/wordlists/rockyou.txt -b 00:14:22:01:23:45 capture.cap`
  },
  {
    question: "How does WPA3 with Opportunistic Wireless Encryption (OWE) eliminate passive open Wi-Fi eavesdropping?",
    shortAnswer: "OWE uses unauthenticated Diffie-Hellman (RFC 8110) to automatically encrypt each user's Wi-Fi connection with a unique pairwise session key, even on public hotspots without a password.",
    explanation: "On legacy open Wi-Fi (e.g., at Kolkata railway stations or cafes), all data is broadcast in plaintext, allowing any listener to read other users' web traffic. WPA3 OWE performs a cryptographic Diffie-Hellman key exchange during the association handshake, establishing an individual AES session key per client so neighboring devices cannot decrypt each other's frames.",
    hint: "Every user in the coffee shop gets their own private encryption key automatically.",
    level: "moderate",
    codeExample: `// 802.11 OWE Association Flow:
// Client → Probe Request (OWE AKM suite)
// AP     → Probe Response (OWE supported)
// Client → Association Request + Client DH Public Key
// AP     → Association Response + AP DH Public Key
// Result : Pairwise Master Key (PMK) derived; channel encrypted with AES-CCMP`
  },
  {
    question: "What is Unshielded Twisted Pair (UTP) Crosstalk, and how can it lead to unintended physical eavesdropping?",
    shortAnswer: "Crosstalk is the electromagnetic bleeding of signals from one copper pair into adjacent wire pairs within the same cable bundle.",
    explanation: "When high-frequency electrical signals travel along copper conductors, electromagnetic radiation induces small voltages in neighboring pairs (Near-End Crosstalk - NEXT / Far-End Crosstalk - FEXT). In poorly shielded Cat5e bundles, an attacker monitoring an unused wire pair in the same conduit can amplify and demodulate the leaked signal from adjacent active lines.",
    hint: "Signals bleeding like sound through thin apartment walls into neighboring wires.",
    level: "expert",
    codeExample: `// Crosstalk Minimization Engineering:
// 1. Tighter Twist Ratios: Differential signaling cancels induced EMF.
// 2. Foil Shielding: Cat6A S/FTP (Screened Fully Shielded Twisted Pair).
// 3. Grounding: Terminate shield drain wire to earth ground at patch panels.`
  },
  {
    question: "Under the Indian Telegraph Act 1885 and Information Technology Act 2000, what are the legal regulations governing Wiretapping?",
    shortAnswer: "Unauthorized wiretapping is a criminal offense under Section 26 of the Telegraph Act and Section 43/66 of the IT Act; lawful interception requires strict authorization from the Union Home Secretary under Section 69.",
    explanation: "Under Section 26 of the Indian Telegraph Act 1885, unlawful interception of telegraphic/electronic communications carries imprisonment up to 3 years. Under Section 69 of the IT Act 2000, lawful wiretapping can only be authorized by the Union Home Secretary or State Home Secretary for sovereignty, defense, or prevention of offenses, with mandatory destruction of unneeded logs after 6 months.",
    hint: "Illegal wiretapping is a crime; lawful wiretapping requires explicit Home Ministry sanction.",
    level: "moderate",
    codeExample: `// Legal Summary (Interception in India):
// Unlawful Wiretap: IT Act Sec 43/66 (Damages up to ₹1 Cr + 3 Yrs Prison)
// Lawful Interception Authority: Section 69 IT Act (Home Secretary Order Required)
// Retention Rule: Intercepted logs reviewed every 60 days by Cabinet Secretary Review Committee`
  },
  {
    question: "How does IPsec in Transport Mode differ from Tunnel Mode in protecting against Network Layer Wiretaps?",
    shortAnswer: "Transport Mode encrypts only the IP payload (leaving original IP headers visible to eavesdroppers), whereas Tunnel Mode encapsulates and encrypts the entire original IP packet inside a new IP header.",
    explanation: "In Transport Mode, an attacker tapping the link can still perform traffic analysis by reading the source and destination IP addresses. In Tunnel Mode (used in site-to-site VPNs), the entire original IP packet is encrypted with ESP and hidden inside a new IP header with gateway addresses, masking end-user identities and subnet structures.",
    hint: "Transport Mode puts a letter in a clear envelope; Tunnel Mode puts the entire envelope inside a box.",
    level: "moderate",
    codeExample: `// IPsec ESP Modes:
// Transport Mode: [Original IP Header (Clear)] [ESP Header] [Payload (Encrypted)] [ESP Trailer]
// Tunnel Mode   : [New Gateway IP Header]     [ESP Header] [Original IP + Payload (Encrypted)] [ESP Trailer]`
  },
  {
    question: "What is SNI (Server Name Indication) snooping, and how does Encrypted Client Hello (ECH) eliminate it?",
    shortAnswer: "SNI transmits the requested domain name in cleartext during the TLS handshake; Encrypted Client Hello (ECH) encrypts the entire ClientHello using the server's public key published in DNS (HTTPS records).",
    explanation: "Historically, even over HTTPS, the browser sends the target hostname (e.g. `secret-banking.kolkata.in`) in cleartext inside the TLS `ServerNameIndication` extension so the server can select the right certificate. An eavesdropper monitoring network traffic can see every website you visit. ECH (RFC 9460) encrypts this handshake extension, closing the last major passive metadata leak in web communications.",
    hint: "Encrypting the website address on the outer envelope so ISPs cannot see which site you visit.",
    level: "expert",
    codeExample: `// ECH DNS Resolution Flow:
// 1. Browser queries DNS: dig HTTPS portal.bank.in
// 2. DNS returns ECHConfig containing Server's Public Key
// 3. Browser encrypts InnerClientHello with HPKE (Hybrid Public Key Encryption)`
  },
  {
    question: "How does an Acoustic Keylogger perform passive eavesdropping without software malware?",
    shortAnswer: "It records the subtle sound vibrations produced by keystrokes and uses machine learning to classify unique acoustic frequencies of different keys.",
    explanation: "Every physical key on a mechanical keyboard produces a distinct sound wave based on its keyboard position and chassis resonance. A sensitive smartphone microphone placed nearby in a Kolkata cafe can record typing audio. Machine learning models analyze peak acoustic frequencies and time-of-flight to reconstruct typed passwords with up to 95% accuracy.",
    hint: "Listening to the click-clack sound of typing to deduce which keys were pressed.",
    level: "expert",
    codeExample: `// Acoustic Profiling Parameters:
// Peak Audio Frequency: 1.2 kHz - 8.5 kHz
// Mel-Frequency Cepstral Coefficients (MFCC) feature extraction → 95% classification accuracy`
  },
  {
    question: "What is an Inline Network Tap's 'Failsafe Bypass' mechanism, and why is it critical for high-availability networks?",
    shortAnswer: "It uses an optical or mechanical relay that automatically closes during a power outage, allowing light/electrical signals to pass through uninterrupted without dropping the link.",
    explanation: "If an active monitoring TAP loses electrical power, a network outage would occur if the link dropped. Failsafe bypass TAPs incorporate spring-loaded mechanical relays or optical prisms that default to a straight-through physical path upon power loss. This guarantees 100% network uptime while the monitoring capability temporarily disconnects.",
    hint: "A spring-loaded switch that stays open with power, but snaps shut to keep the pipe open if power fails.",
    level: "moderate",
    codeExample: `// Failsafe Bypass Operation:
// Normal State (Powered): [Network In] → Splitter → [Network Out] + [Monitoring Port]
// Power Loss State      : [Network In] ------Direct Optical Bypass------> [Network Out]`
  },
  {
    question: "How do End-to-End Encryption (E2EE) messaging protocols (e.g. Signal Protocol / Double Ratchet) neutralize telecom wiretaps?",
    shortAnswer: "They derive ephemeral cryptographic keys per message using a ratcheting Diffie-Hellman exchange, ensuring neither telecom providers nor wiretappers can decrypt historical or future messages.",
    explanation: "Under the Signal Double Ratchet algorithm, every single message sent derives a new symmetric encryption key ($K_{i+1} = \\text{KDF}(K_i)$). Even if an adversary taps the optical fiber at a cellular tower or compromises a single ephemeral key, they cannot decrypt past communications (Forward Secrecy) or subsequent messages (Break-in Recovery).",
    hint: "Every single text message uses a brand-new, self-destructing encryption key.",
    level: "expert",
    codeExample: `// Double Ratchet Key Derivation:
// DH Ratchet step: RootKey_i+1, ChainKey = KDF(RootKey_i, DH(RatchetPriv, RatchetPub))
// Message Key:     MsgKey_j = KDF(ChainKey_j); ChainKey_j+1 = KDF(ChainKey_j)`
  },
  {
    question: "What is VLAN Hopping via Switch Spoofing, and how does it enable inter-VLAN eavesdropping?",
    shortAnswer: "An attacker connects a rogue switch and negotiates 802.1Q trunking via Dynamic Trunking Protocol (DTP), gaining access to all VLAN traffic passing across the switch backplane.",
    explanation: "By default, many switch ports are set to `dynamic auto` or `dynamic desirable`. If an attacker's machine sends DTP negotiation frames, the switch converts the access port into a trunk port. The attacker can then tag frames with any VLAN ID (e.g., VLAN 20 - Management, VLAN 30 - Finance), sniffing and injecting traffic into isolated department networks.",
    hint: "Tricking the switch into treating your laptop like another corporate switch.",
    level: "expert",
    codeExample: `# Yersinia DTP Switch Spoofing Attack:
sudo yersinia dtp -attack 1 -interface eth0
# Switch Mitigation:
switch(config-if)# switchport mode access
switch(config-if)# switchport nonegotiate`
  },
  {
    question: "How does DHCP Snooping prevent rogue DHCP servers from facilitating Man-in-the-Middle eavesdropping?",
    shortAnswer: "It designates switch ports as 'trusted' or 'untrusted', dropping all DHCP Offer/Ack packets coming from unauthorized untrusted user ports.",
    explanation: "A rogue DHCP server responds to client requests with its own IP as the Default Gateway and DNS server, routing all subnet traffic through the attacker for passive sniffing. With DHCP Snooping enabled, the switch allows DHCP server responses exclusively on trusted uplink ports connecting to authorized servers, dropping rogue DHCP packets immediately.",
    hint: "Only allowing official routers to hand out network IP address leases.",
    level: "moderate",
    codeExample: `// Cisco DHCP Snooping Configuration:
switch(config)# ip dhcp snooping
switch(config)# ip dhcp snooping vlan 10,20
switch(config-if)# interface GigabitEthernet1/0/1 (Uplink to real DHCP)
switch(config-if)# ip dhcp snooping trust`
  },
  {
    question: "What is BGP Route Hijacking, and how can it be used to execute stealthy global passive eavesdropping?",
    shortAnswer: "An autonomous system (AS) falsely advertises IP prefix ownership to redirect internet traffic through its territory, inspecting payloads before forwarding them to the real destination.",
    explanation: "In a BGP intercept attack, a rogue Autonomous System advertises a more specific route (e.g., `/24` instead of `/16`) for a target financial institution. Global routers select this path. The rogue AS passively records all cleartext and encrypted traffic on high-capacity recorders and forwards the packets back to the legitimate destination, leaving the connection functional with slight latency.",
    hint: "Putting up a fake highway detour sign so all city traffic drives past your recording cameras first.",
    level: "expert",
    codeExample: `// BGP Interception Flow:
// 1. Attacker AS announces 203.0.113.0/24 (Target Kolkata Bank)
// 2. Global BGP tables update → Traffic routes through Attacker AS
// 3. Attacker clones stream to disk → Forwards to real Bank AS`
  },
  {
    question: "How does Resource Public Key Infrastructure (RPKI) and Route Origin Authorization (ROA) prevent BGP-level passive wiretapping?",
    shortAnswer: "RPKI cryptographically binds IP address blocks to authorized Autonomous System Numbers (ASNs) using digital certificates, allowing routers to reject forged route announcements.",
    explanation: "Under RPKI (RFC 6480), Regional Internet Registries (like APNIC in Asia-Pacific) issue Route Origin Authorizations (ROAs) signed with RPKI certificates. When a border router receives a BGP route announcement, it verifies the origin ASN against the RPKI cache. If an unauthorized AS attempts to hijack the prefix, the route status is marked `Invalid` and discarded.",
    hint: "A digital deed proving who owns an IP address block so impostors are ignored by routers.",
    level: "expert",
    codeExample: `// Cisco IOS-XR RPKI Configuration:
router bgp 65000
 bgp origin-as validation enable
!
router bgp 65000 neighbor 198.51.100.1
 address-family ipv4 unicast
  route-policy RPKI-DROP-INVALID in`
  },
  {
    question: "What is DNS Over HTTPS (DoH / RFC 8484), and how does it prevent ISP-level DNS eavesdropping?",
    shortAnswer: "It encrypts DNS queries and responses using standard HTTPS (port 443), preventing local ISPs, Wi-Fi operators, and wiretappers from inspecting domain lookups.",
    explanation: "Traditional DNS queries are sent over UDP port 53 in cleartext, allowing anyone monitoring the link to log every website domain resolved by a host. DoH encapsulates DNS wire-format messages inside an encrypted TLS session to an upstream resolver (e.g. Cloudflare or Google), blending DNS traffic indistinguishably with general web traffic.",
    hint: "Wrapping your phonebook queries inside an encrypted web session.",
    level: "moderate",
    codeExample: `// DoH Query Format (RFC 8484):
POST /dns-query HTTP/2
Host: cloudflare-dns.com
Content-Type: application/dns-message
Accept: application/dns-message
[Binary DNS Wire-Format Payload (Encrypted)]`
  },
  {
    question: "What is an Optical Power Meter (OPM), and how is it used during physical layer wiretap auditing?",
    shortAnswer: "It measures the precise optical power output (in dBm or mW) of an optical fiber link to verify whether unexpected signal loss indicates a physical tap.",
    explanation: "A baseline optical link budget is calculated based on fiber length, splice loss (0.05 dB/splice), and connector loss (0.2 dB/connector). If an OPM reading at the receiving end shows a sudden unexplained power drop (e.g. signal drops from -4.0 dBm to -4.8 dBm), security auditors know a physical macrobend tap or optical splitter has been installed along the conduit.",
    hint: "A multimeter for light: measuring photon brightness to detect leaks.",
    level: "moderate",
    codeExample: `// Optical Link Budget Formula:
// Received Power (dBm) = Transmit Power (dBm) - (Cable Loss + Splice Loss + Connector Loss + Tap Loss)
// If P_rx is 0.8 dB lower than theoretical baseline → Investigate for physical tap!`
  },
  {
    question: "How does the 'Forward Secrecy' property in modern cryptography neutralize archived wiretap recordings?",
    shortAnswer: "It generates ephemeral session keys using Diffie-Hellman that are discarded after the session, ensuring that compromising a long-term private key cannot decrypt previously recorded traffic.",
    explanation: "In legacy RSA key exchange, if an adversary records 5 years of encrypted banking traffic on hard drives (a passive 'harvest now, decrypt later' attack) and eventually steals the bank's RSA private key, they can decrypt all 5 years of historical traffic. With Ephemeral Diffie-Hellman (ECDHE in TLS 1.3), session keys are generated dynamically and deleted from RAM; the long-term certificate is used only for authentication, rendering archived ciphertexts permanently unbreakable.",
    hint: "Throwing away the temporary safe key after every conversation so the master key cannot open past vaults.",
    level: "expert",
    codeExample: `// Ephemeral Diffie-Hellman (ECDHE):
// Client computes: X = g^a mod p; Server computes: Y = g^b mod p
// Shared Secret:   K = Y^a = X^b = g^(ab) mod p
// 'a' and 'b' are deleted from memory immediately after handshake!`
  },
  {
    question: "What are the physical security requirements for protecting submarine fiber optic cable landing stations against oceanic wiretaps?",
    shortAnswer: "Double-armored submarine cable sheathing, pressurized gas/nitrogen monitoring, continuous coherent OTDR monitoring, and coastal naval radar security zones.",
    explanation: "Submarine fiber optic cables carry 99% of international data. Hostile submarines can use specialized submersibles to tap ocean-floor cables. Landing stations deploy continuous Coherent Optical Time-Domain Reflectometry (C-OTDR) that detects mechanical vibrations and localized microbends along thousands of kilometers of ocean bed, paired with double-layer steel wire armor and electro-acoustic monitoring.",
    hint: "Underwater armored conduits and vibration sensors to protect trans-oceanic internet cables.",
    level: "expert",
    codeExample: `// Submarine Cable Protection Architecture:
// 1. Physical: Double-layer high-tensile steel wire armor + Polyethylene insulation
// 2. Monitoring: Continuous Coherent OTDR (100 Hz polling across 5,000 km)
// 3. Cryptography: Bulk optical transport network (OTN) Layer 1 encryption (AES-256)`
  },
  {
    question: "Synthesize an end-to-end organizational architecture to neutralize passive eavesdropping and physical wiretapping across campus and WAN networks.",
    shortAnswer: "An integrated defense combining MACsec Layer 2 line encryption, TLS 1.3/IPsec ESP Tunnel Mode, OTDR optical monitoring, 802.1X NAC, and Constant Traffic Padding.",
    explanation: "To eliminate passive surveillance: 1. Physical Layer: Armored conduits, continuous OTDR fiber monitoring, and TEMPEST-shielded server racks. 2. Data Link Layer: MACsec (802.1AE) encryption across all inter-switch trunks, Dynamic ARP Inspection, and 802.1X port authentication. 3. Network & Transport: IPsec Tunnel Mode with ESP and TLS 1.3 AEAD with ECH. 4. Metadata: Continuous traffic padding to mask transmission volume spikes.",
    hint: "Encrypt every layer from glass fiber to application payload, while monitoring optical line power continuously.",
    level: "expert",
    codeExample: `// Comprehensive Anti-Wiretap Blueprint:
// Layer 1: Armored conduit + OTDR pulse reflectometry monitoring
// Layer 2: IEEE 802.1AE MACsec (AES-256-GCM) on all trunk links
// Layer 3: IPsec Tunnel Mode with ESP & Constant Traffic Padding
// Layer 7: TLS 1.3 with Encrypted Client Hello (ECH) & DNS-over-HTTPS (DoH)`
  }
];

export default questions;
