const questions = [
  {
    question: "What is hybrid topology?",
    shortAnswer: "A network topology that combines two or more different topologies.",
    explanation: "Hybrid topology blends star, ring, bus, mesh, or tree to meet specific needs.",
    hint: "Think of a mix of different network shapes.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Why would an organization use hybrid topology?",
    shortAnswer: "To leverage the strengths of different topologies for different network segments.",
    explanation: "Different areas have different needs (e.g., redundancy vs. cost-effectiveness).",
    hint: "No single topology fits all.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a star-ring hybrid topology?",
    shortAnswer: "A central switch connects to multiple hubs, each forming a ring topology.",
    explanation: "This combines the easy management of star with the fault tolerance of ring.",
    hint: "Star with rings at each branch.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a star-bus hybrid topology?",
    shortAnswer: "Multiple star networks connected to a central backbone (bus).",
    explanation: "Each star network is a department/floor; the bus connects them all.",
    hint: "Stars on a main line.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a star-mesh hybrid topology?",
    shortAnswer: "A star network with redundant mesh connections for critical nodes.",
    explanation: "Critical servers have multiple paths for high availability.",
    hint: "Star with extra backup links.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the main advantage of hybrid topology?",
    shortAnswer: "Flexibility to tailor each network segment to its specific needs.",
    explanation: "Can optimize for cost, performance, and reliability on a per-segment basis.",
    hint: "Best of all worlds.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the main disadvantage of hybrid topology?",
    shortAnswer: "Increased complexity in design and management.",
    explanation: "Multiple topologies require more expertise and planning.",
    hint: "Harder to manage.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How do you connect different topology segments in a hybrid network?",
    shortAnswer: "Using routers, switches, or gateways.",
    explanation: "Interconnection devices bridge the different topology types.",
    hint: "Bridges between segments.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a backbone in hybrid topology?",
    shortAnswer: "A high-speed connection that links different topology segments together.",
    explanation: "Often a fiber ring or mesh connecting hubs.",
    hint: "The main highway.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Can hybrid topology include mesh for redundancy?",
    shortAnswer: "Yes, mesh can be used in parts of the network where reliability is critical.",
    explanation: "Data centers and core networks often use mesh segments.",
    hint: "Where uptime is critical.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the difference between hybrid and tree topology?",
    shortAnswer: "Tree is a specific hierarchical structure; hybrid is any combination of topologies.",
    explanation: "Tree is a type of hybrid, but hybrid is broader.",
    hint: "Tree is one example of hybrid.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do you design a hybrid topology for a multi-building campus?",
    shortAnswer: "Use a backbone (e.g., fiber ring) connecting buildings, each with its own star or mesh topology.",
    explanation: "Each building has internal topology; the backbone interconnects them.",
    hint: "Buildings as branches, backbone as the trunk.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What routing protocols are used in hybrid topologies?",
    shortAnswer: "OSPF, EIGRP, or BGP, depending on the size and complexity.",
    explanation: "Dynamic routing protocols adapt to topology changes.",
    hint: "Protocols that find the best path.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of VLANs in hybrid topology?",
    shortAnswer: "VLANs logically segment traffic across different topology types.",
    explanation: "VLANs provide isolation and security across the hybrid network.",
    hint: "Logical separation.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do you ensure redundancy in a hybrid topology?",
    shortAnswer: "By using redundant links, dual switches, and mesh segments where needed.",
    explanation: "Redundancy is targeted where it matters most.",
    hint: "Backup paths.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the impact of a backbone failure in hybrid topology?",
    shortAnswer: "Segments connected to that backbone lose connectivity.",
    explanation: "The backbone is critical; redundancy is needed.",
    hint: "The main road is out.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the cost implication of hybrid topology?",
    shortAnswer: "Higher than single topology due to multiple hardware types and more cabling.",
    explanation: "Cost varies based on the topologies chosen.",
    hint: "More parts = more cost.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do you troubleshoot a hybrid topology?",
    shortAnswer: "Isolate the segment with the problem, check interconnection devices, and verify routing.",
    explanation: "Troubleshooting is systematic, starting from the affected segment.",
    hint: "Find the broken branch.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the benefit of using a ring backbone in hybrid topology?",
    shortAnswer: "Provides fault tolerance – if one link fails, traffic reroutes the other way.",
    explanation: "A ring backbone is resilient and commonly used.",
    hint: "Two paths around the ring.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the benefit of using a star topology in offices?",
    shortAnswer: "Easy to manage and expand; a single device failure doesn't affect others.",
    explanation: "Star is ideal for departmental networks.",
    hint: "Easy to add new employees.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the benefit of using a mesh topology for a data center?",
    shortAnswer: "Provides high redundancy and minimal downtime.",
    explanation: "Data centers require maximum reliability.",
    hint: "No single point of failure.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the concept of 'spanning tree' in hybrid networks?",
    shortAnswer: "STP prevents loops when there are redundant links between switches.",
    explanation: "Redundant links can cause loops; STP blocks some ports.",
    hint: "Prevents circular paths.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does SDN simplify hybrid topology management?",
    shortAnswer: "SDN provides a central controller, making it easier to manage diverse topologies.",
    explanation: "Centralized control simplifies configuration and monitoring.",
    hint: "A single pane of glass.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the difference between a hybrid and a heterogeneous network?",
    shortAnswer: "Hybrid is about topology; heterogeneous is about different types of devices or protocols.",
    explanation: "Hybrid focuses on the network structure; heterogeneous focuses on components.",
    hint: "Structure vs. components.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of network segmentation in hybrid topology?",
    shortAnswer: "Segmentation isolates traffic and improves security across different topology segments.",
    explanation: "VLANs and subnets provide logical separation.",
    hint: "Separate areas.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do you ensure QoS across different topology segments?",
    shortAnswer: "Use QoS policies at interconnection points and within each segment.",
    explanation: "Priority handling ensures critical traffic gets priority.",
    hint: "Priority lanes.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are the challenges of managing a hybrid topology?",
    shortAnswer: "Complexity, interoperability issues, and the need for skilled staff.",
    explanation: "Multiple topologies require broad expertise.",
    hint: "Hard to manage.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do you plan for scalability in hybrid topology?",
    shortAnswer: "Design with expansion in mind – leave spare ports and plan for additional segments.",
    explanation: "Modular design facilitates growth.",
    hint: "Plan for growth.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of a firewall in hybrid topology?",
    shortAnswer: "A firewall is placed at critical junctions (e.g., between topology segments) for security.",
    explanation: "It filters traffic between different parts of the network.",
    hint: "Security guard between areas.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the future of hybrid topology with emerging technologies?",
    shortAnswer: "Hybrid topology will evolve with SDN, automation, and AI-driven management.",
    explanation: "Networks are becoming more dynamic and adaptable.",
    hint: "Smarter hybrid networks.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;