// topic0_questions.js
// 30 Moderate to Expert Questions on the Need for Testing Optimality in Transportation Problems

const questions = [
  {
    question: "What is the fundamental difference between an Initial Basic Feasible Solution (IBFS) and an Optimal Solution in transportation programming?",
    shortAnswer: "An IBFS satisfies all supply and demand constraints without violating non-negativity (feasible), but may not achieve the minimum possible total transportation cost Z. An optimal solution minimizes Z globally across all feasible solutions.",
    explanation: "Methods like NWCR, Matrix Minima, and VAM only construct valid starting vertices (IBFS) in the feasible polytope. An optimality test is mathematically required to determine if any unused route can further decrease total cost.",
    hint: "Think feasible starting point vs certified minimum cost.",
    level: "moderate",
    codeExample: "IBFS (Feasible: Ax = b, x >= 0) != Optimal (min Z = c^T x)"
  },
  {
    question: "Why can't even Vogel's Approximation Method (VAM) guarantee 100% mathematical optimality in every transportation problem?",
    shortAnswer: "Because VAM is a greedy heuristic that minimizes one-step local penalty regrets rather than exploring global linear programming simplex pivots across all basic exchange cycles.",
    explanation: "Although VAM often achieves solutions within 1-2% of optimal (or optimal directly), pathological cost matrices with complex bipartite cycles can trap VAM in a local sub-optimum.",
    hint: "Heuristics evaluate local regret, not full global simplex duals.",
    level: "expert",
    codeExample: "VAM Solution != Always Global Minimum; Optimality Test is mandatory."
  },
  {
    question: "What is the mathematical condition that proves an Initial Basic Feasible Solution is globally optimal?",
    shortAnswer: "All non-basic cell evaluation indices (opportunity costs) must be non-negative: d_ij = c_ij - (u_i + v_j) >= 0 for all unoccupied cells (i, j).",
    explanation: "When every d_ij >= 0, introducing any non-basic shipping route would either increase total cost (if d_ij > 0) or leave it unchanged (if d_ij = 0). No cost-reducing pivot exists.",
    hint: "Every unoccupied route opportunity cost d_ij >= 0.",
    level: "expert",
    codeExample: "Optimality Criterion: forall (i, j) in NonBasic, d_ij = c_ij - u_i - v_j >= 0"
  },
  {
    question: "What occurs if an operations manager implements an IBFS generated by the North-West Corner Rule without performing an optimality test?",
    shortAnswer: "The enterprise risks overspending significantly (frequently 25% to 50% above the minimum achievable freight expenditure), resulting in substantial corporate capital waste.",
    explanation: "NWCR is completely cost-blind. Deploying its raw allocation plan in high-volume freight logistics causes severe budget inefficiencies.",
    hint: "Cost-blind solutions create major financial losses.",
    level: "moderate",
    codeExample: "Excess Loss = Z_NWCR - Z_Optimal (can exceed ₹100,000s in enterprise supply chains)."
  },
  {
    question: "Suppose Debangshu in Barrackpore obtains an IBFS with total cost Z = ₹4,800. After applying the MODI test, he discovers an opportunity cost d_23 = -₹4. What does this negative value signify?",
    shortAnswer: "Allocating shipping volume to unused route (2, 3) will decrease the total transportation cost by ₹4 for every unit redirected into that cell.",
    explanation: "A negative opportunity cost d_ij < 0 indicates an entering candidate route that yields direct per-unit marginal savings.",
    hint: "Negative opportunity cost means potential per-unit cost reduction.",
    level: "moderate",
    codeExample: "d_23 = -₹4 => Total Cost drops by ₹4 per shifted ton."
  },
  {
    question: "In the 2-stage Transportation Problem solving methodology, what are the distinct roles of Stage 1 and Stage 2?",
    shortAnswer: "Stage 1 constructs an Initial Basic Feasible Solution (via NWCR, Least Cost, or VAM); Stage 2 performs the Optimality Test (via MODI or Stepping-Stone) and iteratively improves the solution until global optimality is certified.",
    explanation: "Stage 1 finds a valid basic vertex on the constraint polyhedron; Stage 2 traverses adjacent vertices to reach the absolute minimum cost vertex.",
    hint: "Stage 1 = Initial feasible basis; Stage 2 = Optimality audit & improvement.",
    level: "moderate",
    codeExample: "Pipeline: Raw Problem → [Stage 1: IBFS] → [Stage 2: MODI Test & Pivot] → Optimal Plan."
  },
  {
    question: "Why is the Stepping-Stone method less efficient than the MODI method for testing the optimality of large matrices?",
    shortAnswer: "Stepping-Stone requires tracing individual closed loops for every single non-basic cell to calculate evaluation indices, whereas MODI calculates dual potentials (u_i, v_j) once and evaluates all non-basic cells simultaneously.",
    explanation: "In an m x n matrix with (m-1)(n-1) empty cells, Stepping-Stone traces (m-1)(n-1) separate geometric loops, while MODI uses simple arithmetic additions u_i + v_j.",
    hint: "MODI evaluates all empty cells via row/column potentials in one go.",
    level: "expert",
    codeExample: "Stepping-Stone: O((m*n)^2) loop traces vs MODI: O(m*n) potential evaluations."
  },
  {
    question: "What prerequisite must an Initial Basic Feasible Solution satisfy before any optimality test can be executed?",
    shortAnswer: "It must be non-degenerate, meaning it contains exactly m + n - 1 basic cells forming an open (loop-free) spanning tree.",
    explanation: "Without m + n - 1 independent basic equations u_i + v_j = c_ij, the system of linear equations is underdetermined and dual potentials cannot be calculated.",
    hint: "Exact basis count must equal m + n - 1 without closed loops.",
    level: "expert",
    codeExample: "Prerequisite Check: Count(BasicCells) === m + n - 1 && isAcyclic(Basis) === true"
  },
  {
    question: "Suppose Susmita in Ichapur evaluates a 3x3 logistics network with an IBFS cost of ₹2,400. If all opportunity costs satisfy d_ij >= 0, what should she conclude?",
    shortAnswer: "The current IBFS is certified to be globally optimal; no further adjustments can reduce total freight costs below ₹2,400.",
    explanation: "When no non-basic route has d_ij < 0, the optimality criterion is satisfied and the algorithm terminates.",
    hint: "All d_ij >= 0 means optimal solution is reached.",
    level: "moderate",
    codeExample: "if (all(d_ij >= 0)) { Terminate('Globally Optimal at ₹2,400'); }"
  },
  {
    question: "If an optimality test shows that all non-basic cells have d_ij > 0 except for one cell where d_kl = 0, what does this indicate?",
    shortAnswer: "An alternative (multiple) optimal basic feasible solution exists that achieves the exact same minimum total cost Z.",
    explanation: "A zero opportunity cost d_kl = 0 means shifting flow into cell (k, l) creates an alternative optimal routing pattern without altering total cost.",
    hint: "d_ij = 0 on a non-basic cell indicates alternative optimal solutions.",
    level: "expert",
    codeExample: "d_kl === 0 => Alternative Optimal Solution exists with identical Z."
  },
  {
    question: "How does the concept of 'Opportunity Cost' in transportation problems connect to shadow prices in Linear Programming Duality?",
    shortAnswer: "The dual multipliers u_i and v_j represent origin and destination shadow prices; the opportunity cost d_ij = c_ij - (u_i + v_j) is the reduced cost coefficient from the simplex dual.",
    explanation: "In LP duality, reduced costs indicate how much the objective coefficient c_ij must improve before variable x_ij enters the optimal basis.",
    hint: "Dual shadow prices u_i and v_j determine reduced costs d_ij.",
    level: "expert",
    codeExample: "Dual LP: d_ij = c_ij - u_i - v_j (Simplex Reduced Cost)"
  },
  {
    question: "Suppose Mamata in Kolkata compares two initial solutions: Solution A (cost ₹3,200) and Solution B (cost ₹3,000). Does Solution B guarantee fewer MODI iterations to reach the optimum than Solution A?",
    shortAnswer: "Not necessarily; while Solution B has a lower starting cost, the number of MODI pivoting iterations depends on the geometric distance in basis vertices to the optimal basic solution.",
    explanation: "Cost proximity does not strictly correlate with basis pivot proximity, though in practice higher-quality IBFS methods (like VAM) usually require 0 to 1 iteration.",
    hint: "Basis vertex distance determines iteration count, not raw cost alone.",
    level: "expert",
    codeExample: "Lower initial cost != Guaranteed fewer simplex pivots."
  },
  {
    question: "Why is an optimality test essential in government procurement and public sector logistics in West Bengal?",
    shortAnswer: "To provide mathematical proof of fiduciary compliance and ensure public tax funds are not wasted on sub-optimal freight contracts.",
    explanation: "Auditors require formal optimality proofs (all d_ij >= 0) to verify that logistics tenders minimize public expenditure.",
    hint: "Provides auditable proof of maximum fiscal efficiency.",
    level: "moderate",
    codeExample: "Public Audit Standard: Certified Optimal Basis with all d_ij >= 0."
  },
  {
    question: "What happens if a student attempts to perform a MODI optimality test on a degenerate solution with only 4 basic cells in a 3x3 tableau?",
    shortAnswer: "The system of equations u_i + v_j = c_ij cannot be solved for all rows and columns because there are 6 unknown potentials but only 4 basic equations.",
    explanation: "Setting u_1 = 0 leaves 5 unknowns with only 4 equations, leaving at least one row or column multiplier undetermined.",
    hint: "More unknowns than equations → cannot solve for all u and v.",
    level: "expert",
    codeExample: "Unknowns (m + n = 6) > Equations (4) => Solvers stall without epsilon."
  },
  {
    question: "How does testing for optimality prevent supply chain disruptions during peak demand seasons in Barrackpore and Kolkata?",
    shortAnswer: "By eliminating congested, high-cost bottleneck routes and redistributing goods through the most economically efficient transport corridors.",
    explanation: "Optimality testing uncovers hidden routing inefficiencies that create both financial losses and physical transport congestion.",
    hint: "Eliminates inefficient routes and streamlines flow.",
    level: "intermediate",
    codeExample: "Optimality Audit → Identifies hidden bottlenecks and high-cost routes."
  },
  {
    question: "If Mahima evaluates a transportation tableau and finds three negative opportunity costs: d_12 = -₹2, d_21 = -₹7, and d_32 = -₹4, which cell should enter the basis first according to standard Dantzig simplex rules?",
    shortAnswer: "Cell (2, 1) with the most negative opportunity cost (d_21 = -₹7).",
    explanation: "The most negative d_ij indicates the steepest rate of cost decrease per unit transferred, offering the greatest immediate marginal improvement.",
    hint: "Pick the cell with the most negative opportunity cost.",
    level: "moderate",
    codeExample: "Entering Cell = argmin { d_ij | d_ij < 0 } = (2, 1) with d_21 = -₹7."
  },
  {
    question: "Can an Initial Basic Feasible Solution generated by Matrix Minima be already optimal?",
    shortAnswer: "Yes, in some instances Matrix Minima happens to find the optimal basis directly, but this can ONLY be confirmed by executing an optimality test.",
    explanation: "Without computing non-basic opportunity costs d_ij, an analyst cannot know whether a solution is optimal or merely a local minimum.",
    hint: "It might be optimal, but only an optimality test can confirm it.",
    level: "moderate",
    codeExample: "Verification Rule: Always test d_ij >= 0 to confirm optimality."
  },
  {
    question: "What is the historical significance of the MODI method developed by G. B. Dantzig and later popularized in operations research?",
    shortAnswer: "It adapted the Linear Programming Simplex Method specifically for transportation matrices, replacing matrix inversion with rapid dual potential additions.",
    explanation: "MODI (Modified Distribution) revolutionized logistics computation by solving transportation linear programs in fraction of the time required by general simplex tableau inversion.",
    hint: "Specialized simplex adaptation for bipartite transportation networks.",
    level: "intermediate",
    codeExample: "MODI = Transportation Simplex with O(m+n) multiplier updates."
  },
  {
    question: "Suppose Abhronila in Jadavpur manages a textbook printing distribution network. An untested NWCR plan gives Z = ₹14,200. After MODI optimization, Z drops to ₹9,400. What is the annual financial savings on a monthly dispatch schedule?",
    shortAnswer: "₹57,600 annual savings ( (₹14,200 - ₹9,400) * 12 months = ₹4,800 * 12 = ₹57,600 ).",
    explanation: "Monthly savings = ₹4,800. Across 12 months, the optimality test saves ₹57,600 in logistics expenditure.",
    hint: "Monthly savings ₹4,800 * 12 months.",
    level: "moderate",
    codeExample: "Annual Savings = (14200 - 9400) * 12 = ₹57,600"
  },
  {
    question: "Why is the term 'Improvement Index' often used interchangeably with 'Opportunity Cost' in optimality testing literature?",
    shortAnswer: "Because the index indicates the exact unit improvement (reduction) in the objective function Z if that non-basic cell is activated.",
    explanation: "If index = -₹5, total cost improves by ₹5 for each unit shipped along that route.",
    hint: "Index measures how much the total cost improves.",
    level: "intermediate",
    codeExample: "Improvement Index I_ij = -d_ij = (u_i + v_j) - c_ij"
  },
  {
    question: "What is the relationship between the number of non-basic cells and the number of opportunity cost evaluations in an m x n transportation tableau?",
    shortAnswer: "There are exactly (m * n) - (m + n - 1) = (m - 1)(n - 1) non-basic cells, and each one requires exactly one opportunity cost evaluation d_ij.",
    explanation: "In a 3x4 tableau, there are (3-1)(4-1) = 2 * 3 = 6 non-basic cells to test for optimality.",
    hint: "(m - 1) * (n - 1) opportunity costs to compute.",
    level: "expert",
    codeExample: "Evaluations Count = (m - 1) * (n - 1)"
  },
  {
    question: "In a 4x4 matrix, how many opportunity costs d_ij must be evaluated during each optimality test?",
    shortAnswer: "9 opportunity costs ( (4 - 1) * (4 - 1) = 3 * 3 = 9 non-basic cells ).",
    explanation: "Total cells = 16. Basic cells = 4 + 4 - 1 = 7. Non-basic cells to evaluate = 16 - 7 = 9.",
    hint: "(4 - 1) * (4 - 1) = 9.",
    level: "moderate",
    codeExample: "Non-Basic Evaluations = 3 * 3 = 9"
  },
  {
    question: "Why does the presence of a ₹0 dummy row or column not change the necessity of performing an optimality test?",
    shortAnswer: "Because dummy allocations determine which origins or destinations absorb deficits or surpluses, and suboptimal dummy assignments increase real shipping costs elsewhere.",
    explanation: "Optimality testing optimizes both real routes and dummy allocations to minimize net active freight spending.",
    hint: "Dummy placement directly impacts real route allocations.",
    level: "expert",
    codeExample: "Dummy Cells participate in dual equations: u_dummy + v_j = 0."
  },
  {
    question: "What is a 'local optimum' vs a 'global optimum', and why does linear programming guarantee that a local optimum in transportation is ALWAYS globally optimal?",
    shortAnswer: "Because the transportation feasible region is a convex polyhedron and the objective function is linear, ensuring that any local minimum where all d_ij >= 0 is unconditionally the global minimum.",
    explanation: "Convexity guarantees that no lower-cost isolated valleys exist elsewhere in the feasible space.",
    hint: "Linearity and convexity guarantee local minimum == global minimum.",
    level: "expert",
    codeExample: "Theorem: In LP, Local Optimum <=> Global Optimum."
  },
  {
    question: "Suppose Debangshu solves a problem using VAM and calculates all d_ij values, finding min(d_ij) = 0. Should he perform a loop adjustment pivot?",
    shortAnswer: "No, the current solution is already optimal; pivoting into a cell with d_ij = 0 will only produce an alternate optimal solution with the identical total cost Z.",
    explanation: "Since no d_ij < 0 exists, current cost Z is already minimal.",
    hint: "min(d_ij) = 0 means solution is optimal (with alternate optima).",
    level: "moderate",
    codeExample: "min(d_ij) === 0 => Optimal; pivot is optional for alternative basis."
  },
  {
    question: "What is the primary danger of relying on computer intuition or visual inspection of shipping costs rather than formal optimality testing?",
    shortAnswer: "Human intuition is easily misled by isolated cheap cells, missing subtle closed multi-route trade-offs that unlock lower network-wide costs.",
    explanation: "A complex network can reduce overall cost by increasing one local rate to unlock massive savings across three other interconnected routes.",
    hint: "Intuition misses multi-hop bipartite loop trade-offs.",
    level: "intermediate",
    codeExample: "Network trade-off: +₹2 on route A unlocks -₹10 on routes B and C."
  },
  {
    question: "How does the MODI optimality test verify that no closed loops can improve the current solution without actually drawing all possible loops?",
    shortAnswer: "By solving the dual potential equations u_i + v_j = c_ij, which algebraically encapsulate the net cost change around any hypothetical closed loop through d_ij = c_ij - u_i - v_j.",
    explanation: "The potential difference d_ij mathematically equals the sum of alternating signs around the unique loop associated with cell (i, j).",
    hint: "Dual potentials algebraically represent the loop sum for every cell.",
    level: "expert",
    codeExample: "Loop Theorem: d_ij = sum of alternating costs around loop(i, j)."
  },
  {
    question: "If an operations team is under intense time pressure, why is testing optimality via MODI still recommended before finalizing logistics contracts?",
    shortAnswer: "Because a MODI check takes only 2-3 minutes manually (or milliseconds via software) and routinely uncovers thousands of rupees in preventable freight expenses.",
    explanation: "The return on time invested in an optimality test is extraordinarily high.",
    hint: "High ROI: few minutes of calculation saves massive budget percentages.",
    level: "intermediate",
    codeExample: "Time investment: 2 mins → Payoff: 10-30% freight budget reduction."
  },
  {
    question: "What is the summary motto that students in Sukanta Hui's class remember regarding Initial Solutions and Optimality?",
    shortAnswer: "'An IBFS gets your trucks moving; an Optimality Test ensures your business stays profitable!'",
    explanation: "Feasibility guarantees operational viability; optimality guarantees economic supremacy.",
    hint: "Feasibility enables delivery; optimality maximizes profit.",
    level: "moderate",
    codeExample: "Motto: Feasibility (IBFS) + Optimality (MODI) = Supply Chain Mastery."
  },
  {
    question: "What is the ultimate goal of mastering Topic 0 in the MODI Optimality module?",
    shortAnswer: "To deeply grasp WHY optimality testing is mandatory, recognize the financial and operational limitations of IBFS heuristics, and prepare to compute u-v dual multipliers with complete conceptual clarity.",
    explanation: "Understanding the motivation behind optimality testing transforms mechanical arithmetic into powerful strategic optimization insight.",
    hint: "Understand the economic and mathematical necessity of testing optimality.",
    level: "expert",
    codeExample: "Outcome: Full mastery of the need for optimality testing and dual potentials."
  }
];

export default questions;
