/**
 * Java Core Tutorial - Module 006_005: Type Erasure & Generics Limitations
 * Topic 4: Inspecting Bytecode with 'javap -c -v': Observing Erased Types & Bridge Flags
 * Educator: Sukanta Hui | Academic Hub: Barrackpore, West Bengal
 */

package com.coderaccotax.javatutorial.generics;

public class JavapBytecodeDisassemblyDemo {

    public static class ExampleHolder<T extends CharSequence> {
        private T value;
        public void setValue(T val) { this.value = val; }
        public T getValue() { return value; }
    }

    public static void main(String[] args) {
        System.out.println("==========================================================================");
        System.out.println(" TOPIC 4: BYTECODE DISASSEMBLY VIA javap - BARRACKPORE");
        System.out.println("==========================================================================\n");

        System.out.println(">>> HOW TO DISASSEMBLE & VERIFY TYPE ERASURE USING JAVAP:");
        System.out.println("  Command: 'javap -c -v ExampleHolder.class'");
        System.out.println();
        System.out.println(">>> TYPICAL BYTECODE OUTPUT GENERATED BY JAVAC:");
        System.out.println("  public void setValue(java.lang.CharSequence);");
        System.out.println("    descriptor: (Ljava/lang/CharSequence;)V");
        System.out.println("    flags: (0x0001) ACC_PUBLIC");
        System.out.println("    Code:");
        System.out.println("       0: aload_0");
        System.out.println("       1: aload_1");
        System.out.println("       2: putfield      #7 // Field value:Ljava/lang/CharSequence;");
        System.out.println("       5: return");
        System.out.println();
        System.out.println(">>> OBSERVATIONS:");
        System.out.println("  1. 'T' was completely erased to 'java.lang.CharSequence' in field and method descriptors.");
        System.out.println("  2. Bridge methods will show flag: 'ACC_BRIDGE, ACC_SYNTHETIC'.");
        System.out.println("  3. Signature attribute preserves generic metadata for IDE reflection!");

        System.out.println("\n==========================================================================");
    }
}