// File: src/components/topics/topic1_files/topic1_questions.js
const questions = [
  {
    question: "What is the main purpose of flow control at the Data Link Layer?",
    shortAnswer: "To prevent a fast sender from overwhelming a slow receiver's buffer.",
    explanation: "Flow control ensures the sender transmits data at a rate the receiver can handle. Without it, frames would be dropped, leading to retransmissions and poor performance.",
    hint: "Think about a water pipe: if the sending end has high pressure and the receiving end has a small tank, you need a valve to regulate flow.",
    level: "basic",
    codeExample: "// In TCP, the 'rwnd' field in the segment header advertises the receiver's available buffer space."
  },
  {
    question: "Describe Stop-and-Wait flow control in one sentence.",
    shortAnswer: "The sender transmits one frame and waits for an acknowledgment before sending the next.",
    explanation: "This is the simplest form of flow control. It uses a 1‑bit sequence number (0 or 1) to distinguish duplicate frames. The sender's timer ensures retransmission if an ACK is lost.",
    hint: "It's like a conversation where you say one sentence and wait for the other person to nod before continuing.",
    level: "basic",
  },
  {
    question: "What is the fundamental limitation of Stop-and-Wait on high bandwidth‑delay product (BDP) links?",
    shortAnswer: "The sender spends most of its time idle, waiting for ACKs, so the link utilization is extremely low.",
    explanation: "BDP = bandwidth × RTT. In Stop‑and‑Wait, only one frame is in flight. The maximum throughput = frame size / RTT, which is much smaller than the link bandwidth for large BDP.",
    hint: "Calculate: If RTT = 100 ms and frame = 1500 bytes, throughput max = 0.12 Mbps even on a 1 Gbps link.",
    level: "moderate",
  },
  {
    question: "How does a sliding window protocol improve throughput compared to Stop-and-Wait?",
    shortAnswer: "It allows up to W frames to be sent without waiting for ACKs, keeping the pipeline full.",
    explanation: "As long as the sender has space in its window, it can transmit. ACKs slide the window forward, letting new frames be transmitted immediately. The window size determines the maximum number of outstanding frames.",
    hint: "Imagine an assembly line: Stop‑and‑Wait makes one item, stops, gets approval, then moves. Sliding window keeps 10 items moving at once.",
    level: "moderate",
  },
  {
    question: "What is the relationship between window size (W), frame transmission time (T_f), and round‑trip time (RTT) for full link utilization?",
    shortAnswer: "We need W × T_f ≥ RTT (or equivalently, W ≥ RTT / T_f).",
    explanation: "The time from sending the first bit of the first frame to receiving its ACK is about RTT. During that time, the sender must keep transmitting frames. The number of frames that can be sent in RTT is RTT / T_f, so the window must be at least that large.",
    hint: "Think of a train: the window size is the number of train cars that can be on the track before the first car reaches the destination and an ACK comes back.",
    level: "expert",
  },
  {
    question: "Why does Stop-and-Wait need a 1‑bit sequence number, while sliding window needs more bits?",
    shortAnswer: "Stop‑and‑Wait only needs to distinguish between a new frame and a retransmission of the previous one. Sliding window may have many outstanding frames, so it needs a larger sequence number space to avoid ambiguity.",
    explanation: "With a window size W, the sequence numbers must be at least 2W for Go‑Back‑N (or W+1 for Selective Repeat) to correctly handle wrap‑around and distinguish new from old frames.",
    hint: "If you only have numbers 0 and 1, you can't label 3 outstanding frames uniquely.",
    level: "moderate",
  },
  {
    question: "What is a cumulative ACK in the context of sliding window?",
    shortAnswer: "An ACK that acknowledges all frames up to a certain sequence number, not just the most recent one.",
    explanation: "If a receiver receives frames 0,1,2 correctly, it can send an ACK with sequence number 3, meaning 'I have received all frames up to 2, next expected is 3'. This reduces ACK traffic and simplifies recovery.",
    hint: "Instead of saying 'I got frame 1', 'I got frame 2', you say 'I got everything up to frame 2'.",
    level: "moderate",
  },
  {
    question: "Compare Go‑Back‑N and Selective Repeat in terms of retransmission efficiency.",
    shortAnswer: "Go‑Back‑N retransmits all frames from the lost frame onward, even if later frames were received correctly. Selective Repeat retransmits only the lost frame(s).",
    explanation: "Go‑Back‑N is simpler (receiver only needs to buffer in order) but wastes bandwidth on high error links. Selective Repeat requires more buffer and logic but is more efficient.",
    hint: "Go‑Back‑N is like re‑reading an entire paragraph because you missed one word. Selective Repeat is like only re‑reading the missed word.",
    level: "expert",
  },
  {
    question: "What is a 'timer' used for in flow control protocols?",
    shortAnswer: "To detect lost frames or ACKs and trigger retransmission.",
    explanation: "After sending a frame, the sender starts a timer. If the ACK does not arrive before the timer expires, the sender assumes the frame or its ACK was lost and retransmits the frame (or multiple frames, depending on the protocol).",
    hint: "It's like setting an alarm: if you don't get a reply by the time the alarm rings, you call again.",
    level: "basic",
  },
  {
    question: "What is a 'spurious timeout' and why is it harmful?",
    shortAnswer: "A timeout that occurs even though the frame and its ACK were not lost, just delayed due to network congestion or variable latency.",
    explanation: "Spurious timeouts cause unnecessary retransmissions, wasting bandwidth and increasing congestion. Modern protocols use algorithms like Eifel detection or RTT estimation with high variance to avoid them.",
    hint: "It's like assuming your friend didn't get your text because they took 5 minutes to reply, so you resend it – now they get two copies.",
    level: "expert",
  },
  {
    question: "How does TCP's advertised window (rwnd) relate to Data Link flow control?",
    shortAnswer: "rwnd is a sliding window mechanism at the transport layer, but the principle is identical to Data Link sliding window – it reflects the receiver's available buffer space.",
    explanation: "TCP uses flow control to prevent the sender from overwhelming the receiving application. The window size is carried in every TCP segment. The Data Link layer may also have its own flow control (e.g., Ethernet PAUSE frames), but TCP's is end‑to‑end.",
    hint: "Both layers solve the same problem but at different scales: per‑hop at Data Link, end‑to‑end at Transport.",
    level: "moderate",
  },
  {
    question: "What is the 'bandwidth-delay product' (BDP) and why does it matter for flow control?",
    shortAnswer: "BDP = bandwidth × RTT, the total amount of data that can be in flight (in the pipe) at any time.",
    explanation: "To fully utilize a link, the sender's window must be at least as large as the BDP. If the window is smaller, the sender will run out of data to send while waiting for ACKs, leaving the link idle.",
    hint: "BDP is the 'volume' of the pipe. Your flow control window is the amount of water you can pour in before the first drop reaches the other end.",
    level: "expert",
  },
  {
    question: "Why can't Stop-and-Wait be used for high‑speed satellite links? Give a numerical example.",
    shortAnswer: "Because its maximum throughput is frame_size / RTT. For a satellite (RTT ≈ 500 ms, frame=1500 bytes), throughput ≈ 24 kbps – far below modern speeds.",
    explanation: "Even if the link is 50 Mbps, Stop‑and‑Wait limits you to 24 kbps. That's a waste of 99.95% of the capacity.",
    hint: "Calculate throughput = (frame size * 8) / RTT. For 1500 bytes = 12000 bits / 0.5 s = 24 kbps.",
    level: "moderate",
  },
  {
    question: "What is 'piggybacking' in flow control?",
    shortAnswer: "Attaching an acknowledgment to an outgoing data frame instead of sending a separate ACK frame.",
    explanation: "In full‑duplex communication, both sides may have data to send. Piggybacking reduces the number of frames and improves efficiency. The receiver sets a bit in the header of its data frame to acknowledge previously received data.",
    hint: "Instead of sending a separate 'got it' card, you write 'got it' on the back of the next card you send.",
    level: "moderate",
  },
  {
    question: "What is the 'NAK' (Negative Acknowledgment) and when is it used?",
    shortAnswer: "A NAK indicates that a frame was received but with an error (or out‑of‑order in some protocols).",
    explanation: "NAKs can speed up recovery: the receiver immediately asks for retransmission instead of waiting for the sender's timer to expire. However, NAKs can also cause duplicates if the NAK itself is lost.",
    hint: "ACK = 'got it, good'. NAK = 'got it, but it's corrupt, please resend'.",
    level: "moderate",
  },
  {
    question: "Why does Selective Repeat require a larger receiver buffer than Go‑Back‑N?",
    shortAnswer: "Selective Repeat must buffer out‑of‑order frames that arrive before the missing one(s), while Go‑Back‑N discards them.",
    explanation: "In Go‑Back‑N, if frame 2 is lost, the receiver discards frames 3,4,... and only sends ACKs for frame 1. In Selective Repeat, the receiver stores frames 3,4,... and asks only for frame 2. This saves bandwidth but requires buffer space for the out‑of‑order frames.",
    hint: "Selective Repeat is like keeping later puzzle pieces while you wait for the missing piece. Go‑Back‑N throws them away and asks for all pieces again.",
    level: "expert",
  },
  {
    question: "What is the maximum window size for Go‑Back‑N given n bits for sequence numbers?",
    shortAnswer: "Maximum window size = 2^n - 1.",
    explanation: "Using 2^n would cause ambiguity when the sequence numbers wrap around. For example, with n=3 (seq 0-7), window=7. If window=8, the sender could send frames 0-7, all outstanding. If all ACKs are lost, after timeout it would retransmit frame 0, but the receiver might think it's a new frame 0 after wrapping, causing duplicate acceptance.",
    hint: "The '1' ensures that the window never fully covers the sequence number space, avoiding the wrap‑around ambiguity.",
    level: "expert",
  },
  {
    question: "What is the maximum window size for Selective Repeat with n bits?",
    shortAnswer: "Maximum window size = 2^(n-1).",
    explanation: "Selective Repeat requires half the sequence number space to distinguish between old and new frames because of the possibility of out‑of‑order storage. For n=3 (0-7), max window = 4.",
    hint: "If window size were larger, a new frame might have the same sequence number as an old frame still buffered, causing confusion.",
    level: "expert",
  },
  {
    question: "How does the receiver's 'advertised window' prevent buffer overflow?",
    shortAnswer: "The receiver includes its current free buffer size (rwnd) in every ACK. The sender must never have more than rwnd bytes outstanding.",
    explanation: "As the application consumes data, the receiver window opens (increases). As new data arrives, the window closes. This dynamic feedback is the core of TCP's flow control.",
    hint: "It's like a water tank: the sender sees a sign 'available capacity: 1000 L' and must not send more than that until the sign updates.",
    level: "moderate",
  },
  {
    question: "What is 'head‑of‑line blocking' in the context of flow control?",
    shortAnswer: "A situation where a lost or delayed frame prevents delivery of subsequent frames even if they are intact, because the receiver expects in‑order delivery.",
    explanation: "In Go‑Back‑N, a single lost frame blocks all later frames from being delivered to the higher layer. Even in Selective Repeat, if the flow control window is stuck waiting for that one frame, it can block.",
    hint: "One slow car at the front of a tunnel blocks all cars behind it, even if they are fast.",
    level: "expert",
  },
  {
    question: "Explain the concept of 'self‑clocking' in sliding window protocols.",
    shortAnswer: "The return of ACKs naturally paces the sender: for each ACK, the sender may send a new frame. This keeps the transmission rate matched to the network's capacity.",
    explanation: "The sender doesn't need an external clock; the arrival of ACKs triggers transmission. If the network is congested, ACKs delay, and the sender automatically slows down.",
    hint: "It's like a bucket brigade: the next person can only throw another bucket when the previous empty bucket comes back.",
    level: "expert",
  },
  {
    question: "What is a 'duplicate ACK' and what does it indicate?",
    shortAnswer: "A duplicate ACK is an ACK that repeats the same acknowledgment number. It usually indicates a segment or frame was lost or reordered.",
    explanation: "When a receiver gets an out‑of‑order segment, it immediately sends a duplicate ACK for the last in‑order segment. Three duplicate ACKs often trigger fast retransmit in TCP.",
    hint: "If you keep saying 'I've received up to packet 5' three times, it suggests packet 6 might be lost.",
    level: "moderate",
  },
  {
    question: "What is the 'fast retransmit' algorithm?",
    shortAnswer: "A heuristic where the sender retransmits a lost segment after receiving three duplicate ACKs, without waiting for a timeout.",
    explanation: "This improves performance because waiting for a timeout would be too slow. The three duplicate ACKs serve as a strong hint that a segment was lost, not just delayed.",
    hint: "Don't wait for the alarm to ring; if three bystanders say 'we still haven't seen the bus', send another bus immediately.",
    level: "expert",
  },
  {
    question: "How does flow control differ from congestion control?",
    shortAnswer: "Flow control prevents sender from overwhelming receiver. Congestion control prevents sender from overwhelming the network (routers, links).",
    explanation: "Flow control is end‑to‑end, based on receiver's buffer. Congestion control is network‑aware, based on packet loss or ECN. Both use window mechanisms but with different goals.",
    hint: "Flow control = 'can the receiver handle this pace?' Congestion control = 'can the network handle this pace?'",
    level: "moderate",
  },
  {
    question: "What does the term 'window scaling' mean in TCP (RRC 7323)?",
    shortAnswer: "An option that allows the TCP window size to be larger than 64 KB by using a scaling factor.",
    explanation: "Modern high‑speed links have BDPs larger than 64 KB. Window scaling shifts the window field left by a scale factor (0–14), allowing windows up to 1 GB. This is essential for 10 Gbps+ links.",
    hint: "It's like using a multiplier: you can advertise a window of 65,535 but the scale factor says 'multiply by 8' → 524,280 bytes.",
    level: "expert",
  },
  {
    question: "Why does IEEE 802.11 (Wi‑Fi) use a different flow control approach than Ethernet?",
    shortAnswer: "Wi‑Fi uses a ‘frame aggregation’ and block acknowledgment (Block ACK) mechanism, which is a form of sliding window with selective repeat adapted for the wireless medium.",
    explanation: "Due to higher error rates, Wi‑Fi needs efficient retransmission of individual MPDUs. Block ACK allows the receiver to acknowledge multiple frames in one response, reducing overhead.",
    hint: "Wireless is lossy; so selective repeat is much better than Go‑Back‑N. Block ACK groups many ACKs together.",
    level: "expert",
  },
  {
    question: "What is the 'Maximum Segment Lifetime' (MSL) and how does it relate to sequence numbers?",
    shortAnswer: "MSL is the maximum time a segment can exist in the network before being discarded. Sequence numbers must not wrap around within MSL to avoid old duplicates confusing the receiver.",
    explanation: "If sequence numbers wrap too quickly, a delayed duplicate frame from a previous connection might arrive and be accepted as new. That's why high‑speed protocols use larger sequence number spaces or timestamps.",
    hint: "Think of sequence numbers as 'age stamps'. If numbers repeat too soon, an old packet could pretend to be new.",
    level: "expert",
  },
  {
    question: "What is the difference between 'ACK clock' and 'rate‑based flow control'?",
    shortAnswer: "ACK clock is the natural pacing derived from sliding window ACK arrivals. Rate‑based flow control uses a separate timer or token bucket to shape the transmission rate independently of ACKs.",
    explanation: "ACK clock works well when ACKs are not delayed. Rate‑based control is used in protocols like UDP‑based streaming or in some high‑speed networks where ACK clock may be too bursty.",
    hint: "ACK clock = 'I go when you tell me you're ready'. Rate‑based = 'I send at exactly X packets per second regardless of ACKs'.",
    level: "expert",
  },
  {
    question: "How does the ‘silly window syndrome’ (SWS) affect flow control and how is it avoided?",
    shortAnswer: "SWS occurs when the receiver advertises very small increments of window (e.g., 1 byte), causing the sender to transmit many tiny segments, wasting overhead.",
    explanation: "Solutions: receivers should not advertise small windows (delayed ACK, Nagle's algorithm on sender side, or 'clumping' of data). The goal is to avoid many small transmissions.",
    hint: "It's like making many phone calls to say one word each time. Instead, wait until you have a sentence.",
    level: "expert",
  },
  {
    question: "Can flow control be implemented without sequence numbers? If so, how?",
    shortAnswer: "Yes, using a simple credit‑based scheme (e.g., XON/XOFF, Ethernet PAUSE) where the receiver sends a ‘stop’ signal after its buffer fills.",
    explanation: "These are low‑level, per‑hop mechanisms. They don't require numbers because they are not error‑recovery protocols – they assume no loss and just throttle the sender. Once the buffer empties, a ‘start’ signal is sent.",
    hint: "Like a traffic light: red means stop, green means go – no numbers needed.",
    level: "moderate",
  },
  {
    question: "What is the role of the 'P' (push) flag in protocols like HDLC and how does it affect flow?",
    shortAnswer: "The P/F (Poll/Final) bit is used to force an immediate response (e.g., a status report or ACK) from the receiver, often for flow control or error recovery.",
    explanation: "A primary station can poll a secondary; the secondary responds with the Final bit set. This can be used to get a quick indication of the receiver's window status.",
    hint: "It's like saying 'Hey, I need an answer right now – don't wait for piggybacking'.",
    level: "expert",
  }
];

export default questions;