const questions = [
  {
    question: "What is the primary reason for having a computer network?",
    shortAnswer: "To share resources and enable communication between devices.",
    explanation: "Networks exist to eliminate isolation, allowing devices to share hardware (printers, storage), software, and data, while enabling seamless communication.",
    hint: "Think about how you share a file with a friend without using a USB drive.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does networking reduce costs for an organisation?",
    shortAnswer: "By centralising expensive resources like servers and printers, and sharing them among many users.",
    explanation: "Instead of buying a printer for each employee, a network printer serves everyone. Centralised software licensing also reduces per-seat costs.",
    hint: "Compare buying 50 printers vs one high-speed printer connected to a network.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is resource sharing in networking?",
    shortAnswer: "The ability to use hardware, software, or data from any connected device.",
    explanation: "Examples: sharing a printer, accessing a shared drive, or using a common database.",
    hint: "When you print to the lab printer from your own computer, you're using resource sharing.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Why is centralised data management important?",
    shortAnswer: "It simplifies backup, security, and access control.",
    explanation: "Data stored on a central server is easier to back up, monitor for threats, and manage permissions compared to scattered local drives.",
    hint: "Think of a school where all report cards are stored on one secure server.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What role does networking play in communication?",
    shortAnswer: "It enables email, instant messaging, video calls, and collaborative platforms.",
    explanation: "Networks carry communication data in real time, connecting people across rooms or continents.",
    hint: "How do you talk to a friend in another city? Through the network.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is remote access and why is it needed?",
    shortAnswer: "Remote access allows users to connect to a network from outside the physical location.",
    explanation: "It enables telecommuting, accessing files from home, and managing servers remotely.",
    hint: "Working from home while accessing office files uses remote access.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does networking improve collaboration?",
    shortAnswer: "By allowing multiple users to work on the same documents and projects simultaneously.",
    explanation: "Tools like Google Docs, shared repositories (Git), and project management software rely on networks.",
    hint: "Think about how you and your classmates edit a presentation together.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is scalability in networking?",
    shortAnswer: "The ability to grow the network by adding new users and devices without major redesign.",
    explanation: "A scalable network can handle increased traffic and new nodes gracefully.",
    hint: "Adding a new computer to your home Wi-Fi is an example of scaling up.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Why is security a key consideration when networking?",
    shortAnswer: "To protect sensitive data from unauthorised access and cyber threats.",
    explanation: "Networks expose data to potential interception; hence firewalls, encryption, and authentication are essential.",
    hint: "Without security, anyone on the network could potentially see your files.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the difference between a standalone computer and a networked one?",
    shortAnswer: "A standalone works in isolation; a networked one can communicate and share resources.",
    explanation: "Networked computers can access shared printers, files, and the internet, while standalone computers are limited to their own hardware.",
    hint: "A standalone computer is like an island; a networked one is part of a city.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a server in the context of networking needs?",
    shortAnswer: "A server is a computer that provides services (files, printing, email) to other devices on the network.",
    explanation: "Servers are the backbone of most networks, fulfilling requests from clients.",
    hint: "When you open a webpage, a server sends you the page.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "Why do businesses prefer client-server networks over peer-to-peer?",
    shortAnswer: "Client-server offers centralised management, security, and scalability.",
    explanation: "With client-server, administrators can control access, back up data centrally, and handle many users efficiently.",
    hint: "Large organisations need central control – peer-to-peer works for small groups.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is bandwidth and why is it a critical need?",
    shortAnswer: "Bandwidth is the capacity of a network to transmit data, measured in bps.",
    explanation: "Insufficient bandwidth causes slow performance, affecting productivity and user experience.",
    hint: "High bandwidth = fast downloads; low bandwidth = buffering.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is network redundancy and why is it needed?",
    shortAnswer: "Redundancy means having backup links and devices to prevent downtime.",
    explanation: "If one path fails, traffic can be rerouted. Critical for hospitals, banks, and online services.",
    hint: "Think of having a spare tire in your car – you need it when the primary fails.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does a network support data backup?",
    shortAnswer: "By allowing data to be automatically copied from local devices to a central backup server.",
    explanation: "Centralised backup ensures that even if a device is lost, data remains safe and recoverable.",
    hint: "Your laptop's files can be backed up to the cloud over the network.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the purpose of network policies?",
    shortAnswer: "To define rules for acceptable use, access permissions, and security protocols.",
    explanation: "Policies ensure that users behave responsibly and that the network remains secure and efficient.",
    hint: "Your school may have an AUP (Acceptable Use Policy) for the computer lab.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a VLAN and why would you need it?",
    shortAnswer: "A Virtual LAN logically segments a physical network into separate broadcast domains.",
    explanation: "VLANs improve security, performance, and management by isolating traffic (e.g., separating guest Wi-Fi from internal network).",
    hint: "It's like having separate rooms in a single building – each with its own security.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does networking facilitate e-commerce?",
    shortAnswer: "By connecting customers, web servers, payment gateways, and inventory systems.",
    explanation: "Online shopping relies on multiple network interactions: browsing, adding to cart, payment processing, order confirmation.",
    hint: "When you buy a book online, your request travels through many networks.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is QoS (Quality of Service) and why is it needed?",
    shortAnswer: "QoS prioritises critical traffic (e.g., VoIP, video) over less important traffic.",
    explanation: "It ensures that real-time applications don't suffer from delays caused by bulk downloads.",
    hint: "You want your video call to be clear even if someone is downloading a large file.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "Why is network documentation a 'need' for professionals?",
    shortAnswer: "Documentation provides a clear reference for troubleshooting, planning, and knowledge transfer.",
    explanation: "Network diagrams, IP lists, and configuration files save hours when problems occur.",
    hint: "Imagine fixing a network without knowing what is connected – documentation is your map.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the need for network testing and monitoring?",
    shortAnswer: "To detect issues, measure performance, and ensure availability.",
    explanation: "Tools like ping, traceroute, and SNMP help identify failures, bottlenecks, and security breaches.",
    hint: "Monitoring is like a health checkup for your network.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does networking support disaster recovery?",
    shortAnswer: "By replicating data to off-site locations and providing failover mechanisms.",
    explanation: "Networks enable real-time replication of critical data to backup data centers, ensuring business continuity.",
    hint: "If a fire destroys one office, the network connects to a backup site with the same data.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the need for network segmentation?",
    shortAnswer: "To improve security and performance by dividing a network into smaller segments.",
    explanation: "Segmentation limits the spread of breaches and reduces congestion by localising traffic.",
    hint: "Think of watertight compartments in a ship – if one leaks, the others stay safe.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "Why is low latency critical in some networks?",
    shortAnswer: "For real-time applications like stock trading, telemedicine, and gaming.",
    explanation: "High latency can ruin user experience and cause financial losses in high-frequency trading.",
    hint: "A few milliseconds can make a huge difference in a fast-paced stock market.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of a DMZ (Demilitarised Zone) in networking?",
    shortAnswer: "A DMZ is a subnetwork that exposes external-facing services (web, email) to the public while protecting the internal network.",
    explanation: "It adds an extra layer of security. If a public server is compromised, the internal network remains safe.",
    hint: "It's like a buffer zone between your home and the outside world.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does networking enable cloud computing?",
    shortAnswer: "By connecting users to remote data centers that provide on-demand computing resources.",
    explanation: "Networks are the pipes that deliver cloud services – without them, cloud computing wouldn't exist.",
    hint: "When you access Google Drive, you're using a network to reach a cloud server.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the need for network encryption (e.g., VPN, HTTPS)?",
    shortAnswer: "To protect data from eavesdropping and tampering during transmission.",
    explanation: "Encryption ensures that sensitive information (passwords, credit cards) remains confidential.",
    hint: "Locking your data in a box while it travels across the internet.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "Why is the concept of 'convergence' important in networking?",
    shortAnswer: "Convergence allows voice, video, and data to travel over the same network infrastructure.",
    explanation: "It reduces costs and simplifies management by using one network for everything (VoIP, IPTV, traditional data).",
    hint: "Instead of separate phone and data lines, everything runs on IP.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are the networking needs of the Internet of Things (IoT)?",
    shortAnswer: "Low-power, reliable connectivity with support for many devices and small data packets.",
    explanation: "IoT devices (sensors, smart appliances) require lightweight protocols like MQTT and often use mesh networks.",
    hint: "Think of a smart home where everything from bulbs to locks is connected.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does networking support mobile workforce?",
    shortAnswer: "Through VPNs, wireless networks, and cloud-based applications accessible from anywhere.",
    explanation: "Mobile workers need secure, always-on connectivity to access corporate resources.",
    hint: "Employees working from cafes or home need reliable network access.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the fundamental trade-off in networking needs?",
    shortAnswer: "Performance vs. security – higher security often introduces overhead and latency.",
    explanation: "More encryption and filtering protect data but may slow down transmission; engineers must balance both.",
    hint: "A strongly locked door is very secure but takes longer to open.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;