// topic12_questions.js
// 30 FAQs on "Algorithm for Infix to Postfix" – basic to expert.

const questions = [
  {
    question: "What is the core data structure used in the infix‑to‑postfix algorithm?",
    shortAnswer: "A stack.",
    explanation: "The stack is used to hold operators and parentheses temporarily until they are output.",
    hint: "LIFO.",
    level: "basic",
    codeExample: "Stack<Character> stack = new Stack<>();",
  },
  {
    question: "What is the output of the algorithm?",
    shortAnswer: "A postfix expression string.",
    explanation: "The algorithm produces a string containing the postfix notation of the input infix expression.",
    hint: "It's the result.",
    level: "basic",
    codeExample: "String postfix = infixToPostfix(infix);",
  },
  {
    question: "How does the algorithm handle operands?",
    shortAnswer: "It appends them directly to the output.",
    explanation: "Operands maintain their relative order in postfix.",
    hint: "No stack needed for operands.",
    level: "basic",
    codeExample: "if (isOperand(token)) postfix.append(token);",
  },
  {
    question: "How are left parentheses handled?",
    shortAnswer: "They are pushed onto the stack.",
    explanation: "They act as markers for the start of a sub‑expression.",
    hint: "Push.",
    level: "basic",
    codeExample: "if (token == '(') stack.push(token);",
  },
  {
    question: "How are right parentheses handled?",
    shortAnswer: "Pop operators from the stack until a '(' is found; discard both.",
    explanation: "This ensures the sub‑expression is fully converted.",
    hint: "Pop until '('.",
    level: "basic",
    codeExample: "while (stack.peek() != '(') { postfix.append(stack.pop()); } stack.pop();",
  },
  {
    question: "How does the algorithm decide when to pop operators from the stack?",
    shortAnswer: "It pops while the top operator has higher or equal precedence (for left‑associative).",
    explanation: "This preserves the correct order of evaluation.",
    hint: "Higher or equal precedence.",
    level: "intermediate",
    codeExample: "while (precedence(stack.peek()) >= precedence(token)) { pop; }",
  },
  {
    question: "What is the role of associativity in the algorithm?",
    shortAnswer: "It determines whether equal precedence operators are popped before pushing the new one.",
    explanation: "Left‑associative operators pop equal precedence; right‑associative do not.",
    hint: "Left‑associative pops; right‑associative doesn't.",
    level: "advanced",
    codeExample: "if (isLeftAssociative(token) && precedence(stack.peek()) == precedence(token)) { pop; }",
  },
  {
    question: "What happens after all tokens have been processed?",
    shortAnswer: "All remaining operators in the stack are popped and appended to the output.",
    explanation: "This clears any operators still waiting.",
    hint: "Pop all.",
    level: "basic",
    codeExample: "while (!stack.isEmpty()) { postfix.append(stack.pop()); }",
  },
  {
    question: "What does the algorithm do if it encounters an invalid character?",
    shortAnswer: "It throws an exception or error.",
    explanation: "Invalid characters are not allowed in valid infix expressions.",
    hint: "Error handling.",
    level: "intermediate",
    codeExample: "throw new IllegalArgumentException(...);",
  },
  {
    question: "What is the time complexity of the algorithm?",
    shortAnswer: "O(n), where n is the length of the infix expression.",
    explanation: "Each token is processed once, and each operator is pushed and popped at most once.",
    hint: "Linear.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What is the space complexity?",
    shortAnswer: "O(n) in the worst case.",
    explanation: "The stack can hold up to the number of operators in the expression.",
    hint: "Linear.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "Can the algorithm handle multi‑character operands like 'var'?",
    shortAnswer: "Yes, if tokens are properly scanned (e.g., using a tokenizer).",
    explanation: "The basic algorithm assumes single‑character operands; for multi‑character, you need to tokenize differently.",
    hint: "Use a scanner.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "What is the difference between this algorithm and the Shunting‑yard algorithm?",
    shortAnswer: "They are essentially the same; the Shunting‑yard algorithm is the name given by Dijkstra.",
    explanation: "Dijkstra's algorithm includes both conversion and evaluation aspects.",
    hint: "Same.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What happens if there is a mismatched parenthesis?",
    shortAnswer: "The algorithm detects it and throws an error (extra ')' or leftover '(').",
    explanation: "The stack will be empty when encountering ')', or leftover '(' at the end.",
    hint: "Error condition.",
    level: "intermediate",
    codeExample: "if (stack.isEmpty() || stack.peek() != '(') { error; }",
  },
  {
    question: "Can the algorithm convert expressions with functions (e.g., sin, cos)?",
    shortAnswer: "With modifications, yes. Functions are treated as operators with highest precedence.",
    explanation: "You can extend the algorithm to handle function names and parentheses.",
    hint: "Extend the parser.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "How does the algorithm handle unary operators (e.g., -5)?",
    shortAnswer: "It requires special handling, usually by distinguishing unary minus from binary minus.",
    explanation: "This is often done by marking unary operators with a special symbol or using a different precedence.",
    hint: "Special case.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "What is the output for infix `A+B*C`?",
    shortAnswer: "`A B C * +`",
    explanation: "Multiplication has higher precedence, so B*C comes first, then +A.",
    hint: "Precedence.",
    level: "basic",
    codeExample: "A B C * +",
  },
  {
    question: "What is the output for infix `(A+B)*C`?",
    shortAnswer: "`A B + C *`",
    explanation: "Parentheses force addition first.",
    hint: "Parentheses override.",
    level: "basic",
    codeExample: "A B + C *",
  },
  {
    question: "What is the output for infix `A+B*C-D`?",
    shortAnswer: "`A B C * + D -`",
    explanation: "Multiplication first, then addition, then subtraction (left‑associative).",
    hint: "Order: * then + then -.",
    level: "intermediate",
    codeExample: "A B C * + D -",
  },
  {
    question: "What is the output for infix `A-B-C`?",
    shortAnswer: "`A B - C -`",
    explanation: "Subtraction is left‑associative, so (A-B)-C.",
    hint: "Left‑associative.",
    level: "basic",
    codeExample: "A B - C -",
  },
  {
    question: "What is the output for infix `A^B^C` (exponentiation is right‑associative)?",
    shortAnswer: "`A B C ^ ^`",
    explanation: "Right‑associative means A^(B^C), so postfix is A B C ^ ^.",
    hint: "Right‑associative.",
    level: "advanced",
    codeExample: "A B C ^ ^",
  },
  {
    question: "What is the output for infix `A*(B+C)-D/E`?",
    shortAnswer: "`A B C + * D E / -`",
    explanation: "Parentheses first, then multiplication, division, subtraction.",
    hint: "Follow precedence and parentheses.",
    level: "advanced",
    codeExample: "A B C + * D E / -",
  },
  {
    question: "What is the output for infix `A+B*C/D`?",
    shortAnswer: "`A B C * D / +`",
    explanation: "Multiplication and division are left‑associative: (B*C)/D, then add A.",
    hint: "Left‑associative for * and /.",
    level: "intermediate",
    codeExample: "A B C * D / +",
  },
  {
    question: "What is the output for infix `A*B+C/D`?",
    shortAnswer: "`A B * C D / +`",
    explanation: "Multiplication and division first, then addition.",
    hint: "Two separate computations then add.",
    level: "intermediate",
    codeExample: "A B * C D / +",
  },
  {
    question: "What is the output for infix `A*(B+C/D)`?",
    shortAnswer: "`A B C D / + *`",
    explanation: "Inside parentheses: C/D, then +B, then multiply by A.",
    hint: "Parentheses first.",
    level: "advanced",
    codeExample: "A B C D / + *",
  },
  {
    question: "Can the algorithm be modified to evaluate the expression directly?",
    shortAnswer: "Yes, by performing arithmetic when an operator is popped (instead of appending it to output).",
    explanation: "This is used in evaluators that compute the result of postfix expressions.",
    hint: "Evaluation on the fly.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "How does the algorithm handle spaces in the input?",
    shortAnswer: "It typically ignores spaces by skipping whitespace characters.",
    explanation: "Spaces are not part of the expression syntax.",
    hint: "Skip whitespace.",
    level: "basic",
    codeExample: "if (Character.isWhitespace(ch)) continue;",
  },
  {
    question: "What is the purpose of the `precedence` function?",
    shortAnswer: "To compare the precedence of two operators.",
    explanation: "It assigns a numeric value to each operator; higher value = higher precedence.",
    hint: "Comparison.",
    level: "intermediate",
    codeExample: "int precedence(char op) { ... }",
  },
  {
    question: "What is the purpose of the `isLeftAssociative` function?",
    shortAnswer: "To determine whether an operator evaluates left‑to‑right.",
    explanation: "It's needed to decide whether to pop equal precedence operators.",
    hint: "Associativity check.",
    level: "advanced",
    codeExample: "boolean isLeftAssociative(char op) { return op != '^'; }",
  },
  {
    question: "Is the algorithm deterministic?",
    shortAnswer: "Yes, for a given valid infix expression, it always produces the same postfix output.",
    explanation: "The algorithm follows strict rules with no ambiguity.",
    hint: "Deterministic.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "How can you test the algorithm?",
    shortAnswer: "Write unit tests with various infix expressions and compare the output to expected postfix.",
    explanation: "Test simple, complex, with parentheses, with different operators.",
    hint: "Test cases.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
];

export default questions;