// topic_hdlc_questions.js
const questions = [
  { question: "What does HDLC stand for?", shortAnswer: "High-Level Data Link Control", explanation: "ISO standard for bit-synchronous data link layer.", hint: "Think of link-level control.", level: "basic", codeExample: null },
  { question: "Name the three types of HDLC frames.", shortAnswer: "I-frame (Information), S-frame (Supervisory), U-frame (Unnumbered).", explanation: "I-frames carry data, S-frames control flow, U-frames handle link management.", hint: "I for Info, S for Supervisory, U for Unnumbered.", level: "basic", codeExample: null },
  { question: "What is the purpose of the flag field in HDLC?", shortAnswer: "To delimit the beginning and end of a frame (01111110).", explanation: "Flags are unique bit patterns that cannot appear inside the frame due to bit stuffing.", hint: "Look for 0x7E in hex dumps.", level: "basic", codeExample: null },
  { question: "Why is bit stuffing used in HDLC?", shortAnswer: "To ensure the flag pattern 01111110 never appears accidentally inside the data.", explanation: "After five consecutive 1s, a 0 is inserted; the receiver removes it.", hint: "Prevents false flag detection.", level: "intermediate", codeExample: null },
  { question: "What is the difference between an I‑frame and a U‑frame?", shortAnswer: "I‑frames carry user data and have sequence numbers; U‑frames are for link management and have no sequence numbers.", explanation: "U‑frames set up and disconnect links, while I‑frames transfer data.", hint: "I = Information, U = Unnumbered (connection management).", level: "intermediate", codeExample: null },
  { question: "What does an S‑frame do?", shortAnswer: "Supervisory frames provide flow and error control (ACK, NAK, REJ, RNR).", explanation: "They do not carry user data but manage the sliding window.", hint: "S = Supervisory (control).", level: "intermediate", codeExample: null },
  { question: "What is the typical size of the FCS in HDLC?", shortAnswer: "16-bit CRC (CRC‑16/CCITT) or 32-bit for enhanced reliability.", explanation: "FCS covers the address, control, and information fields.", hint: "Earlier HDLC used 16 bits, later optional 32 bits.", level: "advanced", codeExample: null },
  { question: "What are the three station types in HDLC?", shortAnswer: "Primary (controls link), Secondary (responds), Combined (peer-to-peer).", explanation: "Combined stations are used in ABM mode.", hint: "Primary = master, Secondary = slave, Combined = both.", level: "intermediate", codeExample: null },
  { question: "Describe the Asynchronous Balanced Mode (ABM).", shortAnswer: "Both stations are combined; each can initiate transmission and send commands/responses.", explanation: "Most common mode in modern implementations (e.g., LAPB).", hint: "Balanced = equal roles.", level: "advanced", codeExample: null },
  { question: "What is the purpose of the N(R) field in an I‑frame?", shortAnswer: "Next expected sequence number, used for piggybacked acknowledgements.", explanation: "It acknowledges all frames up to N(R)-1.", hint: "N(R) = acknowledgment.", level: "advanced", codeExample: null },
  // Add up to 30 questions
];
export default questions;