// topic1_files/topic1_questions.js
// Module 004_005: Server Logs, Slow Query Analysis & Performance Schema
// Topic 1: The Error Log: Configuration, Rotation, Diagnostic Messages, and Critical Alerts

const questions = [
  {
    question: "What is the primary role of the MySQL Error Log in production database management?",
    shortAnswer: "It serves as the definitive diagnostic journal recording server startup/shutdown sequences, fatal engine crashes, InnoDB crash recovery, hardware I/O errors, page corruption warnings, and aborted client connections.",
    explanation: "The error log is the first file inspected by DBAs to diagnose startup failures, unplanned restarts, or hardware anomalies.",
    hint: "Definitive diagnostic journal for crashes, engine errors, and server lifecycle.",
    level: "basic",
    codeExample: `-- Check error log path:
SHOW VARIABLES LIKE 'log_error';`
  },
  {
    question: "What are the 3 verbosity levels of `log_error_verbosity` in MySQL 8.0, and which is recommended for production?",
    shortAnswer: "`1` = Errors only; `2` = Errors and Warnings (Recommended for production); `3` = Errors, Warnings, and Informational Notes.",
    explanation: "Level 2 captures critical warnings (such as replication failures and connection aborts) without polluting disk partitions with high-frequency informational notes.",
    hint: "1=Errors, 2=Errors+Warnings (Recommended), 3=Errors+Warnings+Notes.",
    level: "basic",
    codeExample: `SET PERSIST log_error_verbosity = 2;`
  },
  {
    question: "How does the Component-Based Error Logging architecture in MySQL 8.0 (`log_error_services`) revolutionize log processing?",
    shortAnswer: "It modularizes error log processing into pluggable filter and sink components, allowing DBAs to route error events simultaneously to traditional text files, structured JSON sinks (`log_sink_json`), and systemd syslog (`log_sink_syseventlog`).",
    explanation: "Emitting logs in structured JSON format enables direct automated ingestion by cloud SIEM platforms (like ELK, Datadog, or Grafana Loki) without regex parsing.",
    hint: "Modular pipeline supporting pluggable JSON sinks and syslog components.",
    level: "expert",
    codeExample: `INSTALL COMPONENT 'file://component_log_sink_json';
SET PERSIST log_error_services = 'log_filter_internal; log_sink_json';`
  },
  {
    question: "What is the structure of a JSON error log record generated by `log_sink_json` in MySQL 8.0?",
    shortAnswer: "A JSON object containing standardized fields: `\"prio\"` (severity), `\"err_code\"` (error number), `\"subsystem\"` (InnoDB/Server/Repl), `\"msg\"` (error text), and `\"time\"` (ISO 8601 UTC timestamp).",
    explanation: "Standardized JSON keys allow automated log ingestion pipelines to trigger immediate alerts on high-severity events.",
    hint: "Standardized JSON object with prio, err_code, subsystem, msg, and time keys.",
    level: "intermediate",
    codeExample: `{
  "prio": "ERROR",
  "err_code": 11906,
  "subsystem": "InnoDB",
  "msg": "Database page corruption on disk in tablespace 45",
  "time": "2026-08-25T15:00:00.123456Z"
}`
  },
  {
    question: "In Mamata & Susmita's Barrackpore store, the MySQL server failed to start with `[ERROR] [MY-010119] [Server] Aborting`. What error log diagnosis revealed the cause?",
    shortAnswer: "The error log showed that port 3306 was already bound by a zombie `mysqld` process: `[ERROR] [MY-010262] [Server] Can't start server: Bind on TCP/IP port: Address already in use`.",
    explanation: "Killing the orphaned background process freed port 3306, allowing MySQL to start cleanly.",
    hint: "Address already in use error revealed port 3306 was locked by an orphaned process.",
    level: "moderate",
    codeExample: `# Barrackpore Error Log Trace:
# [ERROR] [MY-010262] [Server] Can't start server: Bind on TCP/IP port: Address already in use`
  },
  {
    question: "In Abhronila & Debangshu's Kolkata fintech bank, how did JSON error logging prevent an unannounced replica crash from causing downtime across ₹500 Crores in transactions?",
    shortAnswer: "Debangshu's Datadog SIEM ingested a structured `log_sink_json` event (`\"prio\": \"ERROR\", \"subsystem\": \"Replica\"`), triggering an automated PagerDuty alert within 3 seconds when a replication I/O thread failed.",
    explanation: "The automated alert allowed the SRE team to resolve the replication network blip before replication lag impacted core banking reporting.",
    hint: "JSON log event triggered automated PagerDuty SIEM alert within 3 seconds.",
    level: "expert",
    codeExample: `{
  "prio": "ERROR",
  "err_code": 13114,
  "subsystem": "Replica",
  "msg": "Replica I/O thread connection lost to source",
  "time": "2026-08-25T15:00:03.491200Z"
}`
  },
  {
    question: "What is the purpose of `log_error_suppression_list` in MySQL 8.0?",
    shortAnswer: "It specifies a comma-separated list of harmless error/warning codes (e.g. `MY-010055`, `MY-010008`) that should be suppressed from being written to the Error Log.",
    explanation: "Suppresses noisy, repetitive warnings (like port scan connection aborts) from filling disk space and obscuring critical alerts.",
    hint: "Suppresses specified harmless warning codes from flooding the error log.",
    level: "intermediate",
    codeExample: `SET PERSIST log_error_suppression_list = 'MY-010055,MY-010008';`
  },
  {
    question: "How do you rotate the MySQL Error Log using Linux `logrotate` without stopping the running database?",
    shortAnswer: "Configure `logrotate` to rename the log file and execute `mysqladmin -u root -p flush-logs error` in the `postrotate` script block.",
    explanation: "The `flush-logs error` command tells the `mysqld` process to close its old file descriptor and reopen the active error log path cleanly.",
    hint: "Use logrotate with postrotate command: mysqladmin flush-logs error.",
    level: "intermediate",
    codeExample: `/var/log/mysql/error.log {
  daily
  rotate 14
  compress
  missingok
  postrotate
    mysqladmin -u root -pSecurePass flush-logs error
  endscript
}`
  },
  {
    question: "What command in SQL forces MySQL to close and reopen the Error Log file handle immediately?",
    shortAnswer: "Execute `FLUSH ERROR LOGS;` (or `FLUSH LOGS;`).",
    explanation: "Releases the active file handle and creates a new error log file if the previous file was moved or archived.",
    hint: "Run FLUSH ERROR LOGS.",
    level: "basic",
    codeExample: `FLUSH ERROR LOGS;`
  },
  {
    question: "What does an `[ERROR] [MY-011906] [InnoDB] Database page corruption on disk` log signature indicate?",
    shortAnswer: "An InnoDB 16KB physical data page failed its CRC32 checksum validation, indicating hardware disk corruption, filesystem bit rot, or an unbuffered power outage during page writes.",
    explanation: "This is a critical alert requiring immediate page-level recovery or restoring from a physical hot backup.",
    hint: "Indicates hardware disk corruption or failed 16KB page CRC32 checksum.",
    level: "expert",
    codeExample: `# [ERROR] [MY-011906] [InnoDB] Database page corruption on disk in tablespace 45 page [page id: space=45, page number=1028]`
  },
  {
    question: "How do you view the last 100 lines of the MySQL Error Log from the command line in Linux?",
    shortAnswer: "Run `tail -n 100 /var/log/mysql/error.log` (or `journalctl -u mysql -n 100` if using systemd).",
    explanation: "Quickly displays the most recent diagnostic events and error traces.",
    hint: "Use tail -n 100 on the error log file path.",
    level: "basic",
    codeExample: `tail -n 100 /var/log/mysql/error.log`
  },
  {
    question: "What is the difference between `log_error_verbosity = 1` and `log_error_verbosity = 3`?",
    shortAnswer: "`1` logs ONLY critical errors and suppresses all warnings and connection notes; `3` logs errors, warnings, and every informational note (such as client connection handshakes and buffer pool resize progress).",
    explanation: "Verbosity 1 is too quiet for production monitoring; verbosity 3 is excessively noisy and can fill disks in high-concurrency environments.",
    hint: "1 is errors-only; 3 is ultra-verbose with connection and system notes.",
    level: "basic",
    codeExample: `-- Level 1: Errors only
-- Level 3: Errors, Warnings, and Informational Notes`
  },
  {
    question: "What does the error signature `[Warning] [MY-010055] [Server] IP address '192.168.1.50' could not be resolved` indicate?",
    shortAnswer: "MySQL attempted a reverse DNS lookup on a connecting client's IP address and failed due to DNS server latency or missing PTR records.",
    explanation: "Setting `skip_name_resolve = ON` in `my.cnf` disables client DNS lookups, eliminating this warning and speeding up connection authentication.",
    hint: "Failed reverse DNS lookup on client IP; resolve by setting skip_name_resolve=ON.",
    level: "intermediate",
    codeExample: `[mysqld]
skip_name_resolve = ON`
  },
  {
    question: "How does MySQL 8.0 format error codes in error log messages (e.g. `MY-010914`)?",
    shortAnswer: "Each message contains an explicit prefix `MY-` followed by a 6-digit numeric error code, identifying the exact error symbol in the MySQL documentation.",
    explanation: "Structured error numbers allow automated parsing scripts to categorize and route errors by exact error code.",
    hint: "Uses standardized MY-XXXXXX 6-digit numeric error codes.",
    level: "basic",
    codeExample: `[ERROR] [MY-010914] [Server] Got an error reading communication packets`
  },
  {
    question: "What happens if the MySQL Error Log file cannot be written due to operating system permission issues on startup?",
    shortAnswer: "The MySQL daemon process will abort immediately and write a fatal startup failure message to `stderr` / systemd journal.",
    explanation: "The `mysqld` process requires write permissions on the error log file and its parent directory (typically owned by `mysql:mysql`).",
    hint: "MySQL fails to start if it cannot write to its configured error log path.",
    level: "basic",
    codeExample: `chown -R mysql:mysql /var/log/mysql/`
  },
  {
    question: "What is `log_sink_syseventlog` in MySQL 8.0?",
    shortAnswer: "An error logging sink component that directs error messages directly to the Windows Event Log on Windows or the systemd syslog on Linux.",
    explanation: "Enables centralized OS-level log ingestion without maintaining separate log files on disk.",
    hint: "Directs error messages to Windows Event Log or Linux syslog.",
    level: "intermediate",
    codeExample: `INSTALL COMPONENT 'file://component_log_sink_syseventlog';
SET PERSIST log_error_services = 'log_filter_internal; log_sink_syseventlog';`
  },
  {
    question: "What does the error log entry `[Note] [MY-012543] [InnoDB] *** (1) TRANSACTION` indicate?",
    shortAnswer: "An InnoDB deadlock occurred between two concurrent transactions, and the error log is recording the full deadlock trace (if `innodb_print_all_deadlocks = ON` is enabled).",
    explanation: "Reviewing deadlock traces in the error log allows developers to identify conflicting table locks and index locking orders.",
    hint: "Records an InnoDB transaction deadlock trace when innodb_print_all_deadlocks is enabled.",
    level: "intermediate",
    codeExample: `SET PERSIST innodb_print_all_deadlocks = ON;`
  },
  {
    question: "How do you configure the Error Log timestamp format to include microsecond precision in MySQL 8.0?",
    shortAnswer: "Set `log_timestamps = UTC` (or `SYSTEM`), which automatically outputs high-resolution ISO 8601 timestamps with microsecond precision (`YYYY-MM-DDTHH:MM:SS.uuuuuuZ`).",
    explanation: "High-resolution timestamps ensure precise chronological event correlation during incident investigations.",
    hint: "Set log_timestamps to UTC or SYSTEM.",
    level: "basic",
    codeExample: `SET PERSIST log_timestamps = 'SYSTEM';`
  },
  {
    question: "What is the danger of setting `log_error_verbosity = 3` on a busy production server receiving 10,000 connections per second?",
    shortAnswer: "It generates gigabytes of informational connection and disconnect messages per hour, consuming disk I/O bandwidth and rapidly filling up disk space.",
    explanation: "Verbosity 3 should only be enabled temporarily in development or staging environments.",
    hint: "Generates massive connection message volume, saturating disk I/O.",
    level: "basic",
    codeExample: `-- Keep log_error_verbosity at 2 in production.`
  },
  {
    question: "How do you verify which error log filter and sink components are currently active in MySQL 8.0?",
    shortAnswer: "Query `SELECT * FROM performance_schema.log_status;` or check `SHOW VARIABLES LIKE 'log_error_services';`.",
    explanation: "Displays the active error log pipeline configuration.",
    hint: "Inspect the log_error_services system variable.",
    level: "basic",
    codeExample: `SHOW VARIABLES LIKE 'log_error_services';`
  },
  {
    question: "What does `[ERROR] [MY-010119] [Server] Disk is full writing './ibdata1'` indicate in the Error Log?",
    shortAnswer: "The filesystem partition holding the MySQL tablespace has run out of free disk space, causing all transactional write operations to freeze.",
    explanation: "Immediate action required: free disk space or extend the storage volume to prevent transaction crashes.",
    hint: "Tablespace disk partition is 100% full; writes are frozen.",
    level: "basic",
    codeExample: `# Free space immediately or extend the underlying LVM / EBS volume.`
  },
  {
    question: "Can multiple error log sinks be enabled simultaneously in MySQL 8.0?",
    shortAnswer: "Yes, by listing multiple sinks in `log_error_services` (e.g. `SET PERSIST log_error_services = 'log_filter_internal; log_sink_internal; log_sink_json';`).",
    explanation: "Emits error events simultaneously to both traditional text files and structured JSON files.",
    hint: "List multiple sinks separated by semicolons in log_error_services.",
    level: "expert",
    codeExample: `SET PERSIST log_error_services = 'log_filter_internal; log_sink_internal; log_sink_json';`
  },
  {
    question: "What is the default error log destination if `log_error` is not explicitly configured in `my.cnf`?",
    shortAnswer: "On Linux, MySQL creates a file named `<hostname>.err` inside the MySQL data directory (`/var/lib/mysql/`); on systemd installations, it writes to `stderr` / journalctl.",
    explanation: "Explicitly defining `log_error = /var/log/mysql/error.log` is recommended for predictable log management.",
    hint: "Defaults to <hostname>.err in data directory or stderr/journalctl.",
    level: "basic",
    codeExample: `[mysqld]
log_error = /var/log/mysql/error.log`
  },
  {
    question: "How does MySQL Error Log handle crash recovery messages when the server boots after a power outage?",
    shortAnswer: "It logs the InnoDB redo log scanning progress, active Log Sequence Numbers (LSN), and rolls forward committed pages and rolls back uncommitted transactions with timestamped status updates.",
    explanation: "Provides visibility into the crash recovery duration and verifies database integrity upon restart.",
    hint: "Logs redo log roll-forward, LSN checkpoints, and undo rollback progress.",
    level: "intermediate",
    codeExample: `[Note] [MY-012208] [InnoDB] Starting crash recovery from checkpoint LSN=184920491`
  },
  {
    question: "What is the role of `log_filter_internal` in the MySQL 8.0 error logging pipeline?",
    shortAnswer: "It is the built-in filtering component that applies `log_error_verbosity` and `log_error_suppression_list` rules to filter messages before passing them to the configured sinks.",
    explanation: "Ensures only events meeting verbosity and suppression criteria reach the output sinks.",
    hint: "Applies verbosity and suppression filtering rules before sending events to sinks.",
    level: "expert",
    codeExample: `-- Must be the first component in log_error_services:
SET PERSIST log_error_services = 'log_filter_internal; log_sink_internal';`
  },
  {
    question: "How do you search the MySQL Error Log for all instances of aborted connections over the past 24 hours?",
    shortAnswer: "Use `grep -i 'aborted connection' /var/log/mysql/error.log` or filter by error code `grep 'MY-010914' /var/log/mysql/error.log`.",
    explanation: "Identifies application connection pool timeouts, network dropped packets, or authentication failures.",
    hint: "Grep for 'aborted connection' or error code MY-010914.",
    level: "basic",
    codeExample: `grep -i "aborted connection" /var/log/mysql/error.log | tail -n 20`
  },
  {
    question: "Why should the Error Log be monitored by automated monitoring agents (like Prometheus Node Exporter / Datadog Agent)?",
    shortAnswer: "To trigger immediate real-time alerts upon detecting critical error patterns (`page corruption`, `deadlocks`, `replication errors`) before they escalate into catastrophic application outages.",
    explanation: "Automated log scraping eliminates reliance on manual log checking.",
    hint: "Automates real-time alerting for critical corruption and replication failures.",
    level: "basic",
    codeExample: `-- Prometheus grok_exporter / Datadog log parser rules.`
  },
  {
    question: "What is the impact of character encoding in the Error Log when logging queries containing Unicode or Bengali text?",
    shortAnswer: "The Error Log encodes all text strings in UTF-8 (`utf8mb4`), ensuring that multilingual schema names and query fragments are displayed without character corruption.",
    explanation: "Maintains international character fidelity across all diagnostic logs.",
    hint: "Encodes all messages in UTF-8 to preserve international characters.",
    level: "basic",
    codeExample: `[Warning] [MY-010055] [Server] Table \`kolkata_retail\`.\`ক্রেতা\` has missing index.`
  },
  {
    question: "How do you uninstall an error log component (e.g. `log_sink_json`) if it is no longer required?",
    shortAnswer: "Reconfigure `log_error_services` to remove the sink, then execute `UNINSTALL COMPONENT 'file://component_log_sink_json';`.",
    explanation: "Cleanly removes the component from the MySQL memory space.",
    hint: "Update log_error_services and run UNINSTALL COMPONENT.",
    level: "intermediate",
    codeExample: `SET PERSIST log_error_services = 'log_filter_internal; log_sink_internal';
UNINSTALL COMPONENT 'file://component_log_sink_json';`
  },
  {
    question: "What is the primary operational takeaway of Topic 1 in Module 004_005?",
    shortAnswer: "The MySQL Error Log is the foundational diagnostic record for server health: configure `log_error_verbosity = 2` for optimal warning capture without disk bloat, adopt structured JSON logging (`log_sink_json`) for automated cloud SIEM alerting, configure automated log rotation via Linux `logrotate` with `flush-logs error`, and suppress noisy warnings with `log_error_suppression_list`.",
    explanation: "Mastering error log configuration and interpretation allows database administrators to diagnose crashes, detect hardware corruption early, and maintain 99.999% production uptime.",
    hint: "Summarize log_error_verbosity=2, JSON sinks, logrotate integration, and corruption diagnostics.",
    level: "basic",
    codeExample: `-- Master Error Log Configuration:
INSTALL COMPONENT 'file://component_log_sink_json';
SET PERSIST log_error_verbosity = 2;
SET PERSIST log_error_services = 'log_filter_internal; log_sink_internal; log_sink_json';
SET PERSIST log_error_suppression_list = 'MY-010055,MY-010008';`
  }
];

export default questions;
