// topic2_questions.js
// CBSE Class XI Computer Science (083) - Topic 2 FAQs & Questions Bank
// Educator: Sukanta Hui (Coder & AccoTax, Barrackpore)

const questions = [
  {
    id: "q1",
    question: "What is a System Bus in computer architecture?",
    answer: "A System Bus is a pathway consisting of a group of parallel conducting wires (tracks) that transfers binary signals (data, addresses, and control instructions) between the CPU, primary memory, and I/O devices.",
    explanation: "The bus allows multiple hardware modules to communicate across a shared electronic interface on the motherboard.",
    explanationBn: "সিস্টেম বাস হলো মাদারবোর্ডের ওপর থাকা পরিবাহী তারের সমাহার যার মাধ্যমে CPU, মেমোরি ও অন্যান্য পেরিফেরাল ডিভাইসের মধ্যে বাইনারি সিগন্যাল আদান-প্রদান হয়।",
    category: "Concepts"
  },
  {
    id: "q2",
    question: "Why is the Address Bus strictly unidirectional while the Data Bus is bidirectional?",
    answer: "The Address Bus is unidirectional because only the CPU (or a DMA controller) determines and outputs the target memory location to access. The Data Bus is bidirectional because the CPU must both READ data from memory/peripherals and WRITE data back into them.",
    explanation: "Memory chips never initiate requests to the CPU, hence memory never drives the address bus.",
    explanationBn: "অ্যাড্রেস বাস কেবল CPU থেকে মেমোরির দিকে যায় কারণ CPU কোন অ্যাড্রেস অ্যাক্সেস করতে হবে তা নির্ধারণ করে। কিন্তু ডেটা বাসে ডেটা গ্রহণ (Read) এবং প্রেরণ (Write) উভয় কাজই হয় বলে এটি দ্বিমুখী (Bidirectional)।",
    category: "Directionality"
  },
  {
    id: "q3",
    question: "If a processor has an Address Bus of 32 bits, calculate the maximum amount of RAM it can directly address.",
    answer: "Maximum directly addressable RAM = 2^32 bytes = 4,294,967,296 bytes = 4 Gigabytes (GB).",
    explanation: "Formula: Capacity = 2^N bytes, where N is the number of address lines. 2^32 = 2^2 × 2^30 = 4 × 1 GB = 4 GB.",
    explanationBn: "৩২-বিট অ্যাড্রেস বাসের জন্য সর্বোচ্চ মেমোরি = ২^৩২ বাইট = ৪ গিগাবাইট (4 GB)।",
    category: "Calculations"
  },
  {
    id: "q4",
    question: "A legacy computer has a 20-bit address bus. What is its memory limit in Kilobytes or Megabytes?",
    answer: "Memory capacity = 2^20 bytes = 1,048,576 bytes = 1 Megabyte (1 MB).",
    explanation: "This was the historic architectural limit of the Intel 8086/8088 microprocessors.",
    explanationBn: "২০-বিট অ্যাড্রেস বাসের ধারণক্ষমতা = ২^২০ বাইট = ১ মেগাবাইট (1 MB)।",
    category: "Calculations"
  },
  {
    id: "q5",
    question: "What is the primary role of the Control Bus in a computer system?",
    answer: "The Control Bus transmits timing pulses, synchronization signals, read/write commands, and interrupt requests generated by the Control Unit to orchestrate hardware activity.",
    explanation: "Without the Control Bus, memory chips would not know whether an address on the Address Bus is intended for a Read or Write operation.",
    explanationBn: "কন্ট্রোল বাস রিড/রাইট কমান্ড, টাইমিং সিগন্যাল ও ইন্টারাপ্ট সংকেত পাঠিয়ে মেমোরি ও I/O ডিভাইসের কার্যক্রম সমন্বয় করে।",
    category: "Control Bus"
  },
  {
    id: "q6",
    question: "Name three critical control signal lines carried over the Control Bus.",
    answer: "1. Memory Read (MEMR)\n2. Memory Write (MEMW)\n3. Interrupt Request (INTR) / Interrupt Acknowledge (INTA).",
    explanation: "Other common control lines include I/O Read (IOR), I/O Write (IOW), Bus Request, and System Reset.",
    explanationBn: "১. Memory Read (MEMR), ২. Memory Write (MEMW), এবং ৩. Interrupt Request (INTR)।",
    category: "Control Bus"
  },
  {
    id: "q7",
    question: "How does the width of the Data Bus affect the overall throughput of a computer?",
    answer: "The width of the Data Bus dictates how many bits (or bytes) can be transferred between the CPU and memory in a single clock cycle. A 64-bit data bus moves 8 bytes at once, doubling the data throughput compared to a 32-bit bus.",
    explanation: "Greater bus width reduces the number of fetch cycles required for multi-byte data types and complex instructions.",
    explanationBn: "ডেটা বাসের প্রস্থ বেশি হলে এক সাইকেলে বেশি পরিমাণ ডেটা (যেমন 64-bit বা 8 Bytes) একসাথে স্থানান্তরিত হতে পারে, ফলে কম্পিউটারের গতি বাড়ে।",
    category: "Data Bus"
  },
  {
    id: "q8",
    question: "Explain what happens during a 'Memory Read' bus transaction.",
    answer: "1. CPU places the target physical address onto the Address Bus.\n2. CPU asserts the MEM_READ line on the Control Bus.\n3. RAM decodes the address, retrieves the byte/word, and places it onto the Data Bus.\n4. CPU latches the data from the Data Bus into the Memory Data Register (MDR).",
    explanation: "This 4-step sequence constitutes a standard machine read cycle.",
    explanationBn: "১. CPU অ্যাড্রেস বাসে ঠিকানা দেয়। ২. কন্ট্রোল বাসে Read সিগন্যাল পাঠায়। ৩. র‍্যাম ডেটা বাসে ডেটা দেয়। ৪. CPU-র MDR ডেটা গ্রহণ করে।",
    category: "Transactions"
  },
  {
    id: "q9",
    question: "Explain what happens during a 'Memory Write' bus transaction.",
    answer: "1. CPU places the target address on the Address Bus.\n2. CPU places the data to be stored on the Data Bus.\n3. CPU asserts the MEM_WRITE line on the Control Bus.\n4. RAM reads the Data Bus and permanently stores the bits at the specified address location.",
    explanation: "The write cycle ensures that modified variables are safely stored into physical RAM cells.",
    explanationBn: "১. CPU অ্যাড্রেস বাসে ঠিকানা দেয়। ২. ডেটা বাসে সংরক্ষিতব্য মান দেয়। ৩. Write সিগন্যাল পাঠায়। ৪. র‍্যাম সেই ডেটা নির্দিষ্ট ঠিকানায় লিখে নেয়।",
    category: "Transactions"
  },
  {
    id: "q10",
    question: "What is the difference between an Internal Bus and an External System Bus?",
    answer: "An Internal Bus connects components within the CPU chip itself (ALU, CU, Registers), whereas an External System Bus connects the CPU package to external motherboard components (RAM, ROM, Expansion slots).",
    explanation: "Internal buses operate at full CPU core clock frequency (e.g. 4.5 GHz), while external system buses operate at motherboard chipset clock speeds.",
    explanationBn: "অভ্যন্তরীণ বাস CPU চিপের ভেতরের অংশগুলোকে যুক্ত করে, আর বাহ্যিক সিস্টেম বাস CPU-কে মাদারবোর্ডের মেমোরি ও স্লটের সাথে যুক্ত করে।",
    category: "Architecture"
  },
  {
    id: "q11",
    question: "Calculate the theoretical maximum memory capacity of a modern 64-bit processor with a 48-bit physical address bus.",
    answer: "Capacity = 2^48 bytes = 2^8 × 2^40 bytes = 256 Terabytes (TB).",
    explanation: "Although 64-bit pointers can theoretically reference 16 Exabytes (2^64), modern CPU hardware implementations typically implement 48 or 52 physical address lines to save chip pin count and energy.",
    explanationBn: "৪৮-বিট ফিজিক্যাল অ্যাড্রেস বাসের জন্য মেমোরি সীমা = ২^৪৮ বাইট = ২৫৬ টেরাবাইট (256 TB)।",
    category: "Calculations"
  },
  {
    id: "q12",
    question: "What is 'Bus Contention' and how is it resolved?",
    answer: "Bus Contention occurs when two hardware devices attempt to drive electrical signals onto the shared Data Bus at the same instant. It is resolved using a Bus Arbiter and Tri-State Logic (High-Z state).",
    explanation: "Tri-state buffers ensure that inactive devices disconnect from the bus electrically by entering high impedance.",
    explanationBn: "যখন দুটি ডিভাইস একই সময়ে বাসে সিগন্যাল পাঠাতে চেষ্টা করে তখন সংঘর্ষ বা Bus Contention ঘটে; বাস আরবিটার এটি নিয়ন্ত্রণ করে।",
    category: "Advanced"
  },
  {
    id: "q13",
    question: "What is a 'Bus Clock' and how does it relate to bus bandwidth?",
    answer: "The Bus Clock provides the synchronization frequency (e.g., 1600 MHz, 3200 MHz) at which bits are latched across the bus lines. Bandwidth equals (Bus Width in bytes) × (Bus Clock Frequency in Hz).",
    explanation: "Higher bus clock speeds increase the total gigabytes per second that can be streamed between CPU and RAM.",
    explanationBn: "বাস ক্লক হলো বাসের স্পন্দন গতি; বাস ক্লক ও বাস প্রস্থ গুণ করে মোট ব্যান্ডউইডথ (GB/s) পাওয়া যায়।",
    category: "Calculations"
  },
  {
    id: "q14",
    question: "What is the function of the 'Reset' line on the Control Bus?",
    answer: "The Reset line clears all CPU internal registers, sets the Program Counter (PC) to the initial bootstrap firmware entry point (e.g., 0xFFFF0), and re-initializes memory controllers upon power-on or reboot.",
    explanation: "This guarantees a deterministic, known starting state whenever the machine boots up.",
    explanationBn: "রিসেট লাইন সমস্ত রেজিস্টারের মান মুছে দিয়ে PC-কে বায়োসের শুরুর অ্যাড্রেসে সেট করে সিস্টেম রিবুট নিশ্চিত করে।",
    category: "Control Bus"
  },
  {
    id: "q15",
    question: "True or False: 'A 16-bit data bus can transfer an 8-byte integer in a single clock cycle.'",
    answer: "False. A 16-bit data bus transfers 2 bytes per clock cycle. To transfer an 8-byte (64-bit) integer, it requires 4 separate consecutive bus access cycles.",
    explanation: "Total cycles = 8 bytes / 2 bytes_per_cycle = 4 cycles.",
    explanationBn: "ভুল। ১৬-বিট ডেটা বাস একবারে মাত্র ২ বাইট পাঠাতে পারে; ৮ বাইট পাঠাতে ৪টি আলাদা সাইকেলের প্রয়োজন হবে।",
    category: "True/False"
  },
  {
    id: "q16",
    question: "What is DMA (Direct Memory Access) and how does it utilize the System Bus?",
    answer: "DMA allows high-speed peripheral controllers (like SSDs or Gigabit Network Cards) to transfer data directly to and from RAM without routing every byte through the CPU core.",
    explanation: "The DMA controller requests bus control via the 'Bus Request' control line; once the CPU grants control via 'Bus Grant', the DMA controller drives the Address and Data buses directly.",
    explanationBn: "DMA-এর মাধ্যমে হার্ডডিস্ক বা নেটওয়ার্ক কার্ড CPU-কে বিরক্ত না করে সরাসরি প্রধান মেমোরির (RAM) সাথে উচ্চ গতিতে ডেটা আদান-প্রদান করতে পারে।",
    category: "Architecture"
  },
  {
    id: "q17",
    question: "What is PCIe (Peripheral Component Interconnect Express) in modern PC bus design?",
    answer: "PCIe is a high-speed serial expansion bus standard that uses point-to-point dedicated 'lanes' (x1, x4, x8, x16) to connect graphics cards (GPUs) and NVMe SSDs to the CPU.",
    explanation: "Unlike legacy parallel buses, serial PCIe achieves higher clock rates without suffering from parallel line cross-talk or clock skew.",
    explanationBn: "PCIe হলো আধুনিক উচ্চগতির সিরিয়াল বাস যা গ্রাফিক্স কার্ড এবং দ্রুতগতির NVMe SSD-কে সরাসরি CPU-র সাথে যুক্ত করে।",
    category: "Modern Standards"
  },
  {
    id: "q18",
    question: "If an address bus has 14 lines, how many memory cells can it address?",
    answer: "Number of addressable cells = 2^14 = 16,384 bytes = 16 Kilobytes (KB).",
    explanation: "2^14 = 2^4 × 2^10 = 16 × 1024 = 16,384.",
    explanationBn: "১৪-টি অ্যাড্রেস লাইনের সাহায্যে ২^১৪ = ১৬,৩৮৪ টি ঘর বা ১৬ কিলোবাইট (16 KB) মেমোরি অ্যাক্সেস করা সম্ভব।",
    category: "Calculations"
  },
  {
    id: "q19",
    question: "What role does the 'Interrupt Request (INTR)' line play on the Control Bus?",
    answer: "Peripherals (like the keyboard when a key is pressed) pull the INTR line to high voltage to alert the CPU that urgent attention is required, prompting the CPU to pause its current work and execute an Interrupt Service Routine (ISR).",
    explanation: "This enables responsive event-driven hardware communication without constant CPU polling.",
    explanationBn: "যখন কোনো কিবোর্ড বা মাউস সিগন্যাল আসে, তখন INTR লাইনের মাধ্যমে প্রসেসরকে সতর্ক করা হয় যাতে প্রসেসর দ্রুত প্রতিক্রিয়া জানায়।",
    category: "Control Bus"
  },
  {
    id: "q20",
    question: "What is 'Tri-State Logic' in bus transceivers?",
    answer: "Tri-State Logic allows a digital output pin to assume three distinct electrical states: Logic 0 (Low), Logic 1 (High), and High Impedance (Hi-Z or disconnected).",
    explanation: "The Hi-Z state allows multiple chips to share the same bus wire without causing short circuits when only one chip is transmitting.",
    explanationBn: "ট্রাই-স্টেট লজিকে ৩টি অবস্থা থাকে: ০, ১ এবং হাই-ইম্পিড্যান্স (বিচ্ছিন্ন অবস্থা), যা একই বাসে একাধিক ডিভাইস নিরাপদে যুক্ত করতে সাহায্য করে।",
    category: "Advanced"
  },
  {
    id: "q21",
    question: "How does the Address Bus differentiate between RAM access and I/O Port access in Intel x86 architecture?",
    answer: "The CPU uses the M/IO# control line on the Control Bus. When M/IO# is High, the address is interpreted as a memory location; when Low, it is interpreted as an I/O peripheral port (Isolated I/O).",
    explanation: "This prevents memory addresses and hardware peripheral port registers from conflicting.",
    explanationBn: "কন্ট্রোল বাসের M/IO# সিগন্যাল দিয়ে প্রসেসর বোঝায় যে উক্ত অ্যাড্রেসটি র‍্যামের জন্য নাকি I/O পোর্টের জন্য।",
    category: "Control Bus"
  },
  {
    id: "q22",
    question: "Calculate the bandwidth of a 32-bit wide data bus running at 400 MHz.",
    answer: "Bandwidth = (32 bits / 8) × 400,000,000 Hz = 4 bytes × 400,000,000 = 1,600,000,000 bytes/sec = 1.6 GB/sec (or 1,525.87 MB/s).",
    explanation: "Formula: Data transferred per second = Bus width in bytes × Frequency.",
    explanationBn: "ব্যান্ডউইডথ = (৩২/৮) বাইট × ৪০০ মেগাহার্টজ = ৪ × ৪০০ = ১.৬ গিগাবাইট প্রতি সেকেন্ড (1.6 GB/s)।",
    category: "Calculations"
  },
  {
    id: "q23",
    question: "Why can't the Address Bus be bidirectional in standard Von Neumann systems?",
    answer: "Because allowing memory chips to drive addresses backward into the CPU would destroy the master-slave control hierarchy and cause severe bus contention with the CPU's internal MAR register.",
    explanation: "The CPU is the central initiator of memory cycles, so address generation is strictly a one-way command.",
    explanationBn: "কারণ মেমোরি চিপ কখনো প্রসেসরকে অ্যাড্রেস পাঠায় না; প্রসেসরই একমাত্র মেমোরির নির্দিষ্ট ঠিকানা নির্বাচন করে নির্দেশ দেয়।",
    category: "Directionality"
  },
  {
    id: "q24",
    question: "What is 'Multiplexed Bus Architecture' (e.g., AD0-AD7 in Intel 8085)?",
    answer: "A design where the same physical pins carry Address bits during the first clock state (ALE=High) and Data bits during subsequent clock states (ALE=Low) to reduce physical chip pin count.",
    explanation: "Multiplexing saves silicon space and pin count at the cost of slight multiplexing demux latency.",
    explanationBn: "চিপের পিন সংখ্যা কমানোর জন্য একই তারে প্রথমে অ্যাড্রেস এবং পরে ডেটা পাঠানোর পদ্ধতিকে মাল্টিপ্লেক্সড বাস বলে।",
    category: "Architecture"
  },
  {
    id: "q25",
    question: "Summary Question: Identify the bus involved in each action: (a) Reading byte from RAM 0x5000, (b) Sending 'Write Strobe', (c) Transferring user keyboard character 'A'.",
    answer: "(a) Address Bus carries address 0x5000.\n(b) Control Bus asserts the MEM_WRITE strobe signal.\n(c) Data Bus transfers ASCII 'A' (binary 01000001) from input buffer into the CPU.",
    explanation: "This captures the coordinated role of all three buses in complete system I/O transactions.",
    explanationBn: "(ক) অ্যাড্রেস বাস 0x5000 বহন করে। (খ) কন্ট্রোল বাস রাইট স্ট্রোব পাঠায়। (গ) ডেটা বাস কিবোর্ডের অক্ষর 'A' (ASCII 65) প্রসেসরে পাঠায়।",
    category: "Summary"
  }
];

export default questions;
