// File: src/components/topics/topic2_files/topic2_questions.js
const questions = [
  {
    question: "Why is error detection needed at the Data Link Layer if higher layers also have checksums?",
    shortAnswer: "To discard corrupted frames early, preventing them from consuming higher‑layer resources and to avoid wasting bandwidth on retransmissions.",
    explanation: "If a frame is corrupted on a link, the Data Link layer can drop it immediately and (if using ARQ) request a retransmission at the same hop. Waiting for TCP to time out would be much slower and waste bandwidth.",
    hint: "It's more efficient to reject a spoiled letter at the local post office than to send it across the country only to find it's unreadable.",
    level: "moderate",
    codeExample: "// In Wireshark, you'll see 'Bad FCS' frames if CRC fails at Ethernet layer."
  },
  {
    question: "What is the main limitation of a single parity bit?",
    shortAnswer: "It can only detect an odd number of bit errors; any even number of errors goes undetected.",
    explanation: "A single parity bit makes the total number of 1's even (or odd). Flipping two bits changes the count by 2 (or -2), preserving parity, so the error is invisible.",
    hint: "Even number of errors → even parity remains even. The receiver thinks everything is fine.",
    level: "basic",
  },
  {
    question: "How does two‑dimensional parity improve over single parity?",
    shortAnswer: "It can detect and even correct single‑bit errors, and detects some multiple errors because each bit belongs to a unique row and column.",
    explanation: "By adding parity bits for rows and columns, a single flipped bit will cause one row parity error and one column parity error, pinpointing the exact bit. Multiple errors may still escape but less likely.",
    hint: "Think of a bingo card: if a number is marked wrong, you can tell which row and column are inconsistent.",
    level: "moderate",
  },
  {
    question: "What does CRC stand for and what mathematical concept does it use?",
    shortAnswer: "Cyclic Redundancy Check; it uses polynomial division over GF(2) (binary arithmetic without carries).",
    explanation: "The message is interpreted as a polynomial. Both sender and receiver divide by a fixed generator polynomial. The remainder (CRC) is appended. The receiver checks if the remainder is zero.",
    hint: "It's like long division, but with XOR instead of subtraction.",
    level: "moderate",
  },
  {
    question: "What is the 'generator polynomial' in CRC? Give an example from Ethernet.",
    shortAnswer: "A generator polynomial is a predetermined divisor used in CRC calculation. Ethernet uses CRC‑32 with polynomial 0x04C11DB7.",
    explanation: "The polynomial determines which errors are detectable. Standard polynomials have been chosen for maximum burst error detection. For CRC‑32, the degree is 32, so the FCS is 32 bits.",
    hint: "It's like a secret key that both sides agree on; the remainder depends on it.",
    level: "moderate",
  },
  {
    question: "How many bits of overhead does CRC‑32 add to a frame?",
    shortAnswer: "32 bits (4 bytes).",
    explanation: "CRC‑32 produces a 32‑bit remainder, which is appended to the frame. This is why the minimum Ethernet frame size is 64 bytes (including the FCS).",
    hint: "CRC‑n adds n bits of overhead.",
    level: "basic",
  },
  {
    question: "What types of errors can a CRC with generator polynomial of degree r detect?",
    shortAnswer: "All single and double bit errors, any odd number of errors, and bursts of length ≤ r.",
    explanation: "Additionally, the probability of an undetected error for random noise is about 2^{-r} for long frames, assuming a properly chosen polynomial.",
    hint: "The longer the CRC (higher r), the stronger the detection, but also more overhead.",
    level: "expert",
  },
  {
    question: "Why does the Internet checksum use one's complement arithmetic?",
    shortAnswer: "One's complement makes the checksum endian‑independent and allows incremental updates without full recomputation.",
    explanation: "One's complement has the property that the sum of a number and its complement is all ones. This also simplifies detecting all‑zeros vs. all‑ones cases. It's also easier to implement in software than CRC.",
    hint: "It's an old design choice that still works well for header integrity.",
    level: "expert",
  },
  {
    question: "What is a 'checksum offload' in modern NICs?",
    shortAnswer: "Hardware acceleration where the network interface computes or validates the TCP/UDP/IP checksum, relieving the CPU.",
    explanation: "The NIC can calculate the checksum during transmission or verify it on reception, often in parallel with DMA. This reduces CPU usage and improves throughput.",
    hint: "It's like having a dedicated calculator for checksums so the main processor can do other work.",
    level: "moderate",
  },
  {
    question: "Can CRC detect all possible errors?",
    shortAnswer: "No. There is always a small probability that an error pattern will produce the same remainder, making an undetected error.",
    explanation: "For a random error burst longer than r bits, the probability of undetected error is 2^{-r} for a well‑chosen polynomial. But it's theoretically possible for some error patterns to go undetected, though extremely unlikely.",
    hint: "Nothing is perfect, but CRC‑32 is good enough for most practical purposes.",
    level: "expert",
  },
  {
    question: "What is the difference between error detection and error correction?",
    shortAnswer: "Detection only tells you that an error occurred; correction allows you to reconstruct the original data without retransmission.",
    explanation: "Detection uses codes like CRC, parity, checksum. Correction requires more redundant bits (e.g., Hamming codes, Reed‑Solomon). Correction is used when retransmission is too costly (e.g., satellite, storage).",
    hint: "Detection = 'something is wrong'. Correction = 'here is how to fix it'.",
    level: "basic",
  },
  {
    question: "Why is CRC preferred over checksum for link‑layer error detection?",
    shortAnswer: "CRC has much stronger error detection capabilities, especially for burst errors, with relatively low overhead.",
    explanation: "Checksums can miss errors like swapping 16‑bit words or adding a constant to all words. CRC, with proper polynomial, catches all bursts up to r bits. Hardware implementation of CRC is also very efficient.",
    hint: "CRC is the heavy‑duty lock; checksum is the simple latch.",
    level: "moderate",
  },
  {
    question: "What is a 'burst error' and why is CRC good at detecting it?",
    shortAnswer: "A burst error is a contiguous sequence of bits where the first and last are flipped, with any bits in between possibly flipped. CRC with degree r detects any burst of length ≤ r.",
    explanation: "Many physical errors (e.g., lightning, motor spikes) cause burst errors. The polynomial division property ensures that any burst shorter than the CRC length cannot be a multiple of the generator polynomial, so the remainder becomes non‑zero.",
    hint: "A burst is like a scratch on a CD – many consecutive errors. CRC‑32 can catch any scratch up to 32 bits long.",
    level: "expert",
  },
  {
    question: "What is the 'Internet checksum' algorithm in simple steps?",
    shortAnswer: "1) Divide data into 16‑bit words. 2) Sum all words using one's complement addition. 3) Take the one's complement of the total. 4) Insert that value as the checksum.",
    explanation: "On reception, compute the sum (including the checksum field). If the result is all 1's (0xFFFF), the header is considered valid. The algorithm is fast and incremental.",
    hint: "Add all 16‑bit pieces, carry the overflow back around, then flip all bits.",
    level: "moderate",
    codeExample: "// C-like: while (len > 1) { sum += *data++; len -= 2; } if (len) sum += *(uint8_t*)data; while (sum>>16) sum = (sum & 0xFFFF) + (sum>>16); return ~sum;"
  },
  {
    question: "Why does TCP compute a checksum that includes a pseudo‑header?",
    shortAnswer: "The pseudo‑header protects against misdelivery by including source and destination IP addresses and the protocol number in the checksum.",
    explanation: "Without the pseudo‑header, a corrupted packet could be delivered to the wrong IP address or wrong transport protocol and the checksum would still pass. The pseudo‑header ensures the segment is associated with the correct connection.",
    hint: "It's like adding the address of the intended recipient inside the envelope as extra verification.",
    level: "expert",
  },
  {
    question: "What is the 'Fletcher checksum' and where is it used?",
    shortAnswer: "A checksum algorithm that uses two running sums (or four in Fletcher‑64) and is stronger than the Internet checksum but weaker than CRC. Used in some older protocols, e.g., UBX protocol.",
    explanation: "Fletcher computes sum1 = sum of all bytes mod 255, sum2 = sum of sum1 mod 255. It detects many errors that simple sum misses, but still not as robust as CRC.",
    hint: "It's a middle ground between simple checksum and CRC.",
    level: "expert",
  },
  {
    question: "Can you use a CRC to also correct errors (like a Hamming code)?",
    shortAnswer: "No, CRC is designed for detection only. However, some variants (CRC with error correction) exist, but they are not standard.",
    explanation: "CRC lacks the structure needed for forward error correction (FEC). For correction, you need codes with sufficient Hamming distance and decoding algorithms (e.g., Reed‑Solomon).",
    hint: "CRC is the alarm bell, not the repair crew.",
    level: "moderate",
  },
  {
    question: "What is the role of the 'frame check sequence' (FCS) in Ethernet?",
    shortAnswer: "The FCS is the 32‑bit CRC value appended to the Ethernet frame for error detection.",
    explanation: "The FCS covers the destination MAC, source MAC, type/length, and payload. If the receiver calculates a CRC that doesn't match the FCS, the frame is discarded and no ACK is sent (for protocols that use ACKs).",
    hint: "It's like a tamper‑evident seal on a package.",
    level: "basic",
  },
  {
    question: "What does 'end‑to‑end checksum' mean in the context of TCP?",
    shortAnswer: "The checksum covers the entire TCP segment (header + payload) from the source to the final destination, not just hop‑by‑hop.",
    explanation: "While each link may have its own CRC, the TCP checksum ensures that even if a frame is corrupted in a switch's memory or by a buggy NIC, the corruption is detected at the receiving host.",
    hint: "Multiple layers of protection: CRC per hop + checksum end to end.",
    level: "moderate",
  },
  {
    question: "Can a single parity bit detect all 1‑bit errors?",
    shortAnswer: "Yes, any single‑bit error changes the parity of the number of 1's, so it will be detected.",
    explanation: "That is the only guarantee of single parity. Two flips may or may not be detected depending on whether parity returns to the original value.",
    hint: "It's reliable only for isolated, rare bit flips.",
    level: "basic",
  },
  {
    question: "What is a 'checksum trailer' in some data link protocols?",
    shortAnswer: "A field appended after the payload, similar to an FCS, that contains a checksum or CRC for error detection.",
    explanation: "Examples include HDLC's FCS (16‑ or 32‑bit CRC) and PPP's FCS. The term 'checksum' is sometimes used interchangeably with CRC in protocols, but technically they differ.",
    hint: "Same concept: extra bytes at the end for integrity check.",
    level: "moderate",
  },
  {
    question: "What is the 'non‑closed ideal' in CRC polynomial selection?",
    shortAnswer: "A polynomial that is not a factor of (x^k + 1) for any k less than the frame length, ensuring all double‑bit errors are detected.",
    explanation: "Choosing a primitive polynomial ensures maximum detection capability. Standard polynomials like CRC‑32 are primitive and have been analyzed for burst detection.",
    hint: "Not all polynomials are equal; the standards use proven ones.",
    level: "expert",
  },
  {
    question: "How does the receiver know where the CRC field ends when the frame length is variable?",
    shortAnswer: "The CRC is always placed at a fixed offset from the end of the frame (or the end of the payload). The length is determined by the header or by a delimiter.",
    explanation: "In Ethernet, the FCS is the last 4 bytes. In HDLC, the frame is delimited by flags, and the FCS is the two or four bytes before the closing flag.",
    hint: "The protocol defines a fixed position for the error detection code.",
    level: "moderate",
  },
  {
    question: "What is the 'vertical parity' vs 'horizontal parity'?",
    shortAnswer: "Vertical parity is per character (or per column), horizontal parity is per row in a block of data.",
    explanation: "Combining both gives two‑dimensional parity. Many early communication protocols used vertical parity for each byte plus a block check character (horizontal).",
    hint: "Vertical = down the column; Horizontal = across the row.",
    level: "basic",
  },
  {
    question: "Why does the Internet checksum use 16 bits instead of 32?",
    shortAnswer: "To keep header overhead low (16 bits vs 32) while still providing reasonable error detection for short packets (max 64KB).",
    explanation: "When IP was designed, 16 bits was a good trade‑off. For larger packets, TCP checksum is still 16 bits but is supplemented by CRC at lower layers.",
    hint: "It's a balance between overhead and protection.",
    level: "moderate",
  },
  {
    question: "What is the difference between 'even parity' and 'odd parity'?",
    shortAnswer: "Even parity: total number of 1's (including parity bit) is even. Odd parity: total is odd.",
    explanation: "Both work identically; the choice is arbitrary but must be consistent between sender and receiver. Even parity is more common in memory systems; odd parity used in some serial links.",
    hint: "Only the convention matters, not which one.",
    level: "basic",
  },
  {
    question: "What is the 'Hamming distance' of an error detection code?",
    shortAnswer: "The minimum number of bit flips needed to transform one valid codeword into another. For detection, the Hamming distance must be at least d+1 to detect d errors.",
    explanation: "Single parity has Hamming distance 2 (can detect 1 error). CRC‑32 has Hamming distance much larger (depending on polynomial and frame length).",
    hint: "Distance = number of bits that differ. Larger distance = stronger detection.",
    level: "expert",
  },
  {
    question: "What is a 'false positive' in error detection?",
    shortAnswer: "When a corrupted frame is incorrectly accepted as valid because the error pattern yields the correct CRC or checksum.",
    explanation: "With perfect detection, false positives never happen. But real codes have non‑zero probability. For CRC‑32, the probability is about 2<sup>-32</sup> for random errors, which is tiny but non‑zero.",
    hint: "The alarm fails to ring even though there is an error.",
    level: "moderate",
  },
  {
    question: "Why does Wi‑Fi use a 32‑bit CRC even though it's a wireless medium with higher error rates?",
    shortAnswer: "CRC‑32 provides a very low undetected error probability, which is needed because a misdelivered frame could cause application‑level corruption.",
    explanation: "Wireless has more errors, so strong detection is critical to avoid delivering corrupt data to higher layers. Additionally, hardware CRC calculation is fast and low overhead.",
    hint: "Even on unreliable media, you want reliable detection.",
    level: "expert",
  },
  {
    question: "What is the 'checksum' field in the IPv4 header?",
    shortAnswer: "A 16‑bit Internet checksum covering only the IP header (not the payload).",
    explanation: "It protects the header integrity because routers modify fields (TTL). The payload is protected by upper‑layer checksums (TCP/UDP) or not at all (e.g., UDP with zero checksum allowed in IPv6).",
    hint: "Only the header, not the data. That's why TCP/UDP need their own checksums.",
    level: "moderate",
  }
];

export default questions;