// src/components/study/c-language/topics/001_005_c-pattern-output-practice-lab/topic2_files/topic2_questions.js

export const questions = [
  {
    "question": "[Module 001_001] Who is recognized as the creator of the C programming language at Bell Labs?",
    "options": [
      "Bjarne Stroustrup",
      "Dennis Ritchie",
      "Ken Thompson",
      "Linus Torvalds"
    ],
    "answerIndex": 1,
    "explanation": "Dennis Ritchie created the C language at AT&T Bell Laboratories between 1969 and 1973 to construct the UNIX operating system."
  },
  {
    "question": "[Module 001_001] Which language was the direct predecessor to C?",
    "options": [
      "Pascal",
      "B Language (derived from BCPL)",
      "Fortran",
      "ALGOL"
    ],
    "answerIndex": 1,
    "explanation": "Ken Thompson developed 'B' (based on BCPL). Dennis Ritchie extended B with data types to create C."
  },
  {
    "question": "[Module 001_001] Which operating system kernel was rewritten in C in 1972, demonstrating C's portability?",
    "options": [
      "UNIX",
      "MS-DOS",
      "CP/M",
      "VMS"
    ],
    "answerIndex": 0,
    "explanation": "UNIX was rewritten in C in 1972, making UNIX the first major portable operating system kernel."
  },
  {
    "question": "[Module 001_001] What machine architecture was used for the initial development of C and UNIX?",
    "options": [
      "DEC PDP-11",
      "Intel 8086",
      "IBM System/360",
      "ENIAC"
    ],
    "answerIndex": 0,
    "explanation": "The C compiler and UNIX kernel were initially developed on the DEC PDP-11 computer."
  },
  {
    "question": "[Module 001_001] What is the first official ANSI standard for C language published in 1989 called?",
    "options": [
      "C89 (or ANSI C / C90)",
      "C99",
      "K&R C",
      "C11"
    ],
    "answerIndex": 0,
    "explanation": "ANSI standardized C in 1989 as ANSI X3.159-1989, commonly known as C89 (and adopted by ISO as C90)."
  },
  {
    "question": "[Module 001_001] What are the four fundamental sequential stages of the GCC compilation toolchain?",
    "options": [
      "Preprocessing -> Compilation -> Assembly -> Linking",
      "Parsing -> Compiling -> Debugging -> Running",
      "Preprocessing -> Linking -> Assembly -> Execution",
      "Scanning -> Building -> Linking -> Loading"
    ],
    "answerIndex": 0,
    "explanation": "The GCC toolchain transforms C code via: 1. Preprocessor (.c to .i), 2. Compiler (.i to .s), 3. Assembler (.s to .o), 4. Linker (.o to executable)."
  },
  {
    "question": "[Module 001_001] Which GCC flag stops the toolchain after the Preprocessing stage, outputting expanded source text?",
    "options": [
      "-E",
      "-S",
      "-c",
      "-o"
    ],
    "answerIndex": 0,
    "explanation": "gcc -E runs only the preprocessor, expanding header includes and macros into stdout or a .i file."
  },
  {
    "question": "[Module 001_001] Which GCC flag stops execution after compilation, producing target assembly code (.s file)?",
    "options": [
      "-S",
      "-E",
      "-c",
      "-o"
    ],
    "answerIndex": 0,
    "explanation": "gcc -S runs compilation to produce an assembly code file (.s)."
  },
  {
    "question": "[Module 001_001] Which GCC flag compiles source files into relocatable machine object code (.o file) without linking?",
    "options": [
      "-c",
      "-E",
      "-S",
      "-o"
    ],
    "answerIndex": 0,
    "explanation": "gcc -c compiles and assembles source files into binary object code files (.o) without linking."
  },
  {
    "question": "[Module 001_001] What is the role of the Linker in the GCC compilation pipeline?",
    "options": [
      "Combines relocatable object files (.o) and C standard library binaries into a final native executable",
      "Strips comments from code",
      "Translates assembly to machine code",
      "Expands #define macros"
    ],
    "answerIndex": 0,
    "explanation": "The Linker resolves cross-file function calls/symbols and combines object files and standard libraries into an executable binary."
  },
  {
    "question": "[Module 001_001] What extension is given to preprocessed C source files generated by 'gcc -E'?",
    "options": [
      ".i",
      ".s",
      ".o",
      ".exe"
    ],
    "answerIndex": 0,
    "explanation": "Preprocessed C source files carry the '.i' file extension."
  },
  {
    "question": "[Module 001_001] What extension is given to human-readable assembly code files generated by 'gcc -S'?",
    "options": [
      ".s",
      ".i",
      ".o",
      ".obj"
    ],
    "answerIndex": 0,
    "explanation": "Assembly files generated by GCC carry the '.s' file extension."
  },
  {
    "question": "[Module 001_001] What extension is given to compiled binary object files on Linux/UNIX systems generated by 'gcc -c'?",
    "options": [
      ".o",
      ".i",
      ".s",
      ".exe"
    ],
    "answerIndex": 0,
    "explanation": "Binary object files carry the '.o' extension on Linux/UNIX (.obj on Windows MSVC)."
  },
  {
    "question": "[Module 001_001] What preprocessor directive is required to include standard input/output functions like printf and scanf?",
    "options": [
      "#include <stdio.h>",
      "#include <stdlib.h>",
      "#include <conio.h>",
      "#include <string.h>"
    ],
    "answerIndex": 0,
    "explanation": "#include <stdio.h> provides prototypes and definitions for standard I/O operations."
  },
  {
    "question": "[Module 001_001] What is the standard required entry point function signature for every hosted C application?",
    "options": [
      "int main(void) or int main(int argc, char *argv[])",
      "void main()",
      "main()",
      "float main(void)"
    ],
    "answerIndex": 0,
    "explanation": "ISO C specifies that main() must return 'int' and take either (void) or (int argc, char *argv[])."
  },
  {
    "question": "[Module 001_001] What exit code returned by main() conventionally signifies successful program execution to the OS?",
    "options": [
      "0 (EXIT_SUCCESS)",
      "1",
      "-1",
      "100"
    ],
    "answerIndex": 0,
    "explanation": "Returning 0 from main() indicates successful execution to the operating system shell."
  },
  {
    "question": "[Module 001_001] What exit code returned by main() conventionally signifies an error to the OS shell?",
    "options": [
      "Non-zero (e.g. 1 or EXIT_FAILURE)",
      "0",
      "NULL",
      "void"
    ],
    "answerIndex": 0,
    "explanation": "Returning a non-zero integer indicates an error status to the host OS environment."
  },
  {
    "question": "[Module 001_001] Which header file defines the standard macros EXIT_SUCCESS and EXIT_FAILURE?",
    "options": [
      "<stdlib.h>",
      "<stdio.h>",
      "<stddef.h>",
      "<limits.h>"
    ],
    "answerIndex": 0,
    "explanation": "<stdlib.h> defines EXIT_SUCCESS (0) and EXIT_FAILURE (1)."
  },
  {
    "question": "[Module 001_001] What format specifier is used in printf() to output a signed decimal integer?",
    "options": [
      "%d (or %i)",
      "%f",
      "%c",
      "%u"
    ],
    "answerIndex": 0,
    "explanation": "%d or %i formats signed decimal integers."
  },
  {
    "question": "[Module 001_001] What format specifier is used in printf() to output a single character?",
    "options": [
      "%c",
      "%s",
      "%d",
      "%f"
    ],
    "answerIndex": 0,
    "explanation": "%c formats single characters."
  },
  {
    "question": "[Module 001_001] What format specifier is used in printf() to output a null-terminated string?",
    "options": [
      "%s",
      "%c",
      "%p",
      "%str"
    ],
    "answerIndex": 0,
    "explanation": "%s formats null-terminated character strings."
  },
  {
    "question": "[Module 001_001] What format specifier is used in printf() to output a floating-point number?",
    "options": [
      "%f",
      "%d",
      "%c",
      "%s"
    ],
    "answerIndex": 0,
    "explanation": "%f formats floating-point values."
  },
  {
    "question": "[Module 001_001] What format specifier is required in scanf() to read input into a 'double' variable?",
    "options": [
      "%lf",
      "%f",
      "%d",
      "%s"
    ],
    "answerIndex": 0,
    "explanation": "scanf() requires %lf to read into a double pointer (while printf uses %f for float and double)."
  },
  {
    "question": "[Module 001_001] Why is the address-of operator '&' required in scanf(\"%d\", &x)?",
    "options": [
      "Because scanf uses Call by Reference (pointers) to mutate caller variable x directly in memory",
      "Because & converts x to float",
      "Because & is a preprocessor macro",
      "Required for syntax aesthetics"
    ],
    "answerIndex": 0,
    "explanation": "scanf needs the memory address (&x) so it can write the parsed user input directly into variable x's RAM location."
  },
  {
    "question": "[Module 001_001] What happens if you forget the '&' operator when reading a scalar variable in scanf(\"%d\", x)?",
    "options": [
      "scanf treats the value of x as a memory pointer, causing a crash (Segmentation Fault) when trying to write to that random address",
      "x is read normally",
      "x becomes 0",
      "Compiler fixes it"
    ],
    "answerIndex": 0,
    "explanation": "Omitting '&' passes x's integer value as an address pointer. scanf attempts to write to that garbage address, causing a Segmentation Fault."
  },
  {
    "question": "[Module 001_001] What format specifier is used to display a memory address pointer in hexadecimal format?",
    "options": [
      "%p",
      "%x",
      "%d",
      "%ptr"
    ],
    "answerIndex": 0,
    "explanation": "%p is the ISO C format specifier for printing void* memory pointer addresses."
  },
  {
    "question": "[Module 001_001] What escape sequence causes output to advance to a new line in console I/O?",
    "options": [
      "\\n",
      "\\t",
      "\\r",
      "\\b"
    ],
    "answerIndex": 0,
    "explanation": "\\n represents a newline character."
  },
  {
    "question": "[Module 001_001] What escape sequence inserts a horizontal tab spacing in console output?",
    "options": [
      "\\t",
      "\\n",
      "\\v",
      "\\a"
    ],
    "answerIndex": 0,
    "explanation": "\\t represents a horizontal tab."
  },
  {
    "question": "[Module 001_001] What function from <stdio.h> flushes the output buffer of a stream (e.g. fflush(stdout))?",
    "options": [
      "fflush()",
      "fclean()",
      "flushall()",
      "clearbuf()"
    ],
    "answerIndex": 0,
    "explanation": "fflush(stdout) forces buffered output bytes to be written immediately to the terminal device."
  },
  {
    "question": "[Module 001_001] What function from <stdio.h> reads a single character from standard input (stdin)?",
    "options": [
      "getchar() (or fgetc(stdin))",
      "putchar()",
      "puts()",
      "getch()"
    ],
    "answerIndex": 0,
    "explanation": "getchar() reads the next single character from stdin."
  },
  {
    "question": "[Module 001_001] What function from <stdio.h> writes a single character to standard output (stdout)?",
    "options": [
      "putchar() (or fputc(c, stdout))",
      "getchar()",
      "puts()",
      "scanf()"
    ],
    "answerIndex": 0,
    "explanation": "putchar(c) outputs a single character to stdout."
  },
  {
    "question": "[Module 001_001] What function writes a string followed by a newline to stdout?",
    "options": [
      "puts()",
      "gets()",
      "printf()",
      "putchar()"
    ],
    "answerIndex": 0,
    "explanation": "puts(str) writes the null-terminated string 'str' to stdout followed by an automatic newline character."
  },
  {
    "question": "[Module 001_001] Why was gets() deprecated in C99 and removed in C11?",
    "options": [
      "It did not check buffer bounds, creating catastrophic buffer overflow security vulnerabilities",
      "It was too fast",
      "It only worked for numbers",
      "It required pointers"
    ],
    "answerIndex": 0,
    "explanation": "gets() suffered from buffer overflow vulnerabilities because it could not limit input length. It was replaced by fgets()."
  },
  {
    "question": "[Module 001_001] What safe string input function should be used instead of gets()?",
    "options": [
      "fgets(buffer, size, stdin)",
      "scanf(\"%s\", buffer)",
      "gets_s()",
      "fputs()"
    ],
    "answerIndex": 0,
    "explanation": "fgets(buffer, sizeof(buffer), stdin) safely bounds input reading to prevent buffer overflows."
  },
  {
    "question": "[Module 001_001] What format specifier prints an integer in lowercase hexadecimal?",
    "options": [
      "%x",
      "%X",
      "%o",
      "%h"
    ],
    "answerIndex": 0,
    "explanation": "%x prints integers in lowercase hexadecimal."
  },
  {
    "question": "[Module 001_001] What format specifier prints an integer in octal (base 8)?",
    "options": [
      "%o",
      "%x",
      "%b",
      "%d"
    ],
    "answerIndex": 0,
    "explanation": "%o prints integers in octal format."
  },
  {
    "question": "[Module 001_001] What is the difference between #include <file.h> and #include \"file.h\"?",
    "options": [
      "<file.h> searches standard system directories; \"file.h\" searches current working directory first then system directories",
      "\"file.h\" is for C++; <file.h> is for C",
      "No difference",
      "<file.h> compiles faster"
    ],
    "answerIndex": 0,
    "explanation": "Angle brackets search standard library paths; quotes search local user project directories first."
  },
  {
    "question": "[Module 001_001] What standard stream object in C represents default console input?",
    "options": [
      "stdin",
      "stdout",
      "stderr",
      "stdnull"
    ],
    "answerIndex": 0,
    "explanation": "stdin represents standard input (keyboard stream)."
  },
  {
    "question": "[Module 001_001] What standard stream object in C represents default unbuffered error output?",
    "options": [
      "stderr",
      "stdout",
      "stdin",
      "stdlog"
    ],
    "answerIndex": 0,
    "explanation": "stderr represents standard error output stream."
  },
  {
    "question": "[Module 001_001] What is the return value of printf()?",
    "options": [
      "The total number of characters successfully printed to output stream",
      "0",
      "1",
      "void"
    ],
    "answerIndex": 0,
    "explanation": "printf() returns the total count of characters transmitted to output (or negative value on error)."
  },
  {
    "question": "[Module 001_001] What is the return value of scanf()?",
    "options": [
      "The number of input items successfully matched and assigned",
      "0",
      "1",
      "The input text"
    ],
    "answerIndex": 0,
    "explanation": "scanf() returns the count of input items successfully matched and assigned."
  },
  {
    "question": "[Module 001_001] What constant macro is returned by getchar()/fgetc() when end-of-file is reached?",
    "options": [
      "EOF (-1)",
      "NULL",
      "0",
      "END"
    ],
    "answerIndex": 0,
    "explanation": "EOF (defined as -1 in <stdio.h>) is returned when stream end-of-file or error occurs."
  },
  {
    "question": "[Module 001_001] Which C standard introduced single-line comments starting with '//'?",
    "options": [
      "C99",
      "C89",
      "K&R C",
      "C17"
    ],
    "answerIndex": 0,
    "explanation": "Single-line comments starting with '//' were officially adopted in C99."
  },
  {
    "question": "[Module 001_001] What happens if block comment closing tag '*/' is omitted in C?",
    "options": [
      "The compiler treats all subsequent code as comment text until EOF, causing syntax errors",
      "Compiles normally",
      "Warns only",
      "Automatically closes at newline"
    ],
    "answerIndex": 0,
    "explanation": "Block comments '/* ... */' swallow all text until '*/'. Omitting '*/' causes the compiler to comment out the rest of the file."
  },
  {
    "question": "[Module 001_001] Can block comments '/* ... */' be nested in standard C?",
    "options": [
      "No, the first '*/' closes the entire block comment",
      "Yes",
      "Only in C23",
      "Only with GCC -O3"
    ],
    "answerIndex": 0,
    "explanation": "Standard C does NOT support nested block comments. The first '*/' closes the comment."
  },
  {
    "question": "[Module 001_001] What is the purpose of the GCC '-Wall' compiler flag?",
    "options": [
      "Enables all recommended compiler warning messages to help catch code defects",
      "Compiles for Windows",
      "Waits for input",
      "Disables optimization"
    ],
    "answerIndex": 0,
    "explanation": "gcc -Wall enables comprehensive compiler warning diagnostics."
  },
  {
    "question": "[Module 001_001] What is the purpose of the GCC '-O2' compiler flag?",
    "options": [
      "Enables standard level-2 code optimization for performance",
      "Disables optimization",
      "Compiles 2 files",
      "Outputs assembly"
    ],
    "answerIndex": 0,
    "explanation": "gcc -O2 enables standard performance optimizations without increasing code size excessively."
  },
  {
    "question": "[Module 001_001] What is the purpose of the GCC '-g' compiler flag?",
    "options": [
      "Generates GDB debugging symbols inside the compiled binary",
      "Compiles graphics",
      "Enables GCC extensions",
      "Generates documentation"
    ],
    "answerIndex": 0,
    "explanation": "gcc -g inserts source debugging symbols used by gdb debugger."
  },
  {
    "question": "[Module 001_001] What is a Segmentation Fault (SIGSEGV) in program execution?",
    "options": [
      "A hardware/OS exception triggered when a program attempts to access a memory address it does not own or have permission to read/write",
      "A syntax error",
      "A loop error",
      "A missing header"
    ],
    "answerIndex": 0,
    "explanation": "Segmentation Fault occurs when accessing invalid memory (e.g. dereferencing NULL or out-of-bound pointers)."
  },
  {
    "question": "[Module 001_001] Why is C described as a 'middle-level' language?",
    "options": [
      "Combines high-level structured control constructs with low-level direct memory/hardware manipulation capabilities",
      "Runs half as fast as assembly",
      "Only runs on mid-size computers",
      "Lacks pointers"
    ],
    "answerIndex": 0,
    "explanation": "C provides structured abstractions (functions, loops) alongside hardware-level access (pointers, bitwise ops)."
  },
  {
    "question": "[Module 001_002] What is the smallest individual unit of a C program recognized by the lexer?",
    "options": [
      "Token",
      "Statement",
      "Instruction",
      "Expression"
    ],
    "answerIndex": 0,
    "explanation": "A token is the smallest individual unit of a C program."
  },
  {
    "question": "[Module 001_002] How many categories of tokens are defined in standard C?",
    "options": [
      "6 (Keywords, Identifiers, Constants, Strings, Special Symbols, Operators)",
      "4",
      "5",
      "8"
    ],
    "answerIndex": 0,
    "explanation": "C tokens are classified into 6 categories: Keywords, Identifiers, Constants, Strings, Special Symbols, Operators."
  },
  {
    "question": "[Module 001_002] How many keywords were defined in standard ANSI C89?",
    "options": [
      "32",
      "24",
      "48",
      "60"
    ],
    "answerIndex": 0,
    "explanation": "ANSI C89 specified exactly 32 reserved keywords."
  },
  {
    "question": "[Module 001_002] Which of the following is a valid identifier name in C?",
    "options": [
      "_userValue1",
      "1userValue",
      "default",
      "user-value"
    ],
    "answerIndex": 0,
    "explanation": "'_userValue1' is valid. Identifiers cannot start with digits, contain hyphens, or use reserved keywords like 'default'."
  },
  {
    "question": "[Module 001_002] What rule dictates that the lexer picks the longest sequence of characters that forms a valid token?",
    "options": [
      "Maximal Munch Rule",
      "Shortest Match",
      "Operator Priority",
      "Lexical Binding"
    ],
    "answerIndex": 0,
    "explanation": "Maximal Munch specifies that the lexer constructs the longest valid token possible from input characters."
  },
  {
    "question": "[Module 001_002] What is the size of 'char' on all ISO C compliant systems?",
    "options": [
      "EXACTLY 1 byte (sizeof(char) == 1)",
      "2 bytes",
      "4 bytes",
      "Implementation-defined"
    ],
    "answerIndex": 0,
    "explanation": "ISO C defines sizeof(char) to be EXACTLY 1 byte on all systems."
  },
  {
    "question": "[Module 001_002] What is CHAR_BIT in <limits.h>?",
    "options": [
      "The number of bits in a char byte (typically 8)",
      "4",
      "16",
      "32"
    ],
    "answerIndex": 0,
    "explanation": "CHAR_BIT specifies the number of bits in a byte (8 on standard hardware)."
  },
  {
    "question": "[Module 001_002] What is the typical size of 'int' on 32-bit and 64-bit x86 architectures?",
    "options": [
      "4 bytes (32 bits)",
      "2 bytes",
      "8 bytes",
      "1 byte"
    ],
    "answerIndex": 0,
    "explanation": "On modern 32-bit and 64-bit systems, 'int' is 4 bytes (32 bits)."
  },
  {
    "question": "[Module 001_002] What is the precision and size of an IEEE 754 'float' type?",
    "options": [
      "4 bytes (32 bits), ~6-7 decimal digits precision",
      "8 bytes, 15 digits",
      "2 bytes, 3 digits",
      "16 bytes"
    ],
    "answerIndex": 0,
    "explanation": "IEEE 754 float uses 4 bytes and provides ~6-7 decimal digits precision."
  },
  {
    "question": "[Module 001_002] What is the precision and size of an IEEE 754 'double' type?",
    "options": [
      "8 bytes (64 bits), ~15-17 decimal digits precision",
      "4 bytes, 7 digits",
      "12 bytes",
      "16 bytes"
    ],
    "answerIndex": 0,
    "explanation": "IEEE 754 double uses 8 bytes and provides ~15-17 decimal digits precision."
  },
  {
    "question": "[Module 001_002] What is the range of a 2's complement signed 8-bit integer (signed char)?",
    "options": [
      "-128 to +127",
      "0 to 255",
      "-255 to +255",
      "-127 to +128"
    ],
    "answerIndex": 0,
    "explanation": "8-bit signed char ranges from -128 to +127."
  },
  {
    "question": "[Module 001_002] What is the range of an unsigned 8-bit integer (unsigned char)?",
    "options": [
      "0 to 255",
      "-128 to +127",
      "0 to 65535",
      "-255 to +255"
    ],
    "answerIndex": 0,
    "explanation": "8-bit unsigned char ranges from 0 to 255."
  },
  {
    "question": "[Module 001_002] What happens when an unsigned integer exceeds its maximum representable value in C?",
    "options": [
      "Wraps around modulo 2^N (well-defined arithmetic overflow)",
      "Undefined Behavior",
      "Runtime crash",
      "Capped at max"
    ],
    "answerIndex": 0,
    "explanation": "Unsigned integer overflow is well-defined: it wraps around modulo 2^N."
  },
  {
    "question": "[Module 001_002] What happens when a signed integer overflows in C (e.g. INT_MAX + 1)?",
    "options": [
      "Triggers Undefined Behavior (UB)",
      "Wraps to INT_MIN predictably",
      "Crashes OS",
      "Converts to float"
    ],
    "answerIndex": 0,
    "explanation": "Signed integer overflow results in Undefined Behavior (UB) in standard C."
  },
  {
    "question": "[Module 001_002] Which header file defines integer data type limits like INT_MAX and CHAR_MIN?",
    "options": [
      "<limits.h>",
      "<float.h>",
      "<math.h>",
      "<stddef.h>"
    ],
    "answerIndex": 0,
    "explanation": "<limits.h> defines integer type boundary limits."
  },
  {
    "question": "[Module 001_002] Which header file defines exact-width integer types like int32_t and uint8_t?",
    "options": [
      "<stdint.h>",
      "<stdlib.h>",
      "<limits.h>",
      "<stddef.h>"
    ],
    "answerIndex": 0,
    "explanation": "<stdint.h> provides exact-width integer typedefs."
  },
  {
    "question": "[Module 001_002] What integer type from <stdint.h> is guaranteed to be large enough to safely hold a pointer address?",
    "options": [
      "intptr_t (or uintptr_t)",
      "intmax_t",
      "int32_t",
      "size_t"
    ],
    "answerIndex": 0,
    "explanation": "intptr_t and uintptr_t are guaranteed to hold pointer addresses without loss of data."
  },
  {
    "question": "[Module 001_002] Which data type model does 64-bit Linux use (Long & Pointer 64-bit, Int 32-bit)?",
    "options": [
      "LP64",
      "LLP64",
      "ILP32",
      "LP32"
    ],
    "answerIndex": 0,
    "explanation": "64-bit Linux/UNIX uses the LP64 data model."
  },
  {
    "question": "[Module 001_002] Which data type model does 64-bit Windows use (Long Long & Pointer 64-bit, Int & Long 32-bit)?",
    "options": [
      "LLP64",
      "LP64",
      "ILP32",
      "LP32"
    ],
    "answerIndex": 0,
    "explanation": "64-bit Windows uses the LLP64 data model."
  },
  {
    "question": "[Module 001_002] What prefix indicates an octal (base 8) integer literal in C?",
    "options": [
      "Leading zero '0' (e.g. 052)",
      "0x",
      "0b",
      "#"
    ],
    "answerIndex": 0,
    "explanation": "A leading zero '0' indicates an octal integer literal."
  },
  {
    "question": "[Module 001_002] What prefix indicates a hexadecimal (base 16) integer literal in C?",
    "options": [
      "0x (or 0X)",
      "0o",
      "0b",
      "16#"
    ],
    "answerIndex": 0,
    "explanation": "'0x' or '0X' indicates a hexadecimal literal."
  },
  {
    "question": "[Module 001_002] What prefix indicates a binary integer literal in C23 / GCC extension?",
    "options": [
      "0b (or 0B)",
      "0x",
      "0o",
      "bin#"
    ],
    "answerIndex": 0,
    "explanation": "'0b' or '0B' indicates a binary literal."
  },
  {
    "question": "[Module 001_002] What suffix forces a floating-point literal to be 'float' (e.g. 3.14f)?",
    "options": [
      "f or F",
      "d",
      "l",
      "s"
    ],
    "answerIndex": 0,
    "explanation": "Suffix 'f' or 'F' specifies single-precision float."
  },
  {
    "question": "[Module 001_002] What is the type of a character literal like 'A' in standard C?",
    "options": [
      "int (sizeof('A') == sizeof(int))",
      "char (1 byte)",
      "unsigned char",
      "float"
    ],
    "answerIndex": 0,
    "explanation": "In C, character literals like 'A' are typed as 'int'."
  },
  {
    "question": "[Module 001_002] What is sizeof(\"ABC\") in bytes?",
    "options": [
      "4 bytes (includes implicit '\\0' null terminator)",
      "3 bytes",
      "8 bytes",
      "2 bytes"
    ],
    "answerIndex": 0,
    "explanation": "\"ABC\" has 3 letters + 1 null terminator '\\0' = 4 bytes."
  },
  {
    "question": "[Module 001_002] What happens if a program modifies a character in a string literal (char *p = \"hi\"; p[0] = 'H';)?",
    "options": [
      "Undefined Behavior (typically Segmentation Fault crash because string literals reside in read-only memory)",
      "Updates string",
      "Ignored",
      "Compiler warning"
    ],
    "answerIndex": 0,
    "explanation": "Modifying string literals results in Undefined Behavior (crash)."
  },
  {
    "question": "[Module 001_002] What is the difference between '#define MAX 100' and 'const int MAX = 100;'?",
    "options": [
      "#define is preprocessor text substitution without type checking; const is a scoped read-only variable checked by compiler",
      "#define uses RAM",
      "No difference",
      "const cannot be used for numbers"
    ],
    "answerIndex": 0,
    "explanation": "#define is macro text replacement; const is a typed read-only variable."
  },
  {
    "question": "[Module 001_002] Can modulus operator (%) be applied to float/double operands in C?",
    "options": [
      "No, % is strictly restricted to integer types (use fmod() from <math.h> for floats)",
      "Yes",
      "Only for floats",
      "Only in GCC"
    ],
    "answerIndex": 0,
    "explanation": "% requires integer operands. Use fmod() for floating-point remainder."
  },
  {
    "question": "[Module 001_002] What is the result of integer division -7 / 2 in C99?",
    "options": [
      "-3 (truncation towards zero)",
      "-4",
      "-3.5",
      "Undefined"
    ],
    "answerIndex": 0,
    "explanation": "C99 mandates truncation towards zero for integer division."
  },
  {
    "question": "[Module 001_002] What is the value of expression: -10 % 3 in C99?",
    "options": [
      "-1",
      "1",
      "-3",
      "0"
    ],
    "answerIndex": 0,
    "explanation": "In C99, (a/b)*b + (a%b) == a. -10 % 3 evaluates to -1."
  },
  {
    "question": "[Module 001_002] What is the difference between prefix ++x and postfix x++?",
    "options": [
      "++x increments x before returning value; x++ returns current value first then increments x",
      "++x is slower",
      "x++ is for floats",
      "No difference"
    ],
    "answerIndex": 0,
    "explanation": "Prefix ++x returns updated value; postfix x++ returns old value first."
  },
  {
    "question": "[Module 001_002] What occurs if a variable is modified multiple times without a sequence point (x = x++ + ++x)?",
    "options": [
      "Undefined Behavior (UB)",
      "Evaluates 12",
      "Compiler fixes it",
      "Runs left to right"
    ],
    "answerIndex": 0,
    "explanation": "Modifying a variable multiple times without an intervening sequence point causes Undefined Behavior."
  },
  {
    "question": "[Module 001_002] What is short-circuit evaluation in logical AND (&&)?",
    "options": [
      "If left operand is false (0), right operand is NOT evaluated",
      "If left is true, right is skipped",
      "Both evaluated parallel",
      "Right evaluated first"
    ],
    "answerIndex": 0,
    "explanation": "In &&, if left operand is 0, evaluation stops immediately."
  },
  {
    "question": "[Module 001_002] What is short-circuit evaluation in logical OR (||)?",
    "options": [
      "If left operand is true (non-zero), right operand is NOT evaluated",
      "If left is false, right is skipped",
      "Both evaluated parallel",
      "Throws exception"
    ],
    "answerIndex": 0,
    "explanation": "In ||, if left operand is true, evaluation stops immediately."
  },
  {
    "question": "[Module 001_002] What is the result of !(-5) in C?",
    "options": [
      "0",
      "1",
      "5",
      "-5"
    ],
    "answerIndex": 0,
    "explanation": "Since -5 is non-zero (true), !(-5) evaluates to 0 (false)."
  },
  {
    "question": "[Module 001_002] Which operator has the lowest precedence in all of C?",
    "options": [
      "Comma operator (,)",
      "Assignment (=)",
      "Logical OR (||)",
      "Ternary (? :)"
    ],
    "answerIndex": 0,
    "explanation": "The comma operator (,) has the lowest precedence."
  },
  {
    "question": "[Module 001_002] What is the result of bitwise AND: 5 & 3 (00000101 & 00000011)?",
    "options": [
      "1 (00000001)",
      "7",
      "6",
      "8"
    ],
    "answerIndex": 0,
    "explanation": "00000101 & 00000011 = 00000001 (1)."
  },
  {
    "question": "[Module 001_002] What is the result of bitwise OR: 5 | 3 (00000101 | 00000011)?",
    "options": [
      "7 (00000111)",
      "1",
      "6",
      "15"
    ],
    "answerIndex": 0,
    "explanation": "00000101 | 00000011 = 00000111 (7)."
  },
  {
    "question": "[Module 001_002] What is the result of bitwise XOR: 5 ^ 3 (00000101 ^ 00000011)?",
    "options": [
      "6 (00000110)",
      "1",
      "7",
      "2"
    ],
    "answerIndex": 0,
    "explanation": "00000101 ^ 00000011 = 00000110 (6)."
  },
  {
    "question": "[Module 001_002] What operation sets bit n of variable x to 1?",
    "options": [
      "x |= (1 << n)",
      "x &= ~(1 << n)",
      "x ^= (1 << n)",
      "x >>= n"
    ],
    "answerIndex": 0,
    "explanation": "x |= (1 << n) sets bit n to 1."
  },
  {
    "question": "[Module 001_002] What operation clears bit n of variable x to 0?",
    "options": [
      "x &= ~(1 << n)",
      "x |= (1 << n)",
      "x ^= (1 << n)",
      "x &= (1 << n)"
    ],
    "answerIndex": 0,
    "explanation": "x &= ~(1 << n) clears bit n to 0."
  },
  {
    "question": "[Module 001_002] What operation toggles (flips) bit n of variable x?",
    "options": [
      "x ^= (1 << n)",
      "x |= (1 << n)",
      "x &= ~(1 << n)",
      "x = ~x"
    ],
    "answerIndex": 0,
    "explanation": "x ^= (1 << n) flips bit n."
  },
  {
    "question": "[Module 001_002] What does expression x & (x - 1) do?",
    "options": [
      "Clears the lowest set bit (rightmost 1-bit) of x",
      "Sets lowest bit",
      "Doubles x",
      "Inverts x"
    ],
    "answerIndex": 0,
    "explanation": "x & (x - 1) clears the rightmost set bit of x."
  },
  {
    "question": "[Module 001_002] How do you check if positive integer x is a power of 2?",
    "options": [
      "(x > 0) && ((x & (x - 1)) == 0)",
      "(x & 2) == 0",
      "(x | (x - 1)) == 0",
      "(x ^ 2) == 0"
    ],
    "answerIndex": 0,
    "explanation": "If x > 0 and x & (x - 1) == 0, x is a power of 2."
  },
  {
    "question": "[Module 001_002] What is the nature of the sizeof operator in C?",
    "options": [
      "Compile-time unary operator (operand inside sizeof is NOT evaluated at runtime)",
      "Runtime function",
      "Preprocessor macro",
      "Hardware flag"
    ],
    "answerIndex": 0,
    "explanation": "sizeof is a compile-time operator; expressions inside sizeof are not executed."
  },
  {
    "question": "[Module 001_002] Given int i = 5; sizeof(i++); what is the value of i after this line?",
    "options": [
      "5 (i++ inside sizeof is not executed at runtime)",
      "6",
      "0",
      "Undefined"
    ],
    "answerIndex": 0,
    "explanation": "sizeof operands are unevaluated contexts; i remains 5."
  },
  {
    "question": "[Module 001_002] What type does sizeof operator return?",
    "options": [
      "size_t (unsigned integer type defined in <stddef.h>)",
      "int",
      "long",
      "unsigned int"
    ],
    "answerIndex": 0,
    "explanation": "sizeof returns size_t."
  },
  {
    "question": "[Module 001_002] What is Integer Promotion in C?",
    "options": [
      "Types smaller than int (char, short) are automatically converted to 'int' before arithmetic/bitwise operations",
      "Converting int to float",
      "Global variables",
      "Signed to unsigned"
    ],
    "answerIndex": 0,
    "explanation": "Types smaller than int are promoted to 'int' before evaluation."
  },
  {
    "question": "[Module 001_002] What is the outcome of comparison (-1 > 1U) on 32-bit int system?",
    "options": [
      "Evaluates to 1 (true) because signed -1 is converted to unsigned int (UINT_MAX, 4294967295), which is > 1!",
      "Evaluates 0 (false)",
      "Compiler error",
      "Evaluates -1"
    ],
    "answerIndex": 0,
    "explanation": "Usual arithmetic conversions promote -1 to unsigned int (4294967295 > 1 is TRUE!)."
  },
  {
    "question": "[Module 001_002] What is the result of expression: (float) 7 / 2?",
    "options": [
      "3.5f",
      "3.0f",
      "3f",
      "4.0f"
    ],
    "answerIndex": 0,
    "explanation": "(float) 7 gives 7.0f; 7.0f / 2 triggers float division giving 3.5f."
  },
  {
    "question": "[Module 001_003] How does an 'if' statement evaluate its condition expression in C?",
    "options": [
      "Any non-zero value is treated as true (1); zero (0) is treated as false",
      "Only 1 is true",
      "Only positive integers",
      "Strings only"
    ],
    "answerIndex": 0,
    "explanation": "Any non-zero value is true; 0 is false."
  },
  {
    "question": "[Module 001_003] What is the output of: int x = 0; if (x = 5) printf(\"YES\"); else printf(\"NO\");?",
    "options": [
      "YES",
      "NO",
      "Compiler error",
      "Nothing"
    ],
    "answerIndex": 0,
    "explanation": "(x = 5) assigns 5 and evaluates to 5 (true). 'YES' is printed."
  },
  {
    "question": "[Module 001_003] What is the output of: int x = 5; if (x == 10); printf(\"HELLO\");?",
    "options": [
      "HELLO is printed unconditionally",
      "Nothing",
      "Compiler error",
      "HELLO printed if x==10"
    ],
    "answerIndex": 0,
    "explanation": "Semicolon ';' forms a null statement body. printf(\"HELLO\") executes unconditionally."
  },
  {
    "question": "[Module 001_003] To which 'if' statement does an 'else' clause attach in nested structures (Dangling Else)?",
    "options": [
      "To the nearest preceding unclosed 'if' statement in the same block scope",
      "First if",
      "Matching indentation",
      "Compiler error"
    ],
    "answerIndex": 0,
    "explanation": "'else' pairs with nearest preceding unclosed 'if' in the same scope."
  },
  {
    "question": "[Module 001_003] What types are permitted as controlling expressions in a C 'switch' statement?",
    "options": [
      "Integer types only (int, char, enum, short, long)",
      "Floats",
      "Strings",
      "Any data type"
    ],
    "answerIndex": 0,
    "explanation": "switch expressions must evaluate to integer types."
  },
  {
    "question": "[Module 001_003] What requirement applies to case label values in a switch statement?",
    "options": [
      "Must be compile-time integer constant expressions",
      "Can be variables",
      "Can be floats",
      "Can be strings"
    ],
    "answerIndex": 0,
    "explanation": "Case labels must be compile-time integer constant expressions."
  },
  {
    "question": "[Module 001_003] What is 'fall-through' behavior in switch cases?",
    "options": [
      "Execution continues into subsequent case blocks unless interrupted by break or return",
      "Switch crashes",
      "Variables fall out of scope",
      "Default runs first"
    ],
    "answerIndex": 0,
    "explanation": "Control falls through into subsequent cases unless break/return is hit."
  },
  {
    "question": "[Module 001_003] How do compilers optimize dense switch statements with contiguous integer cases?",
    "options": [
      "By generating a hardware Jump Table (branch table) for O(1) constant-time dispatch",
      "Converting to loop",
      "Ignoring break",
      "Slow scan"
    ],
    "answerIndex": 0,
    "explanation": "Dense switches are optimized into Jump Tables for O(1) jump."
  },
  {
    "question": "[Module 001_003] What is an entry-controlled (pre-test) loop construct in C?",
    "options": [
      "A loop where condition is tested BEFORE executing loop body (while, for)",
      "do-while loop",
      "Exit loop",
      "Infinite loop"
    ],
    "answerIndex": 0,
    "explanation": "Entry-controlled loops (while, for) test conditions before running loop body."
  },
  {
    "question": "[Module 001_003] What is an exit-controlled (post-test) loop construct in C?",
    "options": [
      "A loop where condition is tested AFTER executing loop body (do-while)",
      "for loop",
      "while loop",
      "Entry loop"
    ],
    "answerIndex": 0,
    "explanation": "Exit-controlled loop (do-while) tests condition after running body."
  },
  {
    "question": "[Module 001_003] How many times is a 'do-while' loop body guaranteed to execute?",
    "options": [
      "At least 1 time",
      "0 times",
      "2 times",
      "10 times"
    ],
    "answerIndex": 0,
    "explanation": "do-while executes at least once because test is at the end."
  },
  {
    "question": "[Module 001_003] What happens if all expressions are omitted in a for loop: for (;;) { ... }?",
    "options": [
      "Creates an intentional INFINITE LOOP",
      "Compiler error",
      "Executes 0 times",
      "Executes 1 time"
    ],
    "answerIndex": 0,
    "explanation": "for (;;) omits test condition, defaulting to true (infinite loop)."
  },
  {
    "question": "[Module 001_003] What is the scope of a variable declared inside a C99 for loop header: for (int i = 0; ...)?",
    "options": [
      "Block scope restricted exclusively to the for loop statement and body",
      "Global scope",
      "Function scope",
      "File scope"
    ],
    "answerIndex": 0,
    "explanation": "Variable 'i' is scoped strictly to the for loop."
  },
  {
    "question": "[Module 001_003] What is the output of: int i = 5; while (i > 0); { printf(\"%d\", i); i--; }?",
    "options": [
      "Infinite loop (stuck at empty statement while (i > 0);)",
      "54321",
      "5",
      "Compiler error"
    ],
    "answerIndex": 0,
    "explanation": "Semicolon ';' forms null body; i remains 5, trapping execution in an infinite null loop."
  },
  {
    "question": "[Module 001_003] What statement syntactically terminates a do-while loop in C?",
    "options": [
      "while (condition); (with mandatory trailing semicolon)",
      "while (condition)",
      "end do;",
      "until;"
    ],
    "answerIndex": 0,
    "explanation": "do-while strictly requires trailing semicolon after condition."
  },
  {
    "question": "[Module 001_003] What is the effect of executing 'break' inside a loop?",
    "options": [
      "Immediately terminates innermost enclosing loop and transfers control to following statement",
      "Skips iteration",
      "Exits program",
      "Restarts loop"
    ],
    "answerIndex": 0,
    "explanation": "break terminates the innermost loop immediately."
  },
  {
    "question": "[Module 001_003] What is the effect of executing 'continue' inside a loop?",
    "options": [
      "Skips remaining statements in current iteration and jumps directly to loop condition/update check",
      "Terminates loop",
      "Exits main",
      "Restarts program"
    ],
    "answerIndex": 0,
    "explanation": "continue skips to the next iteration evaluation."
  },
  {
    "question": "[Module 001_003] In a 'for' loop, where does execution jump when 'continue' is encountered?",
    "options": [
      "Directly to loop increment/update expression (expr3)",
      "Initialization",
      "After loop",
      "Top of main"
    ],
    "answerIndex": 0,
    "explanation": "In for loop, continue jumps to increment/update expression (expr3)."
  },
  {
    "question": "[Module 001_003] If 'break' is executed inside an INNER nested loop, which loop does it terminate?",
    "options": [
      "Only the innermost loop containing the break statement",
      "All loops",
      "Outermost loop",
      "Function"
    ],
    "answerIndex": 0,
    "explanation": "break terminates ONLY the single innermost loop."
  },
  {
    "question": "[Module 001_003] What is the goto statement in C used for?",
    "options": [
      "Unconditional transfer of control to a named statement label within the SAME function",
      "Cross file jump",
      "Break functions",
      "System calls"
    ],
    "answerIndex": 0,
    "explanation": "goto jumps unconditionally to a label within the same function."
  },
  {
    "question": "[Module 001_003] Can 'goto' jump to a label defined inside a completely different function?",
    "options": [
      "No, goto targets are strictly scoped to labels within the SAME function",
      "Yes",
      "Only global functions",
      "Only in C23"
    ],
    "answerIndex": 0,
    "explanation": "goto cannot jump across functions in C."
  },
  {
    "question": "[Module 001_003] What is a legitimate use case for 'goto' in Linux kernel programming?",
    "options": [
      "Cleanup and error recovery routing to release resources before function exit",
      "Replacing for loops",
      "Nested loops",
      "Recursion"
    ],
    "answerIndex": 0,
    "explanation": "goto is standard in systems code for centralized error cleanup."
  },
  {
    "question": "[Module 001_003] How do you break out of multiple nested loops at once in standard C?",
    "options": [
      "Use 'goto' to jump to a label placed outside the outermost loop",
      "break 2;",
      "continue all;",
      "return loop;"
    ],
    "answerIndex": 0,
    "explanation": "Using goto is the standard idiomatic way to break out of multi-level nested loops."
  },
  {
    "question": "[Module 001_003] How many total iterations occur in a nested loop where outer loop runs N times and inner loop runs M times?",
    "options": [
      "N * M",
      "N + M",
      "N^M",
      "M^N"
    ],
    "answerIndex": 0,
    "explanation": "Total iterations = N * M."
  },
  {
    "question": "[Module 001_003] What coordinate mapping convention is standard for 2D matrix pattern printing?",
    "options": [
      "Outer loop controls ROWS (r), Inner loop controls COLUMNS (c)",
      "Outer cols, Inner rows",
      "Both rows",
      "Outer color"
    ],
    "answerIndex": 0,
    "explanation": "Outer loop controls rows; inner loop controls columns."
  },
  {
    "question": "[Module 001_003] What pattern is printed by: for (r=1..4) { for (c=1..r) print \"*\"; print \"\\n\"; }?",
    "options": [
      "Left-aligned right-angled triangle of stars",
      "Square",
      "Inverted triangle",
      "Pyramid"
    ],
    "answerIndex": 0,
    "explanation": "Row 1 has 1 star, Row 2 has 2... forms right-angled triangle."
  },
  {
    "question": "[Module 001_003] How many leading spaces are needed on row r (1 to N) for a centered star pyramid?",
    "options": [
      "N - r spaces",
      "r - 1 spaces",
      "r spaces",
      "N + r spaces"
    ],
    "answerIndex": 0,
    "explanation": "Centered pyramid requires (N - r) leading spaces on row r."
  },
  {
    "question": "[Module 001_003] How many stars are on row r (1 to N) for a centered isosceles star pyramid?",
    "options": [
      "2 * r - 1 stars (odd series: 1, 3, 5, 7, 9)",
      "r stars",
      "2 * r stars",
      "r + 2 stars"
    ],
    "answerIndex": 0,
    "explanation": "Odd series (2 * r - 1) stars on row r."
  },
  {
    "question": "[Module 001_003] What is Floyd's Triangle?",
    "options": [
      "Right-angled triangle filled with consecutive natural numbers (1 / 2 3 / 4 5 6 / 7 8 9 10)",
      "Prime triangle",
      "Pascal triangle",
      "Zero matrix"
    ],
    "answerIndex": 0,
    "explanation": "Floyd's Triangle contains consecutive natural numbers."
  },
  {
    "question": "[Module 001_003] What condition identifies elements on the main (primary) diagonal of an N x N matrix (0-indexed)?",
    "options": [
      "(r == c)",
      "(r + c == N - 1)",
      "r == 0",
      "c == 0"
    ],
    "answerIndex": 0,
    "explanation": "(r == c) identifies primary diagonal elements."
  },
  {
    "question": "[Module 001_003] What condition identifies elements on the secondary (anti) diagonal of an N x N matrix?",
    "options": [
      "(r + c == N - 1)",
      "(r == c)",
      "r == N",
      "c == N"
    ],
    "answerIndex": 0,
    "explanation": "(r + c == N - 1) identifies anti-diagonal elements."
  },
  {
    "question": "[Module 001_003] What condition identifies boundary (border) cells of an N x M matrix (0-indexed)?",
    "options": [
      "(r == 0 || r == N - 1 || c == 0 || c == M - 1)",
      "(r == c)",
      "(r + c == 0)",
      "(r == N)"
    ],
    "answerIndex": 0,
    "explanation": "Boundary cells lie on row 0, last row N-1, col 0, or last col M-1."
  },
  {
    "question": "[Module 001_003] What is Pascal's Triangle?",
    "options": [
      "Triangular array of binomial coefficients C(n, k) where each entry is sum of two numbers directly above it",
      "Random numbers",
      "Floyd triangle",
      "Powers of 2"
    ],
    "answerIndex": 0,
    "explanation": "Pascal's Triangle represents binomial coefficients."
  },
  {
    "question": "[Module 001_003] What formula computes entry at row n, col k (0-indexed) in Pascal's Triangle?",
    "options": [
      "n! / (k! * (n - k)!) (Combination formula C(n, k))",
      "n^k",
      "n * k",
      "n + k"
    ],
    "answerIndex": 0,
    "explanation": "Binomial formula C(n, k) = n! / (k! * (n - k)!)."
  },
  {
    "question": "[Module 001_003] What is a Prime Number?",
    "options": [
      "Integer > 1 with no positive divisors other than 1 and itself",
      "Odd integer",
      "Negative integer",
      "Divisible by 2"
    ],
    "answerIndex": 0,
    "explanation": "A prime is an integer > 1 divisible only by 1 and itself."
  },
  {
    "question": "[Module 001_003] What is the optimal upper limit for trial division prime checking of N?",
    "options": [
      "sqrt(N) (square root of N)",
      "N / 2",
      "N - 1",
      "N"
    ],
    "answerIndex": 0,
    "explanation": "Testing factors up to sqrt(N) is sufficient for primality test."
  },
  {
    "question": "[Module 001_003] What is an Armstrong Number for a 3-digit integer?",
    "options": [
      "Number equal to sum of cubes of its digits (e.g. 153 = 1^3 + 5^3 + 3^3)",
      "Sum of digits",
      "Product of digits",
      "Prime"
    ],
    "answerIndex": 0,
    "explanation": "153 = 1^3 + 5^3 + 3^3 = 153 (Armstrong Number)."
  },
  {
    "question": "[Module 001_003] How do you extract the last digit of integer N in C?",
    "options": [
      "N % 10",
      "N / 10",
      "N - 10",
      "N * 10"
    ],
    "answerIndex": 0,
    "explanation": "N % 10 extracts the rightmost units digit."
  },
  {
    "question": "[Module 001_003] How do you remove the last digit of integer N in C?",
    "options": [
      "N = N / 10",
      "N = N % 10",
      "N = N - 10",
      "N = N * 10"
    ],
    "answerIndex": 0,
    "explanation": "Integer division N / 10 truncates the rightmost digit."
  },
  {
    "question": "[Module 001_003] What is a Palindrome Number?",
    "options": [
      "Number identical when digits are reversed (e.g. 121, 1331)",
      "Prime",
      "Divisible by 10",
      "Even"
    ],
    "answerIndex": 0,
    "explanation": "A palindrome reads the same forwards and backwards."
  },
  {
    "question": "[Module 001_003] What is the Fibonacci sequence definition?",
    "options": [
      "F(0)=0, F(1)=1, and F(n) = F(n-1) + F(n-2) for n >= 2 (0, 1, 1, 2, 3, 5, 8...)",
      "Primes",
      "Squares",
      "Powers of 2"
    ],
    "answerIndex": 0,
    "explanation": "Fibonacci sequence sums the previous two terms."
  },
  {
    "question": "[Module 001_003] What is a Perfect Number?",
    "options": [
      "Positive integer equal to sum of its proper positive divisors (excluding itself, e.g. 6 = 1 + 2 + 3)",
      "Square number",
      "Prime",
      "Power of 10"
    ],
    "answerIndex": 0,
    "explanation": "6 is a perfect number because 1 + 2 + 3 = 6."
  },
  {
    "question": "[Module 001_003] What algorithm computes GCD(a, b) efficiently using repeated modulus?",
    "options": [
      "Euclidean Algorithm",
      "Sieve of Eratosthenes",
      "Binary search",
      "Bubble sort"
    ],
    "answerIndex": 0,
    "explanation": "Euclidean Algorithm calculates GCD via repeated modulus."
  },
  {
    "question": "[Module 001_003] What is the relation between GCD(a, b) and LCM(a, b)?",
    "options": [
      "a * b = GCD(a, b) * LCM(a, b)",
      "LCM = a + b",
      "GCD = LCM",
      "LCM = a * b * GCD"
    ],
    "answerIndex": 0,
    "explanation": "Product of two numbers equals product of their GCD and LCM."
  },
  {
    "question": "[Module 001_003] What is a Strong Number (Krishnamurthy Number)?",
    "options": [
      "Number equal to sum of factorials of its digits (e.g. 145 = 1! + 4! + 5!)",
      "Divisible by 10",
      "Prime",
      "Armstrong"
    ],
    "answerIndex": 0,
    "explanation": "145 = 1! + 4! + 5! = 1 + 24 + 120 = 145 (Strong Number)."
  },
  {
    "question": "[Module 001_003] What is an Automorphic Number?",
    "options": [
      "Number whose square ends in the same digits as the number itself (e.g. 25^2 = 625)",
      "Cube equal",
      "Prime",
      "Self divisible"
    ],
    "answerIndex": 0,
    "explanation": "25^2 = 625 (ends in 25, automorphic)."
  },
  {
    "question": "[Module 001_003] What is a Harshad Number?",
    "options": [
      "Integer divisible by the sum of its digits (e.g. 18 -> 1+8=9; 18 % 9 == 0)",
      "No factors",
      "Prime",
      "Negative"
    ],
    "answerIndex": 0,
    "explanation": "18 is divisible by (1 + 8 = 9) -> Harshad Number."
  },
  {
    "question": "[Module 001_003] What is the sum of first N natural numbers formula: 1 + 2 + ... + N?",
    "options": [
      "N * (N + 1) / 2",
      "N * N",
      "N * (N - 1) / 2",
      "2 * N"
    ],
    "answerIndex": 0,
    "explanation": "Sum of first N natural numbers = N * (N + 1) / 2."
  },
  {
    "question": "[Module 001_003] What is the output of: int i=0; while(i<3) { switch(i) { case 0: i+=1; break; case 1: i+=2; break; } printf(\"%d \", i); }?",
    "options": [
      "1 3 ",
      "1 2 3 ",
      "0 1 2 ",
      "Infinite loop"
    ],
    "answerIndex": 0,
    "explanation": "Iter 1: i=0 matches case 0 -> i=1, prints 1. Iter 2: i=1 matches case 1 -> i=3, prints 3. Exit. Output: '1 3 '."
  },
  {
    "question": "[Module 001_003] In a switch embedded in a loop, what does 'break' inside a case exit from?",
    "options": [
      "It exits the switch statement ONLY (surrounding loop continues)",
      "Exits loop",
      "Exits main",
      "Exits both"
    ],
    "answerIndex": 0,
    "explanation": "break inside a switch exits ONLY the switch block."
  },
  {
    "question": "[Module 001_004] What is a function prototype (declaration) in C?",
    "options": [
      "Statement informing compiler about function signature (return type, name, parameter types) before usage",
      "Implementation body",
      "Macro replacement",
      "Global variable"
    ],
    "answerIndex": 0,
    "explanation": "A prototype declares function signature to compiler before usage."
  },
  {
    "question": "[Module 001_004] Where are function prototypes typically placed?",
    "options": [
      "At the top of C source file or inside header file (.h) before main()",
      "Inside return",
      "After main",
      "Inside loop"
    ],
    "answerIndex": 0,
    "explanation": "Prototypes are placed before function calls at file top or in headers."
  },
  {
    "question": "[Module 001_004] What does 'int getValue(void);' specify?",
    "options": [
      "Function strictly accepts ZERO arguments",
      "Accepts variable arguments",
      "Takes void pointer",
      "Returns void"
    ],
    "answerIndex": 0,
    "explanation": "(void) in parameter list specifies zero arguments."
  },
  {
    "question": "[Module 001_004] Which keyword suggests expanding function code directly at call site to eliminate call overhead?",
    "options": [
      "inline",
      "static",
      "extern",
      "register"
    ],
    "answerIndex": 0,
    "explanation": "'inline' requests compiler inlining at call site."
  },
  {
    "question": "[Module 001_004] What is modular programming in C?",
    "options": [
      "Decomposing a large program into independent, reusable functions across header (.h) and source (.c) files",
      "Writing everything in main()",
      "Hardware threads",
      "No loops"
    ],
    "answerIndex": 0,
    "explanation": "Modular design breaks code into reusable functions and files."
  },
  {
    "question": "[Module 001_004] What header guard mechanism prevents duplicate inclusion redefinition errors?",
    "options": [
      "#ifndef HEADER_H \\n #define HEADER_H \\n ... \\n #endif",
      "#includeonce",
      "#import",
      "#pragma loop"
    ],
    "answerIndex": 0,
    "explanation": "Header guards prevent duplicate header inclusion errors."
  },
  {
    "question": "[Module 001_004] What single-line preprocessor directive acts as a modern header guard?",
    "options": [
      "#pragma once",
      "#guard",
      "#define once",
      "#once"
    ],
    "answerIndex": 0,
    "explanation": "#pragma once prevents multiple header inclusion."
  },
  {
    "question": "[Module 001_004] Does standard C support function overloading (multiple functions with same name)?",
    "options": [
      "No, C does NOT support function overloading",
      "Yes",
      "Only in C99",
      "Only for floats"
    ],
    "answerIndex": 0,
    "explanation": "C does not support function overloading."
  },
  {
    "question": "[Module 001_004] What default parameter passing mechanism does C use for scalar variables?",
    "options": [
      "Call by Value",
      "Call by Reference",
      "Call by Name",
      "Call by Result"
    ],
    "answerIndex": 0,
    "explanation": "C strictly uses Call by Value by default."
  },
  {
    "question": "[Module 001_004] How is Call by Reference simulated in C?",
    "options": [
      "By passing variable memory addresses (pointers) as arguments to pointer parameters",
      "ref keyword",
      "Global variables",
      "Return two values"
    ],
    "answerIndex": 0,
    "explanation": "Call by Reference is simulated by passing pointer addresses (&var)."
  },
  {
    "question": "[Module 001_004] When an array is passed to a function (void process(int arr[])), what actually happens?",
    "options": [
      "The array automatically DECAYS into a pointer to its first element (&arr[0])",
      "Array is copied",
      "Size is passed",
      "Struct passed"
    ],
    "answerIndex": 0,
    "explanation": "Arrays decay to pointers when passed to functions."
  },
  {
    "question": "[Module 001_004] Are modifications to array elements inside a function reflected in caller's array?",
    "options": [
      "Yes, because function operates directly on caller's memory via the decayed pointer",
      "No",
      "Only static arrays",
      "Only 1D"
    ],
    "answerIndex": 0,
    "explanation": "Array parameter pointer mutations modify caller array directly."
  },
  {
    "question": "[Module 001_004] What happens inside a function when sizeof(arr) is called on an array parameter 'int arr[]'?",
    "options": [
      "sizeof(arr) returns sizeof(int*) (pointer size, 4 or 8 bytes), NOT full array size!",
      "Returns array size",
      "Returns element count",
      "Compiler error"
    ],
    "answerIndex": 0,
    "explanation": "Inside function, arr is a pointer; sizeof(arr) returns pointer size."
  },
  {
    "question": "[Module 001_004] Can a function return a pointer to its local automatic stack variable (int* get() { int x=5; return &x; })?",
    "options": [
      "NO! Returns Dangling Pointer causing Undefined Behavior because local stack frame is destroyed on return!",
      "Yes",
      "Yes valid",
      "Only C99"
    ],
    "answerIndex": 0,
    "explanation": "Returning &x of a local automatic variable creates a dangerous dangling pointer."
  },
  {
    "question": "[Module 001_004] How can a function safely return a memory pointer allocated inside it?",
    "options": [
      "Allocate memory on HEAP using malloc(), or return pointer to static variable",
      "Return &local",
      "Use auto",
      "Return &param"
    ],
    "answerIndex": 0,
    "explanation": "Heap memory (malloc) or static memory persists after function returns."
  },
  {
    "question": "[Module 001_004] Which header file provides macros for variadic function handling (va_list, va_start, va_arg, va_end)?",
    "options": [
      "<stdarg.h>",
      "<stdlib.h>",
      "<stdio.h>",
      "<stddef.h>"
    ],
    "answerIndex": 0,
    "explanation": "<stdarg.h> provides variadic argument macros."
  },
  {
    "question": "[Module 001_004] In variadic functions, what default argument promotion applies to 'float' parameters passed to '...'?",
    "options": [
      "float is automatically promoted to 'double' (va_arg must specify double)",
      "float remains float",
      "float to int",
      "float error"
    ],
    "answerIndex": 0,
    "explanation": "Variadic calls promote float to double."
  },
  {
    "question": "[Module 001_004] What is Variable Scope in C?",
    "options": [
      "Region of source code text where variable identifier is visible and accessible",
      "RAM address",
      "Time duration",
      "Byte size"
    ],
    "answerIndex": 0,
    "explanation": "Scope defines code visibility region."
  },
  {
    "question": "[Module 001_004] What is Variable Lifetime (Storage Duration)?",
    "options": [
      "Period of program execution time during which variable exists in RAM memory",
      "Lines of text",
      "Data type",
      "Variable name"
    ],
    "answerIndex": 0,
    "explanation": "Lifetime defines memory temporal duration."
  },
  {
    "question": "[Module 001_004] What is default initial value of uninitialized local automatic variable?",
    "options": [
      "Indeterminate garbage value",
      "0",
      "NULL",
      "1"
    ],
    "answerIndex": 0,
    "explanation": "Local automatic variables contain garbage values."
  },
  {
    "question": "[Module 001_004] What is default initial value of uninitialized global or static variable?",
    "options": [
      "Implicitly zero-initialized (0 / NULL)",
      "Garbage value",
      "1",
      "Undefined"
    ],
    "answerIndex": 0,
    "explanation": "Global and static variables are zero-initialized at program startup."
  },
  {
    "question": "[Module 001_004] What is Linkage in C?",
    "options": [
      "Property governing whether multiple declarations of an identifier refer to the same object across translation units",
      "Database link",
      "HTML link",
      "Loop compile"
    ],
    "answerIndex": 0,
    "explanation": "Linkage determines cross-scope/file symbol resolution."
  },
  {
    "question": "[Module 001_004] What linkage applies to global variables declared WITHOUT 'static' outside functions?",
    "options": [
      "External Linkage (accessible across source files using 'extern')",
      "Internal Linkage",
      "No Linkage",
      "Block Linkage"
    ],
    "answerIndex": 0,
    "explanation": "Non-static global variables have External Linkage."
  },
  {
    "question": "[Module 001_004] What linkage applies to global variables declared WITH 'static' outside functions?",
    "options": [
      "Internal Linkage (restricted exclusively to current source file)",
      "External Linkage",
      "No Linkage",
      "Universal Linkage"
    ],
    "answerIndex": 0,
    "explanation": "File-scope static variables have Internal Linkage."
  },
  {
    "question": "[Module 001_004] How can file A access global variable 'int count;' defined in file B?",
    "options": [
      "Declare 'extern int count;' in file A",
      "Re-define int count in A",
      "Import file B",
      "static int count;"
    ],
    "answerIndex": 0,
    "explanation": "'extern int count;' imports external symbol declaration."
  },
  {
    "question": "[Module 001_004] What does 'auto' storage class specify for local variables in C?",
    "options": [
      "Automatic storage duration (stack allocation); default for local block variables",
      "Type inference",
      "Heap allocation",
      "Global variable"
    ],
    "answerIndex": 0,
    "explanation": "auto specifies stack allocation (default for local variables)."
  },
  {
    "question": "[Module 001_004] What request does 'register' storage class specifier make?",
    "options": [
      "Requests storing variable in fast CPU register instead of RAM stack",
      "Forces RAM",
      "Allocates heap",
      "Static memory"
    ],
    "answerIndex": 0,
    "explanation": "register requests CPU register allocation for fast access."
  },
  {
    "question": "[Module 001_004] Can address-of operator '&' be applied to a 'register' variable in C?",
    "options": [
      "NO! Applying '&' to a 'register' variable causes a COMPILER ERROR!",
      "Yes",
      "Returns NULL",
      "Only C++"
    ],
    "answerIndex": 0,
    "explanation": "Applying & to register variable causes compile error."
  },
  {
    "question": "[Module 001_004] What is the effect of applying 'static' to a LOCAL variable inside a function?",
    "options": [
      "Storage duration becomes STATIC: value persists across multiple function calls",
      "Makes global",
      "Makes read-only",
      "Deletes on return"
    ],
    "answerIndex": 0,
    "explanation": "Local static variables retain their values across function invocations."
  },
  {
    "question": "[Module 001_004] When is a local static variable initialized?",
    "options": [
      "Exactly ONCE before program execution starts (at startup / compile time)",
      "On every call",
      "When main returns",
      "On stack overflow"
    ],
    "answerIndex": 0,
    "explanation": "Local static variables are initialized once at startup."
  },
  {
    "question": "[Module 001_004] Where are local automatic variables allocated in process memory?",
    "options": [
      "On Call Stack (Stack Frame)",
      "Data segment",
      "BSS segment",
      "Heap"
    ],
    "answerIndex": 0,
    "explanation": "Automatic variables are allocated on call stack frame."
  },
  {
    "question": "[Module 001_004] Where are global and static variables allocated in process memory?",
    "options": [
      "In Data Segment (initialized) or BSS Segment (uninitialized zero-fill)",
      "Call stack",
      "Heap",
      "Text segment"
    ],
    "answerIndex": 0,
    "explanation": "Global/static variables reside in Data and BSS segments."
  },
  {
    "question": "[Module 001_004] What storage class specifier was introduced in C11 for thread-specific variable isolation?",
    "options": [
      "_Thread_local (or thread_local in <threads.h>)",
      "static_thread",
      "extern_thread",
      "auto_thread"
    ],
    "answerIndex": 0,
    "explanation": "C11 introduced _Thread_local for thread-isolated variables."
  },
  {
    "question": "[Module 001_004] Can multiple storage class specifiers be combined on one declaration (static extern int x)?",
    "options": [
      "No! Combining multiple storage class specifiers causes a COMPILER ERROR",
      "Yes",
      "Only in main",
      "Only in C23"
    ],
    "answerIndex": 0,
    "explanation": "Combining storage class specifiers causes a compile-time error."
  },
  {
    "question": "[Module 001_004] What are the two essential components required in every recursive function?",
    "options": [
      "Base Case (termination condition) and Recursive Step (reducing problem size)",
      "Loop & break",
      "Pointer & Struct",
      "Init & Free"
    ],
    "answerIndex": 0,
    "explanation": "Recursion requires Base Case and Recursive Step."
  },
  {
    "question": "[Module 001_004] What happens if a recursive function lacks a base case?",
    "options": [
      "Unbounded recursion leading to Stack Overflow runtime crash",
      "Infinite output",
      "Compiles to loop",
      "Returns 0"
    ],
    "answerIndex": 0,
    "explanation": "Lacking base case causes Stack Overflow crash."
  },
  {
    "question": "[Module 001_004] What is a Stack Frame (Activation Record)?",
    "options": [
      "Region of stack memory allocated for a function call, storing parameters, local variables, and return address",
      "Heap block",
      "CPU register",
      "Disk file"
    ],
    "answerIndex": 0,
    "explanation": "Stack Frame stores function parameters, local variables, and return address."
  },
  {
    "question": "[Module 001_004] What is Tail Recursion?",
    "options": [
      "Special recursion where recursive call is VERY LAST operation executed in function with no pending work",
      "Recursion at start",
      "Recursion in loop",
      "Mutual recursion"
    ],
    "answerIndex": 0,
    "explanation": "Tail recursion has recursive call as final operation."
  },
  {
    "question": "[Module 001_004] Why is Tail Recursion significant for compilers (Tail Call Optimization - TCO)?",
    "options": [
      "Compilers optimize tail-recursive functions into iterative loops, reusing current stack frame to achieve O(1) space!",
      "Makes multithreaded",
      "Uses heap",
      "Eliminates base case"
    ],
    "answerIndex": 0,
    "explanation": "TCO reuses stack frames to prevent stack overflow."
  },
  {
    "question": "[Module 001_004] What is the mathematical output of fib(5) for naive recursive Fibonacci (0,1,1,2,3,5...)?",
    "options": [
      "5",
      "8",
      "3",
      "13"
    ],
    "answerIndex": 0,
    "explanation": "fib(5) = 5."
  },
  {
    "question": "[Module 001_004] What is time complexity of naive double-recursive Fibonacci fib(n) = fib(n-1) + fib(n-2)?",
    "options": [
      "O(2^N) Exponential time complexity",
      "O(N)",
      "O(N log N)",
      "O(1)"
    ],
    "answerIndex": 0,
    "explanation": "Naive recursive Fibonacci has exponential O(2^N) time complexity."
  },
  {
    "question": "[Module 001_004] What technique caches recursive subproblem results to avoid redundant calculations?",
    "options": [
      "Memoization (Dynamic Programming)",
      "Stack overflow",
      "Tail call",
      "Heap allocation"
    ],
    "answerIndex": 0,
    "explanation": "Memoization caches subproblem results to optimize recursion."
  },
  {
    "question": "[Module 001_004] What is Function Pointer in C?",
    "options": [
      "Variable storing memory address of executable function code in text segment",
      "Pointer returned by function",
      "Void pointer",
      "Heap pointer"
    ],
    "answerIndex": 0,
    "explanation": "Function pointer holds executable code address in text segment."
  },
  {
    "question": "[Module 001_004] What is correct syntax to declare function pointer 'fp' taking two ints and returning int?",
    "options": [
      "int (*fp)(int, int);",
      "int *fp(int, int);",
      "int fp*(int, int);",
      "(int*) fp(int, int);"
    ],
    "answerIndex": 0,
    "explanation": "int (*fp)(int, int); declares a function pointer."
  },
  {
    "question": "[Module 001_004] How do you invoke a function using function pointer 'fp' with arguments 5 and 3?",
    "options": [
      "fp(5, 3); (or (*fp)(5, 3);)",
      "*fp(5, 3);",
      "fp->(5, 3);",
      "call(fp, 5, 3);"
    ],
    "answerIndex": 0,
    "explanation": "fp(5, 3); or (*fp)(5, 3); invokes the target function pointer."
  },
  {
    "question": "[Module 001_004] What is Callback Function pattern in C?",
    "options": [
      "Passing function pointer as argument to another function so it can execute callback dynamically",
      "Recursive function",
      "Return statement",
      "Main function"
    ],
    "answerIndex": 0,
    "explanation": "Callback passes function pointer into API for dynamic execution."
  },
  {
    "question": "[Module 001_004] Which standard library function uses callback function pointer for sorting?",
    "options": [
      "qsort()",
      "bsearch()",
      "both qsort() and bsearch()",
      "malloc()"
    ],
    "answerIndex": 2,
    "explanation": "qsort() and bsearch() use custom comparison callback function pointers."
  },
  {
    "question": "[Module 001_004] What is Function Dispatch Table?",
    "options": [
      "Array of function pointers used to select and execute functions dynamically based on index",
      "Switch table",
      "Stack frame",
      "Symbol table"
    ],
    "answerIndex": 0,
    "explanation": "Array of function pointers acts as a dispatch table for state machines."
  },
  {
    "question": "[Module 001_004] What is difference between 'int *f()' and 'int (*f)()'?",
    "options": [
      "int *f() is function returning int*; int (*f)() is function pointer returning int",
      "Identical",
      "f() is private",
      "No difference"
    ],
    "answerIndex": 0,
    "explanation": "int *f() returns int pointer; int (*f)() is a function pointer."
  },
  {
    "question": "[Module 001_004] What size does a function pointer occupy on 64-bit architecture?",
    "options": [
      "8 bytes (64 bits, same as address pointers)",
      "4 bytes",
      "16 bytes",
      "Varies"
    ],
    "answerIndex": 0,
    "explanation": "Function pointers occupy 8 bytes on 64-bit platforms."
  }
];
