const topic3_questions = [
  {
    "question": "What is a 'Synthetic Bridge Method' in Java Generics, and why does the compiler generate it?",
    "shortAnswer": "When a class extends or implements a parameterized class/interface (e.g. 'class MyNode extends BaseNode<String>'), type erasure erases the parent method to 'setData(Object)', while the child defines 'setData(String)'. Without a bridge method, the child would overload instead of override the parent method. The javac compiler generates a hidden synthetic 'bridge method' ('setData(Object)') that delegates to 'setData(String)', preserving runtime polymorphism.",
    "explanation": "Inspectable at runtime via 'Method.isBridge()'.",
    "hint": "A synthetic method generated by javac to bridge erased Object signatures and preserve polymorphism.",
    "level": "Advanced",
    "codeExample": "for (Method m : clazz.getDeclaredMethods()) if (m.isBridge()) { ... }"
  }
];

export default topic3_questions;