const topic7_questions = [
  {
    "question": "What happens when you run anyMatch() on an infinite stream generated by Stream.iterate()?",
    "shortAnswer": "If an element matching the predicate exists in the sequence, anyMatch() will find it, short-circuit, and terminate successfully. If no elements match, it will continue running indefinitely.",
    "explanation": "Short-circuiting operations can safely process infinite streams if the termination condition is met.",
    "hint": "Terminates immediately once the first match is encountered.",
    "level": "Intermediate",
    "codeExample": "Stream.iterate(1, n → n + 1).anyMatch(n → n == 100); // Returns true and terminates in 100 iterations!"
  },
  {
    "question": "Why does allMatch() return true when called on an EMPTY stream?",
    "shortAnswer": "In formal logic, allMatch() on an empty set is Vacuously True because there is no element in the stream that contradicts the predicate condition.",
    "explanation": "Similarly, noneMatch() returns true on an empty stream, while anyMatch() returns false.",
    "hint": "Vacuous truth in logic: no elements exist to violate the condition.",
    "level": "Intermediate",
    "codeExample": "List.<String>of().stream().allMatch(s → s.length() > 100); // Returns true (Vacuous truth)!"
  }
];

export default topic7_questions;
