export const topic5Questions = [
  {
    question: "What is GNU Make and why is it essential for C programming?",
    answer: "GNU Make is a build automation tool that reads a 'Makefile' and executes compiler commands based on file modification timestamps (mtime), ensuring only modified source files are recompiled (incremental build)."
  },
  {
    question: "What is the basic syntax of a Makefile rule?",
    answer: "target: prerequisites\n\treceipe_command\n(Note: The command line MUST begin with a real TAB character, not spaces)."
  },
  {
    question: "What is the meaning of the automatic variable '$@' in Makefiles?",
    answer: "'$@' represents the file name of the target being generated by the current rule."
  },
  {
    question: "What is the meaning of the automatic variable '$<' in Makefiles?",
    answer: "'$<' represents the name of the first prerequisite (commonly the .c source file in a pattern rule)."
  },
  {
    question: "What is the meaning of the automatic variable '$^' in Makefiles?",
    answer: "'$^' represents the list of ALL prerequisites of the rule separated by spaces."
  },
  {
    question: "Why must recipe command lines in Makefiles start with a TAB character instead of spaces?",
    answer: "GNU Make's syntax parser strictly requires a real ASCII TAB character (\\t) to distinguish recipe commands from variable assignments and target declarations. Spaces produce a 'missing separator' syntax error."
  },
  {
    question: "What is a '.PHONY' target in Makefiles and why is it used?",
    answer: "'.PHONY: clean all' declares that 'clean' is an action target rather than a real physical file on disk. If a file named 'clean' exists in the folder, Make would otherwise think the target is up to date and skip it."
  },
  {
    question: "What are the standard Makefile variables CC and CFLAGS?",
    answer: "'CC' defines the C compiler executable (default: gcc or clang). 'CFLAGS' defines the compiler flags (e.g. -Wall -Wextra -O2 -std=c11 -Iinclude)."
  },
  {
    question: "What is a Pattern Rule (e.g. %.o: %.c) in GNU Make?",
    answer: "A generalized rule that tells Make how to compile any .c file into its corresponding .o object file: '%.o: %.c \\n\\t$(CC) $(CFLAGS) -c $< -o $@'."
  },
  {
    question: "What does the '=' vs ':=' assignment operator mean in Makefiles?",
    answer: "':=' is simply expanded (evaluated immediately when assigned). '=' is recursively expanded (evaluated dynamically every time the variable is referenced)."
  },
  {
    question: "How does Make decide whether a target needs to be rebuilt?",
    answer: "Make compares the last-modified timestamp (mtime) of the target against the mtime of all its prerequisites. If any prerequisite is newer than the target (or if the target doesn't exist), the recipe is executed."
  },
  {
    question: "What is the purpose of the 'wildcard' function in GNU Make?",
    answer: "'SRCS := $(wildcard src/*.c)' automatically searches the directory and expands into a list of all matching .c source filenames."
  },
  {
    question: "What is the purpose of the 'patsubst' function in GNU Make?",
    answer: "'OBJS := $(patsubst src/%.c, obj/%.o, $(SRCS))' translates source file paths into corresponding object file paths."
  },
  {
    question: "What does the '@' prefix before a command line in a Makefile do?",
    answer: "It suppresses echoing the command string to the console before running it (e.g. '@echo \"Building...\"')."
  },
  {
    question: "What does the '-' prefix before a command line in a Makefile do?",
    answer: "It instructs Make to ignore non-zero exit codes (errors) and continue building (e.g. '-rm -rf obj')."
  },
  {
    question: "What is CMake and how does it relate to Makefiles?",
    answer: "CMake is a cross-platform meta-build generator that reads 'CMakeLists.txt' and automatically generates native Makefiles on Linux/macOS or Visual Studio project files on Windows."
  },
  {
    question: "How do you generate automated header dependency tracking in GCC and Make?",
    answer: "Use GCC flags '-MMD -MP' which generates '.d' dependency files listing all included headers for each .c file, and include them in the Makefile with '-include $(DEPS)'."
  },
  {
    question: "What is a parallel build in Make and what flag enables it?",
    answer: "The '-j' flag (e.g. 'make -j8') compiles independent object files simultaneously across multiple CPU cores, accelerating build times."
  },
  {
    question: "What is an Order-Only Prerequisite in GNU Make (| dir)?",
    answer: "Prerequisites placed after a pipe '|' (e.g. '$(TARGET): $(OBJS) | bin') ensure the directory is created before building, but changes to the directory timestamp do not trigger a rebuild of the target."
  },
  {
    question: "How do you specify a default target in a Makefile?",
    answer: "The first non-pattern target encountered in the Makefile is automatically treated as the default target when 'make' is called without arguments (by convention named 'all')."
  },
  {
    question: "What does 'make clean' conventionally do?",
    answer: "It deletes all generated object files (.o), binaries, and build directories to reset the repository to a clean state."
  },
  {
    question: "Can environment variables be passed directly to Make from the command line?",
    answer: "Yes, e.g. 'make CFLAGS=\"-g -O0\"' overrides the internal CFLAGS variable."
  },
  {
    question: "What does the '$*' automatic variable represent?",
    answer: "The stem (the substring matching the '%' wildcard in a pattern rule)."
  },
  {
    question: "Why should compiler warning flags (-Wall -Wextra -Werror) always be in CFLAGS?",
    answer: "To ensure the compiler catches potential bugs, uninitialized variables, and type mismatches early during the automated build stage."
  },
  {
    question: "What file name does GNU Make search for by default?",
    answer: "GNUmakefile, makefile, and Makefile (in that priority order)."
  }
];
