// File: src/components/topics/topic0_files/topic0_questions.js
const questions = [
    {
        question: "What is the primary role of the Data Link Layer in the OSI model?",
        shortAnswer: "To provide node-to-node reliable data transfer across a physical link.",
        explanation: "The Data Link Layer takes raw bits from the Physical Layer and organizes them into frames. It ensures these frames are delivered without errors to the next directly connected node, handling flow control, error detection, and media access.",
        hint: "Think about the layer that talks directly to the network card and the switch.",
        level: "basic",
        codeExample: "// In Wireshark, packets at this layer are shown as Ethernet II frames."
    },
    {
        question: "What is the difference between a node-to-node and an end-to-end connection?",
        shortAnswer: "Node-to-node is between two directly connected devices (e.g., PC to router). End-to-end is between the source and final destination (e.g., PC to a web server).",
        explanation: "The Data Link Layer is responsible for node-to-node delivery. The Network Layer (IP) and Transport Layer (TCP) are responsible for end-to-end delivery, routing packets across multiple networks.",
        hint: "How many 'hops' does a packet take? Each hop is a node-to-node transfer, handled by the Data Link Layer.",
        level: "moderate",
    },
    {
        question: "What is a MAC address, and at which layer is it used?",
        shortAnswer: "A MAC (Media Access Control) address is a unique hardware identifier for a network interface, used at the Data Link Layer.",
        explanation: "MAC addresses are 48-bit (or 64-bit) addresses typically burned into a network interface card (NIC). They are used in the frame header to specify the source and destination for node-to-node delivery within the same network segment.",
        hint: "The 'arp -a' command shows the mapping between IP (Layer 3) and MAC (Layer 2) addresses.",
        level: "basic",
    },
    {
        question: "Name the five core functions of the Data Link Layer.",
        shortAnswer: "Framing, Physical Addressing, Flow Control, Error Control, and Access Control.",
        explanation: "Framing organizes bits into frames. Physical addressing adds source and destination MAC addresses. Flow control manages data rate to prevent overwhelming a receiver. Error control detects and corrects transmission errors. Access control coordinates who gets to transmit on a shared medium.",
        hint: "Remember the mnemonic: 'Fit People Find Every Answer' (Framing, Physical, Flow, Error, Access).",
        level: "moderate",
    },
    {
        question: "What is the main difference between a hub and a switch, in the context of the Data Link Layer?",
        shortAnswer: "A hub operates at the Physical Layer (repeats bits), while a switch operates at the Data Link Layer (forwards frames based on MAC addresses).",
        explanation: "A hub is a 'dumb' device that repeats an electrical signal out all ports, causing collisions. A switch is 'intelligent' - it learns which MAC addresses are on which port and forwards frames only to the intended destination port, reducing collisions and increasing efficiency.",
        hint: "Think about 'collision domains'. A hub has one; a switch creates a separate one for each port.",
        level: "expert",
    },
    {
        question: "What is a 'frame' in the context of the Data Link Layer?",
        shortAnswer: "A frame is the Protocol Data Unit (PDU) of the Data Link Layer, consisting of header, payload (data from the Network Layer), and trailer.",
        explanation: "The header contains MAC addresses and other control information. The payload is the encapsulated network-layer packet. The trailer usually contains a Frame Check Sequence (FCS) for error detection.",
        hint: "It's like an envelope: header (addresses, routing info), payload (the letter), trailer (a seal or checksum).",
        level: "basic",
    },
    {
        question: "What does 'error control' mean at the Data Link Layer, and what are two primary methods to achieve it?",
        shortAnswer: "Error control is the ability to detect and, optionally, correct transmission errors. Common methods are error detection (CRC, Checksum) with retransmission (ARQ) and Forward Error Correction (FEC).",
        explanation: "While higher layers also have error control, the Data Link Layer provides rapid, per-hop error recovery. If a frame has a bad FCS, the receiver typically discards it and the sender (using an ARQ like Stop-and-Wait) will retransmit.",
        hint: "Consider the difference between 'detecting' a typo and 'correcting' it without asking for help.",
        level: "moderate",
    },
    {
        question: "What does the ARP (Address Resolution Protocol) do, and which two layers does it connect?",
        shortAnswer: "ARP maps an IP address (Layer 3) to a MAC address (Layer 2) within a local network.",
        explanation: "When a device knows the destination IP but not its MAC address, it broadcasts an ARP request. The device with that IP replies with its MAC address. This is crucial for encapsulating a packet into a frame.",
        hint: "Without ARP, your computer couldn't find the MAC address of your router, and the Data Link Layer wouldn't know where to send the frame.",
        level: "moderate",
    },
    {
        question: "What is a 'collision domain', and how does a switch affect it?",
        shortAnswer: "A collision domain is a network segment where data packets can collide with one another. A switch isolates each port into its own collision domain.",
        explanation: "In older Ethernet with hubs, all devices shared one collision domain (CSMA/CD was needed). Each port on a modern switch is a separate collision domain, allowing full-duplex communication and eliminating collisions.",
        hint: "Imagine a room (hub) where everyone shares one microphone vs. many soundproof booths (switch) where each person has their own.",
        level: "moderate",
    },
    {
        question: "What is the purpose of the Frame Check Sequence (FCS) in an Ethernet frame trailer?",
        shortAnswer: "The FCS is used for error detection. The sender computes a CRC value and appends it. The receiver recomputes it; if the values don't match, the frame is considered corrupt and discarded.",
        explanation: "The FCS is a 32-bit CRC (Cyclic Redundancy Check) that provides a very strong check for bit errors introduced during transmission. It's a cornerstone of Data Link Layer reliability.",
        hint: "It's like a tamper-evident seal. If the seal is broken (bad FCS), you don't trust the contents.",
        level: "expert",
    },
    {
        question: "Why is flow control needed at the Data Link Layer even if higher layers like TCP also provide it?",
        shortAnswer: "Data Link flow control provides fast, hardware-assisted, per-hop backpressure to prevent buffer overruns on directly connected devices, which is much faster than end-to-end TCP flow control.",
        explanation: "TCP flow control is end-to-end and takes many RTTs to react. Data Link flow control (e.g., Ethernet PAUSE frames or older XON/XOFF) operates in microseconds, preventing a fast neighbor from overwhelming a slow one's local buffers.",
        hint: "Think of a direct conversation: you can ask someone to 'hold on' instantly (Layer 2), vs. sending a letter to ask them to slow down (Layer 4).",
        level: "expert",
    },
    {
        question: "What is the 'Preamble' in an Ethernet frame?",
        shortAnswer: "The preamble is a 7-byte pattern of alternating 1s and 0s used to synchronize the receiver's clock before the actual frame is sent.",
        explanation: "It's part of the Physical Layer convergence procedure but is intimately tied to Ethernet framing. It allows the receiving NIC to lock onto the bit stream before the Start Frame Delimiter (SFD) indicates the frame header is starting.",
        hint: "It's like a drummer giving a '1, 2, 3, 4!' count-in before the band starts playing the song.",
        level: "expert",
    },
    {
        question: "What is a 'VLAN' (Virtual LAN) and how does it relate to the Data Link Layer?",
        shortAnswer: "A VLAN is a logical segmentation of a network at the Data Link Layer, creating isolated broadcast domains on the same physical switch infrastructure.",
        explanation: "VLANs use a tag (IEEE 802.1Q) inserted into the Ethernet frame header. This tag tells the switch which VLAN the frame belongs to, allowing traffic from multiple networks to coexist on the same physical wires."
    },
    {
        question: "What is the difference between a 'unicast', 'broadcast', and 'multicast' frame?",
        shortAnswer: "Unicast is to one specific MAC address, broadcast is to all devices on the network (FF:FF:FF:FF:FF:FF), and multicast is to a group of interested devices.",
        explanation: "These are the three addressing modes at the Data Link Layer. Switches learn unicast addresses, flood broadcasts to all ports in a VLAN, and can use IGMP snooping to intelligently forward multicast frames.",
        hint: "Unicast = a private letter; Broadcast = a public announcement; Multicast = a subscription-only newsletter.",
        level: "moderate",
    },
    {
        question: "What is a 'jumbo frame' and what is its advantage and disadvantage?",
        shortAnswer: "A jumbo frame is an Ethernet frame with a payload larger than the standard 1500 bytes (typically up to 9000 bytes). Advantage: less overhead (fewer frames for large data). Disadvantage: requires all devices on the path to support it.",
        explanation: "Jumbo frames reduce CPU interrupts and increase throughput for large bulk data transfers. However, they increase latency for small packets and can cause fragmentation if a non-supporting device is encountered.",
        hint: "Think about moving furniture: one big truck (jumbo frame) vs. many small vans (standard frames).",
        level: "expert",
    },
    {
        question: "What does 'PAUSE frame' do in Ethernet flow control?",
        shortAnswer: "A PAUSE frame is a special Ethernet frame that tells the sender to stop transmitting for a specified period, enabling hardware-level flow control.",
        explanation: "When a switch's buffer gets full, it can send a PAUSE frame to the connected device. This is simple but can cause head-of-line blocking issues, so more advanced flow control (Priority Flow Control) is used in data centers.",
        hint: "It's like raising your hand to say 'stop talking for a moment, I need to catch up on my notes'.",
        level: "expert",
    },
    {
        question: "What is the 'Type/Length' field in an Ethernet II frame?",
        shortAnswer: "This field either indicates the protocol type of the encapsulated payload (e.g., 0x0800 for IPv4) or the length of the payload, depending on the value (<=1500 means length, >1500 means type).",
        explanation: "In modern Ethernet, it's almost always used as a Type field. The demultiplexing allows the Data Link Layer to pass the payload to the correct Network Layer protocol (e.g., IPv4, IPv6, ARP).",
        hint: "It's a 'door number' for the next layer up. The frame says 'this package is for IPv4' or 'this one is for ARP'.",
        level: "expert",
    },
    {
        question: "What is the role of the LLC (Logical Link Control) sublayer?",
        shortAnswer: "The LLC sublayer (IEEE 802.2) provides multiplexing and flow control for the upper layers, independent of the physical medium.",
        explanation: "The MAC sublayer handles media access (CSMA/CD, etc.). The LLC sublayer sits above it and talks to the Network Layer, allowing multiple Network Layer protocols (e.g., IP, IPX) to share the same data link.",
        hint: "Think of it as a universal adapter: it makes the MAC sublayer look the same to the Network Layer, regardless of whether you're using Ethernet, Wi-Fi, or something else.",
        level: "expert",
    },
    {
        question: "Which layer does a network bridge operate at, and what is its primary function?",
        shortAnswer: "A bridge operates at the Data Link Layer. Its primary function is to segment a network by learning which MAC addresses are on each side and forwarding frames selectively.",
        explanation: "Bridges reduce collision domains and can connect different physical media (e.g., Ethernet to fiber). They were the predecessor to switches, which are essentially multi-port bridges.",
        hint: "It's a 'smart repeater' that only passes traffic across the bridge if it needs to go to the other side.",
        level: "moderate",
    },
    {
        question: "Explain the concept of 'promiscuous mode' on a network interface.",
        shortAnswer: "Promiscuous mode forces a NIC to pass all received frames up the stack, not just those addressed to its own MAC address or broadcasts.",
        explanation: "This is used by packet analyzers like Wireshark to 'sniff' traffic on a network. It's a powerful diagnostic tool but a security risk if used maliciously on a shared network.",
        hint: "Normal mode is like opening only your own mailbox. Promiscuous mode is like listening to everyone's conversations in a room.",
        level: "expert",
    },
    {
        question: "What is 'Spanning Tree Protocol' (STP) and why is it needed at the Data Link Layer?",
        shortAnswer: "STP prevents Layer 2 loops in a redundant switched network by creating a logical loop-free topology.",
        explanation: "Without STP, redundant links would cause broadcast storms and MAC address table instability. STP blocks certain ports and recalculates the tree if a link fails, providing redundancy without loops.",
        hint: "Imagine bridges connecting islands. Redundancy is good, but a loop would cause a traffic jam that never ends. STP is the traffic controller that breaks the loop logically.",
        level: "expert",
    },
    {
        question: "What does the 'loopback' address at the Data Link Layer represent?",
        shortAnswer: "There's no standard Data Link 'loopback address', but many NICs support a loopback mode where frames sent out are immediately received back counter.",
        explanation: "A software loopback (like 127.0.0.1 at IP layer) tests the network stack without hardware. A hardware loopback at the Data Link Layer helps test the NIC itself.",
        hint: "It's like writing yourself a letter and putting it back in your own mailbox to test the postal service.",
        level: "moderate",
    },
    {
        question: "What is the 'Maximum Transmission Unit' (MTU) in the context of the Data Link Layer?",
        shortAnswer: "MTU is the maximum size of the payload (network layer packet) that a link-layer frame can carry.",
        explanation: "For Ethernet, the MTU is typically 1500 bytes. If an IP packet is larger than the MTU, it must be fragmented (at the Network Layer) before being passed down to the Data Link Layer.",
        hint: "It's the maximum cargo weight your truck (frame) can carry. The package (IP packet) must be split into smaller parcels if it's too heavy.",
        level: "moderate",
    },
    {
        question: "How does the Data Link Layer help in 'Quality of Service' (QoS) on a network?",
        shortAnswer: "Using fields like 802.1Q/p priority (the PCP bits in the VLAN tag) to prioritize certain frames over others.",
        explanation: "A switch can recognize these priority tags and treat time-sensitive frames (like VoIP) with higher priority than bulk file transfers. This is a simple but effective Layer 2 QoS mechanism.",
        hint: "Think of an airport: First-class passengers (high priority frames) get to board before economy (low priority).",
        level: "expert",
    },
    {
        question: "What is 'crosstalk' from a Data Link Layer perspective?",
        shortAnswer: "Crosstalk is electromagnetic interference from one wire to another, causing bit errors. The Data Link Layer's error detection (FCS) and retransmission handle its effects.",
        explanation: "Crosstalk is a Physical Layer problem, but its manifestation (corrupted bits) is detected and mitigated by the Data Link Layer's error control mechanisms.",
        hint: "It's like hearing a conversation from the next cubicle while you're on the phone. You might hear the wrong words (errors), so you ask the person to repeat (retransmit).",
        level: "expert",
    },
    {
        question: "What is a 'NIC' and what role does it play in the Data Link Layer?",
        shortAnswer: "A Network Interface Card (NIC) is the hardware that implements the Data Link (and Physical) Layer functions, like MAC addressing, framing, and processing FCS.",
        explanation: "The NIC's driver handles the Data Link Layer protocol specifics. The hardware itself often offloads checksum calculation and other tasks from the CPU.",
        hint: "It's the physical 'post office' attached to your computer, responsible for packing and unpacking envelopes (frames).",
        level: "basic",
    },
    {
        question: "Compare CSMA/CD (used in wired Ethernet) with CSMA/CA (used in Wi-Fi).",
        shortAnswer: "CSMA/CD (Collision Detection) detects collisions after they happen. CSMA/CA (Collision Avoidance) tries to avoid collisions by waiting for a clear channel and using RTS/CTS.",
        explanation: "On a wire, you can detect collisions easily (CSMA/CD). Over the air, you can't easily listen while transmitting, so Wi-Fi avoids collisions (CSMA/CA) at the cost of more overhead.",
        hint: "CD is like a crowded room where you shout and if someone else shouts, you stop. CA is like raising your hand and waiting to be called upon.",
        level: "expert",
    },
    {
        question: "What is a 'host route' in the context of a Data Link Layer switching table?",
        shortAnswer: "A host route in a switch's MAC address table is an entry that maps a single unicast MAC address to a specific port.",
        explanation: "Switches learn host routes by examining the source MAC address of incoming frames. The table is dynamic (ages out) and has a very high capacity in enterprise switches.",
        hint: "It's like a concierge with a perfect memory for which room (port) each guest (MAC address) lives in.",
        level: "moderate",
    },
    {
        question: "Why is the Data Link layer often called the 'error detection' layer?",
        shortAnswer: "Because it provides extremely robust error detection (e.g., 32-bit CRC) for each and every frame, catching almost all physical-layer bit errors.",
        explanation: "While higher layers also have checksums (TCP, UDP), the Data Link layer's FCS catches errors that occur on the wire. This prevents corrupt data from even reaching the Network layer on many hops.",
        hint: "Think of it as a rigorous quality control checkpoint at every station, not just the final destination.",
        level: "moderate",
    },
    {
        question: "What is the 'Start Frame Delimiter' (SFD) in an Ethernet frame?",
        shortAnswer: "The SFD is a single byte (10101011) that immediately follows the preamble and signals the actual beginning of the frame header.",
        explanation: "The preamble syncs clocks; the SFD tells the receiver 'the next byte is the first byte of the frame (destination MAC)'. It's a critical part of the frame synchronization process.",
        hint: "It's the 'ready, set, GO!' after the count-in. The 'GO' is the SFD.",
        level: "expert",
    }
];

export default questions;