// topic10_questions.js
// 30 FAQs on "Postfix Expression" – basic to expert.

const questions = [
  {
    question: "What is a postfix expression?",
    shortAnswer: "An expression where the operator appears after its operands.",
    explanation: "Also known as Reverse Polish Notation (RPN). Example: `A B +`.",
    hint: "Operator last.",
    level: "basic",
    codeExample: "2 3 +",
  },
  {
    question: "What is another name for postfix notation?",
    shortAnswer: "Reverse Polish Notation (RPN).",
    explanation: "It's called 'Reverse' because it's the reverse of Polish (prefix) notation.",
    hint: "RPN.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "Why is postfix notation useful?",
    shortAnswer: "It eliminates the need for parentheses and precedence rules.",
    explanation: "Evaluation is straightforward with a stack.",
    hint: "No ambiguity.",
    level: "basic",
    codeExample: "2 3 +",
  },
  {
    question: "How do you evaluate a postfix expression?",
    shortAnswer: "Scan from left to right, using a stack.",
    explanation: "Push operands, pop when an operator is encountered, and push the result.",
    hint: "Left-to-right with stack.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What is the postfix form of `A + B`?",
    shortAnswer: "A B +",
    explanation: "Operator '+' comes after operands A and B.",
    hint: "Operands first.",
    level: "basic",
    codeExample: "A B +",
  },
  {
    question: "What is the postfix form of `(A + B) * C`?",
    shortAnswer: "A B + C *",
    explanation: "The addition is done first, then multiplication.",
    hint: "Inner operation first.",
    level: "intermediate",
    codeExample: "A B + C *",
  },
  {
    question: "What is the postfix form of `A * B + C`?",
    shortAnswer: "A B * C +",
    explanation: "Multiplication before addition due to precedence.",
    hint: "Higher precedence first.",
    level: "intermediate",
    codeExample: "A B * C +",
  },
  {
    question: "What is the postfix form of `A + B * C`?",
    shortAnswer: "A B C * +",
    explanation: "Multiplication first, then addition.",
    hint: "Precedence.",
    level: "intermediate",
    codeExample: "A B C * +",
  },
  {
    question: "Does postfix notation require parentheses?",
    shortAnswer: "No, parentheses are never needed.",
    explanation: "The operator position eliminates ambiguity.",
    hint: "Not needed.",
    level: "basic",
    codeExample: "2 3 +",
  },
  {
    question: "Which programming languages use postfix notation?",
    shortAnswer: "Forth and PostScript.",
    explanation: "These languages are stack-based and use postfix natively.",
    hint: "Think of stack languages.",
    level: "intermediate",
    codeExample: "2 3 + .",
  },
  {
    question: "What is the postfix form of `A + B * C + D`?",
    shortAnswer: "A B C * + D +",
    explanation: "Multiplication first, then additions from left to right.",
    hint: "Left-to-right for same precedence.",
    level: "advanced",
    codeExample: "A B C * + D +",
  },
  {
    question: "What is the difference between prefix and postfix?",
    shortAnswer: "Prefix has operator before operands; postfix has operator after operands.",
    explanation: "They are mirror images.",
    hint: "Before vs after.",
    level: "basic",
    codeExample: "Prefix: + A B; Postfix: A B +",
  },
  {
    question: "How do you convert infix to postfix?",
    shortAnswer: "Use the Shunting‑yard algorithm with a stack.",
    explanation: "The algorithm handles precedence and parentheses.",
    hint: "Classic algorithm.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "What data structure is used to evaluate postfix?",
    shortAnswer: "A stack.",
    explanation: "Operands are pushed, operators pop and push results.",
    hint: "LIFO.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What is the time complexity of evaluating postfix?",
    shortAnswer: "O(n) where n is the number of tokens.",
    explanation: "Each token is processed once.",
    hint: "Linear.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What are the advantages of postfix over infix?",
    shortAnswer: "No precedence, no parentheses, easier for machines.",
    explanation: "Evaluation is straightforward with a stack.",
    hint: "Machine-friendly.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What are the disadvantages of postfix for humans?",
    shortAnswer: "It's less intuitive and harder to read for complex expressions.",
    explanation: "Humans are trained to read infix.",
    hint: "Not human-friendly.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "How do you handle unary operators in postfix?",
    shortAnswer: "They are written after the operand, but this can be ambiguous.",
    explanation: "Often, unary operators are handled specially in conversion.",
    hint: "Requires care.",
    level: "advanced",
    codeExample: "5 - (unary) would be ambiguous",
  },
  {
    question: "What is the postfix representation of `-5`?",
    shortAnswer: "5 - (but this is ambiguous; usually handled differently)",
    explanation: "In practice, unary minus is often treated as a binary operator with a zero.",
    hint: "Special handling.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "What is the postfix form of `a > b && c < d`?",
    shortAnswer: "a b > c d < &&",
    explanation: "Each relational becomes postfix, then logical AND.",
    hint: "Convert each part.",
    level: "advanced",
    codeExample: "a b > c d < &&",
  },
  {
    question: "Is postfix notation used in compilers?",
    shortAnswer: "Yes, often as an intermediate representation.",
    explanation: "It simplifies code generation.",
    hint: "Used internally.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "What is the postfix form of `(A+B)*(C-D)`?",
    shortAnswer: "A B + C D - *",
    explanation: "Each parenthesized sub-expression is converted to postfix.",
    hint: "Inner first.",
    level: "intermediate",
    codeExample: "A B + C D - *",
  },
  {
    question: "Is postfix notation commonly used in mathematical textbooks?",
    shortAnswer: "No, textbooks use infix.",
    explanation: "Postfix is mainly used in computer science contexts.",
    hint: "Mostly academic.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What is the role of whitespace in postfix?",
    shortAnswer: "Whitespace is used to separate tokens.",
    explanation: "Without whitespace, parsing becomes ambiguous.",
    hint: "Use spaces.",
    level: "basic",
    codeExample: "2 3 +",
  },
  {
    question: "Can postfix expressions be nested?",
    shortAnswer: "Yes, operands can be sub-expressions.",
    explanation: "Example: `2 3 + 4 *`.",
    hint: "Nesting allowed.",
    level: "intermediate",
    codeExample: "2 3 + 4 *",
  },
  {
    question: "What is the postfix form of `2 + 3 * 4`?",
    shortAnswer: "2 3 4 * +",
    explanation: "Multiplication first.",
    hint: "Precedence.",
    level: "intermediate",
    codeExample: "2 3 4 * +",
  },
  {
    question: "What is the postfix form of `(2 + 3) * 4`?",
    shortAnswer: "2 3 + 4 *",
    explanation: "Parentheses force addition first.",
    hint: "Parentheses override.",
    level: "intermediate",
    codeExample: "2 3 + 4 *",
  },
  {
    question: "Why do HP calculators use postfix?",
    shortAnswer: "It reduces keystrokes and eliminates parentheses.",
    explanation: "Engineers and scientists find RPN efficient.",
    hint: "Efficiency.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What is the maximum stack depth needed for postfix evaluation?",
    shortAnswer: "It depends on the expression; in worst case, it's the number of operands.",
    explanation: "The stack size equals the depth of nested operations.",
    hint: "Depends on expression.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "Can you evaluate postfix with a single stack?",
    shortAnswer: "Yes, one stack for operands is sufficient.",
    explanation: "Operators are applied immediately, so no need for an operator stack.",
    hint: "One stack.",
    level: "basic",
    codeExample: "Not applicable",
  },
];

export default questions;