// topic14_files/topic14_questions.js

const questions = [
  {
    question: "What is the primary purpose of the `WITH ROLLUP` modifier in MySQL?",
    shortAnswer: "`WITH ROLLUP` adds super-aggregate summary rows (subtotals and a grand total) to the standard `GROUP BY` result set in a single query pass.",
    explanation: "WITH ROLLUP enables hierarchical multi-level reporting without writing separate queries linked with UNION ALL.",
    hint: "It computes subtotals and a grand total automatically alongside standard group rows.",
    level: "basic"
  },
  {
    question: "If you specify `GROUP BY country, state, city WITH ROLLUP`, how many levels of aggregation are generated?",
    shortAnswer: "4 levels: (country, state, city), (country, state, NULL), (country, NULL, NULL), and (NULL, NULL, NULL) grand total.",
    explanation: "For N grouping columns, WITH ROLLUP generates N + 1 levels of aggregation from right to left.",
    hint: "Formula is N + 1 levels, where N = 3 columns, so 4 levels total.",
    level: "basic"
  },
  {
    question: "Why does MySQL place `NULL` in the grouping columns of subtotal and grand total rows generated by `WITH ROLLUP`?",
    shortAnswer: "`NULL` indicates that the specific column has been collapsed/aggregated across all its possible values to form the super-aggregate total.",
    explanation: "The NULL serves as a placeholder denoting 'All Values' for that dimensional level.",
    hint: "NULL indicates that all distinct values for that column were combined into a subtotal.",
    level: "basic"
  },
  {
    question: "What problem occurs if a grouping column naturally contains legitimate `NULL` values in the source table when using `WITH ROLLUP`?",
    shortAnswer: "It becomes ambiguous whether a `NULL` in the output represents a genuine missing data value or a ROLLUP-generated subtotal row.",
    explanation: "Source data NULL and ROLLUP super-aggregate NULL appear identical unless the GROUPING() function is used to disambiguate.",
    hint: "Natural data NULLs look identical to ROLLUP subtotal NULLs.",
    level: "moderate"
  },
  {
    question: "How does the MySQL 8.0+ `GROUPING()` function resolve ambiguity between data NULLs and ROLLUP NULLs?",
    shortAnswer: "`GROUPING(col)` returns `1` if the NULL represents a super-aggregate total row generated by ROLLUP, and `0` for regular data rows (including natural NULLs).",
    explanation: "GROUPING() provides a definitive binary flag to differentiate ROLLUP super-aggregates from underlying row data.",
    hint: "GROUPING() returns 1 for ROLLUP-created summary rows and 0 for regular data.",
    level: "moderate"
  },
  {
    question: "How can you replace ROLLUP NULLs with descriptive labels like '>> GRAND TOTAL <<' using `GROUPING()`?",
    shortAnswer: "`IF(GROUPING(centre_city) = 1, '>> GRAND TOTAL <<', centre_city) AS centre_city`",
    explanation: "Using IF() or CASE with GROUPING() safely formats summary row headers without accidentally overriding real data values.",
    hint: "Use IF(GROUPING(column) = 1, 'GRAND TOTAL', column).",
    level: "moderate"
  },
  {
    question: "Can `COALESCE()` be used to label ROLLUP subtotal rows?",
    shortAnswer: "YES, `COALESCE(col, 'Subtotal')` works provided that the underlying column is defined as `NOT NULL` in the database schema.",
    explanation: "COALESCE replaces any NULL value with a fallback string, but if natural NULLs exist in the table, it will mistakenly label them as subtotals.",
    hint: "COALESCE works safely only when the column has a NOT NULL constraint.",
    level: "basic"
  },
  {
    question: "Why does the column order in `GROUP BY colA, colB WITH ROLLUP` matter significantly?",
    shortAnswer: "Because ROLLUP aggregates strictly in a hierarchical right-to-left order; `GROUP BY colA, colB` produces subtotals for each `colA`, whereas `GROUP BY colB, colA` produces subtotals for each `colB`.",
    explanation: "Hierarchy order determines which dimensions are collapsed first; the leftmost column is the broadest grouping level.",
    hint: "The leftmost column defines the primary subtotal container.",
    level: "moderate"
  },
  {
    question: "Why does `SELECT dept, role, SUM(salary) FROM employees GROUP BY dept, role WITH ROLLUP ORDER BY dept DESC;` fail or behave restrictively in MySQL?",
    shortAnswer: "In MySQL, `WITH ROLLUP` and `ORDER BY` are mutually exclusive in the same query block because sorting would disrupt the hierarchical placement of subtotal rows.",
    explanation: "Standard sorting mixes subtotal rows in between regular rows; MySQL disallows direct ORDER BY with ROLLUP in the same query block.",
    hint: "ORDER BY and WITH ROLLUP cannot be combined in the same query block.",
    level: "moderate"
  },
  {
    question: "How do you sort a `WITH ROLLUP` result set while keeping subtotal and grand total rows at the bottom?",
    shortAnswer: "Wrap the ROLLUP query inside a Common Table Expression (CTE) or derived table subquery, and apply `ORDER BY` on the outer query using `GROUPING()` flags.",
    explanation: "Outer query sorting allows controlling where subtotals and grand totals appear relative to detail rows.",
    hint: "Use a subquery/CTE and sort externally in the outer SELECT.",
    level: "expert"
  },
  {
    question: "Does `WITH ROLLUP` increase the time complexity or table scan overhead compared to standard `GROUP BY`?",
    shortAnswer: "NO. MySQL calculates super-aggregates during the single aggregation pass over the grouped hash table or index, making it dramatically faster than running multiple queries.",
    explanation: "ROLLUP computes subtotals in a single pipeline pass without re-reading the physical disk records.",
    hint: "It computes everything in a single relational pass.",
    level: "moderate"
  },
  {
    question: "What is the difference between `WITH ROLLUP` and `GROUPING SETS` in relational databases?",
    shortAnswer: "`WITH ROLLUP` produces hierarchical subtotals in fixed right-to-left order, while `GROUPING SETS` allows specifying arbitrary custom combinations of grouping dimensions.",
    explanation: "ROLLUP is a specific linear hierarchy subset of the generalized GROUPING SETS construct.",
    hint: "ROLLUP is strictly hierarchical; GROUPING SETS allows arbitrary grouping sets.",
    level: "expert"
  },
  {
    question: "How does `HAVING` interact with `WITH ROLLUP`?",
    shortAnswer: "The `HAVING` clause filters both fine-grained groups AND super-aggregate subtotal rows based on the aggregate condition.",
    explanation: "If a HAVING condition is not met by a subtotal row, that subtotal row is discarded just like any normal group row.",
    hint: "HAVING filters both detail groups and super-aggregate subtotal rows.",
    level: "expert"
  },
  {
    question: "How do you write a query to compute student enrollment count and tuition fee totals by Center, Course Stream, and Grand Total?",
    shortAnswer: "`SELECT centre_city, course_stream, COUNT(*), SUM(fee_inr) FROM enrollments GROUP BY centre_city, course_stream WITH ROLLUP;`",
    explanation: "Standard two-column hierarchy with ROLLUP generating city-stream details, city subtotals, and institutional grand total.",
    hint: "GROUP BY centre_city, course_stream WITH ROLLUP.",
    level: "basic"
  },
  {
    question: "What is returned in the `course_stream` column of a Center-level subtotal row in `GROUP BY centre_city, course_stream WITH ROLLUP`?",
    shortAnswer: "`NULL` (representing all course streams rolled up for that center).",
    explanation: "The rightmost column in the hierarchy is collapsed first to NULL.",
    hint: "It returns NULL because all course streams are aggregated together.",
    level: "basic"
  },
  {
    question: "Can `GROUP_CONCAT()` be used in a `WITH ROLLUP` query?",
    shortAnswer: "YES. In subtotal and grand total rows, `GROUP_CONCAT()` concatenates all string values belonging to the entire subtotal or grand total scope.",
    explanation: "Aggregate functions operate normally across the expanded scope of each super-aggregate level.",
    hint: "GROUP_CONCAT includes all values across the entire rolled-up partition.",
    level: "moderate"
  },
  {
    question: "How can you detect specifically the Grand Total row in a `WITH ROLLUP` query on `(col1, col2)`?",
    shortAnswer: "When `GROUPING(col1) = 1` (since col1 is the leftmost dimension, its grouping flag is only 1 for the grand total).",
    explanation: "The leftmost grouping column is only collapsed at the final grand total stage.",
    hint: "Check if GROUPING(leftmost_column) = 1.",
    level: "moderate"
  },
  {
    question: "What happens if you use `COUNT(column_name)` vs `COUNT(*)` in a `WITH ROLLUP` query?",
    shortAnswer: "`COUNT(*)` counts all rows including those with NULLs, while `COUNT(column_name)` counts only rows where `column_name` is non-NULL across all hierarchy levels.",
    explanation: "Standard aggregate NULL semantics apply consistently across all super-aggregate subtotal and grand total rows.",
    hint: "COUNT(*) counts total rows; COUNT(col) skips null values in both detail and subtotal rows.",
    level: "basic"
  },
  {
    question: "Can you combine `WITH ROLLUP` with expressions like `YEAR(admit_date)`?",
    shortAnswer: "YES, you can write `GROUP BY centre_city, YEAR(admit_date) WITH ROLLUP`.",
    explanation: "Expressions and scalar function transformations are fully supported in multi-column ROLLUP hierarchies.",
    hint: "Yes; expressions work just like regular columns in WITH ROLLUP.",
    level: "basic"
  },
  {
    question: "How does `LIMIT` behave when applied to a `WITH ROLLUP` query?",
    shortAnswer: "`LIMIT` truncates the output rows after all group rows, subtotals, and grand totals are formed, which might inadvertently cut off the grand total row.",
    explanation: "LIMIT applies at the final projection stage (Stage 7), meaning trailing subtotal/grand total rows may be omitted.",
    hint: "LIMIT applies last and can cut off the grand total row at the bottom.",
    level: "moderate"
  },
  {
    question: "What is the output of `SELECT AVG(marks) FROM students GROUP BY city WITH ROLLUP;` on the grand total row?",
    shortAnswer: "The grand total row contains the overall institutional average score across all students, not an average of city averages.",
    explanation: "ROLLUP re-aggregates over all base rows (total marks / total students), avoiding mathematical averaging errors.",
    hint: "It computes the true global average over all raw student records.",
    level: "moderate"
  },
  {
    question: "Why is computing true grand averages with `WITH ROLLUP` safer than averaging pre-calculated group averages in Excel/BI tools?",
    shortAnswer: "Averaging pre-calculated averages introduces mathematical weighting distortion when groups have different student counts; ROLLUP computes true global sums divided by global counts.",
    explanation: "True weighted average calculation is preserved by the database engine at every ROLLUP tier.",
    hint: "Prevents Simpson's Paradox and unweighted average calculation errors.",
    level: "expert"
  },
  {
    question: "How can you use `CASE` and `GROUPING()` to create an indented hierarchical tree layout in SQL?",
    shortAnswer: "Use `CASE WHEN GROUPING(col1)=1 THEN 'GRAND TOTAL' WHEN GROUPING(col2)=1 THEN CONCAT('  Total ', col1) ELSE CONCAT('    ', col2) END`.",
    explanation: "String concatenation with spaces based on GROUPING flags formats relational rows into visual visual trees.",
    hint: "Combine CASE with indentation spaces based on GROUPING() depth.",
    level: "moderate"
  },
  {
    question: "Can `WITH ROLLUP` be used with a single column (e.g. `GROUP BY centre_city WITH ROLLUP`)?",
    shortAnswer: "YES. It will output each city's aggregated row followed by a single Grand Total row.",
    explanation: "With N=1, ROLLUP produces 1+1 = 2 levels (individual cities + grand total).",
    hint: "Yes; produces individual city groups plus one final grand total row.",
    level: "basic"
  },
  {
    question: "What index structure best accelerates a `GROUP BY region, district, branch WITH ROLLUP` query?",
    shortAnswer: "A composite B-Tree index on `(region, district, branch)` matching the exact left-to-right hierarchy.",
    explanation: "Allows MySQL to traverse the index in hierarchical order, emitting subtotals on prefix boundaries without filesort.",
    hint: "Composite index matching the hierarchy order (region, district, branch).",
    level: "expert"
  },
  {
    question: "What error occurs if you try to use `WITH ROLLUP` inside a window function `OVER ()` clause?",
    shortAnswer: "Syntax Error. `WITH ROLLUP` is an extension of `GROUP BY` only and cannot be specified inside `OVER (PARTITION BY ...)` clauses.",
    explanation: "Window functions compute rolling partitions independently of GROUP BY modifiers.",
    hint: "WITH ROLLUP is valid only with GROUP BY, not inside OVER() clauses.",
    level: "expert"
  },
  {
    question: "How can you export a `WITH ROLLUP` report to JSON with subtotals identified?",
    shortAnswer: "Use `JSON_OBJECT('is_subtotal', GROUPING(col1) OR GROUPING(col2), 'city', col1, 'total', SUM(amount))`.",
    explanation: "The GROUPING flag can be mapped to a boolean property in generated JSON payloads.",
    hint: "Map GROUPING() result directly to a boolean property in JSON_OBJECT.",
    level: "expert"
  },
  {
    question: "How do `MIN()` and `MAX()` behave on the Grand Total row of a `WITH ROLLUP` query?",
    shortAnswer: "They compute the absolute minimum and maximum values across the entire dataset.",
    explanation: "Global extrema are correctly calculated over all rows that participated in the query.",
    hint: "They return the global minimum and maximum across the entire dataset.",
    level: "basic"
  },
  {
    question: "What is the difference between `GROUP BY col1, col2 WITH ROLLUP` and multiple `UNION ALL` queries in terms of database locks and buffer pool?",
    shortAnswer: "`WITH ROLLUP` executes in a single table scan holding one read lock, whereas `UNION ALL` performs multiple table scans, causing higher buffer pool churn and read locks.",
    explanation: "Single pass aggregation reduces I/O pressure, cache thrashing, and concurrency contention.",
    hint: "WITH ROLLUP takes a single pass with one lock, avoiding multiple redundant scans.",
    level: "expert"
  },
  {
    question: "What is the golden rule for ordering columns in `WITH ROLLUP` queries?",
    shortAnswer: "Place columns in order from highest/broadest hierarchy to lowest/finest hierarchy (e.g., Year -> Quarter -> Month -> Day, or Country -> State -> City).",
    explanation: "ROLLUP drops columns from right to left; placing the highest hierarchy first produces logical, intuitive subtotal breakdowns.",
    hint: "Order from broadest category on the left to finest detail on the right.",
    level: "basic"
  }
];

export default questions;
