import React, { useState } from "react";
import clsx from "clsx";

// ─── Common Framework Imports ──────────────────────────────────────────
import Teacher from "../../../../../common/TeacherSukantaHui";
import FAQTemplate from "../../../../../common/FAQTemplate";
import PlainTextPrint from "../../../../../common/PlainTextPrint";
import questions from "./topic10_files/topic10_questions";
import noteText from "./topic10_files/topic10_note.txt?raw";

/**
 * Topic10 – Table Maintenance Commands: OPTIMIZE TABLE, CHECK TABLE, ANALYZE TABLE, REPAIR TABLE
 * Module: 004_001_storage-engines-and-architecture
 *
 * @component
 * @returns {JSX.Element} Interactive table maintenance workbench: analyzing index cardinality statistics refresh with ANALYZE TABLE, structural B+ tree validation with CHECK TABLE, online defragmentation with OPTIMIZE TABLE, legacy REPAIR TABLE handling, and automated fleet maintenance with mysqlcheck.
 */
const Topic10 = () => {
  // Interactive Maintenance Command State
  const [selectedMaintCmd, setSelectedMaintCmd] = useState("cmd1_analyze");

  const maintenanceCommands = {
    cmd1_analyze: {
      cmdNumber: "1. ANALYZE TABLE",
      title: "1. ANALYZE TABLE: Refreshing Optimizer Index Statistics",
      badge: "Statistics Refresh",
      badgeColor: "emerald",
      sqlSnippet: `-- 📊 ANALYZE TABLE: OPTIMIZER STATS REFRESH:
-- 1. Refresh index cardinality statistics on active tables:
ANALYZE TABLE customer_orders, students;

-- 2. Inspect persistent index statistics generated by MySQL:
SELECT 
    table_name, index_name, stat_name, stat_value, stat_description
FROM mysql.innodb_index_stats
WHERE database_name = 'college_admissions'
ORDER BY table_name, index_name;

-- 3. Configure sample page density (Higher = More Accurate on large tables):
SHOW VARIABLES LIKE 'innodb_stats_persistent_sample_pages'; -- Default: 20`,
      metricsTable: [
        { feature: "Primary Duty", value: "Updates index cardinality statistics", role: "Guides Cost-Based Optimizer (CBO) to choose optimal indexes" },
        { feature: "Locking Behavior", value: "Light sampling read lock", role: "Zero table rebuild; live concurrent writes continue normally" },
        { feature: "Execution Duration", value: "Milliseconds", role: "Samples 20 to 100 pages in memory" },
        { feature: "Catalog Table", value: "mysql.innodb_index_stats", role: "Persists statistics across server restarts" }
      ],
      explanation:
        "`ANALYZE TABLE` samples index pages and updates persistent statistics in `mysql.innodb_index_stats`. It executes in milliseconds without locking concurrent writes, ensuring the Cost-Based Optimizer selects index seeks over full table scans."
    },
    cmd2_check: {
      cmdNumber: "2. CHECK TABLE",
      title: "2. CHECK TABLE: Structural Integrity & Corruption Validation",
      badge: "Integrity Audit",
      badgeColor: "cyan",
      sqlSnippet: `-- 🔍 CHECK TABLE: VERIFYING B+ TREE & CHECKSUM INTEGRITY:
-- 1. Standard Integrity Check:
CHECK TABLE customer_orders;
-- Output: [Table: customer_orders, Op: check, Msg_type: status, Msg_text: OK]

-- 2. Comprehensive Deep Scan (Validates all rows against secondary indexes):
CHECK TABLE customer_orders EXTENDED;

-- 3. Pre-Upgrade Compatibility Check (Before major MySQL 8.0 upgrade):
CHECK TABLE customer_orders FOR UPGRADE;

-- 4. Fast Check (Validates only improperly closed tables):
CHECK TABLE customer_orders FAST;`,
      metricsTable: [
        { feature: "Primary Duty", value: "Validates B+ tree links and checksums", role: "Detects corrupted pages and index pointer mismatches" },
        { feature: "QUICK Option", value: "Validates tree links only", role: "Fastest verification without scanning every individual row" },
        { feature: "EXTENDED Option", value: "Deep row-by-row verification", role: "Matches every single data row against all secondary indexes" },
        { feature: "FOR UPGRADE", value: "Version compatibility audit", role: "Flags deprecated keywords or incompatible column types" }
      ],
      explanation:
        "`CHECK TABLE` validates B+ tree structural integrity, page checksums, and secondary index pointers. Running `CHECK TABLE ... FOR UPGRADE` is mandatory before major MySQL version upgrades to catch schema incompatibilities."
    },
    cmd3_optimize: {
      cmdNumber: "3. OPTIMIZE TABLE",
      title: "3. OPTIMIZE TABLE: Online Defragmentation & Disk Reclamation",
      badge: "Online Rebuild",
      badgeColor: "amber",
      sqlSnippet: `-- ⚡ OPTIMIZE TABLE: ONLINE DEFRAGMENTATION & REBUILD:
-- 1. Reclaim deleted dead space and shrink .ibd file:
OPTIMIZE TABLE customer_orders;

-- Output for InnoDB:
-- [Table: customer_orders, Op: optimize, Msg_type: note, 
--  Msg_text: Table does not support optimize, doing recreate + analyze instead]
-- [Table: customer_orders, Op: optimize, Msg_type: status, Msg_text: OK]

-- 2. Equivalent Declarative Online DDL:
ALTER TABLE customer_orders ENGINE = InnoDB, ALGORITHM = INPLACE, LOCK = NONE;`,
      metricsTable: [
        { feature: "Primary Duty", value: "Online Table Rebuild", role: "Compacts active rows and reclaims data_free dead space" },
        { feature: "Disk Impact", value: "Shrinks physical .ibd file", role: "Returns reclaimed space directly to the OS filesystem" },
        { feature: "Index Optimization", value: "Sorted Index Build", role: "Rebuilds all secondary indexes in sorted key order (~93% fill)" },
        { feature: "Concurrency", value: "Zero Downtime (ALGORITHM=INPLACE)", role: "Allows uninterrupted live application reads and writes" }
      ],
      explanation:
        "`OPTIMIZE TABLE` performs an online table rebuild, compacting active rows into 93% full pages, rebuilding secondary indexes in sorted order, and shrinking the physical `.ibd` file on disk while live writes continue."
    },
    cmd4_mysqlcheck: {
      cmdNumber: "4. mysqlcheck Utility",
      title: "4. Automated Fleet Maintenance with the mysqlcheck CLI Utility",
      badge: "CLI Automation",
      badgeColor: "rose",
      sqlSnippet: `-- 🤖 AUTOMATING MAINTENANCE FLEET-WIDE WITH MYSQLCHECK:
-- 1. Run health check across all databases:
-- mysqlcheck -u root -p --check --all-databases

-- 2. Update optimizer statistics across specific database:
-- mysqlcheck -u root -p --analyze --databases college_admissions

-- 3. Defragment and reclaim space across all tables:
-- mysqlcheck -u root -p --optimize --databases college_admissions

-- 4. Multi-threaded Parallel Execution for fast maintenance:
-- mysqlcheck -u root -p --analyze --all-databases --parallel 4`,
      metricsTable: [
        { feature: "Command Utility", value: "mysqlcheck CLI binary", role: "Automates maintenance across multiple schemas and tables" },
        { feature: "Parallel Execution", value: "--parallel &lt;N&gt;", role: "Executes maintenance across multiple CPU cores in parallel" },
        { feature: "Auto-Authentication", value: "~/.my.cnf integration", role: "Ideal for scheduled midnight cron maintenance jobs" },
        { feature: "Summary Logging", value: "Standardized Exit Codes", role: "Integrates with enterprise monitoring systems (Nagios/Zabbix)" }
      ],
      explanation:
        "`mysqlcheck` is the standard command-line utility for automating `ANALYZE`, `CHECK`, and `OPTIMIZE` across entire database instances, supporting multi-threaded parallel execution for nightly cron maintenance."
    }
  };

  const navItems = [
    { id: "commands-overview", label: "1. Commands Overview" },
    { id: "matrix-diagram", label: "2. Maintenance Pipeline Diagram" },
    { id: "interactive-workbench", label: "3. Maintenance Workbench" },
    { id: "case-studies", label: "4. Real-World Case Studies" },
    { id: "pitfalls-rules", label: "5. Senior Pitfalls & Best Practices" },
    { id: "checklist", label: "6. Table Maintenance Checklist" },
    { id: "faq-section", label: "7. FAQs (30 Deep Questions)" },
    { id: "teacher-notes", label: "8. Printable Note & Teacher's Observation" }
  ];

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 antialiased selection:bg-cyan-500 selection:text-slate-900 pb-20">
      {/* Header Banner */}
      <header className="border-b border-slate-800 bg-gradient-to-r from-slate-900 via-indigo-950/40 to-slate-900 py-10 px-4 sm:px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          <div className="flex items-center gap-3 text-cyan-400 text-sm font-semibold tracking-wider uppercase mb-2">
            <span>Module 004_001</span>
            <span>•</span>
            <span>Topic 10 of 12</span>
            <span>•</span>
            <span className="px-2.5 py-0.5 rounded-full bg-cyan-950/80 border border-cyan-700/50 text-cyan-300 text-xs">
              Table Maintenance
            </span>
          </div>
          <h1 className="text-xl sm:text-2xl md:text-3xl font-bold text-white tracking-tight">
            Table Maintenance Commands: OPTIMIZE TABLE, CHECK TABLE, ANALYZE TABLE, REPAIR TABLE
          </h1>
          <p className="mt-3 text-lg sm:text-xl text-slate-300 max-w-3xl leading-relaxed">
            Master the four administrative maintenance pillars of MySQL: refresh Cost-Based Optimizer index cardinality statistics with <code className="text-emerald-400 font-mono">ANALYZE TABLE</code>, validate structural integrity with <code className="text-cyan-400 font-mono">CHECK TABLE</code>, defragment storage with <code className="text-amber-400 font-mono">OPTIMIZE TABLE</code>, and automate fleet routines using <code className="text-rose-400 font-mono">mysqlcheck</code>.
          </p>
        </div>
      </header>

      {/* Navigation Quick Links */}
      <nav className="sticky top-0 z-30 bg-slate-900/90 backdrop-blur-md border-b border-slate-800 px-4 sm:px-6 lg:px-8 py-3">
        <div className="max-w-6xl mx-auto flex items-center gap-2 overflow-x-auto text-xs sm:text-sm font-medium scrollbar-thin scrollbar-thumb-slate-700">
          {navItems.map((item) => (
            <a
              key={item.id}
              href={`#${item.id}`}
              className="whitespace-nowrap px-3 py-1.5 rounded-lg bg-slate-800/80 hover:bg-cyan-600/30 hover:text-cyan-300 text-slate-300 transition-all duration-300 border border-slate-700/50 hover:border-cyan-500/40"
            >
              {item.label}
            </a>
          ))}
        </div>
      </nav>

      {/* Main Container */}
      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-16">
        {/* SECTION 1: Commands Overview */}
        <section id="commands-overview" className="space-y-6">
          <div className="border-l-4 border-emerald-500 pl-4">
            <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
              1. The 4 Table Maintenance Pillars
            </h2>
            <p className="text-slate-400 mt-1 text-sm sm:text-base">
              Distinct administrative commands maintaining query optimizer efficiency, data integrity, and physical storage.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-2">
              <span className="text-xs font-mono text-emerald-400 font-bold uppercase">1. ANALYZE TABLE</span>
              <h3 className="font-bold text-white">Index Cardinality</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Updates `mysql.innodb_index_stats` to guide Cost-Based Optimizer query plans.
              </p>
            </div>

            <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-2">
              <span className="text-xs font-mono text-cyan-400 font-bold uppercase">2. CHECK TABLE</span>
              <h3 className="font-bold text-white">Structural Integrity</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Scans B+ tree pointer consistency and validates page CRC32 checksums.
              </p>
            </div>

            <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-2">
              <span className="text-xs font-mono text-amber-400 font-bold uppercase">3. OPTIMIZE TABLE</span>
              <h3 className="font-bold text-white">Defragmentation</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Rebuilds table into 93% compact pages, shrinking physical `.ibd` files.
              </p>
            </div>

            <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-2">
              <span className="text-xs font-mono text-rose-400 font-bold uppercase">4. mysqlcheck</span>
              <h3 className="font-bold text-white">CLI Automation</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Executes multi-threaded parallel maintenance across all databases in cron jobs.
              </p>
            </div>
          </div>
        </section>

        {/* SECTION 2: Maintenance Pipeline Diagram */}
        <section id="matrix-diagram" className="space-y-6">
          <div className="border-l-4 border-indigo-500 pl-4">
            <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
              2. Visual Anatomy: Table Maintenance Decision Matrix
            </h2>
            <p className="text-slate-400 mt-1 text-sm sm:text-base">
              Selecting the appropriate maintenance command based on diagnostic symptoms.
            </p>
          </div>

          <div className="p-6 rounded-2xl bg-slate-900/90 border border-slate-800 space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-base font-bold text-cyan-300">
                Figure 10.1: Maintenance Trigger &amp; Execution Pipeline
              </h3>
              <span className="text-xs text-slate-400 font-mono">DBA Operational Matrix</span>
            </div>

            <div className="w-full overflow-x-auto bg-slate-950 p-4 rounded-xl border border-slate-800">
              <svg
                viewBox="0 0 950 360"
                className="w-full max-w-4xl mx-auto block font-sans"
                style={{ minWidth: "700px" }}
              >
                <defs>
                  <marker id="arrMaintCyan" markerWidth="8" markerHeight="8" refX="6" refY="4" orient="auto">
                    <polygon points="0 0, 8 4, 0 8" fill="#38bdf8" />
                  </marker>
                </defs>

                {/* Box 1: ANALYZE TABLE */}
                <rect x="20" y="40" width="280" height="280" rx="8" fill="#0f172a" stroke="#10b981" strokeWidth="1.5" />
                <text x="160" y="70" fill="#34d399" fontSize="12" fontWeight="bold" textAnchor="middle">
                  1. ANALYZE TABLE (Stats)
                </text>
                <line x1="20" y1="85" x2="300" y2="85" stroke="#334155" />

                <rect x="35" y="105" width="250" height="45" rx="4" fill="#1e293b" stroke="#047857" />
                <text x="45" y="125" fill="#a7f3d0" fontSize="10" fontWeight="bold">Symptom: Slow Query Plans</text>
                <text x="45" y="140" fill="#94a3b8" fontSize="9">Optimizer choosing ALL instead of Index</text>

                <rect x="35" y="165" width="250" height="45" rx="4" fill="#1e293b" stroke="#0284c7" />
                <text x="45" y="185" fill="#bae6fd" fontSize="10" fontWeight="bold">Action: Sampling Read Lock</text>
                <text x="45" y="200" fill="#94a3b8" fontSize="9">Updates mysql.innodb_index_stats</text>

                <rect x="35" y="225" width="250" height="45" rx="4" fill="#1e293b" stroke="#10b981" />
                <text x="45" y="245" fill="#34d399" fontSize="10" fontWeight="bold">Result: Fast Index Plans Restored! ✅</text>

                {/* Box 2: CHECK TABLE */}
                <rect x="335" y="40" width="280" height="280" rx="8" fill="#0f172a" stroke="#0ea5e9" strokeWidth="1.5" />
                <text x="475" y="70" fill="#38bdf8" fontSize="12" fontWeight="bold" textAnchor="middle">
                  2. CHECK TABLE (Integrity)
                </text>
                <line x1="335" y1="85" x2="615" y2="85" stroke="#334155" />

                <rect x="350" y="105" width="250" height="45" rx="4" fill="#1e293b" stroke="#0284c7" />
                <text x="360" y="125" fill="#bae6fd" fontSize="10" fontWeight="bold">Symptom: Suspected Corruption</text>
                <text x="360" y="140" fill="#94a3b8" fontSize="9">Post-crash audit or Pre-Upgrade verification</text>

                <rect x="350" y="165" width="250" height="45" rx="4" fill="#1e293b" stroke="#d97706" />
                <text x="360" y="185" fill="#fde68a" fontSize="10" fontWeight="bold">Action: CRC32 &amp; B+ Tree Audit</text>
                <text x="360" y="200" fill="#94a3b8" fontSize="9">Validates page headers and pointers</text>

                <rect x="350" y="225" width="250" height="45" rx="4" fill="#1e293b" stroke="#10b981" />
                <text x="360" y="245" fill="#34d399" fontSize="10" fontWeight="bold">Result: Msg_text: OK Verified! ✅</text>

                {/* Box 3: OPTIMIZE TABLE */}
                <rect x="650" y="40" width="280" height="280" rx="8" fill="#0f172a" stroke="#f59e0b" strokeWidth="1.5" />
                <text x="790" y="70" fill="#fbbf24" fontSize="12" fontWeight="bold" textAnchor="middle">
                  3. OPTIMIZE TABLE (Defrag)
                </text>
                <line x1="650" y1="85" x2="930" y2="85" stroke="#334155" />

                <rect x="665" y="105" width="250" height="45" rx="4" fill="#1e293b" stroke="#d97706" />
                <text x="675" y="125" fill="#fde68a" fontSize="10" fontWeight="bold">Symptom: High data_free Bloat</text>
                <text x="675" y="140" fill="#94a3b8" fontSize="9">Deleted rows leaving dead space in .ibd</text>

                <rect x="665" y="165" width="250" height="45" rx="4" fill="#1e293b" stroke="#047857" />
                <text x="675" y="185" fill="#a7f3d0" fontSize="10" fontWeight="bold">Action: Online Table Rebuild</text>
                <text x="675" y="200" fill="#94a3b8" fontSize="9">ALGORITHM=INPLACE, LOCK=NONE</text>

                <rect x="665" y="225" width="250" height="45" rx="4" fill="#1e293b" stroke="#10b981" />
                <text x="675" y="245" fill="#34d399" fontSize="10" fontWeight="bold">Result: .ibd File Shrunk on OS! ✅</text>
              </svg>
            </div>
          </div>
        </section>

        {/* SECTION 3: Maintenance Workbench */}
        <section id="interactive-workbench" className="space-y-6">
          <div className="border-l-4 border-cyan-500 pl-4">
            <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
              3. Interactive Maintenance Workbench
            </h2>
            <p className="text-slate-400 mt-1 text-sm sm:text-base">
              Select a maintenance command to inspect syntax variations, lock behaviors, and DBA execution runbooks.
            </p>
          </div>

          {/* Tab Buttons */}
          <div className="flex flex-wrap gap-2.5">
            {Object.keys(maintenanceCommands).map((key) => {
              const cmd = maintenanceCommands[key];
              const isSelected = selectedMaintCmd === key;
              return (
                <button
                  key={key}
                  onClick={() => setSelectedMaintCmd(key)}
                  className={clsx(
                    "px-4 py-2.5 rounded-xl text-xs sm:text-sm font-semibold transition-all duration-300 border flex items-center gap-2",
                    isSelected
                      ? "bg-cyan-600/30 text-cyan-300 border-cyan-500 shadow-lg shadow-cyan-950/50"
                      : "bg-slate-900/80 text-slate-400 border-slate-800 hover:bg-slate-800 hover:text-slate-200"
                  )}
                >
                  <span
                    className={clsx(
                      "w-2.5 h-2.5 rounded-full",
                      cmd.badgeColor === "emerald" && "bg-emerald-400",
                      cmd.badgeColor === "cyan" && "bg-cyan-400",
                      cmd.badgeColor === "amber" && "bg-amber-400",
                      cmd.badgeColor === "rose" && "bg-rose-400"
                    )}
                  />
                  <span>{cmd.cmdNumber}</span>
                </button>
              );
            })}
          </div>

          {/* Display Card */}
          <div className="p-6 rounded-2xl bg-slate-900/90 border border-slate-800 space-y-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-4">
              <h3 className="text-lg sm:text-xl font-bold text-white">
                {maintenanceCommands[selectedMaintCmd].title}
              </h3>
              <span
                className={clsx(
                  "px-3 py-1 rounded-full text-xs font-mono font-bold self-start sm:self-auto",
                  maintenanceCommands[selectedMaintCmd].badgeColor === "emerald" &&
                    "bg-emerald-950 text-emerald-300 border border-emerald-800",
                  maintenanceCommands[selectedMaintCmd].badgeColor === "cyan" &&
                    "bg-cyan-950 text-cyan-300 border border-cyan-800",
                  maintenanceCommands[selectedMaintCmd].badgeColor === "amber" &&
                    "bg-amber-950 text-amber-300 border border-amber-800",
                  maintenanceCommands[selectedMaintCmd].badgeColor === "rose" &&
                    "bg-rose-950 text-rose-300 border border-rose-800"
                )}
              >
                {maintenanceCommands[selectedMaintCmd].badge}
              </span>
            </div>

            {/* SQL Script Block */}
            <div className="space-y-2">
              <span className="text-xs font-mono text-slate-400 uppercase tracking-wider">
                Maintenance Script &amp; Diagnostic Queries:
              </span>
              <pre className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs sm:text-sm font-mono text-cyan-300 overflow-x-auto leading-relaxed scrollbar-thin scrollbar-thumb-slate-700">
                {maintenanceCommands[selectedMaintCmd].sqlSnippet}
              </pre>
            </div>

            {/* Metrics Table */}
            <div className="space-y-2">
              <span className="text-xs font-mono text-slate-400 uppercase tracking-wider">
                Operational Characteristics:
              </span>
              <div className="overflow-x-auto rounded-xl border border-slate-800 bg-slate-950">
                <table className="w-full text-left text-xs sm:text-sm text-slate-300">
                  <thead className="bg-slate-900/80 text-cyan-400 font-mono uppercase text-[11px]">
                    <tr>
                      <th className="py-2.5 px-4">Maintenance Feature</th>
                      <th className="py-2.5 px-4">Configuration &amp; Value</th>
                      <th className="py-2.5 px-4">Operational Role</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-800 font-mono text-xs">
                    {maintenanceCommands[selectedMaintCmd].metricsTable.map((row, idx) => (
                      <tr key={idx} className="hover:bg-slate-900/50">
                        <td className="py-3 px-4 font-bold text-white font-sans">{row.feature}</td>
                        <td className="py-3 px-4 text-cyan-300">{row.value}</td>
                        <td className="py-3 px-4 text-slate-300 font-sans">{row.role}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Explanation Box */}
            <div className="p-4 rounded-xl bg-slate-950 border border-slate-800">
              <h4 className="text-xs font-bold text-cyan-400 uppercase tracking-wider mb-1">
                Engineering Assessment:
              </h4>
              <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                {maintenanceCommands[selectedMaintCmd].explanation}
              </p>
            </div>
          </div>
        </section>

        {/* SECTION 4: Real-World Case Studies */}
        <section id="case-studies" className="space-y-6">
          <div className="border-l-4 border-indigo-500 pl-4">
            <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
              4. Real-World Maintenance Case Studies
            </h2>
            <p className="text-slate-400 mt-1 text-sm sm:text-base">
              Resolving optimizer plan regressions and pre-upgrade validations in West Bengal systems.
            </p>
          </div>

          <div className="space-y-6">
            {/* Case 1: Mamata & Susmita's Statistics Refresh */}
            <div className="p-6 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-800 pb-3">
                <h3 className="text-base font-bold text-white flex items-center gap-2">
                  <span className="w-2.5 h-2.5 rounded-full bg-emerald-400" />
                  Case 1: Mamata &amp; Susmita – Fixing 8-Second Query Regression with ANALYZE TABLE in Barrackpore
                </h3>
                <span className="text-xs font-mono text-emerald-400 bg-emerald-950/80 px-2.5 py-1 rounded-full border border-emerald-800">
                  Plan Regression Fixed
                </span>
              </div>
              <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                In Barrackpore, after inserting 2 million student marksheet records, a query that normally ran in 2ms suddenly took 8.4 seconds because stale statistics caused the optimizer to perform a full table scan. Running `ANALYZE TABLE student_marksheets;` refreshed `mysql.innodb_index_stats` in 120ms, immediately restoring the 2ms index range seek execution plan.
              </p>
            </div>

            {/* Case 2: Abhronila & Debangshu's Pre-Upgrade Check */}
            <div className="p-6 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-800 pb-3">
                <h3 className="text-base font-bold text-white flex items-center gap-2">
                  <span className="w-2.5 h-2.5 rounded-full bg-cyan-400" />
                  Case 2: Abhronila &amp; Debangshu – Zero-Failure MySQL 8.0 Upgrade with CHECK FOR UPGRADE in Kolkata
                </h3>
                <span className="text-xs font-mono text-cyan-400 bg-cyan-950/80 px-2.5 py-1 rounded-full border border-cyan-800">
                  Upgrade Verified
                </span>
              </div>
              <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                In Kolkata, running `mysqlcheck --check-upgrade --all-databases` prior to migrating a 500-table database from MySQL 5.7 to MySQL 8.0 identified 3 legacy tables with deprecated `utf8` (utf8mb3) collation collisions and 1 table using the newly reserved keyword `GROUPS`. Fixing these 4 tables beforehand enabled a 100% flawless zero-downtime MySQL 8.0 upgrade.
              </p>
            </div>
          </div>
        </section>

        {/* SECTION 5: Senior Pitfalls & Best Practices */}
        <section id="pitfalls-rules" className="space-y-6">
          <div className="border-l-4 border-rose-500 pl-4">
            <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
              5. Senior Pitfalls &amp; Production Best Practices
            </h2>
            <p className="text-slate-400 mt-1 text-sm sm:text-base">
              Avoid dangerous table maintenance mistakes in production environments.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="p-6 rounded-2xl bg-slate-900/80 border border-slate-800">
              <h3 className="text-base font-bold text-rose-400 mb-3 flex items-center gap-2">
                <span>⚠️</span> Pitfall 1: Attempting REPAIR TABLE on InnoDB
              </h3>
              <p className="text-xs sm:text-sm text-slate-300 leading-relaxed mb-3">
                `REPAIR TABLE` is a legacy MyISAM command; executing it on InnoDB outputs a warning and does nothing.
              </p>
              <div className="text-xs font-mono text-emerald-400 p-2 bg-slate-950 rounded border border-slate-800">
                Rule: Use OPTIMIZE TABLE or ALTER TABLE ... ENGINE=InnoDB for InnoDB tables.
              </div>
            </div>

            <div className="p-6 rounded-2xl bg-slate-900/80 border border-slate-800">
              <h3 className="text-base font-bold text-rose-400 mb-3 flex items-center gap-2">
                <span>⚠️</span> Pitfall 2: Forgetting ANALYZE after Bulk Data Imports
              </h3>
              <p className="text-xs sm:text-sm text-slate-300 leading-relaxed mb-3">
                Importing millions of rows without running `ANALYZE TABLE` leaves the optimizer with outdated cardinality estimates, degrading query performance.
              </p>
              <div className="text-xs font-mono text-emerald-400 p-2 bg-slate-950 rounded border border-slate-800">
                Rule: Always execute ANALYZE TABLE immediately following bulk ETL imports.
              </div>
            </div>

            <div className="p-6 rounded-2xl bg-slate-900/80 border border-slate-800">
              <h3 className="text-base font-bold text-emerald-400 mb-3 flex items-center gap-2">
                <span>✓</span> Best Practice 1: Automate with mysqlcheck
              </h3>
              <p className="text-xs sm:text-sm text-slate-300 leading-relaxed mb-3">
                Use `mysqlcheck --analyze --all-databases` in a scheduled weekly cron job to ensure the query optimizer always has fresh cardinality statistics.
              </p>
              <div className="text-xs text-slate-400">
                Guarantees optimal query plans across all database schemas.
              </div>
            </div>

            <div className="p-6 rounded-2xl bg-slate-900/80 border border-slate-800">
              <h3 className="text-base font-bold text-emerald-400 mb-3 flex items-center gap-2">
                <span>✓</span> Best Practice 2: Run CHECK FOR UPGRADE
              </h3>
              <p className="text-xs sm:text-sm text-slate-300 leading-relaxed mb-3">
                Always run `CHECK TABLE tbl FOR UPGRADE;` prior to any major MySQL upgrade to detect incompatible collations, data types, and reserved words.
              </p>
              <div className="text-xs text-slate-400">
                Prevents upgrade failures and corrupted data dictionaries.
              </div>
            </div>
          </div>
        </section>

        {/* SECTION 6: Table Maintenance Checklist */}
        <section id="checklist" className="space-y-6">
          <div className="border-l-4 border-amber-500 pl-4">
            <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
              6. DBA Table Maintenance Checklist
            </h2>
            <p className="text-slate-400 mt-1 text-sm sm:text-base">
              Key maintenance operations to incorporate into enterprise database runbooks.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="p-6 rounded-2xl bg-slate-900/80 border border-slate-800">
              <h3 className="text-base font-bold text-white mb-4 flex items-center gap-2">
                <span className="text-amber-400">✓</span> Maintenance Checklist
              </h3>
              <ul className="space-y-3 text-xs sm:text-sm text-slate-300">
                <li className="flex items-start gap-2">
                  <span className="text-emerald-400 font-bold font-mono">01.</span>
                  <span><strong className="text-emerald-400">ANALYZE TABLE</strong> = Run post-bulk-import to refresh index cardinality.</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-cyan-400 font-bold font-mono">02.</span>
                  <span><strong className="text-cyan-400">CHECK TABLE</strong> = Execute `FOR UPGRADE` prior to MySQL version migrations.</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-amber-400 font-bold font-mono">03.</span>
                  <span><strong className="text-amber-400">OPTIMIZE TABLE</strong> = Rebuild tables when `data_free` &gt; 20% of table size.</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-rose-400 font-bold font-mono">04.</span>
                  <span><strong className="text-rose-400">mysqlcheck</strong> = Schedule weekly automated statistics updates in cron.</span>
                </li>
              </ul>
            </div>

            <div className="p-6 rounded-2xl bg-slate-900/80 border border-slate-800">
              <h3 className="text-base font-bold text-white mb-4 flex items-center gap-2">
                <span className="text-cyan-400">💡</span> Senior Developer Hints
              </h3>
              <div className="space-y-4 text-xs sm:text-sm text-slate-300">
                <div className="p-3 bg-slate-950 rounded-lg border border-slate-800">
                  <span className="text-cyan-400 font-bold block mb-1">“Observe ANALYZE vs OPTIMIZE...”</span>
                  `ANALYZE TABLE` runs in milliseconds because it only samples index pages to update statistics. `OPTIMIZE TABLE` rebuilds the entire B+ tree into a new file. Know which one you need before running maintenance!
                </div>
                <div className="p-3 bg-slate-950 rounded-lg border border-slate-800">
                  <span className="text-emerald-400 font-bold block mb-1">“Think about mysqlcheck --parallel...”</span>
                  On a server with 100 databases, running `mysqlcheck --analyze --all-databases --parallel 8` completes in 2 minutes instead of 20 minutes!
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* SECTION 7: FAQ Template */}
        <section id="faq-section" className="space-y-6">
          <div className="border-l-4 border-cyan-500 pl-4">
            <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
              7. Frequently Asked Questions (30 Deep-Dive Questions)
            </h2>
            <p className="text-slate-400 mt-1 text-sm sm:text-base">
              Comprehensive reference questions covering Table Maintenance Commands and mysqlcheck.
            </p>
          </div>

          <FAQTemplate
            title="MySQL Table Maintenance Commands FAQs"
            questions={questions}
          />
        </section>

        {/* SECTION 8: PlainTextPrint & Teacher's Note */}
        <section id="teacher-notes" className="space-y-8">
          <div className="border-l-4 border-indigo-500 pl-4">
            <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
              8. Printable Topic Note &amp; Teacher's Observation
            </h2>
            <p className="text-slate-400 mt-1 text-sm sm:text-base">
              Download clean text documentation for revision and study Sukanta Hui's direct pedagogical insights.
            </p>
          </div>

          <PlainTextPrint
            content={noteText}
            title="Table Maintenance Commands: OPTIMIZE TABLE, CHECK TABLE, ANALYZE TABLE, REPAIR TABLE"
            stampEnabled={true}
            showDownload={true}
            downloadButtonText="Download Topic Note (.txt)"
            downloadFileName="topic10_note.txt"
          />

          <Teacher
            note="Proactive table maintenance is the hallmark of a world-class database administrator. When a query suddenly slows down from 5ms to 10 seconds, junior developers panic and rewrite application code; senior DBAs run ANALYZE TABLE to refresh stale index statistics in 50 milliseconds! When storage fills up after large archival purges, OPTIMIZE TABLE reclaims tens of gigabytes online. And before any major database upgrade, CHECK TABLE FOR UPGRADE ensures zero surprises. Master these four maintenance pillars to keep your MySQL instances humming at peak performance!"
          />
        </section>
      </main>
    </div>
  );
};

export default Topic10;
