const questions = [
  {
    question: "What is bus topology?",
    shortAnswer: "A network topology where all devices connect to a single backbone cable.",
    explanation: "Devices share the same communication line, with terminators at both ends.",
    hint: "Think of a single road with houses along it.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the backbone in bus topology?",
    shortAnswer: "The main cable (bus) that all devices connect to.",
    explanation: "Data travels along the backbone, and all devices can see the traffic.",
    hint: "The main road.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What are terminators in bus topology?",
    shortAnswer: "Devices at the ends of the bus that absorb signals to prevent reflection.",
    explanation: "Without terminators, signals bounce back and cause data corruption.",
    hint: "Signal absorbers.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the role of a T-connector in bus topology?",
    shortAnswer: "A connector that attaches each device to the backbone cable.",
    explanation: "T-connectors are used with coaxial cable to tap into the bus.",
    hint: "The branch connecting the device to the road.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What happens if the backbone cable breaks in bus topology?",
    shortAnswer: "The entire network goes down.",
    explanation: "All devices rely on the single cable for communication.",
    hint: "A broken road stops all traffic.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the maximum length of a 10BASE-2 bus topology segment?",
    shortAnswer: "185 meters.",
    explanation: "10BASE-2 (thinnet) had a maximum segment length of 185m.",
    hint: "About 600 feet.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the maximum number of nodes on a 10BASE-2 bus?",
    shortAnswer: "30 nodes per segment.",
    explanation: "More than 30 nodes would degrade performance.",
    hint: "A small classroom.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the advantage of bus topology?",
    shortAnswer: "Simple and inexpensive to implement.",
    explanation: "Requires less cabling than star topology.",
    hint: "Cheap and easy.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the disadvantage of bus topology?",
    shortAnswer: "A single break in the backbone brings down the network.",
    explanation: "The bus is a single point of failure.",
    hint: "One break, everyone down.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Is bus topology still used today?",
    shortAnswer: "No, it's largely obsolete, replaced by star topology.",
    explanation: "Modern networks use switches for better performance and reliability.",
    hint: "Old technology.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is CSMA/CD and why is it used in bus topology?",
    shortAnswer: "Carrier Sense Multiple Access with Collision Detection – a protocol to manage collisions.",
    explanation: "Devices listen before transmitting and back off if a collision occurs.",
    hint: "Listen before speaking, and stop if someone interrupts.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does a collision occur in bus topology?",
    shortAnswer: "When two devices transmit data simultaneously on the bus.",
    explanation: "Collisions cause data corruption and require retransmission.",
    hint: "Two cars meeting in the same lane.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is signal reflection in bus topology?",
    shortAnswer: "When a signal reaches the end of the bus and bounces back.",
    explanation: "Reflection causes data corruption; terminators absorb the signal.",
    hint: "An echo in a tunnel.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between bus and star topology?",
    shortAnswer: "Bus has a single central cable; star has a central hub/switch.",
    explanation: "Star is more reliable and scalable.",
    hint: "One road vs. spokes from a center.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "Why is star topology more reliable than bus?",
    shortAnswer: "A failure in one device doesn't affect others; bus failure affects everyone.",
    explanation: "In star, each device has its own cable to the switch.",
    hint: "One broken branch vs. a broken trunk.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What was 10BASE-2?",
    shortAnswer: "An early Ethernet standard using thin coaxial cable in bus topology.",
    explanation: "10 = 10 Mbps, BASE = baseband, 2 = max length ~200m (actually 185m).",
    hint: "Thinnet Ethernet.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What was 10BASE-5?",
    shortAnswer: "An early Ethernet standard using thick coaxial cable (thicknet) in bus topology.",
    explanation: "10 = 10 Mbps, BASE = baseband, 5 = max length 500m.",
    hint: "Thicknet Ethernet.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of the MAC address in bus topology?",
    shortAnswer: "The MAC address identifies the intended recipient of a data frame.",
    explanation: "All devices see the data, but only the device with the matching MAC processes it.",
    hint: "The destination address.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How do you troubleshoot a bus network failure?",
    shortAnswer: "Check the backbone for breaks, ensure terminators are in place, and test each connection.",
    explanation: "Isolating faults in a bus can be time-consuming.",
    hint: "Find the break in the line.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the impact of adding more devices to a bus network?",
    shortAnswer: "Performance degrades due to more collisions and reduced bandwidth per device.",
    explanation: "All devices share the same bandwidth.",
    hint: "More cars on a single road = more traffic.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between half-duplex and full-duplex in bus topology?",
    shortAnswer: "Bus topology is half-duplex – devices can't send and receive simultaneously.",
    explanation: "Collisions occur because devices share the same medium.",
    hint: "Walkie-talkie vs. telephone.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the binary exponential backoff algorithm?",
    shortAnswer: "A collision resolution mechanism where devices wait an increasing random time before retransmitting.",
    explanation: "Used in CSMA/CD to reduce repeated collisions.",
    hint: "Back off and try again later.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "Why did Ethernet evolve from bus to star?",
    shortAnswer: "Star topology with switches eliminates collisions and provides better performance and reliability.",
    explanation: "Switches create separate collision domains and support full-duplex.",
    hint: "A more efficient design.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of a switch in star topology vs. a bus?",
    shortAnswer: "A switch intelligently forwards data to the intended port; a bus broadcasts to all devices.",
    explanation: "Switches reduce collisions and improve security.",
    hint: "A smart traffic controller.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the maximum cable length for a modern Ethernet network?",
    shortAnswer: "100 meters for twisted-pair Ethernet (Cat5e/Cat6).",
    explanation: "Beyond 100m, signal attenuation requires repeaters or fiber.",
    hint: "The standard limit for a single cable run.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is impedance matching in bus topology?",
    shortAnswer: "Ensuring the cable's impedance matches the terminators (50 ohms) to prevent reflection.",
    explanation: "Mismatch causes signal reflections and data errors.",
    hint: "Matching the resistance.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is a collision domain in bus topology?",
    shortAnswer: "The portion of the network where collisions can occur – the entire bus.",
    explanation: "All devices on the bus share the same collision domain.",
    hint: "Where traffic can collide.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does a repeater extend a bus network?",
    shortAnswer: "A repeater regenerates the signal, allowing longer cable segments.",
    explanation: "Repeaters extend the physical length of the bus.",
    hint: "A signal booster.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the significance of the 5-4-3 rule in Ethernet?",
    shortAnswer: "A rule for Ethernet segments: 5 segments, 4 repeaters, and only 3 populated segments.",
    explanation: "Ensures signal propagation delays stay within limits.",
    hint: "A rule for early Ethernet design.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are the lessons from bus topology for modern network design?",
    shortAnswer: "Avoid single points of failure, plan for scalability, and use switched networks.",
    explanation: "Bus topology taught us the importance of fault tolerance and traffic management.",
    hint: "Learn from the past.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;