const questions = [
  {
    question: "What is the legal-service resource allocation problem?",
    shortAnswer: "It's an LP problem that optimizes the mix of legal cases to maximize revenue given limited lawyer, paralegal, and staff resources.",
    explanation: "Law firms must decide how many cases of each type to handle. Each case type requires different amounts of senior lawyers, junior lawyers, paralegals, and staff. The goal is to maximize revenue within these constraints.",
    hint: "Optimizing case mix with limited legal resources.",
    level: "basic",
    codeExample: "Max Z = 8x + 6y\nSubject to: 3x + 2y ≤ 24, 2x + 4y ≤ 32"
  },
  {
    question: "What resources are typically considered in legal-service allocation?",
    shortAnswer: "Senior lawyers, junior lawyers, paralegals, administrative staff, and office space.",
    explanation: "Different case types require different combinations of resources. Senior lawyers are the most expensive and scarce resource. Paralegals and support staff also constrain capacity.",
    hint: "Legal professionals and support staff.",
    level: "basic",
    codeExample: "Senior Lawyers: 3x + 2y ≤ 24\nJunior Lawyers: 2x + 4y ≤ 32\nParalegals: x + 3y ≤ 21"
  },
  {
    question: "Why is revenue maximization used as the objective in legal-service allocation?",
    shortAnswer: "Law firms typically want to maximize revenue or profit from their limited resources.",
    explanation: "Law firms have fixed costs (salaries, office space) and variable revenue from cases. Maximizing revenue helps utilize resources efficiently and increase profitability.",
    hint: "Maximizing revenue = maximizing resource utilization.",
    level: "intermediate",
    codeExample: "Max Z = 8x + 6y where x and y are case volumes"
  },
  {
    question: "How do senior and junior lawyers differ in resource allocation?",
    shortAnswer: "Senior lawyers have higher hourly rates and may be required for complex cases, while junior lawyers handle routine work.",
    explanation: "Senior lawyers are more expensive and scarce. They should be allocated to cases that require their expertise. Junior lawyers can handle simpler cases.",
    hint: "Senior = expensive/expert, Junior = lower cost.",
    level: "intermediate",
    codeExample: "Senior: 3 hours/case, Junior: 2 hours/case"
  },
  {
    question: "What is the role of paralegals in legal-service allocation?",
    shortAnswer: "Paralegals handle document review, research, and administrative tasks, freeing lawyers for higher-value work.",
    explanation: "Paralegals are a critical resource that can become a bottleneck if not properly allocated. They handle tasks that don't require legal expertise.",
    hint: "Support tasks for lawyers.",
    level: "intermediate",
    codeExample: "Paralegal hours: x + 3y ≤ 21"
  },
  {
    question: "How do you formulate a legal-service allocation problem?",
    shortAnswer: "Define variables (case volumes), formulate constraints (resource availability), and state the objective (revenue maximization).",
    explanation: "Step 1: Define x and y for different case types. Step 2: Write constraints for each resource. Step 3: Define revenue per case. Step 4: Set up the LP problem.",
    hint: "Variables → Constraints → Objective.",
    level: "intermediate",
    codeExample: "Max Z = c₁x + c₂y\ns.t. a₁₁x + a₁₂y ≤ b₁ (Resource 1)\na₂₁x + a₂₂y ≤ b₂ (Resource 2)"
  },
  {
    question: "What does a binding constraint mean in legal-service allocation?",
    shortAnswer: "A binding constraint means a resource is fully utilized and is a bottleneck limiting case volume.",
    explanation: "If a resource constraint is binding (slack = 0), the firm cannot handle more cases without adding that resource. This resource limits revenue potential.",
    hint: "Fully utilized = bottleneck.",
    level: "intermediate",
    codeExample: "Paralegals: x + 3y = 21 (binding)\nAll paralegal hours are used"
  },
  {
    question: "What is the shadow price of a lawyer in legal-service allocation?",
    shortAnswer: "The shadow price is the additional revenue generated by having one more hour of that lawyer's time.",
    explanation: "If a lawyer constraint is binding, the shadow price tells you how much revenue increases if you add one more lawyer hour. This helps decide whether to hire more lawyers.",
    hint: "Value of additional lawyer hours.",
    level: "advanced",
    codeExample: "Shadow price = ₹2/hour → Each extra hour adds ₹2 lakhs"
  },
  {
    question: "How does specialization affect legal-service allocation?",
    shortAnswer: "Specialization means some lawyers can only handle certain case types, adding additional constraints.",
    explanation: "If senior lawyers only handle Corporate Law, you need separate constraints for specialized resources. This makes the problem more complex.",
    hint: "Some lawyers only handle specific case types.",
    level: "advanced",
    codeExample: "Senior Corporate: x ≤ 4 (max cases)\nSenior Family: y ≤ 3"
  },
  {
    question: "What is the difference between Corporate Law and Family Law cases?",
    shortAnswer: "Corporate Law cases typically require more senior lawyer time and generate higher revenue, while Family Law cases use more paralegal and junior lawyer time.",
    explanation: "Corporate cases are complex and high-value. Family cases may be more numerous but lower revenue per case. Different resource requirements affect the optimal mix.",
    hint: "Corporate = high value/complex, Family = lower value/less complex.",
    level: "intermediate",
    codeExample: "Corporate: 3 senior hours, Family: 2 senior hours"
  },
  {
    question: "How do you handle seasonality in legal-service allocation?",
    shortAnswer: "Seasonality can be handled by creating separate LP models for different time periods or adding seasonal constraints.",
    explanation: "Case volumes may vary seasonally (tax season, court schedules). Resources may also vary (vacations). Adjust constraints accordingly.",
    hint: "Different models for different seasons.",
    level: "advanced",
    codeExample: "Summer constraints: lower availability\nTax season: higher demand"
  },
  {
    question: "Why might a legal-service LP problem have multiple optimal solutions?",
    shortAnswer: "Multiple optimal solutions occur when different case mixes generate the same revenue.",
    explanation: "If the objective function is parallel to a resource constraint, different case volumes can give the same revenue. This gives flexibility in case selection.",
    hint: "Same revenue from different mixes.",
    level: "advanced",
    codeExample: "Revenue: 8x + 6y = 48\nBoth (3,4) and (6,0) give same revenue"
  },
  {
    question: "How does client priority affect legal-service allocation?",
    shortAnswer: "Client priority can be modeled as additional constraints or by modifying the objective function.",
    explanation: "High-priority clients may require guaranteed capacity. This adds constraints that must be satisfied before optimizing revenue.",
    hint: "Priority clients = additional constraints.",
    level: "advanced",
    codeExample: "Priority client: x ≥ 2 (minimum cases)"
  },
  {
    question: "What is the role of administrative staff in legal-service allocation?",
    shortAnswer: "Administrative staff handle scheduling, billing, and client communication, indirectly affecting case capacity.",
    explanation: "While not directly handling cases, administrative staff support lawyers and paralegals. Limited staff can constrain how many cases can be managed.",
    hint: "Support functions limit capacity.",
    level: "intermediate",
    codeExample: "Admin hours: 2x + y ≤ 16"
  },
  {
    question: "How do you interpret slack in legal-service allocation?",
    shortAnswer: "Slack represents unused resource capacity that could be used for additional cases.",
    explanation: "If a resource has slack, the firm could handle more cases without adding that resource. This represents growth opportunity.",
    hint: "Slack = unused capacity = opportunity.",
    level: "intermediate",
    codeExample: "Senior lawyers slack: 3 hours → Can handle more cases"
  },
  {
    question: "What is the impact of hiring more paralegals?",
    shortAnswer: "Hiring more paralegals increases capacity for support tasks, potentially increasing case volume and revenue.",
    explanation: "If paralegals are a bottleneck, adding more allows lawyers to handle more cases. The shadow price of paralegals indicates the value of hiring more.",
    hint: "More paralegals = more case capacity.",
    level: "intermediate",
    codeExample: "Paralegals +1 → Revenue +₹2 lakhs"
  },
  {
    question: "How do court schedules affect legal-service allocation?",
    shortAnswer: "Court availability constrains when cases can be filed and tried, affecting case scheduling.",
    explanation: "Court schedules can limit the number of cases that can be processed. This adds time-based constraints to the LP model.",
    hint: "Court availability = time constraints.",
    level: "advanced",
    codeExample: "Court slots: x + y ≤ 8 (per day)"
  },
  {
    question: "What is the difference between case volume and revenue in legal services?",
    shortAnswer: "Case volume is the number of cases handled; revenue is the income generated. Different case types have different revenue per case.",
    explanation: "Maximizing volume doesn't always maximize revenue. The LP objective should focus on revenue, not just case count.",
    hint: "Revenue per case varies by type.",
    level: "intermediate",
    codeExample: "Corporate: ₹8 lakhs/case\nFamily: ₹6 lakhs/case"
  },
  {
    question: "How do you validate a legal-service allocation model?",
    shortAnswer: "Validate by comparing model predictions with actual operations and adjusting constraints as needed.",
    explanation: "Check if the model's optimal solution makes practical sense. Verify resource usage matches actual operations. Adjust constraints based on reality.",
    hint: "Compare model to real operations.",
    level: "advanced",
    codeExample: "Actual case mix vs. model recommendation"
  }
];

export default questions;