// topic7_files/topic7_questions.js

const questions = [
  {
    question: "What is a Multi-Table Join in SQL?",
    shortAnswer: "A relational query that connects three, four, or more normalized tables in a single SQL statement using a chain of join conditions.",
    explanation: "Standard formal definition of multi-table joins.",
    hint: "Joining 3 or more tables in a single query.",
    level: "basic"
  },
  {
    question: "How does the MySQL query engine physically execute a multi-table join (e.g. A ⋈ B ⋈ C)?",
    shortAnswer: "As a sequence of pairwise binary joins: it joins Table A with Table B to form intermediate result I1, then joins I1 with Table C.",
    explanation: "Pairwise binary join execution pipeline.",
    hint: "As a sequence of pairwise binary joins.",
    level: "basic"
  },
  {
    question: "What is the standard order analytics join chain in e-commerce database design?",
    shortAnswer: "`Customers ➔ Orders ➔ Order_Items ➔ Products ➔ Categories`.",
    explanation: "Classic 5-table e-commerce join chain.",
    hint: "Customers ➔ Orders ➔ Order_Items ➔ Products ➔ Categories.",
    level: "basic"
  },
  {
    question: "What is the danger of following a `LEFT JOIN` with an `INNER JOIN` in a multi-table query?",
    shortAnswer: "The subsequent `INNER JOIN` filters out NULL rows generated by the `LEFT JOIN`, accidentally converting the entire query into an inner join.",
    explanation: "The INNER-after-LEFT join cancellation trap.",
    hint: "The INNER JOIN discards NULL rows, defeating the LEFT JOIN.",
    level: "moderate"
  },
  {
    question: "How do you prevent an INNER JOIN from cancelling an earlier LEFT JOIN in a multi-table chain?",
    shortAnswer: "By using consistent `LEFT JOIN`s across all subsequent child tables in the chain (or wrapping the inner join in a subquery).",
    explanation: "Maintaining outer join preservation in multi-table queries.",
    hint: "Use consistent LEFT JOINs across the entire chain.",
    level: "moderate"
  },
  {
    question: "In academy management, write a 4-table join connecting `students`, `enrollments`, `courses`, and `instructors`.",
    shortAnswer: "`SELECT s.name, c.title, i.name FROM students s JOIN enrollments e ON s.id = e.student_id JOIN courses c ON e.course_id = c.id JOIN instructors i ON c.instructor_id = i.id;`",
    explanation: "Academy 4-table join syntax.",
    hint: "Chain 3 JOIN clauses connecting the 4 tables.",
    level: "basic"
  },
  {
    question: "Why are unique table aliases essential when joining 4 or more tables?",
    shortAnswer: "To keep SQL queries readable, concise, and prevent 'Column is ambiguous' errors when multiple tables contain columns like `id`, `name`, or `created_at`.",
    explanation: "Table aliasing in multi-table queries.",
    hint: "Prevents column ambiguity and keeps queries readable.",
    level: "basic"
  },
  {
    question: "What system variable in MySQL controls the depth of the optimizer's search for the best join order?",
    shortAnswer: "`optimizer_search_depth`.",
    explanation: "MySQL optimizer search depth variable.",
    hint: "optimizer_search_depth.",
    level: "expert"
  },
  {
    question: "What happens if a query joins 15 tables and `optimizer_search_depth` is set to 0 (automatic)?",
    shortAnswer: "MySQL uses heuristics to limit the search space, preventing the query compiler from spending seconds evaluating all $15!$ permutations.",
    explanation: "Query optimization heuristics for high table counts.",
    hint: "Uses heuristics to avoid evaluating factorial permutations.",
    level: "expert"
  },
  {
    question: "What index strategy should be implemented for high-speed multi-table joins?",
    shortAnswer: "Every Foreign Key column in the join chain must have a dedicated single-column or composite B-Tree index.",
    explanation: "Foreign key indexing for multi-table joins.",
    hint: "Index all foreign key columns in the join chain.",
    level: "basic"
  },
  {
    question: "In healthcare, how do you join `patients`, `appointments`, `doctors`, and `departments`?",
    shortAnswer: "`SELECT p.name, d.name, dept.name FROM patients p JOIN appointments a ON p.id = a.patient_id JOIN doctors d ON a.doc_id = d.id JOIN departments dept ON d.dept_id = dept.id;`",
    explanation: "Healthcare 4-table join chain.",
    hint: "Chain appointments to doctors and departments.",
    level: "basic"
  },
  {
    question: "How does placing a `WHERE` filter early affect multi-table join performance?",
    shortAnswer: "It reduces the cardinality of the driving table, dramatically shrinking the number of rows processed in subsequent join stages.",
    explanation: "Early row pruning in join pipelines.",
    hint: "Prunes intermediate rows early, speeding up subsequent joins.",
    level: "moderate"
  },
  {
    question: "What is an 'Intermediate Result Set' in a multi-table join?",
    shortAnswer: "The temporary row set produced by joining two tables before that result is passed into the next join stage in the pipeline.",
    explanation: "Definition of intermediate result sets.",
    hint: "The temporary row set created between join steps.",
    level: "basic"
  },
  {
    question: "Why should you avoid joining tables that are not needed in the `SELECT` or `WHERE` clauses?",
    shortAnswer: "Because each extra join consumes CPU, memory, and buffer pool pages, adding unnecessary latency to the query.",
    explanation: "Eliminating superfluous joins.",
    hint: "Unneeded joins waste CPU, memory, and buffer pool resources.",
    level: "basic"
  },
  {
    question: "In banking, write a query joining `customers`, `accounts`, `transactions`, and `branches`.",
    shortAnswer: "`SELECT c.name, a.acc_no, t.amount, b.branch_name FROM customers c JOIN accounts a ON c.id = a.cust_id JOIN transactions t ON a.acc_no = t.acc_no JOIN branches b ON a.branch_id = b.id;`",
    explanation: "Banking 4-table join syntax.",
    hint: "Customers ➔ Accounts ➔ Transactions and Branches.",
    level: "basic"
  },
  {
    question: "Can a multi-table join combine `INNER JOIN`, `LEFT JOIN`, and a `SELF JOIN` in the same query?",
    shortAnswer: "YES. Complex enterprise queries frequently combine multiple join types in a single statement.",
    explanation: "Combining heterogeneous join types.",
    hint: "Yes, heterogeneous join types can be combined.",
    level: "moderate"
  },
  {
    question: "What is the maximum number of tables that can be joined in a single MySQL query?",
    shortAnswer: "61 tables (MySQL architectural limit).",
    explanation: "MySQL maximum join table limit.",
    hint: "61 tables.",
    level: "expert"
  },
  {
    question: "What is the 'Star Schema' join pattern in data warehousing?",
    shortAnswer: "A centralized Fact table joined outwards to multiple independent Dimension tables (e.g. `fact_sales` joined to `dim_date`, `dim_customer`, `dim_product`).",
    explanation: "Star schema multi-table joins.",
    hint: "Central Fact table joined to multiple Dimension tables.",
    level: "moderate"
  },
  {
    question: "What is the 'Snowflake Schema' join pattern?",
    shortAnswer: "A star schema where dimension tables are further normalized into sub-dimension tables, requiring multi-level chained joins (e.g. `dim_product ➔ dim_category ➔ dim_department`).",
    explanation: "Snowflake schema normalized multi-table joins.",
    hint: "Normalized dimension hierarchies in data warehouses.",
    level: "moderate"
  },
  {
    question: "How can you verify the join order chosen by MySQL for a 5-table query?",
    shortAnswer: "Run `EXPLAIN SELECT ...` and inspect the top-to-bottom order of tables listed in the output table column.",
    explanation: "Inspecting join order with EXPLAIN.",
    hint: "Check EXPLAIN output table order from top to bottom.",
    level: "basic"
  },
  {
    question: "What does the `STRAIGHT_JOIN` modifier do when used in a multi-table query?",
    shortAnswer: "It forces the query optimizer to join the tables in the exact order they are listed in the `FROM` clause, bypassing optimizer reordering.",
    explanation: "STRAIGHT_JOIN in multi-table queries.",
    hint: "Forces MySQL to join tables in the exact written order.",
    level: "expert"
  },
  {
    question: "In logistics, write a join chain connecting `shipments`, `carriers`, `routes`, and `destinations`.",
    shortAnswer: "`SELECT s.id, c.name, r.distance, d.city FROM shipments s JOIN carriers c ON s.carrier_id = c.id JOIN routes r ON s.route_id = r.id JOIN destinations d ON r.dest_id = d.id;`",
    explanation: "Logistics 4-table join chain.",
    hint: "Shipments ➔ Carriers and Routes ➔ Destinations.",
    level: "basic"
  },
  {
    question: "Why can multi-table joins on unindexed columns cause severe performance degradation?",
    shortAnswer: "Because each unindexed step multiplies table scan overhead, escalating query latency exponentially.",
    explanation: "Unindexed multi-table join latency explosion.",
    hint: "Full table scans at each step cause exponential slowdowns.",
    level: "basic"
  },
  {
    question: "How does `GROUP BY` interact with a multi-table join?",
    shortAnswer: "The database joins all tables first to form the unified intermediate dataset, then groups the rows and calculates aggregates.",
    explanation: "Order of operations: Join then Group.",
    hint: "Joins are evaluated before grouping and aggregation.",
    level: "basic"
  },
  {
    question: "In academy reporting, how do you calculate total tuition fees collected per instructor across 4 joined tables?",
    shortAnswer: "`SELECT i.instructor_name, SUM(p.amount) FROM instructors i JOIN courses c ON i.id = c.instructor_id JOIN enrollments e ON c.id = e.course_id JOIN payments p ON e.id = p.enrollment_id GROUP BY i.id, i.instructor_name;`",
    explanation: "4-table revenue aggregation by instructor.",
    hint: "Join instructors to courses, enrollments, payments with SUM(p.amount) and GROUP BY.",
    level: "moderate"
  },
  {
    question: "What is a 'Junction Table' (Bridge Table) in a multi-table join?",
    shortAnswer: "An intermediate table used to resolve a many-to-many relationship by holding foreign keys referencing two parent tables (e.g. `student_courses`).",
    explanation: "Definition of junction table in multi-table joins.",
    hint: "An intermediate table resolving M:N relationships.",
    level: "basic"
  },
  {
    question: "When joining a parent table, a junction table, and a child table, what is the standard join pattern?",
    shortAnswer: "`FROM ParentA p JOIN Junction j ON p.id = j.parent_id JOIN ChildB c ON j.child_id = c.id;`",
    explanation: "Standard junction table join pattern.",
    hint: "Parent ➔ Junction ➔ Child.",
    level: "basic"
  },
  {
    question: "How do database views help manage complex 5-table joins in production?",
    shortAnswer: "By encapsulating the complex join query into a reusable virtual table, simplifying application code and enhancing security.",
    explanation: "Encapsulating multi-table joins in views.",
    hint: "Encapsulates complex join SQL into reusable virtual tables.",
    level: "basic"
  },
  {
    question: "What is the risk of selecting columns from all 5 tables using `SELECT *` in a multi-table join?",
    shortAnswer: "It transfers redundant foreign keys and all non-essential columns across the network, wasting RAM and network bandwidth.",
    explanation: "SELECT * hazards in multi-table joins.",
    hint: "Wastes bandwidth and memory by transferring duplicate and unnecessary columns.",
    level: "basic"
  },
  {
    question: "What is the ultimate takeaway for database engineers regarding Multi-Table Joins?",
    shortAnswer: "Multi-table joins connect normalized relational data across the enterprise; always qualify columns with clear aliases, maintain index coverage on every foreign key, and beware of mixing INNER and LEFT joins improperly.",
    explanation: "Final summary conclusion for Topic 7 in Module 5.",
    hint: "Connects normalized tables; use descriptive aliases, index foreign keys, and maintain outer join consistency.",
    level: "basic"
  }
];

export default questions;
