// topic4_questions.js
// 30 FAQs on "Operator Precedence" – basic to expert.

const questions = [
  {
    question: "What is operator precedence?",
    shortAnswer: "It defines the order in which operators are evaluated in an expression.",
    explanation: "Operators with higher precedence are evaluated before those with lower precedence. For example, multiplication is evaluated before addition.",
    hint: "Think of it like the order of operations in maths.",
    level: "basic",
    codeExample: "int result = 5 + 3 * 2; // 11, not 16",
  },
  {
    question: "Which operators have the highest precedence in Java?",
    shortAnswer: "Postfix operators (`++` and `--`) have the highest precedence.",
    explanation: "They are followed by prefix operators, then multiplicative, additive, etc.",
    hint: "Postfix increment/decrement bind the tightest.",
    level: "basic",
    codeExample: "int i = 5; int j = i++ + 2; // i++ evaluated first",
  },
  {
    question: "What is the precedence of `*` versus `+`?",
    shortAnswer: "`*` has higher precedence than `+`.",
    explanation: "So `a + b * c` is evaluated as `a + (b * c)`.",
    hint: "Multiplication is done before addition.",
    level: "basic",
    codeExample: "int x = 2 + 3 * 4; // 14",
  },
  {
    question: "How do you override precedence?",
    shortAnswer: "Use parentheses `()` to group sub‑expressions.",
    explanation: "Parentheses have the highest precedence, so anything inside them is evaluated first.",
    hint: "They let you force a specific order.",
    level: "basic",
    codeExample: "int x = (2 + 3) * 4; // 20",
  },
  {
    question: "What is the precedence of logical `&&` versus `||`?",
    shortAnswer: "`&&` has higher precedence than `||`.",
    explanation: "So `a || b && c` is `a || (b && c)`.",
    hint: "AND is like multiplication, OR like addition.",
    level: "intermediate",
    codeExample: "boolean b = true || false && false; // true",
  },
  {
    question: "What is the precedence of relational operators compared to logical?",
    shortAnswer: "Relational operators (`>`, `<`, `==`, etc.) have higher precedence than logical operators (`&&`, `||`).",
    explanation: "So `a > b && c < d` is `(a > b) && (c < d)`.",
    hint: "Comparisons are done before logical connections.",
    level: "intermediate",
    codeExample: "if (age >= 18 && hasLicense) { }",
  },
  {
    question: "What is the associativity of most operators?",
    shortAnswer: "Most binary operators are left‑associative (evaluated left to right).",
    explanation: "For example, `a - b - c` is `(a - b) - c`.",
    hint: "Left to right for same precedence.",
    level: "basic",
    codeExample: "int x = 10 - 3 - 2; // (10-3)-2 = 5",
  },
  {
    question: "Which operators are right‑associative?",
    shortAnswer: "Assignment operators (`=`, `+=`, etc.) and the ternary operator (`? :`) are right‑associative.",
    explanation: "Also, prefix unary operators are right‑associative.",
    hint: "They bind from right to left.",
    level: "intermediate",
    codeExample: "int a = b = c = 5; // c=5, b=c, a=b",
  },
  {
    question: "What is the precedence of `instanceof`?",
    shortAnswer: "`instanceof` has higher precedence than `==` and `!=`, but lower than relationals.",
    explanation: "It is used for type checking.",
    hint: "It's between relational and equality.",
    level: "intermediate",
    codeExample: "if (obj instanceof String == true) { } // ok, but better with parentheses",
  },
  {
    question: "What is the precedence of the ternary operator?",
    shortAnswer: "It has lower precedence than logical OR (`||`) but higher than assignment.",
    explanation: "It's often used with parentheses to avoid confusion.",
    hint: "It's the only ternary operator.",
    level: "intermediate",
    codeExample: "int max = (a > b) ? a : b;",
  },
  {
    question: "What is the lowest precedence operator?",
    shortAnswer: "Assignment operators have the lowest precedence.",
    explanation: "This ensures the right side is fully evaluated before assignment.",
    hint: "Assignment is last.",
    level: "basic",
    codeExample: "int x = 5 + 3 * 2; // multiplication first, then addition, then assignment",
  },
  {
    question: "What is the effect of `&` vs `&&` precedence?",
    shortAnswer: "`&` has higher precedence than `&&`, but both are lower than equality and relational.",
    explanation: "They are used for bitwise and logical (non‑short‑circuit) operations.",
    hint: "`&` is higher in the table.",
    level: "advanced",
    codeExample: "// Precedence: & > ^ > | > && > ||",
  },
  {
    question: "What does precedence determine?",
    shortAnswer: "It determines which operands are grouped with which operators.",
    explanation: "For example, `a + b * c` groups `b` with `*` first.",
    hint: "It's about binding.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "Can parentheses change the result of an expression?",
    shortAnswer: "Yes, they can override precedence and change the evaluation order, leading to different results.",
    explanation: "Example: `(5 + 3) * 2` vs `5 + (3 * 2)`.",
    hint: "Try it and see.",
    level: "basic",
    codeExample: "System.out.println((5+3)*2); // 16\nSystem.out.println(5+(3*2)); // 11",
  },
  {
    question: "What is the precedence of shift operators?",
    shortAnswer: "Shift operators (`<<`, `>>`, `>>>`) have higher precedence than relational and lower than additive.",
    explanation: "They are used for bit shifting.",
    hint: "They come after additive.",
    level: "advanced",
    codeExample: "int y = 8 << 2 + 1; // 8 << 3 = 64 (since + has higher precedence)",
  },
  {
    question: "What is the precedence of unary operators?",
    shortAnswer: "Unary operators have very high precedence, just after postfix operators.",
    explanation: "This means they apply to the immediate operand.",
    hint: "They bind tightly.",
    level: "basic",
    codeExample: "int a = -5 + 3; // (-5) + 3 = -2",
  },
  {
    question: "How does precedence affect `if` conditions?",
    shortAnswer: "It determines how the condition is parsed. For example, `if (a > b && c < d)` is parsed as `(a > b) && (c < d)`.",
    explanation: "Relational operators have higher precedence than logical, so they are evaluated first.",
    hint: "Use parentheses to be explicit.",
    level: "intermediate",
    codeExample: "if (age >= 18 && hasLicense) { } // safe",
  },
  {
    question: "What is the precedence of `+` for strings?",
    shortAnswer: "String concatenation `+` has the same precedence as numeric addition (additive).",
    explanation: "It's a binary operator with the same precedence level.",
    hint: "It's overloaded but precedence is unchanged.",
    level: "intermediate",
    codeExample: "String s = \"Hello\" + 5 + 3; // \"Hello53\" because left‑associative",
  },
  {
    question: "What is the associativity of `+` and `-`?",
    shortAnswer: "They are left‑associative.",
    explanation: "So `a - b + c` is `(a - b) + c`.",
    hint: "Left to right.",
    level: "basic",
    codeExample: "int x = 10 - 3 + 2; // 9",
  },
  {
    question: "What is the precedence of `^` (XOR)?",
    shortAnswer: "It has lower precedence than `&` but higher than `|`.",
    explanation: "It's a bitwise operator.",
    hint: "Order: &, ^, |.",
    level: "advanced",
    codeExample: "int result = 0b1010 ^ 0b1100;",
  },
  {
    question: "What is the effect of precedence on readability?",
    shortAnswer: "Complex precedence can reduce readability; using parentheses improves clarity.",
    explanation: "Even if you know precedence, other readers may not.",
    hint: "Write for humans, not the compiler.",
    level: "intermediate",
    codeExample: "// Use (a + b) * c instead of a + b * c if that's what you mean",
  },
  {
    question: "How does precedence affect compound assignments?",
    shortAnswer: "Compound assignments have low precedence, so the right side is evaluated first.",
    explanation: "Example: `x *= 2 + 3` is `x = x * (2 + 3)` because `+` has higher precedence than `*=`.",
    hint: "The right side is evaluated first.",
    level: "intermediate",
    codeExample: "int x = 5; x *= 2 + 3; // x becomes 25 (5 * 5)",
  },
  {
    question: "What is the precedence of cast `(type)`?",
    shortAnswer: "Cast has very high precedence, just after unary operators.",
    explanation: "It applies to the immediate operand.",
    hint: "It's used to convert types.",
    level: "intermediate",
    codeExample: "double d = (double) 5 / 2; // (double)5 / 2 = 2.5",
  },
  {
    question: "What is the precedence of `!`?",
    shortAnswer: "`!` (logical NOT) has high precedence, just after unary minus.",
    explanation: "It applies to the following boolean expression.",
    hint: "It's a unary operator.",
    level: "basic",
    codeExample: "boolean b = !false; // true",
  },
  {
    question: "What is the precedence of `++` and `--`?",
    shortAnswer: "Postfix `++` and `--` have the highest precedence; prefix have slightly lower (same as unary).",
    explanation: "Postfix binds tighter than prefix.",
    hint: "Postfix first, then prefix.",
    level: "basic",
    codeExample: "int i = 5; int j = i++ + ++i; // complex, avoid",
  },
  {
    question: "What is the precedence of `?:` vs `=`?",
    shortAnswer: "Ternary (`?:`) has higher precedence than assignment, so `int x = a > b ? a : b;` is fine.",
    explanation: "Assignment is lower, so the ternary evaluates fully before assignment.",
    hint: "The ternary is higher.",
    level: "intermediate",
    codeExample: "int max = a > b ? a : b; // works as expected",
  },
  {
    question: "What are the consequences of wrong precedence?",
    shortAnswer: "It leads to logic errors that may not be obvious and can cause incorrect results.",
    explanation: "Such bugs are often hard to find.",
    hint: "Use parentheses to avoid.",
    level: "intermediate",
    codeExample: "// if (x = 5) is a common bug",
  },
  {
    question: "How do you memorize precedence?",
    shortAnswer: "You don't need to—use parentheses and rely on the compiler; the table is available.",
    explanation: "Professionals often refer to the table when needed.",
    hint: "Don't waste brain cycles memorizing; use parentheses.",
    level: "basic",
    codeExample: "// Use parentheses for clarity",
  },
  {
    question: "What is the precedence of `||` vs `|`?",
    shortAnswer: "`|` has higher precedence than `||`.",
    explanation: "So `a | b && c` is parsed as `(a | b) && c` if `&&` is higher, but actually `&&` is higher than `|`, so careful.",
    hint: "Check the table: `&` > `^` > `|` > `&&` > `||`.",
    level: "advanced",
    codeExample: "boolean result = true | false && false; // (true | false) && false = true && false = false",
  },
  {
    question: "What is the precedence of `~` and `-`?",
    shortAnswer: "`~` and unary minus have the same precedence (unary).",
    explanation: "They are evaluated right‑to‑left.",
    hint: "Both are unary.",
    level: "advanced",
    codeExample: "int result = ~ -5; // ~(-5) = 4",
  },
];

export default questions;