// topic7_questions.js
// 30 FAQs on "Types of Expressions" – basic to expert.

const questions = [
  {
    question: "What are the three types of expressions?",
    shortAnswer: "Infix, prefix, and postfix.",
    explanation: "They differ by the position of the operator relative to the operands.",
    hint: "Operator position.",
    level: "basic",
    codeExample: "Infix: A+B; Prefix: +AB; Postfix: AB+",
  },
  {
    question: "What is an infix expression?",
    shortAnswer: "An expression where the operator is placed between the operands.",
    explanation: "This is the standard notation used in mathematics and most programming languages.",
    hint: "A + B.",
    level: "basic",
    codeExample: "A + B, A * (B + C)",
  },
  {
    question: "What is a prefix expression?",
    shortAnswer: "An expression where the operator is placed before the operands.",
    explanation: "Also called Polish notation; no parentheses needed.",
    hint: "+ A B.",
    level: "basic",
    codeExample: "+ A B, * A + B C",
  },
  {
    question: "What is a postfix expression?",
    shortAnswer: "An expression where the operator is placed after the operands.",
    explanation: "Also called Reverse Polish Notation (RPN); stack‑friendly.",
    hint: "A B +.",
    level: "basic",
    codeExample: "A B +, A B C + *",
  },
  {
    question: "Why is infix easier for humans?",
    shortAnswer: "Because it matches natural mathematical notation and is intuitive.",
    explanation: "We are trained from a young age to read expressions with operators between operands.",
    hint: "It's what we learn in school.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "Why is prefix/postfix easier for computers?",
    shortAnswer: "They are unambiguous, require no precedence rules or parentheses, and can be evaluated with a stack.",
    explanation: "The evaluation order is explicit from the position of operators.",
    hint: "They are machine‑friendly.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What is the difference between prefix and postfix?",
    shortAnswer: "Prefix has the operator before operands; postfix has it after.",
    explanation: "They are symmetric notations.",
    hint: "Pre‑ vs post‑.",
    level: "basic",
    codeExample: "Prefix: + A B; Postfix: A B +",
  },
  {
    question: "Does prefix require parentheses?",
    shortAnswer: "No, prefix does not require parentheses because the order is determined by the positions.",
    explanation: "The operator position makes the grouping explicit.",
    hint: "No parentheses needed.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "Does postfix require parentheses?",
    shortAnswer: "No, postfix also does not require parentheses.",
    explanation: "The operator follows the operands, so the grouping is clear.",
    hint: "No parentheses needed.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What is the advantage of infix?",
    shortAnswer: "It's readable and familiar to humans.",
    explanation: "It's the standard notation in textbooks and everyday use.",
    hint: "Human‑friendly.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What is the advantage of prefix?",
    shortAnswer: "It's easy to parse and doesn't need precedence rules.",
    explanation: "It's used in languages like Lisp.",
    hint: "Machine‑friendly.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What is the advantage of postfix?",
    shortAnswer: "It's stack‑based and efficient, used in calculators and some languages.",
    explanation: "Evaluation is a simple linear scan with a stack.",
    hint: "Stack‑friendly.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "Can you mix notations in one expression?",
    shortAnswer: "No, an expression uses one consistent notation.",
    explanation: "Mixed notations would be ambiguous.",
    hint: "Stick to one.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "How do you identify the type of an expression?",
    shortAnswer: "Look at the position of the operator relative to operands.",
    explanation: "If between → infix; before → prefix; after → postfix.",
    hint: "Operator position is key.",
    level: "basic",
    codeExample: "A+B → infix; +AB → prefix; AB+ → postfix",
  },
  {
    question: "What is the relationship between infix and prefix/postfix?",
    shortAnswer: "They are equivalent notations; one can be converted to another.",
    explanation: "Conversion changes the position of operators while preserving the meaning.",
    hint: "They are translatable.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What is the role of parentheses in infix?",
    shortAnswer: "They override the default precedence and explicitly group sub‑expressions.",
    explanation: "In prefix/postfix, parentheses are not needed.",
    hint: "Parentheses are for grouping.",
    level: "basic",
    codeExample: "(A+B)*C vs A+B*C",
  },
  {
    question: "What is the role of operator precedence in infix?",
    shortAnswer: "It defines the implicit order of evaluation when multiple operators are present without parentheses.",
    explanation: "Infix relies on precedence to resolve ambiguity.",
    hint: "Precedence rules.",
    level: "basic",
    codeExample: "A+B*C → A+(B*C)",
  },
  {
    question: "Are prefix and postfix affected by precedence?",
    shortAnswer: "No, because the order is explicit from the position of operators.",
    explanation: "There's no ambiguity, so precedence is irrelevant.",
    hint: "No precedence needed.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What is the significance of the operator position?",
    shortAnswer: "It determines the evaluation order and the notation type.",
    explanation: "The position tells us how to parse and evaluate the expression.",
    hint: "Position is everything.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "Why is postfix called Reverse Polish Notation?",
    shortAnswer: "Because it's the reverse of Polish (prefix) notation.",
    explanation: "The term 'Reverse' indicates the operator is moved to the end.",
    hint: "It's the reverse order.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What are some examples of prefix languages?",
    shortAnswer: "Lisp dialects (Scheme, Common Lisp) use prefix notation.",
    explanation: "In Lisp, all expressions are written in prefix form.",
    hint: "Lisp is the classic example.",
    level: "intermediate",
    codeExample: "(+ 2 3) → 5",
  },
  {
    question: "What are some examples of postfix languages?",
    shortAnswer: "Forth, PostScript, and some calculators use postfix.",
    explanation: "These are stack‑based languages.",
    hint: "Forth and PostScript.",
    level: "intermediate",
    codeExample: "2 3 + . → 5",
  },
  {
    question: "Can you evaluate prefix directly without conversion?",
    shortAnswer: "Yes, by scanning right‑to‑left and using a stack.",
    explanation: "It's symmetric to postfix evaluation.",
    hint: "Scan from the right.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "Is infix less efficient for machines?",
    shortAnswer: "Yes, because it requires more complex parsing with precedence and parentheses.",
    explanation: "Machines prefer simpler, unambiguous notations.",
    hint: "More complex.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What is the stack requirement for postfix evaluation?",
    shortAnswer: "A single stack for operands.",
    explanation: "Push operands, pop two when an operator appears, push result.",
    hint: "One stack.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What is the stack requirement for prefix evaluation?",
    shortAnswer: "A single stack for operands, scanning from right to left.",
    explanation: "Push operands, pop two when an operator appears, push result.",
    hint: "One stack, right‑to‑left.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "Can all infix expressions be converted to prefix/postfix?",
    shortAnswer: "Yes, every infix expression has an equivalent prefix and postfix form.",
    explanation: "The conversion is well‑defined.",
    hint: "It's always possible.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What is the importance of understanding these types?",
    shortAnswer: "It's essential for compiler design, expression evaluation, and understanding of programming languages.",
    explanation: "It's a fundamental computer science concept.",
    hint: "It's foundational.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "Which notation is used in most calculators?",
    shortAnswer: "Many scientific calculators use postfix (RPN), but simple calculators use infix.",
    explanation: "RPN calculators are popular for their efficiency.",
    hint: "Some use RPN.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What is the main disadvantage of prefix/postfix for humans?",
    shortAnswer: "They are less intuitive and harder to read, especially for complex expressions.",
    explanation: "Humans are trained to read infix, so prefix/postfix can be confusing.",
    hint: "Not human‑friendly.",
    level: "basic",
    codeExample: "Not applicable",
  },
];

export default questions;