// topic5_files/topic5_questions.js

const questions = [
  {
    question: "What is the core principle of Write-Ahead Logging (WAL) in InnoDB?",
    shortAnswer: "A transaction's physical modifications must be written and persisted to the sequential **Redo Log** on disk *before* the dirty data pages in the Buffer Pool are written to random sectors in disk tablespaces.",
    explanation: "Allows fast sequential disk I/O to guarantee Durability without waiting for slow random disk writes.",
    hint: "Sequential redo logging must occur before random disk page flushing.",
    level: "basic"
  },
  {
    question: "Why is appending to the Redo Log significantly faster than writing dirty pages directly to tablespaces?",
    shortAnswer: "Because the Redo Log uses **pure sequential I/O** (appending small byte records to contiguous log blocks), whereas flushing dirty pages requires **random I/O** (writing 16KB blocks across disparate disk locations).",
    explanation: "Sequential disk writes achieve orders of magnitude higher throughput than random writes.",
    hint: "Sequential I/O is drastically faster than random 16KB disk page writes.",
    level: "basic"
  },
  {
    question: "What is the Log Sequence Number (LSN) and how is it measured?",
    shortAnswer: "A monotonically increasing 64-bit integer representing the cumulative count of redo log bytes generated by InnoDB since the database was initialized.",
    explanation: "Every modification increments the LSN by the exact byte length of its redo record.",
    hint: "Monotonically increasing 64-bit integer tracking total cumulative redo log bytes.",
    level: "expert"
  },
  {
    question: "What are the four key LSN milestones displayed in `SHOW ENGINE INNODB STATUS`?",
    shortAnswer: "1) **Log sequence number** (current LSN in memory), 2) **Log flushed up to** (LSN written to redo log on disk), 3) **Pages flushed up to** (oldest dirty page LSN flushed), and 4) **Last checkpoint at** (LSN of the safe checkpoint boundary).",
    explanation: "These four markers track the flow of data from memory to disk logs and tablespaces.",
    hint: "Log sequence number, Log flushed up to, Pages flushed up to, and Last checkpoint at.",
    level: "expert"
  },
  {
    question: "What is 'Checkpoint Age' in InnoDB?",
    shortAnswer: "The mathematical difference between the current **Log Sequence Number** and the **Last Checkpoint LSN** (`Checkpoint Age = Current LSN - Checkpoint LSN`), representing the volume of uncheckpointed redo logs.",
    explanation: "Tracks how close the circular redo log ring is to filling up.",
    hint: "The difference between Current LSN and Last Checkpoint LSN.",
    level: "expert"
  },
  {
    question: "What happens if Checkpoint Age reaches the maximum capacity of the Redo Log files?",
    shortAnswer: "InnoDB enters **Synchronous Flush Throttling**: it halts or severely throttles client write transactions until background Page Cleaners can flush dirty pages to disk and advance the Checkpoint LSN.",
    explanation: "Prevents uncheckpointed redo log records from being overwritten in the circular ring.",
    hint: "Halts client writes and forces synchronous page flushing to prevent log overwriting.",
    level: "expert"
  },
  {
    question: "What are the three sequential steps of the InnoDB Crash Recovery process upon server restart?",
    shortAnswer: "1) **Doublewrite Verification** (restores any torn 16KB pages), 2) **Redo Log Roll-Forward** (replays committed changes from Checkpoint LSN to end of log into memory), and 3) **Undo Log Roll-Back** (rolls back active uncommitted transactions).",
    explanation: "Guarantees complete ACID consistency after an unexpected server crash or power failure.",
    hint: "Doublewrite torn page fix → Redo roll-forward → Undo roll-back.",
    level: "expert"
  },
  {
    question: "How is Redo Log capacity configured dynamically in MySQL 8.0.30+?",
    shortAnswer: "Via `SET GLOBAL innodb_redo_log_capacity = SIZE;` (e.g. `SET GLOBAL innodb_redo_log_capacity = 17179869184;` for 16 GB), which manages dynamic redo log files in the `#innodb_redo` directory online without restarting.",
    explanation: "Replaced the legacy static `innodb_log_file_size` and `innodb_log_files_in_group` settings.",
    hint: "Configured online via SET GLOBAL innodb_redo_log_capacity = ...;",
    level: "basic",
    codeExample: "SET GLOBAL innodb_redo_log_capacity = 8589934592; -- 8 GB Redo Log Capacity"
  },
  {
    question: "What is the difference between the Redo Log and the Binary Log (Binlog)?",
    shortAnswer: "- **Redo Log**: Storage-engine-specific (InnoDB), physical page changes, circular fixed size, used exclusively for **Crash Recovery**.\n- **Binary Log**: Server-layer universal, logical SQL events/row changes, sequential grow-only, used for **Replication** and **Point-in-Time Recovery**.",
    explanation: "Redo log recovers the local engine on crash; binlog replicates changes to replicas.",
    hint: "Redo log = InnoDB physical crash recovery; Binlog = Server-layer replication and point-in-time recovery.",
    level: "basic"
  },
  {
    question: "What is 'Two-Phase Commit' (2PC) between the Redo Log and the Binary Log?",
    shortAnswer: "A coordination protocol (Prepare → Write Binlog → Commit) ensuring that transaction changes in the InnoDB Redo Log and the MySQL Binary Log remain 100% synchronized, preventing replication desync on crash.",
    explanation: "Guarantees consistency between local storage engine and replication stream.",
    hint: "Coordinates Redo Log and Binlog commit states to prevent replication desynchronization.",
    level: "expert"
  },
  {
    question: "What is a 'Torn Page' and how does InnoDB detect it during crash recovery?",
    shortAnswer: "A corrupted 16KB page that was only partially written (e.g. only 4KB written) to disk when a power outage occurred; InnoDB detects it via checksum mismatch in the page header/trailer.",
    explanation: "Torn pages are repaired using the intact copy in the Doublewrite Buffer.",
    hint: "A partially written 16KB page caused by power loss during disk write.",
    level: "basic"
  },
  {
    question: "What does the `innodb_force_recovery` parameter do, and when should it be used?",
    shortAnswer: "An emergency troubleshooting parameter (levels 1 to 6) that forces InnoDB to start in read-only degraded mode during catastrophic disk corruption, allowing DBAs to dump data (`mysqldump`).",
    explanation: "Emergency disaster recovery tool; should never be left enabled in normal production.",
    hint: "Emergency parameter (values 1-6) to start InnoDB in degraded mode for disaster data export.",
    level: "expert"
  },
  {
    question: "Why does a large Redo Log capacity improve write performance during traffic spikes?",
    shortAnswer: "Because it allows a larger 'Checkpoint Age', enabling InnoDB to buffer more dirty pages in RAM during write bursts without triggering synchronous write throttling.",
    explanation: "Smoothes out I/O spikes by decoupling write bursts from immediate disk flushing.",
    hint: "Allows buffering write bursts in memory without triggering synchronous flush stalls.",
    level: "basic"
  },
  {
    question: "What is the trade-off of having an extremely large Redo Log capacity (e.g. 64 GB)?",
    shortAnswer: "Longer **Crash Recovery Duration** upon server restart, because InnoDB must scan and replay a larger volume of uncheckpointed redo log records from disk into memory.",
    explanation: "Balancing peak write performance against acceptable MTTR (Mean Time to Recover).",
    hint: "Increases crash recovery startup time because more uncheckpointed redo logs must be replayed.",
    level: "expert"
  },
  {
    question: "How do you calculate how many megabytes of Redo Log are generated per minute in your database?",
    shortAnswer: "Record `Innodb_os_log_written` from `SHOW GLOBAL STATUS`, wait 60 seconds, record it again, and compute: `(Val2 - Val1) / (1024 * 1024)` MB/min.",
    explanation: "Essential calculation for properly sizing redo log capacity.",
    hint: "Measure delta in Innodb_os_log_written over a 60-second window.",
    level: "basic",
    codeExample: "SHOW GLOBAL STATUS LIKE 'Innodb_os_log_written';\n-- Wait 60s and re-run to measure write throughput in bytes"
  },
  {
    question: "What happens during the 'Redo Log Roll-Forward' phase of crash recovery?",
    shortAnswer: "InnoDB starts at the Last Checkpoint LSN, reads all physical redo log records up to the crash point, and reapplies all page modifications to 16KB frames in the Buffer Pool, restoring the state of all committed data.",
    explanation: "Brings the in-memory state of tablespaces up to the exact moment of the crash.",
    hint: "Reapplies all committed physical page changes from Checkpoint LSN to end of log.",
    level: "expert"
  },
  {
    question: "What happens during the 'Undo Log Roll-Back' phase of crash recovery?",
    shortAnswer: "InnoDB identifies all transactions that were active (uncommitted) when the crash occurred and traverses their Undo Log records to reverse their modifications, restoring tables to their pre-transaction state.",
    explanation: "Enforces ACID Atomicity by ensuring incomplete transactions leave no residual changes.",
    hint: "Reverses modifications made by incomplete, uncommitted transactions active during crash.",
    level: "expert"
  },
  {
    question: "What file naming convention is used for Redo Log files in MySQL 8.0.30+?",
    shortAnswer: "`#ib_redo*` files located in the `#innodb_redo` directory (e.g. `#ib_redo1`, `#ib_redo2`), dynamically created and destroyed by MySQL as capacity is resized.",
    explanation: "Replaced the legacy fixed-file `ib_logfile0` and `ib_logfile1` names.",
    hint: "#ib_redo* files in the #innodb_redo directory.",
    level: "basic"
  },
  {
    question: "Can `innodb_redo_log_capacity` be adjusted while transactions are actively executing?",
    shortAnswer: "Yes! MySQL 8.0.30+ automatically adjusts the number of `#ib_redo*` files in the background online without requiring a server restart or downtime.",
    explanation: "Zero-downtime storage capacity management.",
    hint: "Yes, fully dynamic and online in MySQL 8.0.30+.",
    level: "basic"
  },
  {
    question: "What is a 'Physiological' Redo Log Record?",
    shortAnswer: "A hybrid logging format where the record specifies a **physical page address** (tablespace ID and page number) combined with a **logical operation** description of the row modification within that page.",
    explanation: "Minimizes redo log size while guaranteeing deterministic physical page recovery.",
    hint: "Hybrid format specifying physical page address with logical row modification payload.",
    level: "expert"
  },
  {
    question: "What metric in `SHOW ENGINE INNODB STATUS` indicates that the database is experiencing Redo Log write stalls?",
    shortAnswer: "High wait times in the `SEMAPHORES` section, frequent `log wait` events, and `Checkpoint Age` hovering near `Redo Log Capacity`.",
    explanation: "Indicates that the redo log capacity is too small for the write workload.",
    hint: "Checkpoint Age approaching Redo Capacity and log wait semaphores in engine status.",
    level: "expert"
  },
  {
    question: "What is the recommended rule of thumb for sizing `innodb_redo_log_capacity`?",
    shortAnswer: "Size it to hold approximately **1 to 2 hours of peak write traffic** (e.g. if the system generates 10 GB of redo logs per hour during peak, set capacity to 16 GB - 20 GB).",
    explanation: "Ensures smooth background page flushing without synchronous flush stalls.",
    hint: "Capacity equal to 1 to 2 hours of peak write traffic volume.",
    level: "basic"
  },
  {
    question: "Why does InnoDB write Redo Logs in 512-byte blocks?",
    shortAnswer: "Because 512 bytes matches standard disk sector sizes, ensuring that individual log block writes are atomic and immune to torn sector corruption on most storage hardware.",
    explanation: "Guarantees atomic block write alignment.",
    hint: "512 bytes matches standard hardware disk sector size for atomic writes.",
    level: "expert"
  },
  {
    question: "What happens if you delete `#innodb_redo` log files manually while MySQL is stopped cleanly?",
    shortAnswer: "If shutdown was clean (Sharp Checkpoint at LSN 0 delta), MySQL will recreate new empty redo log files on startup; however, if the server crashed, deleting them causes **permanent unrecoverable data loss**!",
    explanation: "Never delete redo logs manually after an unexpected crash.",
    hint: "Safe only on clean shutdown; causes permanent data loss if server had crashed.",
    level: "expert"
  },
  {
    question: "How do you verify whether Redo Logging is currently enabled or disabled in MySQL 8.0?",
    shortAnswer: "`SHOW GLOBAL STATUS LIKE 'Innodb_redo_log_enabled';`",
    explanation: "Redo logging can be temporarily disabled (`ALTER INSTANCE DISABLE INNODB REDO_LOG`) during bulk initial data loading to accelerate ingestion.",
    hint: "SHOW GLOBAL STATUS LIKE 'Innodb_redo_log_enabled';",
    level: "basic",
    codeExample: "-- Temporarily disable redo log for initial bulk load (MySQL 8.0.21+):\nALTER INSTANCE DISABLE INNODB REDO_LOG;\n-- Load bulk dataset...\nALTER INSTANCE ENABLE INNODB REDO_LOG;"
  },
  {
    question: "Why must Redo Logging be RE-ENABLED immediately after a bulk data load?",
    shortAnswer: "Because with redo logging disabled, any unexpected server crash or power failure will leave the database in an unrecoverable state, requiring the entire instance to be re-initialized from backup.",
    explanation: "Disabling redo logging turns off crash recovery durability.",
    hint: "Without redo logging, the database cannot recover from an unexpected crash.",
    level: "basic"
  },
  {
    question: "What is the function of the `Log flushed up to` LSN marker?",
    shortAnswer: "It indicates the highest LSN byte position that has been successfully written and synced (`fsynced`) from the in-memory Log Buffer to the on-disk Redo Log files.",
    explanation: "Represents the boundary of durable transaction records.",
    hint: "The highest LSN written and synced from memory to disk redo logs.",
    level: "expert"
  },
  {
    question: "What role does the InnoDB Redo Log play in MySQL Master-Slave replication?",
    shortAnswer: "None directly! Replication relies on the **Binary Log**; the Redo Log operates purely at the local storage engine layer to protect local data pages from server crashes.",
    explanation: "Clean architectural separation between local crash recovery and distributed replication.",
    hint: "Redo log is for local crash recovery; replication uses the server-level Binary Log.",
    level: "basic"
  },
  {
    question: "How does InnoDB ensure that redo log records are not corrupted by silent storage bit-rot?",
    shortAnswer: "Every 512-byte redo log block includes a **CRC32 checksum** in its header and trailer, which InnoDB validates before replaying during crash recovery.",
    explanation: "Guarantees log integrity during crash replay.",
    hint: "Validates CRC32 checksums embedded in each 512-byte log block.",
    level: "expert"
  },
  {
    question: "What is the primary architectural takeaway of Topic 5 in Module 004_001?",
    shortAnswer: "Write-Ahead Logging (WAL) via the InnoDB Redo Log transforms expensive random disk page writes into fast sequential log appends, enabling maximum transactional throughput while guaranteeing 100% crash recovery via the 3-step pipeline (Doublewrite check → Redo roll-forward → Undo roll-back).",
    explanation: "Mastery of WAL and crash recovery is the cornerstone of enterprise database durability.",
    hint: "WAL enables RAM-speed transaction processing backed by crash-safe sequential durability.",
    level: "basic"
  }
];

export default questions;
