const questions = [
  {
    question: "What is ring topology?",
    shortAnswer: "A network topology where devices are connected in a circular loop.",
    explanation: "Each device connects to exactly two neighbors, forming a ring.",
    hint: "Think of a circle of devices.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "How does data travel in ring topology?",
    shortAnswer: "Data travels in one direction (or both in dual-ring) around the ring.",
    explanation: "Each device regenerates and forwards the signal to the next device.",
    hint: "Around and around in a circle.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a token in ring topology?",
    shortAnswer: "A special frame that circulates the ring, granting permission to transmit.",
    explanation: "Only the device holding the token can send data.",
    hint: "A permission slip to talk.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is Token Ring (IEEE 802.5)?",
    shortAnswer: "An early ring topology standard by IBM, using token passing.",
    explanation: "Operated at 4 Mbps or 16 Mbps over twisted pair, now obsolete.",
    hint: "A classic ring network.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is FDDI?",
    shortAnswer: "Fiber Distributed Data Interface – a dual-ring topology using fiber optics.",
    explanation: "Operated at 100 Mbps, used for backbone networks.",
    hint: "Fiber optic dual ring.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the advantage of a dual ring?",
    shortAnswer: "Fault tolerance – if one ring breaks, traffic reroutes on the other.",
    explanation: "Dual rings provide redundancy and high availability.",
    hint: "A backup path.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What happens if a single ring breaks?",
    shortAnswer: "The entire network goes down.",
    explanation: "In a single ring, a break breaks the communication path.",
    hint: "A broken circle.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the role of a repeater in ring topology?",
    shortAnswer: "A repeater regenerates signals to maintain quality over long distances.",
    explanation: "Each device acts as a repeater, forwarding signals to the next.",
    hint: "Signal booster.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the advantage of ring topology?",
    shortAnswer: "Deterministic performance – no collisions.",
    explanation: "Token passing ensures fair access and predictable delays.",
    hint: "No collisions, predictable.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the disadvantage of ring topology?",
    shortAnswer: "A single break brings down the network (without dual-ring).",
    explanation: "Adding or removing devices requires network disruption.",
    hint: "One break, everyone down.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is a MAU (Multistation Access Unit)?",
    shortAnswer: "A device used in Token Ring to connect nodes in a star-like physical layout.",
    explanation: "The logical topology is a ring; the physical topology is star.",
    hint: "Token Ring hub.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does token passing prevent collisions?",
    shortAnswer: "Only one device has the token at a time, so no two devices transmit simultaneously.",
    explanation: "The token circulates; a device must wait for the token to transmit.",
    hint: "Taking turns.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between Token Ring and Ethernet?",
    shortAnswer: "Token Ring uses token passing (deterministic); Ethernet uses CSMA/CD (contention-based).",
    explanation: "Token Ring is fair and predictable; Ethernet is simpler and more scalable.",
    hint: "One takes turns; the other listens then speaks.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the maximum length of a Token Ring network?",
    shortAnswer: "Limited by the number of devices and cable length, typically up to a few hundred meters.",
    explanation: "Token Ring uses twisted pair and has distance limits.",
    hint: "Not as long as fiber.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the maximum number of nodes in a Token Ring?",
    shortAnswer: "Up to 260 nodes per ring in Token Ring.",
    explanation: "The limit is due to signal attenuation and token rotation time.",
    hint: "A few hundred.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How does a dual ring recover from a break?",
    shortAnswer: "Traffic reroutes in the opposite direction around the break.",
    explanation: "The two rings form a folded ring, maintaining connectivity.",
    hint: "Going the other way.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is a ring beacon?",
    shortAnswer: "A special frame used in Token Ring to signal a fault or ring break.",
    explanation: "Beacons help in fault detection and recovery.",
    hint: "A distress signal.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the role of the active monitor in Token Ring?",
    shortAnswer: "The active monitor manages the token, detects failures, and handles ring recovery.",
    explanation: "One node is elected as the active monitor.",
    hint: "The ring manager.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the difference between a single ring and a dual ring?",
    shortAnswer: "Single ring has one path; dual ring has two paths in opposite directions.",
    explanation: "Dual ring provides fault tolerance and higher availability.",
    hint: "One vs. two circles.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "Why is ring topology less common today?",
    shortAnswer: "Star topology with switches offers better performance, scalability, and cost-effectiveness.",
    explanation: "Ethernet over twisted pair is simpler and supports higher speeds.",
    hint: "Switched Ethernet won.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the advantage of fiber optics in ring topology?",
    shortAnswer: "Fiber supports longer distances and higher speeds with lower attenuation.",
    explanation: "Fiber is used in FDDI and modern ring networks.",
    hint: "Long, fast, and clean.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the disadvantage of using a hub in Token Ring?",
    shortAnswer: "If the hub fails, the logical ring breaks.",
    explanation: "The physical star relies on the hub; the hub is a single point of failure.",
    hint: "The hub is critical.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does Token Ring handle priority?",
    shortAnswer: "By using priority bits in the token to allow higher-priority devices to transmit first.",
    explanation: "Priority levels ensure critical traffic gets preference.",
    hint: "VIP tokens.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the worst-case token rotation time?",
    shortAnswer: "The time it takes for the token to complete a full circle when all devices are transmitting.",
    explanation: "This determines maximum latency in Token Ring.",
    hint: "Guaranteed worst-case delay.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the benefit of deterministic access in ring topology?",
    shortAnswer: "Guaranteed maximum delay, suitable for real-time applications.",
    explanation: "Predictable performance is critical for voice and industrial control.",
    hint: "Know the max delay.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How does FDDI achieve high speed over long distances?",
    shortAnswer: "Using fiber optics and a dual-ring with 100 Mbps speed.",
    explanation: "FDDI was designed for backbone networks up to 100 km.",
    hint: "High-speed fiber ring.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is a ring failure recovery mechanism?",
    shortAnswer: "Dual-ring wrapping: traffic reroutes in the opposite direction.",
    explanation: "This creates a folded ring that bypasses the fault.",
    hint: "Go around the break.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the impact of node failure in a ring?",
    shortAnswer: "In a single ring, the node failure breaks the ring; in a dual ring, traffic reroutes.",
    explanation: "Node failure in single ring takes down the network.",
    hint: "One bad node, trouble.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How do you troubleshoot a ring network?",
    shortAnswer: "Use ring monitoring tools, check for beacons, and test with a ring analyzer.",
    explanation: "Isolate the break by checking each segment.",
    hint: "Find the break.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are the modern use cases for ring topology?",
    shortAnswer: "Industrial networks (PROFIBUS, EtherCAT) and some metro networks.",
    explanation: "Ring topology is still used in environments requiring deterministic performance.",
    hint: "Industrial and metro.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;