// topic1_questions.js
// CBSE Class XI Computer Science (083) - Topic 1 FAQs & Questions Bank
// Educator: Sukanta Hui (Coder & AccoTax, Barrackpore)

const questions = [
  {
    id: "q1",
    question: "What are the three fundamental components of a Central Processing Unit (CPU)?",
    answer: "The three fundamental components of a CPU are: (1) Arithmetic Logic Unit (ALU), (2) Control Unit (CU), and (3) Internal Registers (such as Accumulator, Program Counter, Instruction Register, MAR, and MDR).",
    explanation: "The ALU handles mathematical and logical processing, the CU directs the instruction flow and timing signals, and the internal registers provide ultra-fast temporary storage inside the CPU chip.",
    explanationBn: "CPU-র তিনটি মূল উপাদান হলো: ALU (গাণিতিক ও যৌক্তিক একক), CU (নিয়ন্ত্রণ একক), এবং অভ্যন্তরীণ রেজিস্টারসমূহ (যেমন Accumulator, PC, IR ইত্যাদি)।",
    category: "Concepts"
  },
  {
    id: "q2",
    question: "What is the specific role of the Program Counter (PC) register during program execution?",
    answer: "The Program Counter (PC) stores the memory address of the NEXT instruction to be fetched and executed. As soon as the current instruction address is passed to MAR, PC is automatically incremented to point to the subsequent instruction.",
    explanation: "When branch or jump instructions occur (such as if-else or loop constructs), the PC is updated with the target branch address instead of sequential incrementing.",
    explanationBn: "Program Counter (PC) পরবর্তী যে নির্দেশটি মেমোরি থেকে ফেচ করতে হবে তার মেমোরি অ্যাড্রেস ধরে রাখে এবং ফেচ হওয়ার সাথে সাথেই পরবর্তী নির্দেশের অ্যাড্রেসে স্বয়ংক্রিয়ভাবে বৃদ্ধি পায়।",
    category: "Registers"
  },
  {
    id: "q3",
    question: "Differentiate between the Memory Address Register (MAR) and Memory Data Register (MDR).",
    answer: "MAR holds the physical address in RAM that needs to be accessed, whereas MDR (or MBR) holds the actual data or instruction word being read from or written to that memory location.",
    explanation: "MAR connects directly to the unidirectional Address Bus, while MDR connects directly to the bidirectional Data Bus.",
    explanationBn: "MAR মেমোরির নির্দিষ্ট অ্যাড্রেস বা ঠিকানা নির্দেশ করে, আর MDR সেই নির্দিষ্ট মেমোরি অ্যাড্রেসে সংরক্ষিত আসল ডেটা বা নির্দেশ ধরে রাখে।",
    category: "Registers"
  },
  {
    id: "q4",
    question: "Why is the Control Unit (CU) often referred to as the 'supervisor' or 'orchestra conductor' of the computer?",
    answer: "Because the CU coordinates and directs all operations of the computer system by fetching, decoding instructions, and generating electrical timing and control signals without actually executing arithmetic operations itself.",
    explanation: "Just as an orchestra conductor doesn't play all the instruments but directs every musician on when and how to play, the CU instructs ALU, memory, and I/O devices on when to transfer and process data.",
    explanationBn: "কারণ CU নিজে কোনো গণনা না করেও সমস্ত হার্ডওয়্যার ডিভাইসের মধ্যে ডেটা ও সিগন্যাল প্রবাহ নিয়ন্ত্রণ ও পরিচালনা করে।",
    category: "Concepts"
  },
  {
    id: "q5",
    question: "What is an Accumulator (ACC) register and what is its primary function?",
    answer: "The Accumulator (ACC) is a dedicated general/working register in the CPU that temporarily stores the intermediate and final arithmetic or logical results generated by the Arithmetic Logic Unit (ALU).",
    explanation: "For example, in the operation `X = A + B + C`, after adding A and B, the intermediate sum is kept in the Accumulator before adding C.",
    explanationBn: "Accumulator হলো CPU-র একটি বিশেষ রেজিস্টার যা ALU দ্বারা সম্পন্ন গাণিতিক বা যৌক্তিক অপারেশনের অন্তর্বর্তীকালীন ফলাফল ধারণ করে।",
    category: "Registers"
  },
  {
    id: "q6",
    question: "What happens to the Instruction Register (IR) during the fetch-decode phase?",
    answer: "During the fetch phase, the instruction word fetched from memory via MDR is loaded into the Instruction Register (IR). During the decode phase, the Control Unit examines the opcode in the IR to determine which electrical micro-signals to trigger.",
    explanation: "The IR holds the instruction constant throughout its decoding and execution lifecycle until the next instruction is fetched.",
    explanationBn: "ফেচ করার পর মেমোরি থেকে আসা নির্দেশটি IR-এ জমা হয় এবং কন্ট্রোল ইউনিট IR-এর অপকোড ডিকোড করে যথাযথ পদক্ষেপ গ্রহণ করে।",
    category: "Instruction Cycle"
  },
  {
    id: "q7",
    question: "What is the function of the Status / Flags Register in a processor?",
    answer: "The Flags register contains individual status bits (flags) that reflect the outcome of the most recently executed arithmetic or logic operation (e.g., Zero Flag, Sign Flag, Carry Flag, and Overflow Flag).",
    explanation: "Conditional branching statements (e.g., `if (x == 0):`) inspect the Zero Flag bit to decide whether to jump to another code block.",
    explanationBn: "ফ্ল্যাগ রেজিস্টার গাণিতিক অপারেশনের ফলাফল সম্পর্কে তথ্য দেয় (যেমন ফলাফল শূন্য কিনা, ঋণাত্মক কিনা, বা ক্যারি এসেছে কিনা)।",
    category: "Registers"
  },
  {
    id: "q8",
    question: "Calculate the clock cycle time (T) of a 3.5 GHz Intel/AMD processor.",
    answer: "Clock Cycle Time T = 1 / Frequency = 1 / (3.5 × 10^9 s^-1) ≈ 0.2857 nanoseconds (or 285.7 picoseconds).",
    explanation: "Clock frequency denotes ticks per second. High clock speed means each tick takes a fraction of a nanosecond to complete.",
    explanationBn: "৩.৫ গিগাহার্টজ প্রসেসরের প্রতিটি ক্লক সাইকেলের সময় = ১ / (৩.৫ × ১০^৯) = প্রায় ০.২৮৫৭ ন্যানোসেকেন্ড।",
    category: "Calculations"
  },
  {
    id: "q9",
    question: "Why are CPU registers faster than Cache Memory and RAM?",
    answer: "Registers are fabricated directly onto the CPU silicon core right next to the execution pipelines, avoiding external bus propagation delays and capacitive line load.",
    explanation: "Registers operate with zero or near-zero wait states at the CPU's native clock frequency (e.g. 4 GHz), while Cache and RAM require bus traversal.",
    explanationBn: "রেজিস্টার সরাসরি CPU কোরের অভ্যন্তরে অবস্থিত হওয়ায় এতে অ্যাক্সেস করতে কোনো বাহ্যিক বাস বা সার্কিট বিলম্ব ঘটে না।",
    category: "Memory Hierarchy"
  },
  {
    id: "q10",
    question: "What is an Opcode and an Operand in a machine instruction?",
    answer: "An Opcode (Operation Code) specifies the action to be performed (e.g., ADD, SUB, JUMP), while the Operand specifies the data or memory address upon which the operation is performed.",
    explanation: "In the assembly instruction `ADD R1, 2048`, `ADD` is the Opcode, and `R1` and `2048` are the Operands.",
    explanationBn: "Opcode নির্দেশ করে কী কাজ করতে হবে (যেমন ADD, SUB), আর Operand নির্দেশ করে কোন ডেটা বা অ্যাড্রেসের ওপর সেই কাজটি সম্পন্ন হবে।",
    category: "Architecture"
  },
  {
    id: "q11",
    question: "Which register is updated when a function call or subroutine interrupt occurs?",
    answer: "The Program Counter (PC) is updated with the entry address of the subroutine, and the previous return address is pushed into the Stack Pointer (SP) register in memory.",
    explanation: "This allows the CPU to resume normal execution exactly where it left off after the subroutine completes via a RETURN instruction.",
    explanationBn: "সাবরুটিন বা ফাংশন কলের সময় PC পরিবর্তিত হয়ে নতুন সাবরুটিনের অ্যাড্রেসে চলে যায় এবং পূর্ববর্তী অ্যাড্রেসটি স্ট্যাক পয়েন্টার (SP)-এ জমা থাকে।",
    category: "Registers"
  },
  {
    id: "q12",
    question: "State whether the following statement is True or False: 'The ALU directly reads data from secondary hard drives.'",
    answer: "False. The ALU only operates on operands loaded into CPU registers or primary memory buffers (RAM/Cache). Secondary storage data must first be transferred to RAM.",
    explanation: "The CPU cannot directly execute or compute data sitting on HDDs or SSDs without loading it into main memory first.",
    explanationBn: "ভুল। ALU সরাসরি সেকেন্ডারি হার্ডড্রাইভ থেকে কোনো ডেটা পড়তে পারে না; ডেটা প্রথমে র‍্যামে লোড হতে হয়।",
    category: "True/False"
  },
  {
    id: "q13",
    question: "What is the difference between General Purpose Registers (GPRs) and Special Purpose Registers (SPRs)?",
    answer: "GPRs (like R0, R1, R2 / EAX, EBX) can be used by programmers and compilers to hold arbitrary variables and data, whereas SPRs (like PC, IR, MAR, MDR, SP) have dedicated, hardware-enforced roles in the instruction cycle.",
    explanation: "Programmers cannot freely use SPRs for general variable storage without altering CPU execution logic.",
    explanationBn: "GPR সাধারণ ডেটা ও চলক সাময়িকভাবে রাখার জন্য ব্যবহৃত হয়, কিন্তু SPR-এর নির্দিষ্ট হার্ডওয়্যারভিত্তিক দায়িত্ব থাকে (যেমন PC বা IR)।",
    category: "Registers"
  },
  {
    id: "q14",
    question: "What is the role of the System Clock in relation to CPU registers?",
    answer: "The System Clock produces continuous quartz crystal electrical oscillations that synchronize register state changes, latching, and data transfers between the ALU, CU, and memory.",
    explanation: "Without clock pulses, logic gates inside registers would not know when to capture input data or hold steady values.",
    explanationBn: "সিস্টেম ক্লক বিদ্যুৎ স্পন্দন তৈরি করে যার মাধ্যমে রেজিস্টার ও ALU-এর মধ্যে ডেটা আদান-প্রদান সময়নিষ্ঠভাবে সম্পন্ন হয়।",
    category: "Architecture"
  },
  {
    id: "q15",
    question: "If a processor has a 32-bit Program Counter, what is the maximum addressable memory space?",
    answer: "Maximum addressable memory space = 2^32 bytes = 4,294,967,296 bytes = 4 Gigabytes (GB).",
    explanation: "A 32-bit register can generate 2^32 distinct binary combinations, allowing individual access to 4 GB of memory addresses.",
    explanationBn: "৩২-বিট PC থাকলে ২^৩২ টি আলাদা অ্যাড্রেস নির্দেশ করা যায়, যা ৪ গিগাবাইট (4 GB) মেমোরির সমান।",
    category: "Calculations"
  },
  {
    id: "q16",
    question: "What is meant by the 'word size' of a CPU?",
    answer: "The word size is the number of bits that the CPU's internal registers and ALU can process in a single clock cycle (e.g. 32-bit or 64-bit architecture).",
    explanation: "A 64-bit CPU has 64-bit wide registers, allowing it to process 8 bytes of integer or memory pointers in one basic machine step.",
    explanationBn: "CPU Word Size বলতে বোঝায় এক সাইকেলে CPU-র রেজিস্টার ও ALU কত বিট ডেটা একসাথে প্রসেস করতে পারে (যেমন 64-bit)।",
    category: "Architecture"
  },
  {
    id: "q17",
    question: "Which component inside the ALU performs logical AND, OR, and NOT operations?",
    answer: "Logic gates (AND gates, OR gates, Inverters/NOT gates, and Multiplexers) fabricated using silicon semiconductor transistors perform logical operations inside the ALU.",
    explanation: "These circuits accept binary high/low voltage levels and output the evaluated truth value in fractions of a nanosecond.",
    explanationBn: "ALU-র ভেতরে থাকা লজিক গেটসমূহ (AND, OR, NOT ইত্যাদি) লজিক্যাল অপারেশন সম্পন্ন করে।",
    category: "ALU"
  },
  {
    id: "q18",
    question: "What is the full form of MIPS and FLOPS in processor performance benchmarking?",
    answer: "MIPS stands for 'Million Instructions Per Second', and FLOPS stands for 'Floating-Point Operations Per Second'.",
    explanation: "MIPS measures integer processing performance, whereas FLOPS measures scientific and graphics floating-point calculation speed.",
    explanationBn: "MIPS = Million Instructions Per Second এবং FLOPS = Floating-Point Operations Per Second।",
    category: "Benchmarking"
  },
  {
    id: "q19",
    question: "Explain what happens when an arithmetic overflow occurs during an ADD operation in the ALU.",
    answer: "When the result of an arithmetic calculation exceeds the maximum storage capacity of the destination register, the Overflow Flag (O/V) in the Status register is set to 1 to alert the system of numerical truncation.",
    explanation: "For an 8-bit signed integer register (-128 to +127), adding 100 + 50 yields 150, which overflows and corrupts the sign bit.",
    explanationBn: "যখন কোনো গাণিতিক ফলাফল রেজিস্টারের সর্বোচ্চ ধারণক্ষমতা ছাড়িয়ে যায়, তখন স্ট্যাটাস রেজিস্টারের ওভারফ্লো ফ্ল্যাগ অন (১) হয়ে যায়।",
    category: "ALU"
  },
  {
    id: "q20",
    question: "How does the Control Unit communicate with I/O devices?",
    answer: "The Control Unit sends read/write control signals over the Control Bus to I/O controllers and memory-mapped I/O register ports.",
    explanation: "Device controllers interpret these control signals to activate physical mechanisms like motor rotation or network transmission.",
    explanationBn: "কন্ট্রোল বাস দিয়ে কন্ট্রোল ইউনিট I/O কন্ট্রোলারের রেজিস্টারে রিড/রাইট সিগন্যাল প্রেরণ করে।",
    category: "Control Unit"
  },
  {
    id: "q21",
    question: "Name two modern processor architectures used in desktop computers and smartphones.",
    answer: "x86-64 (CISC architecture used by Intel and AMD in laptops/desktops) and ARM (RISC architecture used by Apple Silicon, Qualcomm, and MediaTek in smartphones).",
    explanation: "x86-64 utilizes complex variable-length instructions, while ARM utilizes power-efficient reduced instruction sets.",
    explanationBn: "x86-64 (Intel ও AMD পিসি ও ল্যাপটপে ব্যবহৃত) এবং ARM (স্মার্টফোন ও আধুনিক ডিভাইসে ব্যবহৃত)।",
    category: "Architecture"
  },
  {
    id: "q22",
    question: "What is a 'Bus Interface Unit' (BIU) in modern CPU architecture?",
    answer: "The Bus Interface Unit (BIU) is the CPU sub-module that manages physical data, address, and control transfers between the internal CPU registers and the external system bus.",
    explanation: "BIU handles pre-fetching instructions into internal queues to keep the execution unit fed with continuous data.",
    explanationBn: "BIU হলো CPU-র সেই অংশ যা বাহ্যিক সিস্টেম বাসের সাথে অভ্যন্তরীণ রেজিস্টারগুলোর সংযোগ ও যোগাযোগ পরিচালনা করে।",
    category: "Architecture"
  },
  {
    id: "q23",
    question: "Why is the Instruction Register (IR) not directly accessible to programmers in standard high-level languages?",
    answer: "IR is a dedicated hardware register designed to hold the raw binary machine code opcode under direct hardware decoding by the CU. Allowing user modification would corrupt the hardware decoding state machine.",
    explanation: "High-level languages like Python abstract away machine-level register management for safety and portability.",
    explanationBn: "কারণ IR সরাসরি হার্ডওয়্যার দ্বারা নিয়ন্ত্রিত হয়; ব্যবহারকারী এতে হস্তক্ষেপ করলে প্রসেসরের নির্দেশ নির্বাহ প্রক্রিয়া বিভ্রান্ত হবে।",
    category: "Registers"
  },
  {
    id: "q24",
    question: "Explain the concept of 'Clock Skew' in high-speed CPU circuit boards.",
    answer: "Clock Skew is the spatial time difference between the arrival of the clock signal at different registers due to physical wire length variations and temperature differences.",
    explanation: "Engineers design equal-length clock distribution trees (H-trees) on silicon to minimize skew and prevent register race conditions.",
    explanationBn: "সার্কিটের বিভিন্ন প্রান্তে তারের দূরত্বের পার্থক্যের কারণে একই সময়ে ক্লক সিগন্যাল না পৌঁছানোর পার্থক্যকে Clock Skew বলে।",
    category: "Advanced"
  },
  {
    id: "q25",
    question: "Summary Question: Trace the data pathway in CPU when executing: `ADD R1, [1050]`",
    answer: "1. Address 1050 is placed into MAR.\n2. Control Unit sends Memory Read signal over Control Bus.\n3. Value at RAM[1050] is read via Data Bus into MDR.\n4. ALU takes value from R1 and MDR, adds them, and stores the result into R1 or Accumulator.\n5. Status flags (Z, S, C, O) are updated.",
    explanation: "This complete cycle illustrates how MAR, MDR, CU, ALU, and registers work in seamless harmony during a single instruction step.",
    explanationBn: "১. MAR-এ ১০৫০ অ্যাড্রেস যায়। ২. CU মেমোরি রিড সিগন্যাল পাঠায়। ৩. MDR-এ ডেটা আসে। ৪. ALU রেজিস্টার R1 ও MDR যোগ করে। ৫. ফলাফল রেজিস্টারে সংরক্ষিত হয় এবং ফ্ল্যাগ আপডেট হয়।",
    category: "Tracing"
  }
];

export default questions;
