/**
 * Module 001_004: Topic 10: Switch with Strings (introduced in Java 7) and internal hashcode matching
 * 30 High-Yield Comprehensive Q&A Items
 * Educator: Sukanta Hui | Coder & AccoTax Barrackpore
 */

const questions = [
  {
    question: "When was switching on `String` objects introduced in Java?",
    shortAnswer: "In Java SE 7 (as part of Project Coin / JSR 334).",
    explanation: "Before Java 7, switch only supported integral primitives, wrappers, and enums.",
    hint: "Introduced in Java 7.",
    level: "basic",
    codeExample: "switch (command) { case \"START\": ... }"
  },
  {
    question: "How does the Java compiler (`javac`) implement `String` switching in bytecode?",
    shortAnswer: "As a TWO-STAGE process: 1. Evaluates `str.hashCode()` in a jump table (`lookupswitch`/`tableswitch`); 2. Verifies string equality using `str.equals(\"caseVal\")` to resolve hash collisions.",
    explanation: "Two-tiered hash jump plus equality verification.",
    hint: "Two stages: hashCode() jump table followed by .equals() check.",
    level: "intermediate",
    codeExample: "// Bytecode invokes hashCode() then .equals()"
  },
  {
    question: "What happens if a `null` String is passed to a traditional `switch (str)` statement?",
    shortAnswer: "Throws a `java.lang.NullPointerException` immediately upon evaluating the switch expression.",
    explanation: "Because the compiler-generated bytecode calls `str.hashCode()`, calling a method on `null` triggers an immediate NPE.",
    hint: "Throws NullPointerException due to str.hashCode().",
    level: "basic",
    codeExample: "String s = null;\n// switch (s) { } // THROWS NullPointerException"
  },
  {
    question: "How does Java handle Hash Collisions in String switch statements?",
    shortAnswer: "If two distinct strings have identical hash codes (e.g. `\"FB\"` and `\"Ea\"`), both map to the same hash jump branch, where sequential `.equals()` checks distinguish between them.",
    explanation: "Ensures 100% mathematical correctness even during hash collisions.",
    hint: "Sequential .equals() checks inside the same hash bucket.",
    level: "intermediate",
    codeExample: "// \"FB\".hashCode() == \"Ea\".hashCode() (2236)"
  },
  {
    question: "Are String switch case comparisons case-sensitive in Java?",
    shortAnswer: "Yes, comparisons are strictly case-sensitive (`\"Java\"` will NOT match `\"java\"`).",
    explanation: "Because `.equals()` is used internally.",
    hint: "Strictly case-sensitive.",
    level: "basic",
    codeExample: "switch (s.toUpperCase()) { case \"JAVA\": ... } // Case-insensitive pattern"
  },
  {
    question: "How can you perform a case-insensitive String switch in Java?",
    shortAnswer: "Normalize the input string before switching: `switch (input.toUpperCase())` or `switch (input.toLowerCase())` (with a defensive null check).",
    explanation: "Standard normalization idiom.",
    hint: "Normalize with .toUpperCase() or .toLowerCase().",
    level: "basic",
    codeExample: "if (input != null) {\n    switch (input.toUpperCase()) { case \"ADMIN\": ... }\n}"
  },
  {
    question: "What are the rules for String `case` labels in a switch statement?",
    shortAnswer: "String case labels must be compile-time constant String literals or `final` String variables initialized with constant expressions; `null` is forbidden in traditional switch.",
    explanation: "Enforced strictly by JLS §14.11.",
    hint: "Must be compile-time constant Strings.",
    level: "basic",
    codeExample: "final String CMD = \"EXIT\";\nswitch (s) { case CMD: ... }"
  },
  {
    question: "Can a `case` label in a String switch be a runtime variable (`String cmd = getCmd(); case cmd:`)?",
    shortAnswer: "No! `case` labels must be compile-time constants (causes a compile error: 'constant expression required').",
    explanation: "Runtime variables cannot be used as case labels.",
    hint: "Constant expression required.",
    level: "basic",
    codeExample: "String dyn = \"TEST\";\n// case dyn: // COMPILER ERROR!"
  },
  {
    question: "In the Coder & AccoTax Barrackpore fee collection engine, how is String switch used?",
    shortAnswer: "To route tuition payments across payment modes: `\"UPI\"`, `\"NEFT\"`, `\"NET_BANKING\"`, and `\"CASH_COUNTER\"` in Indian Rupees (₹).",
    explanation: "Demonstrates practical enterprise payment dispatching.",
    hint: "Routes payment modes (UPI, NEFT, Net Banking) in ₹.",
    level: "basic",
    codeExample: "switch (paymentMode) { case \"UPI\": ... case \"NEFT\": ... }"
  },
  {
    question: "Why is String switch generally faster than an `else-if` ladder of `.equals()` calls?",
    shortAnswer: "Because `String.hashCode()` computes an integer hash once and jumps in $O(1)$/$O(\log N)$ time, avoiding multiple sequential character-by-character string comparisons.",
    explanation: "Computes hash once instead of doing $N$ string comparisons.",
    hint: "Single hash calculation vs multiple string comparisons.",
    level: "intermediate",
    codeExample: "// String switch hashes once"
  },
  {
    question: "What happens if a String switch contains duplicate `case` labels with different string formatting (`case \"test\":` and `case \"test\":`)?",
    shortAnswer: "Compilation error: 'duplicate case label'.",
    explanation: "Case labels must be strictly unique.",
    hint: "Duplicate case labels cause compile error.",
    level: "basic",
    codeExample: "// case \"A\": ... case \"A\": // COMPILER ERROR"
  },
  {
    question: "Can a String switch have `null` as a case label in Java 7 to 16?",
    shortAnswer: "No! `case null:` was illegal prior to Java 17-21 preview features.",
    explanation: "Traditional switch threw NPE on null selectors.",
    hint: "Illegal before Java 17-21.",
    level: "intermediate",
    codeExample: "// case null: // ILLEGAL in traditional Java 7-16 switch"
  },
  {
    question: "How does Java 21 permit handling `null` in String switch expressions?",
    shortAnswer: "By allowing an explicit `case null → handleNull();` or `case null, default → handleFallback();` branch.",
    explanation: "Modern pattern matching enhancement in Java 21.",
    hint: "case null → is permitted in Java 21.",
    level: "advanced",
    codeExample: "switch (s) { case null → \"Null Input\"; case \"A\" → \"A\"; default → \"Other\"; }"
  },
  {
    question: "What is the bytecode overhead of switching on 5 Strings compared to switching on 5 integers?",
    shortAnswer: "String switch generates two switch instructions in bytecode (one for hash lookup and one for branch dispatch) plus `.equals()` method invocation calls.",
    explanation: "Slightly more bytecode instructions, but still very fast.",
    hint: "Two switch instructions in bytecode plus .equals().",
    level: "advanced",
    codeExample: "// Two-tier bytecode jump sequence"
  },
  {
    question: "What happens if two strings have different lengths and different characters but produce the same hash code?",
    shortAnswer: "Java's `.equals()` call in Stage 2 returns `false`, rejecting the incorrect case and jumping to subsequent checks or `default`.",
    explanation: "Guarantees 100% collision immunity.",
    hint: ".equals() verifies exact match and guards against collisions.",
    level: "basic",
    codeExample: "if (s.hashCode() == 2236) { if (s.equals(\"FB\")) ... }"
  },
  {
    question: "Can constant string concatenation be used in case labels (e.g. `case \"USER_\" + \"ADMIN\":`)?",
    shortAnswer: "Yes! The compiler evaluates constant string concatenations into a single interned string constant (`\"USER_ADMIN\"`) at compile time.",
    explanation: "Constant string concatenation is legal.",
    hint: "Compile-time string concatenation is legal.",
    level: "intermediate",
    codeExample: "case \"PAY_\" + \"UPI\": // Legal (Constant \"PAY_UPI\")"
  },
  {
    question: "Why should you NOT use String switch for continuous text parsing (e.g. tokenizers)?",
    shortAnswer: "Because lexers and tokenizers typically benefit more from finite state automata or regex engines.",
    explanation: "Switch is best for fixed keyword dispatch.",
    hint: "Use state automata for parsing.",
    level: "intermediate",
    codeExample: "// Use state machine for token parsing"
  },
  {
    question: "What is the result of `String s = new String(\"ABC\"); switch (s) { case \"ABC\": print(\"Matched\"); break; }`?",
    shortAnswer: "Prints `\"Matched\"`.",
    explanation: "String switch uses `.equals()` (logical equality), NOT `==` (reference equality), so `new String(\"ABC\")` matches `\"ABC\"`.",
    hint: "Uses .equals() content comparison, so new String() matches.",
    level: "basic",
    codeExample: "String s = new String(\"ABC\"); switch (s) { case \"ABC\": print(\"Matched\"); break; }"
  },
  {
    question: "What is the result of `String s = \"abc\"; switch (s) { case \"ABC\": print(\"1\"); break; default: print(\"2\"); break; }`?",
    shortAnswer: "Prints `\"2\"`.",
    explanation: "Case sensitivity causes `\"abc\"` to not match `\"ABC\"`, executing `default`.",
    hint: "Case-sensitive: prints 2.",
    level: "basic",
    codeExample: "String s = \"abc\"; switch (s) { case \"ABC\": print(\"1\"); default: print(\"2\"); } // 2"
  },
  {
    question: "Can an empty String `\"\"` be used as a `case` label in Java?",
    shortAnswer: "Yes! `\"\"` is a valid string literal with `hashCode() == 0`.",
    explanation: "Completely legal in Java.",
    hint: "Empty string \"\" is a legal case label.",
    level: "basic",
    codeExample: "case \"\": handleEmpty(); break;"
  },
  {
    question: "How does the HotSpot JIT compiler optimize String switch at runtime?",
    shortAnswer: "It inlines the `.equals()` check and uses hardware string comparison instructions (e.g. AVX vector comparison on modern CPUs).",
    explanation: "Vectorized assembly acceleration.",
    hint: "Inlining and vectorized string comparisons.",
    level: "advanced",
    codeExample: "// HotSpot optimizes string equality checks"
  },
  {
    question: "What is the best way to handle null selectors defensively in String switch before Java 21?",
    shortAnswer: "Check `if (str == null)` with a guard clause or use `Objects.requireNonNull(str)` before entering the switch.",
    explanation: "Defensive guard pattern.",
    hint: "Check if (str == null) before entering switch.",
    level: "basic",
    codeExample: "if (cmd == null) return;\nswitch (cmd) { case \"A\": ... }"
  },
  {
    question: "What is the difference between switching on a `String` vs switching on an `enum`?",
    shortAnswer: "Enum switch is type-safe, validated at compile-time, and operates on primitive integer ordinals; String switch operates on dynamic strings and involves hashcode + equals overhead.",
    explanation: "Enums are preferred when the set of constants is fixed and known at compile-time.",
    hint: "Enums provide compile-time type safety; Strings are dynamic.",
    level: "intermediate",
    codeExample: "switch (branchEnum) vs switch (branchString)"
  },
  {
    question: "What happens if a class defines `public static final String ACTION = System.getProperty(\"action\");` and uses it as a `case` label?",
    shortAnswer: "Compilation error: `System.getProperty()` is evaluated at runtime, so `ACTION` is NOT a compile-time constant expression.",
    explanation: "Runtime evaluations are not compile-time constants.",
    hint: "System.getProperty() is a runtime call, not a compile-time constant.",
    level: "advanced",
    codeExample: "// final String A = System.getProperty(\"x\"); case A: // COMPILER ERROR"
  },
  {
    question: "Can multiple String case labels be stacked in traditional switch?",
    shortAnswer: "Yes! E.g. `case \"Y\": case \"YES\": case \"TRUE\": confirm(); break;`.",
    explanation: "Standard intentional multi-case grouping.",
    hint: "Stacked String cases share execution.",
    level: "basic",
    codeExample: "case \"Y\":\ncase \"YES\":\n    confirm();\n    break;"
  },
  {
    question: "In the Coder & AccoTax Barrackpore admissions portal, why are course codes normalized?",
    shortAnswer: "Input strings are trimmed and upper-cased (`courseCode.trim().toUpperCase()`) before switching to ensure robust user input tolerance in Indian Rupees (₹).",
    explanation: "Ensures resilient user input matching.",
    hint: "Normalizes input with trim() and toUpperCase().",
    level: "basic",
    codeExample: "switch (code.trim().toUpperCase()) { case \"JAVA\": ... }"
  },
  {
    question: "What is the return type of `String.hashCode()` in Java?",
    shortAnswer: "A 32-bit signed integer (`int`).",
    explanation: "Maps directly into JVM 32-bit `tableswitch`/`lookupswitch` instructions.",
    hint: "32-bit signed int.",
    level: "basic",
    codeExample: "int hash = \"JAVA\".hashCode();"
  },
  {
    question: "What is the formula used by `String.hashCode()` in Java?",
    shortAnswer: "$s[0] \\cdot 31^{n-1} + s[1] \\cdot 31^{n-2} + \\dots + s[n-1]$ using 31 as prime multiplier.",
    explanation: "Deterministic standard Java hash algorithm.",
    hint: "Polynomial hash with prime multiplier 31.",
    level: "advanced",
    codeExample: "// s[0]*31^(n-1) + ... + s[n-1]"
  },
  {
    question: "What is the ultimate takeaway of Module 001_004 Topic 10 for Java developers?",
    shortAnswer: "String switch (Java 7+) provides clean, efficient dispatching via two-stage bytecode compilation (hashCode jump + equals verification); always guard against null selectors, keep case labels as compile-time constants, and normalize inputs for case tolerance.",
    explanation: "Essential foundation for enterprise command routers and API gateways.",
    hint: "Two-stage hashCode + equals matching; guard against nulls.",
    level: "basic",
    codeExample: "// Summary: switch (str) with two-stage hash jump and defensive null guards"
  },
  {
    question: "What is the next topic (Topic 11) in Module 001_004?",
    shortAnswer: "Modern Switch Expressions (introduced in Java 14+): arrow syntax (case X → Y).",
    explanation: "Topic 11 explores modern switch expressions, arrow syntax, elimination of boilerplate, and concise single-line branches.",
    hint: "Modern Switch Expressions and arrow syntax.",
    level: "basic",
    codeExample: "// Topic 11: Modern Switch Expressions (Java 14+)"
  }
];

export default questions;
