const questions = [
  {
    question: "What was ARPANET and why is it significant?",
    shortAnswer: "ARPANET was the first packet-switching network, funded by DARPA, and the precursor to the modern internet.",
    explanation: "It demonstrated the feasibility of packet switching and led to the development of TCP/IP. Its first message was sent in 1969.",
    hint: "Think of ARPANET as the 'grandparent' of the internet.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "Who are the key inventors of TCP/IP?",
    shortAnswer: "Vint Cerf and Bob Kahn developed TCP/IP in the 1970s.",
    explanation: "They designed the protocol suite that allows different networks to interconnect, forming the basis of the Internet.",
    hint: "They are often called the 'fathers of the internet'.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is the difference between the Internet and the World Wide Web?",
    shortAnswer: "The Internet is the infrastructure (networks, routers), while the Web is a service (web pages, HTTP) that runs on it.",
    explanation: "The Internet is the physical and logical network; the Web is an application layer built on top, using HTTP and browsers.",
    hint: "The web is like a store inside a shopping mall (the internet).",
    level: "basic",
    codeExample: null,
  },
  {
    question: "When was the World Wide Web invented and by whom?",
    shortAnswer: "Tim Berners-Lee invented the World Wide Web in 1991.",
    explanation: "He proposed a hypertext system, wrote the first browser and server, and set the standards that made the web accessible.",
    hint: "He worked at CERN in Switzerland.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What was the first message sent over ARPANET?",
    shortAnswer: "The intended message was 'LOGIN', but only 'LO' was sent before a crash.",
    explanation: "This crash is famously the first network error, yet it proved the system could send data.",
    hint: "It was a simple word, but technology failed halfway through.",
    level: "basic",
    codeExample: null,
  },
  {
    question: "What is packet switching and why was it revolutionary?",
    shortAnswer: "Packet switching breaks data into small packets that travel independently, allowing efficient use of network links.",
    explanation: "Unlike circuit switching (like old phone calls), packet switching doesn't reserve a dedicated path, making networks more robust and efficient.",
    hint: "Think of sending a book as separate pages that can take different routes.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "When did Ethernet first appear and who invented it?",
    shortAnswer: "Ethernet was developed by Robert Metcalfe at Xerox PARC in the early 1970s and standardised in 1980.",
    explanation: "Ethernet became the dominant LAN technology, using CSMA/CD for medium access.",
    hint: "Metcalfe also famously stated 'Metcalfe's Law' about network value.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What role did the military play in the development of the internet?",
    shortAnswer: "The military (DARPA) funded ARPANET and later research into robust, decentralized networks.",
    explanation: "They wanted a network that could survive partial failures (e.g., nuclear attack), which influenced the packet-switched design.",
    hint: "The internet's resilience owes much to military requirements.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is an RFC and why is it important?",
    shortAnswer: "Request for Comments (RFC) are documents that define internet standards, protocols, and best practices.",
    explanation: "RFCs are how the internet community collaborates; they are living documents that evolve.",
    hint: "Every major protocol (TCP, IP, HTTP) has an RFC.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How did the Domain Name System (DNS) evolve?",
    shortAnswer: "DNS was introduced in the 1980s to replace the hosts.txt file, allowing hierarchical name resolution.",
    explanation: "DNS maps human-friendly names to IP addresses, making the internet user-friendly.",
    hint: "Before DNS, you had to remember IP addresses!",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What was the significance of the 1990s for the internet?",
    shortAnswer: "The 1990s saw the commercialisation of the internet, the rise of the web, and the dot-com boom.",
    explanation: "Browsers like Mosaic and Netscape brought the internet to the masses, and companies began to use it for business.",
    hint: "It transitioned from academic/military to public.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the history of Wi-Fi?",
    shortAnswer: "Wi-Fi (IEEE 802.11) was first released in 1997, with significant improvements in 1999 (802.11b).",
    explanation: "It allowed wireless networking, freeing users from cables, and became ubiquitous in homes and public spaces.",
    hint: "The 'Wi-Fi' brand was created by the Wi-Fi Alliance.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How did the internet evolve from IPv4 to IPv6?",
    shortAnswer: "IPv4 addresses (32-bit) ran out; IPv6 (128-bit) was developed in the late 1990s to provide a much larger address space.",
    explanation: "The transition has been gradual, with dual-stack and tunneling mechanisms.",
    hint: "IPv6 solves the address shortage problem.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What are some key milestones in the history of networking?",
    shortAnswer: "ARPANET (1969), TCP/IP (1974), Ethernet (1980), WWW (1991), Wi-Fi (1997), IPv6 (1998), 4G/5G.",
    explanation: "Each milestone added new capabilities—speed, wireless, mobility, and capacity.",
    hint: "The timeline is a story of continuous improvement.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "How did the internet become global?",
    shortAnswer: "Through the interconnection of regional networks, international undersea cables, and the adoption of common protocols.",
    explanation: "ISP peering, satellite links, and fiber optics expanded reach to every continent.",
    hint: "It's a network of networks.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the history of email?",
    shortAnswer: "Email was one of the first applications on ARPANET, with the first email sent by Ray Tomlinson in 1971.",
    explanation: "He also introduced the '@' symbol to separate user from host.",
    hint: "The '@' became a standard due to email.",
    level: "intermediate",
    codeExample: null,
  },
  {
    question: "What is the significance of the 'Internet Engineering Task Force' (IETF)?",
    shortAnswer: "The IETF is a large open community that develops and promotes internet standards, primarily through RFCs.",
    explanation: "It's a democratic, volunteer-driven organisation that ensures the internet evolves in an open manner.",
    hint: "They are the technical backbone of internet governance.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How did the advent of broadband change networking?",
    shortAnswer: "Broadband (DSL, cable, fiber) provided high-speed, always-on connections, enabling rich media and always-on services.",
    explanation: "It replaced dial-up, which was slow and tied up phone lines, and allowed the growth of streaming, gaming, and cloud.",
    hint: "Think of the difference between waiting for a page to load and instant access.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the role of network neutrality in the history of the internet?",
    shortAnswer: "Net neutrality is the principle that ISPs should treat all data equally, without discrimination.",
    explanation: "Debates emerged in the 2000s as ISPs considered throttling or prioritising traffic. It's a key policy issue.",
    hint: "It's about keeping the internet open and fair.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How did cloud computing emerge from networking history?",
    shortAnswer: "Cloud computing evolved from time-sharing, grid computing, and the availability of high-bandwidth networks.",
    explanation: "With robust networks, computing resources could be centralised and accessed remotely, leading to IaaS, PaaS, SaaS.",
    hint: "The network made the cloud possible.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What are 'Internet pioneers' and who are some notable ones?",
    shortAnswer: "Pioneers are individuals who made fundamental contributions to the development of the internet.",
    explanation: "Besides Cerf and Kahn, others include Paul Baran (packet switching), Leonard Kleinrock, Larry Roberts, and Tim Berners-Lee.",
    hint: "Many have received awards like the Turing Award.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How did networking become wireless?",
    shortAnswer: "Wireless networking started with radio-based systems, evolved to cellular (1G, 2G...) and Wi-Fi, using licensed and unlicensed spectrum.",
    explanation: "The need for mobility drove the development of wireless protocols.",
    hint: "Your smartphone combines many wireless technologies.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the history of the 'Internet of Things' (IoT) in networking?",
    shortAnswer: "IoT emerged in the 2000s as cheaper sensors and wireless connectivity allowed everyday devices to be networked.",
    explanation: "It's an extension of networking to non-computer devices, using protocols like MQTT, CoAP, and LoRa.",
    hint: "From smart bulbs to industrial sensors, everything is connected.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How did network security evolve?",
    shortAnswer: "Security was initially an afterthought; firewalls (1990s), encryption (SSL/TLS), and intrusion detection systems were added over time.",
    explanation: "The need for secure transactions (e-commerce) and privacy drove the development of security protocols.",
    hint: "Early networks were built on trust; now we assume hostility.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the significance of the 'National Science Foundation' (NSF) in internet history?",
    shortAnswer: "NSF funded the NSFNET backbone in the 1980s, which became a major part of the internet and promoted civilian use.",
    explanation: "NSFNET replaced ARPANET as the primary backbone and later was decommissioned to allow commercial ISPs.",
    hint: "It helped move the internet from military to public.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How did social media influence networking infrastructure?",
    shortAnswer: "Social media drove the demand for massive data centres, content delivery networks (CDNs), and real-time protocols.",
    explanation: "Platforms like Facebook, YouTube, and Twitter pushed the need for scalability, low latency, and high availability.",
    hint: "Every 'like' or 'share' is a network event.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the history of optical networking?",
    shortAnswer: "Optical networking uses fiber optics for high-speed transmission; it became commercially viable in the 1980s and has been the backbone of long-distance networks.",
    explanation: "WDM (Wavelength Division Multiplexing) increased capacity dramatically.",
    hint: "Underwater cables use fiber optics.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "How did the open-source movement affect networking?",
    shortAnswer: "Open-source software (Linux, Apache, BIND, etc.) provided free, reliable networking tools that fueled the internet's growth.",
    explanation: "Many key protocols and servers are open source, reducing costs and enabling innovation.",
    hint: "Much of the internet runs on open-source.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "What is the future direction of network history?",
    shortAnswer: "The future points to AI-driven networks (Self-Driving Networks), quantum networking, space-based internet (Starlink), and 6G.",
    explanation: "History shows that networks become faster, more pervasive, and more intelligent over time.",
    hint: "The next chapter is being written now.",
    level: "expert",
    codeExample: null,
  },
  {
    question: "Why is understanding network history important for a network engineer?",
    shortAnswer: "It helps you understand why certain design decisions were made, appreciate the resilience, and anticipate future trends.",
    explanation: "Knowing the past informs better problem-solving and innovation.",
    hint: "Those who don't learn from history are doomed to repeat it.",
    level: "expert",
    codeExample: null,
  },
];

export default questions;