// File: src/components/topics/topic7_files/topic7_questions.js
const questions = [
  {
    question: "What is a checksum?",
    shortAnswer: "A small datum derived from a block of data, used to detect errors.",
    explanation: "Checksums are computed by a function (e.g., sum, CRC) and appended to the data. The receiver recomputes and compares.",
    hint: "It's like a digital fingerprint for error detection.",
    level: "basic",
    codeExample: "// Python: checksum = sum(data) & 0xFFFF"
  },
  {
    question: "How does the Internet checksum differ from a simple sum?",
    shortAnswer: "The Internet checksum uses ones' complement addition, which makes it endian‑independent and allows easy verification (resulting in all ones).",
    explanation: "Simple sum just adds the words; Internet checksum adds, folds carry, then takes ones' complement.",
    hint: "Ones' complement is the key.",
    level: "moderate",
  },
  {
    question: "What is the size of the Internet checksum?",
    shortAnswer: "16 bits (2 bytes).",
    explanation: "It is a 16‑bit value, allowing a range of 0 to 65535 (or 0x0000 to 0xFFFF).",
    hint: "Same as a TCP/UDP checksum field.",
    level: "basic",
  },
  {
    question: "Why does the Internet checksum use the ones' complement?",
    shortAnswer: "Because it makes the checksum independent of endianness and simplifies verification: the receiver can sum all words (including checksum) and check for all 1s (0xFFFF).",
    explanation: "Also, ones' complement arithmetic has no 'negative zero' issue and is easy to implement in hardware.",
    hint: "It's all about simplification.",
    level: "expert",
  },
  {
    question: "What data does the TCP checksum cover?",
    shortAnswer: "The TCP checksum covers a pseudo‑header (source/dest IP, protocol, TCP length) plus the TCP header and data.",
    explanation: "The pseudo‑header provides protection against misdelivery; it's not transmitted but is included in the calculation.",
    hint: "It's end‑to‑end and includes IP addresses.",
    level: "moderate",
  },
  {
    question: "What is the pseudo‑header in TCP/UDP checksum?",
    shortAnswer: "A 12‑byte structure containing source IP, destination IP, protocol, and UDP/TCP length, used in checksum computation to detect misdelivery.",
    explanation: "It is not transmitted; it's prepended to the segment before computing the checksum.",
    hint: "It adds context to the segment.",
    level: "moderate",
  },
  {
    question: "How does the receiver verify the Internet checksum?",
    shortAnswer: "The receiver computes the ones' complement sum of all 16‑bit words in the packet (including the checksum field). If the result is 0xFFFF, the checksum is valid.",
    explanation: "Because the sender made the sum (data + checksum) equal to 0xFFFF, the receiver just checks if the total is all ones.",
    hint: "All ones means valid.",
    level: "moderate",
  },
  {
    question: "Why is the checksum field set to 0 before computing the checksum?",
    shortAnswer: "Because the checksum itself is not known until after computation; it must be excluded from the sum to avoid circularity.",
    explanation: "The sender sets the field to 0, computes the sum, then places the result in the field.",
    hint: "You can't use the result in its own computation.",
    level: "basic",
  },
  {
    question: "What is the main advantage of checksum over parity?",
    shortAnswer: "Checksum can detect more error patterns (including multiple bit errors) and is not limited to single‑bit detection.",
    explanation: "A 16‑bit checksum has 65536 possible values, giving a much lower undetected error probability than a 1‑bit parity.",
    hint: "More bits = better detection.",
    level: "moderate",
  },
  {
    question: "What is the difference between checksum and CRC?",
    shortAnswer: "CRC is more mathematically robust, catches burst errors, and is usually hardware‑implemented. Checksum is simpler, faster in software, but weaker.",
    explanation: "CRC uses polynomial division; checksum uses addition. CRC is used at link layer (Ethernet); checksum at transport layer (TCP).",
    hint: "CRC is stronger; checksum is faster.",
    level: "moderate",
  },
  {
    question: "What is the Fletcher checksum?",
    shortAnswer: "A checksum algorithm that uses two running sums, providing better detection than a simple sum with similar overhead.",
    explanation: "Fletcher‑16 uses sum1 and sum2, where sum2 is the sum of sum1 values. It detects more errors than a single sum.",
    hint: "Two sums are better than one.",
    level: "expert",
  },
  {
    question: "What is the Adler‑32 checksum?",
    shortAnswer: "A 32‑bit checksum invented by Mark Adler, used in zlib; similar to Fletcher but with different parameters.",
    explanation: "It's fast and provides reasonable detection for many applications.",
    hint: "It's a faster alternative to CRC‑32.",
    level: "expert",
  },
  {
    question: "Why do modern protocols like IPv6 not use a checksum for the header?",
    shortAnswer: "IPv6 relies on upper‑layer checksums (TCP/UDP) and link‑layer CRCs for error detection, eliminating the need for a separate header checksum.",
    explanation: "The IPv4 header checksum was necessary because routers modified fields; IPv6 routers do not modify the header, so it's considered redundant.",
    hint: "Less overhead, reliance on other layers.",
    level: "expert",
  },
  {
    question: "What is the 'Internet checksum' also known as?",
    shortAnswer: "The ones' complement checksum or the 16‑bit ones' complement sum.",
    explanation: "It's defined in RFC 1071 and is used in IP, TCP, UDP, ICMP, and many other protocols.",
    hint: "It's the standard Internet checksum.",
    level: "basic",
  },
  {
    question: "How do you compute the Internet checksum for an odd number of bytes?",
    shortAnswer: "Pad the last byte with a zero to form a 16‑bit word, then compute the sum as usual.",
    explanation: "If the data length is odd, the last byte is considered the high byte of the word, with low byte 0.",
    hint: "Zero‑padding.",
    level: "moderate",
  },
  {
    question: "What is the maximum value of a 16‑bit checksum?",
    shortAnswer: "0xFFFF (65535).",
    explanation: "Since it's 16 bits, the range is 0 to 65535.",
    hint: "All bits set.",
    level: "basic",
  },
  {
    question: "Can two different messages produce the same checksum?",
    shortAnswer: "Yes, checksums are not unique; collisions are possible.",
    explanation: "Because the checksum space is limited (16 bits), many messages map to the same value. This is why checksums are not cryptographically secure.",
    hint: "Collisions happen.",
    level: "moderate",
  },
  {
    question: "What is the role of checksum in UDP?",
    shortAnswer: "It provides error detection for the UDP datagram. If the checksum is zero, it means it was not computed (optional in IPv4).",
    explanation: "IPv6 requires a checksum; IPv4 allows zero to indicate no checksum (rarely used).",
    hint: "Optional but recommended.",
    level: "moderate",
  },
  {
    question: "Why is the checksum in IP header only over the header, not the payload?",
    shortAnswer: "To allow routers to quickly recompute the checksum after modifying the TTL field without having to process the entire packet.",
    explanation: "The header is small and frequently modified; the payload is large and would slow routers.",
    hint: "Efficiency.",
    level: "expert",
  },
  {
    question: "What is the difference between a checksum and a hash?",
    shortAnswer: "A checksum is fast, small, and designed for error detection; a hash is cryptographically secure and designed to be collision‑resistant.",
    explanation: "Checksums are not secure against intentional tampering; hashes (like SHA‑256) are.",
    hint: "Hash = security; checksum = speed.",
    level: "moderate",
  },
  {
    question: "How is the Internet checksum affected by byte order?",
    shortAnswer: "It is computed in network byte order (big‑endian). Little‑endian machines must swap bytes before summing.",
    explanation: "The standard ensures interoperability across different platforms.",
    hint: "Network byte order.",
    level: "moderate",
  },
  {
    question: "What is the 'carry fold' in Internet checksum computation?",
    shortAnswer: "When the sum of two 16‑bit words exceeds 0xFFFF, the carry (1) is added back to the lower 16 bits.",
    explanation: "This is how ones' complement addition handles overflow; it ensures the result stays within 16 bits.",
    hint: "Wrap‑around with carry.",
    level: "expert",
  },
  {
    question: "What is the complement of a checksum?",
    shortAnswer: "The ones' complement of the sum; i.e., each bit is flipped.",
    explanation: "The sender sends the complement; the receiver sums all words (including checksum) and expects all ones (0xFFFF).",
    hint: "Flip all bits.",
    level: "moderate",
  },
  {
    question: "Can the Internet checksum detect all single‑bit errors?",
    shortAnswer: "No, but it can detect many. A single‑bit error changes the sum, but if the error is in a position that doesn't affect the sum (e.g., two bits cancel), it might go undetected.",
    explanation: "However, because it's 16‑bit, the probability of undetected error is low (~2<sup>-16</sup> for random errors).",
    hint: "Not perfect, but good.",
    level: "moderate",
  },
  {
    question: "What is the difference between the checksum in IPv4 and IPv6?",
    shortAnswer: "IPv4 has a header checksum; IPv6 does not. IPv6 relies on upper‑layer and link‑layer checks.",
    explanation: "IPv6 removed the header checksum to simplify routers and because link‑layer CRCs provide adequate protection.",
    hint: "IPv6: no header checksum.",
    level: "moderate",
  },
  {
    question: "What is the role of checksum in ICMP?",
    shortAnswer: "It covers the entire ICMP message (header and data) to detect errors.",
    explanation: "Like TCP/UDP, ICMP uses a 16‑bit ones' complement checksum.",
    hint: "Same algorithm.",
    level: "basic",
  },
  {
    question: "What is the 'checksum offload' feature in network interfaces?",
    shortAnswer: "A hardware feature where the NIC computes or verifies the checksum, freeing the CPU.",
    explanation: "Modern NICs can calculate checksums for TCP/UDP/IP in hardware, reducing CPU load and improving throughput.",
    hint: "Hardware acceleration.",
    level: "moderate",
  },
  {
    question: "How do you compute the checksum of a file in Linux?",
    shortAnswer: "Use commands like `sum`, `cksum`, or `md5sum` (though MD5 is a hash, not a simple checksum).",
    explanation: "`sum` computes a simple checksum (like the old UNIX sum); `cksum` gives a CRC‑32 checksum.",
    hint: "Command line tools.",
    level: "basic",
  },
  {
    question: "What is the 'Ethernet FCS' and how is it different from a checksum?",
    shortAnswer: "The FCS is a 32‑bit CRC, not a simple sum. It is far more robust for link‑layer error detection.",
    explanation: "It uses polynomial division (CRC‑32) and detects burst errors, which checksums might miss.",
    hint: "CRC, not checksum.",
    level: "moderate",
  },
  {
    question: "Why is the TCP checksum mandatory in IPv6 but optional in IPv4?",
    shortAnswer: "IPv6 requires the checksum to ensure integrity because it does not have a header checksum and relies on upper layers.",
    explanation: "IPv4 routers check header checksum; IPv6 does not, so TCP/UDP checksum becomes essential.",
    hint: "IPv6 shifted responsibility.",
    level: "expert",
  }
];

export default questions;