// File: src/components/topics/topic3_files/topic3_questions.js
const questions = [
  {
    question: "What is the main advantage of forward error correction (FEC) over retransmission?",
    shortAnswer: "It corrects errors at the receiver without needing a reverse channel or waiting for retransmission.",
    explanation: "FEC is essential when the round‑trip time is long (satellite), when retransmission is impossible (broadcast), or when low latency is required.",
    hint: "Think of a live broadcast: you cannot ask the studio to resend a corrupted frame.",
    level: "basic",
    codeExample: "// ECC memory corrects single-bit errors on the fly without the CPU even knowing."
  },
  {
    question: "What is the Hamming distance of a code and why is it important?",
    shortAnswer: "It's the minimum number of bit flips that turn one valid codeword into another. It determines error detection and correction capability.",
    explanation: "For a code with Hamming distance d: detects d−1 errors, corrects ⌊(d−1)/2⌋ errors.",
    hint: "The greater the distance, the more robust the code.",
    level: "moderate",
  },
  {
    question: "What is the Hamming distance of the classic (7,4) Hamming code?",
    shortAnswer: "3.",
    explanation: "With distance 3, it can correct any single error and detect any double error (but not correct double errors).",
    hint: "Distance 3 = correct 1 error, detect 2 errors.",
    level: "basic",
  },
  {
    question: "Why are parity bits placed at positions that are powers of two in Hamming code?",
    shortAnswer: "Because each parity bit controls a unique set of bits determined by the binary representation of their positions, enabling the syndrome to point directly to the error location.",
    explanation: "Parity at position 2^k checks all positions whose binary representation has the k‑th bit set (counting from LSB). This design ensures that the syndrome equals the index of the erroneous bit.",
    hint: "It's like a binary search on the bits: each parity bit tells you whether the error is in the half where that bit is 1.",
    level: "expert",
  },
  {
    question: "What is the syndrome in Hamming code?",
    shortAnswer: "A binary vector computed by comparing the received parity bits with recalculated parity bits; its value (in decimal) indicates the position of the error.",
    explanation: "If the syndrome is zero, no error. If non‑zero, it directly gives the 1‑based index of the erroneous bit. The decoder flips that bit to correct the error.",
    hint: "The syndrome is both a flag and a map to the error.",
    level: "moderate",
  },
  {
    question: "Can Hamming(7,4) correct a double‑bit error? Why?",
    shortAnswer: "No, because the Hamming distance is 3. Two errors could produce a valid codeword different from the original, or a syndrome that points to a wrong single bit.",
    explanation: "With two errors, the syndrome may be non‑zero but would not correspond to the actual error pattern. The decoder would flip a wrong bit, making the data even more corrupted.",
    hint: "Distance 3 means two errors can look like a different valid codeword or a single error elsewhere.",
    level: "moderate",
  },
  {
    question: "What is the extended Hamming code (8,4)?",
    shortAnswer: "(8,4) Hamming code adds an overall parity bit (even parity over all 7 bits) to create Hamming distance 4.",
    explanation: "This gives SECDED: Single Error Correction, Double Error Detection. The extra parity distinguishes between one error (overall parity odd) and two errors (overall parity even but syndrome non‑zero).",
    hint: "It's a common enhancement used in ECC memory.",
    level: "expert",
  },
  {
    question: "How many parity bits are needed for k data bits in a Hamming code?",
    shortAnswer: "The smallest r such that 2^r ≥ k + r + 1.",
    explanation: "This inequality ensures that the r parity bits can encode up to k + r positions (all bits including parity) plus the 'no error' case.",
    hint: "For k=4, r=3 because 2^3=8 ≥ 4+3+1=8. For k=11, r=4 because 16 ≥ 16.",
    level: "moderate",
  },
  {
    question: "What is SECDED?",
    shortAnswer: "Single Error Correction, Double Error Detection – a capability provided by extended Hamming codes.",
    explanation: "SECDED can correct any single‑bit error and detect (but not correct) any double‑bit error. It is widely used in main memory (ECC DIMMs).",
    hint: "The 'D' is for detection, not correction, of two errors.",
    level: "basic",
  },
  {
    question: "How does a Hamming decoder know whether an error is correctable or uncorrectable?",
    shortAnswer: "In SECDED (extended Hamming), a syndrome of zero and overall parity even → no error. Non‑zero syndrome and overall parity odd → single error (correctable). Non‑zero syndrome and overall parity even → double error (detectable but not correctable).",
    explanation: "The overall parity bit provides an extra check. For plain Hamming(7,4), all non‑zero syndromes are treated as single errors, potentially leading to mis‑correction for double errors.",
    hint: "The parity of the whole codeword tells you if an odd or even number of errors occurred.",
    level: "expert",
  },
  {
    question: "What is the code rate of Hamming(7,4)?",
    shortAnswer: "4/7 ≈ 0.571, meaning 57% of the bits are data, 43% are overhead.",
    explanation: "Code rate = k / n. Lower rate means more redundancy but stronger error protection.",
    hint: "Higher rate = less overhead, weaker protection.",
    level: "basic",
  },
  {
    question: "What is the difference between Hamming code and Reed‑Solomon?",
    shortAnswer: "Hamming corrects single bits; Reed‑Solomon corrects bursts of errors (symbol errors) and is used in QR codes, CDs, DVDs.",
    explanation: "Reed‑Solomon works on symbols (e.g., bytes) rather than bits and can correct multiple symbol errors. It's more powerful but also more complex.",
    hint: "Hamming is for random bit errors; Reed‑Solomon for burst errors (like scratches).",
    level: "moderate",
  },
  {
    question: "Why can't Hamming code be used to correct errors in a high‑error‑rate channel like deep space?",
    shortAnswer: "Hamming code corrects only single errors. Deep space channels often experience longer burst errors or higher error rates, requiring stronger codes like convolutional or turbo codes.",
    explanation: "For deep space, the signal‑to‑noise ratio is very low, causing many errors. Codes with higher Hamming distance (e.g., Reed‑Solomon, LDPC) are needed.",
    hint: "One error per codeword is too optimistic for space.",
    level: "moderate",
  },
  {
    question: "What is the 'Hamming bound' (sphere‑packing bound)?",
    shortAnswer: "A bound on the number of codewords in a code with given length and error correction capability, based on the idea that Hamming spheres of radius t (correctable errors) around each codeword must be disjoint.",
    explanation: "For a perfect code, the spheres exactly cover the space. Hamming codes are perfect codes because they achieve the Hamming bound for t=1.",
    hint: "Perfect codes pack the space with no gaps and no overlaps.",
    level: "expert",
  },
  {
    question: "What is the generator matrix for Hamming(7,4)?",
    shortAnswer: "A 4×7 matrix G = [I₄ | P], where P is a 4×3 matrix whose columns are the binary representations of positions 1..7 excluding the power‑of‑two columns.",
    explanation: "Multiplying the data vector (1×4) by G gives the codeword. The parity‑check matrix H is [Pᵀ | I₃] and satisfies G·Hᵀ = 0.",
    hint: "The columns of H are all non‑zero 3‑bit binary vectors, which is the defining property.",
    level: "expert",
    codeExample: "// In MATLAB: G = [1 0 0 0 1 1 1; 0 1 0 0 0 1 1; 0 0 1 0 1 0 1; 0 0 0 1 1 1 0]"
  },
  {
    question: "What is a perfect code?",
    shortAnswer: "A code that exactly fills the Hamming space with disjoint spheres of radius t; no unused vectors.",
    explanation: "Hamming codes (binary) are perfect for t=1. The only other binary perfect codes are repetition codes and the Golay (23,12) code.",
    hint: "Every possible received vector is either a codeword or lies within distance 1 of exactly one codeword.",
    level: "expert",
  },
  {
    question: "How does Hamming code handle a situation where the syndrome points to a parity bit?",
    shortAnswer: "If the syndrome equals the position of a parity bit (e.g., 1,2,4), that parity bit itself is corrupted, and the data bits remain correct.",
    explanation: "The decoder still flips that parity bit (since the syndrome says so). Flipping a parity bit does not alter the final data extraction. The data bits are unaffected.",
    hint: "Parity bits are part of the codeword; they can also be corrected.",
    level: "moderate",
  },
  {
    question: "What is the difference between systematic and non‑systematic Hamming codes?",
    shortAnswer: "Systematic codes keep the original data bits unchanged in the codeword (and add parity separately). Non‑systematic codes mix data and parity.",
    explanation: "Hamming(7,4) as usually taught is systematic: data bits occupy positions 3,5,6,7 (or 5,6,7,8). Non‑systematic forms exist but are rarely used because systematic simplifies extraction.",
    hint: "Systematic = you can read the original data directly from fixed positions.",
    level: "moderate",
  },
  {
    question: "Can Hamming code be used to correct errors in a 64‑bit memory word?",
    shortAnswer: "Yes, by using a Hamming code with enough parity bits: 7 parity bits for 64 data bits (72 total, Hamming(72,64) – actually SECDED needs 8 parity bits for single correction and double detection).",
    explanation: "ECC DIMMs typically use (72,64) SECDED codes, which are shortened Hamming codes (from a (127,120) Hamming code).",
    hint: "The formula 2^r ≥ 64 + r + 1 gives r=7 for pure correction, but SECDED requires r=8.",
    level: "expert",
  },
  {
    question: "What happens if a Hamming(7,4) decoder receives a codeword with three errors?",
    shortAnswer: "It will likely miscorrect (produce a wrong data word) because the syndrome will point to some bit, but flipping it will not recover the original.",
    explanation: "Three errors may bring the received vector within distance 1 of a different codeword. The syndrome will be non‑zero and the decoder will 'correct' the wrong bit, possibly increasing the error count.",
    hint: "The code is only guaranteed to work for up to 1 error.",
    level: "expert",
  },
  {
    question: "How is interleaving used with Hamming codes to combat burst errors?",
    shortAnswer: "Interleaving spreads bits from multiple codewords across the burst, so each codeword sees only a single error, which Hamming can correct.",
    explanation: "If you have a burst of 10 errors, you arrange codewords so that the burst hits each codeword at only one position. After deinterleaving, each codeword has one error → correctable.",
    hint: "Interleaving converts a burst into scattered single errors.",
    level: "expert",
  },
  {
    question: "What is the 'parity‑check matrix' H of Hamming(7,4)?",
    shortAnswer: "A 3×7 matrix where the columns are all non‑zero 3‑bit vectors (except possibly reordered).",
    explanation: "For a systematic code, H = [Pᵀ | I₃]. The syndrome s = r·Hᵀ gives the error position (as a binary number).",
    hint: "The columns of H are just the numbers 1..7 in binary.",
    level: "expert",
  },
  {
    question: "Why is Hamming code called 'perfect'?",
    shortAnswer: "Because the Hamming spheres of radius 1 around each codeword exactly partition the whole space of 2^n binary vectors without overlap and without gaps.",
    explanation: "For Hamming(7,4): each sphere contains 1 + 7 = 8 vectors. There are 2^4 = 16 codewords. 16×8 = 128 = 2^7 – the whole space. No vector is left uncovered, and no vector belongs to two spheres.",
    hint: "It's a perfect tiling of the binary hypercube.",
    level: "expert",
  },
  {
    question: "What is the relationship between Hamming code and the (7,4) code used in early modems?",
    shortAnswer: "Bell System modems in the 1970s used Hamming(7,4) for error correction on voice‑band lines (e.g., Bell 202).",
    explanation: "It was one of the first practical applications of error‑correction codes in commercial communication systems.",
    hint: "Hamming's work saved billions of dollars in phone network reliability.",
    level: "moderate",
  },
  {
    question: "How would you implement a Hamming(7,4) encoder in hardware?",
    shortAnswer: "Using XOR gates: each parity bit is the XOR of specific data bits according to the parity matrix.",
    explanation: "For example, p₁ = d₁ ⊕ d₂ ⊕ d₄. This can be done with a few logic gates. Such an encoder has near‑zero latency.",
    hint: "XOR trees are simple and fast.",
    level: "expert",
  },
  {
    question: "What is the 'syndrome decoding' method?",
    shortAnswer: "A method where a precomputed table maps syndromes to error positions, used to avoid recomputing parity each time.",
    explanation: "For a small code like Hamming(7,4), syndrome decoding can be implemented as a simple lookup table or algebraic formula (syndrome = error position).",
    hint: "Instead of solving equations, you look up the error location from the syndrome.",
    level: "moderate",
  },
  {
    question: "Does Hamming code require a lot of buffer memory at the receiver?",
    shortAnswer: "No, it's a block code that works on isolated blocks (e.g., 7 bits). No long buffer is needed beyond the block size.",
    explanation: "Unlike convolutional codes that have memory, block codes process each block independently. This makes them simpler for hardware.",
    hint: "Hamming is like fixing a misspelled word without looking at the next sentence.",
    level: "basic",
  },
  {
    question: "Can Hamming code be used for error detection only (without correction)?",
    shortAnswer: "Yes, but it's inefficient. You'd get detection of up to 2 errors, but you could achieve that with a simpler parity code.",
    explanation: "However, if you already have a Hamming encoder for correction, you can choose to only flag errors (without correcting) by checking the syndrome.",
    hint: "You don't have to use the correction capability.",
    level: "moderate",
  },
  {
    question: "What is 'soft‑decision decoding' and why is it not used with Hamming?",
    shortAnswer: "Soft‑decision uses analogue signal levels (confidence) to improve decoding. Hamming is a hard‑decision code; soft decoding would require different codes (like convolutional).",
    explanation: "Hamming code assumes bits are already quantised to 0/1. Soft decoding needs codes with different design (e.g., Viterbi decoding).",
    hint: "Hamming is designed for clean binary inputs.",
    level: "expert",
  },
  {
    question: "What is a 'shortened Hamming code'?",
    shortAnswer: "A Hamming code with some data bits set to zero (or not transmitted) to achieve a different block length.",
    explanation: "For example, Hamming(127,120) can be shortened to (72,64) by setting 56 data bits to zero. This is used in ECC memory.",
    hint: "Shortening reduces the block size while keeping the same error correction power relative to the shortened length.",
    level: "expert",
  }
];

export default questions;