#!/usr/bin/env bash
# ==============================================================================
# BASH LAB: SQUASH MERGING MECHANICS (git merge --squash)
# MODULE: 002_002_merging-strategies-and-conflict-resolution (Topic 10)
# INSTRUCTOR: Sukanta Hui (Coder & AccoTax, Barrackpore)
# ==============================================================================

set -euo pipefail

LAB_DIR="$HOME/git_squash_merge_lab"
echo "=== Step 1: Initializing Sandbox Repository at $LAB_DIR ==="
rm -rf "$LAB_DIR"
mkdir -p "$LAB_DIR"
cd "$LAB_DIR"

git init -b main
git config user.name "Sukanta Hui"
git config user.email "sukanta@coderaccotax.in"

echo "=== Step 2: Creating Base Project Commit ==="
echo "console.log('Coder & AccoTax System - Barrackpore');" > app.js
git add app.js
git commit -m "feat: initial project setup"

echo "=== Step 3: Creating Feature Branch with 4 Messy WIP Commits ==="
git switch -c feature/invoice-generator

echo "// WIP step 1" >> invoice.js
git add invoice.js
git commit -m "WIP: add invoice draft file"

echo "// WIP step 2: add header function" >> invoice.js
git commit -am "wip: add header logic"

echo "// WIP step 3: fix typo in header" >> invoice.js
git commit -am "fix: typo in calculation"

echo "function generateGSTInvoice(amount) { return amount * 1.18; }" >> invoice.js
git commit -am "feat: finish GST 18% calculation engine"

echo ""
echo "=== Step 4: Inspecting Feature Branch Commit Log (4 commits) ==="
git log --oneline main..feature/invoice-generator

echo ""
echo "=== Step 5: Switching to main and Executing Squash Merge ==="
git switch main
git merge --squash feature/invoice-generator

echo ""
echo "--- Inspecting git status after --squash (Notice files are staged, NOT committed!) ---"
git status

echo ""
echo "--- Inspecting .git/SQUASH_MSG generated by Git ---"
cat .git/SQUASH_MSG

echo ""
echo "=== Step 6: Creating the Consolidated Atomic Commit ==="
git commit -m "feat(invoice): implement comprehensive GST invoice generation engine (18% slab)"

echo ""
echo "=== Step 7: Verifying Commit Parents (Must be exactly 1 parent, NOT 2!) ==="
PARENT_COUNT=$(git rev-list --parents -n 1 HEAD | wc -w)
echo "Parent count for new commit (inclusive of commit SHA): $PARENT_COUNT (Expected: 2 tokens = 1 parent commit)"

echo ""
echo "=== Step 8: Inspecting Final Clean Linear Log Graph on main ==="
git log --graph --oneline

echo ""
echo "=== Step 9: Safe Cleanup of Feature Branch ==="
git branch -D feature/invoice-generator
echo "Feature branch deleted cleanly. Repository log remains perfectly linear!"

echo "=== Lab Complete: Squash merge mechanics verified successfully! ==="
