<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
    <title>Dynamic HTML Elements</title>
</head>
<body>
    <h2>Dynamic Element Generation</h2>
    
    <c:set var="tagName" value="div" scope="request" />
    <c:set var="cssClass" value="highlight" scope="request" />
    
    <jsp:element name="${tagName}">
        <jsp:attribute name="class">${cssClass}</jsp:attribute>
        <jsp:attribute name="id">dynamicBox</jsp:attribute>
        <jsp:body>
            This content is generated by &lt;jsp:element&gt; and &lt;jsp:body&gt;.
            Tag name and attributes are decided at runtime.
        </jsp:body>
    </jsp:element>
    
    <!-- You can also create input fields dynamically -->
    <c:forEach var="field" items="['username', 'email', 'phone']">
        <jsp:element name="input">
            <jsp:attribute name="type">text</jsp:attribute>
            <jsp:attribute name="name">${field}</jsp:attribute>
            <jsp:attribute name="placeholder">Enter ${field}</jsp:attribute>
        </jsp:element>
        <br/>
    </c:forEach>
</body>
</html>