// topic13_questions.js
// 30 FAQs on "Step-by-Step Examples" – basic to expert.

const questions = [
  {
    question: "What is the main purpose of tracing the conversion algorithm?",
    shortAnswer: "To understand how the stack and output evolve at each step.",
    explanation: "Tracing helps build intuition for the algorithm's behavior.",
    hint: "It shows the process, not just the result.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "In the trace, what happens to an operand?",
    shortAnswer: "It is immediately appended to the output.",
    explanation: "Operands never wait on the stack.",
    hint: "Output directly.",
    level: "basic",
    codeExample: "A → output: A",
  },
  {
    question: "What happens to a left parenthesis in the trace?",
    shortAnswer: "It is pushed onto the stack.",
    explanation: "It acts as a marker for the start of a sub‑expression.",
    hint: "Push.",
    level: "basic",
    codeExample: "( → stack: [ ( ]",
  },
  {
    question: "What happens to a right parenthesis in the trace?",
    shortAnswer: "Operators are popped from the stack until a '(' is found; then the '(' is discarded.",
    explanation: "This completes the sub‑expression.",
    hint: "Pop until '('.",
    level: "basic",
    codeExample: ") → stack: [ + ] → output: AB+",
  },
  {
    question: "What happens when an operator is encountered?",
    shortAnswer: "The algorithm pops operators of higher or equal precedence (for left‑associative) from the stack, then pushes the new operator.",
    explanation: "This maintains the correct order.",
    hint: "Pop, then push.",
    level: "intermediate",
    codeExample: "+ → stack: [ * ] → pop *, push +",
  },
  {
    question: "Why do we pop operators of equal precedence for left‑associative operators?",
    shortAnswer: "Because left‑associative operators evaluate left‑to‑right, so the earlier operator should be output first.",
    explanation: "Example: A-B-C → (A-B)-C.",
    hint: "Left‑to‑right.",
    level: "advanced",
    codeExample: "A-B-C → A B - C -",
  },
  {
    question: "What is the trace for `A+B`?",
    shortAnswer: "A → output; + → push; B → output; end → pop + → AB+",
    explanation: "Simple case with no precedence conflict.",
    hint: "Follow the rules.",
    level: "basic",
    codeExample: "AB+",
  },
  {
    question: "What is the trace for `A+B*C`?",
    shortAnswer: "A→output; +→push; B→output; *→push (higher); C→output; end→pop *→output, pop +→output → ABC*+",
    explanation: "Multiplication has higher precedence, so it stays on top.",
    hint: "Precedence.",
    level: "intermediate",
    codeExample: "ABC*+",
  },
  {
    question: "What is the trace for `(A+B)*C`?",
    shortAnswer: "( → push; A→output; +→push; B→output; ) → pop +, discard '('; *→push; C→output; end→pop * → AB+C*",
    explanation: "Parentheses force addition first.",
    hint: "Parentheses override.",
    level: "intermediate",
    codeExample: "AB+C*",
  },
  {
    question: "What is the trace for `A*B+C*D`?",
    shortAnswer: "A→output; *→push; B→output; +→pop * (higher), push +; C→output; *→push; D→output; end→pop *, pop + → AB*CD*+",
    explanation: "Multiplication first, then addition.",
    hint: "Precedence.",
    level: "advanced",
    codeExample: "AB*CD*+",
  },
  {
    question: "How can you verify your manual trace?",
    shortAnswer: "Implement the algorithm and compare its output to your trace.",
    explanation: "This confirms your understanding.",
    hint: "Code it.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What does the stack contain at each step?",
    shortAnswer: "It contains operators and parentheses that have been seen but not yet output.",
    explanation: "The stack is the temporary storage.",
    hint: "Waiting area.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What does the output contain at each step?",
    shortAnswer: "The partially built postfix expression.",
    explanation: "It grows as tokens are processed.",
    hint: "Growing output.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "Can you trace an expression with exponentiation (^)?",
    shortAnswer: "Yes, but remember that ^ is right‑associative, so equal precedence is NOT popped.",
    explanation: "Example: A^B^C → A B C ^ ^.",
    hint: "Right‑associative.",
    level: "advanced",
    codeExample: "A^B^C → A B C ^ ^",
  },
  {
    question: "What is the trace for `A-B-C`?",
    shortAnswer: "A→output; -→push; B→output; -→pop - (equal, left‑assoc), push -; C→output; end→pop - → AB-C-",
    explanation: "Subtraction is left‑associative.",
    hint: "Left‑associative.",
    level: "intermediate",
    codeExample: "AB-C-",
  },
  {
    question: "What is the trace for `A^B^C`?",
    shortAnswer: "A→output; ^→push; B→output; ^→push (right‑assoc, so no pop); C→output; end→pop ^, pop ^ → ABC^^",
    explanation: "Exponentiation is right‑associative.",
    hint: "Right‑associative.",
    level: "advanced",
    codeExample: "ABC^^",
  },
  {
    question: "What is the trace for `(A+B)*(C-D)`?",
    shortAnswer: "Complex; follows parentheses and precedence.",
    explanation: "Each sub‑expression is converted, then combined.",
    hint: "Multiple parentheses.",
    level: "advanced",
    codeExample: "AB+CD-*",
  },
  {
    question: "What is the trace for `A*(B+C)-D/E`?",
    shortAnswer: "Parentheses first, then multiplication, division, subtraction.",
    explanation: "A B C + * D E / -",
    hint: "Follow precedence.",
    level: "advanced",
    codeExample: "A B C + * D E / -",
  },
  {
    question: "What is the purpose of the trace in learning?",
    shortAnswer: "To build a mental model of how the algorithm works.",
    explanation: "Tracing is a proven teaching technique.",
    hint: "Learning aid.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "How do you handle spaces in the input during tracing?",
    shortAnswer: "Spaces are ignored.",
    explanation: "They are not part of the expression.",
    hint: "Ignore.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What happens if you encounter a mismatched parenthesis during tracing?",
    shortAnswer: "An error is raised.",
    explanation: "The expression is invalid.",
    hint: "Error.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "Can you trace an expression with multi‑character operands?",
    shortAnswer: "Yes, but you need to treat them as whole tokens.",
    explanation: "Modify the scanner to read words.",
    hint: "Tokenize.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "What is the trace for `A+B*C-D`?",
    shortAnswer: "A→out; +→push; B→out; *→push; C→out; -→pop * (higher), pop + (equal), push -; D→out; end→pop - → ABC*+D-",
    explanation: "Precedence and associativity.",
    hint: "Follow the rules.",
    level: "advanced",
    codeExample: "ABC*+D-",
  },
  {
    question: "What is the trace for `(A+B)*(C-D)+E`?",
    shortAnswer: "AB+CD-*E+",
    explanation: "Parentheses first, then multiplication, then addition.",
    hint: "Complex.",
    level: "advanced",
    codeExample: "AB+CD-*E+",
  },
  {
    question: "How does the trace change if the expression is right‑associative?",
    shortAnswer: "Equal precedence operators are not popped.",
    explanation: "Example: A^B^C.",
    hint: "Right‑associative.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "What is the trace for `A+B*C-D/E`?",
    shortAnswer: "ABC*+DE/-",
    explanation: "Multiplication, division, then addition/subtraction.",
    hint: "Precedence.",
    level: "advanced",
    codeExample: "ABC*+DE/-",
  },
  {
    question: "Can you trace an expression with logical operators?",
    shortAnswer: "Yes, using the same rules if precedence is defined.",
    explanation: "Logical AND/OR have lower precedence than relational.",
    hint: "Same algorithm.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "What is the trace for `A>B && C<D`?",
    shortAnswer: "AB>CD<&&",
    explanation: "Relationals first, then AND.",
    hint: "Precedence.",
    level: "advanced",
    codeExample: "AB>CD<&&",
  },
  {
    question: "How do you trace unary minus?",
    shortAnswer: "It requires special handling; typically, it's treated as a separate token with high precedence.",
    explanation: "Unary minus is not handled by the basic algorithm.",
    hint: "Special case.",
    level: "expert",
    codeExample: "Not applicable",
  },
  {
    question: "What is the value of tracing with a debugger?",
    shortAnswer: "It shows the exact state of the stack and output, helping identify bugs.",
    explanation: "Useful for debugging your own implementation.",
    hint: "Debugging tool.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "Can you trace an expression with implicit multiplication (e.g., 2x)?",
    shortAnswer: "The algorithm assumes explicit operators; implicit multiplication must be handled by a pre‑processor.",
    explanation: "Most algorithms require explicit operators.",
    hint: "Explicit.",
    level: "advanced",
    codeExample: "Not applicable",
  },
];

export default questions;