// topic2_questions.js
// 30 FAQs on "What is an Operator?" – basic to expert.

const questions = [
  {
    question: "What is an operator in programming?",
    shortAnswer: "An operator is a symbol that performs an operation on one or more operands to produce a result.",
    explanation: "Operators are the fundamental building blocks of expressions. They tell the computer what action to take with the given data.",
    hint: "Think of them as the verbs in a sentence.",
    level: "basic",
    codeExample: "int result = 5 + 3; // + is the operator",
  },
  {
    question: "What are the different categories of operators in Java?",
    shortAnswer: "Arithmetic, relational, logical, assignment, unary, ternary, bitwise, and shift operators.",
    explanation: "Java has a rich set of operators, each designed for specific kinds of operations.",
    hint: "Try to classify operators you use frequently.",
    level: "basic",
    codeExample: "// Arithmetic: +, -, *, /, %\n// Relational: ==, !=, >, <, >=, <=",
  },
  {
    question: "What is the difference between unary, binary, and ternary operators?",
    shortAnswer: "Unary operators act on one operand, binary on two, and ternary on three (only the conditional operator ?:).",
    explanation: "The number of operands defines the arity of the operator.",
    hint: "Count the operands around the operator.",
    level: "basic",
    codeExample: "int a = -5; // unary minus\nint b = a + 3; // binary +\nint max = (a>b)?a:b; // ternary",
  },
  {
    question: "What is the assignment operator?",
    shortAnswer: "The assignment operator `=` assigns the value of the right operand to the left operand.",
    explanation: "It is not equality; it stores the value in the variable.",
    hint: "It's the most common operator and often confused with `==`.",
    level: "basic",
    codeExample: "int x = 10; // assigns 10 to x",
  },
  {
    question: "What is the difference between `=` and `==`?",
    shortAnswer: "`=` is assignment, `==` is equality comparison.",
    explanation: "Using `=` in a conditional is a classic bug; the compiler may not catch it.",
    hint: "If you see `if (x = 5)`, it's probably wrong.",
    level: "basic",
    codeExample: "if (x == 5) { } // correct\nif (x = 5) { } // assignment, not comparison",
  },
  {
    question: "What are compound assignment operators?",
    shortAnswer: "Operators like `+=`, `-=`, `*=`, `/=` that combine assignment with an arithmetic operation.",
    explanation: "They are shorthand: `x += 5` is equivalent to `x = x + 5`.",
    hint: "They make the code shorter and often clearer.",
    level: "intermediate",
    codeExample: "int count = 0;\ncount += 10; // count becomes 10",
  },
  {
    question: "What is the ternary operator?",
    shortAnswer: "The ternary operator `? :` is a conditional operator that takes three operands and returns one of two values based on a condition.",
    explanation: "Syntax: `condition ? valueIfTrue : valueIfFalse`.",
    hint: "It's like a compact if‑else.",
    level: "intermediate",
    codeExample: "int max = (a > b) ? a : b;",
  },
  {
    question: "What is short‑circuit evaluation?",
    shortAnswer: "In `&&` and `||`, the second operand is evaluated only if needed to determine the result.",
    explanation: "For `&&`, if the first operand is false, the result is false without evaluating the second. For `||`, if the first is true, the result is true.",
    hint: "This can prevent null pointer exceptions.",
    level: "intermediate",
    codeExample: "if (obj != null && obj.isValid()) { }",
  },
  {
    question: "What is integer division?",
    shortAnswer: "Integer division occurs when both operands are integers; the result is truncated (floor for positive numbers).",
    explanation: "For example, `5 / 2` yields `2`, not `2.5`. To get a floating‑point result, use `5 / 2.0`.",
    hint: "If you need exact division, promote one operand to double.",
    level: "basic",
    codeExample: "double result = 5 / 2.0; // 2.5",
  },
  {
    question: "What is the modulo operator?",
    shortAnswer: "The modulo operator `%` returns the remainder of a division.",
    explanation: "For example, `10 % 3` equals `1`. It's often used to check evenness (`n % 2 == 0`).",
    hint: "Think of it as the leftover after division.",
    level: "basic",
    codeExample: "int rem = 7 % 3; // 1",
  },
  {
    question: "What are logical operators?",
    shortAnswer: "Logical operators are `&&` (AND), `||` (OR), and `!` (NOT), used to combine boolean expressions.",
    explanation: "They produce a boolean result based on the truth values of their operands.",
    hint: "They are essential for decision making.",
    level: "basic",
    codeExample: "boolean canDrive = (age >= 18) && hasLicense;",
  },
  {
    question: "What is the difference between `&` and `&&`?",
    shortAnswer: "`&` is bitwise AND (also can be used as logical AND without short‑circuit), while `&&` is short‑circuit logical AND.",
    explanation: "For boolean operands, `&` always evaluates both sides; `&&` may skip the second if the first is false.",
    hint: "Prefer `&&` for conditionals.",
    level: "intermediate",
    codeExample: "if (a != null && a.length() > 0) // safe\nif (a != null & a.length() > 0) // may cause NPE if a is null",
  },
  {
    question: "What are bitwise operators?",
    shortAnswer: "Bitwise operators (`&`, `|`, `^`, `~`, `<<`, `>>`, `>>>`) operate on individual bits of integer operands.",
    explanation: "They are used for low‑level manipulation of binary data, e.g., for flags or optimizations.",
    hint: "Use them only when you need bit‑level control.",
    level: "advanced",
    codeExample: "int flags = 0b1010;\nint masked = flags & 0b1000; // extract bit",
  },
  {
    question: "What is operator precedence?",
    shortAnswer: "Operator precedence determines the order in which operators are applied in an expression.",
    explanation: "For example, multiplication has higher precedence than addition, so `a + b * c` is `a + (b * c)`.",
    hint: "Use parentheses to make precedence explicit.",
    level: "basic",
    codeExample: "int result = 5 + 3 * 2; // 11, not 16",
  },
  {
    question: "What is operator associativity?",
    shortAnswer: "Associativity defines the order in which operators of the same precedence are evaluated (left‑to‑right or right‑to‑left).",
    explanation: "Most operators are left‑associative, meaning `a - b - c` is `(a - b) - c`. Assignment is right‑associative.",
    hint: "Remember that parentheses override associativity.",
    level: "intermediate",
    codeExample: "int a = b = c = 5; // right‑associative: c=5, b=c, a=b",
  },
  {
    question: "What is the `instanceof` operator?",
    shortAnswer: "`instanceof` checks whether an object is an instance of a specific class or interface.",
    explanation: "It returns true if the object is of that type or a subtype.",
    hint: "Use it before casting to avoid ClassCastException.",
    level: "intermediate",
    codeExample: "if (obj instanceof String) { String s = (String) obj; }",
  },
  {
    question: "What are the shift operators?",
    shortAnswer: "`<<` (left shift), `>>` (signed right shift), and `>>>` (unsigned right shift) move bits left or right.",
    explanation: "They are used for efficient multiplication/division by powers of two (e.g., `x << 2` multiplies by 4).",
    hint: "Be careful with sign extension in right shifts.",
    level: "advanced",
    codeExample: "int y = 8 << 1; // 16",
  },
  {
    question: "Can you use `+` with strings?",
    shortAnswer: "Yes, `+` concatenates strings in Java.",
    explanation: "If at least one operand is a String, the other is converted to a string and concatenated.",
    hint: "Using `+` in a loop can be inefficient; use StringBuilder.",
    level: "basic",
    codeExample: "String message = \"Hello, \" + name;",
  },
  {
    question: "What is the increment operator?",
    shortAnswer: "`++` increases the variable by 1. Prefix `++i` increments then uses; postfix `i++` uses then increments.",
    explanation: "They are unary operators with side effects.",
    hint: "Use them carefully in complex expressions.",
    level: "intermediate",
    codeExample: "int i = 5;\nint a = ++i; // a=6, i=6\nint b = i++; // b=6, i=7",
  },
  {
    question: "What is the decrement operator?",
    shortAnswer: "`--` decreases the variable by 1, with prefix and postfix variants like `++`.",
    explanation: "They work similarly to increment but in the opposite direction.",
    hint: "Same caution applies.",
    level: "intermediate",
    codeExample: "int j = 5;\nint c = --j; // c=4, j=4",
  },
  {
    question: "What is the conditional operator's return type?",
    shortAnswer: "The result type is the type of the second and third operands (after numeric promotion).",
    explanation: "If the two operands have different types, the result is the more general type (e.g., if one is int and the other double, result is double).",
    hint: "The type is determined at compile time.",
    level: "advanced",
    codeExample: "double d = (x > 5) ? 10 : 3.14; // result is double",
  },
  {
    question: "What are the common mistakes with operators?",
    shortAnswer: "Misusing `=` instead of `==`, integer division truncation, precedence errors, and side‑effects in complex expressions.",
    explanation: "These can lead to subtle bugs that are hard to track.",
    hint: "Use static analysis tools to catch such mistakes.",
    level: "intermediate",
    codeExample: "// Mistake: if (x = 5) ...",
  },
  {
    question: "Can operators be overloaded in Java?",
    shortAnswer: "Java does not allow user‑defined operator overloading, except for the `+` operator which is overloaded for strings.",
    explanation: "Operator overloading is not supported in Java to keep the language simple.",
    hint: "Unlike C++, Java limits operator overloading.",
    level: "advanced",
    codeExample: "// Only + is overloaded for String",
  },
  {
    question: "What is the `new` operator?",
    shortAnswer: "The `new` operator creates a new object instance and returns a reference to it.",
    explanation: "It allocates memory and invokes the constructor.",
    hint: "Used to instantiate classes.",
    level: "basic",
    codeExample: "Student s = new Student();",
  },
  {
    question: "What is the `cast` operator?",
    shortAnswer: "The cast operator `(type)` explicitly converts a value from one type to another.",
    explanation: "It's used to downcast or to force a numeric conversion.",
    hint: "Be careful with class casts to avoid ClassCastException.",
    level: "intermediate",
    codeExample: "double d = 5.7;\nint i = (int) d; // i = 5 (truncates)",
  },
  {
    question: "What is the purpose of the `+` operator with numbers?",
    shortAnswer: "It performs addition of numeric types.",
    explanation: "If both operands are numeric, `+` adds them. If one is a string, it concatenates.",
    hint: "The behavior depends on the operand types.",
    level: "basic",
    codeExample: "int sum = 5 + 3; // 8",
  },
  {
    question: "What is the difference between `&` and `|` vs `&&` and `||`?",
    shortAnswer: "`&` and `|` are bitwise operators (or logical without short‑circuit if operands are booleans), while `&&` and `||` are short‑circuit logical operators.",
    explanation: "Prefer `&&` and `||` for boolean logic to get short‑circuit evaluation.",
    hint: "Use `&` for bitwise operations.",
    level: "intermediate",
    codeExample: "boolean b = (a > 5) & (b < 10); // no short‑circuit\nboolean c = (a > 5) && (b < 10); // short‑circuit",
  },
  {
    question: "What is the `!` operator used for?",
    shortAnswer: "The `!` operator negates a boolean value (true becomes false, false becomes true).",
    explanation: "It is a unary logical NOT operator.",
    hint: "Use it to invert conditions.",
    level: "basic",
    codeExample: "boolean isClosed = !isOpen;",
  },
  {
    question: "What is the role of operators in expression evaluation?",
    shortAnswer: "Operators define the operations to be performed on operands; they are the core of expression evaluation.",
    explanation: "The evaluation process involves applying operators according to precedence and associativity.",
    hint: "This is the foundation of computation.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "How does Java handle type promotion in expressions?",
    shortAnswer: "Java promotes operands to the type that can represent all possible values without loss (binary numeric promotion).",
    explanation: "For example, if one operand is double, the other becomes double; if one is float, the other becomes float; etc.",
    hint: "This avoids loss of precision.",
    level: "intermediate",
    codeExample: "double result = 5 + 2.3; // int 5 promoted to double",
  },
  {
    question: "What is the `instanceof` operator's return type?",
    shortAnswer: "`instanceof` returns a boolean.",
    explanation: "It's used to test the type of an object at runtime.",
    hint: "Commonly used before casting.",
    level: "intermediate",
    codeExample: "if (obj instanceof String) { ... }",
  },
];

export default questions;