const questions = [
  {
    "id": "q1",
    "question": "Q1: What is a Virtual Shopping Cart in an E-Commerce web application?",
    "options": [
      "A software component that temporarily holds, organizes, and calculates totals for items selected by a customer before checkout",
      "A physical metal trolley wheeled inside a supermarket",
      "A database table that stores only customer passwords",
      "A browser extension that deletes search history"
    ],
    "answer": "A software component that temporarily holds, organizes, and calculates totals for items selected by a customer before checkout",
    "explanation": "A virtual shopping cart acts as an online container that tracks products, quantities, prices, taxes, and discounts during a shopping session.",
    "explanationBn": "ভার্চুয়াল শপিং কার্ট হলো এমন একটি সফটওয়্যার যা চেকআউটের পূর্বে ক্রেতার পছন্দের পণ্য ও মোট মূল্য হিসাব রাখে।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Easy",
    "hint": "A software component that temporarily holds..."
  },
  {
    "id": "q2",
    "question": "Q2: Which technology is primarily used by web browsers to preserve the contents of a shopping cart across page navigation?",
    "options": [
      "HTTP Cookies, Session Storage, or Server-Side Session IDs",
      "Computer BIOS ROM memory",
      "Static CSS stylesheets",
      "Physical hard disk partition tables"
    ],
    "answer": "HTTP Cookies, Session Storage, or Server-Side Session IDs",
    "explanation": "Because HTTP is a stateless protocol, session cookies and backend session stores maintain the user's cart state across different product pages.",
    "explanationBn": "HTTP একটি স্টেটলেস প্রোটোকল হওয়ায় সেশন কুকি বা সার্ভার সেশন কার্টের ডেটা মনে রাখে।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Medium",
    "hint": "HTTP Cookies, Session Storage..."
  },
  {
    "id": "q3",
    "question": "Q3: Which of the following operations is NOT typically supported by a standard virtual shopping cart?",
    "options": [
      "Permanently modifying the manufacturer's wholesale cost in the central database",
      "Increasing or decreasing product quantity",
      "Removing unwanted items from the list",
      "Applying promotional discount coupon codes"
    ],
    "answer": "Permanently modifying the manufacturer's wholesale cost in the central database",
    "explanation": "A customer cannot alter base product pricing in the database; they can only adjust quantity, remove items, or enter valid coupon codes.",
    "explanationBn": "ক্রেতা কার্টের মাধ্যমে পণ্যের মূল ডেটাবেজ প্রাইস পরিবর্তন করতে পারেন না।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Easy",
    "hint": "Permanently modifying the manufacturer's..."
  },
  {
    "id": "q4",
    "question": "Q4: What happens during the 'Checkout' phase in a shopping cart workflow?",
    "options": [
      "The user confirms the shipping address, chooses payment method, and enters the secure payment gateway",
      "The user's computer automatically reboots",
      "All items in the cart are permanently deleted without payment",
      "The web browser uninstalls itself"
    ],
    "answer": "The user confirms the shipping address, chooses payment method, and enters the secure payment gateway",
    "explanation": "Checkout transitions the user from item selection to delivery address validation and secure payment processing.",
    "explanationBn": "চেকআউট ধাপে ডেলিভারি ঠিকানা নিশ্চিত করে পেমেন্ট গেটওয়েতে অর্থ পরিশোধ করা হয়।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Easy",
    "hint": "The user confirms the shipping address..."
  },
  {
    "id": "q5",
    "question": "Q5: How does a shopping cart dynamically calculate the final payable amount?",
    "options": [
      "Total = (Sum of Unit Prices x Quantities) - Discounts + Applicable Taxes (GST) + Shipping Charges",
      "Total = Multiplied product IDs only",
      "Total = Fixed ₹100 flat fee regardless of cart items",
      "Total = Random price generated by the server clock"
    ],
    "answer": "Total = (Sum of Unit Prices x Quantities) - Discounts + Applicable Taxes (GST) + Shipping Charges",
    "explanation": "The cart calculates the itemized subtotal, deducts coupon discounts, adds GST/taxes, and appends delivery fees.",
    "explanationBn": "মোট মূল্য = (পণ্যের দাম × সংখ্যা) - ছাড় + জিএসটি ট্যাক্স + ডেলিভারি চার্জ।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Medium",
    "hint": "Total = (Sum of Unit Prices..."
  },
  {
    "id": "q6",
    "question": "Q6: What is 'Cart Abandonment' in e-commerce analytics?",
    "options": [
      "When a shopper adds products to the shopping cart but leaves the website without completing the purchase",
      "When the physical delivery van breaks down",
      "When the server runs out of disk storage",
      "When a buyer deletes their browser bookmark"
    ],
    "answer": "When a shopper adds products to the shopping cart but leaves the website without completing the purchase",
    "explanation": "Cart abandonment occurs when a prospective buyer initiates a checkout process for items in the cart but drops off before completing the transaction.",
    "explanationBn": "কার্ট অ্যাবান্ডনমেন্ট হলো কার্টে জিনিস যুক্ত করার পর না কিনে সাইট ত্যাগ করা।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Medium",
    "hint": "When a shopper adds products..."
  },
  {
    "id": "q7",
    "question": "Q7: Which feature allows an e-commerce platform to alert a buyer if an item in their cart is low in stock?",
    "options": [
      "Real-time Inventory Integration / Stock Quantity Checker",
      "Operating System Task Scheduler",
      "Graphics Card Shader Pipeline",
      "Audio Codec Buffer"
    ],
    "answer": "Real-time Inventory Integration / Stock Quantity Checker",
    "explanation": "The shopping cart interfaces with the backend warehouse database to verify live stock availability.",
    "explanationBn": "লাইভ স্টক চেকার ডেটাবেজের সাথে যোগাযোগ করে পণ্যের মজুদ সংখ্যা জানিয়ে দেয়।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Medium",
    "hint": "Real-time Inventory Integration..."
  },
  {
    "id": "q8",
    "question": "Q8: What is the primary difference between a 'Wishlist' and a 'Shopping Cart'?",
    "options": [
      "A Wishlist is for saving products for long-term future reference; a Shopping Cart is an active queue intended for immediate checkout and purchase",
      "A Wishlist automatically charges the user's credit card daily",
      "A Shopping Cart cannot display product prices",
      "There is no difference between them"
    ],
    "answer": "A Wishlist is for saving products for long-term future reference; a Shopping Cart is an active queue intended for immediate checkout and purchase",
    "explanation": "Wishlists store desired items without pricing obligations, whereas shopping carts aggregate items for immediate transaction processing.",
    "explanationBn": "উইশলিস্ট ভবিষ্যতে কেনার জন্য জিনিস জমিয়ে রাখে, আর কার্ট অবিলম্বে কেনার জন্য তৈরি থাকে।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Easy",
    "hint": "A Wishlist is for saving products..."
  },
  {
    "id": "q9",
    "question": "Q9: When a student adds 3 units of a ₹450 textbook and applies a 10% coupon code with ₹50 shipping, what is the total cart value?",
    "options": [
      "₹1265 (Subtotal: ₹1350 - Discount: ₹135 + Shipping: ₹50)",
      "₹1400",
      "₹900",
      "₹450"
    ],
    "answer": "₹1265 (Subtotal: ₹1350 - Discount: ₹135 + Shipping: ₹50)",
    "explanation": "Subtotal = 3 * 450 = ₹1350. Discount = 10% of 1350 = ₹135. Total = 1350 - 135 + 50 = ₹1265.",
    "explanationBn": "সাবটোটাল = ১৩৫০ টাকা, ১০% ছাড় = ১৩৫ টাকা, মোট = ১৩৫০ - ১৩৫ + ৫০ = ১২৬৫ টাকা।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Medium",
    "hint": "₹1265 (Subtotal: ₹1350..."
  },
  {
    "id": "q10",
    "question": "Q10: Which UI element on an e-commerce navigation header typically indicates the number of items currently in the cart?",
    "options": [
      "Cart Badge / Counter Icon (e.g. cart icon with number badge)",
      "System Clock",
      "Audio Mute Toggle",
      "Browser Refresh Button"
    ],
    "answer": "Cart Badge / Counter Icon (e.g. cart icon with number badge)",
    "explanation": "A badge counter on the top navigation bar gives instant visual feedback on the number of items queued.",
    "explanationBn": "হেডারের কার্ট আইকনের ওপর ব্যাজ কাউন্টার দিয়ে জমা হওয়া পণ্যের সংখ্যা দেখানো হয়।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Easy",
    "hint": "Cart Badge / Counter Icon..."
  },
  {
    "id": "q11",
    "question": "Q11: Why is statelessness in HTTP a challenge for shopping cart design, and how is it resolved?",
    "options": [
      "HTTP does not remember previous requests; solved by attaching unique session tokens / cookies to each request",
      "HTTP cannot transmit images; solved by using FTP",
      "HTTP only works on Windows; solved by installing Linux",
      "HTTP cannot display text; solved by using video"
    ],
    "answer": "HTTP does not remember previous requests; solved by attaching unique session tokens / cookies to each request",
    "explanation": "HTTP is stateless by default. Web applications use session cookies to identify returning client requests and restore cart items.",
    "explanationBn": "HTTP স্টেটলেস হওয়ায় সেশন কুকি ও টোকেনের সাহায্যে প্রতি রিকোয়েস্টে কার্টের ডেটা সনাক্ত করা হয়।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Hard",
    "hint": "HTTP does not remember previous..."
  },
  {
    "id": "q12",
    "question": "Q12: What is the primary purpose of a 'Promo Code / Coupon Code' input field in a shopping cart?",
    "options": [
      "To allow customers to redeem discount vouchers and special promotional rebates",
      "To change the website's default programming language",
      "To delete the server's database logs",
      "To permanently disable online payments"
    ],
    "answer": "To allow customers to redeem discount vouchers and special promotional rebates",
    "explanation": "Coupon code inputs validate promotional rules on the backend and recalculate total payable prices dynamically.",
    "explanationBn": "কুপন কোড দিয়ে গ্রাহক বিভিন্ন অফার ও ছাড়ের সুবিধা পেতে পারেন।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Easy",
    "hint": "To allow customers to redeem discount..."
  },
  {
    "id": "q13",
    "question": "Q13: Which database relationship typically connects a User Cart table to Cart Items in a relational database?",
    "options": [
      "One-to-Many relationship (One User Cart can hold Many Cart Items)",
      "One-to-One relationship only",
      "Many-to-None relationship",
      "No relationship is possible in SQL"
    ],
    "answer": "One-to-Many relationship (One User Cart can hold Many Cart Items)",
    "explanation": "A single cart entity corresponds to multiple product item records referenced via foreign keys.",
    "explanationBn": "একটি শপিং কার্টে একাধিক পণ্য থাকতে পারে, যা ডেটাবেজে 1-to-Many রিলেশনশিপ।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Hard",
    "hint": "One-to-Many relationship..."
  },
  {
    "id": "q14",
    "question": "Q14: What is 'Persistent Cart' functionality in modern e-commerce portals?",
    "options": [
      "The cart contents remain saved even if the user logs out or switches from a laptop to a mobile phone",
      "A cart that cannot be emptied under any circumstances",
      "A cart that charges money every second",
      "A cart that only stores expired items"
    ],
    "answer": "The cart contents remain saved even if the user logs out or switches from a laptop to a mobile phone",
    "explanation": "Persistent carts store items in the user's backend database profile, allowing cross-device synchronization.",
    "explanationBn": "পারসিস্টেন্ট কার্টে ডেটাবেজে পণ্য সেভ থাকে, ফলে ডিভাইস বদলালেও কার্ট খালি হয় না।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Medium",
    "hint": "The cart contents remain saved..."
  },
  {
    "id": "q15",
    "question": "Q15: What security protocol must protect the shopping cart during the checkout and payment phase?",
    "options": [
      "HTTPS / TLS 1.3 Encryption",
      "Unencrypted Telnet",
      "Plain FTP Port 21",
      "Unsecured HTTP Port 80"
    ],
    "answer": "HTTPS / TLS 1.3 Encryption",
    "explanation": "HTTPS encrypts sensitive user addresses and payment parameters preventing eavesdropping and tampering.",
    "explanationBn": "চেকআউট ও পেমেন্টের সময় সংবেদনশীল তথ্য সুরক্ষায় HTTPS ও TLS এনক্রিপশন আবশ্যক।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Medium",
    "hint": "HTTPS / TLS 1.3 Encryption..."
  },
  {
    "id": "q16",
    "question": "Q16: Which feature allows an online shopper to remove an item from the cart and place it in the wishlist with one click?",
    "options": [
      "'Move to Wishlist' / 'Save for Later'",
      "'Delete Account'",
      "'Permanent Wipe'",
      "'Factory Reset'"
    ],
    "answer": "'Move to Wishlist' / 'Save for Later'",
    "explanation": "This feature reduces cart clutter while keeping the item readily accessible for future shopping sessions.",
    "explanationBn": "মুভ টু উইশলিস্ট বা সেভ ফর লেটার দিয়ে পণ্যটি কার্ট থেকে সরিয়ে পরবর্তীতে কেনার জন্য রাখা যায়।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Easy",
    "hint": "'Move to Wishlist' / 'Save for Later'..."
  },
  {
    "id": "q17",
    "question": "Q17: What role does the 'Quantity Increment / Decrement' button play in a virtual cart?",
    "options": [
      "Allows the customer to modify the number of units desired without re-visiting the product listing page",
      "Changes the screen resolution of the monitor",
      "Restarts the user's internet router",
      "Translates the webpage into Latin"
    ],
    "answer": "Allows the customer to modify the number of units desired without re-visiting the product listing page",
    "explanation": "Interactive quantity counters (+ / -) allow instant adjustment of unit volume directly inside the cart view.",
    "explanationBn": "পণ্য সংখ্যার বোতাম (+ / -) দিয়ে কার্টের ভেতরেই সরাসরি পরিমাণ বাড়ানো বা কমানো যায়।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Easy",
    "hint": "Allows the customer to modify..."
  },
  {
    "id": "q18",
    "question": "Q18: In an e-commerce database, which attribute in the `Cart_Items` table links to the `Products` table?",
    "options": [
      "ProductID (Foreign Key referencing Products.ProductID)",
      "UserPasswordHash",
      "CustomerFavoriteColor",
      "BrowserVersionString"
    ],
    "answer": "ProductID (Foreign Key referencing Products.ProductID)",
    "explanation": "The foreign key ProductID maintains referential integrity between cart items and master product catalog records.",
    "explanationBn": "ProductID ফরেন কি হিসেবে কাজ করে এবং প্রোডাক্ট টেবিলের সাথে কার্ট আইটেমের সংযোগ ঘটায়।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Hard",
    "hint": "ProductID (Foreign Key..."
  },
  {
    "id": "q19",
    "question": "Q19: Which of the following is a key reason why customers abandon their shopping carts at checkout?",
    "options": [
      "Unexpected high shipping fees, mandatory registration hurdles, or payment gateway failures",
      "Too many free gifts offered by the store",
      "Prices being reduced automatically by 90%",
      "Faster than expected delivery speeds"
    ],
    "answer": "Unexpected high shipping fees, mandatory registration hurdles, or payment gateway failures",
    "explanation": "Hidden delivery costs and complicated multi-step checkout forms are the primary drivers of cart abandonment.",
    "explanationBn": "অতিরিক্ত ডেলিভারি চার্জ, জটিল চেকআউট ফরম ও পেমেন্ট ব্যর্থতা কার্ট অ্যাবান্ডনমেন্টের প্রধান কারণ।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Medium",
    "hint": "Unexpected high shipping fees..."
  },
  {
    "id": "q20",
    "question": "Q20: What is a 'Mini-Cart' or 'Drawer Cart' in modern web design?",
    "options": [
      "A slide-out side panel that displays cart contents without redirecting the user away from the current shopping page",
      "A cart designed exclusively for miniature toys",
      "A cart with a maximum limit of 1 byte of memory",
      "A physical handheld grocery basket"
    ],
    "answer": "A slide-out side panel that displays cart contents without redirecting the user away from the current shopping page",
    "explanation": "Mini-cart drawers provide a frictionless preview of items, subtotal, and checkout links while keeping the user on the catalog page.",
    "explanationBn": "মিনি-কার্ট হলো সাইডবার ড্রয়ার যা বর্তমান পেজ না ছেড়েই কার্টের সারসংক্ষেপ দেখতে সাহায্য করে।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Medium",
    "hint": "A slide-out side panel that displays..."
  },
  {
    "id": "q21",
    "question": "Q21: How does a shopping cart handle GST (Goods and Services Tax) in Indian e-commerce?",
    "options": [
      "Applies the statutory tax percentage (e.g. 5%, 12%, 18%) to the taxable subtotal and itemizes it on the digital invoice",
      "Deletes the tax amount from all records",
      "Charges 100% tax on every item regardless of category",
      "Redirects the user to a police station"
    ],
    "answer": "Applies the statutory tax percentage (e.g. 5%, 12%, 18%) to the taxable subtotal and itemizes it on the digital invoice",
    "explanation": "Automated tax calculation engines compute precise GST rates based on product HSN/SAC codes.",
    "explanationBn": "পণ্যের ক্যাটাগরি ও HSN কোড অনুযায়ী সরকারি জিএসটি হিসাব করে বিল প্রস্তুত করা হয়।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Medium",
    "hint": "Applies the statutory tax percentage..."
  },
  {
    "id": "q22",
    "question": "Q22: What happens when an item in the cart goes 'Out of Stock' before checkout is finalized?",
    "options": [
      "The cart system flags the item as unavailable and prevents checkout until the item is removed or updated",
      "The server automatically manufactures a replacement item",
      "The customer's bank account is permanently closed",
      "The website shuts down forever"
    ],
    "answer": "The cart system flags the item as unavailable and prevents checkout until the item is removed or updated",
    "explanation": "Concurrency controls prevent overselling by validating live stock levels before authorizing final payment.",
    "explanationBn": "পণ্য স্টক আউট হলে কার্ট সিস্টেম তা চিহ্নিত করে এবং চেকআউটে বাধা দিয়ে সতর্ক করে।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Easy",
    "hint": "The cart system flags the item..."
  },
  {
    "id": "q23",
    "question": "Q23: Which client-side JavaScript event is typically triggered when a user clicks the 'Add to Cart' button?",
    "options": [
      "`onClick` event handler triggering a state update or AJAX/Fetch POST request to the cart API",
      "`onShutdown` system reboot event",
      "`onFormatDrive` disk erase event",
      "`onAudioMute` volume event"
    ],
    "answer": "`onClick` event handler triggering a state update or AJAX/Fetch POST request to the cart API",
    "explanation": "In React/JavaScript, the `onClick` event sends an asynchronous request to update the cart state without reloading the page.",
    "explanationBn": "`onClick` ইভেন্ট হ্যান্ডলারের মাধ্যমে পেজ রিলোড ছাড়াই কার্টে পণ্য যুক্ত করার রিকোয়েস্ট পাঠানো হয়।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Medium",
    "hint": "`onClick` event handler triggering..."
  },
  {
    "id": "q24",
    "question": "Q24: What is 'Free Shipping Threshold' in shopping cart strategy?",
    "options": [
      "A minimum cart subtotal (e.g. 'Add ₹150 more to get FREE Delivery!') incentivizing customers to add more items",
      "A physical weighing scale at the post office",
      "A legal rule banning all shipping trucks",
      "A maximum spending limit enforced on students"
    ],
    "answer": "A minimum cart subtotal (e.g. 'Add ₹150 more to get FREE Delivery!') incentivizing customers to add more items",
    "explanation": "Free shipping thresholds encourage higher Average Order Value (AOV) by offering free delivery above a qualifying cart total.",
    "explanationBn": "একটি নির্দিষ্ট মূল্যের বেশি কেনাকাটা করলে বিনামূল্যে ডেলিভারি দেওয়ার কৌশল (যেমন ₹৪৯৯ এর বেশি কিনলে ফ্রি ডেলিভারি)।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Easy",
    "hint": "A minimum cart subtotal..."
  },
  {
    "id": "q25",
    "question": "Q25: Why is the virtual shopping cart considered the vital bridge between browsing and transaction completion?",
    "options": [
      "Because it aggregates choices, calculates transparent financials, holds inventory, and seamlessly handshakes with payment gateways",
      "Because it is the only page that contains images on the website",
      "Because it allows users to modify the server's source code",
      "Because it operates completely without internet connectivity"
    ],
    "answer": "Because it aggregates choices, calculates transparent financials, holds inventory, and seamlessly handshakes with payment gateways",
    "explanation": "The shopping cart transforms casual catalog browsing into an actionable, legally compliant commercial checkout transaction.",
    "explanationBn": "শপিং কার্ট ক্রেতার পছন্দকৃত পণ্যগুলো সাজিয়ে, সঠিক হিসাব বের করে পেমেন্ট গেটওয়ের সাথে যুক্ত করে কেনাকাটা সম্পন্ন করে।",
    "topic": "The Concept and Functionality of a Virtual Shopping Cart in E-Commerce Websites",
    "difficulty": "Easy",
    "hint": "Because it aggregates choices..."
  }
];

export default questions;
