// topic6_questions.js
// 30 FAQs on "Need for Expression Conversion" – basic to expert.

const questions = [
  {
    question: "Why do we need to convert expressions?",
    shortAnswer: "To transform human‑readable infix expressions into machine‑friendly prefix or postfix forms that are unambiguous and easy to evaluate.",
    explanation: "Computers find it difficult to handle operator precedence and parentheses in infix; conversion simplifies evaluation.",
    hint: "It's about making expressions machine‑friendly.",
    level: "basic",
    codeExample: "Infix: 2 + 3 * 4 → Postfix: 2 3 4 * +",
  },
  {
    question: "What is the main problem with infix notation for computers?",
    shortAnswer: "It requires precedence rules and parentheses to determine the order of evaluation, making parsing more complex.",
    explanation: "Computers prefer a linear, unambiguous order without extra rules.",
    hint: "Think about how you'd evaluate 2+3*4.",
    level: "basic",
    codeExample: "2 + 3 * 4 requires knowing that * has higher precedence.",
  },
  {
    question: "What are the advantages of prefix and postfix notations?",
    shortAnswer: "They eliminate the need for parentheses and precedence rules, and they can be evaluated easily using a stack.",
    explanation: "Evaluation is done in a single left‑to‑right (postfix) or right‑to‑left (prefix) pass without lookahead.",
    hint: "They are stack‑friendly.",
    level: "basic",
    codeExample: "Postfix: 2 3 + 4 * → (2+3)*4",
  },
  {
    question: "What is the difference between prefix and postfix?",
    shortAnswer: "In prefix, the operator comes before the operands; in postfix, the operator comes after the operands.",
    explanation: "Example: Infix A+B → Prefix +AB, Postfix AB+.",
    hint: "Pre‑ vs post‑ position of operator.",
    level: "basic",
    codeExample: "Infix: A + B; Prefix: + A B; Postfix: A B +",
  },
  {
    question: "Why is prefix also called Polish notation?",
    shortAnswer: "It was invented by the Polish logician Jan Łukasiewicz in the 1920s.",
    explanation: "The notation is also called Polish notation, while postfix is called Reverse Polish Notation (RPN).",
    hint: "It's named after its inventor.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "What is Reverse Polish Notation (RPN)?",
    shortAnswer: "It's another name for postfix notation, where operators follow their operands.",
    explanation: "RPN is widely used in stack‑based calculators and some programming languages.",
    hint: "Postfix = RPN.",
    level: "basic",
    codeExample: "2 3 + → 5",
  },
  {
    question: "How do prefix and postfix eliminate ambiguity?",
    shortAnswer: "The order of operators and operands is fixed, so there's only one way to evaluate the expression.",
    explanation: "No precedence or parentheses needed because the evaluation order is determined solely by the positions.",
    hint: "They are self‑contained.",
    level: "intermediate",
    codeExample: "Infix: a + b * c; Prefix: + a * b c; Postfix: a b c * +",
  },
  {
    question: "Where is expression conversion used in practice?",
    shortAnswer: "In compilers, calculators, spreadsheet formula evaluation, and many other systems.",
    explanation: "Any system that needs to evaluate mathematical or logical expressions often converts to a simpler form.",
    hint: "Think about how a calculator works.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What is the Shunting‑yard algorithm?",
    shortAnswer: "It's an algorithm for converting infix expressions to postfix (or prefix) using a stack.",
    explanation: "Developed by Edsger Dijkstra, it's a classic algorithm used in parsing.",
    hint: "It's the standard way to convert infix to postfix.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "Can we evaluate infix directly without conversion?",
    shortAnswer: "Yes, but it requires more complex parsing with precedence and parentheses handling.",
    explanation: "Many compilers build an Abstract Syntax Tree (AST) directly, but conversion simplifies the process.",
    hint: "It's possible but more work.",
    level: "intermediate",
    codeExample: "// Evaluating infix requires two‑pass or stack with precedence",
  },
  {
    question: "What is the benefit of using a stack for evaluation?",
    shortAnswer: "Stacks naturally support the LIFO order needed for postfix and prefix evaluation.",
    explanation: "Operands are pushed, and when an operator appears, the required operands are popped and the result pushed.",
    hint: "Stacks are ideal.",
    level: "basic",
    codeExample: "Postfix: 2 3 + → pop 3, pop 2, add, push 5",
  },
  {
    question: "Is expression conversion only for arithmetic?",
    shortAnswer: "No, it can be used for logical, bitwise, and other operators as well.",
    explanation: "Any operator‑based language can benefit from conversion.",
    hint: "It's general.",
    level: "intermediate",
    codeExample: "Logical: true false && → false",
  },
  {
    question: "What is the role of conversion in compiler design?",
    shortAnswer: "Compilers convert source code (often infix) into intermediate representations like postfix or AST for code generation.",
    explanation: "This simplifies later phases like optimisation and machine code generation.",
    hint: "It's a key step in parsing.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "Can you evaluate postfix with only one stack?",
    shortAnswer: "Yes, one stack is sufficient to store operands during evaluation.",
    explanation: "You push operands, and when you see an operator, pop two operands and push the result.",
    hint: "It's a classic stack algorithm.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What is the complexity of evaluating postfix?",
    shortAnswer: "O(n) time, where n is the number of tokens.",
    explanation: "Each token is processed once, so it's linear.",
    hint: "Very efficient.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "Why is prefix evaluation also stack‑based?",
    shortAnswer: "You can evaluate prefix by scanning from right to left with a stack.",
    explanation: "Operators are applied to the next operands on the stack.",
    hint: "It's symmetric to postfix.",
    level: "intermediate",
    codeExample: "Prefix: + 2 3 → scan right: push 3, push 2, see + → pop 2,3, push 5",
  },
  {
    question: "What are the challenges in converting infix to prefix?",
    shortAnswer: "You need to handle parentheses, operator precedence, and associativity, and often use a stack and reverse the expression.",
    explanation: "The conversion is more involved than infix to postfix.",
    hint: "It's a bit trickier.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "How do you handle unary operators in conversion?",
    shortAnswer: "You need to distinguish unary from binary operators and handle them specially, often by pushing a marker.",
    explanation: "Unary operators like `-` or `!` can appear before an operand.",
    hint: "They require special care.",
    level: "advanced",
    codeExample: "Infix: -a + b → might become prefix: + -a b",
  },
  {
    question: "What is the difference between evaluating prefix and postfix?",
    shortAnswer: "Postfix is evaluated left‑to‑right with a stack; prefix is evaluated right‑to‑left with a stack.",
    explanation: "The scanning direction is reversed.",
    hint: "They are mirror images.",
    level: "intermediate",
    codeExample: "Postfix: 2 3 +; Prefix: + 2 3; both give 5.",
  },
  {
    question: "Can you convert directly from infix to prefix without going through postfix?",
    shortAnswer: "Yes, by reversing the infix expression, swapping parentheses, and then converting to postfix, then reversing.",
    explanation: "This technique is commonly used.",
    hint: "It's a common trick.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "What is the role of the stack in the Shunting‑yard algorithm?",
    shortAnswer: "It holds operators and parentheses until they can be output to the postfix expression.",
    explanation: "The algorithm uses a stack to manage operator precedence and parentheses.",
    hint: "It's the core data structure.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "Is prefix notation used in any programming languages?",
    shortAnswer: "Yes, Lisp dialects use prefix notation (e.g., (+ 2 3)).",
    explanation: "In Lisp, all expressions are prefix, making it uniform and easy to parse.",
    hint: "Lisp is the classic example.",
    level: "intermediate",
    codeExample: "(+ 2 3) → 5",
  },
  {
    question: "Is postfix notation used in any programming languages?",
    shortAnswer: "Some stack‑based languages like Forth and PostScript use postfix.",
    explanation: "These languages are inherently stack‑based.",
    hint: "Forth is an example.",
    level: "intermediate",
    codeExample: "2 3 + . → prints 5",
  },
  {
    question: "What is the advantage of postfix over prefix for evaluation?",
    shortAnswer: "Both are similar, but postfix is more common because it matches the natural left‑to‑right reading of expressions.",
    explanation: "Postfix evaluation is intuitive for human readers when tracing.",
    hint: "It's the more popular choice.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "Can you convert infix to prefix using the same algorithm as infix to postfix?",
    shortAnswer: "Yes, with modifications: reverse the expression, swap parentheses, then apply the postfix conversion and reverse the result.",
    explanation: "This is a standard method.",
    hint: "It's a two‑step process.",
    level: "advanced",
    codeExample: "Not applicable",
  },
  {
    question: "What is the significance of parentheses in conversion?",
    shortAnswer: "They override precedence and must be handled carefully – they are removed in the converted expression.",
    explanation: "Parentheses are only needed in infix; after conversion, the order is explicit.",
    hint: "They are eliminated.",
    level: "intermediate",
    codeExample: "Infix: (A+B)*C → Postfix: A B + C *",
  },
  {
    question: "How does conversion affect the order of evaluation?",
    shortAnswer: "It changes the grouping from implicit (precedence) to explicit (position of operators).",
    explanation: "In postfix, the order of operands and operators directly reflects the evaluation order.",
    hint: "It makes the order clear.",
    level: "intermediate",
    codeExample: "Not applicable",
  },
  {
    question: "Why do calculators often use postfix?",
    shortAnswer: "It's easy to implement with a stack and requires no parentheses or precedence handling.",
    explanation: "RPN calculators are simpler to build and use.",
    hint: "Efficiency.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What is the main drawback of prefix and postfix for humans?",
    shortAnswer: "They are less intuitive and harder to read for complex expressions.",
    explanation: "Humans are trained to read infix, so prefix/postfix can be confusing.",
    hint: "They are machine‑friendly, not human‑friendly.",
    level: "basic",
    codeExample: "Infix: (a+b)*(c-d) vs Postfix: a b + c d - *",
  },
  {
    question: "Do all programming languages use infix?",
    shortAnswer: "No, some use prefix (Lisp) or postfix (Forth), but most mainstream languages use infix.",
    explanation: "Infix is the most common because it's natural for humans.",
    hint: "Think of Python, Java, C++.",
    level: "basic",
    codeExample: "Not applicable",
  },
  {
    question: "What is the difference between expression conversion and expression evaluation?",
    shortAnswer: "Conversion changes the representation (e.g., infix to postfix); evaluation computes the result.",
    explanation: "They are separate steps: first convert, then evaluate.",
    hint: "Conversion is transformation, evaluation is computation.",
    level: "basic",
    codeExample: "Not applicable",
  },
];

export default questions;